### ISSUE TITLE
Add pre-built version in "Releases"

### ISSUE THREAD

**Issue by neuromancer85** [ClusterM/hakchi2#1]
Hi @ClusterM ,
since not everyone would be able to build a C# project from source on their machines, could you please provide a pre-bulit and zipped version of hakchi2 (without the nes-tools, to prevent deletion from antivirus software...) in the Release tab here on GitHub?

Thanks and keep on the good work!

**Comment by sukoshi1507** [comment]
https://we.tl/wu6EuCG3a5 <== i compiled from the latest source and posted here.

**Comment by neuromancer85** [comment]
@sukoshi1507 , your file gets deleted from my antivirus at the end of the download.

**Comment by KingKoopa94** [comment]
Visit http://clusterrr.com/soft/hakchi2.zip for a pre-compiled version.
This is from Cluster's website, and the link is constantly kept up-to-date with the git project.

**Comment by ClusterM** [comment]
I'll upload SFX archive since some versions of WinRAR can corrept file attributes.
You can just disable your antivirus.
