### ISSUE TITLE
Sound lag

### ISSUE THREAD

**Issue by DarthTrotsky** [ClusterM/hakchi2#1000]
Hi!

I hacked the mini snes and got an awful lot of sound lag -- I move to the next game in the menu and after a sec I'll hear the click. I flashed the original kernel but still the lag persists. Isn't that supposed to reset to factory settings? Could it be a TV problem? Thanks!

**Comment by DarthTrotsky** [comment]
Sorry for the newb questions, but I held reset and turned it on and it turned of after a while. When I turned it back on, it was working with no lag again! SO this means my mini snes is no longer at factory settings? I don't think I will hack it again...

**Comment by Drakonas** [comment]
flashing OG kernel will not reset the SNES Classic to factory defaults. You need to uninstall Hakchi from the Kernel -> Uninstall function in the Hakchi menu, then flash OG kernel, then perform a factory reset from the SNES Classic main menu (THIS WILL ERASE ALL SAVES). May I ask how much free space you had left on your SNES when you were hacking it?

**Comment by DarthTrotsky** [comment]
many, many thanks!

it was empty, and I uploaded some 15mb (about six snes games, three GBA and
the retroarch cores)

my best!

**Comment by Drakonas** [comment]
@DarthTrotsky Closing this issue. I would still advise to to an uninstall and factory reset, else you will eventually start having crashes as Hakchi is still present on the system but is just semi-inactive. If you need to backup your saves, install custom kernel, backup the saves with Hakchi, then follow the uninstall procedure I mentioned 3 days ago. Reopen this issue if you ever decide to try Hakchi again and still have trouble after trying what I mentioned.
