### ISSUE TITLE
How can i disable Savestate-Function?

### ISSUE THREAD

**Issue by NDpendent** [ClusterM/hakchi2#1003]
I want to remove the Savestate-Function and Rewind,cause it is not retro in my opinion.
2 mb is to much space anyway!
Is there a way to remove it?

**Comment by Drakonas** [comment]
Why are you asking us to remove an option that is built into the SNES Classic code? This is not something that can be done by Hakchi2. If you don't want to use it then just don't save the savestates when you exit the game. They don't save unless you tell them to. Closing this.
