### ISSUE TITLE
Flashing custom Kernel-Waiting for Device

### ISSUE THREAD

**Issue by HEBURNLL** [ClusterM/hakchi2#1004]
Hi, couldn't find whether this has been posted about or not.

Originally started using Hackchi2 adding games to my NESC with no problems with an older version of windows (Vista?).

Next I got a different computer with Windows 8 on it, and followed the instructions to sync my NESC.

The directions tell me to flash the custom kernel, install the driver, but when I do, it just says, "waiting for device"

All the roms have been loaded into Hackchi 2, but I can't get passed the "waiting for device" part after following the on screen directions.

I don't understand how it worked fine with the old computer, but won't work with the newer one.

Any ideas? Thanks in advance for the help.

**Comment by KMFDManic** [comment]
Usually an issue with virus protection or security protection or firewall.  You also want to be sure you are using the official usb cable that came with the System, as well as a direct USB Connection.

**Comment by HEBURNLL** [comment]
Where can I look to see if it is a virus protection or firewall issue? Is there somewhere I can look to get through it?

**Comment by ReyVGM** [comment]
Install the driver again. If it's already installed, then just do what the screen says (hold reset and power on).

Disable anti virus / firewall and test.

**Comment by Drakonas** [comment]
@HEBURNLL This can also be due to using newer USB 3.0/3.1 ports which have been reported to not work with the Hakchi (S)NESC drivers. You should try different ports or you may not be able to use that computer.

**Comment by Drakonas** [comment]
This should have been asked on Reddit rather than here. This is a place for reporting issues that you know what the problem is, not trying to find a solution. https://www.reddit.com/r/miniSNESmods/ Also closing as it has been 3 months without a response.
