### ISSUE TITLE
my snes wont show anything on the tv and idk what to do please help

### ISSUE THREAD

**Issue by zcraft11** [ClusterM/hakchi2#1005]
i tried to hack my snes and i hooked it back up to the tv but now the light is flashing randomly and nothing shows up on the tv, i just need to know how to reset it to normal, i dont even care about hacking it anymore i just dont want to waste $80... please help!

**Comment by Frank-5** [comment]
You are ok.  Don't worry, it's near impossible to brick these units.  First. This is a bug and issue tracker for hackchi.  Not a general help forum.  There are a lot of places to ask for help of this kind.   That being said, If you have your hackchi2 folder with the dump sub folder with your original kernel then all you have to do is uninstall hackchi and flash the original kernel.

**Comment by Frank-5** [comment]
Go to https://www.reddit.com/r/miniSNESmods/ to read the FAQ and ask questions.  Honesty, you can get this resolved and have a cool hacked system that you can customize to your hearts content.

**Comment by Frank-5** [comment]
Here's the FAQ

**Comment by Frank-5** [comment]
https://www.reddit.com/r/miniSNESmods/comments/73qve2/frequently_asked_questions/

**Comment by Frank-5** [comment]
@Drakonas please close this thread.

**Comment by Drakonas** [comment]
@zcraft11 this is not a personal help line. This issue tracker is meant for requesting features or reporting bugs with the code of Hakchi. Please ask for help on Reddit.
