### ISSUE TITLE
NES Mini running hot, experiencing random reboots

### ISSUE THREAD

**Issue by sitrick2** [ClusterM/hakchi2#1010]
NES Mini running 2.21f kernel. Had no real issues until recently, turned it on to play and the OS self-rebooted as soon as the game select screen loaded. Uninstalled the custom kernel, reloaded the stock kernel, reflashed the most recent kernel. Everything worked fine until about an hour into play, where I got another random reboot mid-game. Noticed the case was warmer than I've ever noticed it getting before. 

I saw another issue about power supply issues in a closed thread, but that problem was marked resolved. Apologies if this is duplication and the fix hasn't made it into a main release yet.

**Comment by Shoothimnow** [comment]
There is a current bug reported in issue #966 that is currently still open regarding the SNESC Overheating.

**Comment by Drakonas** [comment]
Closing this as a duplicate.
