### ISSUE TITLE
[Feature Request:] Stretch Fill option

### ISSUE THREAD

**Issue by Averagewriter** [ClusterM/hakchi2#1012]
I use the SNES and NES Classic on both a CRT TV and on a flatscreen. It would be nice to have the option to stretch the screen, as when on the CRT the image still thinks it's 16:9 and thus is stuck in a small distorted window.

**Comment by Drakonas** [comment]
This is a limitation of the hardware, and is not fixable by software. Sorry but this cannot be fixed. At best we'd be able to squish it to be a square on your screen, but it would be so small in the middle of the screen that it would be unplayable. You can however, manipulate the output with Retroarch to possible fit your needs. But Canoe and base games are a no go.

**Comment by Averagewriter** [comment]
I completely disagree, and your comment was very unhelpful. If you aren't prepared to contribute in a productive way then you should refrain from commenting, please.

**Comment by Shoothimnow** [comment]
@Averagewriter, if you want to personally attack a **Collaborator**, be my guest.

But if you feel that he is in error, please write this code for us =D

**Comment by Drakonas** [comment]
@Averagewriter the output on the SNES is inherently widescreen. There is no way to change a widescreen signal to 4:3 ratio with a software hack. The device's hardware has to support the signal.
