### ISSUE TITLE
Request for info on building kernel modules from source

### ISSUE THREAD

**Issue by ZakDanger** [ClusterM/hakchi2#1013]
Can some info please be added on how to build kernel modules for S/NES mini from sourcecode?

I have tried building the clovercon source included with hakchi2 but the resultant kernel module has vermagic that does not match the original. I think this is causing it to not be able to be loaded.

I tried using the open source packs provided by Nintendo for NES, but I think my generated config file is incorrect. It shows "ARMv7 p2v8" in vermagic insted of just "ARMv7".

**Comment by Shoothimnow** [comment]
Is Hakchi2 providing an issue in this situation (as this is the Hakchi2 issues board).

It looks like you are looking for a how-to guide, which is better suited for the reddit https://www.reddit.com/r/miniSNESmods/ page

**Comment by Drakonas** [comment]
Please ask for help on places like Reddit, not on an issue request. There are many that can help you there, and I am not aware of how to do it.
