### ISSUE TITLE
Retroarch weird issue (can't boot normally anymore)

### ISSUE THREAD

**Issue by kagan1416** [ClusterM/hakchi2#1015]
Hey, I encountered a very strange issue. I flashed my snes classic mini with hakchi2, added some games and everything worked as intended. Then I installed retroarch to play games like terranigma. Still no problems. I can shutdown, reboot my snes classic mini and play whatever I want as intended. Then I altered an option in retroarch but I can't remember what exactly. Anyway it crashed instantly and led to a huge issue. After that I was not be able to reboot my snes anymore properly. It flashes and you can hear menu-sound for a fraction of a second and then nothing happens anymore. There is only one possibility to boot my system correctly. I have to press the same combination to enter retroarch menu (L, R, Start, Select) multiple times while booting! It sounds weird but I'm not kidding. After reaching the main menu it works perfectly fine as far as I can tell. Of course I flashed back to the original state and yes it helps but I need retroarch for some games. Maybe retroarch saved my faulty config before crash? Is there a way to delete every single file which is connected to retroarch? Did anyone else encounter this issue? Thanks a lot!

**Comment by ReyVGM** [comment]
Uninstall retroarch, install again.

**Comment by kagan1416** [comment]
Does not work. Issue persists. The only solution currently is to uninstall retroarch completely

**Comment by madmonkey1907** [comment]
weird. there is a 'dump nandc' option in hakchi2. create a dump when the problem is present and send it to me and/or cluster on reddit or twitter

**Comment by kagan1416** [comment]
Ok thanks. I will send it later to you

**Comment by Drakonas** [comment]
This should have been asked on Reddit rather than here. This is a place for reporting issues that you know what the problem is, not trying to find a solution. https://www.reddit.com/r/miniSNESmods/ Also closing as it has been 3 months without a response.
