### ISSUE TITLE
Boot loop

### ISSUE THREAD

**Issue by elierodrigue** [ClusterM/hakchi2#102]
When flashing with current version, Nes classic goes into a boot loop. 
It does it while flashing too.. it cant be turned off, you need to unplug it, however holding reset while in the boot loop will fire recovery mode and flashing can continue.

**Comment by B9KnM8UqQ2W2Vwk7uvZ7** [comment]
I had a similar issue art first.

Where are you putting the **hakchi2** folder? Have you tried putting it in the root of C: and making sure that it's not inside any other folder? If it's not there already try it again after copying the **hakchi2** file and all it's contents to C:

Good luck.

**Comment by sanjay900** [comment]
Im getting bootloops even when its on the root of the c drive.

**Comment by B9KnM8UqQ2W2Vwk7uvZ7** [comment]
Are you also unplugging the USB cable when it tells you to rather than just switching it off while holding the Select button?

**Comment by elierodrigue** [comment]
at first i tried unplugging, the thing is that it never goes really off.

**Comment by elierodrigue** [comment]
Attached is the debug out from the kernel flash log.

You can see that there's :
Exception thrown: 'MadWizard.WinUSBNet.API.APIException' in hakchi.exe
Exception thrown: 'MadWizard.WinUSBNet.USBException' in hakchi.exe

And : Exception thrown: 'com.clusterrr.FelLib.FelParseException' in hakchi.exe
[KernelFlashLog.txt](https://github.com/ClusterM/hakchi2/files/784681/KernelFlashLog.txt)

**Comment by sanjay900** [comment]
I dont get these errors.

**Comment by IeanD** [comment]
I am absolutely experiencing this problem. The system bootloops upon installing a custom kernel, everytime. Tried rebuilding haxchi2, changing directory to C:\, all of it. No dice.

**Comment by sanjay900** [comment]
I still have this problem, has it been solved for anyone else?

**Comment by ClusterM** [comment]
"current version" - 2.11 or 2.12?

**Comment by sanjay900** [comment]
Latest commit, 2.12

**Comment by sanjay900** [comment]
Im getting it with https://github.com/ClusterM/hakchi2/commit/a6b95dcc0f3582558e4c918069b337248b448675

**Comment by sanjay900** [comment]
The problem has fixed itself with 2.12 release, thanks!

**Comment by trislett** [comment]
I had the same error with the latest commit. The latest release fixes it for me as well. We must have been building it wrong...

**Comment by sanjay900** [comment]
Unless its something weird related to debug vs release?

**Comment by trislett** [comment]
I guess it is possible. I only tried the release build. I thought it may be something essential that was in the git ignore.

**Comment by ClusterM** [comment]
It can be related to file attributes.
