### ISSUE TITLE
trouble importing GBA save states

### ISSUE THREAD

**Issue by DiseasedMonkey** [ClusterM/hakchi2#1021]
I'm having no success importing a save state for advance wars 2. It requires a 68kb file and all I can find anywhere is 64k files. Anyone have a work around or a link to a save states that will work?

Thanks

**Comment by ReyVGM** [comment]
This has nothing to do with hakchi, this is a question for the retroarch forums.

**Comment by Drakonas** [comment]
This needs to be asked on a forums or on the Nintendo [SNES Mini Mods](https://www.reddit.com/r/miniSNESmods/) subreddit. This tracker is for reporting bugs or requesting features, not being a personal help line.
