### ISSUE TITLE
"Invalid Kernel Size"

### ISSUE THREAD

**Issue by Pito23** [ClusterM/hakchi2#1023]
Hi,
when i'm trying to load some Kyland K core mods, hakchi2 (latest versione and rev) give me this message... on NESM and SNESM both... i noticed that some cores i want to load are very big in mb size terms... maybe that's the reason?? Any idea?

**Comment by Drakonas** [comment]
... Why are you reporting to someone that didn't make those mods? Report those to him not us. Cluster has nothing to do with Kyland K's mods. Closing this.
