### ISSUE TITLE
dead NES

### ISSUE THREAD

**Issue by Cadymas** [ClusterM/hakchi2#1024]
Morning, 

I am new to this and I followed the instructions and now my NES is only a black screen. I have tried it a few times to repeat the install and still the same result. Any help would be appreciated before the wife kills me for taking away her Zelda game.

**Comment by Shoothimnow** [comment]
For issues that @ClusterM has no control over (you installing incorrectly), please use https://www.reddit.com/r/miniSNESmods/ to ask questions.

This is the issues board for programmers to fix problems that people find.  Sorry, and thank you.

**Comment by Drakonas** [comment]
Be aware @Cadymas it is practically impossible to brick the SNES Classic or hurt the built in games as the entire NAND is ready only. The kernel is all that is needed for the hack, and can always be reset using the Hakchi2 tool, so there is literally no way to hurt the SNES Classic. Many have claimed they bricked their SNES Classics but all that is usually needed is an Uninstall from the Hakchi menu, flashing OG kernel, and flashing the custom kernel again, and going from there. This will not affect saves.
