### ISSUE TITLE
Mario's Early Years - Fun with Numbers (USA) cannot be added to Hakchi2

### ISSUE THREAD

**Issue by rhester72** [ClusterM/hakchi2#1025]
The following ROM:

Mario's Early Years - Fun with Numbers (USA).sfc

with md5sum:

d097b8f2871522c7c1d2bbd18e7c9ad4

fails LoROM/HiROM detection in Hakchi2 despite being a valid image per ucon64:

    uCON64 2.0.3 Win32 (MinGW) 1999-2017
    Uses code from various people. See 'developers.html' for more!
    This may be freely redistributed under the terms of the GNU Public License
    
    Mario's Early Years - Fun with Numbers (USA).sfc
    
    Multi Game Doctor (2)/Multi Game Hunter/MGH
    
    0000ffb0  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ................
    0000ffc0  4d 45 59 20  46 75 6e 20  77 69 74 68  20 4e 75 6d  MEY Fun with Num
    0000ffd0  62 65 72 73  20 31 00 0a  00 01 5a 00  a6 2c 59 d3  bers 1....Z..,Y.
    
    Super Nintendo Entertainment System/SNES/Super Famicom
    MEY Fun with Numbers
    Mindscape/Red Orb Entertainment
    U.S.A.
    1048576 Bytes (8.0000 Mb)
    
    Padded: No
    Interleaved/Swapped: No
    Backup unit/emulator header: No
    HiROM: Yes
    Internal size: 8 Mb
    ROM type: (0) ROM
    ROM speed: 120 ns (FastROM)
    SRAM: No
    Version: 1.0
    Checksum: OK, 0xd359 (calculated) == 0xd359 (internal)
    Inverse checksum: OK, 0x2ca6 (calculated) == 0x2ca6 (internal)
    Checksum (CRC32): 0x8c0c37f4

It is indeed HiROM, and if you hack the detection code in Hakchi2 to default to HiROM instead of erroring out when detection fails, it will add normally and convert to SFROM properly without issue (and plays fine on the SNES Classic with the default preset ID).

This is the only US SNES ROM I am aware of that fails detection.

**Comment by ClusterM** [comment]
Fixed.
