### ISSUE TITLE
Folder structure UI does not follow console type

### ISSUE THREAD

**Issue by rhester72** [ClusterM/hakchi2#1026]
If managing, for example, NES and SNES from the same Hakchi2 instance, switching between them via Settings/Console type works, but the specific setting for Pages/folder structure (FoldersMode and FoldersModeSnes in config.ini) is read but doesn't change in the UI.

Steps to reproduce:

- Set up Hakchi2 for both NES and SNES
- Set NES to custom folder structure (99), leave SNES at default/auto (3)
- Switch between the two console types and observe that the folder structure selection is respected but the checkbox doesn't move under Settings

**Comment by Drakonas** [comment]
If you are using two different consoles, regardless of what they are, it is recommended to use two separate Hakchi folders entirely with the portable version. Hakchi is intended for use with one console at a time.

So, use two separate folders if you want the easiest setup.

Still I will keep this issue open if @ClusterM ever plans to address this.

**Comment by rhester72** [comment]
Actually, that's pretty inaccurate.

It's true that you actually require two separate Hakchi folders if you have two or more consoles of the same type - but Hakchi was clearly and explicitly designed to be used in a single instance with multiple console types.

Besides just clearly seeing your games list change when you switch types, looking at the actual code (ConfigIni.cs is where the action is) makes it clear that the UI was explicitly designed with this case in mind.  If you aren't adept at code, you can see it just as easily in config\config.ini, where each of the relevant variables are split out by console type.  There's also the difference in naming conventions for the kernel dumps, the games folders, etc., etc., etc. - this was not by accident.

This is very much a bug and not oversight, but to be honest I've had trouble figuring out what the bug actually is.  The switch in ConfigIni should automatically select the correct FoldersMode based on ConsoleType...which it reliably does in all cases and for all checkboxes in SyncConsoleType *except* FolderMode.

Anyway...I've read "conventional wisdom" many times to keep them separate, and I find it wasteful and against the actual design of the application...you just weren't meant to do that.  You certainly can if you like, but I'd personally prefer to avoid the pains and pitfalls of dual maintenance.

**Comment by Drakonas** [comment]
I'm not exactly sure why you are complaining when I added the "bug" label and mentioned Cluster on this issue.

**Comment by rhester72** [comment]
I'm not complaining, I'm educating, because you obviously didn't know the things I just pointed out.

Well, that, and comments like "Still I will keep this issue open if @ClusterM ever plans to address this." are not helpful.  He and I are in touch on a regular basis - I'll trust him to decide if a bug is legitimate or not.

**Comment by Drakonas** [comment]
Sorry I have had a lot of pissy people on this issue tracker. I see that you were not angry now. I apologize. I do rarely mention ClusterM though, so I did see it as an actual bug.. I never believed it wasn't, so you know. :)

**Comment by rhester72** [comment]
*laughs*  No worries.  I'm just as annoyed as you are that people use the tracker for basic support requests.

**Comment by Drakonas** [comment]
Thanks. haha

**Comment by ClusterM** [comment]
Fixed. Thank you!
