### ISSUE TITLE
Save States not working SNES hakchi 2.21f

### ISSUE THREAD

**Issue by tharock1982** [ClusterM/hakchi2#1027]
Hi, I had no problem modding my SNES and have 55 games loaded on it.  It seems that the Save States don't work and disappear if I turn the SNES off.  Is there something I may have missed during the Hakchi process?

**Comment by Drakonas** [comment]
Have you used older versions of hakchi? You may need a fresh factory reset. Try to backup your savestates if you need to with Hakchi's save state manager, then perform an uninstall with the Kernel -> Uninstall function in Hakchi, then flash OG kernel (making sure you get no MD5 checksum errors on that), then perform a factory reset on your actual SNES by going to the options menu on your SNESC (this is the most important step and removes residual files from old/bad Hakchi installs), then flash custom kernel again. You can restore your saves after if you need to.

**Comment by bslenul** [comment]
Are you sure you're not confusing suspend point and save state?
-Suspend points are created when you hit the reset button but are temporary, if you change folder or if you turn off your console they're gone.
-Save states are when you actually save your suspend points, you have to press down to select the suspend point then chose a slot and finally press Y to save (or hold Y to overwrite).

My question may seems stupid but I already saw people confusing the 2 on reddit, so I ask just to be sure :)

**Comment by tharock1982** [comment]
My suspend points weren’t saving when I put them into a slot as they would disappear after a shutdown. I reflagged and all is good now. Thank you guys for your replies.

**Comment by war3zlod3r** [comment]
I had a similar issue recently, my suspend points would just launch the game without loading the point, I reset and reinstalled hackchi and restored the suspend points using the save state manager and that got it working again however if I use retroarch save states they work until I exit the game and then if I go back in are gone, any ideas why this would be happening or how to fix?

**Comment by Damachaman** [comment]
I realize it's 7 years later, but this fix still works. I did factory reset through Hakchi, then factory reset on the nes mini (I probably didn't need to) and loaded the hakchi kernel again. 

My files were all on a USB flash drive used with an OTG cable and I didn't need to change anything or backup the save states. All save states started loading again after the wipe/reflash.
