### ISSUE TITLE
Many Kanji missing from Extended font

### ISSUE THREAD

**Issue by TzakShrike** [ClusterM/hakchi2#1030]
Many Kanji are missing from the Extended font. I assume this is in part because the number of codepoints is limited. This is actually much more serious than it sounds because:
1. Some of the characters used in hakchi2's Japanese translation aren't actually in the font. Particularly when choosing to use folders, the "More games..." folder's title is set to "その他のゲーム..." (as specified in FoldersManagerForm.ja-JP.resx), this looks and sounds fine in hakchi2, but on the console it appears as そののゲーム... as 他 is not in the font. (Additionally, その他 sounds weird in this context, it should simply be 他, and ... looks like bad communication between coder and translator, should be … (U+2026; not rendered correctly here, should be in the center of the line like・・・. I suggest using ほかのゲーム・・・ as it currently renders really well in hakchi and on hardware with no issues)). Worse, there is no way to customise the "Back" folder which is (probably?) defined here as 戻る. Good Japanese, except 戻 isn't in the font so it just says る. The quick fix would be to change it to もどる.
2. Many of the kanji in the titles of the in-built games are not in the extended font, causing at least 5 of the in-built games' names to be mangled.
聖剣伝説 > 剣伝説
超魔界村 > 魔界村
ゼルダの伝説　神々のトライフォース > ゼルダの伝説　々のトライフォース
ファイアーエムブレム　紋章の謎 > ファイアーエムブレム　の謎
がんばれゴエモン　ゆき姫救出絵巻 > がんばれゴエモン　ゆき

**Comment by TzakShrike** [comment]
By the way, I was digging around because I thought I would be able to modify the font myself, as a HMOD for example, but I cannot for the life of me figure out what format the fnt file is in.
Still, I'd love to add to this myself and send it back upstream... there are only so many Super Famicom games after all, so the number of Kanji I'd have to do would be limited by that.

**Comment by TzakShrike** [comment]
Actually the "More Games" and "Back" are defined in Properties/Resources.ja-JP.resx

```
  <data name="FolderNameBack">
    <value>戻る</value>
  </data>
  <data name="FolderNameMoreGames">
    <value>その他のゲーム...</value>
  </data>
```

I guess that means I can change my ones by myself:
```
  <data name="FolderNameBack">
    <value>もどる</value>
  </data>
  <data name="FolderNameMoreGames">
    <value>ほかのゲーム・・・</value>
  </data>
```

**Comment by ClusterM** [comment]
There are too many characters in Kanji. Seems like I need to include only required characters somehow.
