### ISSUE TITLE
SNES Classic No sound after adding games :(

### ISSUE THREAD

**Issue by decreebass** [ClusterM/hakchi2#1031]
I've done a bit of Googling and I've seen this has been an occasional issue with seemingly intermittently positive results - but I've added a bunch of games with artwork but now there's absolutely no sound. I've done a system reset, reloaded the original kernel, re-added the games, etc etc but nothing's working. The system and games work fine, there's just no sound. My TV is not muted lol. Is there a fix for this? It seems even factory resetting doesn't bring sound back. Thanks in advance for your help. Windows 10 and Hakchi 2.21, FYI :)

**Comment by decreebass** [comment]
Nevermind. Sorry. Just tried turning my TV off and then on again. I have NO idea why this should have worked, but it did. Apologies, everyone.

**Comment by Frank-5** [comment]
Our Sony Bravia TV does this a lot with our Roku using HDMI. Did this with the SNES classic as well. Must be something about audio over HDMI on this particular brand. Our Samsing and LG don't have this problem.

**Comment by decreebass** [comment]
Weird. This is an LG TV, but the SNES is hooked up through a 3rd party HDMI switcher. The switcher itself can be wonky at times, so I'm not surprised that the TV is having issues. Oh well. Off and on works :)
