### ISSUE TITLE
Music Hack still isn't working.....

### ISSUE THREAD

**Issue by brothan323** [ClusterM/hakchi2#1034]
Hello. Installing the music hack just removes the music from the main menu. Replacing it with any wav file doesn't help, just removing the music_hack.hmod solves the problem.

The wav file I have is a signed 16-bit pcm. I cannot figure out WHY the snes mini refuses to play any wav file.

**Comment by brothan323** [comment]
Can anyone send me a link to a wav file that they use and that you know works?

**Comment by Frank-5** [comment]
Here's one that should work:
https://drive.google.com/file/d/0B5mdSsdO8iFScXJJamx2ZzNaZEk/view

**Comment by Frank-5** [comment]
And the discussion thread on Reddit:
https://www.reddit.com/r/miniSNESmods/comments/75nusx/i_replaced_my_menu_music_with_bgm_2_from_mario/

**Comment by Frank-5** [comment]
Another wav file that should work:
https://drive.google.com/file/d/0Bzpa1QB9mHonMVRITTlqcmUtcWs/view

**Comment by Frank-5** [comment]
I think unsigned 16bit PCM little endian at 44.1kHz is he right format

**Comment by Frank-5** [comment]
Anyway, it would be nice to have the "official" answer from the developer instead.of having to experiment and speculate

**Comment by brothan323** [comment]
OOOOOOOOOOO. LMAo wow.  Alright, I got it working.

PLEASE CLUSTER, for the love of god, put this in the readme for the music_hack.hmod - 

To use this mod correctly, you need to replace the music file inside the user mods -> music_hack.hmod folder first THEN install the music_hack.hmod.

 I kept replacing the wav file then just syncing to the snes mini(like with the busybox fix)

**Comment by brothan323** [comment]
And thanks for the help, Frank.

**Comment by Frank-5** [comment]
No prob, glad you got it working!!

**Comment by Frank-5** [comment]
And yes, you gotta put the  .wav file in the music hack folder first.  Then install the hmod!  :-)

**Comment by Frank-5** [comment]
I'm working on a hmod that allows you to change the other menu sounds as well.  Trying to make it as user friendly as possible.  That's the tough part.  Doing it manually is pretty easy.

**Comment by brothan323** [comment]
Where are the menu sounds located?

**Comment by Frank-5** [comment]
They are in permanent memory just like the music files.  You have to overmount the writable folders with the custom menu sounds similar to the way the hmod works fir the music hack.  Look at the .hmod files and see what is being done.  Basically a script.  There is a very good tutorial on how to create your own hmods

**Comment by Frank-5** [comment]
https://github.com/ClusterM/hakchi2/wiki/Modifications-and-modules-guide

**Comment by Frank-5** [comment]
This is a very good intro to creating your own mods.  If you are familiar with Linux and bash scripts you should have no prob understanding.  Very fine work here I must say.  ClusterM, Madmonkey, etc are some very good coders!

**Comment by Frank-5** [comment]
I made a PDF of this guide for easy offline access.  This SNES classic is a pretty fun machine.  Almost as cool as my Raspi3 running Retropie. Lol.

**Comment by Frank-5** [comment]
Anyway we should prolly continue this on reddit lest the github  gods get angry. Lol. This area is really just for issues, bugs, feature requests relating to hakchi and not for general help.  @ClusterM has enough to look at without having to sort through help questions.   Oh, if you get a chance donate some $$ to him on PayPal.  This tool is worth a lot!!
