### ISSUE TITLE
Driver Install Error

### ISSUE THREAD

**Issue by TSCreed** [ClusterM/hakchi2#1035]
I downloaded HackChi2 so I could move some ROMS to my SNES Classic and I've followed the steps leading up to installing the driver if it's my first time through. When I went to do this it asked for permission to install nesmini_driver and when I accepted it a DOS Box popped up with the error "NES Mini not found, sorry. Press Enter to exit this driver installer" and it closed.

I checked the file list on GitHub and downloaded the .exe itself to run from the local folder and again, no luck. This pretty much has stopped me stone cold so any help rectifying this would be appreciated.

**Comment by ghost** [comment]
Are you using a 2.0 USB port to connect your SNES Classic to your PC? Some people using a 3.0 USB port have reported connectivity issues.

For example, see Issue #920

**Comment by gBaH0JI9I** [comment]
@TSCreed 
Are you Win x64 owner?
If so, you’ll need to disable driver signature enforcement.
For example use this FAQ https://www.howtogeek.com/167723/how-to-disable-driver-signature-verification-on-64-bit-windows-8.1-so-that-you-can-install-unsigned-drivers/

**Comment by TSCreed** [comment]
Should I have the SNES plugged in when I download the Driver? I might have
misunderstood, I thought the driver was being installed into the Computer
and not the SNES. If that's the case I apologize and will reply again once
I try doing it that way. I fear I was being overly cautious doing this
since I don't want to ruin something so I left it unplugged till after I
did that. Also, the video was sort of unclear when to plug it in.

**Comment by ghost** [comment]
Turn off Driver Signature Enforcement if you need to. Literally follow the instructions Hakchi gives you on screen. Before you try to stuff your SNES with roms you should start at creating a backup of the Kernel, I think that's the first step anyway.

If you can dump your kernel and/or install the custom kernel then the driver is installed and you're ready to go.

**Comment by TSCreed** [comment]
It worked properly when I had it plugged in. I was just mistaken in
thinking it was downloading a driver to the Computer, once I understood
where the driver was going; everything worked great. :)

Thanks for he help and thanks for an amazing product. :)

**Comment by ghost** [comment]
Glad you got it to work!

If your problem has been resolved, please close this issue. Thanks!

**Comment by todder14** [comment]
I cant fix my hack.
I tried everything. currently when I plug in my snes to TV I get a black screen that says enter password.
when I try to add games on the hack it says install drivers and it sends me to the black screen that asks me to exit driver installation. 
I'm using windows 10. I have tried everything.
please help.
at least get it working as normal would be good enough
