### ISSUE TITLE
I Search an NAND for SNES mini

### ISSUE THREAD

**Issue by Gentlemen1988** [ClusterM/hakchi2#1036]
Hello every Body i need a German NAND for SNES because the actually NAND are English and i am German i hope anybody can help

**Comment by ghost** [comment]
The settings menu contains an option to change the language. I don't know if that helps. It's an EU model?

**Comment by Shoothimnow** [comment]
if you are searching for an answer for something, please use: https://www.reddit.com/r/miniSNESmods/

Otherwise, for this issue board, can ClusterM **_program a fix_** for your bug?

**Comment by Drakonas** [comment]
This is not the place to ask for copyrighted content, as it is against TOS of Github and Nintendo. Closing.
