### ISSUE TITLE
[Feature Request] Transfer saves from one SNES Classic to Another

### ISSUE THREAD

**Issue by markched** [ClusterM/hakchi2#1039]
Hi,  I don't know if this is a feature currently or not.  
My current set up
- two classics in two different locations (home and office)
- hakchi2 located on "OneDrive" so the program is the same no matter where I am

What I'd like to do:
If I play 10 minutes in the office and I'd like to continue from where I left off at home, how can I do that? 

Sorry if this is already a feature.  If it is, could someone explain how it is done.

**Comment by gBaH0JI9I** [comment]
![default](https://user-images.githubusercontent.com/13234037/32702906-e24f9538-c7fe-11e7-94a0-43778608280b.png)
Export-Import savestates.

**Comment by markched** [comment]
oh that is too cool! thank you!
