### ISSUE TITLE
RetroArch games do not have any way to save

### ISSUE THREAD

**Issue by bobskorn** [ClusterM/hakchi2#104]
version hakchi v2.12rc3

Games we tested are playing fine.  No issues going into games or game play.  However, when you exit the game it says that there is no save state available.  We tested a few of the RetroArch games and had the same issue with all of them.  Please let me know if there is a fix for this.  Thanks!

**Comment by ajmi982** [comment]
this isnt the case with all RA games. I have save states working for SNES and GENESIS games.  NES (non supported mapper) games and N64 Games save states aren't functioning.

**Comment by ClusterM** [comment]
Please wait for release. And RetroArch mod moved to other repository: https://github.com/ClusterM/retroarch-clover
