### ISSUE TITLE
Cannot Fastforward in Retroarch

### ISSUE THREAD

**Issue by markched** [ClusterM/hakchi2#1040]
I'm not sure if this is even supposed to work or not but I've set up RetroArch shortcuts to rewind and fast forward. Rewind works great but forwarding through what I just wound back does not work. Did not work with the Super NES (Snes9x2010) or the Genesis (genesis_plus_gx)  

I'm using RetroArch: Version 1.0c.

Is this feature even supposed to be able to function? Are we supposed to just be able to rewind? If we're only supposed to be able to rewind it's all good, but if we're supposed to be able to Fast Forward, please someone help.

**Comment by ReyVGM** [comment]
This has nothing to do with hakchi. Go ask in the retroarch forums.

**Comment by markched** [comment]
Where would they be if you don't mind me asking?

**Comment by Shoothimnow** [comment]
https://www.reddit.com/r/miniSNESmods/ would get you in the right direction

**Comment by Drakonas** [comment]
This is a feature to request of Retroarch, and not something Hakchi can address. Closing.
