### ISSUE TITLE
Sega Genesis & Atari

### ISSUE THREAD

**Issue by kwise1** [ClusterM/hakchi2#1043]
Will these ROMS work?

**Comment by ArieKindicator** [comment]
Yes, with retroarch and the required cores installed,

**Comment by JeffSeverino** [comment]
Please close this. This is not an issue. It's already answered in the FAQ.

**Comment by kwise1** [comment]
Sorry, I'm a rookie.  I will look on Youtube about how to do this. Thanks for pointing me in the right direction.

**Comment by Drakonas** [comment]
This needs to be asked on the MiniSNESMods subreddit or on forums. This issue tracker is not a personal help line, but is for reporting bugs.
