### ISSUE TITLE
[Feature Request] Possible solution to C8-error when ending N64 in SNESC

### ISSUE THREAD

**Issue by rednal4451** [ClusterM/hakchi2#1044]
First of all: thank you for your great work, it just works great! Even N64- games seem to be working quite fine, but I systematically get a C8- error when pushing the Reset-button on the SNES Classic to end Nintendo 64-games. Currently, I'm resetting it and turning the system off each time, but I really don’t like to hurt my machine like that…

I think this might be solved when there would be a possibility to avoid the SNESC from collecting a save state and the rewind data (or at least the rewind data, which must be the greatest portion and causes the SNESC to overflow its RAM). I'm not an expert at all, so I don't know if it's feasible or not, but I think there might be two options to implement it:
- A tick-off box in hakchi, so that it can remember it for each game separately
- A button combination to hold (on the controller) when pushing the reset button (on the console)

I look forward to hearing from you.

**Comment by bslenul** [comment]
Until then you can use the shortcut down+select (hold for ~1sec) to reset or select "Quit Retroarch" in the Retroarch menu (start+select), like you I get a C8 error with reset button, but no problem when using these 2 methods!

**Comment by Drakonas** [comment]
This is a problem with the Retroarch core, which Cluster did not make. Closing this, as it has nothing to do with Hakchi. If you must, ***create an issue on his*** [Retroarch issue tracker](https://github.com/ClusterM/retroarch-clover), but be warned. Cluster did not originally port the cores to the (S)NES Minis. It is in a broken state, and probably will be until someone more experienced with Retroarch can get it to be more stable, or until he has time to research the issue.

**Comment by markched** [comment]
Thank you for your assistance.
