### ISSUE TITLE
Super Famicom Mini Error

### ISSUE THREAD

**Issue by Death-by-Diarrhea** [ClusterM/hakchi2#1045]
I get an error when I try to snyc games, everything is good until then.  I dumped original kernel, flash custom kernel, when I sync the games I added that comes up.

The picture link is a screen shot of the error I get.
https://snag.gy/JhYTXO.jpg

**Comment by TzakShrike** [comment]
Did you try a different USB cable and port? Do that first.

**Comment by Death-by-Diarrhea** [comment]
Yes, tried that too.  Didn't work, any other suggestions?  I also did it in a different hakchi folder to the same results.

**Comment by Drakonas** [comment]
@BaconGod Either A: you are putting too many games onto the system, or B: you are getting MD5 checksum errors, which means you have corrupted or deleted your Original kernel dump at some point and need to find a clean one on the internet for your region.

**Comment by Death-by-Diarrhea** [comment]
I've only got 47 games total including the new games.  If I corrupted my original kernel dump shouldn't it mean that if I flash the original kernel, it won't work?  It works normally when I flash the original kernel.

Edit:  Your comment got me thinking, I uninstalled and returned the unit to it's original kernel,  redownloaded Hakchi2 and redid everything.  Now it works fine.  :)
