### ISSUE TITLE
Folders in the settings menu

### ISSUE THREAD

**Issue by CubeMasterV1** [ClusterM/hakchi2#105]
The option for putting games in folders on the NES classic does not come up. Could it be because I have V2.09 instead of V2.11? If so how do I update Hakchi2?

**Comment by baconcow** [comment]
Version 2.09 does not include folder support. Version 2.11+ includes folder support. Honestly, wait for 2.12 as it will likely release in the next day or two.

If you want to update to 2.11, download the proper release. This will create a new hakchi2 folder. If you have already flashed your NESCE with games, move the config.ini and dumped kernel files from the 2.09 hakchi2 folder to their appropriate locations in the 2.11 folder. This will ensure that your new hakchi2 version will know that you have already flashed your NESCE with a modified kernel and not attempt to dump your kernel again.
