### ISSUE TITLE
C8 Error N64 games

### ISSUE THREAD

**Issue by markched** [ClusterM/hakchi2#1051]
Hi Guys,

I get a C8 error when I shut down or reset ONLY when playing N64 games, all other games function properly. 

Hakchi2: 2.21f
Retroarch: 1.0c
Freespace: 70mb
Using glupen64

Is this a common thing to happen with N64 games?

**Comment by ghost** [comment]
This appears to be a problem with Retroarch, not with Hakchi2.

Please refer to issue #1044.

**Comment by ghost** [comment]
Delete (duplicate post)

**Comment by markched** [comment]
Thank you for your assistance.
