### ISSUE TITLE
Still getting c7 error report

### ISSUE THREAD

**Issue by Drifta86** [ClusterM/hakchi2#1053]
I am still getting a few c7 error reports on games such as “rock’n’roll racing” and all of the dragon ball z butoden games 

I have tried multiple file types upon uploading and am unsure as to weither there is a way to make them work or if I have to wait for another hakchi update????

**Comment by gBaH0JI9I** [comment]
Need detailed description of the problem.
“Rock n' Roll Racing” for what console? SNES or SEGA? What emulator you use to run?
Write here the content of the command line for problem game.
I launched myself both versions, SNES and SEGA, everything works fine.

**Comment by debtslave** [comment]
need to install snes mod along with retroarch

**Comment by Drakonas** [comment]
Have you thought to check the compatibility list @Drifta86 ? https://docs.google.com/spreadsheets/d/17RX45oDSm-bYXPOiGz_cIVYt5wtZCYnacbDFciegnRk/edit#gid=2014317767 Those games are incompatible with Canoe, the SNES Classic's built in emulator for running games. You need to use retroarch for these games. Closing this. Ask on the MiniSNESMods subreddit if you need help setting Retroarch up, as this is not a Hakchi issue (and this tracker is for reporting bugs with Hakchi, not Nintendo's Canoe)
