### ISSUE TITLE
[SNES Mini] Bricked...No video

### ISSUE THREAD

**Issue by ThePirat91** [ClusterM/hakchi2#1055]
Hello guys, I have a problem with my SNES Classic...I have just flashed hakchi2 with the latest installer (2.21f) but after have putted in 2 snes more roms, my console was bricked and I have no video any more from hdmi port!!!
I have been trying everything...uninstall custom firmware with original kernel re-upload, reinstall hakchi2, etc...nothing seems working... :(
I can see the console from hakchi2 app and from telnet...only no video output... :(

Unfortunately I don't have the original kernel dump (DOH!!) but i have a friend of mine's one....I think it should be the same, right??
I have tried to uninstall hakchi and re-upload this one but nothing....

What can I do with it??

Thanks

**Comment by Frank-5** [comment]
This is not a personal help line.  Ask on Reddit forums for the SNES Classic.  This is only for bug reporting and feature requests.  
Read the other posts on how to fix your unit.  It is not bricked. Near impossible to brick. If you don't have your original kernel then you have not restored your SNES correctly.  Again. Read the FAQ, ask on help forums, etc. 
please close this issue 
Thanks

**Comment by Frank-5** [comment]
This is not a hackchi bug or issue. This is a user error.  
Thank you for your understanding.

**Comment by Drakonas** [comment]
If you can get an original dump from elsewhere that was dumped from an unhacked SNES Classic, yes that is safe to use. Try to uninstall and flash og kernel with that.

**Comment by ThePirat91** [comment]
>If you can get an original dump from elsewhere that was dumped from an unhacked SNES Classic, yes that is safe to use. Try to uninstall and flash og kernel with that.

Thank you for the answer...but I have already tried with that original dump, like wrote on the first post, and it did not worked...I don't know why
I have tried to uninstall the custom one and flash the original (my friend) dump but w/ no luck  :(
That's the 3rd snes I "hack" with this amazing firmware and that's also the first with this kind of problem!! I followed the same steps the whole times....
I don't know if it's a (possible) hakchi2 issue or my fault.

Have you ever seen something like that?

Thanks again

**Comment by gBaH0JI9I** [comment]
Write the original firmware and:
1. Try another HDMI cable.
2. Try a different TV.
3. Try another HDMI cable on another TV.
4. Try to change the power supply too.
5. If all else fails, get to the store under warranty.
Perhaps the problem is in hardware, do not forget remove hakchi2 from the console first and then write the original firmware.

**Comment by ThePirat91** [comment]
Thanks for the answer...
HDMI cable, TV and power supply I used were always the same...I used them with other two snes (with hakchi2 on board) w/ no problem at all!!
Before hakchi2, the "fault" unit worked good with the very same above tools....
As above, I am not able to understand why the fault snes does allow me to see nothing on video, but it "responds" to any other input, like telnet or rom management via hakchi tool!!

Thanks as usual

**Comment by ghost** [comment]
Did you resolve this issue? My suggestion would be to navigate (blindly) to the factory reset option. You'll need your friends help to do that, he needs to tell you what to press on the controller.

**Comment by ThePirat91** [comment]
> Did you resolve this issue? My suggestion would be to navigate (blindly) to the factory reset option. You'll need your friends help to do that, he needs to tell you what to press on the controller.

Thanks for the answer kb0x...unfortunately I'm still lost on this (very) strange problem...I've tried truly everything but nothing worked...I dunno what's didn't like to this snes....I will try with your guess and let you know

Thanks again guys

**Comment by erroneus0** [comment]
The only problems of this sort I have seen were when someone attempted to use Hakchi with a copy of the NES classic which was not original.  Is it possible that the SNES classic is not original?  Did you buy it from a store or did you get it from any of those 'scalpers' or from some unusual online source?

I have heard of people TRYING to brick their SNES classics using Hakchi2 but were unable to break it beyond recovery.  I wonder if the problem is because this was a unit which was previously hacked on at the hardware level or if something else is the problem such as the power supply.

**Comment by ThePirat91** [comment]
The two items were bought from gamestop, both mine and my friend's one.
Like said before, I have had no problems at all with mine.
I have always used the same USB cable, hdmi cable, tv, pc and power supply.
On my snes no problem with these tools... With my friend's one.. You
know...
Thanks guys

**Comment by ghost** [comment]
I wonder if the GPU on the board is dead since everything else appears to work, it's possibly a coincidence that you thought hacking the console caused this issue. I concur, reset the firmware to the original and take it back.

**Comment by madmonkey1907** [comment]
rm -rf "/var/lib/clover/profiles/0"

**Comment by Frank-5** [comment]
So @ThePirat91, did the above suggestion by madmonkey1907 to remove profile 0 fix this issue?  If so please close this issue. There is waaay too much clutter in this git issue tracker.  As a reminder this is not a general help forum.   It is ONLY for issues and feature requests related to hakchi2.  Go to the SNES / NES mini Reddit forums for general help and user questions.

**Comment by ThePirat91** [comment]
>  It is ONLY for issues and feature requests related to hakchi2. Go to the SNES / NES mini Reddit forums for general help and user questions.

Man, I would not be polemical, but THIS IS an issue with hakchi2, direct or not, so this is why I am here.

After that, sorry for my delay but I was on a business trip....
Coming on topic, nothing worked, @madmonkey1907 suggestion neither. I guess it is like @ghost said: GPU fault and possible coincidence with hakchi2.
I'm thinking to rma it.

I'm closing the ticket
Thanks for your time and help, guys.
