### ISSUE TITLE
All original SNES classic games unplayable after latest update

### ISSUE THREAD

**Issue by Tomtwtwtw** [ClusterM/hakchi2#1056]
Just used the program to add some NES classic games to the system, had already installed Genesis and extra SNES games without issue.  Now everything works fine except the pre-installed SNES games.  They all have placeholders without box art and cause a hard stop error when trying to play.  Anyone else experience the issue?

**Comment by ReyVGM** [comment]
Uninstall hakchi from from SNESC, flash original kernel back, and then rehack again. If same issue still happens, then flash original kernel back and do a factory reset. Then rehack again. If same issue happens, then it's either an issue with your hakchi installation or all those emulators you are adding are causing issues.

**Comment by Tomtwtwtw** [comment]
Thanks for the quick response...will give it a go and report back. Confusing part is that retroarch and cores was already installed with no issue. Only the NES games were added, and with the new version of Hak. Hopefully reloading from scratch all on same version will fix my retro woes.

**Comment by Tomtwtwtw** [comment]
So far so good, thanks again for the help!

**Comment by Shoothimnow** [comment]
Can this issue be closed now?

**Comment by Tomtwtwtw** [comment]
Absolutely, everything has been working flawlessly since reloading.
