### ISSUE TITLE
Can't seem to use an in-game save on Super Mario World

### ISSUE THREAD

**Issue by Goodemen** [ClusterM/hakchi2#1061]
I'm testing out why I can't seem to save games in game that have save game options. So I'm using Super Mario World as my testing game, and after completing one level in the first world I'm not able to even pull up a start menu that would normally give you the option to save and every time I exit the game it won't save my progress. I'm not sure what is causing the issue, I have the latest version of Hakchi2 with the Extra Space, retroarch, and snsx2010 modules installed with 184 snes games taking 165 mbs of space out of the 257mbs. Is anyone else having this issue?

**Comment by ReyVGM** [comment]
Uh dude, the game only saves after beating a castle, ghost house or switch palace. The game has no menu to save whenever you want.

**Comment by Drakonas** [comment]
Why are you creating an issue for in-game help? This is not a Hakchi problem. Super Mario World and many other games never had autosaves along the entire way. Closing.
