### ISSUE TITLE
2.21f - NES Mini - Kernel dumped but the MD5 checksum is unknown.

### ISSUE THREAD

**Issue by Hackcell** [ClusterM/hakchi2#1063]
3d108da211685c428cae71fe422ede7a - from US NES mini purchased in Costa Rica less than2 days ago..

**Comment by Drakonas** [comment]
Nobody else is reported to have that MD5 checksum, and it has been out for over a year. Obviously the person selling that NES Mini had already hacked it at some point. Find a kernel online with a proper MD5. This is not something Hakchi needs to address. Closing.
