### ISSUE TITLE
hakchi2 doesn't recognize SuperNES Classic

### ISSUE THREAD

**Issue by Darklordsidius** [ClusterM/hakchi2#1064]
My classic crashed one day when it tried to do the game demo while system was idle. I rebooted the classic and it acted like it was turned on for the first time, asking for language etc.. I set the settings and it booted to the main menu like normal and all my games were there and they all worked.

When I connected the Classic to the PC to remove and add a couple games, the memory was now 10MB less than before. It went from having 184.6MB to 174MB.  I figured I'd reload the original kernel and start over to get my memory back. It said there was an error at location M5 or something like that, after it loaded the kernel and the green light at bottom left corner would stay red and no matter what I did, it would no longer turn green and recognize my Classic. 

When the Classic is turned on, the PC will make the audio chime that the driver was recognizing the Classic being turned on but hakchi would not see it. 

Even with hakchi not recognizing it, it would still write the kernel and even when the Classic was turned off! The power led on the Classic would turn on when the power was turned off. 

The Classic seems to work fine when hooked up to the TV running the original kernel but since hakchi2 isn't recognizing my Classic, I can't tell how much memory is available for adding games.

I've rebooted windows. I've tried a fresh copy of hakchi2... it will not recognize my Classic.

**Comment by ghost** [comment]
Go to the options / settings on your SNES and run a factory reset, then try it again. It sounds simple and maybe condescending but if you haven't tried it you probably should. Make sure you have your original kernel dump etc safe because that's important.

**Comment by Darklordsidius** [comment]
I've already tried that after I used the uninstall option in hakchi2. It had no effect on the program recognizing my Classic.

I've made multiple backups of my original kernel.

**Comment by Darklordsidius** [comment]
If I try to reinstall the driver for the Super NES Classic, the DOS says "NES mini not found, sorry".

**Comment by ghost** [comment]
Another silly suggestion you've probably tried is trying different USB ports or perhaps a powered USB hub. Yet another silly suggestion is look at the back of your console, give the power cable a little push and wiggle, there's a gap between the port and the casing, so mine turned on, windows saw it but wouldn't connect in Hakchi.

Also are you sure that the power supply is strong enough to power the SNES?

**Comment by Darklordsidius** [comment]
I've tried 3 different USB cables, 2 different USB ports on main PC and 1 USB port on laptop. hakchi will not recognize the Classic mini but when connected to the TV, it works fine.

**Comment by Darklordsidius** [comment]
you had mentioned the kernel dump etc. What is the "etc"?

**Comment by Loafdude** [comment]
hakchi wont recognize your snes when running the original kernel
boot to FEL mode by holding the reset button while turning it on.
Then flash the custom kernel

**Comment by ghost** [comment]
The etc is other things like NAND dumps from the Kernel menu in Hakchi2

**Comment by Darklordsidius** [comment]
Dumping the NAND items is required before first use of hakchi2?

**Comment by ghost** [comment]
No, sorry for confusing you. I simply meant if you've made NAND dumps that you should keep them safe with the kernel dump you've made.

**Comment by Darklordsidius** [comment]
I can't even install hakchi2 on a different PC, it will not recognize the classic to install the drivers

**Comment by ghost** [comment]
Q: My PC can't detect my NES/SNES Mini! Why?

A: First of all, check Device Manager and find you console there. If you can't find it, it's hardware problem, try other cable/port. Otherwise make sure that driver is installed and working correctly. If it's not installed, try to disable Windows driver signature check or try to install driver using Zadig util: http://zadig.akeo.ie/

**Comment by Darklordsidius** [comment]
I have no clue what the issue is/was but with the classic turned off, I unplugged the USB from the PCand I clicked on install driver again then plugged the USB in (for the 20something time) and it installed the driver on this different PC while the classic was powered OFF. I chose to flash custom kernel, it actually flashed the custom kernel this time and it is now capable of storing games, or so it says. I'll upload some games and test it out.

My other 2 PC's would not allow to flash custom kernel, they kept saying to connect and turn on my Classic, when it was.

**Comment by Darklordsidius** [comment]
It seems to be working. I used the same USB cable on all 3 PC's and on 7 separate attempts, the Classic was switched OFF but the power LED would be on and remain on, I could write the original kernel to it even though the power switch was OFF but that is all it would do. I don't know what kind of glitch that is but it tricked the 3rd PC into installing the drivers on the 5th attempt to install the drivers on that particular PC. 

I wish I knew what was wrong with it to cause all this to occur to begin with.

**Comment by Drakonas** [comment]
Some PC's in the last 3-5 years have USB 3.0 ports that don't like the (S)NES Mini drivers. Glad you got it fixed.
