### ISSUE TITLE
Problem with my Mini NES classic [SOLVED]

### ISSUE THREAD

**Issue by MiiverseRewritten** [ClusterM/hakchi2#1067]
Hi everybody i open this post beacause i got a problem with my Mini NES classic.
I wanted to remove hakchi2 on my Mini NES but (yes there a but) i forgot my Mini NES classic kernel dump i remove anyway and i got a warning i click to yes but when i turn on my Mini NES there happening : 
![image](https://user-images.githubusercontent.com/33596896/33035243-bfe64262-ce2a-11e7-8ced-030caa0ea5db.png)

[EDIT : I kwon where come the problem i install the game without game like that : 
![image](https://user-images.githubusercontent.com/33596896/33035319-f83506da-ce2a-11e7-8274-891890945d9d.png) I just need a backup from this folder please !]

[EDIT2: I restore all the games nothing is needed]

**Comment by MiiverseRewritten** [comment]
I wanted to remove and reinstall my game in my Mini NES but there what i dont know what happend plz hzlp !

**Comment by MiiverseRewritten** [comment]
There a photo of the problem 
![image](https://user-images.githubusercontent.com/33596896/33033589-3251261a-ce25-11e7-9d3f-53a016591b22.png)

**Comment by MiiverseRewritten** [comment]
OK I understand all the games missing in the mini nes but please can someone backup all the games in the games folder like the *hakchi2 folder*\games please

**Comment by Drakonas** [comment]
So is this resolved?

**Comment by MiiverseRewritten** [comment]
Yes just the version of hakchi2 have a problem.

**Comment by Shoothimnow** [comment]
@Drakonas was asking if this has been resolved for you to close this issue =P

(as this isn't board isn't a forum, it's an issue tracker that lets ClusterM know what he needs to fix.  137 issues sounds like a lot, but this issue tracker plagued with non-issues or user-specific issues that are not meant for ClusterM to fix [which is what this board is for], and should be placed in https://www.reddit.com/r/miniSNESmods/ instead.)

**Comment by Shoothimnow** [comment]
So because this ticket is still open (again this is not a freaking forum.... its a bug tracker....), is there anything else ClusterM can help code for you.  If not, can you please close this ticket....

**Comment by Shoothimnow** [comment]
Issue/Bug Tracker (not a forum)
Ticket Status: Open
Ticket Name: Problem with my Mini NES classic [SOLVED]

Are you still having a problem?

Is there a reason this isn't closed?
