### ISSUE TITLE
Size useage

### ISSUE THREAD

**Issue by warlockv2** [ClusterM/hakchi2#107]
Any way we can get a way to monitor just how much space usage we have?  especially with 2.12 about to release, is there going to be a way we can tell when we reach the limit with games, nw that we can have game boy, snes etc

**Comment by 1lokolo1** [comment]
In 2.11 when I make tests about RA, I check the size of hakchi2\games folder. Now I check the same folder + \user_mods size but I will be a nice feature to add.

Rgs.

**Comment by warlockv2** [comment]
lol, i was just watching your video on youtube previewing the update,  im sadistic gamer podcast haha,  thats pretty funny, small world

**Comment by ajmi982** [comment]
Good rule of thumb right now is check the size of your temp folder that is created when you upload the new kernel. Want it below ~300mb

**Comment by abijanfar** [comment]
+1 for disk usage monitor!

**Comment by bfluryx1234** [comment]
I can't get past 230mb or so without problems... anyone else able to get much higher?  This is for the US version.  I am wondering if the Japanese/Euro ones have didn't limits due to having I would assume different size screensavers (for the demo reel).
