### ISSUE TITLE
NES/SNES Mini no Sound with AverMedia Capture Card and custom Kernel

### ISSUE THREAD

**Issue by BouFrost** [ClusterM/hakchi2#1070]
When I add the custom kernel, I get no sound  on TV and PC (Capture Card is splitting signal to TV and PC). When I plug the NES/SNES Mini directly to my TV, sound is fine. So, the kernel must change something that the capture card doesn't recognize sound. Is there a fix for that or is this known and will be adressed in a future update?
Thx alot in advance :D

**Comment by Shoothimnow** [comment]
Have you tried a different HDMI cable.  I just hacked a co-workers NES not more than 5 minutes ago and everything is working flawlessly.  Sounds like a user specific issue than a Hakchi2 issue (we are currently on the program Hakchi2 issue board, not an all around forum for general questions).

For issues that hakchi2 is encountering that ClusterM can fix via coding, post here
For questions / inquiries / how-to's / everything else : https://www.reddit.com/r/miniSNESmods/

**Comment by ReyVGM** [comment]
You are supposed to hook up the SNESC to a TV or Monitor, not to a video card. A videocard will not have sound if it doesn't support it.

**Comment by BouFrost** [comment]
>youare supposed to hook up the SNESC to a TV or Monitor, not to a video card. A videocard will not have sound if it doesn't support.

Not a video card, a capture card ...
I have to if i want to capture the gameplay. Directly to TV everything works like normal, but with the CaptureCard in between, there is plain no sound ... not at TV and not at PC.
With standart kernel, the CaptureCard does route the sound to the TV and PC like expected. So it has to have something to do with the kernel.

**Comment by Shoothimnow** [comment]
Sounds like a SNESC problem, and not a Hakchi2 problem, which ClusterM can't fix...  

For issues that hakchi2 is encountering that ClusterM can fix via coding, post here
For questions / inquiries / how-to's / everything else : https://www.reddit.com/r/miniSNESmods/

**Comment by Drakonas** [comment]
This sounds like a limitation of the hardware. The HDMI port on the SNES Classic probably uses HDCP to prevent recording. This is not something that needs to be discussed here.

**Comment by gingerbeardman** [comment]
I understood that the Minis do **not** use HDCP? 

https://youtu.be/0HZmoSHMNg0?t=8m57s

**Comment by iBrokeYourGui** [comment]
Sorry, why it Closed? 
I hve the same problem (v2.30) and not see solution here (

**Comment by gingerbeardman** [comment]
Does it work without hakchi2? @sikilyator

**Comment by iBrokeYourGui** [comment]
@gingerbeardman i have SNES not pаtched - its work perfecctly! 
I try delete hackchi2 from NES but i still have no sound. And patch again to no avail.
This is really a hardware limitation.

**Comment by gingerbeardman** [comment]
@sikilyator maybe NES system software is the problem? Hardware is the same between. Does it work if you run NES firmware on SNES?

**Comment by BouFrost** [comment]
to be clear what i initially wanted to make clear

mini (orig kernel) -> TV = Sound
mini (orig kernel) -> cap card -> TV = Sound
mini (orig kernel) -> cap card -> PC = Sound
mini (hackchi) -> TV = Sound
mini (hackchi) -> cap card -> TV = no Sound
mini (hackchi) -> cap card -> PC = no Sound

so, something in hackchi is bothering the cap card that it won't let the sound come through
its the same for both nes and snes
