### ISSUE TITLE
v2.21f FDS games not working.

### ISSUE THREAD

**Issue by Popp1092** [ClusterM/hakchi2#1071]
So after downloading v2.21f web installer, I tried it out on my Famicom Mini. While testing it, I figured out that all Famicom Disk System Games do not work with this new update. I did a factory reset and got rid of any evidence of hakchi2 on the system and once I reinstalled the new update and all FDS games still won't work. Is anyone else experiencing this or is it just me? Also I installed an older update and the FDS games worked on that older version

**Comment by Shoothimnow** [comment]
For issues that hakchi2 is encountering that ClusterM can fix via coding, post here

For questions / inquiries / how-to's / everything else :  https://www.reddit.com/r/miniSNESmods/

**Comment by gBaH0JI9I** [comment]
FDS games requires bios - disksys.rom in system directory.

**Comment by Drakonas** [comment]
Please see Shoothimnow's post. All inquiries and questions need to be asked on miniSNESmods before being posted here. This is a bug report tracker, not a personal help line.
