### ISSUE TITLE
SNES Modules Adding Not Working

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#1072]
Okay, I have a SNES mini and want to put modules like retroarch so I try to put it, it tells me to hold the reset button and turn on the power switch I tried it but it turns on and when it turns on it does nothing. So when It did not turn off it did nothing. So how can I fix this?

**Comment by ghost** [comment]
I also have the right drivers since I dumped my kernel with it

**Comment by gBaH0JI9I** [comment]
https://github.com/ClusterM/hakchi2/wiki/FAQ

**Comment by Shoothimnow** [comment]
https://www.reddit.com/r/miniSNESmods/

**Comment by Drakonas** [comment]
General questions and inquiries need to be asked on reddit. This is a bug tracker, not a personal help line.
