### ISSUE TITLE
Super Street Fighter II and Super Street Fighter II Turbo Arcade - No sound in the intro sequences

### ISSUE THREAD

**Issue by Pito23** [ClusterM/hakchi2#1073]
Hi,
as i wrote on title.

The games plays well with music and sounds also after coin inserted... but the intros and demos gameplay are mute... any help???

I'm using latest hakchi2 + latest retroarch with command line "cps2"

thx

**Comment by Hackcell** [comment]
go into the game operators menu and enable the attract sounds.

**Comment by djritz0** [comment]
How?

**Comment by Hackcell** [comment]
if you have a wii controller pro, press R2 and that will show the game "BIOS"...
At the end this is not an issue related to the emulator., it's a game configuration thing.

**Comment by Pito23** [comment]
yes i've found the menu with that and many other settings too, but unfortunately they don't keep saved when the game is quitted and restarted.

**Comment by Hackcell** [comment]
are you using mame2003? That may be the reason.

**Comment by Pito23** [comment]
No i'm using fba CPS2... with mame2003 the games doesn't work.

**Comment by Drakonas** [comment]
You need to continue this discussion on [MiniSNESMods subreddit](https://www.reddit.com/r/miniSNESmods/) to get Mame set up properly, as the games are reported working by other users. Closing this as this is not a Hakchi bug obviously.
