### ISSUE TITLE
Save state issue

### ISSUE THREAD

**Issue by X13-A** [ClusterM/hakchi2#1074]
So i'm trying to play a gba pokemon hack but when i create a save state (on the snes menu) and try to load it, instead of loading it, it just restarts the game from the very start like i never played it.

**Comment by ReyVGM** [comment]
This is a retroarch issue, not a hakchi issue.

**Comment by X13-A** [comment]
mb

**Comment by Shoothimnow** [comment]
please post in reddit.com/r/miniSNESmods/
this Hakchi2 issue can most likely be closed.

**Comment by gBaH0JI9I** [comment]
#1076

**Comment by Drakonas** [comment]
This is an issue with Retroarch base code, and not of Cluster's concern. This needs to be discussed on MiniSNESMods subreddit, not here.
