### ISSUE TITLE
Some GBA games dont save (solved)

### ISSUE THREAD

**Issue by fireday2** [ClusterM/hakchi2#1076]
I found two games 
1. Mortal Kombat - Deadly Alliance 
2. Mortal Kombat - Tournament Edition
These games dont save
When i resume save - little time black screen, then game start at the beginning
p.s. sry for my english

**p.p.s I solved problem - just uncheck "compress" at games that dont save**

**Comment by ReyVGM** [comment]
This is a retroarch issue, not a hakchi issue.

**Comment by fireday2** [comment]
thought so, thx
p.s. is there some solution ? (i know, it's off-topic, sry)

**Comment by ReyVGM** [comment]
Ask in the retroarch forums.

**Comment by fireday2** [comment]
I solved problem - just uncheck "compress" at games that dont save

**Comment by Frank-5** [comment]
Thanks for posting the solution.   Can you close this ticket now?

**Comment by Shoothimnow** [comment]
Stating "solved" in the title doesn't close this ticket.  This isn't a forum, it's a bug tracker.  Left open tickets like this (not to mention this was posted in the completely incorrect location) clutter up what really needs fixed....  As @Frank-5 stated, can you please close this ticket now...
