### ISSUE TITLE
"Access to the path '(insert game filename)' is denied" error

### ISSUE THREAD

**Issue by Shawniecom** [ClusterM/hakchi2#1079]
first off, about myself: not much programming experience, although I've modded my psp, gamecube, and nes/snes classic before with no problems. I'm trying out retroarch on the nes classic to try playing some genesis games and I'm using hakchi 2.21f. I put the retroarch folders (games and mods) into the hakchi folder. I put in toe_jam.bin (toejam and earl) into the \games\CLV-H-RARCH\libretro\roms in the hakchi folder like they've explained to do. I synced my games. I think I ended up reflashing the custom kernel for some reason, then I removed the toejam and all the other games thinking it didn't work. after I did that, now everytime I want to flash original or custom flash or sync games it gives me this error: Access to the path 'toe_jam.bin' is denied." the nes works fine otherwise. I can still play the original games, but for some reason I can't add any games or flash original or custom kernels. Is there anyway to remove this filepath that it thinks is still there that is preventing me from modifying anything? I've tried deleting and re-adding hakchi, readding the retroarch folders with the toejam.bin file, and restarting everything. I'm not sure what else can fix it? any suggestions?
![hakchi error](https://user-images.githubusercontent.com/34015550/33254310-b04ebd24-d30d-11e7-9e22-fa3df353958f.jpg)

**Comment by ReyVGM** [comment]
.bin is not a correct Genesis extension. Download the game from a good source. A correct Genesis game will be .md or .smd

**Comment by Shawniecom** [comment]
I understand that the genesis roms are mainly smd, but there are a couple that are .bin, similar to how there are some .fig for snes game roms as well, so I wasn't sure if it would work. regardless, the error pops up when I'm trying to sync or flash the nes kernel and it just cancels what it's doing. Is there a log somewhere that I or someone else can see what's causing this?

**Comment by Shoothimnow** [comment]
I would completely remove all of Hakchi2 (from computer and classic) and start again.  We are not encountering this problem =\

**Comment by Shawniecom** [comment]
I've tried deleting the folder, but that didn't do anything. Does hakchi save any files elsewhere in windows 8? I've tried running the uninstall option in the program and it gives the same error. I've also tried resetting the nes to factory settings in the actual system (while playing it), but that didn't work. I'm also running hakchi as administrator.

**Comment by Shawniecom** [comment]
Ahhhh, I found it! Windows created an error temp folder in the Appdata/local folder. I just searched C: for hakchi and found it and deleted it. Now it's working again.

**Comment by Frank-5** [comment]
So can you close this ticket please??
