### ISSUE TITLE
На snes установил драйвер nes прошу помощи!

### ISSUE THREAD

**Issue by AlienGiger** [ClusterM/hakchi2#1081]
Как ясно из названия по случайному обстоятельству на snes поставил не тот драйвер а именно nesовский и выдал ошибку несовместимости. Что теперь делать БЕЗ ПОНЯТИЯ? При запилки игр пишет установите драйвер если он не установлен, жму установить и консоль показывает что драйвер NES инсталлирован, тут у меня и припекло! Мне нужен же SNES! И теперь игры этой плойки не ставит ни в какую, полоса установки тормозит с самого начала а в окне УСТАНОВИТЕ ЕСЛИ НЕ УСТАНОВЛЕН. Прошу помощи кто знает или сталкивался с проблемой. Может отформатировать и поставить родную прошивку, если да то как? Может как то удалить драйвер или перезаписать, ХЗ я неспециалист в этой области а выкидывать 5 рублей на ветер обидно. Заранее спасибо.

**Comment by gBaH0JI9I** [comment]
Слишком сумбурно все написал. Ты выбрал не тот тип приставки при прошивке или что?
Попробуй полностью удалить все с нее. В хакчи выбери меню: "Ядро" - "Полностью удалиться с NES/SNES."
Затем "Ядро" - "Прошить оригинальное ядро."
После этого зайди в консоль и сбрось ее к заводским установкам через меню.
После всего этого можно шить заново, выбрав верно тип приставки.
Надеюсь хоть дамп оригинальной прошивки сделал?

**Comment by AlienGiger** [comment]
нет дамп не сделал каюсь, так как нигде об этом ни видел инфы.Только после разобрался когда было поздно(

**Comment by gBaH0JI9I** [comment]
Дамп предлагался сделаться автоматом при первой попытке добавить игру даже. Если только не выбрал "не сейчас", но тогда и прошиваться приставка не должна была.
Посмотри в папке с хакчи должна быть папка "dump" а в ней файл "kernel_snes.img"
Может все таки есть там.

**Comment by AlienGiger** [comment]
я стаяил оригинальное ядро но мне кажется что накрутил что то не то и проблема не меняется.
Он просто отказывается менять драйвер пишет что драйвер уставлен именно НЕС.
А где чистый дамп можно найти?

**Comment by AlienGiger** [comment]
и где вообще директория дампа я хз ставил веб установкой поэтому незнаю

**Comment by gBaH0JI9I** [comment]
Прежде чем ставить оригинальное ядро, нужно удалить хакчи, я писал выше последовательность:
1. В хакчи выбери меню: "Ядро" - "Полностью удалиться с NES/SNES."
2. Затем "Ядро" - "Прошить оригинальное ядро."
3. После этого зайди в консоль и сбрось ее к заводским установкам через меню.

Если вэб установкой, то все наcтройки, дампы, моды и т.д. в папке "Мои документы\hakchi2"

**Comment by AlienGiger** [comment]
стой! стой! удолить хачи!
а как я потом выберу меню ""ядро"" если хачи нет?
И как зайти в консоль чтобы сбросить настройки?
я же говорю неселен в этом)

**Comment by gBaH0JI9I** [comment]
Там подразумевалось удалить хакчи с консоли, а не с компьютера.
С компьютера, естественно ничего не нужно удалять.
Запусти Хакчи на компе и пройди три шага, что я написал.

**Comment by AlienGiger** [comment]
файл я нашол. как сбросить к завод настройкам?

**Comment by gBaH0JI9I** [comment]
Три шага прошел нормально, ошибок не было?

К заводским - к телеку приставку подключи и у нее в меню выбери "сброс к заводским".
После последнего шага, у тебя чистая приставка, как только из магазина. Можно будет шить заново, главное тип правильно выбрать.

**Comment by AlienGiger** [comment]
еще нет но ща попробую.

**Comment by AlienGiger** [comment]
попробовал удалил, поставил ядро, сбросил настройки - ошибок не было, но когда стал синхронизировать попросил поставить модифицированое ядро, согласился установилось.
Вылезло окно что готово принимать игры и нажал ок! Еще одно окно создание папок оставил по умолчанию. вылезло еще окно О_о!!! и ползунок закачки игры.В окне - включите консоль и поставьте драйвер если не стоит а ползунок не шелохнется. нажал установить в окошке консоли надпись НЕС МИНИ НОТ ФАУНД! и нажмите ентер все стало на месте. Вот и что делать???
Может дамп битый иза меня я чтото накрутил (((, можешь свой дамп дать.

**Comment by AlienGiger** [comment]
Или где скачать чистый дамп? мне кажется дело в нем что он переписался после установки нес драйвера.

**Comment by gBaH0JI9I** [comment]
Ты не поставил на комп драйвер до сих пор.
Выключи консоль. В заучи выбери прошить модифицированное ядро в меню, когда выскочит окно с просьбой установить драйвер, нажать на консоли reset и не отпуская кнопки, включить консоль, держать ресет до тех пор пока бегунок наикомпе не победит.
У тебя должно выскочить окно об установке неподписанного драйвера, соглашаться.
По окончании в хаски внизу будет видно сколько места на консоли свободного, значит все ОК.

**Comment by gBaH0JI9I** [comment]
И если Винда 64-битная, нужно ее загрузить в режиме пропуска проверки подписи драйверов. Это к гуглу.

**Comment by gBaH0JI9I** [comment]
Ты FAQ в вики по хакчи читал? Там все расписано.

**Comment by AlienGiger** [comment]
если можно чуть подробней а то я не понял ресет вкл 2-3 сек я ж так и делал.
Да Вин 7ка 64-б кокой режим пропуска?
я уже загуглился совсем 3 дня гуглю и ни чего кроме как установить игры не нашел?

**Comment by gBaH0JI9I** [comment]
https://github.com/ClusterM/hakchi2/wiki/FAQ

**Comment by gBaH0JI9I** [comment]
В вин 64 семерке, чтобы поставить неподписанный драйвер:

При включении компа, жмёшь F8 до тех пор пока не выскочит меню выбора загрузки винды. 
Если сначала появится выбор с чего грузится, бывает такое, выбираешь жесткий диск и сразу опять быстро F8.
Вообщем нужно меню выбора способа загрузки операционки.
В этом меню выбираешь «Ртключить обязательную проверку подписи драйверов». Грузишься в этом режиме и делаешь все по инструкции. Теперь драйвер станет.
Это защита винды не даёт поставить в систему неподписанный драйвер. 

В консоль драйвер не ставится, не путай, туда шьётся модифицированная прошивка.

**Comment by AlienGiger** [comment]
но вин не оригинал как он может делать проверку драйверов? аааа сори загрузил наверное)

**Comment by AlienGiger** [comment]
а в faq нет ничего такого(

**Comment by AlienGiger** [comment]
будем пробывать !

**Comment by AlienGiger** [comment]
все сделал как сказал - консольное окно и полоса установки игры опять стоит на месте. Пробывал зажать, включить и держать долго но не чего все на месте как стояло так и стоит. 
надпись в окне хачи - 1 подключите нес/снес мини к компу по юсби
2 включиее
3 установите драйвер, если он еще не установлен
жму установить.
надпись в окне консоли- найден юсби девайс: "НЕС МИНИ" instailling wdi driver with<nesmini.inf> at <usb_driver>
Press enter to exit this driver instailler
жму ентер но ничего не происходит все также стаит на месте О.О
руки ложатся!

**Comment by gBaH0JI9I** [comment]
Блин.
Вобщем, если хочешь, могу подключиться удаленно через Teamviewer или AmmyyAdmin на выбор и глянуть что там у тебя.
Только предварительно загрузись в винду в режиме "Отмены проверки подписи драйверов", чтобы уже все посмотреть.

**Comment by AlienGiger** [comment]
ок чуть подожди

**Comment by AlienGiger** [comment]
336 137 221
6u31ek
вот тока я владеть им не гугу

**Comment by gBaH0JI9I** [comment]
Проблема решена, думаю тикет можно закрывать.

Problem solved, I think the ticket can be closed.

**Comment by komikadze** [comment]
Привет. Подскажите пожалуйста  как решили проблему!!!!!

**Comment by EvgeniyShevelev** [comment]
Добрый день. У топикстартера стоит драйвер, консоль рабочая, просто надо подключать USB шнурок в тот же разъём, куда и была подключена приставка в первый раз, при установке дров.
