### ISSUE TITLE
Getting error message when trying to install web installer version of most recent Hakchi

### ISSUE THREAD

**Issue by travelinphan** [ClusterM/hakchi2#1082]
Anyone else getting this?  Been happening all last night and still today

**Comment by Frank-5** [comment]
Did you not read post #1080 right below?  This question has already been answered.  Read the posts before asking questions please

**Comment by travelinphan** [comment]
Um ok.  Really sorry

**Comment by Shoothimnow** [comment]
Site is under maintenance.  This issue can be closed
