### ISSUE TITLE
How to move save states from nes mini to snes mini?

### ISSUE THREAD

**Issue by mlabarca** [ClusterM/hakchi2#1083]
I tried exporting a save state from nes mini to snes mini. Both are using custom rom and the same rom works fine, but the problem is that it seems hakchi is assigning different ids to the same rom game, and importing the save state fails. I've tried opening the uncompressed clvs, editing the id with just notepad, saving it, compressing again, but importing fails due to some write error. Do I have to edit the uncompressed clvs with a hex editor just for this or did I do something else wrong?

**Comment by Frank-5** [comment]
Use notepad++

**Comment by Shoothimnow** [comment]
You are posting in the wrong forum (as this is not even a forum, this is a bug tracker....)

https://www.reddit.com/r/miniSNESmods/

Please close this issue and post in the appropriate location
