### ISSUE TITLE
Need help recreating the password mod.

### ISSUE THREAD

**Issue by NodeTG** [ClusterM/hakchi2#1084]
Not sure if this is the right place (new to github) but I am having trouble remaking the included password mod that comes with hakchi. I cant find any programs to convert .png into raw format. I tried a gimp method and I got a black screen. I cant find any other programs that work. If I need linux I have a linux machine I can use but I have found no information on it anywhere.

Please Help!
Thanks!

**Comment by Frank-5** [comment]
This is the place for reporting hackchi2 bugs and feature requests.  Help for other issues such as this can be found in the Reddit SNES mini forums. Have you read this modification guide yet? https://github.com/ClusterM/hakchi2/wiki/Modifications-and-modules-guide
Or read the FAQ there ?  Again,  all the help me do this and help me do that doesn't belong in a git bug tracker.

**Comment by Frank-5** [comment]
All questions like this do is clutter up the actual intended use of the git bug tracker and make it harder for ClusterM to sort though what actually are bugs and issues and feature requests.  So pleas close this ticket. Thanks

**Comment by NodeTG** [comment]
Yes I did read the modification guide.
