### ISSUE TITLE
[ Feature Request ] Potential Multitap Capabilities

### ISSUE THREAD

**Issue by ThunderTechnologies** [ClusterM/hakchi2#1085]
To start off, I'm more of a hardware guy than a software guy, so I'm not even sure if this is possible. 

The NES and SNES classic use the I2C protocol for the controllers and I2C is designed to have more than one device on the same bus, so long as the devices have different address.

I'm assuming the controllers all have the same address, and because of that, it wouldn't be possible to just slap two controllers on the same port. But Linear makes a chip ([LTC4316](http://www.linear.com/product/LTC4316)) that can translate I2C addresses to another address. 

What I'm thinking is it should be possible to have two controllers on the same port, with one being connected as normal, and the other going through the address translator. Building two of these adapters should be pretty easy, and then we could have four controllers on the SNES Classic.

The hard part (from my point of view) would be to modify the firmware of the SNES to be able to even see the extra two controllers, and then have them act as proper input devices. Is it possible to have the SNES classic understand two extra controllers? If it is, I can build the multitap if someone is able to figure out the software side of things.

**Comment by erroneus0** [comment]
The best place and most appropriate way to see multitap become a reality is through development of the OTG USB port.  This will also require some additional things to ensure USB controllers are properly supported by the OS and Applications software within the NES/SNES classic.

**Comment by electrocret** [comment]
I agree with erroneus0. While the i2p translator would work and be cool. Unfortunately it would  require custom coding  for this one application. Meanwhile if  we add USB controller support it would allow multitap functionality as well as other peripherals such as Mouse. Also, keep in mind that it's difficult/expensive to buy official SNESC controllers separately, so you'd likely be using 3rd party controllers anyways.

**Comment by ThunderTechnologies** [comment]
I had actually completely forgotten about OTG abilities. I were to pursue the I2C route, where  would I modify the settings? I know it'll be rather difficult, but I do like a challenge. I figure I should see if I can even get the snes to detect both controllers on one port.

**Comment by ClusterM** [comment]
It's already done by honeylab: 
http://honeylab.hatenablog.jp/entry/2017/10/27/231848
http://honeylab.hatenablog.jp/entry/2017/11/01/202716
http://honeylab.hatenablog.jp/entry/2017/11/07/092827

**Comment by ThunderTechnologies** [comment]
Cool, I wasn't able to find that when I searched for it. I guess we can call this closed.
Thanks everyone
