### ISSUE TITLE
Box Art Issue

### ISSUE THREAD

**Issue by HelixSoundLab** [ClusterM/hakchi2#1087]
I have renamed the box art exactly the same at the ROMs and have placed the artwork in the art folder. I still have to manually browse for each piece of artwork to get them to work. Any ideas on what this could be?

**Comment by Shoothimnow** [comment]
posted in the wrong location, unless you want ClusterM to code you something that EVERYONE is having a problem with

https://www.reddit.com/r/miniSNESmods/

-----------
That said... please close this and post in https://www.reddit.com/r/miniSNESmods/      .  To be helpful even more, while using Hakchi2... just drag and drop the picture over the one Hakchi2 is showing, it will auto do everything you are trying to do...
