### ISSUE TITLE
Games randomly pause 

### ISSUE THREAD

**Issue by justingodard-zz** [ClusterM/hakchi2#1091]
Recently I've been having trouble with my SNES Classic where (even without a controller plugged in) something is triggering the hardware to think I am pressing "Start". 

I happens on the home page, within a game - basically everywhere, and at random times.  :(

**Comment by ReyVGM** [comment]
What does that have to do with Hakchi?

**Comment by Shoothimnow** [comment]
Is everyone having this problem?

If Yes, please do not close this post
If No, please close this post and post in https://www.reddit.com/r/miniSNESmods/ instead.  People will be MORE THAN GLADLY ABLE to help you fix the problem over there...

This not a forum...  This is an issue tracker...
