### ISSUE TITLE
Nes Black Screen

### ISSUE THREAD

**Issue by javierbex** [ClusterM/hakchi2#1092]
Hi guys. I've tried and tried everything and still got nothing.

So here is what happened. I hacked my nes (way before there was a snes version). Then i got my snes mini and also hacked it. But with a different versión. The thing is that mi PC was formatted and I lost everything. So i tried to re install everything first in my nes. But now i have a black screen in my tv. The exception is that when i turn off mi nes it appears the message "Shutting down" like a normal nes. I've tried to uninstall hakchi, flash original kernel and still got this black screen. What should i do?? and any advices when i'm doing the same with snes for not having the same problem???

Thanks

**Comment by Shoothimnow** [comment]
Is everyone having this problem?

If Yes, please do not close this post
If No, please close this post and post in https://www.reddit.com/r/miniSNESmods/ instead.  People will be MORE THAN GLADLY ABLE to help you fix the problem over there...

This not a forum...  This is an issue tracker...

**Comment by javierbex** [comment]
Sorry, i didn't know that...

**Comment by Shoothimnow** [comment]
Then can you please **_close this issue_** to remove clutter so that ClusterM can work on things that really need fixed that everyone is having problems with?

**Comment by Shoothimnow** [comment]
Again, this is not a forum, and leaving **_this issue open_** is generating clutter...  _**Please close this issue**_

**Comment by Drakonas** [comment]
@Shoothimnow thanks for all you're doing to help keep this tracker clean, while I have been away for family trouble. And @javierbex sorry if you took that harshly, but yes: this is a bug tracker. All questions, inquires, and troubleshooting help needs to be asked on reddit before coming here, please. :)
