### ISSUE TITLE
Cool Baby clone console hack

### ISSUE THREAD

**Issue by astrosspace** [ClusterM/hakchi2#1093]
Is there anyway the to get a Nes clone console to have the same operating system as an official Nes classic? As well as adding games

**Comment by Shoothimnow** [comment]
Please close this "issue" and post it in the appropriate location.... https://www.reddit.com/r/miniSNESmods/

**Comment by Shoothimnow** [comment]
Again, this is not a forum, and leaving **_this issue open_** is generating clutter...  _**Please close this issue**_

**Comment by Drakonas** [comment]
Questions and inquiries need to be asked on reddit. This is a bug tracker, not a personal help line.
