### ISSUE TITLE
Flashed the kernal now wont let me add games

### ISSUE THREAD

**Issue by Merward11** [ClusterM/hakchi2#1095]
![image](https://user-images.githubusercontent.com/32684999/33527288-018b8d06-d846-11e7-9d01-788665ecd8df.png)
 get this screen when trying to add games to my nes mini any help to resolve this will be greatly recieved

**Comment by DecanFrost** [comment]
Are you using webinstaller or manual download..  I get this if I download hakchi2 and put it in side a folder in a folder.  I used to have /nintndo/mods/hakchi2/  and would get that  I put hakchi2 in the Nintendo folder as /nintendo/hakchi2/ and resolved it

**Comment by Merward11** [comment]
all sorted was using the manual download re fashed the custom kernal after downloading the latest version and that solved it cheers for your response
