### ISSUE TITLE
Question for sync game to USB disk

### ISSUE THREAD

**Issue by gexqin** [ClusterM/hakchi2#1097]
Hi 

I saw someone on youtube show how to use hakchi2 to sync games to USB disk.  And they said press Shift Key then click Synchronize ....icon could be select disk. But it doesn`t work for me in my computer it still show Waiting for your NES.....

Any idea？

**Comment by bslenul** [comment]
USB-HOST isnt implemented in hakchi2 official releases (yet?).

Go here: https://github.com/KMFDManic/NESC-SNESC-Modifications  
And if you need more info/help: https://www.reddit.com/r/miniSNESmods/

**Comment by Shoothimnow** [comment]
This isn't a Hakchi2 issue and should be posted in a real forum (not an issue tracker)

https://www.reddit.com/r/miniSNESmods/
