### ISSUE TITLE
Retrieving game info from thegamesdb.net

### ISSUE THREAD

**Issue by darrelhunt** [ClusterM/hakchi2#11]
Think it might be useful to retrieve the info such as the release date, number of players, box art from thegamesdb?

http://wiki.thegamesdb.net/index.php?title=API_Introduction

**Comment by soulctcher** [comment]
There is already code in the current branch to use the XML database from BootGod for the publisher, date, and number of players.  It's just not in a public build yet.

**Comment by darrelhunt** [comment]
Bootgod doesn't go a granular to have the actual release dates for games.  thegamesdb does, for most.

**Comment by soulctcher** [comment]
I'm staring that the XML right now and most of the entries have dates on them.  Depending on the game, it may be just month and year, but many do have the day as well.  Not to mention, it's an offline XML that's being packed in.  Does thegamesdb offer the full XML offline?

**Comment by darrelhunt** [comment]
I've searched that xml for 30 games, some of the most popular ones and they only have the release month.  Those that are in thegamesdb in most cases have the day.

**Comment by soulctcher** [comment]
Considering it's an online resource and not a fully packable XML, and more than a couple of times I've had issues reaching the site (slow responsiveness/timeouts), I'm not sure that's the best way to go.  With BootGod's XML, it doesn't require connectivity.  Obviously it's Cluster's choice which way to go, and he's already coded the BootGod XML in (works great, btw), so we'll see which way he goes.
