### ISSUE TITLE
Getting no display when staring SNES mini. Only Menu music and "Shutting down" when turned off.

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#1101]
When I start the classic I get no display, only black screen. I get audio from what I assume is just the menu music. I can also see the shutting down screen when I turn off the console. The word hackchi gets put on the screen when syncing, and I can enter the Konami code as a password if I enable the password mod.

But, no matter what after flashing back and forth etc, I cant get any UI.

**Comment by Drakonas** [comment]
Please discuss this on https://www.reddit.com/r/miniSNESmods/ This bug tracker is for tracking finite bugs that have been discovered, not troubleshooting problems with using Hakchi.
