### ISSUE TITLE
Not enough disk space

### ISSUE THREAD

**Issue by mugilla** [ClusterM/hakchi2#1102]
I’m trying to save way below the 300mg of dark drive space but it won’t even let me flash custom drive without saying not enough disk space. Need help please.

**Comment by Drakonas** [comment]
Support requests are supposed to be asked on the https://www.reddit.com/r/miniSNESmods/ subreddit. This is a place for submitting known bugs with a program, not figuring out what a bug is. Start there, and someone will probably be able to figure out your problem with you.
