### ISSUE TITLE
Save States Mame

### ISSUE THREAD

**Issue by Zacowacko** [ClusterM/hakchi2#1104]
Do saves states work with Mame? I'm using Mame2000 in order to play Tapper, but when you move down and hit Y to save, nothing happens. Thanks in advance!

**Comment by ReyVGM** [comment]
ask on the https://www.reddit.com/r/miniSNESmods/ subreddit. This is a place for submitting bugs with the program.

**Comment by Shoothimnow** [comment]
This has nothing to do with Hakchi2, please close this issue and post in the subreddit above.
