### ISSUE TITLE
Error adding games to NES Classic

### ISSUE THREAD

**Issue by nesuser87** [ClusterM/hakchi2#1105]
I am trying to add games to my NES classic using Windows 10. Kernel flashing worked perfectly fine, and then I received the error provided in the attached debug log when attempting to add games. Any help in fixing this error would 
[debuglog.txt](https://github.com/ClusterM/hakchi2/files/1539212/debuglog.txt)
be appreciated.

**Comment by Drakonas** [comment]
This is a bug report tracker when one knows an exact bug to report, not a forum to figure out what is causing an error. Support requests need to be made on the proper subreddit: https://www.reddit.com/r/miniSNESmods
