### ISSUE TITLE
New Folder Images For Hakchi2

### ISSUE THREAD

**Issue by luluvulcain** [ClusterM/hakchi2#1106]
New Logos in Folder "folder_images" to replace in Hakchi2 to download at https://github.com/luluvulcain/hakchi2

**Comment by Shoothimnow** [comment]
And this is an _**issue**_ to Hakchi2 how?  Post this in https://www.reddit.com/r/miniSNESmods/ man... **and close this ticket**.  This is not a forum to promote crap, it is an issue tracker for ClusterM to fix **** that comes up.
