### ISSUE TITLE
Adding more games

### ISSUE THREAD

**Issue by angelusjmw** [ClusterM/hakchi2#1108]
Can I add more games to my snes mini classic even after if I already added games to it without having to download the Games again?

**Comment by ghost** [comment]
First, questions like this should be asked on Reddit: https://www.reddit.com/r/minisnesmods This is where people report problems with the Hakchi2 program, not a place to ask how to use it.

Second, when you open Hakchi2, it will show the games you’ve already added to it on the main window. Any of those games you’ve installed onto your Classic will be marked. If you want to add any more games, simply add them to Hakchi2, and then mark them. Next time you flash the custom kernel, Hakchi2 will add any of the games you just marked.

If you’ve somehow deleted games out of Hakchi2, though, you may need to download them again if you want to re-flash the custom kernel.

**Comment by Shoothimnow** [comment]
as @MaskedManiac stated, this is an issue tracker.  **Please close this issue** before you completely abandon it and post in the correct location over on https://www.reddit.com/r/miniSNESmods/

**Comment by Frank-5** [comment]
I agree.  This is ONLY an issue tracker, not a general help, question, or user problem/error forum.  I guess folks that post this type of clutter can't be bothered in reading / understanding this.  Fortunately @Drakonas will remove these nuisance postings if the OP doesn't.  Just takes his time up when he could be helping track and sort bugs and feature requests for Hakchi2.

**Comment by Shoothimnow** [comment]
And here is another person thinking this is just another forum.......

# _**Please Close This Issue**_.  This is not a forum, Nor was this an issue that is suppose to be posted here

**Comment by Frank-5** [comment]
Dang, man. My ears are ringing!  But to the point being made:  This is an issue and bug tracker, not a general help forum as stated above and in about 20 or 30 other previous posts (thankfully closed now). So people, please, for the love of God, QUIT posting questions on general help and support here !!!!   Read the FAQ, watch some YouTube videos, or actually read the instructions and follow the on screen prompts.  Seriously, hakchi2 couldn't be made any simpler unless ClusterM personally installed it for you.

**Comment by Shoothimnow** [comment]
So not only does @angelusjmw posts on the completely wrong site, but also completely abandons this.  Fantastic.  @Drakonas please close this issue...

Please read the FAQs next time...
