### ISSUE TITLE
User Experience Improvements - Display Options in NES Home Menu

### ISSUE THREAD

**Issue by B9KnM8UqQ2W2Vwk7uvZ7** [ClusterM/hakchi2#111]
I have no idea if this is even possible but if so could we please have some of the display options elsewhere listed under "Display" on the NES Home Screen?

I'm thinking specifically of things that are available elsewhere to deal with Overscan and having CRT Filter like option but a better one than the inbuilt version, one that reduces the blur.

**Comment by ClusterM** [comment]
We can't edit shell (yet?)
