### ISSUE TITLE
New games added to SNES showing broken links

### ISSUE THREAD

**Issue by GEEKMODE123** [ClusterM/hakchi2#1112]
I installed with Hakchi 2.0.21.72. Followed all the step made sure i had updated cord's. I uninstalled and reinstalled but still ever game i upload to the snes showa broken link and does not work. Is there something i am missing?

**Comment by Shoothimnow** [comment]
**_Please close this issue_** and post in https://www.reddit.com/r/minisnesmods This is where people report problems with the Hakchi2 program, not a place to ask how to use it.

Unless you want are wanting ClusterM to code you something (the developer of this program), by all means keep this issue open, but this isnt a forum.
