### ISSUE TITLE
Switching to a new version of Hackchi and cant transfer roms saved in SNES mini back to Hackchi

### ISSUE THREAD

**Issue by RedAnimationsYT** [ClusterM/hakchi2#1116]
I have just moved to the newest version of hackchi becouse the other one had some issues with the memory becouse i could use 300 gb from my snes mini and only had like 150 gb so i thought this was an issue with the older version (wich is version 20, aka the 1st one fore snes mini) now that i changed version i have no way to have the same roms i had in the last version with the newest version so please help me.

i have tried going on were it says kernel and options and help and stuff but i do not understand theese things and i just want to move my roms that i downloaded previously from the snes mini back to my pc to add more.

**Comment by bslenul** [comment]
To get your roms from SNESC to your PC: https://www.reddit.com/r/miniSNESmods/comments/7as9kr/purchased_a_already_modded_snes_questions/dpdg9y7/

But this is not a hakchi2 issue so please close this thread, if you have any question go to the [subreddit](https://www.reddit.com/r/miniSNESmods/).
