### ISSUE TITLE
Lost SNES Original Kernel - Please Help

### ISSUE THREAD

**Issue by mike3175** [ClusterM/hakchi2#1117]
Can anyone send me an SNES Original Kernel dump please. My SNES seems to be bricked as I flashed NES one from what I was told would work but seems to not. Would be very grateful if someone can send me a SNES Kernel Dump TY

**Comment by Shoothimnow** [comment]
1) We cannot give that out
2) You are posting in the wrong location - please use https://www.reddit.com/r/miniSNESmods/
3) Hakchi2 is working properly, and you need to **close this issue**
4) Google can also help you

But please close this issue... you posted in the wrong location
