### ISSUE TITLE
any chance to get retroachievements on the NES mini classic?

### ISSUE THREAD

**Issue by christophprokop** [ClusterM/hakchi2#1119]
Hi there,

first of all, a BIG THANK YOU for all your efforts. hakchi2 works like a charm and i have a lot of fun because of the opportunities you made possible!

Only one thing to add would be really cool and that is a connection to http://retroachievements.org/

Any chance this could happen in the future?

Greetings
Christoph

**Comment by Drakonas** [comment]
No, this would not be possible as running something in the background while Canoe is running would not be possible as per the way the system works. Retroarch, perhaps, but that is something to request of Retroarch porters to the architecture the SNES Classic uses. We don't code Retroarch. lol.
