### ISSUE TITLE
C8 Error Reset after N64 Games

### ISSUE THREAD

**Issue by markched** [ClusterM/hakchi2#1120]
Hi Guys,

Not sure if this is still a thing or not or if it's been resolved. My SNES Classic is still doing a C8 Error after pressing "Reset" during N64 gameplay.  

I know I can use the controller reset feature and it does not have this issue, I was just seeing if this has a proper fix for it yet. 

Thanks Guys!

**Comment by Shoothimnow** [comment]
During N64 gameplay... thats not a Hakchi2 computer issue, thats an issue with whatever you are mod you are running the N64 emulator from....

You need to **close the issue here** and post this in the correct location
https://github.com/ClusterM/retroarch-clover/issues

**Comment by markched** [comment]
Thank you!
