### ISSUE TITLE
How to remove hakchi2 from SNES

### ISSUE THREAD

**Issue by ae86Pride** [ClusterM/hakchi2#1121]
Hello,
I hope I'm not repetitive when it comes to this subject. I downloaded Hakchi2 on SNES mini, and I want to remove it and make the system factory settings. I tried to do it from the SNES mini factory reset, but my games are still there.
How would I do this.
I checked previous questions but I didn't find this, unless i'm blind and it is there.
I appreciate the help.

**Comment by Frank-5** [comment]
How's about reading the FAQ / Wiki ?   It's posted in plain sight on this GitHub :
https://github.com/ClusterM/hakchi2/wiki/FAQ
Basically since ver 2.08 you just select uninstall from the menu.  This is an issue reporting area, not a general help forum, so please, close this issue because it is not an issue. Thanks

**Comment by Frank-5** [comment]
Here is the proper place to ask these types of non-issue questions:
https://www.reddit.com/r/miniSNESmods/comments/78odp7/uninstalling_hakchi_without_losing_saves_for/

**Comment by ghost** [comment]
As Frank-5 points out, this section is for reporting issues (bugs) with the actual Hakchi2 program, not for individual users who have issues trying to understand how to use Hakchi2.

In the future, seek help from the modding community on Reddit (from the link Frank-5 posted), and help keep this section strictly for reporting bugs.

That being said, uninstalling Hakchi2 from your console is very easy, just select "Uninstall" from the "Kernel" drop-down menu at the top menu in Hakchi2, and follow the directions in the pop-up windows.

https://imgur.com/a/2YSjF

Please do us a favor, and close this thread so it doesn't remain as an "open issue". Thank you.
