### ISSUE TITLE
Can't unpack ramdisk

### ISSUE THREAD

**Issue by rg4lbaby** [ClusterM/hakchi2#1122]
I'm trying to do the USB mod for my SNES Classic but I get this error. Can anyone help?

![mf](https://user-images.githubusercontent.com/33976929/34187513-c06b2f40-e4ff-11e7-8d85-b31014177405.png)

**Comment by craz02** [comment]
Ok Number 1 you need orginal Stock named as kernel_snes.img in folder dump of hakchi2.
NUMBER 2 open hakchi and go to uninstall hakchi and wait a little bit when the progress is over.
Number 3 flash the orginal kernel that's it and here also wait until progress is over then you snes function again like orginal!!!!!
I got same Problem all the time with this can't unpack ramdisk shit hope it's help!!!!
Yesterday i solved this by that Way that i wrote over.

**Comment by rg4lbaby** [comment]
Okay I will try this out thanks 😊

**Comment by craz02** [comment]
I hope really this will help the People  with the:
Can't unpack ramdisk Issue!!!!

**Comment by yangjutsu** [comment]
i'm having this very same issue. please assist. i lost the original kernal... i'm a modding newborn.

**Comment by craz02** [comment]
Check my first post dude and go on.
Have you a backup of your kernel?

**Comment by yangjutsu** [comment]
nope, i didn't back up the original kernal like ALL the guides said to... is this file interchangeable? can i use someone else's? i am a dodo.

**Comment by craz02** [comment]
E-Mail

**Comment by yangjutsu** [comment]
henry.yang84@gmail.com

**Comment by craz02** [comment]
But when you live in USA you need an us Kernel!!!#

**Comment by yangjutsu** [comment]
i'm cursed... just like the curse weapons in assassin's creed: origins. haha

**Comment by craz02** [comment]
Sent a photo from your snes mini please

**Comment by yangjutsu** [comment]
a photo of what? the bug?
![screenshot 4](https://user-images.githubusercontent.com/34699883/34190112-d3bff974-e4f3-11e7-864c-93de36d61777.png)

**Comment by craz02** [comment]
Nope i mean the snes mini !!#

**Comment by yangjutsu** [comment]
the serial on the back is: SU202981138

**Comment by craz02** [comment]
It seems like it's the US Version from the snes mini or not?

**Comment by yangjutsu** [comment]
i bought from a guy here in gilroy, ca, usa so... i think it's US version

**Comment by craz02** [comment]
Then normaly you need the U S Kernel check out the internet!!!!!
Then follow my first post and  evrything is good

**Comment by yangjutsu** [comment]
copy that, thanks for the assist. merry xmas and happy new year.

**Comment by Shoothimnow** [comment]
When you get this working (or if you have a guide how you fixed it), please post and **close this issue**

Not sure if this is a problem with Hakchi2 or just a bad install of the USB mod, but if this is more of a batched kernal and need to just reinstall the original kernal again, please (again, close this issue) continiue over on a forum rather than an issues board =) https://www.reddit.com/r/miniSNESmods/  Thanks

**Comment by yangjutsu** [comment]
a buddy sent me the EU kernel.img file and i flashed it. now it works, but only holds one game at a time...
one problem solved another arises... like an immortal creature. ahahahah thank you all for the assistance.

**Comment by Shoothimnow** [comment]
Please close this issue (this isn't a forum)

And if you need more assistance, please start a forum post over on Reddit - https://www.reddit.com/r/miniSNESmods/

Thanks

**Comment by yangjutsu** [comment]
How do I close....

**Comment by craz02** [comment]
The Method that i wrote here 100% WORKS DUDE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!😀😀😀

**Comment by yangjutsu** [comment]
I required  an original kernel file for it to flash, dump etc etc

On Dec 20, 2017 10:54 AM, "craz02" <notifications@github.com> wrote:

The Method that i wrote here 100% WORKS DUDE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!😀
😀😀

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ClusterM/hakchi2/issues/1122#issuecomment-353150927>,
or mute the thread

**Comment by hiryu81** [comment]
Hello guys, i have the same problem and i lost my original European Kernel, do you have one to spare? Please :(  my mail is tatsuo.aikido@gmail.com
