### ISSUE TITLE
Blinking Ted power light on NES Mini f hackchi2 version

### ISSUE THREAD

**Issue by paulownz** [ClusterM/hakchi2#1124]
So I had a friend bring his NES

I flashed original kerbal

Then did flash customer kerbal

When gets to "boota" the red light starts flashing intermittently non-stop

Will uninstall and work from original kernel

But can't get custom kernel  to work

Have to revert to uninstall

Never had a problem before 

Why now?

**Comment by Shoothimnow** [comment]
Please close this issue and ask in a forum, this is a user install error, not a Hakchi2 issue
https://www.reddit.com/r/miniSNESmods/

Again though **please close this issue**
