### ISSUE TITLE
SNES C8 with NES games

### ISSUE THREAD

**Issue by biohazard901** [ClusterM/hakchi2#1130]
When I add NES games to the snes classic they load up fine but when I press reset or hold down and press select to reset I always get a C8 error. Any known way to correct this?

**Comment by mrTruch** [comment]
Too many games. Is that possible?

**Comment by biohazard901** [comment]
Nah. The 1st page has 21 games. Even with the genesis games it does this. Ill start streets of rage 2 and when I press down + select to reset it will give me the C8 error.

**Comment by ReyVGM** [comment]
You have too many games on a page or your memory is almost filled up.

**Comment by mrTruch** [comment]
Exactly. Usually is a lack of memory. When you exit it spends memory to create suspend point, for example.

It will explain the error.

What do you mean 1st “page”? Don’t mind if “1st page” has only 21 games but another folder has 100 games.

Lack of memory makes error at all the system, folder or pages.

**Comment by biohazard901** [comment]
I mean the 1st page has the original 21 games on it. I deleted the other games i installed on there. All thats on there right now is streets of rage 2 and while it works it gives the  C8 error when i press down select to reset. Im not even over 100mb there is plenty of space. i already unistalled and reinstalled and it still does the same error.

**Comment by ReyVGM** [comment]
Do a factory reset then. Start over.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
