### ISSUE TITLE
Мне нужна помощь ошибка "can't unpack ramdisk"

### ISSUE THREAD

**Issue by maratmine1** [ClusterM/hakchi2#1133]
Ошибка появляется тогда когда я пытаюсь синхронизировать список игр.Версия хакчи 2.0.21.72.И еще проблема с загрузкой игр "Не удается преобразовать символ Юникода \u043c по индексу 9 формат заданной кодовой странницы."Консоль SNES Mini .Скачал я hakchi web_installer .Помогите пожалуйста!!!

**Comment by megaDRONe86** [comment]
А ты в какую папку распаковал все это дело?
Я думаю, что не должно быть русских путей. Попробуй положить папку с hakchi просто на диск C. Кроме того, я думаю, что все ромы тоже должны иметь английские имена.

**Comment by megaDRONe86** [comment]
P.S. Вообще тут принято писать на английском.
P.S. You should use English here BTW.

**Comment by Shoothimnow** [comment]
#1122

**Comment by maratmine1** [comment]
what if Light-emitting diode is on when it says "should not lighting"?
