### ISSUE TITLE
Problem with synchronize selected games - building folder structure - kachikachi not a directory - please help

### ISSUE THREAD

**Issue by Mljaks** [ClusterM/hakchi2#1136]
I have a problem  with synchronize games on NES. I get error rm:cant start ..... not a directory. Hakchi2 v2.20.  
Windows 7

I tried everything installing newer version also made a new directory on telnet client, but without success. 
Still get same error.

![slika](https://user-images.githubusercontent.com/31959134/34437662-90649e46-eca0-11e7-8354-ce345424f5fa.png)

Can anyone help me with this problem?
Tnx.

**Comment by ClusterM** [comment]
Please update to latest version first.

**Comment by Mljaks** [comment]
Tnx for reply!
I update to latest version (v2.21f) and flash custom kernel. Now i get error:

Base directory: C:\hakchi2_debug
Loading config
Starting, version: 2.0.21.72
Loading games
Loading C:\hakchi2_debug\data\nescarts.xml
Listening port 1023
Loading C:\hakchi2_debug\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
clovershell connected
[ -d /var/lib/hakchi/firmware/ ] && [ -f /var/lib/hakchi/firmware/*.hsqs ] && echo YES || echo NO # exit code: 0
cat /etc/clover/boardtype # exit code: 0
cat /etc/clover/REGION # exit code: 0
Detected board: dp-nes
Detected region: EUR_USA
df /dev/nandc | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code: 0
mount | grep /var/lib/clover # exit code: 1
mkdir -p /var/lib/hakchi/rootfs/usr/share/games/ && du -s /var/lib/hakchi/rootfs/usr/share/games/ | awk '{ print $1 }' # exit code: 0
mkdir -p /var/lib/clover/profiles/0/ && du -s /var/lib/clover/profiles/0/ | awk '{ print $1 }' # exit code: 0
NANDC size: 381,6MB, used: 49,8MB, free: 312,1MB
Used by games: 0,3MB
Used by save-states: 2,6MB
Used by other files (mods, configs, etc.): 46,9MB
Available for games: 312,5MB
Saving config
Executing task: UploadGames
pkill -KILL clover-mcp # exit code: 0
pkill -KILL ReedPlayer-Clover # exit code: 0
pkill -KILL kachikachi # exit code: 1
pkill -KILL canoe-shvc # exit code: 1
gunzip -c - > /dev/fb0 # exit code: 0
tar -xvC / # exit code: 0
chmod +x /bin/* # exit code: 0
chmod +x /etc/init.d/* # exit code: 0
mount | grep /var/lib/hakchi/squashfs # exit code: 0
Processing CLV-H-RIKBN ('Gekitotsu Yonku Battle'), size: 45KB
df /dev/nandc | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code: 0
mount | grep /var/lib/clover # exit code: 1
mkdir -p /var/lib/hakchi/rootfs/usr/share/games/ && du -s /var/lib/hakchi/rootfs/usr/share/games/ | awk '{ print $1 }' # exit code: 0
mkdir -p /var/lib/clover/profiles/0/ && du -s /var/lib/clover/profiles/0/ | awk '{ print $1 }' # exit code: 0
NANDC size: 381,6MB, used: 49,9MB, free: 312,0MB
Used by games: 0,3MB
Used by save-states: 2,6MB
Used by other files (mods, configs, etc.): 47,0MB
Available for games: 312,4MB
umount /usr/share/games/nes/kachikachi # exit code: 1
mkdir -p "/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi" # exit code: 1
reboot # exit code: 0
shell command "mkdir -p "/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi"" returned exit code 1: mkdir: can't create directory '/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi': File exists
   at com.clusterrr.clovershell.ClovershellConnection.Execute(String command, Stream stdin, Stream stdout, Stream stderr, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 680
   at com.clusterrr.clovershell.ClovershellConnection.ExecuteSimple(String command, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 638
   at com.clusterrr.hakchi_gui.WorkerForm.UploadGames() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 898
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 295
shell command "mkdir -p "/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi"" returned exit code 1: mkdir: can't create directory '/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi': File exists
   at com.clusterrr.clovershell.ClovershellConnection.Execute(String command, Stream stdin, Stream stdout, Stream stderr, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 680
   at com.clusterrr.clovershell.ClovershellConnection.ExecuteSimple(String command, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 638
   at com.clusterrr.hakchi_gui.WorkerForm.UploadGames() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 898
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 295
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
write error: Win32Error
clovershell disconnected
clovershell connected
[ -d /var/lib/hakchi/firmware/ ] && [ -f /var/lib/hakchi/firmware/*.hsqs ] && echo YES || echo NO # exit code: 0
cat /etc/clover/boardtype # exit code: 0
cat /etc/clover/REGION # exit code: 0
Detected board: dp-nes
Detected region: EUR_USA
df /dev/nandc | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code: 0
mount | grep /var/lib/clover # exit code: 1
mkdir -p /var/lib/hakchi/rootfs/usr/share/games/ && du -s /var/lib/hakchi/rootfs/usr/share/games/ | awk '{ print $1 }' # exit code: 0
mkdir -p /var/lib/clover/profiles/0/ && du -s /var/lib/clover/profiles/0/ | awk '{ print $1 }' # exit code: 0
NANDC size: 381,6MB, used: 49,8MB, free: 312,1MB
Used by games: 0,3MB
Used by save-states: 2,6MB
Used by other files (mods, configs, etc.): 46,9MB
Available for games: 312,5MB

![slika](https://user-images.githubusercontent.com/31959134/34446334-6e69c0a2-ecda-11e7-97f5-29a7d0548665.png)

Should link below solve my problem?
https://github.com/ClusterM/hakchi2/issues/842

Tnx!

**Comment by Mljaks** [comment]
I solved the problem. I have restored nes classic console to factory settings, then install latest version Hakchi 2.21f and now is working perfect. Happy new year to everybody;)
