### ISSUE TITLE
Last folder/menu position reset to top level (main menu) at reboot; C3, C7 errors; save directory

### ISSUE THREAD

**Issue by ArieKindicator** [ClusterM/hakchi2#1138]
I experienced C3 and C7 errors after I accidentally switched of the tv with the SNES connected to and powered by the tv. Before this the flash drive worked without any issues or error messages.
FYI: I used USB-Host but that doesn't matter as the same issue can occur when all games are stored on internal memory. The maximum number of games in each subfolder is 30 or less. No possible conflicts there.
Other issues with C3 errors are: #1126 and #1132 .

I couldn't start any game or leave the subfolder to a higher (menu) level. It produced a C3 or C7 error.

1. I used a different USB flash drive *with a different and simple folder structure* and the games and folder structure were accessible. In other words: no problems at all.
2. I *reformatted* the 'problem' flash drive and synced all games again (with hakchi2).
3. reformatting (2) didn't work. I got stuck at the same submenu/subfolder structure position as previous. Thus, *the last folder position* or last game position is stored somewhere on internal memory. And, when a external storage device is connected, the  USB identifier too.

I could finally solve it by:
a. moving the existing game directory (with the C3, C7 errors) on the USB drive outside the hakchi directory. I wanted to keep a backup of the games and folder structure and not simply erasing them or reformatting the drive (see 2 above, that doesn't work).
b. creating a new game directory within the hakchi directory on the USB drive and add a few (±5) games to it.

The C3 and C7 errors were gone. So far, so good.

c. I deleted the games in the `hakchi/games` folder, and
d. moved the backuped game and folder structure (a) back to `hakchi/games`

The games and folder structure where perfectly accessible and all C3 and C7 were gone.

I would like an option to overwrite or reset the last game and/or folder position *at bootup* and in case external memory (USB-Host) is used the USB indentifier should be reset or overwritten too. The default position should be top level/main menu.
Potentially, this could prevent a lot occurrences of C3 or C7 error messages.

**C3 and C7 errors and a `saves` directory**
Another cause for C3 or C7 errors is the `saves` directory
If you are using USB-Host with a `hakchi\saves` directory this might cause C3 and C7 errors.
This can be solved by _removing_ the `hakchi\saves` directory.

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

Plus, Hakchi2 is just the application that you install on the SNESC.  Once you get into hmods (like usb_host), this is no longer a hakchi2 issue, than a configuration error.
