### ISSUE TITLE
Error C3

### ISSUE THREAD

**Issue by LudovicoPletto** [ClusterM/hakchi2#1139]
So, excuse me for the trouble, when I try to play a game of the snes not preinstalled I do not start the game and when I try to reset it tells me error C3, I followed the procedure to perfection, what should I do?

**Comment by ghost** [comment]
This is a section dedicated to reporting bugs of Hakchi2. This doesn’t sound like a bug, though. More than likely it’s an issue with your configuration. Help keep this place for bug reports only by making your inquiry here: https://www.reddit.com/r/minisnesmods

Please close this issue report. Thank you.
