### ISSUE TITLE
Issues syncing with SNES Mini and hakchi2 v2.21f

### ISSUE THREAD

**Issue by absols** [ClusterM/hakchi2#1140]
I have done everything, dumping, booting the custom flash etc. but now i click "Synchronize selected games with NES/SNES Mini" it tells me to do the following steps 1. Connect you NES/SNES Mini to the PC via USB Cable. (DONE) 2. Turn it on. (DONE) 3. Install driver if it's not installed yet: INSTALL DRIVER

well I already installed it and when i click the button is says

"NES Mini not found, sorry"

if i put the console into DEV mode and do it I get

"Found USB device: "NES Mini" (1F3A:EFE8) "Installing wdi driver with <nesmini,inf> at <usb_driver>"

I click enter which closes that box and nothing happens still have the 3 steps on my screen. also idk why it says NES Mini but im on a SNES Mini

ALSO NOW I AM GETTING AN ERROR WHEN I TRY TO RE KERNAL AND WHAT NOT SAYING 
![wpbppo5mromzrczx4elv9w](https://user-images.githubusercontent.com/34973680/34458370-0087db4c-ed8d-11e7-9c51-5949c6f7fb98.png)

**Comment by ReyVGM** [comment]
This is a section dedicated to reporting bugs of Hakchi2. This doesn’t sound like a bug, though. More than likely it’s an issue with your configuration. Help keep this place for bug reports only by making your inquiry here: https://www.reddit.com/r/minisnesmods

Please close this issue report. Thank you.

**Comment by ghost** [comment]
I believe this issue report can be closed. The OP was able to resolve the issue.

https://www.reddit.com/r/miniSNESmods/comments/7n58nj/cant_synchronize_games_to_console/
