### ISSUE TITLE
SNES randomly resets itself when playing games

### ISSUE THREAD

**Issue by pcabrera83** [ClusterM/hakchi2#1143]
When playing added SNES ROM's my SNES mini randomly resets itself. It happened when I was playing Chrono Trigger and TMNT V - Turtles in Time. Any idea why this is happening?

**Comment by ReyVGM** [comment]
Send it back to Nintendo for repairs.

**Comment by pcabrera83** [comment]
Let me add to my original topic. This only happens after I used hakchi2. It never occurred before.

**Comment by Frank-5** [comment]
Lol.   
I mean really. 
Rotflmao

Ok, first off this IS NOT the place for personal software support for Hakchi2. This is a place to report bugs and issues. This (and many other posts recently) have been cluttering up this git issue tracker with "help me this and can't find that and this doesn't work and I lost my kernel dump, blah blah blah".
It's almost entertaining if it weren't so sad that people are really this stupid that they can't get this simple concept. Anyway. Go to this really cool support forum for help and support:
https://www.reddit.com/r/minisnesmods
Lots of really bright and eager folks to help. Also make a personal effort to read the wiki and FAQs and read previous support topics.
Ok, finally, sorry to seem so harsh but GEEZ people. Educate thyself.

**Comment by Frank-5** [comment]
And @ReyVGM , hehe. Spot on.

**Comment by Frank-5** [comment]
Wish that @Drakonas or some other moderator were around to close these non issues.  Like I said.  Entertaining but sad that people can't get it through their heads this is an issue tracker not a personal support forum.

**Comment by Drakonas** [comment]
This is something that needs to be handled in the SNES Classic mods subreddit. This tracker is for reporting known bugs to us, not troubleshooting our software. https://www.reddit.com/r/miniSNESmods/
