### ISSUE TITLE
Is it the driver or the console?

### ISSUE THREAD

**Issue by ADumke1999** [ClusterM/hakchi2#1144]
I have been looking at tons and TONS of wikis, youtube videos, and of these posts but cannot find help no matter what I try please help. (This is me trying to dump kernel)
First: it says
Found USB device: "Unknown device #1" <1F3A:EFE8>
Installing wdi driver with <nesmini.inf> at <usb_driver>
It then asks me if I want to allow the program to install so then, i press enter and this pops up,
Press Enter to exit this driver installer
I press enter and it brings me back to the previous screen
afterwards. i repeated with no luck. Went on here for help and a post said to get Zadig and install WCID driver, i tried again and nothing. I then stopped that driver thing that restricts software like that from being downloaded, but still after all that, it wont let me dump my kernel. Just on the screen with instructions and although i do the instructions, if i click install driver, it says the same thing as always... Please help... I am using hakchi 2.20, Windows 7 (shitty PC I know), and zadig 2.23. Soonest assistance would be greatly appreciated

**Comment by ghost** [comment]
Why aren’t you using the latest version of 2.21f? First recommendation is to try the latest version.

This is a place for reporting bugs of Hakchi2, not a place for users to report issues they have when trying to use the software. There is already a large online community for modding Classics over on https://www.reddit.com/r/minisnesmods Please ask you question over there. You will likely get multiple people there to help you out.

If you are confident what you’ve encountered is an actual bug within Hakchi2, report it here. It will be looked into, and if there is a fix, it will likely be implemented in the next version of Hakchi2.

**Comment by jstarks11** [comment]
I'm having the same issue even with hakchi 2.21f.  @GL1TCHTH3W0LF were you able to figure this out?

**Comment by ADumke1999** [comment]
I still need help. It is still giving me trouble, i tried removing driver
restrictions again, setting all permissions on drivers to me, and used
Zadig with no luck. Idk if the driver wont install or it just being
difficult. It says the WCID driver installs om Zadig but nothing else and
it still wont work unfortuntaly. Do tell me if u figure it out

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
