### ISSUE TITLE
Cant add games to hackchi2

### ISSUE THREAD

**Issue by evanthetank** [ClusterM/hakchi2#1145]
whenever I try to add games it will add one game then each subsequent game I try to add replaces the first and deletes it thus only allowing to only ever have 1 new game at a time

**Comment by ReyVGM** [comment]
This is a place for reporting bugs of Hakchi2, not a place for users to report issues they have when trying to use the software. There is already a large online community for modding Classics over on https://www.reddit.com/r/minisnesmods Please ask you question over there. You will likely get multiple people there to help you out.

**Comment by jrn0456** [comment]
I'm having the same issue. I understand that this isn't a place for users to report issues when we are trying to use the software, but could this be a possible bug? I already posted my question on reddit, but I figured I should follow up here just in case it's a bug issue. Thanks.
 
Edit: Nevermind, This issue can be deleted as it's a user error when downloading the ROMS.

**Comment by evanthetank** [comment]
What did u do to resolve it?

**Comment by jrn0456** [comment]
https://www.reddit.com/r/miniSNESmods/comments/7nvqf8/cant_add_games_to_hackchi2/

**Comment by ReyVGM** [comment]
"Edit: Nevermind, This issue can be deleted as it's a user error when downloading the ROMS."

It always is.
