### ISSUE TITLE
when i open a  snes game it goes black and back to folder

### ISSUE THREAD

**Issue by anthonyio073** [ClusterM/hakchi2#1147]
hi ,
i installed hakchi on my snes mini. 
did all as was explained  installed retroarch and everything.
but everytime in want to open a game the screen goed black and then sends me back to the folder i was browsing.

this happends only with snes games.
when i tried it with a gba game its work perfectly.
can someone help me with this please?

thanks!

**Comment by justahumanR** [comment]
hi,
Did you setup a modules for RetroArch?

**Comment by anthonyio073** [comment]
@justahumanR yes i did, but i think i know what the problem is.
all the games are still zipped , i unzipped one and put it on my snes and it worked, so i guess that was the problem and why the gba one did work.

**Comment by ghost** [comment]
Sounds like you figured out the problem. Please do us a favor and close this issue report, then. We're trying to help ClusterM and his mods out by trying to reduce the amount of issue reports they have to sift through. Keep this place strictly for reporting bugs in Hakchi2.

Any questions that can be answered by the modding community we're asking users to direct their question(s) to Reddit: https://www.reddit.com/r/miniSNESmods/

Thanks!

**Comment by Shoothimnow** [comment]
so its been 6 days later... and we will ask again for you to **please close this issue**

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)
