### ISSUE TITLE
How to chanche music on SNES mini?

### ISSUE THREAD

**Issue by justahumanR** [ClusterM/hakchi2#1148]
Where i can change the music on snes?

**Comment by ghost** [comment]
There's already a few discussions about this over on Reddit, such as this one:

https://www.reddit.com/r/miniSNESmods/comments/74kvff/how_feasible_is_it_to_change_the_main_menu_music/

Please help keep this place strictly for reporting bugs of Hakchi2 by asking questions like this over on the modding community's Reddit pages.

Please close this issue report. Thanks.

**Comment by Shoothimnow** [comment]
this isn't an issue... please close this issue

**Comment by justahumanR** [comment]
Sorry, i dont know
