### ISSUE TITLE
Lost SNES Original Kernel

### ISSUE THREAD

**Issue by riman643** [ClusterM/hakchi2#1149]
So I have a Mac and am using a virtual console and somehow all the hakchi files were deleted and I lost my original dump. If someone could please put me in the right direction of where to find an original SNES classic kernel that would be greatly appreciated.

**Comment by Frank-5** [comment]
Ok, first off this IS NOT the place for personal software support for Hakchi2. This is a place to report bugs and issues. This (and many other posts recently) have been cluttering up this git issue tracker with "help me this and can't find that and this doesn't work and I lost my kernel dump, blah blah blah".
It's almost entertaining if it weren't so sad that people are really this stupid that they can't get this simple concept. Anyway. Go to this really cool support forum for help and support:
https://www.reddit.com/r/minisnesmods
Lots of really bright and eager folks to help. Also make a personal effort to read the wiki and FAQs and read previous support topics.
Ok, finally, sorry to seem so harsh but GEEZ people. Educate thyself.

**Comment by riman643** [comment]
The only reason I asked here was because in researching this problem I found a thread exactly like mine with people who actually gave the OP a copy. There is no need to be so condescending and insulting to someone just looking for help.

**Comment by Frank-5** [comment]
I do understand that all you are asking for is some help.  Again this is not the place.  This is a git issue tracking area not a personal help line. If you feel that you have found a bug or issue with why you lost your original kernel image then by all means leave this open. ClusterM can then code you some software to fix the reason you lost your image.  (It’s not like there was no stern warning to back up your kernel in the readme /FAQ)  A simple google search reveals many links to OG kernels   If one were to post that info here then it is in violation of Nintendo’s copyright laws.  It’s the same as asking for a rom link to a snes game.  If you want Nintendo to come shut this area down then you are on the right track.  One link google shows for a OG kernel is https://github.com/JakobAir/SNES-Classic
You’ll have to navigate to the proper subdirectories to find the image.  Sorry for being as you say condescending.  Just frustrating to keep seeing posts that don’t relate to bugs that are trying to be fixed.

**Comment by Frank-5** [comment]
Please cause this thread. Thanks

**Comment by Frank-5** [comment]
*close

**Comment by Drakonas** [comment]
Yeah we don't want to be sharing copyright content here. It is illegal to share the kernel in most countries. Ask elsewhere.
