### ISSUE TITLE
Problem run games other consoles in hakchi2 2.12

### ISSUE THREAD

**Issue by NaikiTurincondeliphone** [ClusterM/hakchi2#115]
I have added SNES and MD games, they appear to me in the boot menu but do not run them. What should I do?

He añadido juegos de SNES y MD, me aparecen en el menú de inicio, pero no los ejecuta. ¿Qué estoy haciendo mal?

**Comment by stepik** [comment]
You should install retroarch.hmod

**Comment by NaikiTurincondeliphone** [comment]
Yeah, I forgot that step, I believed that nothing had to be done.

Thanks! Rgs.
