### ISSUE TITLE
Help with rom-based menus

### ISSUE THREAD

**Issue by Wolf2600** [ClusterM/hakchi2#1150]
Hi there, thanks for checking this out. I have a few Roms that automatically invoke configuration settings, for instance volume, or screen setting options that I can't seem to pass using the gamepad for my SNES Classic. The D-Pad will cycle between the options, or edit their setting, but no button mapped will act as an 'enter' type command and let you pass. Does anyone know of a way I can get by these and play the rom?

Using Hakchi 2/ retroarch on a SNES Classic.

Thanks again!

**Comment by Frank-5** [comment]
Ok, first off this IS NOT the place for personal software support for Hakchi2.   This is a place to report bugs and issues.  This (and many other posts recently) have been cluttering up this git issue tracker with "help me this and can't find that and this doesn't work and I lost my kernel dump, blah blah blah".  
It's almost entertaining if it weren't so sad that people are really this stupid that they can't get this simple concept.   Anyway. Go to this really cool support forum for help and support: 
https://www.reddit.com/r/minisnesmods
Lots of really bright and eager folks to help.  Also make a personal effort to read the wiki and FAQs and read previous support topics.
That being said, this is a retro arch and or MANE support question anyway.  A few clicks on Google will educate you on how to enter the priper config menu to re map whatever let you need for whatever function.  
Ok, finally, sorry to seem so harsh but GEEZ people.  Educate thyself.

**Comment by Frank-5** [comment]
*MAME

**Comment by Wolf2600** [comment]
Thanks for replying. I'll delete this
