### ISSUE TITLE
Deleted Module, Didn't Get Storage Space Back (SNES Classic)

### ISSUE THREAD

**Issue by mits5k** [ClusterM/hakchi2#1151]
Hello,

I installed the _km_mame2010_10_24_17.hmod module (found [HERE](https://mega.nz/#F!J7YFlTDL!3uYttq-FX2RbHu8FDFdqaw), if that's in any way useful). I ultimately decided to delete it and the game associated with it, but when I removed the module, I never got back the storage space on my SNES Classic. Any idea how I might go about solving this issue? Roughly 14MB isn't an insignificant amount of effectively dead space on this thing!

Thanks in advance for anybody who can help!

**Comment by ReyVGM** [comment]
This is a place for reporting bugs of Hakchi2, not a place for users to report issues they have when trying to use the software. There is already a large online community for modding Classics over on https://www.reddit.com/r/minisnesmods Please ask you question over there. You will likely get multiple people there to help you out.

**Comment by mits5k** [comment]
Sorry about that. I'd delete the thread if I could.
