### ISSUE TITLE
Sega Saturn on SNES

### ISSUE THREAD

**Issue by MoreSecxy** [ClusterM/hakchi2#1155]
I recently downloaded Rampage World Tour for snes classic (sega Saturn) and when I click the game it does not run, it takes me back to the menu... Pls help

**Comment by Shoothimnow** [comment]
Yeah... this isn't an issue with Hakchi2.... please close this issue and ask in reddit... https://www.reddit.com/r/miniSNESmods/

**Comment by ghost** [comment]
MDFMKanic says Sega Saturn games run slow. Even if you manage to get the game running, you’ll only get about 10-15 FPS. 

https://www.reddit.com/r/miniSNESmods/comments/7nn8sp/hello_everyone_here_is_where_i_would_like_things/

You may have better luck running the arcade version of Rampage World Tour through mame.

This is not an issue with Hakchi2. Please close this issue, and if you want to further discuss Sega Saturn games on the SNESC, ask your question over on Reddit.

**Comment by Shoothimnow** [comment]
Please close this issue, it doesn't belong here.  This isn't a forum
