### ISSUE TITLE
Got an error: "Access to the pass "Music.wav" is denied"

### ISSUE THREAD

**Issue by Timmak06** [ClusterM/hakchi2#1157]
I goted this error last week and I try hard to fix it: repair music, reinstal hakchi and more. But everytime when I try to do something there, I gots this error. Hope you help me.
  
![Photo](https://user-images.githubusercontent.com/35254235/34711029-d1770ca0-f571-11e7-9ac4-2e9e4a89752b.png)

**Comment by ghost** [comment]
Sounds like you are trying to change music files, and getting errors. Please close this issue and ask your question to the modding community (found on Reddit https://www.reddit.com/r/minisnesmods )

This place is where you report bugs of Hakchi2. The bug reports are looked into, and if there is a fix, it would be implemented in an update of Hakchi2. Considering the last release of Hakchi2 was in October, that means any solutions reported here (if they truly are bugs of Hakchi2) will take a while to get fixes (maybe months). That’s why we encourage people to ask on Reddit - you’ll get a quicker response (and possible fix) than you’ll get here.

**Comment by Timmak06** [comment]
Thank you so much. I am first time on GitHub can you tell me how to close issue?
