### ISSUE TITLE
N64/PSX Games not working with USB-HOST mod

### ISSUE THREAD

**Issue by TheGhettoAgent** [ClusterM/hakchi2#1159]
The snes games will work, but when I try to play n64, psx, or even nes games, it will open the game and then exit imediatley. I downloaded all the right modules and even re-did the process and still nothing. Someone please help.

Thank you in advance!

**Comment by ghost** [comment]
This is a place to report bugs of Hakchi2, not a place for users to ask how to install and run Hakchi2 properly. Please close this issue report and ask your question to the SNESC modding community on Reddit: https://www.reddit.com/r/minisnesmods

**Comment by Shoothimnow** [comment]
Not a Hakchi2 problem.  this is a mod problem running on Hakchi2, which doesn't belong in the Hakchi2 issues board.  As @maskedmaniac has stated, please **close this issue** and ask in the correct location, https://www.reddit.com/r/minisnesmods

**Comment by TheGhettoAgent** [comment]
whoops my bad. Ill close the issue
