### ISSUE TITLE
Flashing factory kernel and factory reset help on SNES classic

### ISSUE THREAD

**Issue by travelinphan** [ClusterM/hakchi2#1162]
I recently lost all sound on my mini.  Was wondering if someone could help walk me through how to flash factory kernel and do a factory reset so I could start over.  Thanks in advance

**Comment by ghost** [comment]
Should be pretty easy to get your console back to factory:

- Connect your Classic to your PC.
- Start up Hakchi2
- At the top of Hakchi2 is a drop-down menu labeled "Kernel". Click on it, and select "Uninstall". Follow the instructions in the pop up windows.

Just remember if you want to completely revert back to factory, after you uninstall Hakchi2, start up your Classic and perform a factory reset in the settings (this will erase all save states on the console).

If that's all you needed, please close this issue report. Thanks!

**Comment by travelinphan** [comment]
Thank you so much!  Final question and then I will close this issue, after uninstalling, flashing the original kernel and doing factory reset, do I just flash the custom kernel do reinstall or do I go step by step of reinstalling?

**Comment by ghost** [comment]
You'll be back to factory after uninstalling Hakchi2 and performing a factory reset within the SNESC's settings. Then, if you want to reinstall Hakchi2, you'll go through the same processes as the first time you installed Hakchi2 (flash original kernel, then custom kernel, etc).

**Comment by Shoothimnow** [comment]
If you are all good, please close this issue

**Comment by travelinphan** [comment]
Done
