### ISSUE TITLE
--Retroarch with Orignal games NOT WORKING!!

### ISSUE THREAD

**Issue by ConnorC10** [ClusterM/hakchi2#1166]
I used --retroarch so all games would run threw retroarch and be able to play them full screen. when i did this i played contra 3 for a good 30 minutes then went to turn up the volume and there was no audio i knew it must just be because of retroarch but its just audio so i left it i kept playing realized there is way more lags it was playable but annoying. then went to donkey kong country the game wouldn't even start and all of the games were affected in different ways whether they wouldn't start or the audio was affected. but only the original 22 games had theses problems. when i turn off --retroarch they run fine but i want to run the games in full screen. do i have to download the roms of each one or is there a fix where i dont loose my saves or have to download them.

**Comment by ghost** [comment]
What version of Hakchi2 are you using?

(Previous versions of Hakchi2 had audio glitches where the stock game audio would be there when you start the game, but would cut out at some point. Version 2.21f is supposed to include the audio fix.)

https://www.reddit.com/r/miniSNESmods/comments/78zsny/anyone_else_getting_an_audio_hiccup_when_playing/

**Comment by ConnorC10** [comment]
I'm using the latest version just hacked my snes around a week ago V2.21

**Comment by ghost** [comment]
Okay. One suggestion I've read over on Reddit is to remove the Retroarch core and then reinstall it.

https://www.reddit.com/r/miniSNESmods/comments/7fs9ey/audio_went_out_on_retroarch_xore/

With the latest versions of hakchi2, you can export your game saves, so if you are concerned you may lose your saves, export them to your PC as a back up, but the only way you will lose your game saves is performing a factory reset in the console's settings. Basically you can uninstall and reinstall Hakchi2 and not lose your game saves.

Another thread says the stock games have attached PCM data which causes audio problems when running through Retroarch, so you may just want to run them without Retroarch. Seems like the most painless workaround.

**Comment by ConnorC10** [comment]
thank you

**Comment by Shoothimnow** [comment]
RetroArch issues belong on the RetroArch issues board, not the Hakchi2 issues board...

https://github.com/ClusterM/retroarch-clover/issues

please close and reopen in the correct location

**Comment by Shoothimnow** [comment]
This is more of a "anyone, help!" post instead of a "ClusterM, everyone needs this code fix" issue.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

Or... in the RetroArch issues board : https://github.com/ClusterM/retroarch-clover/issues
