### ISSUE TITLE
Hackchi not detecting my Atari Games CLOSED

### ISSUE THREAD

**Issue by ConnorC10** [ClusterM/hakchi2#1168]
I added plenty of sega, nes, snes, GB/GBC/GBA etc... games but tried to add Atari games i downloaded the roms for empuradice (i think that's how you spell it) opened hackchi and went to add more games went to the roms location but they did not show up. 
I think this is a total noob question and I'm doing something just a little bit wrong or need to download the roms from a different website but i really need some help. Thanks!

**Comment by ghost** [comment]
I'm sure this is a configuration issue. Check to see what others have done to get Atari games running, like this thread here:

https://www.reddit.com/r/miniSNESmods/comments/766wl2/stellaaaaaaaaa_help_with_the_atari_2600_core_for/

This place is where people report bugs of Hakchi2, not a place to ask how to set it up properly. Please close this issue report, and in the future, ask your questions about how to set up and use Hakchi2 on the modding community's Reddit pages:

https://www.reddit.com/r/miniSNESmods/

**Comment by Shoothimnow** [comment]
yeah, this is still open.... and definitely not a Hakchi2 problem.  As if you were able to hack the SNES mini, then Hakchi2 is working.  If you are having a problem with RetroArch, that's not a Hakchi2 problem.  

Regardless though... this case is still open...

**Comment by ghost** [comment]
In case you don't know how to close the issue, click on the button in the reply box at the bottom of the page:

![untitled](https://user-images.githubusercontent.com/25872534/34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c.jpg)
