### ISSUE TITLE
"Smoothing filter" reported on by default.

### ISSUE THREAD

**Issue by FlyingBurrito76** [ClusterM/hakchi2#117]
Users on Reddit report that the "smoothing filter" is on in RetroArch in the release build of 2.12. Based on the "pixel perfect"/HD nature of the the NES Classic's output, I believe most users would prefer the filter OFF. Can you please update the next build to have "smoothing filter" off by default or have an option from within the Hakchi 2,12 menu to turn it on/off.

*EDIT* Replaced the HMOD file with one that has smoothing off and corrected my issue.

**Comment by stepik** [comment]
It's on when you use 4*3 display settings. Try pixel perfect settings.

**Comment by FlyingBurrito76** [comment]
I'd prefer that it be off entirely. I'm seeing people report that it was turned off and a new version uploaded without smoothing? Can anybody confirm that? I don't want to flash until I know that smoothing has been removed and what the requirements are to have it turned off by default.

**Comment by ajmi982** [comment]
Someone might have made their own version of the RetroArch mod? This isn't a Hakchi issue ita the RetroArch mod config that would need to be changed.

**Comment by baconcow** [comment]
Someone on [Reddit hacked the file](https://www.reddit.com/r/nesclassicmods/comments/5v029d/quick_mod_of_retroarch_mod_no_smooth_no_filter/) to remove the smoothing. Sounds like it would be better with this option off. I dislike smoothing features of emulators as they create an unnatural image.

**Comment by FlyingBurrito76** [comment]
I understand that RetroArch is a separate module, and it's not strictly a Hakchi2 issue, but this release does "include" (or at least link to) the appropriate files to incorporate RetroArch into the 2.12 software. So, if possible can we get confirmation that the current versions of the "retroarch.hmod" file that's currently linked to download has the filter option OFF, or get a version that has it set to OFF?

**Comment by baconcow** [comment]
What he is saying is to make this request on the GitHub for the mod and it will be seen there by ClusterM. Otherwise, leaving it here, it is unfortunately bound to be ignored due to being off-topic. The modified version is by a Reddit member and is unofficial.

**Comment by FlyingBurrito76** [comment]
Thanks for the link to the forked GitHub link baconcow!! That mod file totally worked! Sorry I'm new to reporting "issues" related to stuff like this here. I figured that the "issues" was the correct place to go. But I'm all sorted now and I assume that at some point other people with the bad hmod file with smoothing on will figure out how to replace theirs too.

**Comment by baconcow** [comment]
No problem. If you have not already, check out the [Official GBAtemp hakchi2 thread](https://gbatemp.net/threads/hakchi2-nes-mini-very-simple-pimp-tool.456256/) as there is a lot of discussion on different things, including the retroarch.hmod.

**Comment by FlyingBurrito76** [comment]
Oh yeah, I've looked at that thread ... but my lord it's super long and a bit unruly to sort through.

**Comment by ClusterM** [comment]
This is not RetroArch repository.
