### ISSUE TITLE
"Error: Input string was not in correct format"

### ISSUE THREAD

**Issue by Mateotheshark** [ClusterM/hakchi2#1174]
Has anyone received this error message before? I cant seem to find anything on the web about it....it has been popping up while running the latest Hakchi version. It happens about 20% way through when syncing games after going through all other proper steps...Dump, Flash Custom Kernel, etc...There is nothing about it on Reddit....I apologize in advance to the GitHub Police if I'm posting this in the wrong place...I will delete it if nobody knows anything about it.

**Comment by Shoothimnow** [comment]
Reddit would be a better place to ask (this issues board is more for ClusterM to know that "this specific set of actions causes the SNESC to ______, and everyone is having this issue, please add a code fix")

https://www.reddit.com/r/miniSNESmods/

Thanks man.
