### ISSUE TITLE
bugs in Top gear 2 and Tiny toon sport challenge

### ISSUE THREAD

**Issue by Khalid69** [ClusterM/hakchi2#1179]
Dear 
 the following issues have been notice when playing Top gears 2 and Tiny toon sport challenge:
1- Top gear 2 in two player mode the game freeze and the screen turns black.
2- Tiny toon sport challenge: in weight lifting challenge the weight tools misplaced and disappear.

This two issues have been noticed so far.

Also we would be thankful if you could manage to improve the graphics and the filter.

Regards

**Comment by Shoothimnow** [comment]
This is a "anyone, help!  RetroArch isn't working!" issue, with zero reasons to be in the Hakchi2 issues board.

Please close this issue and repost in reddit : https://www.reddit.com/r/miniSNESmods/

![34943662-8acebffc-f9ca-11e7-99e9-9a0cb522d41c](https://user-images.githubusercontent.com/32903303/35013211-a694fe3e-fada-11e7-8a07-249b28afcc32.jpg)

Or... in the RetroArch issues board : https://github.com/ClusterM/retroarch-clover/issues as seeing that you were able to add the games via Hakchi2 (the computer application) flawlessly, then the... problem... isn't.... Hakchi2.... and it is instead a problem with RetroArch (the emulator).  Again though, please close this issue... it's generating garbage over here on this issues board (this isn't a forum)
