### ISSUE TITLE
Adding cores

### ISSUE THREAD

**Issue by nappymike** [ClusterM/hakchi2#118]
I would like to swap the GBA core out with a different one that runs a lot smoother....I have the core that I would like to use, I just don't know how to swap it...any help would be appreciated.

**Comment by sanjay900** [comment]
Also, this should really be on the retroarch project.

**Comment by sanjay900** [comment]
What core are you thinking of using? Im looking for a smoother core as well.

**Comment by nappymike** [comment]
MGBA

**Comment by sanjay900** [comment]
If you plan to use gba, i would recommend looking for a version of retroarch with all the filters disabled, it speeds that up a lot.

**Comment by baconcow** [comment]
You should remake this issue at the [proper GitHub repo, here](https://github.com/ClusterM/retroarch-clover).

**Comment by ClusterM** [comment]
This is not RetroArch repository.
