### ISSUE TITLE
Не устанавливается драйвер

### ISSUE THREAD

**Issue by Strongleong** [ClusterM/hakchi2#1182]
@ClusterM, пожалуйста, помоги! Я все делал, по инструкции, включил snes в режиме прошивки, нажал на кнопку установить драйвер. Вылезло окно консоли, написано, что драйвер устанавливается. Вроде все установилось, нажал enter, но ничего не произошло. Драйвер не установился, ни каких ошибок не вылезало. 
![image](https://user-images.githubusercontent.com/17177071/35469105-34185eb8-0382-11e8-815c-5b88061747f3.png)
![image](https://user-images.githubusercontent.com/17177071/35469108-456a37ae-0382-11e8-90a2-b0875fddf1b8.png)

**Comment by gBaH0JI9I** [comment]
@Strongleong 
Винда х64? На время отключи в винде проверку подписи устанавливаемых драйверов, иначе он не встанет.

> [Как отключить, читать например тут](http://windows10x.ru/otklyuchenie-proverki-cifrovoj-podpisi-drajverov/)

**Comment by Strongleong** [comment]
@gBaH0JI9I
Да, винда x64. Пробовал поставить и с подписью, и без, так что дело не в ней.

**Comment by gBaH0JI9I** [comment]
В ней.
Разубеждать не стану. Скажу лишь, что вопрос задавался уже не единожды, одному из таких я помогал ставить драйвер по удаленке. Тоже не верил.
Есть еще два фактора - смени провод за заведомо рабочий и смени порт USB. Также не втыкай в USB 3.0. 
Удачи.

**Comment by Strongleong** [comment]
@gBaH0JI9I 
Я еще раз попытался поставить драйвер. И с проверкой на подпись, и без нее. Комп перезагружал. Кабель рабочий, USB тоже. Во всяком случае, комп видит мой телефон через этот кабель и USB.

**Comment by dbelyaev** [comment]
@Strongleong порты, надеюсь, не на передней панели (если стационарка, а не ноутбук) используешь?

**Comment by dbelyaev** [comment]
@Strongleong удалось решить проблему?

**Comment by Strongleong** [comment]
@dbelyaev 
Пробовал **абсолютно** все порты. Так и не решилось ничего. Так же как оказалось мой комп и зеркалку не видит -_- 
Я думаю, что это из-за той же самой проблемы

**Comment by dbelyaev** [comment]
@Strongleong хорошо, спасибо за ответ.

Закрываю Issue так как проблема на стороне пользователя (железо).

**Comment by deagostini6** [comment]
Добрый день !!! не могу закачать игры на snes mini выдает ошибку найдено устройство USB 1f3a : efe8 Кто подскажет как это исправить Драйвер не устанавливается,отключил проверку  подписи  устанавлемых драйверов и это тоже не ничего не дало И на моем пк на материнке только USB 3.0 а спереди 2.0 который не желательно
