### ISSUE TITLE
Images (PNG or JPG) do not load when adding game from a 7zip file

### ISSUE THREAD

**Issue by baconcow** [ClusterM/hakchi2#119]
When adding more games (from the button selection or drag-and-drop) that are in 7zip files, their identically-named images will not load as per the release note: "Box art images will be load automatically if PNG or JPEG file with same name is available.". Adding more games, unzipped, does not have this issue. However, since you can add zipped games, I see this features as not working as expected.

If you put the image in the 7zip file, with the game file, it will ask to select a file to add (in a pop-up form), when adding more games. If the image file is also in the 7zip file, it will upload it correctly. Therefore, it seems the application is looking within the zip file for the image file, instead of the base directory. If it is going to look in the 7zip file, for the image, the application should just ignore the presence of image(s) so that the games can be added without the "select file" pop-up form.

Edit: [My proposed fix](https://github.com/ClusterM/hakchi2/pull/178).

**Comment by ClusterM** [comment]
Fixed.
