### ISSUE TITLE
[REQUEST] Make a fonction for video capturing in hakchi2 [feature request]

### ISSUE THREAD

**Issue by SuperMK8** [ClusterM/hakchi2#1190]
I have a idea : Can you do fonction in hakchi2 for video capturing... but i think that will have some problems

1. Lagging : One screenshot make lag. But 60FPS or 30FPS or custom will be very laggy!

2. USB : That not very a problem but you need to have hakchi2 open on you computer and your TV power on.

Well i have solution: 

For the one : I dont know (lol)

For the two : Make a in real time mini (S)NES

A thing: ![capture](https://user-images.githubusercontent.com/36115005/35771723-a22e78c4-0931-11e8-950a-d6307fb6fcfa.PNG)

**Comment by Drakonas** [comment]
This would be literally impossible, as the SNES Classic would have to send a video signal twice, once through the HDMI and once through the USB. This would make playing games impossibly laggy. Closing this as won't fix. Also consider that a lot of the USB is already in use by the power being sent through it.
