### ISSUE TITLE
Can't install Nes mini not found drivers on my windows 10

### ISSUE THREAD

**Issue by DRUMMER2K18** [ClusterM/hakchi2#1191]
So i been having trouble installing the driver for my computer when i try to add more games and try to  install drivers it say Nes mini not found
i try ZADIG but no luck also i have  Try to disable driver signature but nothing is working i dont know what to do anymore i need help what am i doing wrong or is there a correct way to do it thanks

**Comment by Drakonas** [comment]
Please discuss this on Reddit instead of opening a ticket similar to like 5 other tickets in our tracker which are leading to nowhere because we can't produce these problems on our end. https://www.reddit.com/r/miniSNESmods/
