### ISSUE TITLE
PATCH: Small typos in wiki FAQ

### ISSUE THREAD

**Issue by jesus2099** [ClusterM/hakchi2#1194]
I cannot push to wiki repo.
I have spotted two little typos in the wiki FAQ.
I don’t know if patch files are readable: [wiki_FAQ_patches.zip](https://github.com/ClusterM/hakchi2/files/1706743/wiki_FAQ_patches.zip)
:)

**Comment by dbelyaev** [comment]
@jesus2099 
Hello! I fixed typos in FAQ based on your patch. Sorry I could not do it via PR with you authored commits from the patch, as Github handles Wiki as a separate git repository and does not fully support the whole PR\review\merge routines. But it is fixed now manually!

Thank you for your help!

**Comment by dbelyaev** [comment]
I am now closing this issue as fixed.

**Comment by jesus2099** [comment]
You’re welcome. ☺
