### ISSUE TITLE
Games not loading

### ISSUE THREAD

**Issue by DaveB45ACP** [ClusterM/hakchi2#1196]
Games show up in folder on NES classic, but when I try to run them, it goes back to the home screen. Only using NES games such as TMNT, Cobra Command, Dragon Warrior 1-4, etc. Would love to play these classics from my childhood, but can't. Please help. 

Hakchi 2.21f
Windows 10

**Comment by Drakonas** [comment]
This is an issue tracker. The intent for an issue tracker is to say "I have a problem, and I found the issue with your code to be at line 235, row 23", NOT "Help I don't know what to do.". The latter kind of questions go here: https://www.reddit.com/r/miniSNESmods/ Thanks.
