### ISSUE TITLE
I have a problem with the memory of my SNES MINI

### ISSUE THREAD

**Issue by Mickybgdu67** [ClusterM/hakchi2#1198]
Hi, I am currently facing a problem with the memory of my snes mini, or maybe it is an issue with Hakchi itself, I still don't know. Indeed, when I'm trying to add new games to my SNES (with a memory of 126.3/167.7 mb taken), the hakchi software says that I don't have "enough space on the hardrive". 

I have already tried to delete some games to free more space (I came back then at a memory of 110mb taken) but even with that manipulation, the same messsage appears so I have the feeling that I am a bit stuck here. 

Does anyone of you have a potential solution please? It could be a big help. Many thanks in advance

**Comment by Frank-5** [comment]
Not a help me site.  Close this and go ask on Reddit.

**Comment by Frank-5** [comment]
Repeat.   This is not a please help me site.
