### ISSUE TITLE
Can't uninstall / Snes don't works and lost my dump

### ISSUE THREAD

**Issue by Laserwelt** [ClusterM/hakchi2#1199]
The debug mode tolds me:

![20180212_113900](https://user-images.githubusercontent.com/36404968/36093409-debc94dc-0fea-11e8-9533-b82dc47605c1.jpg)

Greetings Laserwelt

**Comment by Drakonas** [comment]
This is a place for reporting bugs you know the cause of, not a "HELP ME" forum. Please ask this on Reddit: https://www.reddit.com/r/miniSNESmods/
