### ISSUE TITLE
Hakchi2 ver 2.08 not responding or 2.06 always waiting on nes

### ISSUE THREAD

**Issue by debtslave** [ClusterM/hakchi2#12]
I am trying to dump the kernal on version 2.08 and it says not responding.

![image](https://cloud.githubusercontent.com/assets/25160518/21998859/bfe82ad0-dbfc-11e6-96c4-3362a01e2971.png)

I also tried an older version 2.06 and when I try to upload games button it shows me the 5 steps then nothing happens further always waiting on nes. 

I made sure the driver was loaded and it does see the nesmini under usb fine.

Please help sir

**Comment by PATWIST** [comment]
Hello, I have no problem with v2.07, did you tried v2.07 ???
https://github.com/ClusterM/hakchi2/releases/tag/2.07

I made video tutorial: https://www.youtube.com/watch?v=z-VV8pI8oKI

BTW: It seems that you have a lot games to add and it might dont work properly after, rather stay under 100 games :-)

**Comment by debtslave** [comment]
![image](https://cloud.githubusercontent.com/assets/25160518/22004743/dbbc35c2-dc23-11e6-95c2-d509f7af4d02.png)

this is what i get with only one game using your version u mentioned 2.07. i only see the waiting for nes mini screen it never dumps the kernal. what i am doing wrong. it loads the driver fine. in device manager it shows nes mini

**Comment by soulctcher** [comment]
The screen you show in this screenshot is basically waiting on the NES to enter FEL mode.  Literally hold down the RESET button and press/release the POWER button while continuing to hold the RESET button for about 5-6 full seconds.

**Comment by ClusterM** [comment]
Try version 2.09 please. Contact me if problem isn't gone: clusterrr@clusterrr.com

**Comment by debtslave** [comment]
Thanks for the response back.
I resolved the issue apparently there was a usb conflict with my ports and when i unplugged all of my existing usb connections it worked.
Thanks for your great work and awesome customer service.
I will be sending some donation soon.
Bryan 

    On Wednesday, January 18, 2017 4:49 PM, ClusterM <notifications@github.com> wrote:
 

 Try version 2.09 please. Contact me if problem isn't gone: clusterrr@clusterrr.com—

**Comment by Codename77** [comment]
Bonjour, j'ai ce problème avec la version 2.31, il m'est demandé d'extraire le kernel, d'installer un driver et là, une fenêtre de commande s'ouvre, me donne un chemin d'installation dans un dossier hakchi 2 et la fenêtre de dialogue me dit: en attente de votre NES mini
