### ISSUE TITLE
Feature request: upload archived ROMs

### ISSUE THREAD

**Issue by abijanfar** [ClusterM/hakchi2#120]
upload archived ROMs (.zip or .7z) to save precious space on NES Mini

**Comment by baconcow** [comment]
I second this request. I was hoping that RetroArch could at least access zipped ROMs. Those bigger ROMs archive well and sure to take up a lot of room uncompressed.

**Comment by missionfloyd** [comment]
I agree. We don't have a whole lot of space to work with, so retroarch roms should really be zipped.

**Comment by abijanfar** [comment]
Looks like its coming in the next release :)
