### ISSUE TITLE
Found USB device: Unknown Device #1 (1F3A:EFE8) при установке драйвера

### ISSUE THREAD

**Issue by tomfarrium** [ClusterM/hakchi2#1200]
Приставка была прошита ранее, но та версии ОС с которой ее шили была потеряна.
Теперь при любой попытки повлиять на приставку через hakchi2 висит окно установки драйвера, в командной строке которого "сабж" и предложение нажать интер для выхода из установки. Окошко установки драйвера не пропадает и само собой ни чего не происходит. 

Что  мне делать????

Я даже все стереть не могу - не получается, ведь необходимо сдампить ядро, а это тоже требует проверки на установку драйвера.

АААА...
Спасити!

**Comment by Frank-5** [comment]
Это не место, чтобы обратиться за помощью. Это место для сообщения об ошибках с Хакчи. Это не ошибка. Пожалуйста, удалите это сообщение и спросите на форуме SNES Reddit. Благодарю. а также, пожалуйста, напишите на английском языке.

**Comment by Frank-5** [comment]
Это не место, чтобы обратиться за помощью. Это место для сообщения об ошибках от HAKCHI. Это не ошибка. Пожалуйста, удалите это сообщение и спросите на форуме SNES Reddit. Спасибо. а также, пожалуйста, напишите на английском языке.

**Comment by Frank-5** [comment]
Specifically the mini SNES Mods subreddit. https://www.reddit.com/r/miniSNESmods/

**Comment by Frank-5** [comment]
And as I said above,  please post in English so that those of us less linguistically inclined can read these posts.  Thank you.

**Comment by Shoothimnow** [comment]
@Frank-5, ClusterM is Russian.  I just learn to let others deal with these, lol, as google translators can only do so much.  So as much as I would love to support the English only, I can't knowing that the creator is Russian =\  **Edit** I have no idea what this topic is about, as ain't nobody got time to translate that.

**Comment by Frank-5** [comment]
@Shoothimnow, Yes I'm very aware that ClusterM is Russian.  And, lol, true that Google translators can only do so much, but it is Very obvious this is a cry for help, Russian or Not, and this is NOT the place to be continually posting non bug related issues.  So,lol, I'll not try to butt in and help police this github repo. I'll leave that to you folks. Lol

**Comment by Shoothimnow** [comment]
I'm just known for everyone hating me (everywhere) =P.  And I don't mind that.  I appreciate those who support the cause!  I was just chirping in lol, I'll go back into my hole (lol)

**Comment by Frank-5** [comment]
Haha, yes I understand about being in holes!   I usually dig ones way too deep to get out of! ;-)

**Comment by Drakonas** [comment]
@Shoothimnow @Frank-5 I will say I appreciate you both for stepping in here while I've been dealing with family issues over the last few months. I'm closing this as it needs to be asked on Reddit.

**Comment by Frank-5** [comment]
Thank you @Drakonas,  I'm so sorry to hear that you have had to deal with family issues.  Please know you will be in my thoughts and prayers hoping that all will be well. You do a fantastic job monitoring this git repo and it is appreciated very much!!

**Comment by Drakonas** [comment]
Thank you @Frank-5 That is a blessing to hear.
