### ISSUE TITLE
Snes Mini freeze issues FF3

### ISSUE THREAD

**Issue by IBEWsparky540** [ClusterM/hakchi2#1201]
I used hakchi before I ever used my system. I have HOURS invested in Final Fantasy 3. I have save points and the hard saves. I tried re loading old saves and save points and FF3 still freezes at the same point after dialog with Terra after she changes back from her esper form after doing the magitek factory. Any way to fix this? If you can fix this issue I will make a generous donation.

**Comment by Drakonas** [comment]
This is not a place to find what the issue is. Bug trackers are a place to report issues that one knows the cause of, not a place to go "HELP ME". Please discuss this on Reddit instead: https://www.reddit.com/r/miniSNESmods/

**Comment by IBEWsparky540** [comment]
Sorry about that. Im new to this. Thank you for sending the link
