### ISSUE TITLE
Invalid Console

### ISSUE THREAD

**Issue by kristenvlogan** [ClusterM/hakchi2#1202]
Even though I have my SNES mini connected, I keep getting the error, "Invalid console selected! Detected console: NES" Any suggestions? I have selected the SNES and double checked that it is selected.﻿

**Comment by jesusrodcis** [comment]
Facing same issue

**Comment by Frank-5** [comment]
You need to ask this on the mini SNES Mods subreddit. This is not a personal help line for Hakchi,  this is a bug tracker.  You have something wrong on your end.  https://www.reddit.com/r/miniSNESmods/

**Comment by Drakonas** [comment]
As Frank-5 says, this is a place to state what the problem is and what the cause of it is, not "Help me I don't know what to do". That is what the subreddit is for.
