### ISSUE TITLE
different computer

### ISSUE THREAD

**Issue by allpigmustdie** [ClusterM/hakchi2#1206]
Sorry if there is another thread, didn't found what i was looking for.
So my girlfriend got her friend to add some games on her snes mini but now i want to add more from my personal computer wich is a different device. I dont care about losing the already added game.  Since the snes was already "hacked", can i simply click on sync or do i have to follow instruction like if it was the first time. I dont have the original kernel dump and i dont want to mess thing up. 
thank you for your time

**Comment by Frank-5** [comment]
You need to ask this on the mini SNES Mods subreddit. This is not a personal help line for Hakchi, this is a bug tracker. You have something wrong on your end. https://www.reddit.com/r/miniSNESmods/

**Comment by Drakonas** [comment]
As Frank-5 states, this needs to be asked on reddit. This is not a place to ask general questions.
