### ISSUE TITLE
Add Illusion of Gaia patch

### ISSUE THREAD

**Issue by angelusjmw** [ClusterM/hakchi2#1208]
please include the illusion of gaia fix with your next update of the app

https://drive.google.com/file/d/1cPHkJCaNhLYBIx11aBVKJu7dOSPOf8oE/view
that did work for my snes mini classic

have been able to play it since

and i don't want to have to add the fix every time i hack my snes mini classic

**Comment by Alftron** [comment]
If the patch isn't officially merged from my pull request, then you could just as easily rename your patch so it is prefixed with the CRC32 of your Illusion Of Gaia file, for example "**1c3848c0-Illusion of Gaia.ips**" and put it inside the "**patches**" folder of the hakchi2 directory, and that _should_ work every time.
There's also a readme.txt in the patches directory that explains it.
