### ISSUE TITLE
Подскажите как запустить FDS

### ISSUE THREAD

**Issue by Flexeron** [ClusterM/hakchi2#1217]
Уже долго копаюсь, не могу найти как запустить.

**Comment by gBaH0JI9I** [comment]
Читай info к модулям.
Нужно положить disksys.rom в папку /etc/libretro/system/ на консоли.

**Comment by dbelyaev** [comment]
@Flexeron это официальный репозиторий программы. Раздел "Issues" используется для того чтобы, сообщать об обнаруженных багах. К сожалению, это не форум поддержки, и такие запросы обычно будут закрыты без ответа.

Пожалуйста, все вопросы о том как и что делается в программе задавайте на сторонних форумах (реддит и аналоги).
