### ISSUE TITLE
Super Nintendo Mini storage space lost

### ISSUE THREAD

**Issue by cezarartsound** [ClusterM/hakchi2#1224]
Hello, I'm using Hakchi 2.30 and it seems that I lost storage space after install the same modules more than once. Currently I only have 182 MB of free space. And it only increases to 236 MB when I uninstall all modules. What can I do to solve this issue?

**Comment by Shoothimnow** [comment]
That's about how much space you are suppose to have.  Game Saves, the OS System, it all takes up space

**Comment by Dominik92B** [comment]
With the retroarch mod you reach something like 247mb, but I'm having a similar issue since I updated to 2.30. The free space fluctuate much more than before

**Comment by youngtune27** [comment]
cezarartsound Have you used hakchi before? And updated versions or is this your first time using it? And did you notice it higher than 236 at the beginning?

**Comment by cezarartsound** [comment]
It was the first time I used. But I think that everything is normal and the problem was between the screen and de chair. I though that it had much more than 236 when I added the first 200 snes games without installing any module. And I just saw the free space decreasing every time I installed modules because I was adding more modules every time. Sorry guys and thank you.
