### ISSUE TITLE
Retroarch not working - NES games won't load after recent Hackchi2 update

### ISSUE THREAD

**Issue by Nimick26** [ClusterM/hakchi2#1225]
I saw a thread on this subject earlier but it closed. I downloaded and installed the hot fix for retroarch for my snes classic mini, but my NES games still won't load. I tried completely uninstalling hackchi and restored factory settings on my SNES mini, then started from scratch with the latest Hackchi and Retroarch versions and my NES games still won't play. I also tried deleting all my games from Hackchi and reloading them, and this also didn't work. SNES games play fine still but I also can't access retroarch through the console from the menu or in game. Any ideas what might be happening here?

**Comment by hoderer** [comment]
Since this is most likely a retroarch issue, maybe it's a good idea to post that question here:
https://www.reddit.com/r/miniSNESmods/

EDIT: It's a command line issue. Newer retroarch versions no longer load NES games with /bin /nes you have to use /bin /fceumm or /bin /nestopia. You can change the command line of multiple games at once with the "find and replace"-tool. I think there's a youtube video how to do that, just search a bit around.

**Comment by Nimick26** [comment]
Hmm...I tried both command line suggestions with no luck. There was a slight improvement though as before when I tried to run NES games the screen would go black and I could only reset the system but shutting it down and unplugging. Now, with either of these command lines the screen goes black for a second but then returns the to main menu screen.

**Comment by hoderer** [comment]
Do you have a propper retroarch version installed? A newer one of KMFDManic's Set?
https://github.com/KMFDManic/NESC-SNESC-Modifications/releases/

**Comment by Nimick26** [comment]
Yeah, I'm using _km_retroarch_171_standard_2_27_18.hmod

**Comment by Nimick26** [comment]
Ok, so I ran the Hackchi debug version, here's my log. Towards the end of it I synced a couple of NES games and then tried to run one when the system went to a black screen and I had to do a hard shutdown. Can anyone tell what's happening here?

(I also went back to using the current version of Retroarch provided by ClusterM)

[debuglog.txt](https://github.com/ClusterM/hakchi2/files/1776409/debuglog.txt)

**Comment by Nimick26** [comment]
Ok, I figured it out. I had added my roms by copying them directly into the hackchi/snes_games file. This worked for snes games but apparently the nes games don't work if you do this. I finally got the nes games to work by dragging and dropping them into Hackchi and letting it "process" the roms. So problem solved...
