### ISSUE TITLE
How do I add/remove games AFTER ive already modded and added games

### ISSUE THREAD

**Issue by phillipjorgenson** [ClusterM/hakchi2#1229]
Ive already successfully modded my snes classic and added just over 100 games.  But, after going through there are games that dont work, games without box art, and games ive missed adding.   Do id like to do some final finishes,not sure whether i need to flash the kernel again or if I have to reset to default and start over again from scratch..If you could leave a brief step by step (as im almost 40 and fairly computer illiterate)  It would really help, thanks.

**Comment by Stone2k18** [comment]
If you want to delete games.  All you need to do is go to your Hackchi page.  Go to the games list and just delete or UNcheck the games you dont want on your system. To edit the box art just highlight the games and right click. Select download box art. Make sure you sync when youre done.    Hope this helped.

**Comment by dbelyaev** [comment]
I am closing this issue as @Stone2k18's reply gives a good explanation to given question.

**Comment by phillipjorgenson** [comment]
Thanks for getting back to me



________________________________

**Comment by phillipjorgenson** [comment]
Thanks for getting back to me


________________________________
