### ISSUE TITLE
''Down+Select'' only freeze the game when using retroarch since 2.30 update.

### ISSUE THREAD

**Issue by ERK369** [ClusterM/hakchi2#1234]
First, I want to say thanks for this awesome program. The only problem I've noticed is, since the last 2.30 update, all my ''retroarched games'' are freezing when I'm pressing ''Down+Select''. If I press the reset button, nothing happen as far as then I power off (the led stay on). The only option that I have, is to disconnect the power usb from the nes mini to restart the console. My setting is already check for ''Use button combination to reset''. Anyone else experiment this issue yet?

P.S.: Sorry for my english... :)

**Comment by jimmyjamez83** [comment]
This is my 1st install but i've been having the same issue and i've tried to re-install with the same results over and over..

Edit: Ok downloaded the New retroarch_with_cores.zip  > and extract to hakchi2 folder . I put mine in the usermods folder that's in mine. Now works fine, sometimes it takes a bit but no more lock ups.

https://github.com/ClusterM/retroarch-clover/releases/

**Comment by ERK369** [comment]
A big thanks to you @jimmyjamez83 , it works fine for me now!!! 893 nes roms on my mini nes are working almost pecfectly!

**Comment by dbelyaev** [comment]
Nice to hear that it helped you to solve the problem.

Closing this issue.
