### ISSUE TITLE
retro arch module problem

### ISSUE THREAD

**Issue by thedon1976** [ClusterM/hakchi2#1237]
i recently tried to add different game modules gba sega and the like and i went and use the retroarch.hmod picked the ones that i wanted loaded them press ok, not ok i have nes and snes games on my snes so i loaded a few games on just to see if they would gba sega, none would work and all of my nes games stop working my snes games where fine, so i went in dumped the customize kernel put the original kernel back on and put it back to its original state then just had the original games put the custom kernel back on without the gba and segas and still my nes games won't but the system will play all snes games just fine i can live without but hey if you hack it stack it so could somebody anybody tell me what im doing wrong thanks.

**Comment by Stone2k18** [comment]
You need to add different mods every system has a different mod for the game to work.  Also the command lines need to be changed in order for the game to work.  Heres a youtube link.  In the video theres a link to get other mods. Hope this helps you


https://youtu.be/tYBo2tDso3A

**Comment by dbelyaev** [comment]
@thedon1976 closing this issue as this is not a support forum. It is a place to report bugs with hakchi2 application.
