### ISSUE TITLE
[SOLVED] *Certain* SNES, GBA Games Don't Save

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#124]
Hi Cluster/Mad Monkey/Others,

First off you all are doing an incredible job for this community.  Please by all means know your work is very much appreciated.

I was tinkering around with a few of my games and noticed a couple do not create a save state when you exit the game (by hitting the hotkey or reset button).  The screen returns to the UI as if the game was never launched, you can't go back and resume play, nor is it saved.  

I'm wondering if there is something that prevents it from grabbing a screen shot?!?  A game such as Links Awakening (B/W) doesn't work, but the colored DX version works fine, so I don't think it is just RAM alone.  It may be the ROM itself, not sure, but it is consistent in the games listed above.  Perhaps if it is problem with getting a screenshot or for emulators where you just can't get a screenshot, you could default an image in there (maybe the box art or date/time?)

**Comment by sanjay900** [comment]
I had this issue with one of the gameboy games i was playing too.

**Comment by bfluryx1234** [comment]
I just heard a suggestion that it may be the name of the ROM itself that is causing the issue.  The post recommended reducing the length of the name and removing special characters (such as a period).  Since two of these I know had a period (Version 1.1) in the ROM name, I'll give this a try and report back.

**Comment by sanjay900** [comment]
I think your on to something, there was a . in the name.

**Comment by bfluryx1234** [comment]
I confirmed this fixed my issue.  So anyone else having this problem make sure to remove the additional "." from the actual file name (not the display name).  Might be a problem with other characters as well... 

Should I close this issue, or is there a FAQ that should first be updated to perhaps help others out?

**Comment by sanjay900** [comment]
I feel like we should leave this, as while removing .'s is a workaround, it would be nice if they just worked.
