### ISSUE TITLE
Switch SFC Classic to western firmware?

### ISSUE THREAD

**Issue by dndlnx** [ClusterM/hakchi2#1242]
No issue, just inquiring. Is a total conversion recommended, games and all? I'm interested in the looks of the console. Sure I could just get the EU version, but it'd be neat to have the "Super Famicom" labelling as well.  

I saw a couple reddit posts about this, one person said they were successful but lost more space than anticipated. Any problem(s) I might encounter, other than that? I'm not trying to fit 100 games on there, just a select group of omitted classics. RPG's etc.

**Comment by dbelyaev** [comment]
Hello, @dndlnx!

Thanks for you inquiring but we are trying to have issue log clean as possible to avoid overseeing real reported bugs in hakchi application.

Please, ask your question on specific forums or subreddits, good place to start is here: https://www.reddit.com/r/miniSNESmods/

Closing this issue.
