### ISSUE TITLE
Memory size changing

### ISSUE THREAD

**Issue by phillipjorgenson** [ClusterM/hakchi2#1243]
Ive had no problems so  far, i went to delete few games,  when I last synchronized I had around 200 MB space on my snes classic, and I had used approx 179 MBs, I went to  synchronize after deleting a  few games but it refused to synchronize telling me I now had too many games as is,weird considering i had space left after my last synchronization and I now had even less games to synch.  Please help.

**Comment by pboling** [comment]
Possible that game saves took up the free space?

**Comment by phillipjorgenson** [comment]
Ive got maybe a dozen saves  all together, so I dont think so.

**Comment by phillipjorgenson** [comment]
I haven't made more than two saves since I last synced, had 24MBs space  to spare and more games than this sync which wouldn't go through.

**Comment by pboling** [comment]
Doesn't it say somewhere the size of the games?  Maybe you swapped out one game for another much bigger game?  Every game is a different size.

**Comment by phillipjorgenson** [comment]
That would make sense if I added games,but I deleted games and I was  still 26MBs over.  This after a successful sync just two days ago where I had about 24 MBs spare space.  It seems Ive lost exactly 50 MBs, and I wonder if it has something to do with the extra space Hackshi finds for saves.

________________________________
