### ISSUE TITLE
NES Games retroarc dont run or freeze console 

### ISSUE THREAD

**Issue by Tango80** [ClusterM/hakchi2#1245]
I have installed 2.3 + all new cores, retroarc is also installed. But now my Nes Games wont run anymore. Make the System Many times complete new but nothing change. Has anyone the same Problem ?

**Comment by Tango80** [comment]
Ok i Fix it , i have to reinstall my NES Library .now Works Fine 👍

**Comment by dbelyaev** [comment]
Thanks for your feedback!

Closing this issue.
