### ISSUE TITLE
md5 question

### ISSUE THREAD

**Issue by acidrain97** [ClusterM/hakchi2#1246]
this is just for my own curiosity but does anyone have a list of md5 checksums for the nes/snes/famicom kernels? 

Also is the US SNES kernal the same as the European SNES? same checksum as well?

thanx

**Comment by 9BallJet** [comment]
I got this message today when modding, all working fine though.

**Comment by acidrain97** [comment]
ok that really doesn't answer any of my questions...

**Comment by dbelyaev** [comment]
Hello, @acidrain97,

It is an issue tracker to report bugs with hakchi application. It is not a support forum or a place to discuss different hacks and mods. 

Please, ask your question on specific forums or subreddits, good place to start is here: https://www.reddit.com/r/miniSNESmods/

Closing this issue.
