### ISSUE TITLE
SNES Mini not responding on the tv

### ISSUE THREAD

**Issue by bachmann23** [ClusterM/hakchi2#1248]
so i had it all hacked perfectly, kept the original dump on the computer but had to restore the PC so i have now lost the original my fault. so like the idiot i am tried to reconnect it to the PC and dump kernel but now when its all plugged into the TV it detects the HDMI but nothing actually come on the screen tried loads of cables etc HELP!!

**Comment by dbelyaev** [comment]
Hello, @bachmann23,

This issue log is being used for bug tracking in hakchi application. We are trying to have it clean as possible thus all support request will be removed.

Please, ask your question or seek help on specific forums or subreddits. Good place to start can be found here: https://www.reddit.com/r/miniSNESmods/

Closing this issue.
