### ISSUE TITLE
[SOLVED] Possible to Improve Performance on *certain* SNES/GBA Games???

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#125]
So I know we can switch out cores for the non-stock ones, but I was advised against touching the cores of the prepackaged cores.  Is there anything that can be done to improve performance of certain games or is it limitations of the system?

StarFox (SNES) & Stunt FX (which use that FX chip) seem to drag a bit.
Yoshi's Island (SNES) is having audio/slight speed issues
Metroid Fusion (GBA) is having audio/speed issues

**Comment by warlockv2** [comment]
thats hillarious dude, those ae the games i tested to, i use an everdrive for all my real systems with a framemeister, but certain games cant run on it like the fx ones, i was hoping this would solve it and no, they do not work well.

**Comment by sanjay900** [comment]
I found that my GBA games lagged a lot until i disabled all the filtering that was going on. I did end up swapping the gba core though so that might also have done it.

**Comment by bfluryx1234** [comment]
The updated mGBA emulator addresses a lot of the issues with the GBA games.  I am told the SNES 2005 version works better as well.
