### ISSUE TITLE
Classic SNES softbricked - turns off on its own, no video output

### ISSUE THREAD

**Issue by Jack3478** [ClusterM/hakchi2#1253]
I got an MD5 checksum error last night while setting up my system, so I decided to just reset it completely and start from scratch (the error came up as I tried to add another game, I had already gotten it up and running with Chrono Trigger). I uninstalled hakchi2 from the system and flashed the original kernel, but now when I turn it on it just turns off after a few seconds with no video output.

Also, when following the steps to connect my SNES while uninstalling, flashing kernel, etc., the LED turns on about halfway through the driver running. I've already moved my original dump back to the folders before flashing the original kernel.

**Comment by DecanFrost** [comment]
when it does that it usually means no kernel or missing hakchi files.  flash stock in FLE mode and then custom again

**Comment by Jack3478** [comment]
Thank you. I'm unfamiliar with some of the terminology, how do I make sure hakchi's in FLE mode? And I assume stock means original kernel?

**Comment by NiicoD** [comment]
how do I make sure hakchi's in FLE mode?
=> the SNES must be in FLE mode => on the eject USB device icon, the name of the SNES shows you the mode you are in

**Comment by Jack3478** [comment]
Ah, thank you. For flashing stock, is it enough to just have the original kernel in the dump folder?

**Comment by NiicoD** [comment]
Yes.
https://github.com/ClusterM/hakchi2/issues/1162

**Comment by Jack3478** [comment]
Thank you, it works now! It does seem to have some inconsistent issues still (will sometimes not turn on/off, when i first got it back on hitting reset turned it off), but for the most part it seems to work.

**Comment by PreStalnic** [comment]
Hi, I'm running into a similar issue with my NES Mini. I accidentally set the console type to SNES (as I'm usually working with a SNES mini) and dumped the kernel. I realized I messed up the console type and switched it back and tried to uninstall the hakchi2 only for the program to notify me that there was no kernel set for the console. So, I proceeded to uninstalling hakchi through the SNES setting. It was successful, but the console is softbricked (no video output and the LED light keeps turning on on its own. Is there a way to revert the console back to its original state?

**Comment by Diogogapicolo** [comment]
Boa noite estou com um problema no meu SNES classic mini , quando vc restaura ele de fábrica pelo hakchi geralmente ele sobra 230 MB de espaço para jogos , o meu já voltei ele original de fábrica pelo hakchi e só tá sobrando 218 MB , alguém sabe resolver isso ou se danificou algo nele ?
