### ISSUE TITLE
How to put playstation games on snes classic

### ISSUE THREAD

**Issue by jayforde** [ClusterM/hakchi2#1255]
I know i am late but I've trying to put PlayStation games on the snes but nothing is working i downloaded the psx but can't find a PlayStation file to compress. Can someone help me I've been trying for about 2 weeks now .

**Comment by DecanFrost** [comment]
do a google search for PSX on PSP isos, download the games already converted ... will save you time.  cant say where to find them but you will be in an emulator's paradise when you do

**Comment by DecanFrost** [comment]
dont forget to install the PSX hmod, and amend the games command line from /bin/pbp  to /bin/pcsx or /bin/psx

**Comment by dbelyaev** [comment]
Hello, it is an issue tracker to report bugs with hakchi2 application. It is not a support forum or a place to discuss different hacks and mods. Please, ask your question on specific forums or subreddits, good place to start is here: https://www.reddit.com/r/miniSNESmods/
