### ISSUE TITLE
Feature Request: Select Folder from Main Screen

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#126]
Hi There,

Minor feature request, but when we have custom folder controlled enabled it would be awesome if we could select the folder when viewing the list of games (where you add/config the ROMS) so for example you could just list the folders "Home, Super Nintendo, etc." under the Game Genie Parameters.

Also, would be nice if we could tie a different background/music into each folder.  I suspect this is possible as we can change both right now.  But who knows...

Awesome work there by the way.  Wasn't expecting subfolders, that just rocks!

**Comment by ClusterM** [comment]
It's possible using mods.
