### ISSUE TITLE
freezing snes mini (sega, picodrive)

### ISSUE THREAD

**Issue by forsgear** [ClusterM/hakchi2#1260]
The last version of retroarch core has resolved my problem )

**Comment by forsgear** [comment]
snes games those use retroarch module don’t run at all, black screen

**Comment by forsgear** [comment]
I have found topic on reddit  a guy had the same problem and he resolved it by decreased count of games per page but in my case it didnot solve it

**Comment by forsgear** [comment]
one more thing I have found 
nes , snes roms were broken for some reason and I uploaded them again and they have begun  work well ,with the exception  of freezing of retroarch while I try to leave it

**Comment by forsgear** [comment]
Even factory default did not fix it

**Comment by forsgear** [comment]
I have tried use previous portable version of hackchi and it doesn’t see console at all after impact last version 2.30 . So strange...

**Comment by Shoothimnow** [comment]
Please close this "issue".  Your status on this issue says **Open**, which means that the problem has not been resolved
