### ISSUE TITLE
snes randomly mini shutting down by itself after save state. Starts up and then shuts down.

### ISSUE THREAD

**Issue by fabiophillip** [ClusterM/hakchi2#1269]
Hi, my snes mini is randomly shutting down by itself. It does not happen all the time, but when I push the reset button, add a save state and then open the saved state, sometimes the system shuts down. When I try to turn it back on, sometimes the red light turns on, the music plays for 3 seconds and then the system shuts itself down. Tried plugging the system directly to the TV, but it didn't work.

**Comment by forsgear** [comment]
hi , update retroarch clover to last one 
https://github.com/ClusterM/retroarch-clover/releases

**Comment by fabiophillip** [comment]
hi, thank you for the attention! I did what you said, installed retroarch_with_cores.zip(dragged it to haxchi), left gambatte checked when I dragged the zip file, followed the instructions (reset button, power....), waited until done and now my snes mini cannot run the game boy color games like zelda DX! Please help!

**Comment by forsgear** [comment]
delete the game and add it again, deleting any game won’t concern your save data just use the same rom file . anyway you abel to export your saves files to your pc

**Comment by fabiophillip** [comment]
I tried deleting the game, the synchronizing the snes mini so that it would delete the game. Then, tried adding the rom again(with the same name), synchronized again. Sadly, the problem persists: I try to open it, it gives me a black screen for 5 secs and then comes back to the menu.

**Comment by NiicoD** [comment]
Did you modify the cmd line with the new option for retroarch ?

**Comment by fabiophillip** [comment]
No, I didn't modify the cmd line, but how do I do that?

**Comment by NiicoD** [comment]
https://github.com/ClusterM/retroarch-clover
See "important note".
If not clear, youtube ;)

**Comment by fabiophillip** [comment]
i added --retroarch to command line argument (label "command line (for advanced users only!)") for the zelda dx game in haxchi, then synchronized the game again, but I still get the problem with 5 seconds black screen then return to menu. 
the arguments inside command line  now are: /bin/gbc /usr/share/games/CLV-C-WQWXM/Legend_of_Zelda_The_-_Link_s_Awakening_DX_(V1.1)_(U)_[C][!].gbc.7z --retroarch

**Comment by forsgear** [comment]
Did you try to unzip this game? as I can see do you use archived game with 7zip. I guess it is not good idea to use archived games

**Comment by NiicoD** [comment]
Did you install the right core module (from retroarch) to play GBC games ?

**Comment by fabiophillip** [comment]
well, I didn't enter the 7zip file, just te gbc file, but the argument inside the command line changed it to 7z I guess. 
AS for the right module, I installed retroarch_with_cores.zip(downloaded from github, dragged it to haxchi), left gambatte checked when I dragged the zip file, followed the instructions (reset button, power....), waited until done and now my snes mini cannot run the game boy color games like zelda DX

**Comment by forsgear** [comment]
I have tested zelda dx T-Rus on my snes mini and this works like charm. I can give you only the last advice , export all your saves to your pc , do the factory default your snes mini and hack it again

**Comment by fabiophillip** [comment]
is there any way to know if my snes mini did install the right core module (from retroarch) to play my GBC games?
