### ISSUE TITLE
Feature Request: Folder Shortcuts

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#127]
Hi There,

Not sure how exactly this could be implemented, but it would be great if somehow we could have a game shortcut created that we could put in multiple folders.  For example, I might want to have NBA Jam in a "Sports" Folder, "Super Nintendo" Folder, "All Games - N", Folder.  I know you could copy the game, but that means you have three separate ROMs on there.  Might thought is if you allow copy/paste of a pointer in the folder management screen it would work...

Great job on everything guys!  Really, super impressed!

**Comment by warlockv2** [comment]
thats a fantastic idea, unsure if its possible tho.

**Comment by bfluryx1234** [comment]
From a technical POV I am fairly sure this can actually be done.  The games are indexed by some random characters in the background, not their names alone.  

The question is how you do it in the UI so that it makes logical sense.  I think you have to have be able to right-click and create pointer/shortcut (with a different icon?) that you could then drag anywhere you want in the menu manager and also delete directly within the folder management tool.  And obviously, if you delete the game from the main screen (where you add/delete ROMs), all the pointers would have to be deleted.

The other way is to scrap the folder management GUI, create a GUI just for creating the folder tree structure (with no games in it), then on the main screen (where you add/load ROMs) you could have a checkbox system where you could just put a check next to each folder where you want the game to appear...

A third option might be easier by giving up a little flexibility.  Add a checkbox when clicked the system automatically creates a "special" root folder called "All Games" which sorts the "duplicate" there by letter.  So for example, I could still put "NBA Jam" in my "Super Nintendo" folder, but the system would have a root path as well "All Games"->"N"->"NBA Jam".  

Something like this seems necessary as the system lacks any type of search functionality, and it would most likely not be possible to add it to the core system (both as its new functionality and it would require traversing multiple folders).

**Comment by sanjay900** [comment]
I think the issue there is that the games are all indexed in their respective folders due to how the gui works, so you would have to put games in twice which would take up a lot of room on the device itself.
I wonder if you could do something with links though.

**Comment by bfluryx1234** [comment]
Sanjay, to be clear I was suggesting it would be links/pointers/shortcut, etc.  I agree adding the ROMs would take up space AND also (I believe) would mean you have separate save states in each folder.  Looking at the way he does folders, I am fairly sure he can add a link to a single game in multiple folders and have it work...

**Comment by sanjay900** [comment]
What im more curious about is if mklink will work after all the directories
are overmounted.

**Comment by abijanfar** [comment]
I think what is being asked here is a Tag system vs. a Folder system. It would be a major rework and I don't think the ROI is there.

**Comment by bfluryx1234** [comment]
@abijanfar It is the same as a tag system.  However, if you look at folders.xml the hard work is already done.  The XML stores the folder name and a list of pointers to games.  In theory, today you could modify the XML manually add an additional pointer in a different folder and it would work.  

The work is all on the front-end, not the back-end.  It is not a one hour fix, but it definitely is doable without throwing away much of anything.

**Comment by sanjay900** [comment]
@bfluryx1234 Actually, there is a fair amount of back end work to be done too, as we would need to look into a good way to store the games on the device without duplicating every game, since that would just be a waste of space, and if your going to implement something like this, theres no point in taking shortcuts.

**Comment by sanjay900** [comment]
I wonder if we could get away with just putting all the games in a folder and exposing directory links to the gui or something like that, but again, that does seem like a lot of work to get going.

**Comment by ClusterM** [comment]
I'll think about it.

**Comment by ClusterM** [comment]
Save as #187
