### ISSUE TITLE
Atari 5200 & 7800...

### ISSUE THREAD

**Issue by ERK369** [ClusterM/hakchi2#1278]
Atari 2600 games are working fine with Stella.hmod core. Someone knows which core to use for Atari 5200 & 7800?.. :)

**Comment by Shoothimnow** [comment]
Hakchi2 isn't an emulator.  You're questioning the emulators that run on Hakchi2's shell.  Please close this and re-ask on reddit.  https://www.reddit.com/r/miniSNESmods/

**Comment by Shoothimnow** [comment]
If you are having issues, please ask over on reddit : https://www.reddit.com/r/miniSNESmods/

This issue board is for found issues that everyone is having that needs a code fix.

Please make sure you **close this issue**.
