### ISSUE TITLE
Nes30pro issues with new version

### ISSUE THREAD

**Issue by warlockv2** [ClusterM/hakchi2#128]
i cant seem to use this controller for anythign but nes or gameboy.  if more buttons are required i cant change them etc.  same with analogue stick for n64.  is this an issue within retroarch itself, the hack, or is it not related.

**Comment by doctorworm** [comment]
I am having this same issue. Would love some advice on how to proceed.

**Comment by abijanfar** [comment]
I believe this is an issue with the 8Bitdo receiver not NESC or RetroArch. Hopefully they can release a firmware fix. http://forum.8bitdo.com/thread-1907-1-1.html

**Comment by warlockv2** [comment]
your correct, thank you sir
