### ISSUE TITLE
Unable to dump with rampack error Can't unpack ramdisk

### ISSUE THREAD

**Issue by survivaltribes** [ClusterM/hakchi2#1282]
Hello i try to dump the new kernel with hakchi 2.30 with my snes mini that have a previous kernel version (don't remember the version.) I  am on windows 10 pro 64 bit version 1699
I am unable to boot the snes mini anymore on my tv.
I have this error again and again on hakchi debug

Executing: C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\tools\unpackbootimg.exe
Arguments: -i "C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\temp\kernel.img" -o "C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\temp\kernel"
Directory: C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug
Output:
BOARD_KERNEL_CMDLINE root=/dev/nandb decrypt ro console=ttyS0,115200 loglevel=4 ion_cma_512m=16m coherent_pool=4m consoleblank=0
BOARD_KERNEL_BASE 40000000
BOARD_NAME 
BOARD_PAGE_SIZE 2048
BOARD_KERNEL_OFFSET 00008000
BOARD_RAMDISK_OFFSET 01000000
BOARD_TAGS_OFFSET 00000100

Exit code: 0
Executing: C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\tools\xz.exe
Arguments: -dc "C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz"
Directory: C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug
Errors:
xz: C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz: Compressed data is corrupt

Exit code: 1
Executing: C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\tools\lzop.exe
Arguments: -d "C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz" -o "C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug\temp\kernel\initramfs.cpio"
Directory: C:\Program Files (x86)\hakchi2.30_debug\hakchi2_debug
Errors:
lzop: c:\program files (x86)\hakchi2.30_debug\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz: not a lzop file

Exit code: 1
Can't unpack ramdisk   at com.clusterrr.hakchi_gui.WorkerForm.UnpackRamfs(String kernelPath) in D:\Projects\C#\hakchi2\WorkerForm.cs:line 1253
   at com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress) in D:\Projects\C#\hakchi2\WorkerForm.cs:line 483
   at com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 551
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 286

(sorry for  the bad expression english is not my native language)

Here is the full debuglog . I  am on windows 10 pro 64 bit version 1699
[debuglog.txt](https://github.com/ClusterM/hakchi2/files/1892279/debuglog.txt)

**Comment by survivaltribes** [comment]
Okay i have find a way to repair my snes. Create a dump folder  inside hakchi and add an original Kernel inside the dump folder.
To find the original kernel google is your friend.

**Comment by ghost** [comment]
Could you help me with this please?
