### ISSUE TITLE
Возможно ли запустить эмуляцию PsOne игр на Nes mini с помощью hakchi2+retroarch?

### ISSUE THREAD

**Issue by Scorp849** [ClusterM/hakchi2#1287]
Подскажите пожалуйста, а можно ли с помощью hakchi2 и retroarch воспроизводить игры с ps 1 .  И есть ли вообще точный список консолей игры которых возможно воспроизвести? Вообще очень странно что никто не задавал подобный вопрос...

**Comment by Lighttree** [comment]
> Вообще очень странно что никто не задавал подобный вопрос...

Потому что ответ в 1м абзаце вот тут например:
https://github.com/ClusterM/hakchi2/wiki/FAQ

> **Q:** What is it?
> **A:** This application can add more games to your Nintendo Classic Mini console: NES, Famicom, SNES or Super Famicom.

**Comment by jetbalanced** [comment]
Да ладно? Народ уже несколько месяцев с помощью расширения USB накидывает игры с PS1 и вовсю играет, а Вы тыкаете носом в ответ двухлетней давности.
https://www.youtube.com/watch?v=DKqIG3Yb80c

**Comment by Scorp849** [comment]
Да  с этим я уже давным давно разобрался)) Мне теперь интересен другой вопрос) У мен хаб работает там есть свободный юсб вход. Как воткнуть туда джой беспроводной и сделать его 1 джойстиком... ? Через селект+ старт попробовать поменять управление?  


>Вторник, 22 мая 2018, 21:31 +03:00 от jetbalanced <notifications@github.com>:
>
>Да ладно? Народ уже несколько месяцев с помощью расширения USB накидывает игры с PS1 и вовсю играет, а Вы тыкаете носом в ответ двухлетней давности.
>https://www.youtube.com/watch?v=DKqIG3Yb80c
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
игорь королев

**Comment by jetbalanced** [comment]
Таких решений я нигде не видел, если честно. Все так или иначе используют штатное гнездо.
Если тебе важен именно беспроводной момент, то пользуются вот такими без всяких плясок https://ru.aliexpress.com/item/New-8Bitdo-SF30-Pro-Wireless-Bluetooth-Game-Controller-Gamepad-with-Joystick-for-Windows-Android-macOS-Steam/32847570481.html

**Comment by dbelyaev** [comment]
@Scorp849 пожалуйста, в следующий раз, при создании Issue, формулируйте заголовок кратко и правильно без использования генерализированных предложений.
