### ISSUE TITLE
Have the same game displayed in 'home' and in 'more'

### ISSUE THREAD

**Issue by JoshAubrey** [ClusterM/hakchi2#129]
Original 30 in root > pages/folders split with original 30 included & back button to root

I would like to know if this is possible. 2.11 kind of did it by default by having  the original 30 in root then also mixed into more games. In 2.12 it seems if you have original 30 in root they arent in more games.

In the custom folders manager option of 2.12 I haven't been able to 'copy' a game to another folder, only 'cut'.

So the original 30 are stuck either in 'root' or 'more' but not both.

Can we copy games into multiple folders?

This would also be helpful for people to make a "favorites" folder

**Comment by JoshAubrey** [comment]
This would also be helpful for people to make a "favorites" folder

**Comment by ClusterM** [comment]
Same as #187
