### ISSUE TITLE
Glitches in Mega Man X2

### ISSUE THREAD

**Issue by goggles789** [ClusterM/hakchi2#1296]
Hi, thanks for all your hard work on hackchi, as it makes the experience of owning the SNES mini so great!

I noticed on Mega Man X2, in Bubble Crab stage there is a huge sound bug occurring with the giant fish submarine close to the beginning of the level.  Whenever the fish uses it's large laser beam, the sound glitches terribly.  The other glitch is that the title screen for Mega Man X2 lags a lot when you push start.  I played the game from start to finish without any other issues, though.

Thanks so much!

**Comment by Shoothimnow** [comment]
Hakchi2 is the program that you installed onto your SNES Classic to get the other games added.  

Running those games is something completely different than Hakchi2.  This isn't an issue with Hakchi2, as it seems that you were able to add the games perfectly fine.

Please **close this issue** and re-ask over on https://www.reddit.com/r/miniSNESmods/

**Comment by goggles789** [comment]
Sorry to be a bother, but I’m new at this. What exactly is the problem if it’s not Hackchi, so I know what to ask. Thanks!

Sent from my iPhone

On May 3, 2018, at 12:52 PM, Shoothimnow <notifications@github.com<mailto:notifications@github.com>> wrote:


Hakchi2 is the program that you installed onto your SNES Classic to get the other games added.

Running those games is something completely different than Hakchi2. This isn't an issue with Hakchi2, as it seems that you were able to add the games perfectly fine.

Please close this issue and re-ask over on https://www.reddit.com/r/miniSNESmods/

**Comment by Shoothimnow** [comment]
On Reddit (again, not on here, as you already have your installation of Hakchi2 working), you will find out that Canoe (the SNES Mini Emulator) wasn't created to run every SNES game, only 21 (and barely that).  

There is a compatibility list on Reddit : https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/edit#gid=2014317767

All you have to ask is "Glitches in Mega Man X2" over there, and people will help you out.  Either patch the ROM, or put it into Retroarch, but again, this unfortunately is not a Hakchi2 issue.

**Comment by goggles789** [comment]
Thanks! Sorry for the trouble. Have a great night.

Sent from my iPhone

On May 3, 2018, at 8:10 PM, Shoothimnow <notifications@github.com<mailto:notifications@github.com>> wrote:


On Reddit (again, not on here, as you already have your installation of Hakchi2 working), you will find out that Canoe (the SNES Mini Emulator) wasn't created to run every SNES game, only 21 (and barely that).

There is a compatibility list on Reddit : https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/edit#gid=2014317767

All you have to ask is "Glitches in Mega Man X2" over there, and people will help you out. Either patch the ROM, or put it into Retroarch.

**Comment by Shoothimnow** [comment]
Please **close this issue** before you dissapear

**Comment by goggles789** [comment]
Okay, how do I do that?
________________________________

**Comment by Shoothimnow** [comment]
This is from another user on here.  Seems like it is right next to your "Comment" button.  Only shows up for **Admins** and the **Original Poster**, so I don't see it (which is why I am asking to please close this "task")

![35013211-a694fe3e-fada-11e7-8a07-249b28afcc32](https://user-images.githubusercontent.com/32903303/39628124-04785cf4-4f76-11e8-8440-5a9e03505810.jpg)
