### ISSUE TITLE
Проблема со snes mini

### ISSUE THREAD

**Issue by Arida88** [ClusterM/hakchi2#1297]
После переустановки винды захотел снова установить хакчи и добавить игр. Накосячил перепрошив уже прошитую консоль и все сломал, консоль перестала включатся. Удалил хакчи со снес, поставил оригинальное ядро и стандартные игры начинают работать. Но когда пытаешся заново прошить, поставить эмуляторы и игры то консоль виснет, загорается светодиод и не гаснет пока не отключишь от сети. Подключая к тв так же загорается диод и не гаснет и ничего не показывает

**Comment by jetbalanced** [comment]
Та же проблема, однако она случилась после переезда с 2.21f на 2.30
Полностью удалился, прошил оригинальное ядро, вернул всё к заводским установкам. Прошил 2.30, поставил модули 1.1d. Всё работает ровно до попытки добавить игры. Чёрный экран и, в общем, все те же симптомы до тех пор, пока не сделаешь полный откат на дефолт.
На 2.21f всё отлично.

**Comment by ClusterM** [comment]
Убедитесь, что у вас используется оригинальный образ ядра.

**Comment by jetbalanced** [comment]
Всё верно. На каком-то этапе родное ядро из папки "dump" приняло размер 3,4МБ (вместо изначального 2,7).
Алексей, планируете ли Вы дальнейшую поддержку и развитие hakchi2, или уже всё? Просто многие модули для ретроарха (для PS1, PSP и прочее) к Вашей версии прикручиваться не хотят, а переползать на СЕ-версию как-то не хочется. Или всё можно, просто я чего-то не понимаю?

**Comment by ClusterM** [comment]
Значит оригинальное было удалено, само оно не могло замениться.
Не вижу смысла дальше развивать мою ветку, когда есть CE версия.
