### ISSUE TITLE
Blackscreen on TV after adding Games

### ISSUE THREAD

**Issue by ZokkerBunny** [ClusterM/hakchi2#1305]
Hello,

i tried a lot of times to add Games on my Snes Mini.
It is very simple and i have all Games in .sfc /.smc.
After i followed all Steps to add my fav. Games on my Snes i conect it with my TV.
When i start the Snes i dont have the Menu.. only a Black Screen. :/

I have few probs:

- The MD5 number is wrong
  But i saw thats dosnt matter rly, so i "skipt" this part..

- When i put my fav Games on the Snes and want start the Synchro Progress there are a prob too
  I click it, then i install the driver, the mini black window opens and there is written that they dont find
  my Snes Mini...

is it on of these Problems why i cant add Games on my Snes Mini? :o 
I hope one of you can help me out.^^
I want play so badly Super Bomberman... xD

Thanks for your Time :)

**Comment by ClusterM** [comment]
Seems like you are using not original kernel image. Find your original kernel image, put it into "dump" folder and make full uninstall + flash original kernel.

**Comment by ZokkerBunny** [comment]
Thanks for the fast answer! :)

Where can i find my "original" kernel? :o
It is the kernel what i should save befor adding games to the snes, right?

**Comment by ClusterM** [comment]
Yes, it should be saved after first usage. It's stored in "dump" folder. Can you say size and MD5 or your kernel image to make sure that it's original?

**Comment by ZokkerBunny** [comment]
The Size of my Original Kernel is 3,32 MB (3,481.600 Bytes).

**Comment by ClusterM** [comment]
It's wrong size, it's not original kernel. Please contact me via
clusterrr@clusterrr.com - i'll send you original kernel and instructions.

**Comment by ZokkerBunny** [comment]
Oh, ok. Thanks! :o
