### ISSUE TITLE
SNES Classic Won't Sync, asks for Driver to be installed

### ISSUE THREAD

**Issue by WhiteMousse** [ClusterM/hakchi2#1306]
Hey everyone.

I was able to load games into the SNES mini pretty well.  Followed the instructions, held reset, turned on the power, dumped the original kernal, everything seemed good.  

Put in some games and synced.  I took it out and played it, and it worked great.  However there are a couple games that just won't work.  I reconnected the SNES mini to my computer and deleted them.  However when I tried to sync it, I got a notice that said

   "Waiting for your NES/SNES mini..."
Please do the following steps:
   1) Connect your NES/SNES Mini to the PC via USB cable.
   2) Turn it on.
   3) Install driver if it's not installed yet. 

Now... I already installed the driver when I first started putting games on the thing.  But when I click on the install button, the window comes up and says it's installing, tells me to press enter to exit the driver installer.  

But the original "Waiting on your SNES" window is still there!  So I have to hit cancel, and nothing is done.  

Can you help me?  I'd like to upload more games and take out the ones that don't work, but I don't know how.  Thanks!

**Comment by ClusterM** [comment]
Check the device manager as described in FAQ. Make sure that you connected your SNES mini correctly.

**Comment by WhiteMousse** [comment]
Cluster,  thank you for your reply.  I must confess I don't know where the FAQ is... do you have a link?  

Also, whenever we connect it, we should use the hold reset + power on technique, correct?

**Comment by ClusterM** [comment]
https://github.com/ClusterM/hakchi2/wiki/FAQ
You can find this link directly in hakchi2 menu and here on GitHub.
You should hold reset only when you asked to do it.
