### ISSUE TITLE
Games not loading up on SNES mini (C7 eroor and black screen)

### ISSUE THREAD

**Issue by pinchepapat** [ClusterM/hakchi2#1311]
I first modded my SNES with hakchi and retroarch a couple months back and everything worked perfectly, but now I went back to upload some new games and now games that worked perfectly before (Super Mario All Stars, Mega Man X 2 and 3, NES, Genesis and GBA games) don't load anymore. The SNES games used to load identical to the base games, with the borders and filters, but now they don't load and pop up a C7 error. The NES, Genesis, and GBA games just give a black screen before sending my back to the reset screen. I reflashed the kernel, added --retroarch to the end of the command lines, got the latest versions of retroarch and still nothing. Any advice on what I can do?

**Comment by ClusterM** [comment]
Can you say exact version numbers?

**Comment by pinchepapat** [comment]
sorry to open this again so late, i figured out that adding -"retroarch" to some command lines worked, but im still having problems with games like the mega man x games and chrono trigger.  im using all the latest versions for hakchi and retroarch. these games used to work fine before on the stock emulator but they stopped working when i added some more games onto the console. do i possibly have to download some new mods to get these games to work now? the only mods i have installed right now are the retroarch ones (no extra space mod or sound mod). thanks for helping

**Comment by pinchepapat** [comment]
Update: fixed issue by going under kernel> boot patched kernel from RAM. Then i reinstalled all the games that weren't working and now everything works like a charm
