### ISSUE TITLE
Certain Games wont load/crash/have sound issues

### ISSUE THREAD

**Issue by Kajutza** [ClusterM/hakchi2#1312]
Hey i have problems wth some of my games, some of them dont load when i try to start them i get back to the main menu example Clocktower, some games start but crash or are really slow example Killer Instinct and Terranigma, and other games have problems with the sound with wrong pitch or spipping a note? Ore something example Aladin or Earthworm Jim 1 or Donkey Kong 2. Hope someone can help met thanks.

**Comment by ClusterM** [comment]
Games of which region are used? Are you using original emulator?

**Comment by Kajutza** [comment]
So i was actually able to figure it out. The ones that crashed/had sound issues were European Roms replaced them with USA Roms. The ones that didnt load i needed to install Retroarch Example Clock Tower. And the ones that still dont work are games that people have generally a problem with like Terranigma, but still thanks!
