### ISSUE TITLE
Mini nes cant unpack ramdisk SOLVED.

### ISSUE THREAD

**Issue by Leesin2002** [ClusterM/hakchi2#1313]
I was trying to hack my mini nes with Hackmi 2.30. But it say me (Cant unpack ramdisk) please i need help i dont know what is happening and i need help mates. Also i had previously versions of hackmi. 

Sorry about my english i am from another country.

**Comment by ClusterM** [comment]
Make sure that you have original kernel dump.

**Comment by Leesin2002** [comment]
Thanks man you and your instructions i manage to make my console work again!!!!!!!
