### ISSUE TITLE
Rewind save-state hotkey

### ISSUE THREAD

**Issue by codemeasandwich** [ClusterM/hakchi2#1315]
First of all, thanks for your fantastic work on this project!

I was wondering, as you can remap the reset to a controller press combination. 
Would it also be possible to have an in-game key press combo to bring you directly to the rewind of the save state? This would be better than waiting to go back to the home, pressing down and X to access the rewind.
Also would it be possible to have the save state replay by default in reverse like a 1x rewind?

Thanks and keep up the great work

**Comment by Shoothimnow** [comment]
I would add **[Feature Request]** to the title of this

**Comment by ClusterM** [comment]
No, it's impossible.
