### ISSUE TITLE
PLEASE HELP: C4 Error (Limitation of # of Saves or Memory?)

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#132]
Getting a C4 error when attempting to save SNES game.  This seems to be somehow related to the number of save states in the system.  I can remove a save state from an unrelated game and then save one more game.  Not sure if this limitation is because of the # of SNES games (in total) installed or the # of saves (in total).

It doesn't seem to be a limitation related to the specific folder as I have custom folders enabled and it happens in folders with 12 games and 30 games.  Still investigating (removing some games at the moment)

**Comment by bfluryx1234** [comment]
I confirmed that with less games installed the error is still present.  Seems to be a limitation of the number (or file size?) of the total number of save states on the system across all folders.  Its going to be frustrating as you won't know you hit the limit until you can't save :(

**Comment by bfluryx1234** [comment]
I posted more details on this over on Reddit...

Ok... so the C4 error occurs when trying to save games. Specifically for me it seems to be when I try to save SNES games.

I have narrowed it down to the following:
 1) I can have 18 saved SNES games (excluding battery backup) across as many folders as I want
 2) When limit is reached I can still save games for all other systems!
 3) Limit is not impacted if I remove ROMs
 4) State Slot is set to '0' (not sure if this was the default?)
 5) Previously opened a lot of games that seem to create .SRAM (not sure how to remove, but I have tons!)
 6) Battery Backup Saves (i.e. Zelda) do not seem to impact (at least creating an individual slot, now a brand new game being added might?!?!?) 

Using SNES 2010 Core.

I read somewhere else that another user seemed limited at 10. I am thinking we might be hitting that 30mb limit in some cache folder somewhere...

Reddit link: https://www.reddit.com/r/nesclassicmods/comments/5vox23/who_has_gotten_the_c4_error_ive_narrowed_it_down/

**Comment by ajmi982** [comment]
There needs to be a way to remove our saves. I can no longer save SNES games, get C4 error :(

**Comment by bfluryx1234** [comment]
This mirrors my experience as well with limitation.  Would like a browser to delete saves directly within the system.  My guess is this might be a separate project similar to Retroarch...

**Comment by bfluryx1234** [comment]
Solved.  See linked issue for details, but the system was chewing up memory with 5mb save states in SNES9x2010
