### ISSUE TITLE
"Unknown Error Occured" when going down folders, not up

### ISSUE THREAD

**Issue by babafett** [ClusterM/hakchi2#1329]
I have my SNES modded with Hackchi2 set to "Split games equally" and Max # of titles = 100.

When I go from Page 1 (Letters A to L) to Page 2 (Letters M to Z) I get an "Unknown Error Occured" and have to reset the system. When I reset, it brings me to Page 2.  But going from Page 2 to Page 1 works just fine.

**Comment by ijustwanttohackthesnesclassic** [comment]
the smartest solution is to just not tinker with the folders and let them fix file themselves iw will make the folders have weird names but i did that and i have no problems
