### ISSUE TITLE
FDS Problem

### ISSUE THREAD

**Issue by BaconGod** [ClusterM/hakchi2#133]
I use a famicom mini instead of a NESCE, my issue is that since the 2.12 release, there are original games that are in FDS format and none of them now start while other FDS games I installed via Hakchi2 (2.11 and below version) all still work.  Any way around this?  Maybe @ClusterM can take a look?

**Comment by ClusterM** [comment]
Have you any mods installed?

**Comment by BaconGod** [comment]
just retroarch and fontfix.

**Comment by BaconGod** [comment]
update:  i uninstalled the mods and still get the same error.  dunno if that info will help.

**Comment by ClusterM** [comment]
Yes, it will help. I'll fix it soon. Thank you for report.

**Comment by Slugoid** [comment]
I am still having this issue with 2.21c. Original FDS games will not load after loading custom kernel.
