### ISSUE TITLE
SNES Kernal Dump Problem

### ISSUE THREAD

**Issue by TheDigbySniper74** [ClusterM/hakchi2#1340]
I had owned my SNES Classic for almost half a year and I just started the need to hack it. I've downloaded the installer(being version 2.30), however when I started the Dump Kernel process it gave me the notification of "Do you want 'program' to change these settings". I click yes but the Kernel did not dump. So I close the window and tried to restart, but when I did, I got the following message:

![snes issue](https://user-images.githubusercontent.com/40348870/41518489-98802a84-7277-11e8-881e-08b7b3d0fa7a.PNG)

I have no clue what to do. Thankfully my system hasn't encounter any issue(as of right now) yet I still want to continue to mod the library. IF any one can help it'll be much appreciated.

**Comment by panic2099** [comment]
did yopu find out how to fix it.mine is doing the same thing no matter what I try to do I get that samr mess error

**Comment by TheDigbySniper74** [comment]
Yeah i factory reset the console then carefully followed the steps on the tool. As i did my console was successfully hacked. Also try restarting your pc if you need to. Hope you get yours to work.

**Comment by panic2099** [comment]
I tried restarting the pc.still nothing.wheni try to uninstall hackchi or anything flash the new kernel.i get that error mess.i really don't know computers that much.how do I factory reset the console. thankyou

**Comment by panic2099** [comment]
I found out how to do a factory reset. what tool are you referring to that you followed the steps?thankyou

**Comment by TheDigbySniper74** [comment]
Just go to dump kernel but follow the steps carefully

**Comment by panic2099** [comment]
THANKYOU FOR YOUR HELP.YOUR NOT GONNA BELIEVE THIS IT WONT EVEN LET ME DO A FACTORY RESET.THE NES TURNS OFF LIKE ITS GOING TO BUT THEN WHEN IT COMES BACK ON EVERYTHING IS STILL THERE &I GO TO HACKCHI AND STILL CANT DO ANYTHING..UGH LOL ;( BUT THANK YOU FOR TRYING..HAVE A GOOD ONE

**Comment by panic2099** [comment]
i fixed it .it was a fucking virus on my computer messing everything up.but thankyou again

**Comment by TheDigbySniper74** [comment]
Oh thank god you gave me a good scare jesus

**Comment by TheDigbySniper74** [comment]
Use hackchi tho

**Comment by panic2099** [comment]
it gave me a terrible scare 2,lol. yeah im using hackchi.still having trouble with trying to install other emulators.hopefully I fig it out eventually
