### ISSUE TITLE
All Retroarch games do not boot from the menu though they boot perfectly from the app

### ISSUE THREAD

**Issue by f1r3place** [ClusterM/hakchi2#1341]
Retroarch games on my SNES mini worked, but now they do not, for some reason. Tried installing the Clover app and booting them from it: they did boot! But still no booting from the menu. I installed 4 cores: Retroarch, Genesis_plus_GX, mgba, gambattle.

**Comment by Shoothimnow** [comment]
If you were able to add Retroarch to your NES Classic, then Hakchi2 is working.  Hakchi2 (and this issues board) is for issues that EVERYONE is having and have @ClusterM attempt code re-writes (such as the new MD5 Checksum error).  As counter intuitive as this might sound, but if you were able to add something to your NES Classic, then hakchi2 is working.

For RetroArch issues -> please close this issue and re-ask in an actual forum

https://www.reddit.com/r/miniSNES/
