### ISSUE TITLE
New 2017 NES Mini md5 mismatch

### ISSUE THREAD

**Issue by Casporro** [ClusterM/hakchi2#1342]
The new version of NES Mini gives md5 mismatch error when dump the original kernel.
I'll wait just in case...

**Comment by ijustwanttohackthesnesclassic** [comment]
By this do u mean the rereleased ones that came out with cuz I preordered one and it’s coming out soon and I badly want to be  able to hack it.

**Comment by Casporro** [comment]
Yes, the new rereleased. I got it yesterday and I hope you get it soon.

**Comment by ijustwanttohackthesnesclassic** [comment]
Well this suck in Australia they are releasing in a little more than a week and u really wanted to hack it

**Comment by sweatboxx** [comment]
Yeap same here. 
New batch of the nes mini gives an md5 mismatch error. 
Have stopped the hack process after dumping the kernel and will wait

(my md5 is 90EEC1E2B4F00E53DC2DD53A9E7334C1 with the v2.30 (internal version 2.0.30.18))

**Comment by Brds7t7** [comment]
You can safely ignore the MD5 mismatch error. I have a new (June 2018) NES Mini and get that same error. Mine has the same MD5. It's just because Hakchi doesn't recognise the MD5 of the newer kernel.
I have successfully dumped the kernel, flashed custom kernel, added games and mods, then uninstalled and flashed back the original kernel with no issues in 2.21f. Just ignore the error, hakchi will still work as normal.

**Comment by Casporro** [comment]
Can anyone else confirm that?

**Comment by Brds7t7** [comment]
Several users and devs have reported it works with no issues. Works fine for me. More info here: https://www.reddit.com/r/miniSNESmods/comments/8shszp/update_new_nesc_ok_to_flash_with_hakchi/

**Comment by sweatboxx** [comment]
Like in the FAQ
Q: It says that the MD5 checksum is unknown when I'm trying to flash custom kenel! What I need to do?

A: There are two possible reasons:

    You have some unique unknown revision of NES Mini, please send your kernel dump in this case.
    Some custom kernel already flashed.

It's safe to continue in both cases.

It works for me too.

**Comment by ijustwanttohackthesnesclassic** [comment]
oh thank lord small question for brds7t7  on the link you left it talks about a hakchi 2 community edition on 1.25 but on github its 2.30 and it doesnt say anything about a community edition.
either way thanks!

**Comment by sweatboxx** [comment]
Im not brds7t7 but I have done it with v2.30 (internal version 2.0.30.18). No problems. 

The CE is not same counted as the normal version because its a fork. The latest CE is 1.2.5 by TeamShinkansen I think

**Comment by ijustwanttohackthesnesclassic** [comment]
oh ok thanks for the clarification

**Comment by Brds7t7** [comment]
Yes the CE edition is a fork of Cluster's. It has integrated USB-HOST, etc.
However, I don't use USB-HOST and 2.21f has always worked well for me and does everything I need, so I've always stuck with that version.

But, it's safe to ignore the MD5 error whichever version you use. Cluster may decide to update Hakchi2 later to include the newer kernel MD5. Until then, just ignore it, it'll still work as before.

**Comment by ryder2018** [comment]
Just got the nes mini today, worked fine with the 30 games, my friend looked at mine for me and now it turns on with red light then red light shuts off completely.
Any help at all please, is this now broke :(

**Comment by ClusterM** [comment]
Fixed.
