### ISSUE TITLE
Reset Button Controller Hack doesn't work on New NES Classic

### ISSUE THREAD

**Issue by jayd189** [ClusterM/hakchi2#1349]
Installed hacked kernel.
Added about 70 games and they all work fine.

Made sure that reset was checked.
Made sure the buttons were Down and Select

Does not work when I try to reset using the controller.

Edit:
In case it matters, SNES Classic works fine using same version of hakchi2

**Comment by RythonTheSNES** [comment]
I was finally able to purchase an NES Classic yesterday, and I am having the exact same issue.

**Comment by Fishstix61** [comment]
It's a new kernel. I just thought I bricked one, but dumped an extra I bought. 6k difference in size from the first set of NES classics on the kernels. Was having the same issue and can't wait for a fix.

**Comment by ChaddyBones** [comment]
Any chance I can get a dump of the new kernel? Think something went wrong while hacking one of the new classics and I need to try flashing with the original kernel.

**Comment by Fishstix61** [comment]
You bet. Will send later when I'm on my computer.
________________________________

**Comment by ChaddyBones** [comment]
That would be great! Thanks a bunch!

**Comment by jayd189** [comment]
This was mine
[kernel.img.zip](https://github.com/ClusterM/hakchi2/files/2152299/kernel.img.zip)
@ChaddyBones

**Comment by ChaddyBones** [comment]
Up and running again! Thanks @jayd189 Much appreciated!

Was hacking this one for a friend who only got his hands on an NES Classic just now. Think I'll hold off for a bit until there is an update for the re-released classics before I try again.

**Comment by Brds7t7** [comment]
No issues here for me using 2 SNES minis from 2017 and 2 of thy new NES Classics. Everything works as expected for me. 

Which Hakchi2 version are you using? I've always stuck with 2.21f and had no issues.

**Comment by jayd189** [comment]
2.21f.

The only part that doesn't work is the controller reset.
Everything else works perfectly.

Reset also works on my SNES from earlier this year.

**Comment by Fishstix61** [comment]
Turbo didn't work for me either.
________________________________

**Comment by jayd189** [comment]
Can't comment on turbo, didn't try.

**Comment by ClusterM** [comment]
Can you send me NAND-B image of new NES Mini?

**Comment by sandog78** [comment]
I have tried 2.21F but no go.. What am I doing wrong?

**Comment by bryces76** [comment]
@ClusterM Sent you an email

**Comment by Sludgetrough** [comment]
I can verify that this is happening for me as well.  Newly released NES classic from last week with Hackchi 2.21f.  Reset combo and turbo combo don't work no matter what button combinations I try assigning to it.  Everything else works great!

SNES classic from 6 months ago works fine with reset, so it must be the new kernel.

**Comment by mrstux** [comment]
FWIW, its working for me on the new batch of AUS NES' consoles. I just had to enable it in the Controller Patch settings menu.

And yes, Hakchi warned about the wrong md5.

**Comment by negron87** [comment]
wait, so what do i have to do to correct this issue? very new to this site and hacking the nes mini . i just added 60 gamess help

**Comment by Sludgetrough** [comment]
My NES is a North America console so this could be regional difference.  I also got an "incompatible md5" warning when I flashed my kernel, but everything else works very nicely save the reset combo.  I don't think there's much to do besides wait for a new version of Hackchi2 to fix this problem.

**Comment by sandog78** [comment]
No matter what I do It says enter password after I flash new kernel on the screen

**Comment by Sludgetrough** [comment]
@ClusterM 
Attaching the NAND-B dump from the new NA NES classic for Cluster if he wants to take a look.  Just verified that the problem persists with Hakchi2 2.30 as well as the MD5 checksum warning when flashing the kernel.

Cluster, if you need anything else from the new NES like a kernel dump, just let us know.  You da man!

[nandb.zip](https://github.com/ClusterM/hakchi2/files/2174418/nandb.zip)

**Comment by bgthang** [comment]
I was able to get the reset to work. I switch the key combo to start and select. and when im in a game I hold those two down. Dont press both of them but hold them down and it will drop you to main menu. May also work with the down and select if you hold them but Im too lazy to go back and check

**Comment by Sludgetrough** [comment]
This did not work for me.  

Hakchi2.21f with new NES classic, set the buttons as you suggested, it will not reset.

Also verified that Hakchi2.30 bricks the unit.  Tried several times with different options but the new custom ROM eventually bricks the unit.  Reverting to Hakchi2.21f was the only way I was able to get it working agin.

**Comment by THEFIGZ** [comment]
are they even gonna update the app or fix this?

**Comment by RythonTheSNES** [comment]
They just released Hakchi2 version 2.31, and while I can now use Retroarch without issue, the Reset Controller Hack and the Autofire still do not seem to work for me.

**Comment by ClusterM** [comment]
Can you send me NAND-C dump? Can you record video? Are you sure that you are holding buttons for at least 500ms?

**Comment by Fishstix61** [comment]
Don't have a new batch console in my possession right now.  Certain the buttons are being held for at least that long.  After modding games for some people, I know the serial numbers for the first batch end AND second batch begins somewhere starting with 208########etc.

**Comment by bgthang** [comment]
I went and used the default down and select on another new classic console a coworker bought same time as I did from walmart and when holding the default combo down for approximately  1second  it dropped us to main menu.  Was not able to get the turbos to work though

**Comment by bgthang** [comment]
the serial number on bottom of my console starts with CU212xxxxxxx

**Comment by Sludgetrough** [comment]
@ClusterM 
Please follow this link for the NAND-C dump from my new generation NES Classic.  
Serial number:  CU211919399

[NAND-C Dump on Google Drive](https://drive.google.com/file/d/1HxtR9ztmmEFQ0UYrfeG6cO5t_OpXzyy_/view?usp=sharing)

If there's anything else I can do to help, please just let me know what you need.  Peace!

**Comment by ClusterM** [comment]
@Sludgetrough 
Seems like you have old kernel version installed. Are you tried to reinstall custom kernel using latest hakchi2 version? 
Do you know how to use telnet? Can you show output of "uname -a" command?

**Comment by ClusterM** [comment]
Anybody?..

**Comment by Sludgetrough** [comment]
@ClusterM Sorry for the delay, I was out of town last week.  You are correct, I used an old version because HakChi2 2.30 would brick the unit when I flashed the new kernel.  I see a new version is now out.

I flashed the custom kernel using HakChi2 2.31, but still got the MD5 checksum warning, so this is NOT fixed in the new version.  Loaded in my games and verified that the unit works fine even after a few reboots.  Looks like BOTH THE RESET AND TURBOFIRE GLITCHES ARE FIXED.  This is awesome, thanks for getting that 2.31 patch up so quickly.  Would you still like to see the NAND-C dump and PuTTY output?

@RythonTheSNES The reset button combo will not work unless you use the HakChi2 2.31 menu to select Kernel --> Flash Custom Kernel and follow the instructions from there.   Afterwards, verify your controller button combo and autofire settings, then do another sync.  The autofire is wonky; you have to hold select, then hold the a/b button for about 3-5 seconds to get it to toggle.  Just keep holding both until you see the autofire start to happen on-screen, then you can release select.

**Comment by ClusterM** [comment]
MD5 warning is not a error, it shouldn't be fixed. You should be warned
about it.

пт, 3 авг. 2018 г., 4:28 Sludgetrough <notifications@github.com>:
