### ISSUE TITLE
canbe write kernel but cannot be sync games

### ISSUE THREAD

**Issue by ddknight** [ClusterM/hakchi2#1351]
![qq 20180630164831](https://user-images.githubusercontent.com/7845121/42123485-7cd017fa-7c85-11e8-9c96-329dc7860179.png)
hakchi2 version: 2.3.0, debug mode: on
As you see the picture of the console windows logs.
when I finished custom kernel write job,I going to sync with my minifc,but my pc do not found any usb plug-in devices.
It is confused.
plz help me.

**Comment by ddknight** [comment]
this issue only find on version 2.3.0,my miniFC(Japan) works well with version 2.2.1f

**Comment by sandog78** [comment]
I'm having an issue still with 2.21 get enter a password on screen after flashing
