### ISSUE TITLE
New NES Classic Mini - Can't syncronize, and doesn't work anymore

### ISSUE THREAD

**Issue by PatLaprade** [ClusterM/hakchi2#1352]
Hi there,

I just bought the new version of the NES Classic Mini and was trying to add more games following Hakchi tutorial with Hakchi 2.17d

Hakchi says that after adding modules (the only one I added was retroarch), the red light from the power button on the NES should stay on and therefore the green light next to the number of added games should be green. Mine doesn't stay on and at the same time, I can't find the NES Mini in my devices on my computer. 

When I unplug the USB cord and replug it, the power light gets red for a few seconds and then goes off again. 

So I did reset and power at the same time, then my computer finds it in other devices, but the red light doesn't come back. So when I try to syncronize, of course it doesn't work. My driver is installed so this is not the issue.

I decided to stop trying to make it work and plug it back on my tv, and now the whole thing doesn't work anymore. It says SHUTTING DOWN on my TV and then the power button light disapear. 

So not only am I not able to add any new games, I'M not even able to play with it at all.

Can someone please help me?

Thanks!

**Comment by callusdew** [comment]
Having the same issue with my new NES classic, but using 2.21b.  Running the debug version now.  Hope someone can help!

Base directory: C:\Users\callu\Desktop\hakchi2_debug
Loading config
Starting, version: 2.0.21.32
Loading games
Loading C:\Users\callu\Desktop\hakchi2_debug\data\nescarts.xml
Loading C:\Users\callu\Desktop\hakchi2_debug\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
Executing task: DumpKernel
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 128 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 12624 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 49152 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 48 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
Error: USB read error: IoTimedOut   at com.clusterrr.FelLib.Fel.ReadFromUSB(Byte[] buffer, Int32 offset, Int32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 208
   at com.clusterrr.FelLib.Fel.ReadFromUSB(UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 217
   at com.clusterrr.FelLib.Fel.FelWrite(Byte[] buffer) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 229
   at com.clusterrr.FelLib.Fel.FelRequest(RequestType command) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 250
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 264
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 16 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWFELVerifyDeviceResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWFELVerifyDeviceResponse.cs:line 26
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 275
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Executing: C:\Users\callu\Desktop\hakchi2_debug\tools\unpackbootimg.exe
Arguments: -i "C:\Users\callu\Desktop\hakchi2_debug\temp\kernel.img" -o "C:\Users\callu\Desktop\hakchi2_debug\temp\kernel"
Directory: C:\Users\callu\Desktop\hakchi2_debug
Exit code: 0
Executing: C:\Users\callu\Desktop\hakchi2_debug\tools\lzop.exe
Arguments: -d "C:\Users\callu\Desktop\hakchi2_debug\temp\kernel\kernel.img-ramdisk.gz" -o "C:\Users\callu\Desktop\hakchi2_debug\temp\kernel\initramfs.cpio"
Directory: C:\Users\callu\Desktop\hakchi2_debug
Exit code: 0
Executing: C:\Users\callu\Desktop\hakchi2_debug\tools\cpio.exe
Arguments: -imd --no-preserve-owner --quiet -I "..\initramfs.cpio"
Directory: C:\Users\callu\Desktop\hakchi2_debug\temp\kernel\initramfs
Exit code: 0

**Comment by sandog78** [comment]
where are all the evil genius at working on the issues with the new ver of the classic?

**Comment by callusdew** [comment]
Found the solution!  I have downloaded Hakchi CE 1.2.5 and can confirm it works with the new NES Classic.

https://www.reddit.com/r/miniSNESmods/comments/8tp8wi/warning_do_not_use_hakchi_230_use_hakchi_ce12x/

**Comment by jayd189** [comment]
@callusdew I couldn't get Hakchi CE 1.2.5 to even install on my NES.

**Comment by callusdew** [comment]
@jayd189 Did you move your kernel dump to the CE folder and reload it? I had to move my dump from the 2.17 folder I had it in originally and reload it from there before the CE would work.

**Comment by jayd189** [comment]
I couldn't get it to reboot.

edit: That worked.  Thank you

**Comment by sandog78** [comment]
I have only used the new ver does anyone have the steps for using 1.2.5. I can't seem to get it working I'm getting an error. I added the dump folder from the newest ver I tried first before I knew it didn't work

**Comment by retroaddict** [comment]
Reflash the original kernel by going to the 'Kernel' menu and select 'Flash original kernel'. After this it is complete, you will be able to re-hack your nes classic. Sadly until the current kernel is supported, you might have to reflash the original kernel everytime you want to add new games.

**Comment by ClusterM** [comment]
I can't support old versions.

**Comment by sandog78** [comment]
Will you be working on a ver for the the newest nes classic

**Comment by Deathstalker83** [comment]
I tried everything mine won't reboot. Is there anyway to fix my NES Classic ?

**Comment by superurbi** [comment]
I had estrange issues once upgraded to 2.30 so the snesc menu was stuck in a subfolder and I could not go back. It doesn't let me restore the original Kernel (FEL mode no longer works for me).
So the only workaround I had was launch this command connecting to snesc via Telnet:
**rm -rf "/var/lib/clover/profiles/0"**
Now the menus work but the NES games don't work. At least I can use the SNES games and mame2003 games.
