### ISSUE TITLE
N64 Mini Future Compatibility?

### ISSUE THREAD

**Issue by mickystevo85** [ClusterM/hakchi2#1354]
Hi all and to the creator of this lovely program. I know it hasn't even been announced as yet but if/when the N64 mini is announced, is it likely this program will be updated to allow to add additional roms? Would it be a big effort to update this program or could it be updated and work within a week or so of the N64 minis release? Thanks :)

**Comment by Shoothimnow** [comment]
Can you please close this _**issue**_.  I would re-ask this on reddit.  This is a place for the creator and contributors to fix bugs in code, not a forum where you chit-chat.  If the creator comes on here to see how everything is going, he will see 193 issues that need code fixes.  This _**issue**_ isn't an issue.
