### ISSUE TITLE
MD5 Checksum is unknown (new batch, NES Classic AUS release)

### ISSUE THREAD

**Issue by emukidid** [ClusterM/hakchi2#1359]
Unmodified, straight out of the box (Nintendo re-released it here recently):

![image](https://user-images.githubusercontent.com/4575117/42409583-98268994-821b-11e8-853d-1a627e5e3df7.png)

**Comment by Brds7t7** [comment]
Issue can be closed as Cluster has already listed as fixed for the next release.

https://github.com/ClusterM/hakchi2/compare/2.30...stable

**Comment by Skyline969** [comment]
Can confirm that this MD5 also shows up in Canada.

**Comment by Stygian88** [comment]
Identical in eur as well for the new batch

**Comment by zanloy** [comment]
I got the same for my new batch NA/US NES.
