### ISSUE TITLE
Save States on SNES with NES Controller

### ISSUE THREAD

**Issue by mrridley** [ClusterM/hakchi2#1367]
I got NES Controller recently and faced some stupid problem.
Is there any way to save game with NES controller on SNES?
This feature doesn't work, because it's require Y-button :) 

Can hakchi do the trick ?

**Comment by joeysmallz** [comment]
If you add retroarch in your game list and then change the input configuration you probably can. Wouldn't it be easier with the snes controller or Wii classic controller.

**Comment by mrridley** [comment]
Well, i guess you're right. I just wanted to play in nes games with nes gamepad :)
Dual boot solved this issue for me.
