### ISSUE TITLE
Hakchi warns about mapper, not an issue with RetroArch

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#137]
Hakchi is warning about mappers, but "technically" they work fine now if you install the RetroArch modification.  Maybe either update the text (to point users to RetroArch if not installed) or remove the warning if modification is detected.  

It would appear the hack on the NES is smart enough to figure out the incompatible games and automatically launch them with RetroArch instead.  Genius!

**Comment by warlockv2** [comment]
currently it gives a proper warning, but does informing you retroarch should let the game work,  just give your the option
