### ISSUE TITLE
Folder Graphic Bug

### ISSUE THREAD

**Issue by Kaelivoth** [ClusterM/hakchi2#1378]
I have encountered a bug with on v1.2.5 of hakchi2 CE with the letter O graphic on folder letter O: What happens is that it looks right from the Hakchi menu of folder customization but when viewed on the snes classic it has the graphic for the letter P instead, so I have 2 folders with the letter P on them when I look at it on the SNES classic itsself. I am using the dtm_external_retroarch_5_12_18.hmod, haven't applied the dtm_font_remount_5_12_18.hmod as I'm not sure it deals with the issue i'm referring to.

**Comment by Kaelivoth** [comment]
OK the solution I found is to use the default alphabetical organization manually by clicking the option in the gui itsself  with the folders containing the bug.

**Comment by Brds7t7** [comment]
Hakchi2 CE and its mods aren't built or maintained by Cluster. It's a fork made by a different team.

Please close this issue and post any future issues relating to CE here:

https://github.com/TeamShinkansen/hakchi2/releases/

**Comment by Kaelivoth** [comment]
close #1378
