### ISSUE TITLE
Transifex language translation crowdsourcing services

### ISSUE THREAD

**Issue by Hedda** [ClusterM/hakchi2#138]
Suggest that you setup a new project for Hakchi (and NES/Famicom Mini) on Transifex translation services to get crowdsourced translations from your community.

https://en.wikipedia.org/wiki/Transifex

Many popular open source software projects use Transifex workflows to get free string language translations from their communities.

Example of an open source project using Transifex for many years is Kodi as you can read here:
https://kodi.tv/new-translation-service/
and here:
http://kodi.wiki/view/Translation_System

For end-users wanting to help out with the project using Transifex to translate strings is as easy as using a wiki.

Users just need to register an account for free on Transifex then join the project for the languages they know and begin to translate strings they understand.

All you need to do is point to files on GitHub you want translating and then copy/pull them from Transifex on a regular bases (usually before each release).

**Comment by ClusterM** [comment]
Transifex is not very good. It's better to use tools like ResxTranslator.
