### ISSUE TITLE
Access to path denied, tried all the fixes available

### ISSUE THREAD

**Issue by kadece** [ClusterM/hakchi2#1381]
[debuglog.txt](https://github.com/ClusterM/hakchi2/files/2217364/debuglog.txt)

Hello, I've tried to synchronize games, but during uploading a new kernel a file can't be accessed. AV software is disabled, every permission seems to be granted, but the bug keeps occuring. Thankfully the console works.

I've previously tried with older version of Hakchi (1.2.5) and actually managed to get a new kernel into the console (it displays Hakchi screen during startup), yet the application couldn't see the console after, so it was impossible to upload anything. Please help :(

**Comment by daPhie79** [comment]
v1.2.5 isn't an older version, but a different branch with different protocols. it's actually using the most up-to-date hakchi scripts.

**Comment by kadece** [comment]
Alright, still it can flash the kernel to the console, but cannot see it later and sync games, which is weird.

**Comment by sandog78** [comment]
Having the same issue.

**Comment by kadece** [comment]
While I couldn't do anything with the "official" branch, it did help to run v1.2.5 on a different machine. Uploaded a kernel and a bunch of games without a problem. Still don't know what was the problem though.
