### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by Newarkian** [ClusterM/hakchi2#14]
I did everything successful and every game worked. Only thing not working is the sound. Any ideas or solution for this issue?

**Comment by soulctcher** [comment]
Did you mess with the setting highlighted in the screenshot below, or somehow remove the line?

![image](https://cloud.githubusercontent.com/assets/25140139/22048757/20b221f8-dcfd-11e6-8077-1870a7e64035.png)

If not, then you've likely got something else going on such as the volume is too low or your sound is muted.
