### ISSUE TITLE
Feature Request: merge Game List and Folder Manager into the same view

### ISSUE THREAD

**Issue by abijanfar** [ClusterM/hakchi2#140]
I know this would be a big change, but maybe for the next major release the Game List view and Folder Manager view could be merge into one. I think this would greatly streamline the application and make it easier to manage your library of ROMs.

**Comment by bfluryx1234** [comment]
Very similar request to my Issue 126 which was manage folders in the main view :).  I suspect he did it this way just to get a working version out on time.  Now that the backend is complete, I'm sure it will eventually be adjusted to work within one menu (or at least be accessible without having to hit sync :P)

**Comment by ClusterM** [comment]
Yep, I'll do it later.
