### ISSUE TITLE
Feature Request: Default Information for New Games

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#141]
The system is defaulting a date of 7-15-1983 and publisher Nintendo for games when it can't find a valid one.  Could we modify this so that the defaults are a bit more obvious such as 1-1-1901 and publisher "Unknown".  Would be real slick if it could pull the information from some wiki/database...

It is doing the same for 1P, 2P, and 2P Simultaneous by defaulting to 1P.  Maybe adding a forth option of "Unknown" which could always translate to 1P when transferred to the NESC could make it more obvious this hasn't been set as well?  Since it is getting crowded on that side, suggest making this a dropdown list as well.

**Comment by abijanfar** [comment]
Maybe we can expand the nescarts.xml or have different ones like sfccarts.xml.

**Comment by ClusterM** [comment]
Ok!
