### ISSUE TITLE
Change description of hakchi2 repo

### ISSUE THREAD

**Issue by asiansteev** [ClusterM/hakchi2#143]
```diff
- Tool that allowes to add more games to NES Classic Mini
+ Tool that allows you to add more games to your NES Classic Mini
```

**Comment by sanjay900** [comment]
Why not just make this a pull request instead of an issue?

**Comment by asiansteev** [comment]
Can you edit a repo description from the repo? I thought it was just on
GitHub ui

On Feb 21, 2017 6:40 PM, "Sanjay Govind" <notifications@github.com> wrote:

Why not just make this a pull request instead of an issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ClusterM/hakchi2/issues/143#issuecomment-281518962>,
or mute
the thread

**Comment by sanjay900** [comment]
Yeah i misread what you said before, sorry.

**Comment by ClusterM** [comment]
Done. Thank you :)
