### ISSUE TITLE
Absolute rubbish

### ISSUE THREAD

**Issue by tenKinetic** [ClusterM/hakchi2#1431]
Can't find this file, can't do that, need this which needs that which needs a plethora of nonsensical SHIT.

Is windows crap or is this crap?

Ah, both.

**Comment by tenKinetic** [comment]
Wow that was harsh haha. Would love to know how to provide this thing with its 'key-file' though.....

**Comment by infostreams** [comment]
Just go and use another tool then. Oh wait. The words you're looking for are "Thank you for creating this tool for me. I'm sorry I don't know how to use it."

**Comment by tenKinetic** [comment]
Wow. Incorrect. Big time. .net reference errors on startup. Not me buddy!

**Comment by tenKinetic** [comment]
I'd love to use it!

**Comment by tenKinetic** [comment]
Not everything works. Ce la vie...
