### ISSUE TITLE
SNES and genesis games crashing

### ISSUE THREAD

**Issue by puregamingnut** [ClusterM/hakchi2#144]
wonder if anyone can help all genesis and SNES games I install will load fine but will crash after a few seconds of play i get a black screen my nes mini will lock up pressing the power off/on does nothing i have to pull the power cable to be able to restart the only mod I have install is standard retroarch . i have 33 nes game along with the pre installed 30 and 10 in a folder and 10 genesis game in a folder

**Comment by bfluryx1234** [comment]
You get no error message at all?!?  I think the auto save is set to 10 second increments, time it and confirm if it is always around 10 seconds?!?  If so, do your ROMs have any special characters including "." in them?

**Comment by puregamingnut** [comment]
yes they all have special characters like (USA) i will take all  these out and try thanks

**Comment by puregamingnut** [comment]
ok removed all special characters from my ROMs uninstalled hackchi from my mini and installed it again with retroarch hmod but still getting the lockup on my new mini as above. only thing that's different from hackchi 2.11 about half way when sync games to my nes mini half way say I'm install slot of ROM so it gets me to do the reset and power button but I guess this is normal? can anyone help I don't know what else to try

**Comment by bfluryx1234** [comment]
Have you tried just installing a single game?  When you install more than a certain size/number of games you will have to do the reset in the middle.  The instructions aren't as clear as they could be for this one.  You need to wait for the power light to go out, hit ok on the message pop up, while holding reset hit the power button TWICE on the unit (wait about 10 seconds and it will resume).

Sometimes after you flash it will act a little strange on the first boot (for example the controller may not work), all you need to do is reboot the machine a second time and that should resolve it.

BTW, my apologizes I should have clarified that '(' were allowed in the file name.  You definitely can't have periods and it seems reasonable to assume that certain other special characters such as % or ^ may cause issues as well...

Again does this happen at 10 seconds on the mark every time?  Have you tried to install the cloverApp?

**Comment by ClusterM** [comment]
Sorry, RetroArch in the another repository.
