### ISSUE TITLE
Request: Enable all NESCE ROM space avalaible for non-NES games

### ISSUE THREAD

**Issue by 1lokolo1** [ClusterM/hakchi2#145]
Hi Cluster, 

I'm making some test without games, and using for each rom a hakchi2 game folder, never can I upload more of 30-40MB and the size of the modules RA is no more 20-25MB. 
I think that for the NES games can allowed to add roms until ~300MB without issue.

Thanks so much in advance. 

Rgs.

**Comment by ClusterM** [comment]
This is kernel size limit. I found a workarond but it's need some time to code it.
