### ISSUE TITLE
Savefiles?

### ISSUE THREAD

**Issue by Ask0o** [ClusterM/hakchi2#1463]
Hi! I don't know if it's OK to post this here but I'm wondering, what happens to my existing savefiles on my SNES mini if I flash the kernel to add more games? I'm currently playing FF3/6 and I'm about 25 hours in for the second time becouse I changend the names of the chars and wanted to follow a guide wich was impossible.

**Comment by ClusterM** [comment]
Hi. It will not affect savefiles .
