### ISSUE TITLE
Y button is acting as the b button??

### ISSUE THREAD

**Issue by williamroark** [ClusterM/hakchi2#1465]
So I've hacked my American SNES classic with the 2.30 version of hackchi2. I go to play Kirby Super Star, and I find that I can't inhale, as my Y button is acting like the B button and is making me fly. Also, it is acting much quicker than the B button does, for example, when I hold the B button to fly Kirby flies up at the normal rate, but when I hold Y, Kirby flies up really quickly, as if I'm mashing the B button quickly. I have no idea why this has happened and it's very upsetting, as I was about to beat the game with my sister. (I haven't played since late 2018). I tried removing some games, and only have a total of 107 games on the system now, and so I have no idea what could be wrong. I went into Super Mario World and the Y button is again acting like the B button, so it seems to hold true through all the games. Please help!!

**Comment by Yosh1002** [comment]
Bruh Did u Download on the Mod Store Canoe?

**Comment by williamroark** [comment]
I got rid of all the roms, put maybe 1/4 of them back on, and everything is running smoothly now so ¯\_(ツ)_/¯ i'll close this post now
