### ISSUE TITLE
8Bitdo Controller Support

### ISSUE THREAD

**Issue by stevetb** [ClusterM/hakchi2#147]
The company 8Bitdo makes a large variety of Bluetooth controllers.  Almost all of their controllers (with the exception of the N64 version) are high quality and match the OEM controller design.  Anyone that has used one knows the high quality these controllers are.

8Bitdo has a Classic NES version of their NES30 controller which also includes a Bluetooth dongle which is inserted into the Classic NES controller port.  Once paired this gives you the capability to use the NES30 controller or any of their other high quality controllers on the Classic NES.  A quick search for 8Bitdo controllers on Amazon will show all available controllers and their respective ratings, mostly excellent reviews, good stuff!

I would like to see support added for the 8Bitdo line of products.  Support I specifically mention is X / Y buttons, R / L Shoulder buttons.  Analog stick are also available on the N64 and NES30Pro controllers which would be nice for N64 emulation.

For NES emulation, I would like to see X / Y buttons have the option to be used as Turbo Buttons, similar to how the NES Max controller worked.

Thank you for your consideration of adding this into the Hakchi interface

-Steve

**Comment by warlockv2** [comment]
i already had this issue up,  its not the hakchi issue, its 8bitdos, they need to make new firmware for the retro reciver to have function on all buttons.  right now its not configured to recive those inputs

**Comment by stevetb** [comment]
@warlockv2 - Hi there!  I have looked through all of the open issues and do not see your particular issue.  I do think in reading your comment we have different issues.  For my NES30 controller, the A / B / X / Y / R / L buttons all work within the NESC.  The L & R both match the mapping for A & B.  The X & Y are reversed compared to the A & B.  So, the buttons all work and I do not see that as being an 8Bitdo firmware issue as they are correctly working.

My Issue is more of a feature request to provide better setup for 8Bitdo Controllers.  I would like have the capability to map the controller in the NESC and have it work out of the box against the software.  For the NES platform I would like to see the option for Auto-Fire buttons, similar to the NES Max.

**Comment by warlockv2** [comment]
i dont think you understand....  the 8bitdo controllers receiver, is programmed to work that way.  not the nes classic.  you should read the 8bitdo forums to understand more,  also my issue is closed not open

**Comment by stevetb** [comment]
@warlockv2 -  I'll let you handle this.  It seems you're the big man around here.

**Comment by JoshAubrey** [comment]
The reciever dongle firmware is causing it, 8bitdo never planned for everyone to use it on anything but NES games and hardcoded those controls into it. No new firmware yet to fix it.

**Comment by JoshAubrey** [comment]
So essentially the controller sends L to the dongle, the dongle recieves L and then transmits A to the NES.

**Comment by JoshAubrey** [comment]
http://forum.8bitdo.com/forum-36-1.html
