### ISSUE TITLE
RetroArch GB save states and battery save erase when NES is reset

### ISSUE THREAD

**Issue by Dinos24SP** [ClusterM/hakchi2#148]
My GB save states and battery save work perfectly (saving and reloading, switching games, restarting games and loading saves, etc is no problem) until I turn the unit off and back on, at which point it completely forgets the RetroArch save states (NES Suspend Points for non-RA games do not erase). Have not tested with SNES or GBA yet, but I predict the same will happen. Any suggestions? Thanks!

**Comment by ClusterM** [comment]
Sorry, RetroArch in the another repository.
