### ISSUE TITLE
Added games show 'MAR-ZEL'

### ISSUE THREAD

**Issue by christopherpm** [ClusterM/hakchi2#151]
I've only tried to add 2 games to my NES Classic so far.

I first added Maniac Mansion (Europe) and rebooted. However, the ROM showed up with the name of 'MAR-ZEL' and with no cover art.

To make matters worse, none of the original 30 games that follow M in the alphabet were showing.

So, I removed the game and re-synced. My original 30 games were back.

Thinking that it was the ROM at fault, I then installed Rainbow Islands (Europe), and experienced exactly the same issue - ROM showed as 'MAR-ZEL' with no cover art, and all original games fom M onwards missing again.

Once again, I removed the additional game and re-synced, and I'm back to my original 30 games.

I didn't receive any errors during the kernel builds or flashing.

I'd appreciate any ideas, advice etc...

**Comment by B9KnM8UqQ2W2Vwk7uvZ7** [comment]
Is that not a folder rather than a ROM?

**Mar**io Bros. - **Zel**da II: Adventure of Link

**Comment by christopherpm** [comment]
Well, slap me round the face with a wet trout and call me a Muppet! So it is....
