### ISSUE TITLE
Problem transfering arcade roms

### ISSUE THREAD

**Issue by laahel** [ClusterM/hakchi2#152]
Hello.
Thanks for your project it's amazing. Thus, i encountered a strange behaviour.

First, let me say i tried last version 2.12 with 115 MB of console roms (NES, Master System, Turbo Grafx, Game Boy and Game Boy Color). All is OK with no problems so far.

Next, i wanted to try some arcade games with fba core : 50 games for around 80 MB. Problems started. To try to isolate what went wrong, i ended up loading only the arcade games (no console games, no original 30 games. Smaller rom is 62 kB and bigger rom is 7.10 MB.

When the total size of arcade roms i try to load is under 28 MB, all is ok, at the end of the process, ther is a sound of disconnected peripheral, led goes on and seconds later goes off. Games on console.

When total size of arcade roms goes above ~28 MB, at the end of the process, there is a deconnecting sound, led blinks, then goes on, and there is a connecting sound. Led then never goes off. If i shut down the console, no game is copied on.

I tried with different combinations, from 17 games to 32 games, it happens always around 28 MB.

Same thing happens with "automatic multiple loading".

Thanks

**Comment by ClusterM** [comment]
Seems like maximum kernel size was overflowed. You transferred it as archive? Kernel size calculated before compression, seems like this is problem.

**Comment by laahel** [comment]
Arcade roms were Mame zipped roms (put in a 7z archive for hakchi to import the rom without opening the .zip). Tried several combinations (big roms, small roms <500 kB), the problem occurs if > 28 MB of arcade roms. But less than 28 MB arcade roms and other roms are console, the process goes as normal.

**Comment by laahel** [comment]
Bug fixed with commit "Maximum kernel size reduced since it's calculated before compression".
