### ISSUE TITLE
Can't flash/repair custom kernel on Snes Mini

### ISSUE THREAD

**Issue by rorosprite** [ClusterM/hakchi2#1529]
I have previously flashed the kernel on a previous version, however, it seems i need to do it again. But whenever I try to, it always gets stuck on 14%, I've tried turning off the firewall, resetting hakchi, and now I've got my official snes mini cable, though i haven't tried it with that yet. does anyone know what i should do? I wanna play gba games really bad :(

**Comment by BluezamX** [comment]
Same issue. Installed some ROMs a few versions back, but now can't synchronize (couldn't find file AppData\Local\Temp\hakchi-temp\kernel\initramfs\key-file). When tried to dump the kernel, it get's stuck one done! with the only option being to cancel it.

**Comment by rorosprite** [comment]
wow, didn't expect anyone to comment on this thread to be honest lol, I'm almost glad to hear that we've had the same experience, i still haven't managed to fix it though sadly

**Comment by luigi1015** [comment]
I'm actually having the same issue on my NES mini. If you ever figure out how to fix it please let me know.

**Comment by luigi1015** [comment]
I found a fix, one that worked for me at least. Apparently I was running an old version of Hakchi. I downloaded the latest version (currently 3.9.1) at https://github.com/TeamShinkansen/Hakchi2-CE/releases and it worked like a charm.

**Comment by rorosprite** [comment]
yknow what I'm gonna try it again today LOL, I haven't done it since July last year but now I've got the official cable and version 3.9.1, what could possibly go wrong?

**Comment by JasperWijnhovenCGI** [comment]
I solved it a few days back, although I have no idea how. Just followed the standard procedure and installed the GBA emulator + the Golden Sun games. Good luck Roro!

**Comment by rorosprite** [comment]
oh. my. god. I was in the middle of retrying the process and it was looking grim, cause the system had to reboot a total of 3 times (dunno if that's normal lol) but it worked! I put my laptop in flight mode and I suppose thats what helped, but I'm honestly just so surprised it worked! I guess I can close this thread now, but thanks for the advice Jasper, appreciate all of you guys!😭👍
