### ISSUE TITLE
Impossible to Compile

### ISSUE THREAD

**Issue by 05121983** [ClusterM/hakchi2#153]
Hello !

Impossible to Compile github project of hakchi, it's normal?

Best Regards

**Comment by abijanfar** [comment]
I was able to build the project using VS 2015 Community. What error are you getting?

**Comment by 05121983** [comment]
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		MSB3103 : Fichier Resx non valide. La valeur demandée 'Del' est introuvable. Ligne 808, position 5.	hakchi_gui	C:\Users\ShaDow\Source\Repos\hakchi25\TreeContructorForm.resx	808

**Comment by baconcow** [comment]
This doesn't appear normal. Can you try the current commit ("Compression")? I just compiled it with with Visual Studio 2017 RC.

**Comment by 05121983** [comment]
I just updated visual studio community 2017 RC and i try commit ("Compression") but when i load project i have 2 problems. Unable to load HexDump.csproj and UsbTest.csproj. When I generate hakchi_gui, i have this error : Invalid Resx file. The requested value 'Del' can not be found. Line 808 position 5. (The file is TreeContructorFrom.resx)

**Comment by 05121983** [comment]
I tested by cloning the project and downloading the .zip and even problem

**Comment by laahel** [comment]
Just tested, i have the exact same error with VS2015 & VS2017 RC, with current commit ans 2.12 source.

**Comment by ClusterM** [comment]
Can you try it now? I cloned project and can compile it without any problems.

**Comment by laahel** [comment]
Unable to load HexDump.csproj and UsbTest.csproj -> No more error in latest commits
value 'Del' : a f***ng error with VS as i thought. Replaced Del with Suppr (french version of Del in my french VS install) and i was able to compile with zero errors in compilation.

**Comment by 05121983** [comment]
Cool now work with last commits ! i Have change 'Del' by 'Suppr' and i have no error now ! Thanks ClusterM and laahel !

**Comment by Christux** [comment]
Dears,
I had the same issue, resolved in setting VS2015 in english !
