### ISSUE TITLE
Hakchi 3.8 - moving from internal storage to USB stick storage

### ISSUE THREAD

**Issue by hoagie12** [ClusterM/hakchi2#1536]
Hi,

I just bought an OTG cable and a USB stick for my Snes Mini. The USB stick has been NTS formatted.
I installed new games from cores I never used before : ScummVM, Commodore Amiga.
Once they are recognized by hakchi, I clicked on export to USB.
The games do appear in the games selection screen, but they cannot been launched properly (I did install the latest cores required).
I expect I have to reinitialize the whole system so that the USB stick can be used... How can I do that ?

**Comment by ClusterM** [comment]
This is repo of hackhi 2, not hakchi 3.x
