### ISSUE TITLE
2.12 'Waiting For The Device"

### ISSUE THREAD

**Issue by monkeyass2017** [ClusterM/hakchi2#154]
I am using Windows Vista and was able to upload using 2.11 but for 2.12 Hakchi just say "Waiting For The Device". It will not upload games or install user mods. Not sure what to do so any help or fix would be appreciated. Thanks

**Comment by chinobaba** [comment]
Same here, using XP.  Always gets hung up on 'Waiting on Device'.  Reinstalled zadig, same, fresh install, same, fel mode, same…
Still using 2.11, which works on XP

**Comment by mrodriguezg** [comment]
Me too. In my case, I have recently purchased a new nes mini, so I've never done nothing before. Once the driver is instaled using zadig, I open hakchi2 and add some NES games. By pressing synchronize, the app tells I have to dump the kernel at first and a new window with a progress bar appears with the text "Waiting for the device" for an infinite time.
I'm using Windows XP.

How much time it takes to perform the dump?

**Comment by monkeyass2017** [comment]
It should only take a minute... hopefully 2.13 works with XP and Vista                                                                                                                                                                        Sent from my BlackBerry by the closest thing to a Sasquatch                                                                                                                                                                            From: notifications@github.comSent: February 23, 2017 7:37 PMTo: hakchi2@noreply.github.comReply-to: reply@reply.github.comCc: mccormack@eastlink.ca; author@noreply.github.comSubject: Re: [ClusterM/hakchi2] 2.12 'Waiting For The Device" (#154)  Me too. In my case, I have recently purchased a new nes mini, so I've never done nothing before. Once the driver is instaled using zadig, I open hakchi2 and add some NES games. By pressing synchronize, the app tells I have to dump the kernel at first and a new window with a progress bar appears with the text "Waiting for the device" for an infinite time.
I'm using Windows XP.
How much time it takes to perform the dump?

**Comment by chinobaba** [comment]
@mrodriguezg
Hakchi 2.11 is fine if you just want to add NES games.  2.12 gives seamless integration for snes, genesis…

**Comment by vj1096** [comment]
@monkeyass2017 I was wondering why this was marked closed. What was the resolution?

**Comment by monkeyass2017** [comment]
I had to update my windows to 10                                                                                                                                                                        Sent from my BlackBerry by the closest thing to a Sasquatch                                                                                                                                                                            From: notifications@github.comSent: February 28, 2017 3:23 AMTo: hakchi2@noreply.github.comReply-to: reply@reply.github.comCc: mccormack@eastlink.ca; mention@noreply.github.comSubject: Re: [ClusterM/hakchi2] 2.12 'Waiting For The Device" (#154)  @monkeyass2017 I was wondering why this was marked closed. What was the resolution?
