### ISSUE TITLE
Hakchi ce 3.9.1 cant open device

### ISSUE THREAD

**Issue by chevy2121** [ClusterM/hakchi2#1545]
I get this when i try try to hack my snes with hakchi 3.9.1.  I hacked my genesis mini before I tried to hack my snes mini againI know its not a fake, bought it brand new at best buy. And I've hack it before with an ealier version of hakchi.  I hacked it about 2 years ago and the original files i got off it were lost due to my pc hard drive crashing and was non recoverable. i am using the snes usb cord, and it also tells me that the kernal is outdate but anytime i try to update i get this error. any help with this would be greatly appreciated 

FelException
Can't open device
at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
at com.clusterrr.hakchi_gui.Tasks.MembootTasks.WaitForFelOrMembootableShell(Tasker tasker, Object syncObject, Boolean sdRequired)
at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\Admin\Documents\hakchi2 (non-portable mode)
Loading configuration
Loading spine templates
Starting, version: 3.8.0
Loading libretro core info files
..Executing task: ModTasks.GetHmods
Tasker completed all tasks, conclusion: Success
Building libretro core cross index
Done, 5 cores loaded
Loading C:\Program Files (x86)\Team Shinkansen\Hakchi2 CE\data\nescarts.xml
Loading SNES Cartridge Cache
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
..Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
..Executing task: <>c__DisplayClass0_0.b__0
Executing task: <>c__DisplayClass1_0.b__0
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.3, kernel 3.4.113.29-madmonkey, script v1.0.4-126
.Executing task: <>c__DisplayClass16_0.b__0
Can't open device at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
at com.clusterrr.hakchi_gui.Tasks.MembootTasks.WaitForFelOrMembootableShell(Tasker tasker, Object syncObject, Boolean sdRequired)
at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
Tasker completed all tasks, conclusion: Error
..Executing task: <>c__DisplayClass16_0.b__0
--- End of DEBUGLOG.TXT content ---

**Comment by chevy2121** [comment]
Oh and i am using the snes usb cord

**Comment by ClusterM** [comment]
It's not a hakchi2 CE repo.

**Comment by chevy2121** [comment]
If youre asking if someone else borrowed it or i sold it the answer is no.
