### ISSUE TITLE
Mini SNES Can't turn off playing Retroarch. 

### ISSUE THREAD

**Issue by Farrell39** [ClusterM/hakchi2#1546]
Hello! 
I updated recently to use Hakchi CE 3.9.1 and installed Retroarch Core, Nestopia and SNES 2010, and when I'm playing a NES/ SNES game over Retroarch the console don't turns Off when I switch the power button. So, I must switch reset too and immediately appears "SHUTING DOWN..." screen, or must unplug the USB cable. 
*No problem with original games runing with canoe. 

Someone could tell me how to fix it? 

I already did a factory reset and then reinstall the cores but get same issue. 

SNES Mini USA versión. 
Hakchi CE 3.9.1
RetroArch 190 Xtreme Ozone or RetroArch 190 Xtreme RGUI (only one of this installed)
Nestopia
Snes9x2010 Xtreme 

I would greatly appreciate your help!

**Comment by ClusterM** [comment]
This is not a hakchi2 CE repo.
This is not a RetroArch repo.

**Comment by Farrell39** [comment]
Hello!
I saw the issues and i see common questions about the hack of mini snes or
errors. Would you tell me whats the correct post?

Thank you!

**Comment by ClusterM** [comment]
https://github.com/TeamShinkansen/Hakchi2-CE/

**Comment by Farrell39** [comment]
Thank you!
