### ISSUE TITLE
System retains orphan files when deleting ROMs

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#156]
The system is storing files in at least /var/lib/clover/profiles/0 even after you remove the game.  I suspect these are less than 1 KB a piece, but there must be something else that is eating up storage as I get the impression something is hanging around as I can't transfer remotely nearly 300mb.  As another example, I uninstalled Stella, but I still find files related to the core are installed.

To be clear, the system "behaves" as if it successfully transferred 250mb+.  However, once booted it looks like nothing beyond 220mb or so is actually being sent across (games are just flat out missing), and I get C4 errors as well.  This doesn't seem to be specific to a folder (which are well divided).

What could eat up the number to bring the available storage down from 300mb to 220mb?  That isn't just save states...

**Comment by abijanfar** [comment]
I wish we had access to a command shell so we could look around the file system and do some house keeping. But without a keyboard I guess that would be kind of hard...

**Comment by sanjay900** [comment]
If all you wanted was file management, i wonder how hard it would be to make something like the retroarch file browser but just for managing files.

**Comment by BagginsKQ** [comment]
Just a simple program to show us the system files and maybe an option to 'delete' them from within the system itself might be useful? 

I know some of the flashcards offer that option in their UIs... as well ass ometimes 'copy and paste' options and minor folder creation options. Granted in the case of say a 3DS flashcard you also have touch screen options which makes typing so much easier.

**Comment by bfluryx1234** [comment]
Moved to a new issue https://github.com/ClusterM/hakchi2/issues/192 ... I think we just need an automated tool.
