### ISSUE TITLE
Famicom Mini font missing letters and numbers.

### ISSUE THREAD

**Issue by Godstrument** [ClusterM/hakchi2#157]
Have a Famicom mini. I updated to 2.12. Found the font is missing some numbers and letters.  In v. 2.11 the fonts were fine,  What happened in the new version?

**Comment by BaconGod** [comment]
i think cluster and the gang are already working on this or have resolved this and the other major issue on the famicom mini (original fds games not working - castlevania, metroid, zelda 1 and 2), just wait for the next update.  :)  i also use a famicom mini and reverted back to 2.11 for the meantime.

**Comment by ClusterM** [comment]
Fixed :)

**Comment by BaconGod** [comment]
@ClusterM  you rock!  so its already out?  :D
