### ISSUE TITLE
Program doesn't run anymore

### ISSUE THREAD

**Issue by StefanMili** [ClusterM/hakchi2#1572]
Hi,

I have used hakchi2 latest version 3.9.3, and it was working great.
Yesterday I started receiving these fail messages and cannot workaround these.

![hki1](https://github.com/ClusterM/hakchi2/assets/149595711/d2fdda46-22bc-4b1f-a1ac-15cbbdbbe322)
![hki2](https://github.com/ClusterM/hakchi2/assets/149595711/721b5447-f07f-49cb-9b7d-ddcb0ee7f2f3)
![hki3](https://github.com/ClusterM/hakchi2/assets/149595711/d5d0fb5f-6884-4d40-abaf-d5084dd79234)
![hki4](https://github.com/ClusterM/hakchi2/assets/149595711/7cac7bab-1d86-48ad-b312-fffb5cb49a31)
![hki5](https://github.com/ClusterM/hakchi2/assets/149595711/f8f521e2-1f8e-4358-8663-b94e1ef78e7d)
![hkif](https://github.com/ClusterM/hakchi2/assets/149595711/3fb7269a-b1cf-498d-91e3-159b52f64513)

I have tried uninstalling and installing again, same problem. Tried installing an older version of Hakchi2, and it doesn't fix this issue.

Any help? Thx

**Comment by ClusterM** [comment]
This is not my branch.

**Comment by StefanMili** [comment]
Hei,

Thank you for your response. Sorry if I posted something that's not a
welcomed subject.

I will try to find a solution.

Best regards, Stefan

**Comment by Drakonas** [comment]
@StefanMili Alexey was saying you are not using the version of hakchi2 from this Github. Ask the proper support team for your version.
