### ISSUE TITLE
Broken games not detected by new cores?

### ISSUE THREAD

**Issue by BagginsKQ** [ClusterM/hakchi2#159]
There are a number of games that were made for standard mappers already compatible with Nintendo Mini's standard cores... 

Like Bandits of the Ancient Kings, Uncharted Waters, the Last Ninja, or some of the shmups that game worked, but the menus were glitched etc. There were some games that just didn't load at all like ADND: Hillsfar as well.

Is there any possible way to make these games load most compatible retroarch (FCEUX or Nestopia) core is instead of the NESC standard cores by default?

Also what about games like Wisdom Tree Bible games? DO they work with any of the retroarch cores, and can they be autodetected to load with whichever core is most compatible as well?

What about mods like Star Tropics Music fix? http://www.romhacking.net/hacks/2229/

Is this compatible with any of the cores, can it be loaded by default (to a working core)?

**Comment by BagginsKQ** [comment]
https://docs.google.com/spreadsheets/d/1QTRTPODrhE5X55EciFsiQZaa-xVGlSD73Rt26Nd2rk0/edit#gid=587784428

For complete list of games that are broken, or partially broken and need to be able to detect more compatible cores...

**Comment by abijanfar** [comment]
install RetroArch and include the global command arg "--retroarch". This should run all the NES ROMs with no issues.

**Comment by BagginsKQ** [comment]
I find that retroarch is a bit slower than the mini's original NES core... so that's not a perfect fix.for every game necessarily.

But I'll still try it see how it does.

**Comment by BagginsKQ** [comment]
I've also read that there maybe some FDS issues with these other cores? But who knows.

**Comment by BagginsKQ** [comment]
Is there a way to force individual games on an individual basis to use the Retroarch fxeux emulator rather than built in emulator? 

If I use the global command to force all games to use retroarch how do you disable the global command if you don't want it anymore?

**Comment by BagginsKQ** [comment]
Ok yes you can manually use the --retroarch on any specific game's command line. You don't have to use it globally.

It doesn't seem to fix the problems with unlicensed games like "Bible Adventures" I guess the version of fceux being used on retroarch doesn't have compatibility with mapper 11 yet?

**Comment by bfluryx1234** [comment]
Trying to clean up the bug reports. If this issue can be closed, please do so. Thanks.
