### ISSUE TITLE
Feature Request: Keep Zipped files Zipped for non-NES games

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#160]
Cluster have you seen this link?
https://m.youtube.com/watch?feature=youtu.be&v=3uzrGi2bjGg

It suggests that maybe we can send across ZIP files for ROMs that aren't using the base NES emulator.  If so that could practically double the space for the larger games.  Can you confirm if this would work for say SNES or N64?

If so an easy solution might be just not to unzip any files going forward if the Retroarch modification is detected.  You would need to still read the file to know which emulator to run, but not much else.  Similar to how the modification automatically is called if you add games with mapper issues, it could also just be called for NES games if you add zip files.

This may require tracking which modifications are installed as well.  I am not sure as to whether that is being done yet or not, but it probably should be.  Gets confusing when trying to install/uninstall modifications.

**Comment by bfluryx1234** [comment]
Just saw issue https://github.com/ClusterM/hakchi2/issues/120 was closed which is basically the same thing.  Did we confirm this was added in version 1.13?

**Comment by pcm720** [comment]
From Hakchi2 2.13 release notes :
## What's new
- Compression support! Since RetroArch can run games directly from archives it's possible now to compress non-NES games using 7-Zip. This feature enabled by default but you can disable it in the settings menu. Also you can add the whole archive (required by MAME games).

**Comment by bfluryx1234** [comment]
Yep just saw that and was coming back to close it.  Thanks.
