### ISSUE TITLE
Can't Dump Original File From NES Mini

### ISSUE THREAD

**Issue by OrisX** [ClusterM/hakchi2#163]
I am trying to dump the kernel, I follow the instructions it gives me and nothing happens. I've tried multiple USB ports and multiple versions of hakchi2, but nothing makes a difference.

**Comment by debtslave** [comment]
try disconnecting all usb ports and only plug in the nes i had a similar problem

**Comment by OrisX** [comment]
That still didn't help. I don't even know if the driver is installing to begin with. It comes up with the command box that says it is installing but never gives any confirmation of whether it worked or failed. It just says push enter to exit.

**Comment by debtslave** [comment]
install the driver manually before cluster had the driver integrated i downloaded Zadig

https://www.youtube.com/watch?v=lvHWFyc5Txs

**Comment by OrisX** [comment]
I tried to use that just now and it said the installation was cancelled by the user. I disabled the driver signature enforcement before starting this.

**Comment by bfluryx1234** [comment]
We will need more details...

Please review: https://gbatemp.net/threads/nesc-faq-troubleshooting-for-hacking-nes-classic.462069/

And follow up with the details requested such as O/S, etc, if the issues continue,
