### ISSUE TITLE
Power LED never goes out after uploading kernel (maybe because of N64 roms??)

### ISSUE THREAD

**Issue by doctahoo** [ClusterM/hakchi2#164]
Hi,

I have found a strange behavior: my NES mini power LED stays ON forever after uploading games from hackchi 2.13b... Is it because there are some 7zipped N64 roms??

Thank you for looking into this.

**Comment by debtslave** [comment]
mine does the same thing its fine for sega and snes games

**Comment by debtslave** [comment]
must be the n64 roms

**Comment by anathematizer** [comment]
I was having the same issue but with every rom type - download the latest retroarch (from about an hour ago) it should show hakchi as 2.1.3c then I did not have a problem with the red light any longer

**Comment by 05121983** [comment]
See if in "mod folder" your files is in Unix mod with Notepad++

all files on mods/mod_hakchi and mods/mod_uninstall.

only busybox and resync is on Macintosh format

E.i on screen
![capture](https://cloud.githubusercontent.com/assets/25051653/23329873/92df5978-fb41-11e6-9974-b3b96f5b1a9a.JPG)

**Comment by bfluryx1234** [comment]
This was fixed on 2.13e.  Please confirm and mark the issue as closed.

**Comment by TVsIan** [comment]
Happened to me twice on 2.13e. Restoring the original kernel is fine, but installing the hacked one again resulted in the stuck power LED.

**Comment by black-pudding** [comment]
+1, in 2.13 after installing the custom kernel the power led went red and never went off again.

**Comment by ClusterM** [comment]
Should work fine on 2.14.
