### ISSUE TITLE
hakchi 2.13 hangs (slows to a crawl) after almost finished uploading roms.

### ISSUE THREAD

**Issue by Deathstryker** [ClusterM/hakchi2#165]
I have about 750 NES Roms and about 30 SNES roms I'm uploading. I get almost to the end of the upload process and it brings the prompt up about too many ROMS and the program starts slowing down to a crawl (can't hardly move the window around due to slowness) and the red light never goes off on my NES mini making it impossible to get past this part ( and causing me to have to abort the whole process. I've attached a screenshot of how far I get in the process. I'll do more testing to see if I can figure out what is causing it.
![hakchi](https://cloud.githubusercontent.com/assets/25914361/23327225/4d45636e-fad6-11e6-8f8f-cec74f285b80.PNG)

**Comment by Deathstryker** [comment]
I think I found out what is causing this. It's not letting me install games with compression when I add box art. If I remove the box art, I can install with compression.

**Comment by 05121983** [comment]
See if in "mod folder" your files is in Unix mod with Notepad++

**Comment by Deathstryker** [comment]
![files](https://cloud.githubusercontent.com/assets/25914361/23332039/a5fae68c-fb3f-11e6-8053-0f04e06667f4.PNG)
These are the only ones listed that you described that are not unix files. They are listed as "Windows"

2.13d supposedly fixes the issue I'm having with it but it aborts the process halfway through. Other people seem to be having that issue though (with 2.13d) so I'm gonna wait for Cluster to fix it and see if my issue is corrected.

**Comment by Deathstryker** [comment]
Downloaded 2.13e. This issue is fixed!
