### ISSUE TITLE
"Could not find file 'D:\hacchi2.213\temp\kernel\kernel.img-cmdline'" error

### ISSUE THREAD

**Issue by donduvall** [ClusterM/hakchi2#167]
Testing version 2.13d. Syncing 89 roms for a total of 85MB. About 80% through my sync roughly I get this error....

Could not find file 'D:\hacchi2.213\temp\kernel\kernel.img-cmdline'

**Comment by Wyvern94** [comment]
Same for me. Tried restarting PC and running as Administrator. No luck

**Comment by laahel** [comment]
Same thing here, with the latest commit (b2ba22c4f7ffc1d50c25c98058df3834448c4069). Worked OK with previous one (0d81b5f8614822c9f006de8d2ae049dbb700230f)

**Comment by Deathstryker** [comment]
![capture22](https://cloud.githubusercontent.com/assets/25914361/23332008/03e4cc8c-fb3f-11e6-8ddd-f45cb98103f2.PNG)

Same issue. File isn't in this directory when it looks for it.

**Comment by ClusterM** [comment]
Please redownload and try 2.13e.

**Comment by laahel** [comment]
All is ok now. Thx

**Comment by Deathstryker** [comment]
Seems to be working fine. Thanks for the quick fix!

**Comment by nappymike** [comment]
same here i was on 2.13d from this morning....got to about 86MB adding more games and got that same error...thanks @ClusterM for being so quick about resolving issuies
