### ISSUE TITLE
Any way to reset retroarch.cfg controller settings on the NES classic without reflashing everything?

### ISSUE THREAD

**Issue by anathematizer** [ClusterM/hakchi2#168]
This is on 2.13 (currently on 2.13d but it is not a version-related issue)

Screwed up something in the control cfg in retroarch settings and control pad no longer works in retroarch settings or any of the games launched by retroarch cores.  The original default was retropad.

NES games still work fine as long as they not launched through retroarch.

Have tried uninstalling and reinstalling cores, reflashing the custom kernel and re-synching games but still cannot navigate in the retroarch cfg screen and still cannot use the control pad with any game launched through a retroarch core.

**Comment by Wyvern94** [comment]
Well, just open Hakchi and uninstall retroarch, then reinstalling. This is also way quicker than everything you tried before. I had the same problem. Just do it and make sure you don't mess up next time.

**Comment by teconmoon** [comment]
You can also use a controller in Port 2 to navigate the menu usually even if player 1 gets screwed up

**Comment by bfluryx1234** [comment]
Whvern94 is correct.  Please close this issue,  thanks.
