### ISSUE TITLE
Could not find file 'C:\hakchi2\temp\kernel\kernel.img-cmdline'

### ISSUE THREAD

**Issue by dezign999** [ClusterM/hakchi2#169]
![hakchi](https://cloud.githubusercontent.com/assets/5609452/23332291/410f3510-fb45-11e6-94a4-d690752878b6.jpg)

Tried 2.13d to resolve the issue with Mame roms but I seem to have stumbled onto something new. The largest zip file I have is 16 megs.

**Comment by ClusterM** [comment]
Updated again. Please redownload and test 2.13.e.
Sorry for that :(

**Comment by dezign999** [comment]
Will do. Also, i rename my directories because i have a famicom mini and nesce. I tried leaving the original folder structure in tact and I received the same error with 2.13d. Trying 2.13e now.

![hakchi](https://cloud.githubusercontent.com/assets/5609452/23332314/97c48bb2-fb45-11e6-890d-945adc1105a9.jpg)

**Comment by dezign999** [comment]
2.13e fixes this issue. Thank you!

**Comment by ClusterM** [comment]
Hi!

Sorry for not so fast answer.
Try release candidate of the new version: http://clusterrr.com/temp/hakchi2_14_rc1.zip
February 25, 2017 6:31 PM, "dezign999"  wrote:
	Will do. Also, i rename my directories because i have a famicom mini and nesce. I tried leaving the original folder structure in tact and I received the same error with 2.13d. Trying 2.13e now. 

	 (https://cloud.githubusercontent.com/assets/5609452/23332314/97c48bb2-fb45-11e6-890d-945adc1105a9.jpg)
