### ISSUE TITLE
about "how to update" and some "mapper issues"...(^_^)

### ISSUE THREAD

**Issue by blackjack-78** [ClusterM/hakchi2#17]
Hi Cluster!

First of all, thank you for your job!

I just want to ask you about "how to update"; when i've downloaded a new version, does i need just to copy the new files in the "old" hackchi2. I do this way, but every time, i fear to lose the games installed and the original kernel...I'm not a programmer, just a simple"user", so sorry if it's look a little bit "dumb" to ask.

The next thing is about two games: Akumajou Special - Boku Dracula-kun (J) (aka "kid dracula) and Sakigake!! Otoko Juku - Shippuu Ichi Gou Sei (J).
I can't add and play those games...for the first it's the mapper# 23 and for the second it's the mapper# 16 who are the problems.

If you can make a"miracle" for me , it would be really "appreciated...lol.

Thank you comrade.

And sorry for my "bad" english...до свидания!

**Comment by ClusterM** [comment]
Hi!
Just copy and replace the new files into "old" hakchi2. Don't worry, update doesn't contain "games" folder, "dump" folder and "config.ini". So all games, dump and settings should be fine.

It's near impossible to port VRC games to MMC3 or other mapper :(
