### ISSUE TITLE
Retroarch not detecting GB games

### ISSUE THREAD

**Issue by cjwheatley** [ClusterM/hakchi2#171]
When I try to load my Gameboy games Retroarch is not detecting them, it does detect nes games that the base emulator won't play and loads them. I have also noticed that I have no Retroarch icon on my games screen. I have loaded the mod the way I was supposed to and don't understand what I am doing wrong.

**Comment by puregamingnut** [comment]
you need the Gameboy cores

**Comment by cjwheatley** [comment]
Do you recommend any? For Gameboy Color?

**Comment by cjwheatley** [comment]
Figured it out, loaded gambette core into user mods folder and installed it through the software.

**Comment by cjwheatley** [comment]
Now the save states aren't working for Gameboy games but do work for Gameboy Color games weird? Has anyone else had this happen to them?

**Comment by puregamingnut** [comment]
not tried gameboy or gameboy colour only been using gameboy advance and save states fine with that

**Comment by ClusterM** [comment]
Sorry but RetroArch is in another repo.
