### ISSUE TITLE
Save States not working with compressed games

### ISSUE THREAD

**Issue by trumisery** [ClusterM/hakchi2#172]
Before I uploaded compressed files, all games I had installed would show the suspended state and allow me to save the games... however,

Since I uploaded compressed games, the vast majority of games (that are not nes) do not offer the suspended state to allow for a save state. Save states work for all compressed nes games though...

I am slightly confused with that since the original rom file uncompressed saved just fine though compressed it doesn't... is there somewhere that I need to change an option? Or is this something that is broken with compressed files?

OS: Windows 10
Hack: Hakchi 2.13e (Cluster's version)
Compression Format: .7z
Formats of Roms: gba, sfc, md, sms, pce

Very few games have allowed me to have a suspend point. Any thoughts? May just go back to uncompressed at this rate to keep the save spots...

**Comment by ClusterM** [comment]
RetroArch mod version?

**Comment by ajmi982** [comment]
This would suck as I'm flashing an entire Kerbal filled with compressed ROMs right now.

**Comment by R3ntZ** [comment]
same here, save states working for nes and compressed cps1 games, but not for all other consoles. (i have only zip files)
retroarch version is 1.4.1

**Comment by trumisery** [comment]
Dumb question... where do I find the version number for RetroArch? Same one I have been using since version hakchi2 v2.12

**Comment by R3ntZ** [comment]
if u run the "app" on the nes mini you should see it on the bottom of the screen

**Comment by R3ntZ** [comment]
i fixed it reinstalling retroarch and the cores.

https://github.com/ClusterM/retroarch-clover/releases/download/0.4-fix/release.zip

downloaded from:
https://github.com/ClusterM/retroarch-clover/releases/

**Comment by trumisery** [comment]
Thank you @R3ntZ that seems to have done the trick for a quick test... I am going to check it out later and see if it is indeed my problem.
