### ISSUE TITLE
Games zipped under 30MB in size flagged as too big. Not loading. 

### ISSUE THREAD

**Issue by ajmi982** [ClusterM/hakchi2#173]
Perhaps I'm mistaken but I thought asking as no single room is bigger than 30mb u can flash with no problem. I added Donkey Kong 64 which zips to 26mb but it fails to load. Too big error pops up.

**Comment by bfluryx1234** [comment]
What is the exact error?  Zipped games with more definitely have been confirmed to load.  Was this the size of the original zip or the 7z that Hakchi created in the games folder?

**Comment by ajmi982** [comment]
What was created by Hakchi. Think u can close this. Haven't had the issue in the last few flashes.

**Comment by ClusterM** [comment]
Fixed in 2.14.
