### ISSUE TITLE
Item scrolling with too few items is very jumpy

### ISSUE THREAD

**Issue by teconmoon** [ClusterM/hakchi2#174]
Not sure if this is a known issue or not, but if there are not many items on the home screen or in a subdirectory, when you're scrolling back and forth the displayed items are jumping all over the place.

This doesn't affect how selectable the items are, but very visually distracting. See linked video for example (no audio). The Home Menu and the GameBoy folder are jumpy, but the GameBoy Advance folder with 10 games is fine.

[YouTube Link](https://youtu.be/swK6ZyIUdxc)

Thanks for reading and thanks for this great tool!

Edit: Issue is most noticeable when scrolling right, not bad at all when scrolling left

**Comment by baconcow** [comment]
While I am not sure if this issue is documented here, I have seen it documented on GBAtemp, with video similar to yours. I believe it is a known issue.

**Comment by ClusterM** [comment]
This is problem of NES Mini's shell, it's designed to show 30 games. You need at least 12 games to show them without glitches.
