### ISSUE TITLE
MMC5 emulation - Manual select NES emulator

### ISSUE THREAD

**Issue by llioncourt** [ClusterM/hakchi2#175]
The default NES emulator MMC5 mapper emulation is only good enough to run Castlevania 3, All 2nd generation Koei games, that use the same mapper, are not fully working on it.

I'd like to be able to manually select the emulator for the NES, or at least mark those games as not playable so hakchi2 can assign Retroarch cores to them instead of the default emulator.

Thanks for the amazing work so far, You made me buy this console by the moment I saw your software, otherwise I'd not get it! :)

**Comment by BagginsKQ** [comment]
On indviidual games add --retroarch to the end of the command line option. They'll manually load fceumm support.
