### ISSUE TITLE
run cps2 games

### ISSUE THREAD

**Issue by R3ntZ** [ClusterM/hakchi2#176]
hi, I have installed and setup everything, all works (cps1, others fba games, genesis,...) except cps2 games like marvel vs capcom. I pass the /bin/cps2 as argument, but can't load any of them. suggestions?

**Comment by baconcow** [comment]
Please post this issue at the [retroarch repository](https://github.com/ClusterM/retroarch-clover/issues) as it is out-of-scope for the hakchi2 repository.

**Comment by R3ntZ** [comment]
ok, but having seen it working on some youtube video i tought was just a parameter or the way it's lauched, I tried...
