### ISSUE TITLE
error message: could not find a part of the path temp

### ISSUE THREAD

**Issue by markusjunior** [ClusterM/hakchi2#177]
Hi there 

I am using the latest ´Version of hakchi (2.13d). Flashing the custom kernel went smoothly. Also adding a couple of ROMs for NES and even snes together with the retroarch.

However, for some reason the hakchi tool abort with the error message: could not find a part of the path temp

This happens always when I trigger "syncronize selected games....". First, it appears "building custom kernel".... normally this takes ´just a few seconds and the uploading process starts. But as mentioned, for some reason bevor the uploading part starts, the error message appears.

edit:
imho it has not anything do to with the amount of roms... right now I have just 55 of 80 selected. Some SNES and some NES fails as well, so not only snes roms.

can anybody help?

cheers
Markus

**Comment by markusjunior** [comment]
well some update. Now it becomes weird, but its on my side reproducible.

I do have ROMS a, b and c (games acutally doesnt matter, I use always the same three roms for testing). here comes the weird thing: I can syncronize rom a+b, but not c. However, next try I can syncronize b+c, but not together with rom a. Same goes on, I can syncronize a+c, but not b. I hope you see what I mean.

**Comment by R3ntZ** [comment]
try to update hakchi to the last version: e
https://github.com/ClusterM/hakchi2/releases

**Comment by markusjunior** [comment]
YES DUDE! ;-) That new version kicks it! It went straight trough with the whole set what did not work previously...  perfect now!

**Comment by R3ntZ** [comment]
cool, so now you can close the issue ;)
