### ISSUE TITLE
any chance... and gun nac

### ISSUE THREAD

**Issue by nekonall** [ClusterM/hakchi2#179]
thanks for the awesome work . In one of the earlier versions you had it where we could remove the thumbnails at the bottom .. any chance you could put that option back cause to be honest they annoy the hell outta me .. also is there any way to fix gun nac .. doesn't matter which emulator i use the game plays but the title and shops are jumbled Japanese thanks again

**Comment by baconcow** [comment]
Have you tried **both** retroarch emulators; fceumm and Nestopia?

**Comment by nekonall** [comment]
yeah  i dont understand why it does it .. even tried downloading the rom from mutiple sources .. im not sure what im doing wrong but i cant get gun nac ,crisis force ,or kid dracula to work  tested over 400 other nes / imports tho with no problems

**Comment by BagginsKQ** [comment]
Gun Nac works great in fceumm...
