### ISSUE TITLE
Error: Source array was not long enough.

### ISSUE THREAD

**Issue by baconcow** [ClusterM/hakchi2#18]
Received the following error when attempting to adding a ROM (Yoshi) to Hackchi2 (2.10 release): _Error: Source array was not long enough. Check srcIndex and length, and the array's lower bounds._

![hackchi2_10_source_array](https://cloud.githubusercontent.com/assets/11164879/22123415/e61bb6ce-de61-11e6-9cc2-f88b14fd047b.jpg)

Attempted with multiple versions (No-Intro and GoodSet). Not sure if this is an issue with the ROM, application, or both. This error occurs even when there are no other games added. It occurs when added with other games or added separately.

**Comment by ClusterM** [comment]
I know this ROM, actually it's incorrect because it actual length < length in header. You can add some garbage it end of ROM.
Anyway, I'll ignore this error in next version.
