### ISSUE TITLE
3rd Party Wii Classic Controllers - Possible Fix

### ISSUE THREAD

**Issue by jonholifield** [ClusterM/hakchi2#180]
Many third-party controllers do not work with the NES Classic but work with the Wii Virtual Console

I believe that commenting out the check in clovercon.c will enable these controllers
in clovercon.c these lines can be commented out

332  if (con_info_data[5] != 1) {
333		ERR("unsupported controller id %i", (int)con_info_data[5]);
334		ret = -EIO;
335		goto err;
336   }

There is a possibility that the following check will need to commented out as well and the default case moved up.

603 switch(id->driver_data) {
604 case CLASSIC_ID:
605         DBG("probing classic controller");
606         break;
607 default:
608	        ERR("unknown id: %lu\n", id->driver_data);
609   	return -EINVAL;

to

604	switch (id->driver_data) {
605	case CLASSIC_ID:
606	default:
607		DBG("probing classic controller");
608		break;
609	//default:
610	//	ERR("unknown id: %lu\n", id->driver_data);
611	//	return -EINVAL;
612	}

I do not have the environment set up to rebuild the clovercon.ko file but would be happy to test my theory if it could be build for me. 

Thanks,

**Comment by BagginsKQ** [comment]
Which third parties don't work?

What about the premium Hori branded controllers?

**Comment by jonholifield** [comment]
I have two no-name Wii Classic Controllers that work with the Wii but not the NES classic. I'm fairly certain that it's the same issue that caused the recall of the original version of the EMiO Edge gamepad and Joystick. So, it's not an issue that there are not controllers out there that work, the ones that do cost $25-$30 and the ones that do not cost $5-$10 a piece, (Or free if you already had them for the Wii)
      From the code, it looks like the NES classic sends a command via I2C and expects a 1, if it doesn't get it, it doesn't even try to connect. My guess is the Wii and Wii U controllers never checked the bit, so third party controllers didn't know what the correct "passcode" was as it was not a requirement for working before the NES classic.

**Comment by ClusterM** [comment]
This code just checks that plugged in device is classic controller. Seems like it will not resolve problem.
I'll do some tests with https://github.com/ClusterM/nes2wii soon.

**Comment by archonis83** [comment]
I too got cheep controllers. I didn't know they wouldn't work considering they work on the Wii.

**Comment by jonholifield** [comment]
I still feel like the lines 332 - 336 will fix the issue. It's in the setup routine and keeps the NES from talking to the controller if it feels that it's an unsupported controller based on the identify information the controller provides. As these are copies of the correct controller, I feel that they would work by tricking the NES into accepting them as appropriate controllers. 
      I'll try to set up a cross compiler in Linux to see if I can recompile the clovercon.ko driver.

**Comment by archonis83** [comment]
Any testing?

**Comment by archonis83** [comment]
I don't think we are getting any traction on this.

**Comment by ClusterM** [comment]
Have not tested yet, I was busy. Will test soon.

**Comment by ClusterM** [comment]
Please try this clovercon driver mod: http://clusterrr.com/temp/clovercon2.hmod
If it will not work try this: http://clusterrr.com/temp/clovercon3.hmod

**Comment by jonholifield** [comment]
Sadly, neither 2 or 3 fixed the 3rd party controller issue. 

ClusterM,
     Thank you for taking the time to compile those.

**Comment by ClusterM** [comment]
It's weird. I can't find any protection code. I need to find some non-original controller for testing.

**Comment by jonholifield** [comment]
I was doing a bit of reading on this lovely website
http://wiibrew.org/wiki/Wiimote/Extension_Controllers
and comparing it to what the clovercon driver is doing in the clovercon_setup on line 300.

First it writes 55 to address 0xf0
then it writes 00 to address 0xfb
This is supposed to disable the encryption and send data unencripted, so that's good

Then the clovercon driver writes DATA_FORMAT (which is 3) to address 0xfe, which is part of the 6 byte controller identification block that is read at line 318 of the code. 

Two possibilities come to mind,
First, the cheap 3rd party controllers do not have read/write capabilities there, so the controller ignores the write to 0xfe and reports back whatever it originally had in that memory location. If this is the case, commenting out the error check found in in lines 327 through 330 ("failed to set data format") may allow the controller to be read by the NES.

Or Secondly, the NES is using the DATA_FORMAT variable to set the format to one not used by the Wii. If this is the case, the 3rd party controllers may not have that format in it's programming and all of the data being sent to the NES is in an incorrect format. If this is the case, there may not be a way to fix the 3rd party controllers.

Of course, I could just be wrong all together.

**Comment by ClusterM** [comment]
You are right. Seems like data format is the cause of the problem. I'll try to change data format to 1 and change polling function to parse this format. I'll share mod soon (today, I think).

**Comment by ClusterM** [comment]
Also it's possible that 3rd party controllers can't pass noice check. NESC reading 21 bytes instead of 8. All additional bytes must be zeros to pass check.

**Comment by ClusterM** [comment]
Please test this mods:
1) Data format #1:
http://clusterrr.com/temp/clovercon_data-format-1.hmod
2) Data format auto detection:
http://clusterrr.com/temp/clovercon_data-format-auto.hmod
3) Data format auto detection + alternative noise detection:
http://clusterrr.com/temp/clovercon_data-format-auto_alt-denoise.hmod
4) Data format auto detection + disabled noise detection:
http://clusterrr.com/temp/clovercon_data-format-auto_no-denoise.hmod

**Comment by jonholifield** [comment]
ClusterM, 
My hat's off to you sir, here are the results of my tests:

1.	Data format 1
3rd party Wii Classic – Not working
Nintendo NES Controller – Works 
NES 3rd Party controller (EMiO Gamepad Edge V2)  – Previously works under standard but now always goes left

2.	Data Format Auto
3rd party Wii Classic – Not working
Nintendo NES Controller – Works 
NES 3rd Party controller (EMiO V2) – Works 

3.	Data Format Auto – alt denoise
3rd party Wii Classic – Works 
Nintendo NES Controller – Works 
NES 3rd Party controller (EMiO V2) – Works 

4.	Data Format Auto – no-denoise
3rd party Wii Classic – Works
Nintendo NES Controller – Works 
NES 3rd Party controller (EMiO V2) – Works 

Both the 3rd and the 4th function great with all the controllers that I have. 
Thank you!

**Comment by jonholifield** [comment]
As a side note, synchronizing the game ROMS blows away the updated clovercon hmod on the NES classic and I had to re-install the user hmod afterwards.

**Comment by ClusterM** [comment]
Yes! Thank you!
You can replace clovercon.hmod into mods/hmods folder.
Or just wait for new release, it will be in a few days.

**Comment by DecanFrost** [comment]
so do we put these in the user_mod folder or hmod folder and rename the file ?

**Comment by ClusterM** [comment]
For permanent usage it's better to put it into hmods and rename.

**Comment by widgetfonda** [comment]
Tested all the four mods and it doesn't works for my cheap Aliexpress 3rd party Wii Classic controller :(

**Comment by jonholifield** [comment]
widgetfonda,
Were you able to test your controller with a Wii to confirm the controller is good? Some 3rd party controllers just arrive broken.

Here's a link to the 3rd party controller I tested
https://www.amazon.com/Classic-Controller-Nintendo-Video-Black/dp/B01NADZ8YP/ref=sr_1_4?ie=UTF8&qid=1489756940&sr=8-4

I have two other 3rd party wii classic controllers without the little handles, but they are back home (I'm traveling for work) and it will be mid-april before I can test them.

**Comment by sergiodmn** [comment]
I will test my 2 controllers later today and I will come back with the result, mine are: https://www.amazon.com/gp/product/B01LWJ2E3P/

**Comment by DecanFrost** [comment]
Tested Option #3 and my 3rd Party (cheap) Wii Classic Pro controller works 100%

**Comment by SunlightOnSnow** [comment]
so how do i test these. do i just ut the file into the hmod folder and rename it and delete the old one? i have 2 no name controllers i need to test

**Comment by SunlightOnSnow** [comment]
so option 3 works, sort of. i can now navigate menus but when i start a game it stops working. and now i cant navigate the retroarch menu at all with any controller. any help?

**Comment by ClusterM** [comment]
SunlightOnSnow, have you tried mod # 4?

**Comment by jonholifield** [comment]
Sergiodmn,
    I'm surprised to hear that your controllers did not work, from the amazon page they have the same JRH inspection sticker that mine had. When you synchronized to the NES Mini, did you have any Controller Hacks checked in the Settings menu of hakchi2? I think you would need at least one checked for the program to install the new clovercon driver. 

How I tested mine,
put all the versions into the user hmods folder.
Opened hakchi2
selected Modules, Install extra modules
Checked just one of the clovercon drivers
Clicked OK and followed instructions
Tested the controller
Repeated with all 4 modules

But with my method, each time you synchronize you would need to go back and re-install the custom clovercon module.

**Comment by sergiodmn** [comment]
Hi jonholifield,

I tried as you mentioned and it didn't work. I had selected "Use botton combination to reset" (select+down) in the Controller Hacks section.

**Comment by ClusterM** [comment]
sergiodmn, try version 2.14, it will be released soon.

**Comment by eblackadder** [comment]
Thanks a lot for this wonderful solution. I have a 3rd party Wii classic controller and with the 3rd mod(the only one i tried) it works perfectly!

**Comment by widgetfonda** [comment]
Hi ClusterM !

I've tested v2.14 with my cheap Aliexpress 3rd party Wii Classic controller and sadly it doesn't work. The controller works fine using dolphin and connected to my official wiimote (haven't tried on a real Wii).

I've tested with the for modules with no luck too...
I don't understand why it doesn't work :(

**Comment by sergiodmn** [comment]
Well I've tried with version 2.14 at it doesn't work either, so I think that I'm going to return the controllers to amazon.

Really appreciate all your help.

**Comment by ClusterM** [comment]
widgetfonda, email me to clusterrr@clusterrr if you want to help with translation.
sergiodmn, it's sad :( Can I buy this controller from you? I need it for testing.

**Comment by sergiodmn** [comment]
Yes, if you want them, it is a 2 pack and cost to me EUR 15,99, just let me know the details.

**Comment by DecanFrost** [comment]
I use these cheap 3rd party ones with option #3

http://www.ebay.com/itm/272567227746


Works great

**Comment by str8rippinpro** [comment]
Hey, great work 4/5 of my 3rd party controllers now work. YAY!! Champion!!

**Comment by str8rippinpro** [comment]
Cluster please PM me your address I will send you the non working controller for free cheers!

**Comment by goombah111** [comment]
I posted on the reddit but im also posting here.
i have 2 no brand controllers from ebay. cheapest ones i could find. 
tried everything on this page and more. nothing works.

go ahead and contact me if you want them.

**Comment by ClusterM** [comment]
str8rippinpro, it's not required now. You can help me now without it.

If you have controller that still not working on v3.14 please do the following steps:

1. Install mod with stecial debug version of controller driver (drag&drop on hakchi2 window): http://clusterrr.com/temp/clovercon_debug.hmod
2. Turn NES Mini off.
3. Connect this controller to NES Mini (only one controller, any port).
4. Turn NES Mini on. Wait until it booted up.
5. Close hakchi2 if it's opened.
6. Download: http://clusterrr.com/temp/clovercon_getlog.zip and unpack it somewhere.
7. Run "getlog.bat" from this archive. It should create "clovercon_debug.txt" file.
8. Send this "clovercon_debug.txt" to me: clusterrr@clusterrr.com

**Comment by ClusterM** [comment]
Also you can try this version: http://clusterrr.com/temp/clovercon_debug2.hmod
But seems like it's hardware problem :(

**Comment by amberwillow** [comment]
I've gotten 2 nameless wii classic controllers that do seem to respond somewhat, but the left analog stick is constantly pushing left unless i push the other way, and none of the other buttons seem to react as they should. I've tried a couple of the hmod files on here, but the result is always the same. Is the described behavior the problem that the hmod's are trying to fix?

**Comment by trenhel27** [comment]
Hey DeaconFrost

Is there another way to access that #3 you linked to?  I'd like to try it but it's a dead link...

**Comment by DecanFrost** [comment]
What's your email address I will send it to you

**Comment by trenhel27** [comment]
trenhel27@yahoo.com

Thanks in advance!

**Comment by str8rippinpro** [comment]
I tried all those clover shells and none would fire up the cheap ali express controllers.
Never mind still great work

**Comment by ClusterM** [comment]
Finally I managed this ultra shitty chinese controller to work on NES Mini. It requires to pullup SCL and SDA lines to VCC using 2.2K resistors and patch driver a bit.

**Comment by trenhel27** [comment]
DecanFrost hey I never got that email...

I have 2 cheap controllers I'd like to try that for, I went and bought a Nintendo lisence one but I'd like to get these to work so I can return it lol.  I know there's no guarantee that it'll work but please send that if you could.

**Comment by DecanFrost** [comment]
Ohh crap sorry. I will send it in a bit. As soon as I get home
.

What's the email address again

________________________________

**Comment by trenhel27** [comment]
trenhel27@yahoo.com

**Comment by DecanFrost** [comment]
Alt file is #3 i beleive

________________________________

**Comment by trenhel27** [comment]
Do you mean #3 on that list of 4 by cluster?

Do you know how to install it then?  Maybe I'm doing it wrong?

**Comment by DecanFrost** [comment]
Correct..

Copy them to the user_mod folder like the snes and genesis cores. Then go to install moduals in hakchi2 and select one of them to install then reboot it plug a controller in and try it


________________________________

**Comment by trenhel27** [comment]
Well, no such luck :/

**Comment by trenhel27** [comment]
And now clusters links for creating a debug log to send his way are 404ing all over the place...Guess I'll just bite the $12 and whatever else and just get another Nintendo lisenced controller

**Comment by DecanFrost** [comment]
Where do you live


________________________________

**Comment by trenhel27** [comment]
In Illinois, why?

**Comment by ClusterM** [comment]
What the point to send me more logs?

**Comment by trenhel27** [comment]
Pipe dream?  Lol it's fine I just got another controller the problem is moot now.  Thanks for all you do cluster

**Comment by dami08** [comment]
I tried the HDE-K80 model without any luck :( 
[https://www.amazon.ca/HDE-2-Pack-Classic-Controller-Nintendo/dp/B00MNSLIAS/ref=sr_1_3?ie=UTF8&qid=1499538971&sr=8-3&keywords=hde+classic+controller](url)
Anybody else try this controller and have any better luck with it ?

**Comment by ClusterM** [comment]
@dami08 can you show debug log? You can read it from /dev/clovercon_debug pseudo-file.

**Comment by dami08** [comment]
Thanks for the reply.


I took a look but do not see this file.  Do I need to use a specific hmod ?  Right now I am using the one from https://github.com/ClusterM/hakchi2/tree/master/mods/hmods


I dumped it in the hmods folder.  I am using 2.17c.  Am I missing something ?


[cid:6f3c4ef7-a5e8-4c35-971f-7c52c90a222a]



________________________________

**Comment by dami08** [comment]
It appears 2.17c did not give me the clovercon_debug file but v2.15 does.

________________________________

**Comment by dami08** [comment]
My apologies, here is a file  with some actual logs in it


[clovercon_debug.txt](https://github.com/ClusterM/hakchi2/files/1140036/clovercon_debug.txt)
It appears 2.17c did not give me the clovercon_debug file but v2.15 does.

Basically, the contents of the debug file are as follows : 

Clovercon: initializing controller 0 on bus 1, gpio 195
Clovercon info: added device for controller 1
Clovercon: initializing controller 1 on bus 2, gpio 194
Clovercon: probing classic controller
Clovercon info: probed controller 1
Clovercon: Clovercon setup
Clovercon: write failed with error -70
Clovercon: prepare_read failed
Clovercon error: error reading controller info
Clovercon error: controller setup failed with error 70
Clovercon info: opened controller 1, controller in error state after failed setup
________________________________

**Comment by thatshhhype** [comment]
Hi! 

I just bought 2 third party wii classic controllers which doesnt work. I wanted to follow your links to make them work, but it seems like the links are down (404 not found) :( could you please post a new link so i can make my new controllers work? :) thank you!

**Comment by ClusterM** [comment]
@thatshhhype please read the whole thread. You don't need those links anymore.

**Comment by ClusterM** [comment]
@dami08 error -70 is hardware problem :(

**Comment by Jays87** [comment]
Hey @ClusterM , so is there a fix for version 2.17c?
I am looking to buy the following controllers, but I will save my money if there is no fix. Thanks!
https://www.amazon.ca/gp/product/B06XY7Y8R6/ref=ox_sc_act_title_1?smid=A1RQAO46VQOYLE&psc=1

**Comment by corbincc1** [comment]
I have one of these  Jays87 and also have 2.17c ... it does not work... I'm willing to try the soldering trick but am curious as to which vcc to pullup to or do I solder to both as my board has 2 vcc points.

**Comment by corbincc1** [comment]
[URL=http://s1378.photobucket.com/user/corro101/media/20170818_200838_zpsftxf7oon.jpg.html][IMG]http://i1378.photobucket.com/albums/ah91/corro101/20170818_200838_zpsftxf7oon.jpg[/IMG][/URL]

Pic of the board in the controller

**Comment by ClusterM** [comment]
@Jays87 it's possible to connect any controller but maybe it will require hardwire modification with two resistors.

**Comment by ClusterM** [comment]
@corbincc1 

![image](https://user-images.githubusercontent.com/4236181/29494563-a8619226-85b5-11e7-8d30-9a6591d77108.png)

**Comment by corbincc1** [comment]
Just curious if i need the ground too... i went ahead last night and just
tried did the 2 resistors to the first vdd .. and it worked perfectly.
I appreciate the reply, your work on this is really awesome.

C

**Comment by corbincc1** [comment]
Nevermind.. lol put my glasses on and seen you didn't use the ground at all
lol sorry

**Comment by Jays87** [comment]
Thanks @ClusterM & @corbincc1

Do either of you have a picture of a finish solder controller? @corbincc1 can you show me what you did?
Cheers!

**Comment by Jays87** [comment]
I was actually able to grab a couple of Nintendo branded controllers last night off Kijiji, thanks again for all your help.
Cheers!

**Comment by Jays87** [comment]
Hey @ClusterM , now that I have nintendo branded controllers, do you know how to properly map over the buttons for N64 games... I put on Goldeneye but the controls are all off. Thanks man!

**Comment by ClusterM** [comment]
@Jays87 it depends on emulator settings only, it's not related to hackhi2.

**Comment by perroboc** [comment]
Yep, the hardware mode (2 2.2k resistors) works as intended! thank you @ClusterM!

**Comment by ameisenmann** [comment]
Hardware Fix worked for me, thanks! But I used normal resistors because soldering SMD components is really a pain in the ass. Since I spent one day doing a RGB mod for my french N64 I promised to myself to never solder SMDs again :D.
Btw. I think the quality of the "shitty" controller is ok for 10 €. :)

**Comment by janimaljr** [comment]
Does the resistors hardware fix also require to install clovercon.hmod?

**Comment by janimaljr** [comment]
NVM tested it myself, only need to do hardware resistor mod for it to work. Thanks @ClusterM for that.

Anybody mind sharing the science behind this hardware mod, just curious. Thanks!

**Comment by janitoalevic** [comment]
Hello, I bought a Zettaguard classic controller, it works on SNES Mini but not NES Mini, I opened the controller and I can't find the SDA, SCL and VDD, I suppose which are, but they don't have names

I'm not sure which are and I don't want to screw up the controller https://i.imgur.com/JfRZxBr.jpg

https://www.amazon.com/Zettaguard-Classic-Controller-Nintendo-ZG-WW1/dp/B00SQQ8ICC

**Comment by Darkwing73** [comment]
Hi can anyone send me the hmods 3 and 4:
Data format auto detection + alternative noise detection:
Data format auto detection + disabled noise detection:
The links are down and since it worked for some people, maybe it will work for me. 
My email is darkwing73m@gmail.com 
It would be greatly appreciated. @jonholifield

**Comment by ghost** [comment]
@ClusterM  I think I have two controllers similar to the one in the picture you had posted. After reading through this thread I am still unsure as to whether the softmod on my console, or a had mod on the controllers would be a better solution, though i would prefer a softmod on my console. Additionally in your original picture it appeared that you had only wired the points together and not used resistors, but this might be wrong. 

This is what I have: 
![img_20180712_171214](https://user-images.githubusercontent.com/41173111/42666610-1267d324-85fb-11e8-8172-3c50d04c5887.jpg)

and this is what I think I need to do from the thread:


![2](https://user-images.githubusercontent.com/41173111/42666666-5ce63eae-85fb-11e8-900f-0e42cfd8fa14.jpg)

**Comment by edgaras1002** [comment]
help your links dont work

**Comment by Yosh1002** [comment]
The Link Works But The mod Doesnt  I Used on Snes mini didint work
...

**Comment by ClusterM** [comment]
Why it's still open? It was fixed years ago.

**Comment by Yosh1002** [comment]
So i went to your link and it says Not Found, Error 404

**Comment by Yosh1002** [comment]
so :(

**Comment by ClusterM** [comment]
edgaras1002, why you need it?

**Comment by Darkwing73** [comment]
Hi, what do you need?

**Comment by Yosh1002** [comment]
Cuz my controller has a input lag a minute i wait and it works or not.
If im making no sence sorry.

**Comment by Yosh1002** [comment]
Hello?

**Comment by Yosh1002** [comment]
Hello ClusterM I Need The Download Link

**Comment by Yosh1002** [comment]
I Need your Help

**Comment by Yosh1002** [comment]
ClusterM
Hello, Sir?
