### ISSUE TITLE
cant play Other roms after newest update 2.13e

### ISSUE THREAD

**Issue by DecanFrost** [ClusterM/hakchi2#182]
I flashed all NES games and a few random Genesis, GBC and SNES games and was able to play all of them no problem, until I updated and used the newest 2.13e

I reflashed with 2.13e since I was changing the folder layout and when I flashed them over non of the NON-NES games will load, the screen goes black and then back to game selection menu again.

anyone else have this problem.  I reflashed the retroarch addon also and still no luck

**Comment by masterbates50** [comment]
Exact same thing is happening to me. SNES games no longer working. Screen goes black and goes back to the menu.

**Comment by DecanFrost** [comment]
i tried to replicate it on my other mini, by removing retroarch addon and putting the new release on with out the cores and the games still work on it.. im restoreing back to stock and then going to redo the working one with the new setup i did on the other one that no longer is working

**Comment by markusjunior** [comment]
Same here, this is how I solved it. first flash back the original dump kernel. Add the retroarch mod and do not forget to add the cores as you like as well (see the latest release from yesterday). flash the custom kernel. afterwards for testing, just add one snes game and sync. if this works, go for it with your whole list.

**Comment by Wyvern94** [comment]
Guys just Make sure you have The right path Set in the hakchi game arguments, as you now have 7z in the end.

**Comment by DecanFrost** [comment]
Markusjunior, your correct last night i had to reload to stock and then redo and re add the cores and the snes and others work now

**Comment by masterbates50** [comment]
Ive also deleted a few games and re-added them and noticed they now had the 7z at the end. I will try those tonight to see if they work and if that was my issue, will just delete my library and add them all again. Thanks

**Comment by ClusterM** [comment]
Reinstall latest RetroArch mod.
