### ISSUE TITLE
Wishful Thinking... Sharp X1 Support...

### ISSUE THREAD

**Issue by BagginsKQ** [ClusterM/hakchi2#183]
I don't know how much interest there is, but I think it would be awesome if someone got some kind of Sharp X1 core working, for the Nintendo/Hudson soft software... Like Super Mario Bros. Special.

Can't seem to find any retroarch cores for any of the Japanese computers either (PC-88, Sharp X68000, FM-Towns)...

https://www.mariowiki.com/Super_Mario_Bros._Special

**Comment by baconcow** [comment]
You should add this to the appropriate repository (retroarch).

**Comment by BagginsKQ** [comment]
Well that's fascinating to hear... Hopefully we can find it! Do you have link to the retroarch repository?

**Comment by BagginsKQ** [comment]
https://forums.launchbox-app.com/topic/32988-emulators-for-systems/

According to this it might be folded into mame... Anyone want to test?

**Comment by baconcow** [comment]
Where I was reading, it was part of the mess core. It was labelled as libreto_x1/mess_x1. I cannot seem to find any further information. If you post this link and feature request on the repository for the retroarch, people watching that issue forum (i.e. pcm720 or someone else) may have more information or perhaps already tested it.

**Comment by ClusterM** [comment]
Sorry but RetroArch repo is in another castle.
