### ISSUE TITLE
Analog issue on N64 roms caused by a nes classic mini config file?

### ISSUE THREAD

**Issue by ajmi982** [ClusterM/hakchi2#185]
https://github.com/ClusterM/retroarch-clover/issues/29

All the info u need about this issue is here

**Comment by ClusterM** [comment]
Seems like clovercon driver problem. I will check it.

**Comment by ClusterM** [comment]
Fixed. You can download new clovercon mod now: https://github.com/ClusterM/hakchi2/tree/master/mods/hmods
and replace mods/hmods/clovercon.hmod if you don't want to wait for next version :)
