### ISSUE TITLE
Question for cluster

### ISSUE THREAD

**Issue by warlockv2** [ClusterM/hakchi2#186]
So now that shell has been accessed.  and all the kernel work, do you see in the unknown future usb support for hdd, flash sticks, or maybe sd usb readers etc? basically, can the nesc read from usb, with some changes to the code.  is that a possibility.  

Also your a genius, great work so far.

**Comment by ClusterM** [comment]
It's already done by honeylab. But you can't do it without soldering.

**Comment by S-R-3** [comment]
How about using a Leef Bridge USB 3.0 32GB Dual USB Flash Drive, the way it looks is it would still power the mini but allow storage as well. 

https://www.amazon.com/gp/offer-listing/B00GWP9EYK/ref=dp_olp_new_mbc?ie=UTF8&condition=new

**Comment by ClusterM** [comment]
You need to solder USB-ID pin inside NES Mini, it can't use USB Host without it.

**Comment by DecanFrost** [comment]
is there info on how to do the modification, I wouldnt mind trying it out and soldering the USB in

**Comment by ClusterM** [comment]
You can find it on honeylab's blog: http://honeylab.hatenablog.jp/
