### ISSUE TITLE
Info Request: Official Limitation of 30mb?

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#189]
Can we get an official response on what is limited by 30mb?  Is it the navigation folders?  The game size?  Does it include or exclude compression?  Does it include or exclude subfolders?  Or is it perhaps just how the data is transmitted over in packets of 30 mb?

I realize this is a bug report form, but I am hoping to get a clarified response from Cluster or someone who has seen the code to explain the limitation... seems to be a lot of confusion on this one.

Thanks.

**Comment by elierodrigue** [comment]
Everything is sent in batch to the NES classic. Batch size needs to be 30mb or lower. And there's no way to "merge" two batches.

Ex : Software will take as much roms as possible to create a 30mB file.

So if a compressed rom is larger than 30mB then it cant be sent. For now.

**Comment by bfluryx1234** [comment]
So does the system automatically size the 30mb batches or is it determined by the folder?  If it does it automatically it would mean there isn't really a 30mb limitation other than just a single game can't exceed that number.

**Comment by elierodrigue** [comment]
Software automatically size them. 
Limitation is just because of the way the app send data to the nes mini.
Exactly, only limitation this cause is a single game cant be more than 30mb

**Comment by ClusterM** [comment]
It's not actual for 2.14.
