### ISSUE TITLE
ROM not found message

### ISSUE THREAD

**Issue by ghoost82** [ClusterM/hakchi2#19]
Hi,

there is a bug in the Add more games function. If you try to add a game with an unsupported mapper a dialog will pop up and ask if you want to add it anyway. If you click No there will be remain a empty directory for this game in the game directory.
This empty folder will cause a ROM not found error message the next time hakchi2 is started.

Regards
-jan

**Comment by GoodbyeWorld** [comment]
Aha!! That's what's causing my issue with "file not found".  It was actually a "ROM not found" message, and I was experiencing it after adding unsupported mapper ROMs.

**Comment by ClusterM** [comment]
Fixed, thank you!
