### ISSUE TITLE
Glitchy games won't load with RetroArch

### ISSUE THREAD

**Issue by calmLIKEaBOB-OMB** [ClusterM/hakchi2#190]
There's games that are supposedly compatible with the NES Classic's emulator, but really aren't.  Some games will load but are glitch, like: Air Fortress, Captain America, Gun Nac, Kid Klown, and the StarTropics Music Fix hack.  Some other games just crash, like: Bio Force Ape and Fire Hawk.  There's also some FDS games that won't switch sides, like Otocky and Zelda no Densetsu.  So I was wondering if there was a way to just have a check box for games you want to load with Retroarch instead of the NES's emulator.

Respectfully,
Matthew

**Comment by Bartvz** [comment]
Install the RetroArch module and append the following switches to the "Command line arguments" box for the incompatible roms: 
> --retroarch --core *coreofchoice*

**Comment by bfluryx1234** [comment]
Also this isn't the bug report for RetroArch, that is a seperate project.
