### ISSUE TITLE
Remap Buttons on Wii Classic (or other) Controllers?

### ISSUE THREAD

**Issue by NotATreoFan** [ClusterM/hakchi2#191]
Is there a way, or could there be in a future release, to change the button mapping?

I find it much easier to play NES games with Y and B on a Classic Controller or SNES controller, instead of B and A. Is this something that may be possible?

**Comment by hpd4cl** [comment]
I was going to suggest adding the other buttons on the classic controller to the reset combination choices, but realizes that the home button works.

**Comment by missionfloyd** [comment]
X and A works the same as Y and B would.

**Comment by MelonGx** [comment]
If disabling X/Y Autofire, then X works as B (except for launching Select+B Autofire)

**Comment by NotATreoFan** [comment]
@missionfloyd I'm using a mix of NES, FDS, SNES, and GEN games, some of them do not work in Retroarch, so I can't use the command line switch to run all games in it.

@MelonGx So if I turn off the Auto Fire option, then I could use A for A and X for B, without having to modify any other settings?
