### ISSUE TITLE
[NEW AND IMPROVED] Feature Request: Delete uninstalled games on boot

### ISSUE THREAD

**Issue by bfluryx1234** [ClusterM/hakchi2#192]
Since we are managing ROMs within Hakchi, I would like to propose the tool also address cleaning up save states and orphan data it creates as well.  Hopefully, this can be a relatively straight forward process assuming we can script commands during the boot process.

Basically, I would suggest that we whitelist any games that are installed, visible in Hakchi (but hidden), or base games.  However, everything else is removed.  So Hakchi doesn't actually need to keep track of what is being removed from the system since it attacks the problem from a different angle.  This gives users a straight forward method to decide which save files they want to keep when they remove a ROM (either they hide the game and keep it or they delete the game and it is removed!).

My proposal is that for every title not whitelisted the system would remove all the save states, save images, sram information (which, VERY IMPORTANTLY, I don't believe we can do at all right now without a reset), and in the perfect world any misc game specific configuration files (such as RetroArch).

The script, ideally, would only need to execute once on a boot and then could self destruct and not run again until flashed.  However, it would be fine if it had to run each time you boot the system.  It also would be fine, although not perfect, if it had to run when you clicked on a folder, instead of during the boot process.

It is important that we can turn this functionality on/off as well.  I, along with others, have a test image that we flash with fewer games as it is much quicker than flashing the entire system.  I wouldn't want it to delete all the saves when flashing that image.

**Comment by ClusterM** [comment]
Just later.
