### ISSUE TITLE
REQUEST: 3rd Party / Cheap Controller Support

### ISSUE THREAD

**Issue by str8rippinpro** [ClusterM/hakchi2#193]
Hey there, bought some Classic Wii Controllers for $5US assuming they would work but found of the hard way that only genuine controller are supported
Have donated & happy to donate more money or controllers to help support this.
heres a link to the cheap controllers http://www.ebay.com.au/itm/272320107790?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT
Thanks Alot Champions

**Comment by Bartvz** [comment]
Sames as this: [https://github.com/ClusterM/hakchi2/issues/180](https://github.com/ClusterM/hakchi2/issues/180)

**Comment by archonis83** [comment]
I made the same mistake 😣
