### ISSUE TITLE
VCRUNTIME140.dll While installing driver

### ISSUE THREAD

**Issue by mistercapitale** [ClusterM/hakchi2#195]
I have Win10 and I get an error when I try and install the driver to start the process of installing it. It first tells me that its missing this driver, vcruntime140.dll. I found it and installed it. Then I also get a different error. Anyone else have this issue?

**Comment by graykimbrough** [comment]
I had this error and needed to install Visual C++ to get this .dll. I got that from [here](https://www.microsoft.com/en-us/download/details.aspx?id=53587)).

Are you saying that once you installed Visual C++, you got another (different) error message?

**Comment by ClusterM** [comment]
Fixed.
