### ISSUE TITLE
Synchronize successful, but no extra games

### ISSUE THREAD

**Issue by nilsschmitt** [ClusterM/hakchi2#20]
2.10 seems to be working nice and I got a "everything worked well" message but there are no extra games on my nes classic. nothing changed. I tried it three times and nothing changed.

I choosed 30 extra games, I dumped the kernel, no error message.

what can I do?

**Comment by micklen** [comment]
Same here... 

Seems that the LED never goes out as well... 

Anyone got a clue ?

**Comment by nilsschmitt** [comment]
in my case the led goes out

**Comment by nilsschmitt** [comment]
it worked pretty well the first time, but not with the second nes classic .

**Comment by ClusterM** [comment]
Seems like you has not flashed custom kernel. Please read FAQ - question about second NES Mini.

**Comment by GoodbyeWorld** [comment]
Any chance you were flashing a second NES Classic from the same Hackchi folder that was previously used to flash a different NES Classic?

**Comment by nilsschmitt** [comment]
Thank you! It was my fault. It worked fine with a seperate, new folder.
