### ISSUE TITLE
Some games not in order any longer?

### ISSUE THREAD

**Issue by tjm694** [ClusterM/hakchi2#200]
I have folders split by first letter only.  Some games are not in order.  For example:

Super Mairo USA, Super Sprint, Styx, then a bunch of games, Super Mario Bros 1.  Super Mario 2 FDS, then a few more games, then Super Mario 2 and Super Mario 3.

Also had a whole folder no appear with games in it.  Have around 284 meg of games.

Any insight?

**Comment by seanrox** [comment]
When at the NES Classic Edition menu, if you press the SELECT button on your controller, you can sort the games by title, release date, publisher, etc.  Have you tried using this feature yet to see if it solves your issue?

**Comment by tjm694** [comment]
They are always sorted by letter.  It's just 2 or 3 folders that is doing this.

**Comment by seanrox** [comment]
@tjm694 hmm... another thing to check would be the settings in hakchi2. There are "pages/folders structure" settings you might want to check as well to see if any of those settings change what's going on for you.

**Comment by tjm694** [comment]
fixed itself after 4 reflashes
