### ISSUE TITLE
Unable to save any SNES games

### ISSUE THREAD

**Issue by maniac2025** [ClusterM/hakchi2#201]
I am using the latest 2.13e.  I can't get any SNES games to ever offer to save a suspend point.  None of my games have extra characters in them like periods and what not as mentioned in a previous post about this issue.  I'v removed all games, put my original kernal back into the machine and tried again from scratch.  It's still a no go.  Its the same for Sega games.  If anyone has any idea's please suggest them.  Otherwise I guess i'm reporting a possible bug.

**Comment by Bartvz** [comment]
Please close this issue as it is not a hakchi "bug". Please post it at the retroarch-clover repo.

**Comment by maniac2025** [comment]
moving issue to retroarch-clover repo issues page.
