### ISSUE TITLE
Is there Hackchi for Mac IOS?

### ISSUE THREAD

**Issue by BillyDanzini500** [ClusterM/hakchi2#202]
I can not find Hackchi for Mac. Will they be making Hackchi for Mac in the future if there is not one?

**Comment by black-pudding** [comment]
+1, Hakchi doesn't work properly with Wine Devel or Wineskin. I had to use bootcamp.

**Comment by BillyDanzini500** [comment]
@black-pudding What if you don't have an extra hard drive to partition? Then how do you get boot camp to work?

**Comment by black-pudding** [comment]
You don't need an extra hard drive if you still have enough space on your Mackintosh HD: https://support.apple.com/boot-camp

**Comment by black-pudding** [comment]
@BillyDanzini500 This is the same issue than #42 Mac-Based Hakchi2

**Comment by graykimbrough** [comment]
Not a complete answer to the question here, but I used this method to run hakchi on my mac:

https://toadle.me/2017/02/03/how-to-add-more-games-to-you-nes-mini-classic-using-hakchi2-and-a-mac.html

The only additional thing I had to do was download visual C++ to get a needed .dll. You can download that here by searching for "Microsoft Visual C++ 2015 Redistributable Update 3."

**Comment by azoreseuropa** [comment]
No, you can use it with wineskin. Just install framework net 3.5 SP1 and you are all set. I just run hakchi on my Mac now but haven't test it just yet.

**Comment by Hammid** [comment]
iOS ≠ macOS, but yeah! Wineskin or Parallels Desktop/VirtualBox do the trick.

**Comment by PhoenixWright** [comment]
@Hammid Do you have any advice on how to use Wineskin? I'm not getting the app to open, but I'm not very familiar with Wineskin either.

**Comment by spotanjo3** [comment]
I never had a problem with NES CLASSIC version of Hakchi2 2.14b until now.

What I do is that I compiled it with wineskin for your newer version to use both NES CLASSIC MINI and SNES CLASSIC MINI and I got this error message:

I click MS .NET 3.5 and click RUN

and message is: Do you wish to run winetricks? The following command will be executed: winetricks dotnet35 and I click RUN

and the message said Winetricks Commands Finished!! One second. Too suspicious. Something is wrong because it didnt show many lists before it is complete. 

So I go ahead and click hakchi2.20 and nothing is coming up. 

ERROR!

ERROR, tried to run command WSS-winetricks when the wrapper was already running.  Please make sure the wrapper is not running in order to do this.

HELP ?! Please investigation.

**Comment by spotanjo3** [comment]
@hammid,

Hi. Do you have an advice with those problems ?

**Comment by BillyDanzini500** [comment]
I use “parallels desktop” and “windows xp” now I can use hackchi on my Mac. Make sure to use the right “zadig” for your system to find your Nes/snes

**Comment by spotanjo3** [comment]
Meaning zadig ? No idea. I understand about parallels and windows.. We are talking about wineskin problem.

**Comment by BillyDanzini500** [comment]
I tried using wineskin and I couldn’t figure it out so I used parallels desktop and it was a lot easier for me. Zadig is a separate program that helps you find your drivers

**Comment by spotanjo3** [comment]
Yeah, I tried with Wineskin for NES hackchi2 and it works before they created NES and SNES for newer hackchi2. Now, a newer version of hackchi2 doesnt work with wineskin for both NES and SNES.. That's strange.

Oh, I thought Hackchi2.exe can be use in Mac with Parallels and Windows without using Zadig.  I am confused.

**Comment by BillyDanzini500** [comment]
You do not need zadig for hackchi2. You only need zadig to help find the drivers for Nes/snes if parallels can not find the drivers automatically. After your drivers are connected to your Nes/snes then hackci2 will recognize your Nes/snes is present

**Comment by spotanjo3** [comment]
Thank you. I google it and I got this zadig at: http://zadig.akeo.ie

Is that one ?

**Comment by BillyDanzini500** [comment]
Yes that is the newest version. Here are more version for different windows systems.. 
http://zadig.akeo.ie/downloads/

**Comment by spotanjo3** [comment]
Thank you, BillDanzini500!

**Comment by num8er** [comment]
I found it easy to do with Windows OS running using VirtualBox.
