### ISSUE TITLE
Feature Request: Go back in folder feature navigation with B button pressing.

### ISSUE THREAD

**Issue by bahsura** [ClusterM/hakchi2#203]
I love this software and the new folder feature is great. But I find it awkward to have to manually navigate to the back folder icon and select it with the A button every time I want to navigate back to the previous folder in my folder structure.  I was wondering if with a simple press of the B button I could do the same thing without having to scroll to and select the BACK folder icon. Maybe even have the B button press make the cursor automatically navigate and activate the BACK folder would be enough. Thanks.

**Comment by warlockv2** [comment]
thats a fantastic idea

**Comment by baconcow** [comment]
This would be great. But, wouldn't this require the actual NESCE application to be modified? Maybe it could be implemented like the reset hack?

**Comment by ClusterM** [comment]
Yep, It's impossible without modification of NES shell software :(
