### ISSUE TITLE
4 players

### ISSUE THREAD

**Issue by oghmios** [ClusterM/hakchi2#205]
It is possible, in near future, to play 4 players on a nes mini? It has only two ports, but it is possible to create a hub or anything and emulate 4 pads?

**Comment by baconcow** [comment]
[Something like this](https://www.amazon.com/Mayflash-NES-SNES-Controller-Adapter/dp/B00B2K0C8M/ref=sr_1_1?ie=UTF8&qid=1487798425&sr=8-1&keywords=wii+nes+snes+adapter) Mayflash adapter would allow 4 controllers (2 NES and 2 SNES) to be plugged in at once. The issue would be getting them to all work at once, in a 4-player game.

**Comment by ClusterM** [comment]
Clovercon driver supports up to 4 controllers. Seems like there are output for 4 controllers inside NES Mini but only 2 are connected. So maybe it's possible via soldering.
