### ISSUE TITLE
Some games not transferring

### ISSUE THREAD

**Issue by Timoneda** [ClusterM/hakchi2#206]
When loading huge amounts of games, seems like some of them go missing in the process.
I've spent several days trying things, there is what i found:

On version 2.12 was impossible to re-upload games without drastically changing the content.

Uploaded 400 roms. > deleted some, added other roms > After first upload, all attempts resulted in a collection of empty folders until I uploaded just a few roms + the original 30, an then, retried to massive upload. It went "well".  Almost all games went to the NES, but, some random files dissappeared (f.e. Donkey kong Country)

On Version 2.13e: Being below the limit of 300MB, I've seen the last 20 roms not appearing. retried, with same result. Deleted some roms,but still happening some issues, like missing games the final folders.

When selecting "Original games in root --> automatic in sub folder", I've got several times the original games in root and an empty folder called "More games"

In one of the loads, a folder gave me a black screen. The only solution was to re-upload all again.

It seems I must change the folder structure every time to evade getting empty folders.

Aaand this is how I spent all day. Any ideas?

**Comment by Timoneda** [comment]
Tried again. Missing the first 20 games from the last folder.

**Comment by ClusterM** [comment]
Will be fixed in next version.
