### ISSUE TITLE
2.13e makes the cover art blur

### ISSUE THREAD

**Issue by MelonGx** [ClusterM/hakchi2#207]
I have to use 2.11 to import all cover arts to make them clearer.
However 2.11 doesn't support non-NES box arts.

**Comment by ClusterM** [comment]
Hi. Can you make comparation screenshots? 2.13 keeps aspect ratio and using bilinear filter, maybe it's the problem.

**Comment by MelonGx** [comment]
Sorry for my late replying.
![clv-h-weomq-211](https://cloud.githubusercontent.com/assets/7697767/23916113/1dc07f08-0926-11e7-9150-45bb6d43d3cb.png)
DW3 (2.11)
![clv-h-weomq-213e](https://cloud.githubusercontent.com/assets/7697767/23916114/1e1af0c8-0926-11e7-90a4-46be98e3a907.png)
DW3 (2.13e)

**Comment by ClusterM** [comment]
I can't see the difference on my screens. Can you rebuild hakchi2 by yourself? You can try other resize methods.

**Comment by DecanFrost** [comment]
i do see the difference. I believe its the compression being used on the covers. its probably defaulted to smooth not sharp. it would have to be changed and recompiled
