### ISSUE TITLE
Help running arcade games

### ISSUE THREAD

**Issue by jtgillia** [ClusterM/hakchi2#209]
I'm full of gratitude for the work that has been done to make hakchi so user friendly!  My only issue now is with four arcade games- Pac and Pal, Pole Position, Rolling Thunder, and Moon Patrol.  I've tried three different cores (Mame2003, Mame2000, and FBA), but none of those work.  Is there a core available that can run any of these games?

**Comment by Bartvz** [comment]
This is not the right repo to ask this question this one is: https://github.com/ClusterM/retroarch-clover
Please ask over there and close this issue.

**Comment by jtgillia** [comment]
Ok, thanks.
