### ISSUE TITLE
running games snes 16bit?

### ISSUE THREAD

**Issue by Alex960** [ClusterM/hakchi2#21]
Hi!  Is it possible to run Roms of SNES 16bit games on the NES mini?

**Comment by soulctcher** [comment]
No.  They are two very different systems.

**Comment by NaikiTurincondeliphone** [comment]
Maybe you can make a custom firmware?

**Comment by sukoshi1507** [comment]
the answer is yes, technically it is feasible.
but we lack a few buttons on the pad.
doom has already be ported on the famicom mini.
is it the purpose of ClusterM github? i don't think so.

**Comment by Alex960** [comment]
nes is technically capable of more. You need to create a patch program that would recognize Roms SNES. I hope ClusterM will help us in this?)

**Comment by GoodbyeWorld** [comment]
@Alex960 - The NES hardware (and emulators) are in no way capable of playing a SNES ROM.  You could build your own emulator and load it onto the NES Classic.

**Comment by Alex960** [comment]
@GoodbyeWorld   -  and maybe they worked together? He wanted to play NES, then, including the SNES emulator...
