### ISSUE TITLE
Driver for Windows Vista? 

### ISSUE THREAD

**Issue by Shredasaurus34** [ClusterM/hakchi2#210]
I'm running windows vista 64 bit. I can't seem to get the driver to install for the Classic Nes. Should it work with Vista?

**Comment by baconcow** [comment]
Looking at the readme for the USB driver source, it states "Supports all Windows platform from Windows XP to Windows 10", so one would think it would work on WIndows Vista (which came out between those other versions of Windows).

**Comment by NotATreoFan** [comment]
You may need to disable signed driver enforcement. Check here for more info: http://www.overclock.net/t/187919/how-to-disable-driver-signature-enforcement-in-vista

**Comment by Shredasaurus34** [comment]
The program itself will open and I can load my roms but when I connect my NES classic to my computer....windows sees the device but even when I point device manager to the Hakchi folder...it never installs the driver. If I doublclick the NESMiniDriver.exe it says "This application has failed to start because API-MS-WIN-CRT-RUNTIME-l1-1-0.dll was not found. Re-installing the application may fix this problem".

**Comment by Shredasaurus34** [comment]
Reinstalled Runtime. Now in the driver.exe command window I get 

libwdi:warning [Wdi_create_list] could not read device description for 10: [#0000000D] the data is invalid
 Now in the driver.exe I get "Found USB device:"unknown device #1 1f3a:efe8
installing WDI driver with <nesmini.inf> at <usb_driver>

Press enter to exit driver installer

**Comment by ClusterM** [comment]
Try to use Zadig util.

**Comment by Shredasaurus34** [comment]
Gave Zadig a try. It says "Driver Installation failed (operation timed out). This is starting to become very frustrating.

**Comment by alexsyvolkov** [comment]
Кто-то досихпор юзает Windows Vista :D
