### ISSUE TITLE
game slow downs on certain games

### ISSUE THREAD

**Issue by slinso1337** [ClusterM/hakchi2#211]
Hello,
i havn't found anything related. Maybe someone can simply answer my question.
On some games - like MegaMan1, 4, Kirby and maybe more (didn't test that much until now) - i notice that the games will slow down for some seconds when i have multiple enemies and a lot of animations on the screen. This is really annoying, because it feels like the game has only 10-15 frames.
Is that a know behaviour? Is there a way to fix it?
Thanks!

**Comment by baconcow** [comment]
This is normal behaviour for NES games and happens also on the originals. Boot them up on your PC (which is likely much more powerful than the NESCE), with an emulator, and you will see. The NES could only handle a small amount of simultaneous sprites; 8 per scanline, I believe.

**Comment by Bartvz** [comment]
This is not the right place to raise this, the right place is here: https://github.com/ClusterM/retroarch-clover
Please close this issue and post there.

You could try switching emulator to nestopia or fceux using retroarch (--retroarch -- core *coreofchoice*).

**Comment by slinso1337** [comment]
Thanks. Tested with NES Emulator in Windows. Mega Man 1 - Iceman still slow.
Tired with nestopia - even worse, with fceumm - the same as original emulator.
But this is weird. I cannot remember, that it lagged over 25 years ago on original NES ... :(

**Comment by Bartvz** [comment]
You might be able to verify it on youtube or with someone owning the console and game.
But: 
>This is not the right place to raise this, the right place is here: https://github.com/ClusterM/retroarch-clover
>Please close this issue and post there.
