### ISSUE TITLE
Question, Enhancement : Add Play-Choice 10 as a game in NESC

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#212]
It would be nice to have the arcade machine Play-choice10 (with its 10 game) presented as a game (ie an icon) in the NESC.

**Comment by Bartvz** [comment]
This is not the place to ask this question. Please close this and ask here: https://github.com/ClusterM/retroarch-clover

You can also attach the tags question and enhancement to your post. This will make what you want more clear.

**Comment by black-pudding** [comment]
pcm720 wrote : "You should suggest this in Hakchi2 repo.". https://github.com/ClusterM/retroarch-clover #41

**Comment by Bartvz** [comment]
Good, you found the tags.
But:
>This is not the place to ask this question. Please close this and ask here: https://github.com/ClusterM/retroarch-clover
