### ISSUE TITLE
Controller Hacks (Down+Select)

### ISSUE THREAD

**Issue by BigE909** [ClusterM/hakchi2#215]
I went through the entire process, NES Classic Mini works just fine with over 600 games. My issue is I selected "use button combination to rest" under the controller hacks tab. I left it at default (down+select) but it won't work, I made sure the selection was checked. Now when going back to hakchi2, do I have to restart the entire process just to enable the controller hack?

**Comment by ClusterM** [comment]
Hi!

Make sure that you hold button combination for a ~0.5 of second, not just pressed it.

Yes, you need to repeat the whole synchronization process. It will be fixed in next version, I'm working on it right now.

March 10, 2017 9:38 PM, "BigE909"  wrote:
	I went through the entire process, NES Classic Mini works just fine with over 600 games. My issue is I selected "use button combination to rest" under the controller hacks tab. I left it at default (down+select) but it won't work, I made sure the selection was checked. Now when going back to hakchi2, do I have to restart the entire process just to enable the controller hack?

**Comment by BigE909** [comment]
Awesome! thank you for the quick response.
