### ISSUE TITLE
Cannot put NES Classic into programming mode after flashing Hakchi kernel (2.13e)

### ISSUE THREAD

**Issue by SupahDave** [ClusterM/hakchi2#217]
After I installed the customer kernel, I am no longer able to get the system into flash mode by holding RESET while powering on. The system does not get recognized by any of my computers when doing this anymore. I can power the system on normally but cannot flash anything.

**Comment by SupahDave** [comment]
Just to be clear... This system isn't bricked, it just will not connect to any computer after flashing the customer kernel. Is there any other way to flash it?

**Comment by seanrox** [comment]
When hakchi2 says "waiting for your NES mini" during the syncing, be sure to hold the reset button on the NES mini for at least 5 seconds after pressing the power button... count it out slow like 1... 2... 3... 4... 5... then release it. When I had the same issue waiting longer before releasing reset made it work. Hope that makes sense.

**Comment by SupahDave** [comment]
Sorry, should've specified that I'm not a newb to doing this. I've flashed over 20 NES Classics and this is the first time I've run into this. I was able to get the custom kernel to flash but now when I try booting up while holding in the reset button..... nothing happens

**Comment by seanrox** [comment]
@SupahDave No worries, didn't think you were a newb ;) just trying to make a suggestion since I had a similar issue and doing the "hold for 5 seconds" thing solved it for me. Have you tried rebooting your computer that's having the issue? Sometimes that helps with all sorts of things, again not saying you're a newb, just trying to help.

**Comment by SupahDave** [comment]
Yes, tried rebooting. I even switched over to another computer... still nothing. This is really weird...

**Comment by SupahDave** [comment]
Has anyone else run into this issue?

**Comment by ClusterM** [comment]
It's very strange. Please check that USB cable and USB socket are not bricked.

**Comment by SupahDave** [comment]
Hey Cluster,
Thank you for the direction. You were 100% right! The USB port turned out to be bad. I checked the cable first and it was definitely good so I soldered in a new USB port and that fixed it. The port must have had a broken connection inside of it... You're the man! Thanks for putting me in the right direction!
