### ISSUE TITLE
Cannot add neogeo games

### ISSUE THREAD

**Issue by JPdefrancesco** [ClusterM/hakchi2#219]
Hi,
I cannot seem to add neogeo games to my NES Classic.  I downloaded a neogeo rom such as Metal Slug X.  I did read that I need to download neogeo.zip and add it to a game folder, so I add it to mslugx.  When I select "add more games" in hakchi2 it asks me to "select a file" and shows the options below.  

Select file:
250-c1.bin
250-c2.bin
250-c3.bin
250-c4.bin
250-m1.bin
250-p1.bin
250-p2.bin
250-v1.bin
250-v2.bin
250-v3.bin
neogeo.zip

What have I missed or done incorrectly?

**Comment by seanrox** [comment]
Did you install the proper core to your NES Mini?  Check out https://github.com/ClusterM/retroarch-clover for detailed instructions on how to add additional cores to your system and see if that gets you going.

**Comment by seanrox** [comment]
Here is the specific link for "how to" https://github.com/ClusterM/retroarch-clover#how-to-use-this

**Comment by JPdefrancesco** [comment]
Yup. All cores added and still can't add these games.

**Comment by seanrox** [comment]
I know there is a 30MB filesize limit per ROM, so maybe that has something to do with it? I don't have this ROM to check for sure. Also, is your game ROM zipped? Looking at your original post, it seems you might be trying to add unzipped files. Just a thought trying to work through this with you...

**Comment by black-pudding** [comment]
I think hakchi2 asks, at some point, if you want to import the zip file as an archive (or something like that) or if you want to select a specific file inside the zip file. You have to say you want to import the whole .zip as an archive. Plus you have to change the command line replacing .../zip by .../fba as the "how to" says.

**Comment by black-pudding** [comment]
You also have to be sure that the rom you have is a "parent rom" not to have any dependencies over other files that are missing.
