### ISSUE TITLE
Некорректное наименование игры при синхронизации с БД ROM'ов

### ISSUE THREAD

**Issue by KotovAlexander** [ClusterM/hakchi2#22]
Некорректное наименование игры при синхронизации с БД ROM'ов, похоже игнорируются все символы после запятой.

ROM: Jetsons, The - Cogswell's Caper! (U) [!].nes
Данные в БД: Jetsons, The: Cogswell's Caper
Результат: Jetsons

**Comment by ClusterM** [comment]
Это по той причине, что многие названия после запятой содержат ненужные уточнения. Это может быть как банальный артикль "The", так и название студии, например "Disney's". Думаю, что лучше так и оставить.

**Comment by KotovAlexander** [comment]
Не согласен, название должно быть полным. 

Вот пример проблемы, 2 разные игры:
1. Flintstones, The: The Rescue of Dino & Hoppy
2. Flintstones, The: The Surprise at Dinosaur Peak!

В результате, в обоих случаях: **Flintstones**

**Comment by ClusterM** [comment]
Хорошо, убедили :)
