### ISSUE TITLE
Numbered folders can't be opened 

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#222]
I've reorganised the folders and have put custom folder images (204x204 pixels^2). I've also overwritten the file "folder_back.png" as I hadn't seen any other option in hakchi2 to mod the back folder's image. And now I see the main folders in the NES mini shell but I can't open those (black screen then back to the NES mini shell).

**Comment by black-pudding** [comment]
I've found what caused the bug. It was the name of the folders following this syntax : "1. MARIO", "2. MEGAMAN" and so on.

**Comment by ClusterM** [comment]
Need to find correct pattern which causes this glitch. And add check for it into hakchi2.

**Comment by ClusterM** [comment]
I can't reproduce problem :(

**Comment by black-pudding** [comment]
- There were no games in the home dir
- There were 10 folders named "#. XXX" from "1. MEGAMAN" to "10. ARCADE". The latter folder was set to the right the others to the left.
- Maybe it was the 10th the problem
- The names of the folders were appearing some times with the dot sometime without and in any casse never with the number

**Comment by black-pudding** [comment]
The thing is also that I overwrote the image folder_back.png while I was already in the hakchi2's window to organise the folders on de NES mini.
