### ISSUE TITLE
Question: which files have I to take in the repo?

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#224]
Which files have I to take in the repository in order to have the latest version of hakchi2 (which includes the feature turbo x/y)?

**Comment by baconcow** [comment]
Click the green button, [here](https://github.com/ClusterM/hakchi2), that says "Clone or download". A drop-down menu will open; click "Download ZIP" to obtain the current (non-compiled) version of hakchi2.

**Comment by black-pudding** [comment]
Thx!
