### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Driche** [ClusterM/hakchi2#225]
Played the console for about an hour. Then I went into a folder to play a different game, and the screen went black. When I push the power button the screen says SHUTTING DOWN..... like it normally does when you power the console off.

When I go to turn it back on, the screen is black again. Reset button does nothing.

Tried unplugging for a minute or two and does nothing as well.

**Comment by tjm694** [comment]
Had the same issue, had to reflash it for it work again.

**Comment by ClusterM** [comment]
Seems like invalid folder ID or font problem. Re-flashing should help.

**Comment by Driche** [comment]
Re-flashing helped and all is now working. Thanks for all the input.
