### ISSUE TITLE
Error when using Game Genie code for Battletoads

### ISSUE THREAD

**Issue by graykimbrough** [ClusterM/hakchi2#226]
I am able to apply Game Genie codes to other games, and those seem to work perfectly. But when I apply one to Battletoads, I get an error during the kernel compile (see screenshot below). The code then doesn't have an effect. I suspect this has something to do with the patch, which I applied when I added Battletoads.
<img width="468" alt="screen shot 2017-03-16 at 2 28 54 pm" src="https://cloud.githubusercontent.com/assets/11068513/24013614/5ece07ee-0a58-11e7-9c24-7ed3bd70a2a1.png">

**Comment by ClusterM** [comment]
Hi.
Already fixed. New version will be released soon.
