### ISSUE TITLE
Game genie infinite lives code problem in Contra 

### ISSUE THREAD

**Issue by graykimbrough** [ClusterM/hakchi2#227]
In Contra, the game genie infinite lives code seems to work fine (no major errors like when used in combination with the keep-your-weapon code) until you pick up a laser (L). Then your weapon is rendered inoperable. This continues even when you die and regenerate.

**Comment by 00arak00** [comment]
doesn't really seem like an issue with Hakchi but the fact that you are using a tool to edit game memory?

**Comment by ClusterM** [comment]
omg
