### ISSUE TITLE
What happens to boxart?

### ISSUE THREAD

**Issue by nilsbyte** [ClusterM/hakchi2#228]
When choosing boxart for a game (either manually or through the Google search results in hakchi), what happens to the chosen images when uploading them to the NES mini? 

Are they resized to a certain size?

If not, they would take more space which results in less games fitting onto the NESmini. I would like to know if I can choose the original files for boxart or scaled down versions to save space.

**Comment by baconcow** [comment]
They are resized and converted to a .PNG file. You can look in the specific game's folder within the hakchi2 /games/ folder to see them. You will find that the majority of them are less than 100 kB in size.

**Comment by nilsbyte** [comment]
Thanks for your answer. I have downloaded the covers from The Cover Project at http://www.thecoverproject.net/forums/index.php?topic=20072.

I have cut them in half to show only the front. The height is 2100px. By asking I just wanted to make sure that 714 boxart images don't get uploaded to the mini in original resolution.
