### ISSUE TITLE
Incorrect app folder

### ISSUE THREAD

**Issue by zlinx** [ClusterM/hakchi2#229]
Hello.

First of all: Thank you. This app is awesome and adds real value to NES Mini.

I´ve tried 2.14_RC1 and I get x "Incorrect app folder" errors on exit, where x is the number of games added. When I launch the app again, nothing has been saved.

I haven´t tried to sync with the NES Mini until no completely smooth process :)

**Comment by ClusterM** [comment]
Already fixed. I hope...

**Comment by zlinx** [comment]
Awesome… may I have the current compilation to test it??

Thanks again.

**Comment by ClusterM** [comment]
I'll release it soon.
