### ISSUE TITLE
Ошибка при применении патча

### ISSUE THREAD

**Issue by KotovAlexander** [ClusterM/hakchi2#23]
Ошибка при применении патча: "Индекс находится вне границ массива.".

ROM: Splatter House - Wanpaku Graffiti (J) [!].nes
MD5: 4FA13D2E51A3559D710EA3112E023DC7
Патч: https://cloud.mail.ru/public/F12D/aQben8AHZ

**Comment by ClusterM** [comment]
Fixed, thank you!
