### ISSUE TITLE
HELP! Installing NES Mini and modding with Hakchi 2.13e

### ISSUE THREAD

**Issue by emmanuelfromhawaii** [ClusterM/hakchi2#230]
Problem's I've encountered and how I fixed them. 

1. vcruntime140.dll missing. found file online - https://www.dll-files.com/vcruntime140.dll.html 
Downloaded, unzipped, and put .dll file in C:\Windows\System32 

2. ONGOING ISSUE: Error "NES Mini not found, sorry" when trying to install driver in Hakchi. In device manager, when I plug in and power on NES Mini, device manager has NES Mini listed as "clv-s-nes" with exclamation point indicating missing driver. If I turn it on in FEL mode (holding reset then powering it on), device manager has the NES Mini listed as "Unknown device". It tries to install some sort of driver but finally errors out indicating driver could not be found. 

What I will try tonight - Disable driver signature enforcement on Windows 10. I also have Zadiq ready if disabling driver signature enforcement doesn't work. 

Any other recommendations? 

I'm running Windows 10 32 Bit.

**Comment by baconcow** [comment]
There are release candidates for 2.14 signifying that it may be released soon, officially. You may wish to wait for that release.

For #1, apart from downloading from unofficial sources, have you tried installing the 32-bit version of [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-ca/download/details.aspx?id=48145)?

**Comment by emmanuelfromhawaii** [comment]
@baconcow cool, thanks for the reply. Number 1 is already resolved. I'm going to try and disable driver signature enforcement to see if this resolves the driver install issue.

**Comment by emmanuelfromhawaii** [comment]
Ok! Good news. Turning off driver signature enforcement worked. Everything went well and I now have about 70 games in my NES Mini. This is awesome!
