### ISSUE TITLE
Hakchi2 14 rc1 Forever Red Light If Not Enough Space for Flash

### ISSUE THREAD

**Issue by trumisery** [ClusterM/hakchi2#231]
Not sure if you got my email, but figure this would be a good spot to put this:

 I had flashed a nes mini that was already patched with an earlier version of hakchi2.  I had some nes saves and when I ended up trying to flash with v14 rc1 it gave me a "no more room" error and the system just hung with the hakchi screen outputting from the nes mini.  The only way to power the system off was to unplug the power source.
   I ended up deleting some save games as well as getting rid of a few other games (to make some room) and the system flashed and worked.

   If there is not enough room to flash the system, you basically get the "red light forever" bug that was on a previous version.

**Comment by ClusterM** [comment]
It's already fixed in rc2.
