### ISSUE TITLE
[Enhancement] Batch compression of already added NES roms!

### ISSUE THREAD

**Issue by MiLToS666** [ClusterM/hakchi2#232]
Hello! Since we can pass the --retroarch command for all games, it would be extremely useful to have the option to batch compress all (or selected) already added NES games in the library to save space. This option will also have to fix the .nes file references in the .desktop file to point to the compressed file instead. Artwork and all the other information should stay intact. I see that someone tried to do this already with a pull request on the code but I couldn't try it out. Thank you! :)

**Comment by elierodrigue** [comment]
i'll most likely redo another build with that feature when new version with clovershell is released.

**Comment by MiLToS666** [comment]
I managed to do what I wanted using the command line version of 7zip to find all .nes files in hakchi2 games folder and compress them individually inside their own folders. Then used Notepad++ to find and replace all .nes instances in every .desktop file to .7z and it worked great! Now my library is down to 216MB from 299MB before the compression. Having this procedure as an option in hakchi2 will be great! Thank you very much! 👍

**Comment by abijanfar** [comment]
@elierodrigue I recommend you make your app more of a companion app version a replacement app. That way you can drop your exe (with different name) in the same folder and it would do some "enhancement" work on the existing files. For example compressing all .nes roms. This is how I used your exe in the past.

**Comment by Drakonas** [comment]
This has been addressed.
