### ISSUE TITLE
[Enhancement] Wii's Arcade FightStick

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#233]
Would it be possible to make the official Wii's Arcade FightStick Tatsunoko vs Capcom (Madcatz) operational with the NES mini?

**Comment by ClusterM** [comment]
Yes. But I have not this controller. I need one for coding/testing.

**Comment by Babbonz** [comment]
The tatsunoko vs capcom stick is already fully usable as I've been using this since hakachi was first released (the official stick is basically the same as a classic controller and already works in retroarch etc)

**Comment by black-pudding** [comment]
Cool :)
