### ISSUE TITLE
Compile error due to incorrect resource under french version of Windows

### ISSUE THREAD

**Issue by nespas** [ClusterM/hakchi2#236]
hakchi2 won't compile under french versions of Windows if the 'Del'  resource is not replaced by 'Suppr'.

Error obtained:
1>E:\NES\hakchi2-master\FoldersManagerForm.resx(757,5): error : MSB3103 : Fichier Resx non valide. La valeur demandée 'Del' est introuvable. Ligne 757, position 5.

Fix:
Find a way to automatically use the correct resource text. 'Suppr' works for french Windows but other translations may be required.

**Comment by donlent** [comment]
Same thing here with "Ctrl" on German platform.
Putting "Strg" (the German string for Ctrl) fixes the problem.
@ClusterM: I've seen that you've already fixed the "Del" issue. :-) Maybe you can integrate also Ctrl in an easy way? Thank you very much for the great work!! :-D

**Comment by nespas** [comment]
Tested "resource cleanup" version, builds without error. Thanks !

**Comment by ClusterM** [comment]
Fixed :)
