### ISSUE TITLE
Request : would it be possible to (beta)release v2.14rc# as a executable windows (or OSX app) ?

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#238]
I have totally forgotten how to compile C/C# with the main and plenty of little files. A release for old fart like me of v2.14rc5 in an simple .exe 32/64 or .app for OSX would be sooo nice even its only a beta.

**Comment by baconcow** [comment]
Contact me on Reddit (same name) and I'll compile it for you.

**Comment by black-pudding** [comment]
thx

**Comment by zlinx** [comment]
Thank you...

**Comment by Babbonz** [comment]
I tried your build but now hakachi asks to install the USB drivers each time when flashing the games and folders but fails to connect?  I'll be patient and wait for official build which sounds like it's close to release anyway?

**Comment by zlinx** [comment]
Ok… ok… I'll wait…

This will be like christmast presents!!

**Comment by black-pudding** [comment]
OK thx for your warning

**Comment by Babbonz** [comment]
Update : reinstalled and this does work. You just turn on nes mini now and flash rather than holding down the reset button etc and it flashes super quick!! :)

**Comment by ClusterM** [comment]
Release will be today.

**Comment by zlinx** [comment]
Best piece of news today…

Thank you ClusterM!!
