### ISSUE TITLE
Batman: Return of the Joker - mapper #69

### ISSUE THREAD

**Issue by KI11AK** [ClusterM/hakchi2#24]
I realise this is just a known issue regardless,  but is there a plan or possibility to have this playable on the Mini NES?

**Comment by sukoshi1507** [comment]
have you read hakchi2 source code? do you understand how the software work and what it does? your answer is there.

**Comment by baconcow** [comment]
KI11AK,

Likely the only opportunity to make games work that have incompatible mappers or problems running is with IPS patch files that hack the ROM to use a different mapper or fix other issues. ClusterM has already included IPS patches, within hackchi2, for Battletoads, Bill & Ted's Excellent Video Game Adventure, RoboCop 3, Snow Bros, and Startropics II: Zoda's Revenge. I have found other IPS patches for games like Contra (Japanese version), Holy Diver (Japan), and Splatter House: Wanpaku Graffiti (Japan), although I have not tested them yet on the NES Classic Edition (NES Mini). Unfortunately, I am unable to find an IPS patch for Batman: Return of the Joker. A good place to start looking for these would be at [ROMhacking.net](http://www.romhacking.net/).

**Comment by KI11AK** [comment]
Thanks baconcow.  I appreciate the informative reply
