### ISSUE TITLE
Codemasters mapper #71 titles not working (using 2.13e)

### ISSUE THREAD

**Issue by DeeJayDready** [ClusterM/hakchi2#242]
I am using 2.13e (the first version that I have used) and Codemasters titles such as Micro Machines & Fantastic Adventures of Dizzy (mapper #71), as well as High Speed Pinball (mapper #119) give the error "C6: This suspend point is not usable" when installed. I notice that this mapper issue was supposedly corrected in 2.08. Any advice?

**Comment by baconcow** [comment]
I was able to play Micro Machines on older versions. However, since 2.14 is out, now, why don't you try that. Also, are you using the RetroArch module? Some of those games are not compatible with the emulator built into the NESCE and will require the RetroArch module so that they can use either the Nestopia or FCEUmm emulator to run.

**Comment by DeeJayDready** [comment]
I'm not using any special modules. Just the stock Hakchi. I though that the was all that was need since 2.08 as they were 'automatically patched' - https://github.com/ClusterM/hakchi2/releases/tag/2.08

Here is an example of them working: https://www.youtube.com/watch?v=0g07lYl3YBg

**Comment by baconcow** [comment]
I edited my comment for clarity. Either way, I suggest you use v2.14 as it is the most up-to-date version of hakchi2 and takes mere minutes to send full sets games to the NESCE. The mapper #71 games should work, so there may be an issue somewhere. Either way, you could always install the RetroArch module and force them to run on Nestopia or FCEUmm.

**Comment by DeeJayDready** [comment]
I will try upgrading to the newest version (2.14b) later today and see if that solves it, but I'm not expecting it to. This is only billed as a "very experimental version", and unless the support for mapper #71 games has been dropped in later versions, they should still work post-2.08 as you say.
I want to avoid installing additional modules and add-ons if possible and just use the standard Hakchi2.
I'd be interested to know if anyone else has experienced the "C6: This suspend point is not usable" error when trying to boot certain games?

**Comment by ClusterM** [comment]
Mapper autopatching was removed because RetroArch much more stable and accurate. Just install RetroArch mod.

**Comment by ClusterM** [comment]
Also you can change mapper number manually if you really need it.

**Comment by DeeJayDready** [comment]
I have upgraded to 2.14b, added the retroarch_with_cores modules, flashed the custom kernal, but I cannot sync games. Without the hold Reset option it just sits there...

**Comment by DeeJayDready** [comment]
...and if I click Install driver it says "NES Mini not found, sorry"

**Comment by DeeJayDready** [comment]
Started from scratch with 2.14b and things seem to be working correctly now. Installed the retroarch_with_cores module and Micro Machines etc now seems to work. Thanks.
