### ISSUE TITLE
Keep getting error code out of space 2.14 when it uploads original roms

### ISSUE THREAD

**Issue by tjm694** [ClusterM/hakchi2#243]
Keep getting error code and won't complete when it tries to upload the original nes games.  Wish I could screen grab it.   last message says "out of space"  even though I have 284 meg out of 300 used.   If I disable the original 30 it works fine.  Any ideas?

**Comment by tjm694** [comment]
![capture](https://cloud.githubusercontent.com/assets/3503462/24085017/d347fad4-0cca-11e7-96e3-8604db25afac.PNG)

**Comment by tjm694** [comment]
Any ideas?  Plus I notice it keeps rechecking all the check boxes in the origial 30 as well.

**Comment by tjm694** [comment]
Same error code with 2.14b .... :(

**Comment by Driche** [comment]
I had same error today as well. Fixed by deleting some games. You have to consider .hmod files and art work in the 300MB. I got the message with 277/300MB used.

Sent from my iPhone

On Mar 19, 2017, at 4:38 PM, tjm694 <notifications@github.com<mailto:notifications@github.com>> wrote:


[capture]<https://cloud.githubusercontent.com/assets/3503462/24085017/d347fad4-0cca-11e7-96e3-8604db25afac.PNG>

**Comment by tjm694** [comment]
I'm back to 2.13e now.  It won't even recognize the nes mini in 2.14 anymore.  Just sits there with the read light on.  If I reupload retroarch or such with the FEL mode, it works, but just pressing the power button to sync games, it just sits there "waiting for nes mini" ..... just started.  Worked fine all day.

**Comment by Shinryuken** [comment]
I'm having this problem too uploading something like 215 mb (i have maybe 100 mb of retroarch cores).

Try reducing the games to upload.

@ClusterM , What about checking the space left on the partition with "df" or something else and reporting it back on hakchi2 so you can have on real time the size of the free space?

**Comment by ClusterM** [comment]
Seems like writable partition of NES Mini is overflowed with some data. It can be savestates (bts, latest SNES core using huge savestates), games,. mods.
You can use clovershell tool to check NES Mini's file system: https://github.com/ClusterM/clovershell-client
But it's requires basic Linux knowledge. Writable partition mounted to /var/lib
Also you can do total uninstall (via menu) and reinstall hakchi2 again. It will remove everything but not save-states.
You can use factory reset. It will erase all save-states but not emulators and mods.

**Comment by KMFDManic** [comment]
Depending on whether you are on a 32 bit or 64 bit operating system, you will get about 250 mb or less max flash ability on 32 bit, and 299 or less max flash ability on 64 bit.  This is determined by the inclusion of exclusion of previous save states and hmods  So, If you are on 2.14b, figure out what size your hmods take up, and flash at 250mb - that for 32 bit, or 299 - that for 64 bit.  If you use save states, expect to lose up to an additional 20 mb.  So, factory settings on mini, to clear the save states, or subtract to compensate for save states.  Clusterm is currently working on memory optimization for this bug.  So, this is your best course of action til then:)

**Comment by KMFDManic** [comment]
You may also want to read this related posting about the memory management on 2.14b...

https://github.com/ClusterM/hakchi2/issues/254

Clusterm will get a good handle on things.  Even if it comes down to a choice between fast flashing and less memory to use, versus slow flashing and more memory to use.  At least we will have a personal choice:)  I am sure he will figure things out, however!

**Comment by Drakonas** [comment]
This could have been avoided by leaving ample amount of free space for savestates. Closing.
