### ISSUE TITLE
Game Genie Codes Problem

### ISSUE THREAD

**Issue by Spottedfeather** [ClusterM/hakchi2#245]
I just got the new version of Hakchi2 and notice that you can't put Game Genie codes for anything other than NES games. You can't use Game Genie codes for Genesis or Atari or Game Gear games. Any ideas ?

**Comment by ClusterM** [comment]
Game Genie works only with NES games.
You can use RetroArch's cheat menu for other games.

**Comment by Spottedfeather** [comment]
How do I do that ? I'm just asking ahead of time as it will probably be months before they have the NES classics in any stores....

**Comment by ClusterM** [comment]
Open RetroArch's menu during game (default combination is Select+Start) and select "Cheats" menu.
I have not used it, so I can't say how it's working.

Game Genie is very platform dependent. It's totally different for different platform. And it's not so easy to add this bonus feature too all consoles while support for other consoles is bonus feature too :)
