### ISSUE TITLE
"Save settings to NES mini now" does not work

### ISSUE THREAD

**Issue by nilsbyte** [ClusterM/hakchi2#247]
When changing the sorting order of the games and saving the settings to NES mini, there is no change. I always have to Sync the games to also sync the settings changes.

2.14

**Comment by ClusterM** [comment]
It's related to all non-games settings only: font, controller hacks, epilepsy protection, command line arguments.
To change folder structure need to reupload games (yet).

**Comment by chillmodious** [comment]
If all we are trying to do is change the folder structure and sorting of games we have already uploaded, isn't it just a matter of dragging files around?  If the NES Classic is connected, isn't the point that we can make modifications without having to go through the process of uploading all the games again (which can take a long time)?

**Comment by ClusterM** [comment]
chillmodious, it's not so easy to sync actions on PC and NES Mini but it's planned.
