### ISSUE TITLE
Additions That I'd Like

### ISSUE THREAD

**Issue by NesClassicNoob** [ClusterM/hakchi2#248]
Show how many GB are left on the system in hakchi.

Show how much space each game takes up in hakchi,

Possible more space somehow with adding an sd card or something

Better frames per second for slow games

More releases XD

If those are already a thing,I am sorry I only have the 2.11 version of hakchi and am excited for the new releases!

If there is anything else I would like to add in a short period I will just edit this comment but in a week or so just post a new one :)

**Comment by maskedmaniac** [comment]
Hakchi2 version 2.13 changed the progress bar in the lower right of the window to also display how much space the selected games will use on your NESC. You may want to upgrade from 2.11 to take advantage of some of features that have been added since that version.
