### ISSUE TITLE
[Enhancement] Folder Structure when Adding Games and System Identifiers

### ISSUE THREAD

**Issue by baconcow** [ClusterM/hakchi2#249]
When adding games (hundreds of them), they all get added together in the main window. I then have to organize them all into folders, if using custom folders. Is it possible to have the folder structure integrated into the main window so that you can just drag specific games into folders there? This would only be available when custom folders are selected.

It can be a little confusing when you have multiple games of the same or similar name. If you add the games, along with their artwork, there is no indication of which system they belong to. Some system cover art, when small, make it difficult to decipher the system as they do not have many marking identifiers (i.e. many Japanese NES and SNES cover art).

Also, it would be nice to be able to organize custom folders before going to sync the games to the NES Classic. Perhaps you just want to take some time to organize the folders, in hakchi2, but not add the games until later.

Thanks. Great work!

**Comment by ClusterM** [comment]
It's planned.

**Comment by ClusterM** [comment]
I need somebody to help me draw GUI design.

**Comment by elierodrigue** [comment]
mostly done
