### ISSUE TITLE
Original Kernel Dump Download

### ISSUE THREAD

**Issue by Ippokun81** [ClusterM/hakchi2#25]
Hello to all, I have made a mistake during an update of HAKCHI. I erase my KERNEL DUMP ORIGINAL. I cannot flash NES MINI again, it shows me a warning MD5 Checksum and I cannot again synchronize the games. 
He somebody would be kind enough send me his own ORIGINAL KERNEL DUMP to RESTORE and FLASH it AGAIN.
Thank you in advance.
L.S.

**Comment by NaikiTurincondeliphone** [comment]
Hello, have you tried formatting the NES Mini?

**Comment by Ippokun81** [comment]
Hye, how to do it ? Via Uninstalling in HAKCHI ? All Things in Kernel Tab don’t work.

**Comment by NaikiTurincondeliphone** [comment]
Start the Mini NES and do it from the console settings, but you will lose all saved states

**Comment by Ippokun81** [comment]
Same Problem : 
I can Dump Kernel. Hakchi says : MD5 is unknow etc… (previous hack with hakchi).
I’ve lost the first and original dump.
And when I try to flash kernel again or synchronise game HakChi Says : Access to path D: hakchi2 / temp / kernel / initramfs / bin.chroot is denied.

**Comment by Ippokun81** [comment]
PS : Despite the formatting the hack is still here.

**Comment by NaikiTurincondeliphone** [comment]
It's weird, after formatting you should not have problems. Try downloading a previous version, for example 2.09, to see if it works.

**Comment by Ippokun81** [comment]
Same problem, I think the only solution is to re inject original kernel dump (I think the same in all new mini). And after flash it again

**Comment by NaikiTurincondeliphone** [comment]
Okay, then I'll send you my dump for you to try, but it'll be in a few hours, I'm not home. My nick telegram is @Naiki add me and I'll send it over

**Comment by Ippokun81** [comment]
Done, thank U for your help 

Envoyé de mon iPhone

**Comment by NaikiTurincondeliphone** [comment]
Send me a mail and send you my dump

**Comment by Ippokun81** [comment]
Thank you for your help I received an original dump a dozen minutes ago. problem solved. thank you very much.

Envoyé de mon iPhone

**Comment by NaikiTurincondeliphone** [comment]
Ok, I'm glad you solved it :)

**Comment by ClusterM** [comment]
Original kernel is the same for all consoles but I'm not sure that it's legit to share it.
But it's safe to ignore MD5 warning and continue .

**Comment by GoodbyeWorld** [comment]
@ClusterM - It's nice of you to want to help, but I'd strongly suggest NOT sending that, or offering to send that, to anyone.

Let us nobodies in the community take that risk for you.  :)

**Comment by Ippokun81** [comment]
Thank you to All

**Comment by mafon2** [comment]
Yeah, thanks from me too.

**Comment by getiting** [comment]
can someone send me the kernal i am having the same issue

**Comment by Drakonas** [comment]
Locked this issue as people are still asking for illegally uploaded content.
