### ISSUE TITLE
file extension detection doesn't work for Sega ROMs from Sega Virtual Console

### ISSUE THREAD

**Issue by jmtd** [ClusterM/hakchi2#251]
If you buy and extract ROMs from Sega Virtual Console, they have various different file extensions etc. Examples from my own

Gunstar Heroes U.bin
SONIC2_W.68K
Sonic_Knuckles_wSonic3.bin
SONIC_W.68K

Hakchi2 turns these into command lines like `/bin/bin` and `/bin/68k` which obviously don't work.

One solution is to rename the ROMs before importing, if the user has figured out that this is the problem; or simply change the command line if you are an expert. But perhaps a more clever scheme than looking at the file extension is needed.

**Comment by ClusterM** [comment]
"bin" extension is not a game extension. It can be used for any binary file.
"68k" is not used by pirate scene too, afaik.

**Comment by jmtd** [comment]
Of course you can use any extension for any file. That's why I suggested a better scheme than just looking at the extension. I don't know which (or if any) ROMs typically have a magic number or anything (probably not). I find your position on "pirate scene" pretty funny. You can actually legitimately buy these ROMs now, but let's ignore that and just do what the pirates do?

**Comment by Babbonz** [comment]
I've used homebrew Sega megadrive roms with the bin extension... Just rename the rom extension from bin to md and it works fine.

**Comment by Drakonas** [comment]
Change the /bin/XXX to /bin/md. Solved.
