### ISSUE TITLE
[Question / Bug] 8bitdo NES30 controller button mapping issues

### ISSUE THREAD

**Issue by donlent** [ClusterM/hakchi2#257]
Dear @ClusterM , Dear All

I want to thank you all in advance for your support. I'm sure that out there are experts much more than I am and maybe what I'm writing now will be easy to resolve once you know how to do it...  :-D

Here's the issue:

I obviously bought one of these gorgeous gamepads from 8bitdo (NES30 incl. Retro Receiver Classic):
http://www.8bitdo.com/retro-receiver-nes-classic/

Probably it's the most commonly used out there since it is from a well known company...

Actually it works BUT.... The X and Y buttons as well as the L and R buttons just don't work as expected in SNES games. :-( 

Now I read on the 8bitdo Forum here and there that you can sort of remap the keys. I actually tried that as well but it didn't work either! The buttons just don't get mapped with their default values.
On the other hand if you take the original [Wii Classic Controller ](https://www.google.ch/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwiTqIbHv-fSAhUoKcAKHc7FA6gQjRwIBw&url=https%3A%2F%2Fwww.amazon.de%2FNintendo-2110266-Wii-Classic-Controller%2Fdp%2FB000IN0BSU&psig=AFQjCNE1yiM2OeOkyE_BecCRdjq0TSCB0w&ust=1490182229964452)
everything works as expected... BUT... you have to deal with the short cable like with the original NESC controller.

Now question to you all:
It's just me beeing "dumb" because I don't know how RetroArch remaps the keys or is it really related to the controller's firmware and therefore there's nothing we can do?

Is there somebody out there that has this 8bitdo controller as well and wouldn't mind to test it out with a SNES game (for example Donkey Kong Country)??

Any help is muuuuuuuuch appreciated!

Thanks a lot guys!!
... and the biggest THANK YOU tu @ClusterM  madmonkey that make all this possible!!! 👍 👍 👍

**Comment by ElusivSanity** [comment]
You just need to download their new beta firmware and update the controller with it. Off hand I cant remember what or where, but just google it and you should find a link for v5 beta, or whatever the latest beta version is called.  Fixed mine from only having a/b and a turbo/b turbo.

**Comment by tjm694** [comment]
v1.05 beta works AWESOME for the nes classic dongle for the nes30.  My only issue I have is retroarch seems to use the X button to open the menu, even though I can NOT find where it says it does this.  So 1 press out of 3 the menu will come up.   But that firmware is AWESOME.   StarFox and F-Zero are great with the L & R buttons.   

If anyone has any insight on the X button being mapped to the menu that would be awesome.

**Comment by ElusivSanity** [comment]
@tjm694 

In retroarch menu look in settings>input and "menu toggle gamepad combo" should be set to start + select.

**Comment by donlent** [comment]
Hi all!

Thank you very much for the feedback!

OK I actually installed the latest versions for both the Receiver and the NES30 (btw a new version 3.0 is available since two days ago! :-) )
But the result is still the same!

I want to clarify that I'm not having issues with NES games... only with SNES games since the X and Y buttons are not acting as expected... I suppose because they are like "statically programmed" to be Turbo buttons... but that does not exist in SNES (I think...)

Guys can somebody of you please do me a favor?
Try Donkey Kong Country 1, 2 or 3 and see if you're able to use the X and Y buttons as you should...
Then compare it to a classic controller (if you have one) and see that it's not correctly mapped.

@ElusivSanity could this setting also help me eventually?

Thanks again for your help!!!

Greatly appreciated!!

**Comment by tjm694** [comment]
You need the beta hacked firmware not the official one.  V1. 0 5 Beta




On Wed, Mar 22, 2017 at 4:31 AM -0400, "donlent" <notifications@github.com> wrote:












Hi all!


Thank you very much for the feedback!


OK I actually installed the latest versions for both the Receiver and the NES30 (btw a new version 3.0 is available since two days ago! :-) )

But the result is still the same!


I want to clarify that I'm not having issues with NES games... only with SNES games since the X and Y buttons are not acting as expected... I suppose because they are like "statically programmed" to be Turbo buttons... but that does not exist in SNES (I think...)


Guys can somebody of you please do me a favor?

Try Donkey Kong Country 1, 2 or 3 and see if you're able to use the X and Y buttons as you should...

Then compare it to a classic controller (if you have one) and see that it's not correctly mapped.


@ElusivSanity could this setting also help me eventually?


Thanks again for your help!!!


Greatly appreciated!!

**Comment by donlent** [comment]
Thank you very much @tjm694 !!

I actually found the firmware. Is it that one?
http://forum.8bitdo.com/forum.php?mod=viewthread&tid=1404&page=1#pid4634

After I've flashed it (on the Retro Receiver) is there anything I need to do to activate all buttons or will it be like the Classic Controller by default?

Sorry for all my questions but I really hope that this can help also others facing the same issue...

...8Bitdo is great... but their documentations are just sooooo bad!!!!!

**Comment by ElusivSanity** [comment]
@donlent 

Hey sorry when i first commented back about firmware i wasnt able to be more specific but things were getting busy.  So i'm guessing you have already flashed and figured this out, but if not yes that link is the correct firmware. v1.05 beta.  You should be able to play donkey kong country, any other snes games, or any games which require the additional buttons!

**Comment by donlent** [comment]
Hi @ElusivSanity 
Don't worry!! I'm glad you commented! :-D
Actually no, I didn't have time yet since I'm @work...

But will do it as soon as I get home and will certainly post my result.
In the meantime thanks again for your support!

**Comment by tjm694** [comment]
I just sent into retroarch config and redid the buttons.  Works great. 




On Wed, Mar 22, 2017 at 6:14 AM -0400, "donlent" <notifications@github.com> wrote:












Thank you very much @tjm694 !!


I actually found the firmware. Is it that one?

http://forum.8bitdo.com/forum.php?mod=viewthread&tid=1404&page=1#pid4634


After I've flashed it (on the Retro Receiver) is there anything I need to do to activate all buttons or will it be like the Classic Controller by default?


Sorry for all my questions but I really hope that this can help also others facing the same issue...


...8Bitdo is great... but their documentations are just sooooo bad!!!!!

**Comment by donlent** [comment]
Dear all

Just wanted to confirm that as suggested the firmware listed above (1.0.5 Beta 0) for the Retro [Receiver NES Classic](http://www.8bitdo.com/retro-receiver-nes-classic/) (NOT the Controller) fixes all the problems!!

Super!!! I'm so glad about the help I received!! 

**Additional info for those who are facing the same issues**
That means that you can install whatever Firmware you want on the Controller and it should work in combo with the Receiver. I'm actually running Firmware 3.0 on NES30 without issues.

In case you need to remap the controller buttons as well (make B --> A, X --> Y or whatever you want)
then you'll NEED [Firmware 2.70](http://download.8bitdo.com/Firmware/GamePad/bluetooth_firmware_V2.70.zip)
Only this one supports the such called "RemapTools" (located in the same zip).

If you don't then you're fine with upgrading **_only the controller_** to every new version 8Bitdo will release.

Hope this will help!

Again thank you very much for everything guys!!

@ClusterM Feel free to mark this issue as fixed. ;-)

**Comment by vincenttt** [comment]
The link to the thread does not work, would anyone be so kind and post the beta 0 files here or link it? Can't seem to find it, the 8bitdo site only list the 1.05 Beta3...

**Comment by donlent** [comment]
Dear vincentt

This is what really makes me angry about 8Bitdo... They make such good products but the support is just awful!!

Please find the firmware attached:
[8Bitdo_NesMini_RR_Firmware_v1.05_Beta0.zip](https://github.com/ClusterM/hakchi2/files/1046994/8Bitdo_NesMini_RR_Firmware_v1.05_Beta0.zip)

Remember: It's the Firmware of the RetroReceiver that you need to upgrade!! In case of questions I'm here to assist. ;-)

Best,
Don

**Comment by vincenttt** [comment]
Hey Don! 
Many and thousand thanks! Can't wait to get it working when I get home. 

One thing... I updated the Fc30 this morning =(...I hope the upgrade has no effect on the button issue even though I use the beta 0 on the RR?

**Comment by donlent** [comment]
No problem! It's a pleasure! ;-)

Actually I don't think the firmware of the controller itself is a problem. I haven't upgraded to 4.0 though... Anyway don't worry... you can alwawy go back to a previous firmware. ;-) So you should be all set...

**Comment by vincenttt** [comment]
Downgraded the RR from  and reloaded the Retroarch module as I messed it up completely (--).

Default settings... and everything works like charm. 

Quick summary for those with RR and a FC30 (Bought the RR separately)

1) Retro Receiver: 
- Came with FW 1.03. 
- Upgraded to FW 1.05 Beta 3. Didn't work.
- Downgraded to FW 1.05 Beta 0 (provided here). Works like a charm!

2) The controller (FC30)
- Came with: 2.70 
- Upgraded to 4.00. Works! (2.70 probably works as well)

3) Nes mini
Uninstalled and then installed the Retroarch   (I messed up a lot of buttons in Retroarch, don't think it is necessary reinstall like I did though).

4) Power on the mini and the FC-30. Jump into a SNES (Desert Strike), test all the buttons and ignore everything around me for an hour =).

Thanks Don!

BR.
Vincent

**Comment by AaronBDC** [comment]
dolent 8bitdo makes products that LOOK nice but perform poorly.
lower your expectations.

**Comment by leshrac55** [comment]
Just wanted to add that I got my WiiU Classic controller working with the beta firmware that donlent posted above. For some reason the X+Y buttons were not working for at least 1 game (probably more). I had updated to firmware 1.06 from the 8bitdo site and that did NOT work. As soon as I updated to the 1.05beta listed above it worked great. Thanks!

**Comment by geirawsm** [comment]
Thanks to @donlent for providing a good solution to a problem that 8bitdo should be able to avoid 👍
