### ISSUE TITLE
Controller stopped working after flashing

### ISSUE THREAD

**Issue by tabl** [ClusterM/hakchi2#258]
Hi everyone,

I flashed my NES Mini with hackchi2, and after it was all done, it stopped responding to any buttons pressed on the controller (the original one). Flashing to original kernel or complete deleting hackchi didn't help. Are there any ways to unbrick the console?

**Comment by chiefthief** [comment]
That happens to me too every once in a while when I flash. I simply turn the system off. turn it back on and everything works as it should

**Comment by tabl** [comment]
@chiefthief I wish it were so simple.. I tried rebooting, reflashing and restoring console and nothing helps so far :(

**Comment by 1lokolo1** [comment]
Are you tried to remove the controller and connect it again? Have you some friends that have another controller to test in your mini?

Rgs.

**Comment by mrTruch** [comment]
This happen to me once, my solution was simple. Turn off turn on and WALA! It worked again.

**Comment by Utty88** [comment]
Have you tried the other controller port?
Recently read about an not perfectly soldered USB-Port to the Mini. Maybe there is also a not perfectly soldered controller port possible.

**Comment by tabl** [comment]
@1lokolo1 @Utty88 yep, I tried both ports and reconnected the controller several times. Maybe I should reflash the console with another version of software? By now I tried 2.14 and then 2.13 with no effect

**Comment by 1lokolo1** [comment]
My recommendation is to uninstall hakchi2 and contact with Nintendo SAC or Store where you buy this mini nes classic, I think you mini is faulty. 

Rgs.

**Comment by ClusterM** [comment]
Are you using original controller which bundled with NES Mini or original Classic Conroller?
Which version you are using? Try to fully uninstall hakch2 (uninstall via menu + original kernel reflash) and install hakchi 2.13.

**Comment by black-pudding** [comment]
This also happened to me the 1st time I used hakchi 2.14b. The turn off/on method worked for me.

**Comment by ClusterM** [comment]
If you have controller that still not working on v3.14 please do the following steps:

1. Install mod with stecial debug version of controller driver (drag&drop on hakchi2 window): http://clusterrr.com/temp/clovercon_debug.hmod
2. Turn NES Mini off.
3. Connect this controller to NES Mini (only one controller, any port).
4. Turn NES Mini on. Wait until it booted up.
5. Close hakchi2 if it's opened.
6. Download: http://clusterrr.com/temp/clovercon_getlog.zip and unpack it somewhere.
7. Run "getlog.bat" from this archive. It should create "clovercon_debug.txt" file.
8. Send this "clovercon_debug.txt" to me: clusterrr@clusterrr.com

**Comment by tabl** [comment]
@ClusterM I tried reflashing the console on another computer (Windows XP in VirtualBox on MacBook instead of Windows 10 PC) and it just started working! Hooray!

But now I can't install modified kernel, I am getting "Can't unpack kernel image" error.

**Unpackbootimg.exe** actually works from the command line but not from the app.
Here's the unpackbootimg.exe.stackdump file contents:
`Exception: STATUS_ACCESS_VIOLATION at eip=61151EFB
eax=00000000 ebx=000000A7 ecx=0022B0D8 edx=00000001 esi=0022D51C edi=0022B0D8
ebp=00000000 esp=0022B0C0 program=C:\hakchi214\tools\unpackbootimg.exe, pid 3064, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
End of stack trace`

**Comment by tabl** [comment]
Well now, I fetched Windows 7 image for VirtualBox. Using it I finally flashed modified kernel to the console. And the controller works! 

But I'm afraid it's not the end...

Now I should just start the concole normally, install the driver and start uploading games, but the Device Manager says "The device cannot start" under the "NES Mini" section. How can we beat this final step?

**Comment by tabl** [comment]
I didn't figure out how to fix that USB issue, so I tried uploading games on the PC i started with. And finally it works. I am not sure if this was a hardware or software issue but therefore I'm happy it is solved now. Thank you guys for your support!
