### ISSUE TITLE
Folders' pictures are stretched (v2.14b)

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#259]
First of all, thx for the 2.14b release. It rocks : super fast upload, turbo on x/y and so on!
Issue: the folders' pictures are stretched (compared to what occurred with hakchi 2.13e). A square folder image (204 px x 204 px) appears as a portrait rectangle in the NESC's shell.

**Comment by baconcow** [comment]
Are you putting in a folder image that is exactly 204x204 pixels, or is it another size that is scaling to 204x204 pixels? Could you upload an image of what one looks like in the shell? Thank you.

**Comment by black-pudding** [comment]
Yes the images are exactly 204x204 pixels. I'll take a picture in a while.

**Comment by baconcow** [comment]
I think I may know the issue. I also have a square image on mine, and the resulting image on the NESCE is not stretched. The white area on the right and left of that image is 24 pixels wide (total of 228 pixels wide); 12 pixels on each side. The height of that picture is 204 pixels, which is the maximum amount of pixels that fit.

I have attached an image of what your folder should look like on a TV with 1:1 image settings. As you can see, it has whitespace on the left and right, similarly to the image, of yours.

Is it possible that your TV settings are stretched or set to fit? Please check your TV settings and let me know if that is not the case. I am not sure if this is the solution, but I'll try to help further, if it is not.
![test](https://cloud.githubusercontent.com/assets/11164879/24191082/5c849e06-0ec9-11e7-9bf8-e5f8eec00fab.png)

**Comment by black-pudding** [comment]
The screen is 1920x1200 16/10 and doesn't fit the 720p 16/9. That should be it. Thx!
