### ISSUE TITLE
Files in hakchi2 folder get corrupted and missing

### ISSUE THREAD

**Issue by njascgil** [ClusterM/hakchi2#26]
First of all, thanks to ClusterM for this extremely easy to use and useful piece of software!

I've been using hakchi2 for the past few days to add some 2 player Co-Op games to play with my children.
However, I noticed that I frequently have to replace the files in the hakchi "installation" folder, unpacking the zip file again, because the original files get corrupt or missing.
Usually, the symptom I get is some sort of error while trying to sync with the NES Mini. After replacing the (mostly executable) files, everything is ok again.

I don't recall running any other software alongside hakchi2, and I had my AV disabled... Is there any chance that hakchi2 is modifying its own bin/exe files by itself?

**Comment by jdpgrailsdev** [comment]
Have you verified that your virus scan software is not detecting and deleting the files in the folder?  If you have scanning enabled, this is probably what is happening.  I would recommend adding an exclusion to your virus scan software to not check the `hakchi2` folder and all sub-folders.

**Comment by njascgil** [comment]
Yes, that possible cause crossed my mind, but that's why I disabled the AV... It happened twice with the AV disabled...
