### ISSUE TITLE
Missing "Remove Thumbnails" Option?

### ISSUE THREAD

**Issue by emmanuelfromhawaii** [ClusterM/hakchi2#260]
Was looking at the settings and it's missing the "remove thumbnails" option. I believe this option removes those tiny thumbnails on the bottom of the main game select menu. Using version 2.13.

**Comment by baconcow** [comment]
This does not appear to be a feature of 2.13e. It was a feature of an older version of hakchi2.

**Comment by emmanuelfromhawaii** [comment]
Thanks baconcow. So is it officially gone now with the later versions?

**Comment by ClusterM** [comment]
I decided to move such minor features to mods. This has not been done by anybody yet...

**Comment by emmanuelfromhawaii** [comment]
ok, got it. that was a cool feature though. cleaner gui. otherwise, hakchi is awesome!

**Comment by ClusterM** [comment]
Finally:
https://www.reddit.com/r/nesclassicmods/comments/65s61w/mod_to_remove_thumbnail_bar_and_selector/ =)
