### ISSUE TITLE
[Enhancement] Offer different style of folder images

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#261]
It would be cool if we could choose in hakchi2 different style of folder image.
Here is the one I made. People can add theirs if they want to ask for putting them as an optional choice in hakchi2 too.

![folder_nes](https://cloud.githubusercontent.com/assets/26217893/24285389/1f653956-1070-11e7-9cb7-f5122f350957.png)
![folder_snes](https://cloud.githubusercontent.com/assets/26217893/24285392/1fc51ede-1070-11e7-951d-26fa50f83907.png)
![folder_n64](https://cloud.githubusercontent.com/assets/26217893/24285386/1f4fad34-1070-11e7-97e8-6ea251662d52.png)
![folder_gameboy](https://cloud.githubusercontent.com/assets/26217893/24285378/1ed59a12-1070-11e7-9955-9b8ac0e85e13.png)
![folder_gameboycolor](https://cloud.githubusercontent.com/assets/26217893/24285379/1edba81c-1070-11e7-9876-8bb0f304c606.png)
![folder_gameboyadvance](https://cloud.githubusercontent.com/assets/26217893/24285377/1ed4176e-1070-11e7-838b-c1d94f1e0992.png)
![folder_nds](https://cloud.githubusercontent.com/assets/26217893/24285387/1f5e0f14-1070-11e7-91b6-63242f32a52e.png)

![folder_master_system](https://cloud.githubusercontent.com/assets/26217893/24285384/1f2ca96a-1070-11e7-851b-3b9de92e563a.png)
![folder_megadrive](https://cloud.githubusercontent.com/assets/26217893/24285383/1f2c4a42-1070-11e7-8089-900e16d7f3a2.png)
![folder_saturn](https://cloud.githubusercontent.com/assets/26217893/24285393/1fca0fe8-1070-11e7-924e-b0c322e20180.png)
![folder_ps1](https://cloud.githubusercontent.com/assets/26217893/24285391/1f9c925c-1070-11e7-9350-a1948b7c480c.png)
![folder_atari2600](https://cloud.githubusercontent.com/assets/26217893/24285373/1ea67cbe-1070-11e7-9a50-1dd2e1f8f294.png)
![folder_neogeo](https://cloud.githubusercontent.com/assets/26217893/24285388/1f62ceb4-1070-11e7-9b5b-a14856184222.png)
![folder_arcade](https://cloud.githubusercontent.com/assets/26217893/24285372/1ea47f0e-1070-11e7-928a-e7d68505d7fb.png)

![folder](https://cloud.githubusercontent.com/assets/26217893/24285398/2023adb4-1070-11e7-9922-9abdc52ca406.png)
![folder_back](https://cloud.githubusercontent.com/assets/26217893/24285371/1ea1c732-1070-11e7-8b98-bd661f8b4fd2.png)
![folder_system](https://cloud.githubusercontent.com/assets/26217893/24285395/1fcd9366-1070-11e7-934e-bdcf7e486c3d.png)
![folder_favourites](https://cloud.githubusercontent.com/assets/26217893/24285375/1ec94370-1070-11e7-9134-6da82e3ac5fe.png)

![folder_pokemon](https://cloud.githubusercontent.com/assets/26217893/24285390/1f959fce-1070-11e7-8f7b-1dee44ae5ca4.png)
![folder_castlevania](https://cloud.githubusercontent.com/assets/26217893/24285369/1e9690b0-1070-11e7-834b-3b33c5ecd75c.png)
![folder_cave](https://cloud.githubusercontent.com/assets/26217893/24285370/1e9e926a-1070-11e7-8f84-089da2333222.png)
![folder_darius](https://cloud.githubusercontent.com/assets/26217893/24285368/1e867fe0-1070-11e7-85bd-9b333b2aca88.png)
![folder_donkeykong](https://cloud.githubusercontent.com/assets/26217893/24285374/1ec30db6-1070-11e7-86ae-e78209d95b34.png)
![folder_finalfantasy](https://cloud.githubusercontent.com/assets/26217893/24285376/1ed22198-1070-11e7-9113-ae296670ac75.png)
![folder_mario_mushroom_8bit](https://cloud.githubusercontent.com/assets/26217893/24285381/1f1b030e-1070-11e7-96f5-bb4138e11d9b.png)
![folder_mario](https://cloud.githubusercontent.com/assets/26217893/24285382/1f1eb7a6-1070-11e7-9ece-b7631a966139.png)
![folder_megaman](https://cloud.githubusercontent.com/assets/26217893/24285385/1f2e8d48-1070-11e7-887d-696c57e86db2.png)
![folder_zelda](https://cloud.githubusercontent.com/assets/26217893/24285396/2010794c-1070-11e7-892d-bc11ffe06d78.png)
![folder_1up](https://cloud.githubusercontent.com/assets/26217893/24285367/1e554e52-1070-11e7-8287-ed60656faacf.png)

**Comment by abijanfar** [comment]
Not an issue or enhancement request!

**Comment by black-pudding** [comment]
@abijanfar I've clarified my enhancement request.

**Comment by ClusterM** [comment]
Please read the folder_images\README.txt :)
