### ISSUE TITLE
Adding Modules Error

### ISSUE THREAD

**Issue by JPL0908** [ClusterM/hakchi2#263]
Trying to add Modules...running as Administrator on a Windows 10 box...keep getting an access denied error on "ash" or "busybox" located at C:\Users\<username>\AppData\Local\Temp\hakchi-temp\kernel\initramfs\bin.  When looking at the permissions, I get a message saying "The Permissions on the file are incorrectly ordered, which may cause some entries to be ineffective".  Changing permissions on the files or the folder doesn't help...same error message.  Any ideas?

**Comment by 1lokolo1** [comment]
Have you a Antivirus or similar program running/active?

Rgs.

**Comment by JPL0908** [comment]
Windows Defender is running. Put turning it off, then running add modules...same error.

**Comment by JPL0908** [comment]
What permissions do you see for C:\Users\<username>\AppData\Local\Temp\hakchi-temp\kernel\initramfs\bin\busybox?  Mine are NULL SID (Deny), Account Unknown(S-1-99-0) (Allow full control and Deny), and Everyone (Allow Read & Execute).  If I reset them, it just overrides them when I run add modules again.

**Comment by JPL0908** [comment]
This error message is also displayed when I try to Synchronize selected games.

**Comment by 1lokolo1** [comment]
Where are you running hakchi2?

Rgs.

**Comment by JPL0908** [comment]
Must have something to do with my user.  I created a new user, gave it admin rights, signed into the new user, and everything worked.  Thanks for the help.
