### ISSUE TITLE
Box Art Search not working

### ISSUE THREAD

**Issue by jaybepr** [ClusterM/hakchi2#265]
Hi, I have the v2.14b and all have been working perfect, out of no were the Google search for the Box Art is giving me an error ( Unable to connect to the remote server ). I can download the Box Art and Browse the file and it works, any idea on how can I fix this.  Everything else is working like a charm, super fast and stable.  Thanks in advance.

**Comment by ClusterM** [comment]
Please try this: https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems
