### ISSUE TITLE
Game Boy/Game Boy Color Games are cropped a bit at the top and bottom

### ISSUE THREAD

**Issue by scrcube** [ClusterM/hakchi2#266]
You see the energy, number of metroids, etc. cropped in half in Metroid II.

The same goes for Super Mario Land, the upper part where the number of lives is is cropped in half.

So in summary for Game Boy and Game Boy Color games the screen is cropped at the top and bottom.

**Comment by baconcow** [comment]
Wrong repository. Please see the [retroarch-clover repository](https://github.com/ClusterM/retroarch-clover/issues).

**Comment by scrcube** [comment]
Ok, just posted there and closed this issue.
