### ISSUE TITLE
Sega Master system games need to be unzipped to play them

### ISSUE THREAD

**Issue by dazford** [ClusterM/hakchi2#267]
As the title states, I was unable to play the sega master system games that were zipped with 7zip but if i unzip the individual games and add the unzipped files, the games work. 

Is this something that can be fixed in a future release?

Thanks for all the great work too :-)

**Comment by dazford** [comment]
I have tried to upload some files to assist you but it wont let me even though i have created a .zip file to do it. Let me know if there is another place or email address i can send files to you if you would like me to. ;-)

**Comment by KMFDManic** [comment]
Your 7zipped sms games may be 7zipped with an older version of 7zip that conflicts with the one the mini currently uses.  Adding them in standard zip compression should still render them workable. Rom sets in general like no-intro, etc, use normal zipping for archive purposes, never 7zip. Mine were standard zipped from no-intro. Try that:)

**Comment by dazford** [comment]
Ok I finally got home and tried to unzip every single game with WinRAR and then I rezipped every folder in.zip format. The same issues occurred. I might try doing the same process with the latest 7zip application to see what happens. 

I will also sus out no-intro as you suggested too ;-)

**Comment by dazford** [comment]
I've now updated to 2.15 and 0.7 for Hackchi2 and CloverApp when I tested this. Just as an FYI

**Comment by KMFDManic** [comment]
Try using no-intro sms set.

**Comment by KMFDManic** [comment]
If you still have issues, I can help you.  Sega master system runs great for me. Also, make sure you are using genesis plus gx hmod to run them.

**Comment by dazford** [comment]
I just tried the no-intro versions and so far no issues with the exception of Alex the kid bmx trials. There is no steering in that game. But that was the same in the other version I had too. 

Looks like no-intro works well even though I have done very little testing so far. The GoodSMS versions don't seem to work so well. They are very hit and miss with a lot not working without unzipping and choosing an exact game.sms file. 

Geez you are quick to reply. LOL 

Kudos to you for helping with this. I think using the no-intro sms set is the fix for this. :-)

**Comment by KMFDManic** [comment]
No intro is the fix for most retroarch emulators

**Comment by KMFDManic** [comment]
Alex Kidd BMX Trials, is meant to work with a paddle controller peripheral that originally came with that specific game.  It would likely require a special configuration or hack to run on the Mini.

**Comment by dazford** [comment]
Oh right, I never knew that. I might have to see if a custom config or hack is available :-)

**Comment by KMFDManic** [comment]
Be sure to close this issue, so clusterm knows it is fixed:)

**Comment by dazford** [comment]
Yeah I will. I just have a play around to make sure all is good then close it off. Hopefully this will help someone else too. Things look good so far though ;-)

**Comment by dazford** [comment]
No issues after testing quite a few games. Yaaaayyyy!!!
