### ISSUE TITLE
2.14b working great

### ISSUE THREAD

**Issue by DecanFrost** [ClusterM/hakchi2#268]
I pasted the 2.14b files over the existing 2.13e folder.  Added the updated clovershell mod file.

Installed drivers again. And had no problems installing all the ROMs and it was rediculessly fast like 1min. .. had a bit of graphics clicked on the entire screen but didn't factory reset and all was good

**Comment by baconcow** [comment]
Is this a comment to another issue that you had that has now been resolved?

**Comment by DecanFrost** [comment]
Just wanted to say it worked great that's all


________________________________
