### ISSUE TITLE
Question : can we 7zip .nes files?

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#269]
Can we 7zip .nes files?

**Comment by KMFDManic** [comment]
I posted my method of how to do it, as well as a batch method, a friend of mine did a tutorial for.  It is a relatively easy process and saves a lot of space.

How to add compressed NES games to NESC, mini tutorial.

https://www.reddit.com/r/nesclassicmods/comments/5w7hpf/how_to_add_compressed_nes_games_to_nesc_mini/

**Comment by black-pudding** [comment]
Thanks!
