### ISSUE TITLE
Crashes selecting game

### ISSUE THREAD

**Issue by 00arak00** [ClusterM/hakchi2#27]
I notice that when I select a game from the menu, it crashes when i use the start button.. and when I select a save state it crashes if I use the A button. anyone else have this trouble?

Refreshing with the tool does not help, only returning to original factory seems to resolve it.

**Comment by ClusterM** [comment]
Hi. You have this problem with all games? Or with one?
How much games you installed?
How exactly it crashes? Which error?

**Comment by baconcow** [comment]
Are you getting a black screen? When you power down the NESCE, are you getting a C8 error? If so, you have too many games and save states.

**Comment by 00arak00** [comment]
I was getting the c8 error on any game, funny thing is, i rereshed again to change games (did not reduce the number, just swapped) and not seeing it now lol

**Comment by baconcow** [comment]
This is definitely a limitation of the NESCE. As of 2.11, it has effectively been removed.
