### ISSUE TITLE
can't pack games!!!

### ISSUE THREAD

**Issue by aushey** [ClusterM/hakchi2#272]
having major issue with hakchi 2.14 All previous hakchi's work great on my computer, but everytime i try to upload games on my NES mini with hakchi 2.14 i get error can't pack games. Never seen this error before and not many people are having the same issue. Is it because i'm running windows 8.1?? or something else?? I'm completely lost, please help

**Comment by Lory955** [comment]
First of all try to chance USB port and re-install drivers. After this follow this steps:
1 flash original kernel and shutdown nes mini
2 flash custom kernel and shutdown nes mini
3 upload game

**Comment by CD0ug88** [comment]
I have the same issue: when I try to upload roms it give an error saying "can't pack games", then the nes classic disconnect e reconnect. I tried to flash original kernel, remove all hmods, flash custom kernel (without installing hmods) but it continue to spot the same error. 
![cantpackgames1](https://cloud.githubusercontent.com/assets/26663536/24331271/f1dcdc9c-1230-11e7-9333-36cfd7305d00.jpg)

**Comment by Mathbeach** [comment]
How did you add your other console game in hakchi that way??

**Comment by Mathbeach** [comment]
When i click add more games it only search .nes file

**Comment by ClusterM** [comment]
I'll remove games packing soon. Byt try this if you can:
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems

**Comment by insideone** [comment]
Тоже столкнулся с ошибкой. В дебаге получил это

```
Executing: C:\Program Files\hakchi2\tools\tar.exe
Arguments: -c *
Directory: C:\Program Files\hakchi2\temp\games
Errors:
C:\Program Files\hakchi2\tools\tar.exe: *** could not load netapi32, Win32 error
 0

Exit code: 1
reboot # exit code: 0
can't pack games   в com.clusterrr.hakchi_gui.WorkerForm.UploadGames() в d:\Proj
ects\C#\NesMini\hakchi_gui\WorkerForm.cs:строка 547
   в com.clusterrr.hakchi_gui.WorkerForm.StartThread() в d:\Projects\C#\NesMini\
hakchi_gui\WorkerForm.cs:строка 219
```
Скачал из инета netapi32.dll, но не помогло. Но если скоро запаковку уберут, и ладно :)

**Comment by ClusterM** [comment]
Fixed. Please wait for the next release :)
