### ISSUE TITLE
Enhancement : change the boxes of originals games 

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#273]
Would it be possible to change the art boxes of the 30 originals NES games?

**Comment by Driche** [comment]
You would have to uncheck the original 30 when syncing, load the 30 games with different roms that you find somewhere, then do the box art to match the rest of your set that way.

Sent from my iPhone

On Mar 26, 2017, at 12:04 PM, black-pudding <notifications@github.com<mailto:notifications@github.com>> wrote:


Would it be possible to change the box arts of games from the 30 originals NES games?
