### ISSUE TITLE
Storage problem (no space is left on device)

### ISSUE THREAD

**Issue by NesClassicNoob** [ClusterM/hakchi2#276]
I am using hakchi 2,14,when i try to surpass the 140mb marker and upload those games. It says I have no space left on the device which is wierd because 140 300mb is a weird gap. How do i fix this issue? I have already tried flashing the original kernel and that process but it still wont let me add more than 140.

**Comment by KMFDManic** [comment]
There is a memory limitation that Clusterm addressed and fixed for the next release.  The amount it affects you varies whether you have 32 bit or 64 bit operating system.  There are a few tricks you can do to increase the amount you can FLASH at, til that release.  I would need to know your setup, before I can suggest a path to follow for bypassing 140mb:)

**Comment by NesClassicNoob** [comment]
So hakchi 2.15 will have the space problem fixed? I'm fine with the space i have right now,still don't have a wii classic controller but was wondering what was up. But will it be fixed in hakchi 2.15?

**Comment by KMFDManic** [comment]
He has already fixed this issue.  It was confirmed when he closed another topic with this same issue:)  Patience, and hopefully we will get a release soon!

**Comment by KMFDManic** [comment]
I have the code for his fix. I will likely test things later today:)

**Comment by ClusterM** [comment]
KMFDManic, what are you talking about?

NesClassicNoob, something uses space on flash memory. You can use clovershell tool to check and clean fish memory.

**Comment by KMFDManic** [comment]
I am referring to the 32/64 bit memory limitation you fixed with flash memory.  I was assuming his issue was related to that.  Hmods installed, etc.

**Comment by KMFDManic** [comment]
Given he has all hmods removed, hakchi2 traces gone, and is using your next version with the memory fix...he shouldnt have a space issue.

**Comment by ClusterM** [comment]
Please try version 2.15. It will say what uses flash memory.

**Comment by NesClassicNoob** [comment]
Version 2.15 fixes this problem?

**Comment by piklz** [comment]
i just had this error on a sync list which works under 214b save config in 215 syasy i have no space to sync (but i have)

**Comment by KMFDManic** [comment]
I dealt with a couple others who had space issues.    And, I was able to resolve their problems.  You said you are on 2.15?  And, your micro USB cable....is it the one that came with the Mini?

**Comment by piklz** [comment]
hi its not the mini cable i use the samsung phone cable whic his working fine since beginning; this error seems to appear on windows 8 compat mode .. i put it back to windows 7 on the hakchi.exe i havent see n this error yet and its synced more games?

**Comment by ClusterM** [comment]
2.15 doesn't fixes this problem. It helps to understand what exactly uses storage space. I can't help you without full text of error message or debug log.

**Comment by piklz** [comment]
does that mean debug hakchi zip ..  i can try  sure

**Comment by NesClassicNoob** [comment]
Im using the cable with the system ill wait until tomorrow if you can figure something out do you think its the hmods?

**Comment by KMFDManic** [comment]
Ive been able to figure out what uses storage space, when I remotely connect to peoples computers and analyze their setup. I can help you guys out, if need be.  Clusterm did an amazing job.  But, a majority of conflicts are on the user end.  I can help resolve them.  Just let me know.

**Comment by KMFDManic** [comment]
Great job on 2.15 clusterm. I looked at the source and see where you made changes. Everything looks fantastic!  You have done an exceptional job, as always.

**Comment by ClusterM** [comment]
Use:

    clovershell.exe exec "du -h /var/lib"


To calculate how much flash space uses every folder.

**Comment by NesClassicNoob** [comment]
Ill send you a picture when I can figure out how to screenshot on a laptop :P

**Comment by KMFDManic** [comment]
Thanks for that!

**Comment by NesClassicNoob** [comment]
![no storage on device](https://cloud.githubusercontent.com/assets/26529933/24484478/6bd590e6-14cc-11e7-8abf-06d0837a5d8c.JPG)

**Comment by KMFDManic** [comment]
You Try 2.15 yet?

**Comment by NesClassicNoob** [comment]
No but I will tomorrow, though I doubt this problem will be solved. Let me know if you find anything.

**Comment by CaptDreamer** [comment]
I have the same issue and have tried 2.15. Assistance would be appreciated

**Comment by ClusterM** [comment]
CaptDreamer, same request: full text error (just copy-pasted via Ctrl+C, screenshot not required) or debug log (https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems).
And output of 

    clovershell.exe exec "du -h /var/lib"

if possible (it will solve problem instantly). You can download clovershell there: https://github.com/ClusterM/clovershell-client/releases

**Comment by youngtune27** [comment]
I just had this issue too these last few days have been driving me nuts. Couldn't get past 85mb. I tried some stuff then couldn't get past 95. Then I tried getting a fresh new hakchi and uninstalled mods and resetting to factory settings flashed custom and it true 114 and still didn't work. Always an error, then I unchecked the 30 original games and tried to sync 114 and it worked. So tried to add a few more games and it would error again. So I decided to try something else. I uninstalled mods and then I completely uninstalled hakchi from my mini through the hakchi program. Which I didn't do before. Then I reflashed original kernel. Then I turned system on and factory reset it again. Then I flashed custom kernel. Added my games again and tried 114 with original 30 and it worked!! Got up to 137mb last night and it was still working! Then I upgraded to 2.15 today and I'm at 191 my. All working good.

**Comment by NesClassicNoob** [comment]
@youngtune27 can you try 270 please and let me know the results?

**Comment by KMFDManic** [comment]
@NesClassicNoob and @youngtune27 and whomever else, I am pretty sure I can help you fix the out of space error.  I am u/MDFMKanic on REDDIT.  Send me a private message there and I will try to help you get closer to 299mb:)  I have helped over 300 others flash or fix Mini Nes/computer conflict related issues since the advent of hakchi2 software.

**Comment by DecanFrost** [comment]
I currently have 296mb used out of 300mb (according to v2.14b) in v 2.15 It reports as 316mb used ouf of 335mb

its the same game folder just with either version set up it reports 2 different sizes. either one loads perfectly fine, but im going to test it to the full 335mb tonight.

However when I first install 2,15 I was having major issues, even with a fresh install.. I had to delete clovercon.hmod again and reinstall the 2.15 over top and then seemed to work and driver issues went away also that strangly appeared over night while i was still on 2,14b

**Comment by youngtune27** [comment]
What results. So far what I did worked. I've got 192 and have no issues. Haven't tried to go more than than that. But I couldn't get past it 85. So try uninstalling hakchi completely from your nes. It seemed to work for me

**Comment by youngtune27** [comment]
My bad I didn't see you ask me to try 270 lol my bad. Yes I can try I will have to fine 80mb worth of games throw on.

**Comment by NesClassicNoob** [comment]
![stupid space problem](https://cloud.githubusercontent.com/assets/26529933/24522441/92c7c0d4-155d-11e7-921e-afbe0fb3a1e1.JPG)

Tried Hakchi2.15 and factory reseting after flashing kernel

**Comment by KMFDManic** [comment]
The problem here, is you are trying different things...but, you are not actually analyzing the space and how memory allocates files.  I knew exactly how much space I had free when it ran out of memory/space.  That is the "key" to pinpointing the problem:)

**Comment by KMFDManic** [comment]
One person who had this issue.  I remotely connected to him, and his previous traces of retroarch made his mini act as if it was at 4 gb out of 300mb, and, of course failed.  But, i was able to revert that misread of 4gb and fix things on his end.  Once you realize where the space/memory conflict originates from..or send logs to clusterm..it will help get things fixed that much faster.

**Comment by NesClassicNoob** [comment]
![another issue](https://cloud.githubusercontent.com/assets/26529933/24525392/0d7008b4-1568-11e7-9b24-25f234a058b0.JPG)

I accidently changed my clovershell into a notepad file how do i fix this?

**Comment by youngtune27** [comment]
I got both errors just like you. It didn't change to notepad file. It's just another error. Trust me I got BOTH those as well. Did you uninstall hakchi from inside hakchi? Like actually uninstall it. That's what I had to do. Don't just reset settings on system and reflashed custom. Click uninstall hakchi. And do that.

**Comment by NesClassicNoob** [comment]
No i deleted it put in recycle bin and delete it from there. Do i have do uninstall within hakchi?

**Comment by youngtune27** [comment]
What you did didn't do anything at all. Yes! Make sUre you have your factory dump moved over and then Open up hakchi. Uninstall all mods. Then under one of the tabs up top has uninstall hakchi in it. It completely wipes it clean. Click Uninstall hakchi. Then let it do its thing. Then Flash original kernel. Then Turn system on and factory reset it. Then flash custom kernel. Then add your mods and games. That's what I did to fix it.

**Comment by youngtune27** [comment]
You may have to get your factory dump from the recycling bin if you recycled you're hakchi folder

**Comment by NesClassicNoob** [comment]
Do i reinstall hakchi when i uninstall?

**Comment by youngtune27** [comment]
That's what flashing custom kernel does. But just follow my steps. But no There is not install button just a uninstall one.

**Comment by KMFDManic** [comment]
I went over all of these steps on the memory exception bug report.  There are a few additional ones for this one. But, they are fixed roughly the same way:)

No hmods and no hakchi2 traces and no save states...then analyzing the logs to see if anything still takes up space.  Then, you should be able to do 299 mb or so:)

**Comment by NesClassicNoob** [comment]
So i just uninstall hakchi2 right? that would delete everything?

**Comment by NesClassicNoob** [comment]
@youngtune27 no i mean when i uninstall i have to go back on this website and reinstall it

**Comment by youngtune27** [comment]
No you don't have to get back on this website. It just uninstalls hakchi from your mini. Not from the computer. Don't Delete it from the computer just Uninstall from inside hakchi. Program stays there you don't even have to exit. So uninstall mods then uninstall hakchi and follow the steps. All in the same opened hakchi.

**Comment by KMFDManic** [comment]
Uninstalling hakchi2, will NOT remove everything.  You are missing steps:) This space issue, I have already resolved for a few others on Reddit.  Clusterm HAS given us the means to see where the space is being taken up.  You just have to utilize it:)

**Comment by youngtune27** [comment]
YES it will. If you uninstall all mods. Uninstall hakchi. Then flash original kernel. Then reset system to factory settings. Then flash custom kernel. Then add yours mods and games. How you gonna tell me this don't work when I just did this? And it WORKED. I couldn't get past 85. But not it's not an issue. So again how you gonna say his won't fix the problem when it just did fix mine?

**Comment by KMFDManic** [comment]
Haha, you obviously have NOT read my input on this issue in 2.14b.  The steps you posted, are EXACTLY the ones I said to do!  But, there are OTHER variables that can ALSO cause you to lose ability to flash at 299mb.  Those are the steps I am referring to:)  Uninstalling hakchi2 DOES not not always work out as a go to solution to fixing issues with the NES Mini.  Many have absolutely NOTHING to do with the Mini...but the operating system you are working with.  That is, more or less, what I am saying.

I have also posted that I was ABLE to fix this issue for you guys, literally since this topic was opened:)  I already KNEW the means and how to, since I figured it out in 2.14b.

I am here to help others FIX their Nes Minis, so we can all enjoy them, alike.  I have already been through this issue, and the solution was an easy one:)

**Comment by KMFDManic** [comment]
My Reddit post with a link to the bug report, with my testing and solution to the memory error, last week.  The only thing I couldn't fix was x86/32 bit, since ram optimization was not very good for that:)  But, clusterm, said it should be fixed in 2.15.  Otherwise, the steps you followed, and the ones I previously posted about,,,worked great.  

https://www.reddit.com/r/nesclassicmods/comments/6126k8/mac_users_with_214b_this_post_is_for_you_windows/

**Comment by youngtune27** [comment]
Okay make sense lol :)

**Comment by KMFDManic** [comment]
Yes, it is very easy to say one thing works!  Like, you add gas to a car that breaks down, then it moves a mile.  BUT, then the radio dies, and you realize your alternator or battery might be an issue.  Never expect the quickest solution to be the easiest:)  There will be OTHER issues that you need help with.  I am on Reddit, and have pretty much sorted out almost every potential issue you can have with these awesome devices!  So, feel free to visit https://www.reddit.com/r/nesclassicmods/  I am u/MDFMKanic  there, and I check between HERE and THERE, quite often...doing my best to help fellow enthusiasts:)

**Comment by youngtune27** [comment]
Well I'll be hitting you up if I have issues again lol

**Comment by NesClassicNoob** [comment]
Really i just tried your way and it works! 230 Mb it works! I love you @youngtune27 !!!

**Comment by KMFDManic** [comment]
Haha, I have been fixing computers for over 20 years now.  The stuff you can NOW do on the Mini, I have been doing on PCs, as far back as Windows 98:)  The space issues, are common with computers in general, when using TAR to work with file transfers.  Even on a phone, you may download an update that is 800mb, but it won't allow you to do it unless you have 2 gb free.  See where I am going with this:)  And, @NesClassicNoob if you would have seen my earlier message offering to help you...it wouldn't have taken you this long to FIX your issue:)

**Comment by NesClassicNoob** [comment]
Im sorry @KMFDManic wasn't listening because you wern't giving me specific steps. I thank you all for helping me with this problem. I am now closing the forum. If you have this situation to follow @youngtune27 and read his steps it fixed my issue. If I would need any more help because of problems i will create a new forum. Have an awesome day everyone. And lets pray for more updates,better emulation, and some more storage space somehow!

**Comment by youngtune27** [comment]
@nesclassicnoob hell ya bro! I'm glad it worked for you too :)

**Comment by ZeldaGeek** [comment]
I have the same problem, but it's with v2.21

**Comment by Drakonas** [comment]
..... @ZeldaGeek please ask on https://www.reddit.com/r/miniSNESmods instead of responding to 8 month old tickets, especially one that has been resolved with a patch from Cluster. You are definitely dealing with something else.
