### ISSUE TITLE
Translation Spanish of Spain incomplete (version 2.15)

### ISSUE THREAD

**Issue by NaikiTurincondeliphone** [ClusterM/hakchi2#277]
Hi Cluster, I´m Naiki, the translation does´n apply to 100%, the translation the UI of program no change, but the popups yes (Version 2.15).

Example 1: https://fotos.subefotos.com/3f2b3764a38f4facec0223e8989b5156o.png
Example 2: https://fotos.subefotos.com/875f4c779da819630cb24bd1ab816293o.png

Thanks!

**Comment by ClusterM** [comment]
Oops. Please redownload it now.

**Comment by NaikiTurincondeliphone** [comment]
Ok, UI apply correct now, but there are still some things that have not been apply:

Example 1: https://fotos.subefotos.com/e36b4e641c3b281e45f5622f41aa7e24o.png 
Example 2: https://fotos.subefotos.com/5bb78a95754e6fdb1f26b2e8f1c6f215o.png

And example 3: https://fotos.subefotos.com/afb5fcdad14441f10e1c38f119fa6de5o.png (fixed in doc Google) 

Sorry and thanks

**Comment by ClusterM** [comment]
Please redownload again :)

**Comment by 1lokolo1** [comment]
I think It's solved. I download about 4-5 hours later of the release of 2.15 and I have the menu all translate in Spanish. 

Thanks a lot!

**Comment by NaikiTurincondeliphone** [comment]
I found four examples where it has not been translated into Spanish:

Example 1:

![nes_about](https://cloud.githubusercontent.com/assets/20205678/24513016/732b620e-1570-11e7-8fd4-e8d04d12d451.png)

Example 2:

![nes_cover](https://cloud.githubusercontent.com/assets/20205678/24513035/7b08c868-1570-11e7-85a7-24e1eeac934d.png)

Example 3:

![nes_google](https://cloud.githubusercontent.com/assets/20205678/24513049/858a6ab2-1570-11e7-99d7-55b1585236fd.png)

Example 4:

![nes_files](https://cloud.githubusercontent.com/assets/20205678/24513064/8ea99708-1570-11e7-8549-1352fa6bd263.png)

I add new strings to "hakchi2 - translation project"? Or is it not necessary?

I think it's all over, sorry for the inconvenience, but I'm a perfectionist. :)

---------------------

@1lokolo1 Soy AmbusHNaiki, te he comentado en YouTube de vez en cuando, si ves alguna errata en hakchi2 v2.15, me lo dices y lo modifico el Doc original.

**Comment by NaikiTurincondeliphone** [comment]
Hi, I found one example:

Example 1 (fixed in Doc - hakchi2 - translation project):

![word](https://cloud.githubusercontent.com/assets/20205678/24553423/83c364d0-162a-11e7-9993-163a17a12ea6.png)

This is a coupling error:

![acople](https://cloud.githubusercontent.com/assets/20205678/24553488/a66cbc34-162a-11e7-9c20-ab5d6924eff4.png)

Thank you very much :)

**Comment by ClusterM** [comment]
I fixed "Release date" bug and added new strings to translation sheet: https://docs.google.com/spreadsheets/d/1yrXH-6g61klKmuXTVf3f0ah8DCQObu-9YEJRoWTeuik/edit?usp=sharing

**Comment by NaikiTurincondeliphone** [comment]
OK thanks.

Translated new lines

PS: Missing strings:

- Filter name for file select dialog: "Images" (Imágenes) - String 209
- Title for Google images select dialog "Google images" (Imágenes de Google) - String 210

I added the new strings to Doc :)

**Comment by NaikiTurincondeliphone** [comment]
Done all!

**Comment by PATWIST** [comment]
Thanks Naiki for founding this untranslated text. Now it is in Google docs :-)

**Comment by PATWIST** [comment]
Wow, @NaikiTurincondeliphone you are a good perfectionist to fin all of these :-)
@ClusterM Thanks for creating Google docs for translation. 1. april I translated it and in v2.16 I found my translation includes in hakchi :-) :+1:

**Comment by PATWIST** [comment]
Wow, @NaikiTurincondeliphone you are a good perfectionist to fin all of these :-)
@ClusterM Thanks for creating Google docs for translation. 1. april I translated it and in v2.16 I found my translation includes in hakchi :-) :+1:

**Comment by PATWIST** [comment]
Wow, @NaikiTurincondeliphone you are a good perfectionist to find all of these :-)
@ClusterM Thanks for creating Google docs for translation. 1. april I translated it and in v2.16 I found my translation includes in hakchi :-) :+1:
