### ISSUE TITLE
Mame2003 sound missing in parts of game

### ISSUE THREAD

**Issue by vinnyl69** [ClusterM/hakchi2#278]
came across an issue while playing donkey dong and dk jr, the sounds are not all there.  when mario walks the sound is not there and when he jumps the sound is not there unless it is over a barrel.    in Jr, similar, no sound when climbing the vines or jumping unless over something.     roms have sound when played on windows laptop.

**Comment by black-pudding** [comment]
You should instal the bios_images.hmod that you find [here](https://github.com/kaz321123/Mame-Support-Files) to solve the problem. It adds the samples needed by some games under mame2003 to the NES mini's system.

**Comment by vinnyl69** [comment]
can you give some guidance how to install??  i a new to this...  thanks!!!

**Comment by ClusterM** [comment]
Sorry but RetroArch repository is in another castle.

**Comment by vinnyl69** [comment]
not sure what you mean, sorry.  i have the nes up and running. i just do not see how to upload the bios_images.hmod

**Comment by vinnyl69** [comment]
figured it out.
