### ISSUE TITLE
Save state "floating wing window" not showing up when exiting back to the NES Classic menu

### ISSUE THREAD

**Issue by sceptre2k3** [ClusterM/hakchi2#279]
Background of my system:
- hakchi2 2.15 + new retroarch clover (0.7)
- have 283MB of games uploaded

I experience intermittent issues with the save state "floating wing window" not showing up when exiting back to the NES Classic menu.

What seems to be happening is when I go back to the NES Classic too quickly after the game loads (either on first load when selecting the game or when loading a save state), I end up back at the menu but there is no "floating wing window" to save or to resume the game. This is reproducible pretty much all the time for various retroarch systems (NES, Super NES, Genesis).

There is a workaround that seems present: I've tried this experiment by loading the game, waiting ~5-10s, then going back to the menu, and the "floating wing window" more consistently shows up.

I tested with the original 30 games (exit back to the menu as soon as the game loads), and the issue does not appear.  This seems to indicate it is a retroarch-clover issue (new state zipping maybe?).  Don't know if this is a (new) real issue, or something just inherent with the retroarch-clover design.

**Comment by lil-diabo** [comment]
This needs to be moved to retroarch-clover repo

In any case, I think, by default retroarch autosaves after 10 seconds
Change the line in retroarch.cfg 

autosave_interval = "10" to whatever value

**Comment by KMFDManic** [comment]
You may actually be PAST your Flashing Memory limit for games.  If you pass the limit, HMODS will be funky and not register properly.  You can test this by looking at your Memory Use within the log report, as well as flashing with FEWER games.  I had the same issue when I flashed TOO many games.  Once I cleared the junk off the NES Mini, and was within realm of what I should be flashing at, the save states worked again.  You can possibly have retroarch or hakchi2 traces bogging down your Mini.  Or, even just too many save states!

**Comment by Mathbeach** [comment]
Im having exact same issue but the floating wing never there when exiting retroarch only have 80 mb of 300 used??

**Comment by ClusterM** [comment]
This is not RetroArch repo.
