### ISSUE TITLE
No saving the newly added gamelist and box arts?

### ISSUE THREAD

**Issue by Jepplen** [ClusterM/hakchi2#280]
Hi, I've added a bunch of games for the famicom mini, but a lot of the box arts were wrong so I've redone a lot of them myself as many don't exist intheir pure form on google and plan to do all of them.
I haven't flashed my FC mini yet.

Is there a way to save the current list of games and box arts in Hakchi2 to a file of some sort?
And to be loaded in another Hakchi2, I was thinking of maybe uploading it for other like minded Famicom fans like myself.
Besides, I would cry if all of them dissappeared.

Cheers!

**Comment by KMFDManic** [comment]
GAMES folder in hakchi2.  Make a copy of that.

**Comment by Jepplen** [comment]
Thanks!
