### ISSUE TITLE
Denied path

### ISSUE THREAD

**Issue by biohazard901** [ClusterM/hakchi2#281]
I get this error Access to path "chakan bin" is denied. Cant add any games or uninstall or nothing any idea how to fix this?

**Comment by KMFDManic** [comment]
I can help you fix it via teamviewer if you're still stuck.

**Comment by biohazard901** [comment]
Thanks for offering help it seems though that after messing around with it it now works again. Thanks again.

**Comment by KMFDManic** [comment]
Good to know. It was an easy fix.  But, there are a dozen things that can cause it;)
