### ISSUE TITLE
Memory loss for games on 2.15, Famicom games not working.

### ISSUE THREAD

**Issue by darksaga** [ClusterM/hakchi2#282]
I've detected various issues on 2.15 version, but the worst one is the impossibility to work certain Famicom games from 2.14 version. Games like Wai Wai World 2, Dragon Ball Shenlong no nazo or Crisis Force that where working on versions 2.13 and earlier now doesn't work.

The second is a memory loss for the games on 2.15. Previous versions down to 2.14 have 300 MB left for games. Now, I only have access to 284 MB, with exactly the same cores installed from previous versions.

**Comment by KMFDManic** [comment]
I use fceumm core for those famicom games.  At end of command line --fceumm --retroarch

For memory loss, you need to uninstall hakchi2, uninstall hmods, revert to original kernel, flash custom kernel. Save states can also be deleted by choosing factory reset options on the Nes Mini, itself. If you have cleared everything properly and have No hmods or hakchi2 traces.  Then, flashing should work at 299mb.  Ive helped 11 people do this already.

**Comment by ClusterM** [comment]
You can't run games like Wai Wai World 2, Dragon Ball Shenlong no nazo or Crisis Force on original emulator. If you have issues with RetroArch, create issue report in RetroArch repo.

Version 2.15 shows **real** free space on writable partition (e.g. free space + size of installed games - reserved 10MB). While 300MB is average, not correct size. It you want to free some space, use clovershell tool.
