### ISSUE TITLE
Error using version 2.15

### ISSUE THREAD

**Issue by jaguarx8s** [ClusterM/hakchi2#283]
I see the following when attempting to sync my NES 
![image](https://cloud.githubusercontent.com/assets/26830929/24575403/99603b18-1659-11e7-9ea7-a78104a6f18c.png)

**Comment by THE-PBV** [comment]
Thats Normal  your NES does not have the original kernel and you are updating from 2.14B of older.
hakchi2 is checking the MD5 from the original kernel.

just klik next ;)

**Comment by NesClassicNoob** [comment]
You have to flash the original kernel from your previous hakchi or move the kernel over
