### ISSUE TITLE
Issue trying to find games to add

### ISSUE THREAD

**Issue by jaguarx8s** [ClusterM/hakchi2#284]
Here is what happens when I go back and hit add games, there is nowhere that it shows me where to find the game names etc.  
![image](https://cloud.githubusercontent.com/assets/26830929/24575488/afbf6828-165b-11e7-8b9c-9cfc1f91aabe.png)

**Comment by KMFDManic** [comment]
You have to HAVE the games on your computer's hard drive, then select from whichever directory they are in.  They do not come with hakchi2.

**Comment by jaguarx8s** [comment]
How do I download the games first?

Thank you

On Apr 1, 2017, at 2:19 PM, KMFDManic <notifications@github.com<mailto:notifications@github.com>> wrote:


You have to HAVE the games on your computer's hard drive, then select from whichever directory they are in. They do not come with hakchi2.

**Comment by KMFDManic** [comment]
Yes, you have to "find" the games, first.  Google is your friend:)  I suggest searching for certain key words:)  

Data that is dumped from an NES Cartridge, would be considered a ROM.  If you made it far enough to get hakchi2 installed, I have absolute faith in your ability to make it the full way:)
