### ISSUE TITLE
Need to Reset Settings

### ISSUE THREAD

**Issue by raccoonmario3** [ClusterM/hakchi2#286]
I accidentally set the scale for a shader I was using to 4x, which crashed the emulator. It saved that setting, and now when ever I try to load NES games from Nestopia, I get kicked back to the menu every time. I cannot disable this setting from within the Retroarch icon on the menu, since changing shader settings requires having a game loaded, which crashes the emulator. I tried uninstalling and reinstalling the retroarch .hmod file, but nothing changed. It seems that the settings are being stored somewhere other than in the libretro folder on the NESC's internal memory, in a place that I cannot find or modify. I even tried removing the shader from the Retroarch .hmod file before flashing it, but it still crashed.

I was using this .glsl shader:

https://www.reddit.com/r/nesclassicmods/comments/62uq7h/nes_mini_crt_filter/?st=j0zxbafg&sh=6da41097

Which I downloaded from here:

http://s000.tinyupload.com/index.php?file_id=46847242796620959105

**Comment by KMFDManic** [comment]
Uninstall hakchi2, revert to original kernel, flash custom, reinstall hmods.

**Comment by KMFDManic** [comment]
One other person I helped did this exact same thing.  In his case, he had to uninstall the compromised hmods, after reinstalling them.  

This method, I posted above, was what I did with another recent issue someone had.

**Comment by KMFDManic** [comment]
You can, alternately, use...

--retroarch -fceumm

For the time being, til this is resolved.

Main thing is, whatever hmod you installed, with the shader included.  Install it again, then remove that one.

**Comment by KMFDManic** [comment]
--retroarch --fceumm

Sorry, on phone, unable to edit:)

**Comment by raccoonmario3** [comment]
Is there any way to preserve my saves and/or save-states, or will they be lost if I go back to the original kernel?

**Comment by KMFDManic** [comment]
When you go back to original kernel, it tells you to "factory reset" settings on NES Mini to remove saves.  I cannot guarantee your saves will be safe.  But, that indicates they may.

**Comment by KMFDManic** [comment]
I would, for now, switch to fceumm core if you're worried.  Or, try to reinstall, exactly...the retroarch hmod that screwed things up.  Then, immediately uninstall it. Then, take a fresh, new copy of retroarch hmod and install..then test:)

**Comment by raccoonmario3** [comment]
I solved the problem by uninstalling the Retroarch .hmod, and then installing the newest version. I even got to keep the saves.

**Comment by KMFDManic** [comment]
Awesome!
