### ISSUE TITLE
Long filenames uploading problem

### ISSUE THREAD

**Issue by ClusterM** [ClusterM/hakchi2#287]
Yes, I'm creating issue for myself :)
Very long filenames trancated while uploading to NES Mini on version 2.15.
I know about it, will be fixed soon.

**Comment by KMFDManic** [comment]
jack_nicklaus__greatest_18_holes_of_major_championship_golf.7z

Is probably the longest titled game I have.  I have not even checked to see how it displayed on the Mini.  Do you have an example of one that is truncated, or a character limit?

**Comment by ClusterM** [comment]
KMFDManic, "Gourmet_Sentai_Barayarou__Japan___En_by_Aeon_Genesis_v0.80____Gourmet_Squadron_Barayarou___Incomplete_.sfc.7z " is truncated. Original tar supports only 100 characters in path.
