### ISSUE TITLE
Problems adding 4 player mode games and mapping issues.

### ISSUE THREAD

**Issue by Akriloth** [ClusterM/hakchi2#288]
The following below are the games that I have trouble adding to Hakchi2 because of either 4 players or some form of mapping. The left will be the game and the right of it is the issue.

Action 52 - mapper #228 
Batman: Return of the Joker - mapper #69
Contra - mapper #23
Deadly Towers - mapper #241
Dragon Power - mapper #66
Gauntlet - four screen mode
Goal Two - mapper #118
Gumshoe - mapper #66
High Speed - mapper #119
Impossible Mission - mapper #34
Mach Rider - four screen mode
Mr. Gimmick - mapper #69
NES Play Action Football - #118
Nintendo World Championships 1990 - mapper #105
Pin Bot - mapper #119
Pro Sport Hockey - mapper #118
Racermate Challenger II V6.02.002 - mapper #168
Rad Racer 2 - four screen mode
Summer Carnival 92: Recca - mapper #220 
Thunder & Lightning - mapper #66
Videomation - mapper #13

If anyone knows the fixes for these please let me know. Other than a few games that I can live without (about 3-5) I will have all of the NA games.

**Comment by baconcow** [comment]
Contra (USA) should work fine on the NESCE emulator. The others are likely not supported and will require one of the two NES emulators available in the retroarch module for hakchi2. [Goto this repository](https://github.com/ClusterM/retroarch-clover/releases/tag/0.7) and read about that.

**Comment by ClusterM** [comment]
> because of either 4 players

What?..
