### ISSUE TITLE
No games showing

### ISSUE THREAD

**Issue by hovdogjay** [ClusterM/hakchi2#29]
Added about 60-70 games to go to a total of about 150 or so with the 30 hidden.
When it starts, I only get the overlay screen with BGM playing and at the top it says "GAME TITLE"
When I remove all the new games I added and go back to my game list from 2.10, there's 2 folders that only refresh the 1st 30 games instead of taking me to the next set of games

**Comment by ClusterM** [comment]
Hi. Please redownload  latest version and try again.
