### ISSUE TITLE
Cant unpck the ramdisk

### ISSUE THREAD

**Issue by SamBuijar** [ClusterM/hakchi2#291]
Hi first cluster thanks for the awesome mod and hakchi2 i been using this a couple of days and one day fail and the hakchi2 2.13 when i press synchronise games say cant unpack the ramdisk and now the nes doesnt turn on , please help me

**Comment by SamBuijar** [comment]
Yes

**Comment by ClusterM** [comment]
Can you try debug version? https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems
Seems like you need to put your NES Mini into FEL mode and reflash.

**Comment by SamBuijar** [comment]
![r](https://cloud.githubusercontent.com/assets/26920200/24729232/51876788-1ab1-11e7-94ff-61b72ceeb59c.png)

**Comment by ClusterM** [comment]
SamBuijar, https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems

**Comment by SamBuijar** [comment]
Thanks for solving the problem and talk with a legend 
and thanks for let me play all my old nes, snes and sega genesis games

**Comment by SamBuijar** [comment]
![image](https://cloud.githubusercontent.com/assets/26920200/24738195/33a0bcec-1ae8-11e7-886f-12d5a61df2e1.png)
