### ISSUE TITLE
Please add support for using Y/B as B/A on the classic controller.

### ISSUE THREAD

**Issue by nl255** [ClusterM/hakchi2#292]
If it isn't too much trouble, it would be nice to be able to use the Y button as the NES B button and the B button as the NES A button on the classic controller.

**Comment by KMFDManic** [comment]
You can already do this if you install retroarch, go into settings, and remap:)

**Comment by nl255** [comment]
Except that to make that work you would also have to force the use of retroarch for all games since that setting will have no effect on the nesc emulator.

**Comment by KMFDManic** [comment]
Hehe. I prefer nestopia and fceumm to the default emulator.  But, I guess it is a matter of preferencem

**Comment by nl255** [comment]
It also means having to restart a bunch of games from scratch since there is no way I have found to import/export the sram save files.  Backing up and restoring is no problem but that seems to be it until someone figures out the save format.

**Comment by KMFDManic** [comment]
Clovershell hmod and client allows you to import and export save files.  It is a little advanced.  But, it works!

**Comment by nl255** [comment]
Backup and restore yes, but not transferring sram saves between nestopia/nnnesterj/etc and the default emulator.  The cnes emulator seems to use it's own sram format and is a 33kb file.

**Comment by KMFDManic** [comment]
How many games are you heavily invested in, save wise.

**Comment by TonyVN2** [comment]
Can I ask you a question? What kind of controller you use to play SNES games? I am not able to play because I can not use ,X,A button with my controller

**Comment by KMFDManic** [comment]
Wii pro!  I love it!

**Comment by TonyVN2** [comment]
Thank you! I will try to get one

**Comment by nl255** [comment]
Fine, you win.  I will just use retroarch and start all my games over from scratch.
