### ISSUE TITLE
Can not use SNES class controller (with the SNES/NES converter adapter)

### ISSUE THREAD

**Issue by TonyVN2** [ClusterM/hakchi2#293]
Hello, 
First of all, thank you a lot for your hard work. I have an issue with the controller as mention above: Can not use SNES class controller (includes the SNES/NES converter adapter) in SNES games (RetroArch). I only can use Y,B button only, the X,A cannot use. 

Is there any chances can you help me out?
Many thanks

**Comment by MattMan76** [comment]
You can try pressing Select and Start at the same time while in a SNES game, then go to Settings, Input, Input User 1 Binds. If the Button Number doesn't change for the different buttons when you press them there I think it means that your Adapter isn't compatible with the NES Mini.  Do you have the version of the Adapter that actually says "NES/SNES Controller Adapter for NES Classic and Wii U/Wii" on the top of it?  The older model doesn't work.

**Comment by TonyVN2** [comment]
Yes it does say on that Adapter. It's ok now I am using Wii classic controller. Thank you for helping again
