### ISSUE TITLE
Enhancement : Enable Internet connexion

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#294]
With a powered usb hub or such?

**Comment by ClusterM** [comment]
NES Mini can't work as USB host.

**Comment by black-pudding** [comment]
Or with a custom WiFi adapter on Player 2 gamepad's plug?

**Comment by ClusterM** [comment]
It's better to use USB if you want to connect NES Mini to external world :) NES Mini can't work as USB host but can work as USB client. So it's possible to create some host device to share files in theory .
