### ISSUE TITLE
Game Synchronization Interrupted - Writable Memory = 0.0mb

### ISSUE THREAD

**Issue by goombah111** [ClusterM/hakchi2#295]
Please help, heres a picture 
http://imgur.com/a/MSLsQ

computer died from power outage halfway through sync, now i get this when i try to add games.

everything is as it was before the sync but i cant add new games. or remove any for that matter.
i have it hacked, ive done it a lot. but now im screwed.. :(

**Comment by goombah111** [comment]
i guess i shouldnt have freaked out before trying everything. all i needed to do was re-extract hakchi (2.15) and start from scratch. Hope this helps anyone who has the same problem.

**Comment by ElusivSanity** [comment]
@goombah111 can i ask what your setup was? On a pc with windows or using vmware vbox?
