### ISSUE TITLE
Emulation Issues: Star Wars and Star Wars Empire strikes back

### ISSUE THREAD

**Issue by Phantom-Blood** [ClusterM/hakchi2#296]
Hi there!

Really grateful for your amazing software for NES mini. Have a couple of issues with games though. Star Wars for NES misplaces the textures, so you may see a platform but when you jump on it you go through. Pausing and unpausing the game fixes that, but only till the screen scrolls. Empire strikes back has a simillar problem, but not on such a scale, as the first game.

Would appreciate any help! Thnx!

**Comment by baconcow** [comment]
hakchi2 is not an NES emulator and this repository does not deal with ROM issues. The [retroarch-clover](https://github.com/ClusterM/retroarch-clover/releases/tag/0.7) repository provides two additional emulators for NES ROMs that may help with those games where the NESCE's emulator may have issues. Also, ensure you have compatible ROMs. The [Reddit compatibility thread](https://www.reddit.com/r/nesclassicmods/comments/5mpyxg/is_my_rom_x_working_megathreadconsolidation/) may be the best place to discuss ROM issues.
