### ISSUE TITLE
Enhancement : wallpapers

### ISSUE THREAD

**Issue by black-pudding** [ClusterM/hakchi2#297]
It'd be cool to have a 720p PNG wallpaper for each game to cover the usual black stripes. Like in _Megaman legacy collection_ for example. It'd be put 7zipped in the game directory.
We could also have the box art of the game as wallpaper by default if the option "wallpaper" is ticked.

**Comment by piklz** [comment]
this is called overlays for retroarch very simple to use,

**Comment by black-pudding** [comment]
Thx I'll try it.

**Comment by black-pudding** [comment]
OK I get it. Indeed it's super easy to use.
