### ISSUE TITLE
Nes wont play games that are loaded

### ISSUE THREAD

**Issue by and1a1** [ClusterM/hakchi2#299]
I downloaded roms and uploaded them to hackchi 2.0.15.10.  I then checked all the check boxes, connected my nes classic and pressed "synchronize selected games to mini".  I followed instructions, installed driver then the games uploaded and it said "done"  I plugged my nes to tv and games show with box art as if they would work but when i click "a' to play game and the screen goes black for a few seconds then defaults back to the game selection menu, this applies for all games uploaded from hackchi.  not sure how to make it work

**Comment by KMFDManic** [comment]
You need to install retroarch hmod:)

**Comment by SamBuijar** [comment]
I did it and the snes/genesis games work but if press the reset bottom ,doesnt create a suspend point

**Comment by and1a1** [comment]
How do I do that. Nothing I found is clear online

**Comment by KMFDManic** [comment]
https://github.com/pcm720/retroarch-clover/releases

Retroarch with cores zip.  Install snes 2010 hmod and retroarch hmod and gen plus from that download. Copy them into user mods folder, root.  You can then install them with the module installer part of hakchi2.  There is a drag and drop method of installing, too...but, I prefer the old fashioned way.
