### ISSUE TITLE
install driver error

### ISSUE THREAD

**Issue by greatplainsman** [ClusterM/hakchi2#30]
when i click to install driver, a lil box comes up, it says,
"the system cannot find the file specified"

what am i doing? almost there so i thought....
i could really use help, please.

**Comment by njascgil** [comment]
This may have something to do with issue #26 (i had the same kind of error)
If you haven't already, try to unpack the zip file again to replace missing/corrupted files.

**Comment by swiftwolfcoyote** [comment]
I had this same problem, and I found out that my antivirus program Norton was placing files in quarantine. I uninstalled Norton (I planned on replacing Norton with Avast either way) and unzipped the files replacing the missing files. Everything worked for me after that.
