### ISSUE TITLE
Snes dont make suspend point

### ISSUE THREAD

**Issue by SamBuijar** [ClusterM/hakchi2#300]
When i use the reset bottom or the reset combination in snes/genesis games dont make suspend point/save games

**Comment by KMFDManic** [comment]
What SNES Hmod do you have installed, and which Genesis one?  Both work fine for me.

**Comment by SamBuijar** [comment]
I dont know what are installed

**Comment by Mathbeach** [comment]
I have the exact same issue i tried with snes 2010 and 2005 and both didnt work!!

**Comment by KMFDManic** [comment]
I am using 2.15 hakchi2 and snes 2010 saves work for me.

**Comment by SamBuijar** [comment]
I download the emulators and have the hakchi, where i put the emulator (genesis plus and snes 2010)?

**Comment by KMFDManic** [comment]
Into user mods folder, then install them.

**Comment by SamBuijar** [comment]
![image](https://cloud.githubusercontent.com/assets/26920200/24877452/8088ca4c-1e83-11e7-9679-9e3eb8385ba0.png)

**Comment by KMFDManic** [comment]
COPY the actual HMODS into the ROOT of the USER MODS directory.  Then, they will show up in that installer.

**Comment by SamBuijar** [comment]
I did it still dont make suspend points

**Comment by SamBuijar** [comment]
I did it still dont make suspend points

**Comment by KMFDManic** [comment]
How long did you actually play a game?  Did you JUST load the game, then exit immediately?

**Comment by KMFDManic** [comment]
If you aren't using the most CURRENT snes 2010 hmod, saves won't work.  They were blocked in previous snes 2010s due to the 5mb save bug.  

https://github.com/pcm720/retroarch-clover/releases

It is in retroarch with cores.

**Comment by SamBuijar** [comment]
Thanks for slaving my snes library

**Comment by KMFDManic** [comment]
No problem;)
