### ISSUE TITLE
Access to the path 'Gryzor(tr1).nes' is denied

### ISSUE THREAD

**Issue by hkhan89** [ClusterM/hakchi2#301]
Hey guys, im having a problem synchronizing my games, i tried to dump the kernal and uninstall, but it still gives me this error, can anyone please help me how to fix this?

**Comment by KMFDManic** [comment]
Some common causes of this issue are:

-Security permissions denying you access to that path (administrator access).
-Not using official micro usb cable that comes with Mini NES, along with direct USB connection.
-Hakchi2 not in ROOT directory on C: Drive.
-Firewall NOT permitting hakchi2 access.
-Virus Protection Blocking hakchi2.
-driver signature enforcement blocking hakchi2 drivers for Mini NES.
-read only properties on config.ini file in config directory.

Let me know if you still have trouble, as there are a few more drastic things you may have to do, depending on your computer's setup.

**Comment by hkhan89** [comment]
im using hakchi 2.09 and it seems to be working fine, but im having issues with the latest versions.

**Comment by hkhan89** [comment]
im also testing hakchi 2.12, its working fine, but 2.13 and above still have issues.

**Comment by KMFDManic** [comment]
Use 2.13e.  It will work fine for you. The latest code for the yet unreleased hakchi2 is really nice and should prove to work great for most people, once officially released.  2.14 and 2.15 are different than 2.13e and previous.  So, 2.13e is recommended for now, til your problem is resolved.

**Comment by KMFDManic** [comment]
What is 2.13e doing,

**Comment by hkhan89** [comment]
im using 2.12 for now, so i'll stick to for the time being.

**Comment by elierodrigue** [comment]
Do you still have the issue with latest version? I'll close, reopen if you do have issues.
