### ISSUE TITLE
Some Nes games buttons mapped incorrectly and Retroarch not working on nes only games

### ISSUE THREAD

**Issue by NesClassicNoob** [ClusterM/hakchi2#303]
Hi im using hakchi 2.15 and have this weird issue. Some of my nes games like zelda for example to pause the game you press select and the menu you press start. The same with the sword,the buttons are basically  flipped. Though d pad works normal. But games like Mario bros the buttons work normal. Also I can not access Retroarch on all my nes games by doing the specific button combination. Other systems open it normally which is strange. This isn't really a big problem for me right now but am wondering if there is a fix.

**Comment by KMFDManic** [comment]
Uninstall retroarch hmod, reinstall retroarch hmod.  You most likely unintentionally screwed up retroarch settings, somehow.  THIS is the only way to fix it.

**Comment by NesClassicNoob** [comment]
I did do that,all buttons good now. Can you go into retroarch on an nes game?

**Comment by KMFDManic** [comment]
Select+start

**Comment by NesClassicNoob** [comment]
I know it works for all other systems except the nes one can you go into retroarch while playing an nes game? I deinstalled and reinstalled retroarch.

**Comment by KMFDManic** [comment]
What hakchi2 version are you using?

**Comment by NesClassicNoob** [comment]
2.15

**Comment by KMFDManic** [comment]
https://github.com/pcm720/retroarch-clover/releases

Use the Retroarch HMOD in Retroarch with Cores.  Select+Start should work fine for getting to retroarch options.  Make sure you uinstall the one you currently have installed, again.  Then, try the one I linked you to.
