### ISSUE TITLE
Messing around with a C64 core/bios hmod and now I can't sync

### ISSUE THREAD

**Issue by burnjx** [ClusterM/hakchi2#304]
So I have been playing around with the vice libretro core and have ran into a major issue. Everything was working fine until I accidentally left a file called commodore.ico in the hmod folder I was trying to flash for the "bios." Now, when I attempt to sync or Uninstall I get this error: https://i.imgur.com/PxM6Fso.png

I have tried flashing my original dump multiple times, which flash fine. Tried fresh versions of Hakchi2 2.15 and ran the debug version. I am unable to reproduce the error in the debug version. That image is from a fresh install after being prompted to flash the custom kernel. There's gotta be something being leftover somewhere. 

The system boots fine to the original 30. I am just unable to flash modules or games at this point. I will post a debug log if I can manage to reproduce it there. So strange. 

Any help would be appreciated. 

**Edit**: Managed to flash the custom kernel using the debug version. Going back to the regular version still gives the error when trying to sync. Looks like I may be stuck using the debug version for a while. 

**Edit2**: Back to where I was by using the Debug version. All games and cores previously installed are working fine. Error still happens with the Release version.

**Comment by KMFDManic** [comment]
When you say "fresh install", did you copy anything over from another folder, games, config, etc?

**Comment by burnjx** [comment]
Only my original "dump" folder. Added a second edit to my OP.

**Comment by KMFDManic** [comment]
If you are around on Sunday, and still having this issue...I can help you fix it.  At least you found a sticking point for now.

**Comment by burnjx** [comment]
I would appreciate it. I've gone through all the common fixes suggested when you run into errors (wiki, reddit, gbatemp). I'm usually pretty good at figuring this stuff out. This one has me stumped.

I've deleted anything on my c drive that has anything to do with Hakchi (backed up, of course) besides the debug folder that currently works.

Got a couple more things to try before I call it a night.

**Comment by KMFDManic** [comment]
I have helped 782 total people with Minis, mostly via teamviewer, thus far.  Your error is one I have helped on at least a couple dozen times.  I will have some time Sunday and help you get back in action.

**Comment by burnjx** [comment]
Got it fixed. Turns out I missed a folder in AppData/Local when I was cleaning up. That was causing the error. All good now!

**Comment by KMFDManic** [comment]
Good job!  There are other causes for this error, too.  Glad u got it.
