### ISSUE TITLE
C8 error

### ISSUE THREAD

**Issue by TKECOGP2016** [ClusterM/hakchi2#305]
Hi

We have used hakchi 2.15, and tested a lot of hours with adding games,- NES and SNES.

When we  are putting a picture at menu icons(Those in NES MINI MENU) we got Black screen and C8 error. Without its not a C8 error more.
The Mini Nes is working 100% now. No more errors.

WHY?How is it possible? Is it a code for Mini Nes to use those Menu Icons to let the machine dead?
If removing it, but we are not programmers of any kind,just a little html.....very little.

Hope someone can try something out and let us get menu icons without errors.

Best Regards 

TKECOGP2016

**Comment by KMFDManic** [comment]
How many mb of games are you trying to flash?

**Comment by TKECOGP2016** [comment]
223,2 MB. But maybe u misunderstood our issue.

We have got much C8 error. And when we copy a picture to meny icons in "custom -show Folders Manager every time" option,we get a C8 error and games dont work.

Now we delete those Meny icons,and Nes Mini are working 100% every time.

We are wondering how is that possible?

**Comment by elierodrigue** [comment]
your icon size is most likely wrong. You need to have the same exact dimension as the original ones

**Comment by KMFDManic** [comment]
1.  Uninstall hmods.
2.  Uninstall hakchi2.
3.  Flash to original kernel.
4.  Flash custom kernel.
5.  Use custom folders and reflash.

You have memory locked up and following the above steps should fix your problem.

**Comment by KMFDManic** [comment]
Reinstall hmods after you reflash the games.

**Comment by KMFDManic** [comment]
You can fix your icons in folder images by using this program.

https://pnggauntlet.com

**Comment by TKECOGP2016** [comment]
Thanks!
