### ISSUE TITLE
Hakchi shows more than 300mb storage available

### ISSUE THREAD

**Issue by SupahDave** [ClusterM/hakchi2#306]
![hakchi](https://cloud.githubusercontent.com/assets/25854784/24889027/a4097d16-1e35-11e7-9edb-fa1b4538e2b2.png)

My Hakchi is showing that I have 331.6MB to work with instead of 300MB... Is this accurate???

**Comment by KMFDManic** [comment]
Dont go past 299mb.  Guide to follow is 299mb for games and 10mb for hmods.

**Comment by SupahDave** [comment]
So does anyone know why it would be showing 331MB instead of 300?

**Comment by SupahDave** [comment]
Is this just a Hakchi bug?

**Comment by KMFDManic** [comment]
There is about 381 mb of total space on the mini nes.  But, it fills up quickly with 299 in games and 10 in hmods. You do not want to really go past 299 for games or 10 for hmods.  You will get a c8 error if you attempt to flash at 331 in games.  314 is a hard limit for games if you get lucky.  People sometimes get varying results for what hakchi2 reads as memory. Clovershell hmod would show true memory.

**Comment by SupahDave** [comment]
Great answer. Thanks, chief!
