### ISSUE TITLE
Suspension points n64 & save games import from other emu.

### ISSUE THREAD

**Issue by mrTruch** [ClusterM/hakchi2#308]
New feature import/export savestate doesn't work with n64. (Because still doesn't work savestate).

It can be fixed?

Otherwise, Will be a possibility to import savestates or save games from a game started on a pc, for example, to the NESCE?

Thank you for all the work.

**Comment by ClusterM** [comment]
It's not related to hakchi/hakchi2, it's RetroArch mod problem.
