### ISSUE TITLE
Access to path denied. Please help.

### ISSUE THREAD

**Issue by badfish831** [ClusterM/hakchi2#309]
When I try to flash the custom kernel, i get a error access to the path:
C:\Users\Lee\AppData\Local\Temp\hakchi-temp\kernel\initramfs\bin\rsync

**Comment by KMFDManic** [comment]
Do you know how to browse to that path on your computer?

**Comment by ClusterM** [comment]
Try to disable antivirus software.

**Comment by Drakonas** [comment]
This is obviously an antivirus issue. Add an exception to your antivirus software. This is not a Hakchi problem.

**Comment by leolozes** [comment]
I have the same error, having disabled the antivirus. Tried with the last two releases, same error. 
Tried to execute it with administrator mode, same. 

rsync is not in the ~AppData\Local\hakchi-temp\kernel\initramfs\bin, but other files are there (ash, busybox, cat, mount, sh and umount). 

Any ideas?

**Comment by KMFDManic** [comment]
Here you go:)

https://youtu.be/mGooTybpodM

**Comment by leolozes** [comment]
Thanks! But I already tried pretty much everything that is explained on the video:
- changed read only status of the hakchi folder
- changed system permissions
- deleted temp folder
- deactivated antivirus
- rebooted
- tried to manually copy rsync in the temp folder, but it gets deleted / recreated in every installation it seems, so it's no use
- tried several different versions

Any other ideas?

**Comment by KMFDManic** [comment]
What version of Hakchi2 are you using?

**Comment by leolozes** [comment]
I tried the last 3 releases.

**Comment by KMFDManic** [comment]
Try using debug version.

**Comment by Reed-B** [comment]
FYI, was in the same situation helping a friend here, we tried all the steps above, however, seems like the debug version has worked flawlessly so far. It appears to have added a game successfully now and are now hooking it up to see if success.

Edit: @KMFDManic Awsome, debug version worked, @LeoLozes Give it a try

**Comment by leolozes** [comment]
Well guys, awesome help! 

It works in debug version (which ... I don't understand, but hey, it works!)

**Comment by bosko431** [comment]
I have the same issu using version 2.30.
Debug version did not help, any other suggestions to get access to the "key-file" in initramfs?

**Comment by KMFDManic** [comment]
Did you try following my video?

https://youtu.be/mGooTybpodM

**Comment by ClusterM** [comment]
@bosko431 You used debug version and have not sent log to me? Of course it will not help.

**Comment by bosko431** [comment]
I have also tried 2.3 on a native windows 10 machine.
Working on all the steps in KMFDManic's video.

[debuglog.txt](https://github.com/ClusterM/hakchi2/files/1997877/debuglog.txt)

**Comment by bosko431** [comment]
@ClusterM Thanks for the help in advance!

**Comment by bosko431** [comment]
It seems the key-file is missing.

**Comment by ClusterM** [comment]
@bosko431 Seems like you are using not original kernel dump. Can you say size and MD5 of your kernel image?

**Comment by bosko431** [comment]
@ClusterM I'm trying to use :)
It's a european SNES Classic Mini.
All I did is adding some games and trying to synchronise.

14f764851b27cd50af01a7a45242b9e79d7e9d6d
Size: 14,721,663 bytes

**Comment by ClusterM** [comment]
14,721,663 bytes?! It can't be so huge. Please write me on clusterrr@clusterrr.com - i'll send you original kernel and instructions.

**Comment by epseattle** [comment]
@ClusterM  Hi! I'm having the same issue with @bosko431  Could you help me get the original kernel for my SNES US..? :( Thanks

**Comment by ClusterM** [comment]
Yes, email me. It's not legit to share original kernel.

**Comment by Mrderpman** [comment]
@ClusterM Can you get me the og kernel too?
