### ISSUE TITLE
I can not edit a .lua file Theme design

### ISSUE THREAD

**Issue by Nysde** [ClusterM/hakchi2#313]
change the background color file [colors_hvc.lua] and [colors_nes.lua] bg.lua, I can not edit a .lua file 
/usr/share/clover-ui/resources/scripts/colors_nes.lua"
/usr/share/clover-ui/resources/scripts/colors_hvc.lua"
/usr/share/clover-ui/resources/scripts/bg.lua
...
Edit the .LUA file, to change color, change graphics, Theme design, Edit button position, icon, image...
How to modify a .lua file NINTENDO NES MINI?

**Comment by ClusterM** [comment]
It's compiled Lua files, i have no idea how to edit them. But you can replace NES files with Famicom files and vise versa.

**Comment by Drakonas** [comment]
Please ask this on Reddit or Discord. This is not the place to ask.
