### ISSUE TITLE
Question (I didn't know how to change from issue)

### ISSUE THREAD

**Issue by NesClassicNoob** [ClusterM/hakchi2#314]
Will you still make updates to the nes classic? because this thing is now discontinued for now (if we are lucky) but I heard the famicom mini is coming back.

**Comment by B9KnM8UqQ2W2Vwk7uvZ7** [comment]
It's not been discontinued, Nintendo announced that the next shipment that retailers in North America receive is the last planned shipment for 2017.

That's only in North America so most of the world will still be getting them and as is the way with many of the people working on this stuff, ClusterM isn't based in North America.

**Comment by NesClassicNoob** [comment]
Ok cool,I have a european one anyway but I live in Canada you made me a little more happier :)

**Comment by ClusterM** [comment]
I'm still working on hakchi2 when I have some free time. Also I have some plans to rework GUI.
