### ISSUE TITLE
Michael jackson moonwalk crash 

### ISSUE THREAD

**Issue by SamBuijar** [ClusterM/hakchi2#315]
Hi  was playing michael jackson moonwalker for sega genesis all normal i make suspend points i turn off he nes classic but one day the screen freeze and the nes classic crash i delete the game and all was normal again but i want to know how i can make it work with michael jackson moonwalker again

**Comment by KMFDManic** [comment]
Picodrive is a genesis alternative that may help with the Moonwalker issue.  BUT, I would make sure you are using the no-intro version of Moonwalker, with Genesis plus gx, first.  I have yet to have a crash with the game.

**Comment by ClusterM** [comment]
It's not related to hakchi/hakchi2, it's RetroArch mod problem.

**Comment by SamBuijar** [comment]
Thanks is working good now
