### ISSUE TITLE
Three errors in hakchi2 2.16rc3: UI & Translation Spanish

### ISSUE THREAD

**Issue by NaikiTurincondeliphone** [ClusterM/hakchi2#316]
Hi, Cluster, I have seen three errors in hakchi2 2.16rc3:

1 - This is a coupling error:

![hakchi2_2 16rc3_](https://cloud.githubusercontent.com/assets/20205678/25063954/637e6194-21f0-11e7-891e-dbe3243ff0b2.png)

2 - Missing "KB"

![missing_hakchi2_2 16](https://cloud.githubusercontent.com/assets/20205678/25064579/3f5bf774-21fd-11e7-928b-99a2263632dd.png)

3 - The text is not applied in Spanish:

![hakchi2_2 16rc3](https://cloud.githubusercontent.com/assets/20205678/25063980/d20a3304-21f0-11e7-9d51-1b6d601b1946.png)

Thanks, rgs.

**Comment by ClusterM** [comment]
Fixed, thank you :)

**Comment by NaikiTurincondeliphone** [comment]
Verified, all correct, thanks!
