### ISSUE TITLE
1p or 2p choice on a folder icon (like the way a game icon can be 1p or 2p chosen in hakchi' ui)

### ISSUE THREAD

**Issue by piklz** [ClusterM/hakchi2#317]
HI,Can this already be done via the xml folder spec? or is this being added to the ui in the future?Just curious I'm not that bothered but I guess some people might want 2p only folder-list with all the games for 2p regardless of system/console used? Then i thought actually that might be cool(like my xml lists in retorpie/rpi) but not top of my list for sure!!

**Comment by ClusterM** [comment]
It will cause sorting problems. There is folder priority setting in folder manager, it changes folder's settings to sort correctly when using corresponding sorting method. And it changes players count too. 1P to move folders to the left and 2P - to the right.
