### ISSUE TITLE
Issues using Hakchi 2.15 on Mac

### ISSUE THREAD

**Issue by MastrBlastr81** [ClusterM/hakchi2#318]
Hi Cluster,

First of all thank you all your hard work and brain power to actually work this out for us all. Cheers ;)
I'm new to all this stuff, so forgive me in advance if I sound like an idiot. You state Hakchi 2.15 is able to work on a Mac via Wine. I am attempting to mod a fresh Nintendo Mini.  The app starts up fine and all, but when I attempt to "Flash Original Kernal", I get "Waiting for your NES Mini" box, aswell a progress bar. Please see pic.
![2017-04-16 09 11 30 pm](https://cloud.githubusercontent.com/assets/27642585/25073938/460ba582-22e9-11e7-9ab3-0c9ee6915add.jpg)

When I connect my nes mini into my MacBook pro, I followed the " press and release power button while holding down the reset button for 5 seconds, then releasing it" instructions, but nothing happens? It's as though my mini is'nt detected. The Nes light stays off, and I'm unable to press "install drivers" button, when I do it gives an error beep. What am I doing wrong?

**Comment by KMFDManic** [comment]
https://www.reddit.com/r/nesclassicmods/comments/63oxjz/noob_in_need_of_assistance_having_issues_with/dfw8wbd/

**Comment by ClusterM** [comment]
Seems like some virtualization problem. 
Try version 2.16.

**Comment by KMFDManic** [comment]
Yes, drivers dont install til virtual usb settings have device added while in powered on mode.  2.16 does work reliably for Macs.  FEL mode is not the same.  So, just because FEL works, does not mean Clovershell transfer mode will.  My steps that I linked to do work.  But, use 2.16 for perfect results!
