### ISSUE TITLE
hakchi2 2.11 won't create game folders when uploading roms?

### ISSUE THREAD

**Issue by SoCALCat** [ClusterM/hakchi2#32]
Why won't hakchi2 2.11 won't create folders when uploading over 90 games. I just get a message saying that I ran out of room to be able to fit more games?
I tried messing with different setting but no luck.

I there a certain file I need to add to hakchi2 2.11 to make it work with over 90 games?
Or a specific setting I need to set on hakchi2 2.11?
Thx in advance

**Comment by Ippokun81** [comment]
Good evening, I have the same problem.
I add roms (143 to be precise). Before the end of the loading bar, the software tells me that there is not enough space for roms, that I have to wait for the led to switch off and follow the instructions.
The instructions are to restart the nes mini in FEL mode. The process and the loading bar ends and when connecting the nes mini to the TV, only the original games appear.

**Comment by SoCALCat** [comment]
Yup! That's exactly what I get as well. Sometimes I will get some added games along with a Nintendo blue folder with a game title, but when I go to open, nothing happens it just stays on the menu screen...
This folder only shoes when I use the regular hakchi2 v2.11 not the pimp one...
 
 
  On Thu, Jan 26, 2017 at 12:46 PM, Ippokun81<notifications@github.com> wrote:   
Good evening, I have the same problem.
I add roms (143 to be precise). Before the end of the loading bar, the software tells me that there is not enough space for roms, that I have to wait for the led to switch off and follow the instructions.
The instructions are to restart the nes mini in FEL mode. The process and the loading bar ends and when connecting the nes mini to the TV, only the original games appear.

**Comment by Ippokun81** [comment]
Yes, I had that situation too. But now I do not even have the folders...

**Comment by SoCALCat** [comment]
I wonder if it has to do with the windows operating system beeing used? I'm currently working with Windows 10 64bit. I'm going to try it on my other PC thst has Windows 7 64bit... I'll make sure to post it if I could get it to work...
 
 
  On Thu, Jan 26, 2017 at 1:21 PM, Ippokun81<notifications@github.com> wrote:   
Yes, I had that situation too. But now I do not even have the folders...

**Comment by ClusterM** [comment]
Please say your build version, you can check it into about box.

**Comment by Ippokun81** [comment]
It's 2.0.11.2

Envoyé de mon iPhone

**Comment by ClusterM** [comment]
It's strange. Try to fully uninstall hakchi2 then flash custom kernel again and sync again. Also make sure that you updated all files after downloading new version.

If problem is not solved download special debug version:  https://github.com/ClusterM/hakchi2/releases/download/2.11/hakchi2_debug.zip
Try to upload games using this debug version, archive the whole hakchi2 folder (it should contain temp folder and debug lo) and send it to me. I'll investigate it.

**Comment by SoCALCat** [comment]
I flashed the kernel twice and no go. I also re-unzipped hakchi2 then did a factory flash then after flashed with custom kernel. No luck...
Now. When you say "make sure that you updated all files after downloading"  Exactly what files are you talking about? Is it the Games folder files where I store all of my roms? If so. I normally just copy and past the games folder to the latest version of hakchi2...

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 26, 2017 at 2:35 PM, ClusterM<notifications@github.com> wrote:   
It's strange. Try to fully uninstall hakchi2 then flash custom kernel again and sync again. Also make sure that you updated all files after downloading new version.

If problem is not solved download special debug version: https://github.com/ClusterM/hakchi2/releases/download/2.11/hakchi2_debug.zip
Try to upload games using this debug version, archive the whole hakchi2 folder (it should contain temp folder and debug lo) and send it to me. I'll investigate it.

**Comment by ClusterM** [comment]
I'm talking about "mods" folder.
Please try debug version.

**Comment by SoCALCat** [comment]
Ok cool. I'll give it shot when I get home. I'll keep you posted. Thx for your help...

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 26, 2017 at 3:00 PM, Joe Marquez<so.calcat@yahoo.com> wrote:   I flashed the kernel twice and no go. I also re-unzipped hakchi2 then did a factory flash then after flashed with custom kernel. No luck...
Now. When you say "make sure that you updated all files after downloading"  Exactly what files are you talking about? Is it the Games folder files where I store all of my roms? If so. I normally just copy and past the games folder to the latest version of hakchi2...

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 26, 2017 at 2:35 PM, ClusterM<notifications@github.com> wrote:   
It's strange. Try to fully uninstall hakchi2 then flash custom kernel again and sync again. Also make sure that you updated all files after downloading new version.

If problem is not solved download special debug version: https://github.com/ClusterM/hakchi2/releases/download/2.11/hakchi2_debug.zip
Try to upload games using this debug version, archive the whole hakchi2 folder (it should contain temp folder and debug lo) and send it to me. I'll investigate it.

**Comment by SoCALCat** [comment]
ClusterM
Since hackchi2 debug version 2.0.11.2 doesn't contain a Game Folder. Should I transfer the Game Folder from my previous hackchi2 version 2.0.11.0 to the current hackchi2 debug version?

**Comment by SoCALCat** [comment]
ClusterM
Disregard my last post. I didn't realize that a game folder would appear when opening hackchi2 debug version 2.0.11.2 for the first time.

I just went ahead and copied the game folder that contained all my games from the previous hackchi2 game folder to the latest hackchi2 debug version 2.0.11.2 game folder...

**Comment by Ippokun81** [comment]
Thanks , It worked with de bug the version, with reimport of all the games and with Flash again the Nes.

Envoyé de mon iPhone

**Comment by SoCALCat** [comment]
Right on. I got it to work too. I used the none debug version.
The only thing I noticed, is that will I upload the games right near the end I get the "To many games message" then it will prompt me to shut off the console and disconnect the USB Cable and then reconnect the USB Cable into the console power on while holding reset button, then the up loading resumes and completes it's self...
I then ahut the power off the console, connect it to AC power and hdmi and power on the console, then is all good after that....
Maybe the hakchi2 team will correct the "to many games issue" in the next release. A hakchi2 version where you don't have to disconnect the USB Cable while uploading games. .
At least for now, everything is good. Thanks team for your support and services. I am going to donate to you guys for all you do for us peep's :)  
 
  On Thu, Jan 26, 2017 at 4:58 PM, Joe Marquez<so.calcat@yahoo.com> wrote:   Ok cool. I'll give it shot when I get home. I'll keep you posted. Thx for your help...

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 26, 2017 at 3:00 PM, Joe Marquez<so.calcat@yahoo.com> wrote:   I flashed the kernel twice and no go. I also re-unzipped hakchi2 then did a factory flash then after flashed with custom kernel. No luck...
Now. When you say "make sure that you updated all files after downloading"  Exactly what files are you talking about? Is it the Games folder files where I store all of my roms? If so. I normally just copy and past the games folder to the latest version of hakchi2...

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 26, 2017 at 2:35 PM, ClusterM<notifications@github.com> wrote:   
It's strange. Try to fully uninstall hakchi2 then flash custom kernel again and sync again. Also make sure that you updated all files after downloading new version.

If problem is not solved download special debug version: https://github.com/ClusterM/hakchi2/releases/download/2.11/hakchi2_debug.zip
Try to upload games using this debug version, archive the whole hakchi2 folder (it should contain temp folder and debug lo) and send it to me. I'll investigate it.

**Comment by ClusterM** [comment]
I'm just afraid that kernel will be too big. It's more safe to split transfers. But I'll increase maximum kernel size.

**Comment by SoCALCat** [comment]
You don't think by increasing the kernel to maximum size will damage it?
Also I hear that people are adding as many as 700 games in the console, you think it's a good idea to do that for being able to  save a large amount of game saves?
 

    On Friday, January 27, 2017 7:34 AM, ClusterM <notifications@github.com> wrote:
 

 I'm just afraid that kernel will be too big. It's more safe to split transfers. But I'll increase maximum kernel size.—

**Comment by ClusterM** [comment]
> You don't think by increasing the kernel to maximum size will damage it?
> Also I hear that people are adding as many as 700 games in the console, you think it's a good idea to do that for being able to  save a large amount of game saves?
It will not damage console (it's starts from RAM, not from flash) but game transfer will fails if kernel is very big.

**Comment by ClusterM** [comment]
Re: [ClusterM/hakchi2] hakchi2 2.11 won't create game folders when uploading roms? (#32)


Hi!

Sorry for a long answer.

Kernel executed in RAM only.





You don't think by increasing the kernel to maximum size will damage it?
Also I hear that people are adding as many as 700 games in the console, you think it's a good idea to do that for being able to  save a large amount of game saves?


On Friday, January 27, 2017 7:34 AM, ClusterM <notifications@github.com> wrote:


I'm just afraid that kernel will be too big. It's more safe to split transfers. But I'll increase maximum kernel size.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread. 

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




-- 
С уважением,
 Алексей                          mailto:clusterrr@clusterrr.com
