### ISSUE TITLE
Missing credits of translators in "About" (2.16 final)

### ISSUE THREAD

**Issue by NaikiTurincondeliphone** [ClusterM/hakchi2#322]
Hi, in version 2.16rc3, added credits of translators, but in version final missing.

(Version 2.16rc3)

![about](https://cloud.githubusercontent.com/assets/20205678/25086407/b71c5bda-2367-11e7-8162-6f71d4038302.png)

Thanks!!

**Comment by ClusterM** [comment]
One of translators asked to remove it because of privacy. So I decided to remove it and add only after request/confirmation.

**Comment by MiLToS666** [comment]
You can leave my info there. I would prefer to use my nickname MiLToS_666, my real name is on my email anyway. ;)

**Comment by NaikiTurincondeliphone** [comment]
Ok, there's no problem with me. You can put my mail or Twitter: @___naiki___

**Comment by Mad-Mega** [comment]
Well you can add me but without the mail address
Something like

Mark Dekker - Mad Mega

**Comment by ClusterM** [comment]
Ok! I'll ask others and reupload latest release soon.

**Comment by NaikiTurincondeliphone** [comment]
I reply your mail. Thanks.
