### ISSUE TITLE
Game Manuals

### ISSUE THREAD

**Issue by hossbags2** [ClusterM/hakchi2#323]
Is there a chance to update the game manuals option to instead use the original 30 games but to open a link on a smart device that has all the game mauals

**Comment by KMFDManic** [comment]
You use an Android or Iphone?

**Comment by ClusterM** [comment]
It's possible to change QR code, i think. It's stored in "nes.png" file.

**Comment by ClusterM** [comment]
I made very simple tool pack to do it: http://clusterrr.com/soft/nes_mini_skin_hack.zip
It will also allow to create custom skins :)

How to use:

1. Make sure that you are using hakchi2 v2.14 or newer, install custom kernel using it if it's not installed yet.
2. Close hakchi2 :)
3. Run "fetch_original_skin.bat", it will download original skin from your NES Mini (you connected it to PC already, right?).
4. Edit "nes.png" file with your favorite graphics editor (but not with mspaint, it doesn't support transparency)
5. Run "make_skin_mod.bat", it will create your "skin_hack.hmod" skin mod.
6. Run hakchi2 and just drag-and-drop this "skin_hack.hmod" file to it. Install your skin.
7. Enjoy!

**Comment by Tyson716** [comment]
I tried to create a custom skin using the directions above, however the skin mod tool has errors when processing and does not create the hmod. This is what the box reads:

Making skin pack...
        1 file(s) copied.
      0 [main] tar 260 sync_with_child: child 5196(0x15C) died before initializa
tion with status code 0xC0000142
    258 [main] tar 260 sync_with_child: *** child state waiting for longjmp
../tools/tar: child process: Cannot fork: Resource temporarily unavailable
../tools/tar: Error is not recoverable: exiting now
Done! File skin_hack.hmod created. Just drag-and-drop it to hakchi2 window and i
nstall your skin.
Press any key to continue . . .

Any help? Thanks.

**Comment by ClusterM** [comment]
Seems like tar is not working without mingw...

**Comment by Tyson716** [comment]
I installed Mingw per your suggestion, but it still gives the same error. I don't understand why.

**Comment by ClusterM** [comment]
Try to use tar from mingw package.

**Comment by Tyson716** [comment]
That worked, thanks!
