### ISSUE TITLE
Stuck at Waiting for Nes Mini and box that says Waiting for Nes Mini Please do the following

### ISSUE THREAD

**Issue by FOXMULDERAREA51** [ClusterM/hakchi2#324]
Ok.......I started with Hakchi 2.15.  Setup everything (Load games into application, add covers, etc)  I dumped the original kernel and replaced it with the one from Hakchi 2.15.  Then it says ready to add games.  I go to add games and the screen says Waiting for NES Mini Please do the Following.  The driver for the NES MINI shows when the light is not on.  When the light is on it shows nothing.  Started this with Windows 7 32 bit.  I then go to my Windows XP Pro 32 bit computer and try to downgrade to Hakchi 2.14b.  Games load into software, covers created, dump the previous kernel, replace with one from Hakchi 2.14.  Same thing happens.  Waiting for NES Mini Please do the following......

When I turn on the NES Mini it is not shown in my Device Manager.  If I do the hold reset and then turn on the NES Mini and then wait so the light is off the computer makes a sound that something is connected and then says the screen that talks about turning on the system and holding the reset........click here to install the driver...........the driver is already installed and when I click on it.......installation begins and then after 10 sec it says press enter to exit installation.

Am I doing something wrong or will I have better luck with Hakchi 2.16?  Am I missing another driver?  Please let me know what I am doing wrong.  

Thanks

**Comment by KMFDManic** [comment]
Use 2.13e hakchi2, for now, to get things going.  Confirm that version works for you.  Then, we can focus on getting 2.14/2.15/2.16 working for you:)

**Comment by KMFDManic** [comment]
You can also use zadig to help install the driver on 2.13e, if necessary.

**Comment by angelbless** [comment]
Something similar happens to me ... worked fine the first time I synched my games in 2.17c (they are working on the nes console), then i downloaded cover arts and added some games and now it wont  synch :(.. Please any help?

**Comment by angelbless** [comment]
Btw I used zadig to install the driver, now it appears as Nes Mini there.

**Comment by Drakonas** [comment]
Closing this as the OP has not responded.
