### ISSUE TITLE
Screen Savers Causes the C8 Error on 2.16

### ISSUE THREAD

**Issue by MattMan76** [ClusterM/hakchi2#325]
I don't know if I just didn't noticed this with 2.15, but the Enhanced Screen Savers Causes the C8 Error after about an hour of it just sitting there.   It does it every time I let it sit on the screen saver with 2.16.

**Comment by ClusterM** [comment]
What is Enhanced Screen Savers?

**Comment by MattMan76** [comment]
I was under the impression that the screen saver pixel art other than Mario and Luigi were from a screen saver enhancement mod. Is this incorrect?
In any event I was able to fix my errors, by re-flashing the Kernel.
Thank you very much!
