### ISSUE TITLE
save state manager shows empty panel and then restart on closing

### ISSUE THREAD

**Issue by piklz** [ClusterM/hakchi2#326]
when it pops up its blank ( i have nes and retroarch saves  in my nesmini) when i close window it reboots nesmini (maybe this is normal?>)  (windows 10 creative update edition  admin-launched no virus on or winwdows defender on)

**Comment by ClusterM** [comment]
Try this: https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems
And send me log.

**Comment by piklz** [comment]
cheers Clusterm already on to it!!  I did debug mode heres what it returned:
_,net window popup says:_ invoke or begininvoke cannot be called on a control until the window handle ihas been created
_command verbose says:_
**Invoke or BeginInvoke cannot be called on a control until the window handle has been created.   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at com.clusterrr.hakchi_gui.SaveStateManager.LoadSaveStatesList() in d:\Projects\C#\NesMini\hakchi_gui\SaveStateManager.cs:line 43**

many thanks again other than this 2.16 is continuing already great revisions of your hakchi!

**Comment by piklz** [comment]
or... it might be a conflict with me having ftp enabled as it happened again.. when i disabled ftp mode it loaded? goodluck sir!!!

**Comment by ClusterM** [comment]
Please redownload latest release. Should be fixed now.

**Comment by piklz** [comment]
as ever thanks !!
