### ISSUE TITLE
Question not issue

### ISSUE THREAD

**Issue by TonyBiH** [ClusterM/hakchi2#327]
I have hakchi2 2.00 at home and is work fine I added 64 games. Can I add more and do I need newer version? I downloaded 2.0.16.10 (do I need newer?) and I will add my old folder dump, games and config to newer version. How many games I can have without submenu (I like to scrooll i don't find bad that there is lot of games out of screen). For now I don't wanna use other emulators just NES Mini so If you can answer to me I will be happy. Thank's for good work.
P.S. If I can mention I like Captain America and Avengers but there is some mixup in menu and text (game is playable) If you know someone that could make little patch for that game everything else is fine.

**Comment by MattMan76** [comment]
I have 190 games loaded total and 87 in the top folder with no problems using 2.15 and 2.16.  I believe as you get closer to 90 games in one location (folder) you are more likely to get the C8 Error when you try to load a game from that location. Hope that helps.

**Comment by ClusterM** [comment]
https://github.com/ClusterM/hakchi2/wiki/FAQ

**Comment by TonyBiH** [comment]
I transfered to new version. Now I have around 140 games evenly sorted splitted by 70 and I removed epilepsy protection (when I was first tryed The Legend of Kage I was so scared that my TV malfuncion - missed news about epilepsy protection). Thank you for all help.
