### ISSUE TITLE
Save States not working?

### ISSUE THREAD

**Issue by tjm694** [ClusterM/hakchi2#328]
Just upgraded to 2.16 .... save states show they are there, when I click on them to load it acts like it's going to load, but then just starts the game as if I were starting it fresh.  Any ideas?   Maybe a pointer is wrong for the save states?

**Comment by ClusterM** [comment]
Which game you are trying to load?

**Comment by tjm694** [comment]
The ones I tried were NES ROM hacks ... Super Mario Unlimited, Super Mario 3 Mix .... didn't try any actual NES games .... but the NES ROM hacks were .NES files ...

**Comment by ClusterM** [comment]
Which version are you using? Which mods you have installed?

**Comment by tjm694** [comment]
2.16 and have all mods installed except the "use nestopia" and such .... I just loaded the save state manager you made and deleted 2 save states for SNES games ... you think this could have thrown things off?

**Comment by trumisery** [comment]
Couple things just to make sure are right:

1: Are you using the same core for the save states?  If you were using snes 9x2005 as your main core for snes games for example, and now you are using snes 9x2010, the save states are not compatible with each other.
If you were using a nes core, and are now using the built in nesce emulator, those save states will also not be compatible with each other.

2: If you go back to the previous version that you had working, do the save states still work?  It could be possible there is some corrupt data. 

Those are the only problems I have ever encountered as far as save states have been concerned.

**Comment by tjm694** [comment]
They are NES romhacks.  The NES games work fine .... it's weird.  Will try to reflash at 2.14 and see if they still work.

**Comment by ClusterM** [comment]
So are you using RetroArch or original emulator with those roms? Which version of RetroArch mod is installed?
