### ISSUE TITLE
"Disable Epilepsy Protection" Doesn't Seem to Work

### ISSUE THREAD

**Issue by raccoonmario3** [ClusterM/hakchi2#33]
When I select "Disable for all Games" under "Settings-Epilepsy Protection," and then flash games/kernal to the NES Mini, the games run fine, but the epilepsy protection remains. For example, in Zelda II, there is pretty much no flickering upon death. In custom-added games, the protection is there as well, such as in Darkwing Duck, which I tested. I also tried removing "--enable-armet" from the command line of individual games, to no avail. I tried entering the global command "--disable-armet," and got a C7 error for every game that I tried to run. I had to reflash the NES Mini with that command removed to get the games to work again. Any help would be appreciated.

I am using Windows XP in a virtual machine in VMware Fusion on macOS Sierra (10.12.2).

**Comment by raccoonmario3** [comment]
–UPDATE–

It appears that the feature does work after all. I flashed the system with epilepsy protection enabled, and loaded my save state from the ending to the game. The game clearly had the protection, with all sorts of uneven and strange blurs across the screen. When I flashed the system with Epilepsy protection disabled, the ending screen flashed normally, like it would in an emulator. I still wonder why Zelda II doesn't have proper flickering on the death screen, unless the ROM was modified, and why the brightness seems to change in Darkwing Duck. Perhaps my TV is to blame.

**Comment by raccoonmario3** [comment]
-UPDATE 2-

Zelda II's epilepsy protection seems to be in the ROM itself, and trying to replace it with a ROM from the internet didn't work, as if the system patches the ROM before running it. This "auto-patching" also means that the battery warning after the game-over screen is gone by default. I got around this by using a level editor for the game, placing a block on the overworld that can't be seen in-game, saving the ROM, creating an IPS, patching the IPS to a clean ROM, and then sending my "hacked" ROM over. The epilepsy protection is now gone from Zelda II and the battery warning is back. This method should work for any similar games.

**Comment by 00arak00** [comment]
The system in many cases uses the "Wii" version of the games. Some of them have built in flash blocking and other changes.

**Comment by shifted1** [comment]
@raccoonmario3 Would it be possible to maybe get the IPS patch you made for Zelda II?
