### ISSUE TITLE
2.16b endless .net popup loops cannot launch hakchi

### ISSUE THREAD

**Issue by piklz** [ClusterM/hakchi2#331]
_debug output_ :
**Starting, version: 2.0.16.11
Loading config
Loading games
Object reference not set to an instance of an object.   at com.clusterrr.hakchi_gui.MainForm.LoadLanguages() in d:\Projects\hakchi2\MainForm.cs:line 407
   at com.clusterrr.hakchi_gui.MainForm.FormInitialize() in d:\Projects\hakchi2\MainForm.cs:line 128**

cheers
(windows 10 ,tried compat mode win7,win8,vista_servpack2)

**Comment by llioncourt** [comment]
Quickly click on the error message close button and the other close button of the windows that appears behind it. Then the app will load. After it`s loaded just go to settings-> Language and select a default language. close the app and the error is gone,

**Comment by piklz** [comment]
i eventually worked out to click ok quickly would shot it at least .. but i didnt realise the language select would fix the errors - i should have guessed that really since it was the new feature.thx very much llioncourt for tip

**Comment by ClusterM** [comment]
Oops. My mistake. Will reupload release in a hour.
