### ISSUE TITLE
Games Not Suspending 2.16

### ISSUE THREAD

**Issue by holeshot1982** [ClusterM/hakchi2#334]
When I was running 2.15 I removed all of my SNES and had only NES... Updated to 2.16 this morning and adding some SNES games back.... The games that I previously had earlier are working just fine, Suspend states and all however ALL of the new games I added are not doing Suspend states when I reset the system. I've tested very SNES rom and all the old ones are fine, new ones don't suspend... I have not tested NES because I haven't added any new NES games games.... Any thoughts?

**Comment by holeshot1982** [comment]
Figured it out, had to update the SNES HMod

**Comment by lpossamai** [comment]
>Figured it out, had to update the SNES HMod

@holeshot1982  you could provide us more info (i.e how did you update it?)

Cheers

**Comment by holeshot1982** [comment]
I wish I could but I don't even remember creating this thread. I sort set up the NES Classic the way I wanted it and left it alone.... If I updated the SNES HMod then I probably got the answer from Reddit. My suggestion would be to search Google or check out the Reddit sub. Those guys are more than helpful and can rattle off fixes pretty quick.
