### ISSUE TITLE
can't write to USB error

### ISSUE THREAD

**Issue by spmarch** [ClusterM/hakchi2#338]
I have successfully dumped the kernel but during the initial flashing of the custom kernel I am getting an error message "Can't write to USB" Not sure what is causing this. Using hakchi 2.16 in Windows 10

**Comment by spmarch** [comment]
I have had problems with the NESC rebooting due to the USB port being somewhat loose before, i am guessing that this issue stems from that...

**Comment by derchrisuk** [comment]
I had that once.
Was a bad cable.

**Comment by elierodrigue** [comment]
Yeah thats a cable issue.

**Comment by spmarch** [comment]
Hmm I've tried several different cables all of which work fine otherwise. I am thinking there is a problem with the micro USB port itself.
