### ISSUE TITLE
Famicom mini plz help

### ISSUE THREAD

**Issue by Sossairox** [ClusterM/hakchi2#339]
Hello I want to know before buy the famicom mini (or Nes mini) if it runs NTSC USA games at full speed? Or it happens like the pal games that runs with issues?

**Comment by Sossairox** [comment]
I mean, the famicom mini can runs English games at full speed like jap games??

**Comment by ClusterM** [comment]
Hi.
Both USA and Japanese games use NTSC, 60Hz. So both USA and Japanese games will run at the same speed.
European games will work faster or will not work at all on default emulator.  But this problem can solved using RetroArch.

**Comment by Sossairox** [comment]
thx
