### ISSUE TITLE
change nes classic mini into famicom mini

### ISSUE THREAD

**Issue by blackjack-78** [ClusterM/hakchi2#34]
Hi! I would like to know if it's possible to change my nes classic mini(i mean replace the background and the 30 original games includes )into famicom mini. Since it's possible to choose into the menus of hackchi2 , i know im a "dreamer'...but i have hope! (^_^). I've "tried"to do that with the new update( i've chosen the famicom mini with his 30 games in the menus...but it doesn't work, i've keep my "additional games" and lost my originals games in the transfer...)! ps: sorry for my bad english.. 😆

**Comment by blackjack-78** [comment]
Hi! I would like to know if it's possible to change my nes classic mini( background and the 30 original games includes )into famicom mini. Since it's possible to choose into the menus of hackchi2 , i know im a "dreamer'...but i have hope!(^_^)

**Comment by blackjack-78** [comment]
Sorry, i  forgot...i've "tried"to do that with the new update( i've chosen the famicom moni with his 30 games in the menus...but it doesn't work, i've keep my "additional games" and lost my originals games in the transfer...)ps: sorry for my bad english.. 😆

**Comment by baconcow** [comment]
This application does not add ROMs to the NESCE. The purpose of that choice, in the menu, is the designate which console version you have. Your original 30 games shouldn't have be lost, likely only hidden. Try setting it back to the correct NES version.

**Comment by blackjack-78** [comment]
Thanks for your reply! ^^
