### ISSUE TITLE
Enhancement/Retro-Feature Request  - Hide Thumbnails

### ISSUE THREAD

**Issue by KMFDManic** [ClusterM/hakchi2#340]
Thumbnails when deleted, leave white boxes behind.  On average, deleting all thumbnails would save approximately 10mb of valuable space.  Please implement "Hide Thumbnails" as an option, back into the Main Hakchi2 Gui interface, so that these white boxes would be gone:)

**Comment by baconcow** [comment]
Does the mod linked in [this issue](https://github.com/ClusterM/hakchi2/issues/260) not do this? I see you were part of the reddit discussion, so I am guessing it does not.

**Comment by KMFDManic** [comment]
I am aware of the mod method.  I am requesting it be added back into the Gui because it is more user friendly, and is an excellent way to save essential mb for flashing purposes;)

**Comment by KMFDManic** [comment]
Just noticed he just added this feature into 2.17 RC:)
