### ISSUE TITLE
Help Scripting - Password Protection

### ISSUE THREAD

**Issue by Nysde** [ClusterM/hakchi2#343]
How executed "/etc/init.d/S810password"  after "S79clovercon" (controller driver) but before "S81clover-mcp" (main GUI) ?
Which file to modify to run S810password ?

![628acyt](https://cloud.githubusercontent.com/assets/7020300/25549248/193b63ee-2c71-11e7-8f52-802707d46de8.png)

Hardcore scripting - password protection = https://github.com/ClusterM/hakchi2/wiki/Modifications-and-modules-guide

**Comment by derchrisuk** [comment]
If you want it to run before S81, but after S79, it needs to be names S80

**Comment by ClusterM** [comment]
...but S80 already exists.
It's executed in alphabetical order, nut numeric. So it will be executed just in order shown on your screenshot :)
![image](https://cloud.githubusercontent.com/assets/4236181/25554753/1db8dd4e-2cde-11e7-9c9f-eff91c1b3555.png)

**Comment by Nysde** [comment]
Nothing happens the startup remains normal. . :(

I stored this files as 
"password.raw.gz", 
"password_fail.raw.gz"
 and "password_ok.raw.gz" into "/etc/" directory

and files S810password  Dans /etc/init.d/

**Comment by ClusterM** [comment]
Make sure that S810password has executable rights, e.g. execute:

    chmod +x /etc/init.d/S810password

**Comment by Nysde** [comment]
Thank you ClusterM, I have another question, What software to convert PNG to RAW ?

I used the XnView software, I have a problem displaying
![170430-1241-08](https://cloud.githubusercontent.com/assets/7020300/25563759/35a0d23e-2da3-11e7-8860-e36fe363b9c0.jpg)

![convert](https://cloud.githubusercontent.com/assets/7020300/25563761/3e3e7aae-2da3-11e7-84d2-af81240594f4.PNG)
