### ISSUE TITLE
Can't get driver to install

### ISSUE THREAD

**Issue by heyuimintojsus** [ClusterM/hakchi2#344]
I disabled the driver signature enforcement, but when I go to install driver it still doesn't work (version 2.15). I have googled and searched and I don't know what to do to fix this. 

I get the "The system cannot find the path specified.﻿"

I need specific step by step instructions bc I don't understand any of this, especially since it's not working.

Thank you in advance.

**Comment by ClusterM** [comment]
Hi.

Try this https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems
And show your debug log. Also make sure that file driver\nesmini_driver.exe exists.
