### ISSUE TITLE
Allow editing of display names of original 30 games

### ISSUE THREAD

**Issue by ringbuffer** [ClusterM/hakchi2#346]
If you add games but keep the original 30 names, there are some display name issues to work around.  For example NINJA GAIDEN is in all caps; if you add Ninja Gaiden 2 and Ninja Gaiden 3, you have to put them in all caps too to get them to look the same.  Mega Man 2 is displayed as "MEGA MAN™ 2" so the sort order also gets messed up.  To work around this, I have removed the stock game and added my own version of the ROM where I have more control but it would be nice to keep the original games AND have the control.

**Comment by Neite99** [comment]
I believe the 30 games are coded into the software. To change them would just be a "mask" to make it display differently not necessarily change the title for sorting.

It would probably be quite a bit of work for Cluster or anyone else to do and it sounds like you have the a more feasible solution already by just adding them and hiding the original.

**Comment by Drakonas** [comment]
The original games are locked . you cannot change them. Closing this.
