### ISSUE TITLE
Folder customization for "pages" view

### ISSUE THREAD

**Issue by ringbuffer** [ClusterM/hakchi2#347]
The folder manager is awesome.  The "pages" organization is awesome.  Is there any way to bring these two together?  I'd love to be able to use the folder manager (to pick which items go in which folders, set folder icons, set folder names, etc.) but then get the "pages" navigation where I don't have to go up a level and back down to get to another folder of games.

**Comment by Mad-Mega** [comment]
As far as i know, @ClusterM is working on that, he needs people to design it however.

**Comment by ClusterM** [comment]
It's not so easy to visualize this structure since pages are not tree-like.

**Comment by Jhynjhiruu** [comment]
It would be quite cool if it was possible to create your own folder structures inside Windows Explorer, say, by creating a bunch of folders with <gameName>.hkch files in them, and then letting the user rearrange/rename them however they liked

**Comment by Drakonas** [comment]
Please adjust your statement to make it clearer what you want. It is hard to understand. Closing for now until you do.
