### ISSUE TITLE
Verify failed:0 This is not Good. Error

### ISSUE THREAD

**Issue by GetModded** [ClusterM/hakchi2#348]
Verify failed:0 This is not Good. Error is what I get when I try to upload the new kernel.
I have had no problems with any others except this particular unit.
I dropped down to 2.14 and dumped the kernel then went back up to 2.15 and this happens every time.

**Comment by Neite99** [comment]
Have you tried using a different dump? It may just be the image you are using.

**Comment by ClusterM** [comment]
Maybe corrupted flash memory. You try manually to change "Custom2Flashed" to true in "config.ini" but it's not very safe.

**Comment by Drakonas** [comment]
Closing this as it does not need to stay open.
