### ISSUE TITLE
Strange animation navigating between top-level folders

### ISSUE THREAD

**Issue by ringbuffer** [ClusterM/hakchi2#349]
I have six folders in the root folder that are displayed when I turn on the NES Classic.  Scrolling from left to right, after the fourth folder, the whole list fades out and then is animated sliding in from the left edge of the screen with the fifth folder selected.  Since only four slots (folders or game) fit on the screen at once, I assume it is trying to jump to the next four or something – though it doesn't do anything weird like this for the subfolders.  Scrolling from right to left, the animation functions normally.

**Comment by sanjay900** [comment]
Its due to the fact the the NES Classic menu system wasn't designed to be used with only four games.

**Comment by elierodrigue** [comment]
Yeah part of NES Classic behavior... You could add empty entries to "avoid" that maybe....
