### ISSUE TITLE
Kernel dumping isn't working.

### ISSUE THREAD

**Issue by vvillegasmorral** [ClusterM/hakchi2#350]
Every time I try to dump the kernel following the steps I install it and when I click enter and I leave the cmd windows it keeps like this and does nothing. Behind the steps window says Waiting for the device even though it's connected.
![captura](https://cloud.githubusercontent.com/assets/28198496/25564574/87440440-2db6-11e7-9d27-c8b49be5c0fe.PNG)

**Comment by seanrox** [comment]
Before turning on the power to your NES Mini, hold the reset button. Keep holding the reset button, then press the power button while still holding the reset button. Count to 5 (1... 2... 3... 4... 5...) then let go of the reset button. That should get you going.

**Comment by elierodrigue** [comment]
You could also just hold reset up  until it gets working. 
If you ear the usb connection sound while holding reset, then make sure you installed the drive and you should be all good.
