### ISSUE TITLE
2.0.17 rc1 NESCE DISCONNECTED (Shutting down).

### ISSUE THREAD

**Issue by mrTruch** [ClusterM/hakchi2#351]
HI

I Just get 2.0.17 "rc1"

I have som experience so I updated as usual but I turn on my NESCE and then I open hackchi but "shutting down" appears on my NESCE and it is impossible to play.

After some days I still trying because I was thinking this was a pre-release error but other coleagues can use this "rc1" version. Why not me?

So I try it but same results. And This time I try one thing. When NESCE is shutting down then I select some more game and I try to upload them, to this I must to turn on the NESCE and then it allows me to upload them but when it finished is shutting down again.

Please help with that. Obviously I've tried to flash/reset etc...

I've attached my debuglog, may it will help you.

[debuglog.txt](https://github.com/ClusterM/hakchi2/files/966977/debuglog.txt)

**Comment by MiLToS666** [comment]
I am having the exact same "clovershell disconnected" issue with 2.17rc1.
I even started from stock and same thing happens.

**Comment by elierodrigue** [comment]
It have to do with exection of this command : Clovershell.ExecuteSimple(string.Format("date -s \"{0:yyyy-MM-dd HH:mm:ss}\"", DateTime.UtcNow));
In mainform.cs line 220... Commenting it own fixed it for me... still investigating

**Comment by MiLToS666** [comment]
I deleted this line and it doesn't disconnect now so yes, it has something to do with it I guess.
Another issue appeared and I'm not sure if it has anything to do with this... When I try the new "take screenshot" option, it makes the screenshot fine but after a few seconds hakchi2 stops working and Windows says it's looking for a solution to this problem and eventually it closes. :(

**Comment by ClusterM** [comment]
I'll investigate and fix it soon. Have not so much time now.

**Comment by mrTruch** [comment]
Thanks @ClusterM Try it when you can. We'll waiting with patience.

**Comment by ClusterM** [comment]
That's because of automatic system shutdown :) NES Mini's shell thinks that it's runs for a many years and shutdowns automatically. Seems like time sync feature is not very good idea without onboard RTC clock. Or I need to create some workaround...

**Comment by ClusterM** [comment]
Fixed. It was really easy to disable automatic shutdown before time setup and re-enable it after.
