### ISSUE TITLE
2.11c issue with the dump kernel

### ISSUE THREAD

**Issue by NESFan** [ClusterM/hakchi2#352]
I wanted to say first thanks for developing this. It is great. My antivirus did something to the executable file and it appear to have corrupted the program. I can no longer load games into the program. I was able to restore it to factory setting, but when i do a dump kernel i get this error below. Is there a way to uninstall/reinstall the entire driver and tool to get the program working again properly?

![capture](https://cloud.githubusercontent.com/assets/28244756/25571269/e54b5f4e-2dfb-11e7-891f-34b536dcc88f.JPG)

**Comment by sanjay900** [comment]
If your console is already patched, then you can ignore this error.

**Comment by ClusterM** [comment]
Please read the FAQ.
