### ISSUE TITLE
"Waiting for Device" when trying to sync games - 2.16

### ISSUE THREAD

**Issue by RetroLove** [ClusterM/hakchi2#353]
So just downloaded hakchi2 for the first time.  I'm using ver 2.16.  I was able to get the kernel dump and the module load working.  (I had to use Zadig tool to load the driver), but am running into the same a similar issue when I try to sync the new games.  It will not move beyond the dialogue and "waiting for device" when i sync.

I noticed that with the Zadig tool it recognizes the nes classic as 2 different devices when its in regular powered on mode and FEL mode.  So i installed the driver for both.  Thanks in advance for any help.

**Comment by jayden051209** [comment]
Did you ever instail the drive

**Comment by Drakonas** [comment]
This needs to be discussed on Reddit. This is a place to report bugs that you know what is causing said bugs, not trying to find the solution to your problem. https://www.reddit.com/r/miniSNESmods/
