### ISSUE TITLE
Unsupported mappers now working?

### ISSUE THREAD

**Issue by zeusz4u** [ClusterM/hakchi2#354]
I'm not sure if this issue has been fixed or not (or if it's fixable at all), but I just wanted to address a quick question for you guys:

When adding a NES ROM collection, Hakchi warns me of some games that have unsupported mappers. Just to name a few titles: 

```
Action 52
Batman return of the joker
big nose freaks out
bog nose the cavemen
buzz & walldog
captain comic
castle of deceit
holy diver
```

What I wanted to ask you is that I still added them to my NES Mini, and surprise all seem to be working (indeed only played them for a minute or two). What is supposed to not work when I see the error message? I didn't change any of the default CLI arguments for any of the games, but had instead installed the following modules already: Retroarch, geneis plus, mame2003, snes2010, 

Then noticed the following:
Retorarch description: `It will automatically detect unsupported NES games and run them instead of the default emulator. Save states will work as usual.`

Does this mean that retroarch module automatically fixes all mapper errors with unsupported games? Also, does it use this emulator for all NES games, or only for the unsupported ones, the others will still run on the default emulator? The command line arguments are identical with other supported games.

**Comment by ClusterM** [comment]
...
![screenshots_2017-05-03-03-43-17](https://cloud.githubusercontent.com/assets/4236181/25645025/356ccaae-2fb3-11e7-9eb5-b7e19ae26b6e.png)

Answer is just in first lines of description of module you installed.

**Comment by zeusz4u** [comment]
Thanks, just wasn't sure why games throw me that warning when adding them, but this make sense. I thought they need the arguments to be changed or something in order to use a different emulator, but glad they don't and they simply work out-of-the box with this core not needing to do anything on my end.

Does this mean that almost all of the NES collection games should also work out of the box when using this core, and maybe there's only a handful that don't work at all?

**Comment by ClusterM** [comment]
Yes, near all known NES games should work.

**Comment by zeusz4u** [comment]
Thanks for all the info. I'll close this issue if you don't mind, since it's not really an issue with your app, but it was rather just a question. All the best.
