### ISSUE TITLE
C8 to C2 issue; possible fix

### ISSUE THREAD

**Issue by elierodrigue** [ClusterM/hakchi2#355]
I tried a fix for the c8 to c2 issue. 
Give it a try , its in latest helping hand version : 
https://github.com/elierodrigue/Hakchi_HelpingHand/commit/866d8714880ae1ff66bb20d49b68d692ae480cf3
You'll need to build it, connect your nes classic, run helping hand beside hakchi installation (2.14 and up) and click option 5. Then you can start browsing around. 

Technical details : 
Looking at available space using "df -h", i noticed that approximatly 100k was being created while navigating to a folder i've never opened. On a system that is almost full, it can cause the c8 to c2 issue. 
Looking at what is changing, I noticed that a saved game folder is created for each game / folder loader, even though no data is being saved. That folder by itself is taking some space.
In the change folder procedure (chmenu) i'm adding "find /var/lib/clover/profiles/0/ -type d -exec rmdir {} \; "
before the new folder is mounted, deleting all empty folder (rmdir will fail if folder is not empty and -empty doesnt appear to work). 
It does slow down folder change a tad when there's a lot of cleaning to do, especially if you never cleaned it. (First time took me ~30 secs, but saved 12mb).
Now when browsing around, available memory is always the same to me. 
Didnt throughfully tested, but everything works good so far.

**Comment by MiLToS666** [comment]
I'd like to try this but I think I'm doing something wrong with the build procedure. I've only built hakchi2 source before and I'm trying the same steps but helping hand fails to build with some dependencies errors. :D

**Comment by elierodrigue** [comment]
which dependency is missing? most lilkely hakchi2.exe, you can juste remove it and add a reference to your latest usable hakchi2.exe

**Comment by elierodrigue** [comment]
you could also just put the change i stated in cmenu in your mod folder and reflash custom kernel.

**Comment by elierodrigue** [comment]
i didnt do a pull request for cmenu file as i want to validate its properly working first...

**Comment by MiLToS666** [comment]
Yeah, let me try that method instead! :)

**Comment by MiLToS666** [comment]
It does take a couple more seconds when navigating folders but it's not annoying at all if it really works helps to remove all those empty folders that are created as you mentioned. 👍

**Comment by maskedmaniac** [comment]
If it's the solution to the C8/C2 errors, I may give this a try, too.

I know ClusterM reduced the chance of running into the C8/C2 error by adding a cache cleaning function while navigating folders, but since this sounds like it pretty much eliminates the chance of experiencing the error, maybe this can be incorporated into a future Hakchi2 update.

**Comment by maskedmaniac** [comment]
elierodrigue included this in the Hakchi Helper v1.2. The first time you navigate into a folder, there is about a 15-20 second delay. From that point on folder transitions are only a couple seconds at a time. I've experienced no issues with the added function yet.

**Comment by Drakonas** [comment]
Closing this as this does not need to stay open.
