### ISSUE TITLE
Famicom Mini crashes even without any mods or games added

### ISSUE THREAD

**Issue by megaStryke** [ClusterM/hakchi2#357]
I recently purchased a Famicom Mini and decided to install hakchi2 2.16 on it. I loaded some new games and added an English US translation mod then went to town. Just browsing around on the main menu, the entire screen went black, no error messages or anything. I turned the machine off an on, and each time I did, the machine would crash faster and faster.

I decided to do a clean install. Reset to factory defaults, the Famicom works as intended, so I started again. This time, I simply installed hakchi2 2.16 without any additional bells or whistles: no additional ROMs, no mods, not even any reset button combinations. And again, after browsing around the main UI for a while, the console went black.

So then I tried with 2.15 and 2.14. Again: clean installs, no additional ROMs or mods. Again, after a short while, the machine goes dead.

What could possibly be the issue here? I don't even know what kind of error this could be since I'm not getting so much as an error code thrown up on the TV.

**Comment by mrTruch** [comment]
Try the debug version and send the debuglog, maybe it will help.

**Comment by megaStryke** [comment]
Here's my debug log. When the machine crashes, all it says is "clovershell disconnected," which is what would normally happen if you turn off the console, right?

clovershell connected
cat /etc/clover/REGION # exit code: 0
Detected region: JPN
df /dev/nandc | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code: 0
mkdir -p /var/lib/hakchi/rootfs/usr/share/games/ && du -s /var/lib/hakchi/rootfs/usr/share/games/ | awk '{ print $1 }' # exit code: 0
mkdir -p /var/lib/clover/profiles/0/ && du -s /var/lib/clover/profiles/0/ | awk '{ print $1 }' # exit code: 0
NANDC size: 381.6MB, used: 27.8MB, free: 334.1MB
Used by games: 20.7MB
Used by save-states: 0.2MB
Used by other files (mods, configs, etc.): 7.0MB
Available for games: 354.8MB
clovershell disconnected

**Comment by megaStryke** [comment]
I'm beginning to wonder if I just need more juice running into the machine. I at first had the Mini plugged into my TVs USB port, then I used a spare iPhone USB adapter to plug it into the wall. The console still shut down, but only after a few minutes rather than a few seconds. Perhaps I should buy the dedicated wall adapter.

**Comment by megaStryke** [comment]
Yeah, that turned out to be the issue in the end. Just bought a Famicom Mini-specific adapter and now I'm not getting any more random shutdowns. I guess the machine simply wasn't getting enough power before. I'm going to close the issue now.
