### ISSUE TITLE
App Windows cut off

### ISSUE THREAD

**Issue by DecanFrost** [ClusterM/hakchi2#362]
Hello,  I been trying to use Hakchi2 app  on my Netbook computer, but the bottom of the apps window is cut off..  I have played with the Resolution settings and font sizes / dpi settings.

I ran a program called resizer that allows me to shrink it a little but then the bottom is all messed up and overlapping the info at the bottom.

Any suggestions or ability to add a setting to change the apps window size ?

Thank You

**Comment by elierodrigue** [comment]
being 625x675 the main form is already kind of small. This would require a complete UI rework. 
There's some registry hack to go for a 75% scaling : http://forum.notebookreview.com/threads/how-to-hack-dpi-settings-in-windows-7-likely-works-for-vista-too.588144/ but i never tried those.
