### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by SocietyDweller** [ClusterM/hakchi2#363]
Will those controllers works with the NES Classis and SNES games?

https://www.amazon.ca/HDE-2-Pack-Classic-Controller-Nintendo/dp/B00MNSLIAS/ref=sr_1_1?ie=UTF8&qid=1494346232&sr=8-1&keywords=wii+controller+pro

**Comment by elierodrigue** [comment]
Most likely, Cant be 100% sure.
