### ISSUE TITLE
Scan Lines are not being displayed correctly

### ISSUE THREAD

**Issue by hossbags2** [ClusterM/hakchi2#365]
When you choose Scan Lines in min display, screen looks like there is major RF issues, not scan lines. Screen has vertical lines like the old NES model 2.....

I am using 2.17 version

**Comment by ClusterM** [comment]
Seems like emulator problem. hakchi2 is not emulator.

**Comment by elierodrigue** [comment]
Does the issue still happen if you 1- turn off crt mode, 2 - uninstall all trace of hakchi?
