### ISSUE TITLE
Can't get past 'Waiting For Your Nes Mini'

### ISSUE THREAD

**Issue by buddhahat** [ClusterM/hakchi2#369]
I am trying to mod my Nes Mini on a Mac via Virtual box. I'm using Hakchi 2.17 but keep getting stuck on the 'Waiting For Your Nes Mini' dialog window. I'm sure I have installed the drivers.
I'm a newbie to put it mildly but any advice would be much appreciated. At the moment I just want to install two extra Nes games on there!

Many thanks in advance.

B

**Comment by D-an-W** [comment]
I had the same problem, I had already added custom modules on a fresh factory reset NES Classic but when I flashed the Custom Kernel (Again?) it worked then.

**Comment by buddhahat** [comment]
Thanks for the reply D-an-W. The following advice from user @flywithsean worked for me. I hope he won't mind me pasting it here:

> When using VirtualBox after the custom kernel is loaded on delete the USB from the USB list on virtual box in the bottom right of the screen around your windows box and add it again when it says NES and not tablet in flashing mode

**Comment by JmeG** [comment]
I'm running into this same exact issue.  I was able to load the custom kernel but now it doesn't seem to recognize the device.  

@flywithsean @buddhahat how do you "delete the USB" device within VirtualBox?

**Comment by flywithsean** [comment]
Yeah it's basically in the bottom tool box of the frame surrounding your virtual machine

**Comment by toruk-maktu** [comment]
I'm still having this problem. Can't upload games. Already had this with version hakchi 2.15
I was hopin with the new version the problem would already be fixed.
I tried everything. Im using windows. I used it on a pc with windows 10 and also XP. I also used zadig to install the driver. But after that still won't work. 

What can i do?

**Comment by buddhahat** [comment]
Have you tried @flywithsean's advice which I posted above? 
Failing that, this may seem silly -
You're aware that the Mini Nes needs to be switched on in normal mode (not flashing mode) to load the games, right? I assumed the console needed to be in flashing mode to load the games and took me a while to realise that wasn't the case. When you switch the console on (in normal mode) it takes a while for the 'Waiting' dialog to disappear and for the games to start loading.

**Comment by toruk-maktu** [comment]
Hello thanks for your reply. 
Yes ive tried that advice. But im not using a Mac. Im using windows 10 and/or XP. So i am not using virtual box. 

What do u mean with normal mode? U mean just only the power button on? So without pressing the reset button first? 
If yes .......the power button is on right now and its been one hour now. And still not uploading new games...

**Comment by toruk-maktu** [comment]
I am still at the 
'waiting for your nes mini... 
please follow the steps - turn it on etc...' 

it doesnt upload...

**Comment by buddhahat** [comment]
Hi Toruk, yes that's what I mean by normal mode. Should only take maybe 30 seconds for the upload to start so clearly there's another problem. I'm afraid I can't help beyond flywithsean's advice above. Good luck and hope you sort it soon.

**Comment by buddhahat** [comment]
Are the roms you're trying to upload .nes files, not zipped folders or anything? I'm a real noob so can't help beyond this simple advice I'm afraid!

**Comment by toruk-maktu** [comment]
Ah well thank u buddha. The files are nes files yes. They all work. But i just wanted to upload some other new games on it with the new hakchi. I hope someone has a solution with my problem.
Thank u for your time buddha. Will have 2 wait then, and hopefully a newer version of hakchi or something will fix this problem.

**Comment by sideshow01** [comment]
Are you using the Micro USB cable that came with the NES Mini? If you're using a different one which only works as a charger, then that's your problem.

**Comment by toruk-maktu** [comment]
Hello Sideshow, no i am using the one that came with the nes mini. 
But ive also tried it with another usb cable. still the same problem. Thank u for ur message....

**Comment by madmax01** [comment]
Hi guys,

i'am also completely failing here. not sure what the Issue is.

Using Windows 10  (tried on my PC and with Vmware Workstation)

checked several Videos on net. operated then based on https://www.youtube.com/watch?v=3wgs_0XlEiY
just without Mod Step.

- Dump finished
- Entering Dev Mode (Power button activ - No Light)
- Flashing original kernel > fine
  - Button is lightning - Done Button appears and Light goes off
- Powering manually off - entering again DevMode
- Flashing Custom Kernel > fine
 - Button is lightning > and seeing "Done! You can upload games to youre NES Mini now"

But in the Background i hear a Sound that the USB connection is not activ anymore. Checked with Device Manager and USBDeview.  also hakchi2 is no green Light left of the Games in the Bottom  corner.

So something happens once doing the Custom Kernel Flashing

thx

Max

**Comment by Drakonas** [comment]
This needs to be discussed on Reddit. This is a tracker to report a bug you know the problem causing said bug, not a forum to find the answer to a problem. https://www.reddit.com/r/miniSNESmods/

**Comment by Swaggachu** [comment]
I am still having this same issue when I try to use the latest Hakchi CE Version. The only way I Can load games is Hackchi 2.31 (non CE) hope this helps someone out there. I would still really like to use the latest Hakchi CE Version but no luck.
