### ISSUE TITLE
More control over folder names, and ability add folder icons?

### ISSUE THREAD

**Issue by BagginsKQ** [ClusterM/hakchi2#37]
Would it be possible to have more control over folders (as in set them by 'categories'), as well as be able to assign a graphic/artwork for easier spotting in the menu?

**Comment by T3rry12** [comment]
I agree, even if it just grabbed the first 2 characters from the first game in the folder and the first 2 characters of the last name in the folder, for example 
10 yard fight to american gladiators would be 10-Am perhaps even just have that text as the folder art, that'd be sufficient for now i think

**Comment by baconcow** [comment]
I also like the idea of having two letters representing which games are in the folders.

**Comment by BagginsKQ** [comment]
Well it would be cool if you could assign three letters to represent genre. "Act", "Adv", "RPG", etc. Then be able to place specific games into the folders.

**Comment by T3rry12** [comment]
yeah it would be ideal to just create your own structure on pc and just upload it straight across, but i was thinking baby steps, haaha

**Comment by condiczek** [comment]
https://github.com/ClusterM/hakchi2/pull/65

**Comment by T3rry12** [comment]
why do we need to create another issue for the same thing? just so you can have your name on it?

**Comment by baconcow** [comment]
What additional issue was made?

**Comment by condiczek** [comment]
He does not notice the difference between the issue and pull request / commit. Oh and my name is now here and there, yeah! Lol. Thats the main issue here 😉
