### ISSUE TITLE
Extra Modules no info shown

### ISSUE THREAD

**Issue by ifdiaz** [ClusterM/hakchi2#370]
On Modules - Install Extra Modules, when you select the modules to install on your NES Mini, no info shown about the retroarch modules, only a white screen. Previous versions before 2.17 are OK.

Thanks for the job!

**Comment by elierodrigue** [comment]
You mean that window?
![image](https://cloud.githubusercontent.com/assets/2980364/25924262/d92a5f7e-35af-11e7-800b-de4d1bfd133d.png)

**Comment by ifdiaz** [comment]
Yes, this one. Only shows the built-in modules information (music, password & remove moudules).

**Comment by elierodrigue** [comment]
This most likely have to do with the modules you download. Make sure to download them from here and follow the instructions properly 
https://github.com/ClusterM/retroarch-clover/releases/tag/0.7

**Comment by ifdiaz** [comment]
The modules are on the right place. Tried with the same files in older versions without issues. 

In hakchi 2.17 all the modules are shown correctly and can be installed without problem, but the description text of each module is not shown on the right panel (only bult-in modules show information text when you select them, the others are in blank).

Maybe my description of the issue wasn't the best, but english isn't my language. I will try to upload some pictures when i can.

Thanks again to the community.

**Comment by elierodrigue** [comment]
Can you zip your usermod folder and include it here? And maybe put a screenshot of the issue

**Comment by ifdiaz** [comment]
Yep

![screenshot_1](https://cloud.githubusercontent.com/assets/5717513/26075777/c4e26010-39b6-11e7-8a67-400cdaa71210.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/5717513/26075782/c8d7450a-39b6-11e7-984c-91cda5cd7bd2.png)

https://www.dropbox.com/s/i7jyq2sp619vssi/user_mods.zip?dl=0

**Comment by elierodrigue** [comment]
Try running hakchi as administrator and make sure that you have file permissions.
They work great on my side. It seems like hakchi cant read the content of the file on your end.

**Comment by elierodrigue** [comment]
I'll mark as close for now, if you are 100% sure its not related to file permission, please reopen it.

**Comment by ifdiaz** [comment]
I forgot to comment that the issue only occurs on hakchi installer version, portable version it's alright. Now that installer version was updated to 2.17b also was fixed.
