### ISSUE TITLE
Multiple selection: SHIFT & CTRL shortcuts

### ISSUE THREAD

**Issue by igoticecream** [ClusterM/hakchi2#371]
Hello @ClusterM 

I'd like to request these selection shortcuts:

CTRL+A: Select All
SHIFT+Mouse click: Select all elements between
CTRL+Mouse click: Add elements to the selected list

Those are pretty common shortcuts on Windows. I hope you get the chance to include them on hakchi2

Since we are able to add 3.000 games, it can be pretty annoying to manage them one by one :(

**Comment by KMFDManic** [comment]
Heh, you must have seen my post about this on Reddit, heh.

**Comment by elierodrigue** [comment]
Its not as simple as it sounds. To do that, we need to change the controls used for selection. The treeview in current git version does help a lot with that. So for now its a wont do, but definatly something in the "Nice to have" list.
