### ISSUE TITLE
Controller Hack always: Active "Even when De-Ticked"

### ISSUE THREAD

**Issue by dwynator** [ClusterM/hakchi2#372]
Hello ClusterM,

Title already tells. The controller hack stays enabled 
no matter if it is enabled or disabled from Hakchi2 menu. Pressing Select+Down will return you to the 
Home-/screen.
Maybe something you could look into?

Thanks for the great application!

Kind regards

**Comment by elierodrigue** [comment]
indeed, the check is not bound to anything. @ClusterM  if you can have a look, it seems like its not part of the settings sent to the config file on the nes classic.

**Comment by ClusterM** [comment]
Fixed.
