### ISSUE TITLE
Doom port compatibility?

### ISSUE THREAD

**Issue by BasicObject** [ClusterM/hakchi2#373]
I saw this for libretro. It's called [libretro-prboom](https://github.com/libretro/libretro-prboom) Is it possible this could be ported over? I may be able to help test it. Also wanted to thank everyone working on this project. Thanks!

**Comment by baconcow** [comment]
You should post this question in the [retroarch-clover repository](https://github.com/ClusterM/retroarch-clover) as it deals with the retroarch modules.

**Comment by BasicObject** [comment]
Thanks I'll post this there. Appreciate the help!

**Comment by seanrox** [comment]
Now that you have it posted in the proper area, it would be appreciated if you could close this issue so it helps to clean up the open issues queue...
