### ISSUE TITLE
ps4 controller nes classic/mini wont map

### ISSUE THREAD

**Issue by thrashology** [ClusterM/hakchi2#374]
Hi, I bought a 8bit receiver for the nes classic thinking that i would be able to just connect my ps4 controller wireless but it only the 4 main buttons work (X, O, triangle, square). the triggers cannot be auto mapped and 2 buttons always remain as auto-fire cant figure out how to change it. Is there anyway or has anyone figured out how to map the ps4 controller to the controller settings on the retroarch. I am trying to get it to work for SNES, SEGA, N64. I messed up the controls soooo bad in the settings that i had to uninstall retro arch and reinstall it to get it back to defaults. wish there was some way easier but its the only thing that works. I guess i could just buy the 8bit nes30 controller which apparently does have the correct firmware to work with the nes classic. Any insight would be helpful. Thanks in advanced!

**Comment by NaikiTurincondeliphone** [comment]
Hello, you have to install version 1.05 beta 0, you can find it here: http://forum.8bitdo.com/forum.php?mod=attachment&aid=NTMxfDJhNjg5OWMzfDE0ODgwMTYwODF8MHwxNDA0

**Comment by Cat797** [comment]
Hello, I have the same problem and the links to firmware v1.05 Beta0 are all broken now. It seems 8bitdo has taken that FW down from their page. Does anyone have a link to this FW somewhere else?
-Thanks

**Comment by Beylie** [comment]
https://drive.google.com/open?id=0B51ZHT9zNZWCczBXMWhHUnFqZUk

**Comment by thrashology** [comment]
Hey guys, well i cant get it to work on the ps4 controller... when it gets to sega games its almost impossible to map out the dam C key lol and for 64 it gets confusing as well. What you have to do is buy a 8bitdo Nes30pro controller. This controller with the v.1.72 firm ware and the 1.05beta that Beylie was so kind to provide will make the nes30 conroller work "like butter". check out this dudes video. download on links of video and get the FW from Beylies link. nes, snes and 64 working good so far. but genesis still wont map out C key......

**Comment by Drakonas** [comment]
This needs to be discussed on Reddit. This is not a Hakchi problem but a problem with 8bitdo. 8bitdo released 1.07 firmware that should have fixed this.
