### ISSUE TITLE
Certain games not working with NES Mini

### ISSUE THREAD

**Issue by TheLegendofChaz** [ClusterM/hakchi2#375]
Hi there, so I'm sure a lot of you are aware of the games that aren't currently playable on the NES Mini that use special chips like Batman: Return of the Joker and games like Lagrange Point for the Famicom. I was wondering if any future updates of hackchi would possibly be able to allow these games to be played?

**Comment by elierodrigue** [comment]
You can install the retroarch module and upload any other roms.
https://github.com/ClusterM/retroarch-clover
