### ISSUE TITLE
Feature request:  Disable anti-aliasing

### ISSUE THREAD

**Issue by bob12111** [ClusterM/hakchi2#376]
If you look closely at the sprites, they have been anti-aliased, or rounded.  The effect is particularly bad where there is brownish over green.  For example, in Super Mario Bros, take a look at how rounded Mario's shoulders look when he's standing in front of one of the dark green hills, vs standing against the sky or black areas.  Would it be possible to disable this effect?

**Comment by Drakonas** [comment]
Why don't you try turning on pixel perfect mode in the (S)NES Classic menu. This is not a Hakchi problem.

**Comment by bob12111** [comment]
I do have pixel perfect on.  But yeah, it doesn't seem to be the anti-aliasing, but how my TV upscaled from 720p to 1080p...  Maybe if hakchi could upscale the output to 1080p...?

**Comment by Drakonas** [comment]
lol. That's a SNES Classic issue my friend. That would require much more processing. Hakchi cannot fix this. Closing.
