### ISSUE TITLE
While dumping kernel I get "Can't write to USB" (2.17)

### ISSUE THREAD

**Issue by thegrandmaw** [ClusterM/hakchi2#378]
Title

**Comment by PATWIST** [comment]
Hello, did you used original USB cable from Nintendo? Try using different USB cable. My original works good but I have another which dont work great even with mobile phone.

**Comment by elierodrigue** [comment]
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems

Most likely a cable issue, or a config issue if you are using a virtual windows setup on mac.
