### ISSUE TITLE
Added images are made bigger and degrades quality

### ISSUE THREAD

**Issue by Beylie** [ClusterM/hakchi2#379]
I've just added a few snaps from MAME extras as covers to some of my games. The file sizes of the snaps increase by a factor of 6-7 times and the quality is degraded in the process. 

Example: [http://imgur.com/a/xYLNJ](url)

**Comment by Beylie** [comment]
![clv-z-gqwgp](https://cloud.githubusercontent.com/assets/28935079/26423908/b8dfe43e-40cf-11e7-8d4c-7757d7db2779.png)
![offroadt2p](https://cloud.githubusercontent.com/assets/28935079/26423909/b8e34458-40cf-11e7-9b11-26eb493e0d3c.png)
![clv-z-skoqy](https://cloud.githubusercontent.com/assets/28935079/26423954/d5a0014e-40cf-11e7-955b-3537836b3ab5.png)
![tnzsoa](https://cloud.githubusercontent.com/assets/28935079/26423955/d5a03f42-40cf-11e7-947e-3ae43efd866e.png)

**Comment by Beylie** [comment]
@ClusterM Do you need more examples? Or is this expected behaviour?

**Comment by Drakonas** [comment]
This should have been fixed since time of writing.
