### ISSUE TITLE
8bitdo bluetooth reciever not able to map buttons correctly

### ISSUE THREAD

**Issue by Cat797** [ClusterM/hakchi2#381]
Hi,

I have a 8bitdo mini nes receiver and want to configure my wireless gamepads with retroarch.
I have read in several forums that you need to update the receiver firmware to v1.05 beta0 (in order to map X, Y, L & R buttons in SNES). The only thing is that all forums that suggest this solution all share the same link to this FW and that link is now broken!
I have tried googling for it and also the 8bitdo homepage and also emailed the support but still no luck..

Can someone plz share this FW?

**Comment by NaikiTurincondeliphone** [comment]
Hi:

Here 👍 https://goo.gl/z0U4Xp

**Comment by Cat797** [comment]
Thank you soo much!!
Now everything works! Time for some SNES:)))
