### ISSUE TITLE
Problem with cyrillic app path

### ISSUE THREAD

**Issue by paukonen** [ClusterM/hakchi2#383]
Program throws exceptions endlessly when installed on OS with cyrillic user name with web installer.
Seems that something is wrong with encodings handling.
When I unpack portable version in a folder with only latin symbols in a name everything works just fine.
Exception text:

**Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.NotSupportedException: Данный формат пути не поддерживается.
   в System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath)
   в System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   в System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   в System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String[] pathList, Boolean checkForDuplicates, Boolean needFullPath)
   в System.IO.Directory.CreateDirectory(String path, DirectorySecurity directorySecurity)
   в com.clusterrr.hakchi_gui.ConfigIni.Save()
   в System.Windows.Forms.Form.OnShown(EventArgs e)
   в System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   в System.Threading.ExecutionContext.runTryCode(Object userData)
   в System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   в System.Windows.Forms.Control.InvokeMarshaledCallbacks()

************** Загруженные сборки **************
mscorlib
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
hakchi
    Версия сборки: 2.0.17.31
    Версия Win32: 2.0.17.31
    CodeBase: file:///C:/Users/Саша/AppData/Local/Apps/2.0/M59XOL2C.K5K/XX7M8WEJ.3EJ/hakc..tion_ac3ed33da7b15b8c_0002.0000_698c458441f4991b/hakchi.exe
----------------------------------------
System
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Deployment
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Deployment/2.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Drawing
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
Accessibility
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
hakchi.resources
    Версия сборки: 2.0.17.31
    Версия Win32: 2.0.17.31
    CodeBase: file:///C:/Users/Саша/AppData/Local/Apps/2.0/M59XOL2C.K5K/XX7M8WEJ.3EJ/hakc..tion_ac3ed33da7b15b8c_0002.0000_698c458441f4991b/languages/ru-RU/hakchi.resources.DLL
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 2.0.0.0
    Версия Win32: 2.0.50727.8784 (WinRel.050727-8700)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
System.Core
    Версия сборки: 3.5.0.0
    Версия Win32: 3.5.30729.8795 built by: WinRel
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.**

**Comment by ClusterM** [comment]
This is Windows 10 problem, not cyrillic bug. Fixed.
Sorry that not so fast.
