### ISSUE TITLE
Reset from controller not working

### ISSUE THREAD

**Issue by duanejoh** [ClusterM/hakchi2#384]
I've added games, and everything is working great, except the reset from the controller.  It doesn't seem to do anything.  It's selected in the Settings menu and I have the default buttons selected.  Any ideas?

Duane Johnson.

**Comment by BasicObject** [comment]
This happened to me last night. It seemed like the reset worked for the added NES ROMs but not for the default ROM set. Didn't thoroughly test this though.

**Comment by duanejoh** [comment]
Turns out I wasn't holding the buttons down long enough.  Seems to working for me now!
