### ISSUE TITLE
Sonic The Hedgehog 3 does not work

### ISSUE THREAD

**Issue by jayden051209** [ClusterM/hakchi2#385]
I put sonic 3 on my Nintendo  classic  and when i open it it takes me to the same place it was

**Comment by sideshow01** [comment]
You need to rename the command line arguments from bin to md.

**Comment by jayden051209** [comment]
how do you do that

**Comment by Mad-Mega** [comment]
Did you install Retro-Arch ?

**Comment by ghost** [comment]
Yes

**Comment by Mad-Mega** [comment]
What kind of hmods did you install also ?
What file extension is Sonic 3 ?

**Comment by ghost** [comment]
I use the retroarch.hmod file and the sonic the hedgehog 3 zip
Here is the command line for sonic the hedgehog 3                             /bin/md /usr/share/games/nes/kachikachi/CLV-G-SSIFW/Sonic_the_Hedgehog_3__USA_.md

**Comment by Mad-Mega** [comment]
Can you load other Sega Genesis/Megadrive games ?
