### ISSUE TITLE
Shutting down failure

### ISSUE THREAD

**Issue by JohnSilver78** [ClusterM/hakchi2#386]
My nintendo mini has shut down a few times since version 2.17 and I do not know why. This had not happened before. I'm using a wireless my arcade controller, I searched the net and read that sometimes this may be the cause, but I did not understand why. It does not happen often, but yesterday I suddenly went out twice, the sign of shutting down came out. Any advice? Thanks.

**Comment by ClusterM** [comment]
Hi.
Try to check your power supply, try other power source.

**Comment by JohnSilver78** [comment]
Thank you very much master. Is better now :)
