### ISSUE TITLE
Star Wars is unplayable.

### ISSUE THREAD

**Issue by kylejc86** [ClusterM/hakchi2#39]
Star Wars loads fine but the image shows half the screen fine but the other half is different making the game unplayable. Could this please be looked into.

Thanks

**Comment by baconcow** [comment]
This application does not change how the NESCE plays ROMs. Outside of some included patches, the functionality of the NESCE is as it was originally developed. The best place to discuss ROM compatibility is [here](https://www.reddit.com/r/nesclassicmods/comments/5mpyxg/is_my_rom_x_working_megathreadconsolidation/). You may notice, on the spreadsheet that a Reddit member has already listed Star Wars (USA) as partially working and notes that the first level is glitched and unplayable.

**Comment by mlabarca** [comment]
I'd close this and point any further issues about x game to that list. maybe even link it in the readme.md
