### ISSUE TITLE
Someone now hot to play sonic 3 and rainbow dahs

### ISSUE THREAD

**Issue by SamBuijar** [ClusterM/hakchi2#390]

**Comment by Mad-Mega** [comment]
Install retro-arch !

**Comment by SamBuijar** [comment]
I have do it but i think the problem is with the ips patch because when i patch the game and i started on the nes mini the screen keeps black

**Comment by Mad-Mega** [comment]
Try to run it on a Windows emulator to see if it works, if it works there, you patched it correctly, if not, than patch it again.
I have had no problems with both games running on the NES mini, but mine aren't patched.

**Comment by SamBuijar** [comment]
It is the same thing but in one the screen keeps black and in the other one appear this, i think this is the thing that appear when you try a pirate version of sonic 3 in the sega genesis 
![title_screen_blue_sphere](https://user-images.githubusercontent.com/26920200/27001302-042dfefa-4e1b-11e7-9d10-d52c18e07782.png)

**Comment by Mad-Mega** [comment]
What patch are you trying to run ?

**Comment by SamBuijar** [comment]
I using luna ips patcher for apply the patch sonic 3 and apply the patch sonic 3 and rainbow dash

**Comment by Mad-Mega** [comment]
But what patch ?
Those games do not need any patch.

**Comment by SamBuijar** [comment]
You can't play Sonic 3 and Rainbowdash without appliyng that patch(sonic 3 and rainbow dash) to a sonic 3 rom

**Comment by Mad-Mega** [comment]
Ah i understand

**Comment by Mad-Mega** [comment]
Take a look at this YouTube movie
https://www.youtube.com/watch?v=EMsS9RMj3JA
In the credits there might be a link to what you need

**Comment by SamBuijar** [comment]
I download the file but when i played doesnt start just flash and send me to the menu of the nes mini

**Comment by Mad-Mega** [comment]
Did you enter /bin/md in the command line of Hakchi ?

**Comment by SamBuijar** [comment]
Thank you so much now i can play it
