### ISSUE TITLE
Mysterious Murasame Castle

### ISSUE THREAD

**Issue by ArcadiaMagik** [ClusterM/hakchi2#391]
Hello, I am having an issue with the game Mysterious Murasame Castle (Nazo no Murasamejou) on my Famicom Mini. I am able to get to the title/character select screen, create a file, but then I get hung up on a "Please set disk side B" command screen. No button commands will change the disk side and I can't figure it out...

My question is: Is there a secret button command for changing disks? I have already set custom command lines and had no luck with that either, unless I've missed something or there's a command line I don't know about...I'm determined to get this game working, since it does start just fine.

Thank you and sorry if this question has already been asked. I've found no solutions through Google.

**Comment by Mad-Mega** [comment]
Have you installed Retro-Arch ?

**Comment by ArcadiaMagik** [comment]
I don't have RetroArch installed, although I do know there is a fix for this game through that. Was just hoping maybe there was a fix outside of having to install that. It seems like such a small thing just to be able to switch disks, seeing as the other Famicom Disk games on there work just fine with it. Metroid for example switches disks just fine on a button press, but Murasame does not...

**Comment by Mad-Mega** [comment]
It can only be played with a emu packed with Retro-Arch, that is the only way to map a button to switch the disc.
And yes, some games do work but others, like this, don't.

**Comment by 1lokolo1** [comment]
Check my videos this game is playable from a long time...
https://www.youtube.com/watch?v=IyYNCGTDOQc

Also I made this english Tutorial for anyone can DIY:
https://www.youtube.com/watch?v=j2XBmz7eoBY

Rgs.

**Comment by rhester72** [comment]
You can also convert the FDS to the "native" Nintendo QD format and then kachikachi will run it with disk swaps mapped to Start without issue, no Retroarch required.

**Comment by Drakonas** [comment]
Closing this as this needs to be discussed on Reddit rather than here. https://www.reddit.com/r/miniSNESmods/
