### ISSUE TITLE
NES Classic turns on and off right after reaching the games menu

### ISSUE THREAD

**Issue by zippyjake** [ClusterM/hakchi2#392]
After uploading some custom roms to my NES classic Edition it just wont boot properly to game menu

**Comment by Mad-Mega** [comment]
Can you elaborate ?
What windows version you are running, what Hakchi version, did you install Retro-Arch, what games ?

**Comment by RaZer0k** [comment]
same happen to me... i have to flash original kernel then flash again custom kernel...
this happen every time... i sync games to the miniNes then after reboot from hakchi screen... the console poweroff when enter to menu screen... hen i turn it on... and not problem... but this happen every time i sync games.

**Comment by Drakonas** [comment]
Closing this as this needs to be discussed on Reddit rather than here. https://www.reddit.com/r/miniSNESmods/
