### ISSUE TITLE
I have a third party controller, all buttons respond but the triggers

### ISSUE THREAD

**Issue by samrobac** [ClusterM/hakchi2#394]
I have no idea if it's the controllers themselves or something with the program, but I have the configuration set to the proper buttons, yet they still don't work,

any ideas?

**Comment by SamBuijar** [comment]
I have one that doesn't work at all

**Comment by Simulant87** [comment]
I have this 3ed party Controller: https://www.amazon.de/dp/B06WLGHZVQ
And extended my NES classic mini with hakchi2.17d to contain SNES games.

Not a single button of the controller is working in the games menu. Has anyone a clue how I could bring it to work?

**Comment by Drakonas** [comment]
Closing this as this needs to be discussed on Reddit rather than here. https://www.reddit.com/r/miniSNESmods/
