### ISSUE TITLE
Simple Question For Alexey (Is it possible to run the NES Classic Mini GUI outside of the Mini Hardware)

### ISSUE THREAD

**Issue by MattMan76** [ClusterM/hakchi2#397]
Since you know the technical side of this system as well as anyone I wanted to ask you this quick question. 

Is it possible to run the NES Classic Mini GUI outside of the Mini Hardware?  I ask because many, many, people want to do this who cannot get their hands on the actual NES Classic Mini hardware want to experience the well made GUI.  I would think it would be something simple to run that GUI on different hardware running Linux. 

What do you think?  

Sorry if this is the wrong place for this question.
Matt

**Comment by KapUttyy** [comment]
I think it is possible, but as the GUI itself is Intellectual property of Nintendo it would be a matter of piracy to publish the GUI for running it elsewhere than on the original Hardware. You'd have to extract everything on your own.

**Comment by MattMan76** [comment]
I was thinking because Nintendo has stopped making and selling the Mini that others could implement it on their own personal hardware. But, yes you are correct it would be illegal to make money from using the GUI in any way, and maybe not even a good idea to do it at all. 
Thank you very much for the reply!

**Comment by ClusterM** [comment]
Hi.
Someone already tried to do it. Yes, it's possible in theory.

**Comment by KapUttyy** [comment]
It would not only be illegal to make Money from it. If you would share this for example in Germany it would be handled as a Copyright infringement if Nintendo recognizes the release.
It is their own property.
But if you extract and mod it on your own to your own devices, it should bei okay.
