### ISSUE TITLE
Requesting the ability to add a game more than once. 

### ISSUE THREAD

**Issue by fuzzdistor** [ClusterM/hakchi2#398]
Hi there! Thanks for the tool :D It's awesome and I love it.
The feature I'm requesting is the ability to add a game more than once. That is the most simple solution I can think of for having a lot of "easy to access" save states. I practice games for speedrunning purposes and having a rom for every stage with quick saves set up is a solution I already use in the wii homebrew emulator fceugx, because a lot of savefiles makes the save menu take a lot of time to show every savestate. Without that feature I get to have only 4 saves per game making specific section practice a lot of work to get to.

**Comment by Drakonas** [comment]
You can rename the rom and add and it will produce a different entry.
