### ISSUE TITLE
I cant make save states for non nes games

### ISSUE THREAD

**Issue by riles200199** [ClusterM/hakchi2#399]
I had added games to my nes mini a while back and everything was fine but then yesterday i added some more games using a newer version and now I can only make save states for my nes games and I cant load save states for other games that i had made before

**Comment by ghost** [comment]
If you can't make save states for non nes games then try deleting all the folders in the games folder WARNING This might delete all your NES games and the non nes games which means you will only have the 30 games.

**Comment by Drakonas** [comment]
Closing this as the OP has not responded.
