### ISSUE TITLE
Missing Mappers

### ISSUE THREAD

**Issue by Spottedfeather** [ClusterM/hakchi2#40]
There are several games that I'd like to add, but it says that the mappers don't work. Would it be possible to patch games for mapper #11 and mapper #69 ? I'd like to add Bible Adventures, Bible Buffet, and Batman Return Of The Joker.

**Comment by fstkaz** [comment]
No

**Comment by Spottedfeather** [comment]
Oh. That's too bad. Oh, well. At least I can still play the games on my computer....

**Comment by BagginsKQ** [comment]
or possibly a hacked wii if you have access to one.... In which case you can still use you the Wii compatible NES Mini controller.

**Comment by baconcow** [comment]
There is a good discussion [here](https://www.reddit.com/r/nesclassicmods/comments/5mpyxg/is_my_rom_x_working_megathreadconsolidation/) on which ROMs work.
