### ISSUE TITLE
Problem after  adding games

### ISSUE THREAD

**Issue by Ilrain** [ClusterM/hakchi2#401]
I have added games successfully(they can be seen at the screen) but when I turn on the nintendo mini the controls do not work.  
Everything goes back to normal when I go back to the factory mode but if I try to add games, the problem persists. 
I am using windows 10, I have used hakchi2 2,17 and 2,15 and installed the retroarch.

**Comment by Mad-Mega** [comment]
Try to install 2,14b

**Comment by Ilrain** [comment]
Apparently it might be related to the controller that is used. For example, if I use the original with which the nintendo came with, I have no problems.

**Comment by ClusterM** [comment]
Can you read log from /dev/clovercon_debug ? You can use Telnet or FTP to do it.

**Comment by Ilrain** [comment]
I do not know how to do that. If you could guide me, I think I most likely could do so.

**Comment by Drakonas** [comment]
Ask for this on reddit next time. This is not a personal help line but for submitting bugs with Hakchi.
