### ISSUE TITLE
Theme's wont work

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#402]
When you add the color ui and ui hack modules it doesn't show the words for the games

**Comment by chiefthief** [comment]
you are using too much of the available free memory. you need to remove games and or remove unused save states so you are comfortably enough under the memory limit to save and run games

**Comment by ghost** [comment]
I only have the 30 games and then the modules

**Comment by ClusterM** [comment]
Which modules are installed?

**Comment by ghost** [comment]
The snes9x2010 and retroarch

**Comment by ClusterM** [comment]
Can you try to start RetroArch manually (via CloverApp) and start game manually, via menu?

**Comment by ghost** [comment]
The problem is that i don't have the cores folder

**Comment by ClusterM** [comment]
What you mean?

**Comment by ghost** [comment]
how would i put the games

**Comment by ClusterM** [comment]
As usual, using hakchi.

**Comment by ghost** [comment]
Can i use the super FX chip with the modules and the rom Star Fox 2 Modules Snes9x and retroarch
