### ISSUE TITLE
USB Disconnecting after Custom-Firmware flashed

### ISSUE THREAD

**Issue by madmax01** [ClusterM/hakchi2#405]
Hi guys,

i'am completely failing to get roms on my nes.

Using Windows 10 (tried on my PC and with Vmware Workstation)

checked several Videos on net. operated then based on https://www.youtube.com/watch?v=3wgs_0XlEiY
just without Mod Step.

- Dump finished
- Entering Dev Mode (Power button activ - No Light)
- Flashing original kernel > fine
- Button is lightning red - Done Button appears and Light goes off
- Powering manually off - entering again DevMode
- Flashing Custom Kernel > fine
- Button is lightning red > and seeing "Done! You can upload games to youre NES Mini now"
- But in the Background i hear a Sound that the USB connection is not activ anymore. Checked with Device - Manager and USBDeview. also hakchi2 is no green Light left of the Games in the Bottom corner.

So seems something is happening incorrectly once doing the Custom Flashing. 

not sure how often i tried now > i have no Clue.

thx

Max

**Comment by Mad-Mega** [comment]
Are you using the original USB cable that came with the NES mini ?
Try different USB ports on your windows.
Maybe delete all the USB drivers in your windows, and reboot.

**Comment by madmax01** [comment]
Hi Mad-Mega,

thx for the Answer

i use the Default USB Cable which was shipped with Nes.

so the Nes is recognized in the Dev-Mode > so assuming nothing wrong with the Cable.

sure i already tested differently PC USB Ports.  different 2.0 and different 3.0 Ports

the Issue is only once Custom Firmware is done > then the USB getting automized Disconnected.  So that seems is somehow a controlled Process > as it happens everytime same.

Best regards

Max

**Comment by ClusterM** [comment]
There is no any device in device manager at all? Seems like clovershell daemon is not started for some reason.

**Comment by madmax01** [comment]
Hi ClusterM,

thx.  so once i go into DevMode  the USB Device "NES Mini"  shows up in the Device Manager - and i see it also with USBDeview.

if i flush the Custom - Firmware - it's proceeding normally. (uploading, Executing command,.....,verfiying etc,....) > red light is on > 

Exactly at this Point (Executing command: boota 43800000 USB getting disconnected > and next i see the "Done! You can upload games to youre NES Mini now" :
  
![image](https://user-images.githubusercontent.com/5938215/27912722-1cbf514c-625e-11e7-8338-1743889e1fd3.png)


this are screens before custom flash:


![usb-infos](https://user-images.githubusercontent.com/5938215/27912579-be1b89bc-625d-11e7-8934-ca6e05bc1427.png)
![usb-view](https://user-images.githubusercontent.com/5938215/27912578-be1b59f6-625d-11e7-825f-bcf9822ad914.png)

This is after the Flash:

![usb-after-flash](https://user-images.githubusercontent.com/5938215/27912828-7386b344-625e-11e7-8598-f16670916dd6.png)

also what i saw is that the Device is flagged for "Safe to Unplug"

**Comment by madmax01** [comment]
Ok found out something.

Seems there are 2 different  Device Names

CLV-S-NESY
NES Mini

seems  Windows struggled to find an "usb discriptor Info"  for CLV-S-NESY

only saw NES Mini so far.

Got it fixed now. manually cleared all USB-Ports again - and added it to usb 3.0.

now as able to recognize both. i don't switch away again testing other ports. ha

thx guys
