### ISSUE TITLE
C8 error under 2.17

### ISSUE THREAD

**Issue by ledste** [ClusterM/hakchi2#406]
Hello,
I had c8 error using these settings:
hakchi 2.17.41
I loaded 137 games + 30 already in nes memory for a total of 167
Rom leaded with U! or J!, 99% U a some with J
In Setting: enable used extended fonts, disable expilepsy, enable comprress non NES etc
In page / folder structure: disable / page folder and max number of games per pag 30
After some time, and I think it's screen saver or demo software, (but not sure) the C8 error appears

Then
I just changed in setting / page folder structure: pages, split games equally and I leaded this configuration
I left turned on the mini nes for more then 1 hour, approx 1,20 hour
Now all it seems fine

Stefano

**Comment by ghost** [comment]
You Might had put a console game not for the nes and clicked it

**Comment by ledste** [comment]
No it's not like this. I loaded all the games for nes with: 

name of the game (U) [!].nes

I'm sure 100%.

I think the problem is if you remove the folders then the system has too much games in the root and chrash anyway correct me if I'm wrong. 

Thanks

**Comment by ClusterM** [comment]
So, how many items were on screen? Seems like it's usual out-of-memory condition.

**Comment by ledste** [comment]
The total number of icons (games) on the root directory is 167 (30+137); it's then impossible to use the software function to remove directories and having all the games in the root. I don't like folders but I must use them becasue otherwise the C8 errors appears. Can these info help you or need somenthig esle?

**Comment by ghost** [comment]
Just checking in to let you know I experienced another C8 error myself. I had been using 2.17, NES games only, 30 games per page, and had Hakchi Helper installed to help clear out blank folders when transitioning in an out of pages (to further help prevent C8 errors).

I've played that set up without any issue for several hours worth of gameplay, spread out over the course of a month. Last night I was playing a few games, then went to the "Original 30 Games" page and tried to open Super Mario Bros., and the screen went dark and froze. I hit the power button, and the C8 error came up.

I may be done modding my NESC. I've ran into the C8 error about half a dozen times now, over several builds of Hakchi2 (uninstalling Hakchi2 each time and installing each new version of Hakchi2 from a factory setup), and all while using Hakchi2's recommended settings when installing each new version. I've always been nervous that these C8 errors could be damaging the system in the long run, and I've come across the error enough that I question now if modding the console is worth the risk.

I thank you ClusterM for all your hard work, and wish you the best of luck on your continued work on Hakchi2!

**Comment by JohnSilver78** [comment]
I had the same problem when I added more games, but putting them in folders and folders with only 30 games in each one worked perfectly. But if I leave them loose, unless they are thirty or less, the memory collapses and the error occurs.

**Comment by ledste** [comment]
Actually I have zero games in the root, 167 games divided in 4 folders each of max 50 games (42+42+42+41) and it's wotking fine. I think 50 or maybe 60 games per folder is the limit.

**Comment by zeusz4u** [comment]
try maximum of 40 games per folder, it also helps because all the thumbnails will fit in one page.

I've only encountered errors with SNES games when my storage was almost full... but since now i've left around 50 megs of free space I don't have any issues (only running NES games on the console).

**Comment by ledste** [comment]
ok thank you I will try in the next days.

Stefano

**Comment by angelbless** [comment]
I got that error too. How do you fix the memory issues? Everything was working fine. I tried installing some new games, I got a shell something, insufficiente memory error. Then when booting, error C8 appeared.

**Comment by JohnSilver78** [comment]
What work for me was to put them in folders and never more than 30 games per page, some say 40 games, likewise try not to reach the memory limit that marks the Hakchi.

**Comment by angelbless** [comment]
Thxs for writing back @JohnSilver78.. I have them in folders of 30... in fact, the error occurred after I made my last folder. Any suggestion on how to "free" memory and start over?... Do I have to unselect everything and load again?

**Comment by JohnSilver78** [comment]
You should delete a couple of games and save states and see what happens. Too much memory should be in use

**Comment by angelbless** [comment]
Thxs @JohnSilver78 ! that and @MDFMKanic suggestions helped me solve the trouble.

**Comment by ledste** [comment]
My NES with 40 games per folder works perfectly. I think it's necessary and investigation from developers of hakchi2 to better understand why this out of memory happend.

**Comment by ghost** [comment]
Though steps have been made to reduce the chance of C8 errors, it's still unclear what exactly causes the C8/C2 error. Your set up may be running fine right now, but you could still experience a C8 error sometime down the road.

I've hit a C8 error at least once in every build of Hakchi2 I've used, even when using ClusterM's recommended settings.

It may be a harmless error (just a simple reboot of the console to get back up and running - no real damage to the system itself), but since we can't pinpoint the exact cause, we don't know for sure.
