### ISSUE TITLE
Classic crashes

### ISSUE THREAD

**Issue by chasnotchaz** [ClusterM/hakchi2#407]
Ever since I installed hackchi (I have tried a few versions) I have had problems.  I can select about three or four games before the system flashes on and off.  I have tried installing a different amount of games but the results are the same.  Currently I have only about 160 games installed each in folders of 30.  I don't normally get the c8 error either.  It just flashes off and on.   What could I have done?  People seem to have no problems yet I am experiencing this.

**Comment by ledste** [comment]
I never experienced this kind of problem.

**Comment by Mad-Mega** [comment]
There might be a bad rom in there.
Best thing you could do is uninstall every hmod, uninstall hacki2 and put it back in original mode.
Then re-install hacki2 and install the games.
Test it first with 10 games...and build from there, test all the games before you add more.

**Comment by chasnotchaz** [comment]
Is it possible a bad rom included that I haven't played yet could be a cause?   So far I can get the games to play but when I reset to go back to the main menu after a few tries, this is where I experience it.  Thanks again.

**Comment by Drakonas** [comment]
@chasnotchaz did you ever get this resolved? Please close the issue if so.

**Comment by qurn78** [comment]
I had the same issue. Your box art is too large. I dont know why this was the case, but when I went through my library, and grabbed art that was around 600 pixels tall by whatever, I quit having this issue.

**Comment by chasnotchaz** [comment]
Omg!  I think that’s it!  I went through and severely downsized box art and haven’t had the problem.  Hope it continues.  Unfortunately I originally only captured the first option when I google searched.  Not sure why this would cause the problem.

**Comment by Drakonas** [comment]
@chasnotchaz Artwork related bugs have been fixed in recent versions, but the old artwork from the older versions would have still been present from old installs. That's why you redoing the boxart fixed your problem. This should not be an issue anymore.
