### ISSUE TITLE
Add GB games, NES already hacked

### ISSUE THREAD

**Issue by falcocerr** [ClusterM/hakchi2#409]
I already added games to my NES, I want to add new game boy games but I can't do it
Can someone explain me how to?

**Comment by warlockv2** [comment]
add the roms the same way you would add nes games.  long as you have an updated version of hakchi you should be fine.  make sure you have the retroarch mod installed and actrivated

**Comment by falcocerr** [comment]
Thanks but not sure how it's working
I've been able to add new games ( not following instructions I just turn the nes on) but to install modules I get stuck on a black screen that says "installing wdi driver with <nesmini.inf> at <usb_driver>", I wait for an hour and nothing...
