### ISSUE TITLE
Gun Nac scrambled text

### ISSUE THREAD

**Issue by thrasherx** [ClusterM/hakchi2#41]
The game is playable but the text is indecipherable. Keep up the great work!

**Comment by baconcow** [comment]
This is an issue of the emulator, not the hackchi2 application. There is a good discussion [here](https://www.reddit.com/r/nesclassicmods/comments/5mpyxg/is_my_rom_x_working_megathreadconsolidation/) on which ROMs work and do not work. On a side note, I can confirm I get the same issue as you with this game.
