### ISSUE TITLE
USB Gamepads

### ISSUE THREAD

**Issue by CxxCat** [ClusterM/hakchi2#411]
Is it possible to attach USB gamepad?

**Comment by ClusterM** [comment]
Yes but some soldering skills are required.

**Comment by CxxCat** [comment]
It is not a big deal. Could you give me some manual?

**Comment by ClusterM** [comment]
No, I have not done it. You need to solder OTG pin. But also you need to rebuild kernel for it.

Also you can build and use USB -> I2C adapter.

**Comment by DNA64** [comment]
Just curious why you wanted to use USB gamepads vs Bluetooth (w/ Nincade adapter)?

**Comment by CxxCat** [comment]
It's my point of interests, because I have some controllers like snes with USB. I thought that the true way exists. For example read/write operations via usb-hub connected to nes mini. If we have no idea how to do that I can close the issue.

**Comment by Drakonas** [comment]
Please leave questions like this on reddit or Discord next time. This is a bug tracker for hakchi,
