### ISSUE TITLE
v2.17 download changed?

### ISSUE THREAD

**Issue by teknowledgist** [ClusterM/hakchi2#412]
The current v2.17 .zip download checksum isn't matching the checksum for the "same" v2.17 download (and independently verified) on June 2.   

I don't know when in the last 6 weeks the change occurred.  I also don't have the earlier download, only the checksum.  Obviously, something must be different, but I cannot find any mention of changes.

Any comments?

**Comment by ClusterM** [comment]
I'm updating translations. Minor versions number should be different. You can track changes via commits.

**Comment by teknowledgist** [comment]
Any chance you could include the minor version number somewhere on the web pages or change log?  Thanks.

**Comment by ledste** [comment]
Need help for italian words?

**Comment by ClusterM** [comment]
@teknowledgist you can check commits list on "stable" branch.

@ledste but it already has italian translation.

**Comment by ledste** [comment]
Yes,

 

italian translation is already fine, if you need translation in the future I can help.

 

Bye

 

Stefano

 

Da: ClusterM [mailto:notifications@github.com] 
Inviato: mercoledì 9 agosto 2017 09:53
A: ClusterM/hakchi2 <hakchi2@noreply.github.com>
Cc: ledste <openlinux@fastwebnet.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [ClusterM/hakchi2] v2.17 download changed? (#412)

 

@teknowledgist <https://github.com/teknowledgist>  you can check commits list on "stable" branch.

@ledste <https://github.com/ledste>  but it already has italian translation.

**Comment by teknowledgist** [comment]
@ClusterM Are you compiling and making that the release (without updating the version) with every commit?  Either way, IMHO it would be more "standard" if the version were updated when the release binary changes.

**Comment by ClusterM** [comment]
No, not every commit. And I'm always updating version before upload.

**Comment by teknowledgist** [comment]
You are updating the version the user can see *after installation*.  I mean that it would be helpful (and more standard) if the version displayed on the release page were updated when the binary changes.  Without that, the checksums are changed without any apparent reason *prior to installation*.  That makes (or should make) people nervous.

**Comment by ClusterM** [comment]
Okay.
