### ISSUE TITLE
Edit settings

### ISSUE THREAD

**Issue by falcocerr** [ClusterM/hakchi2#413]
I have installed retroarch and some new modules, the games work just fine but when I try to open the RA menu to change and improve video setting the screen freezes, I can see the menu but I can't select any option and after a few seconds the console restarts
I tried talking to the RA team and they mentioned that for this I should contact you, any idea what might be happening?

**Comment by ClusterM** [comment]
This is not RetroArch repo. I'm not author of RetroArch port. And I think that i need some console output to help...
