### ISSUE TITLE
Can't get past 'Waiting For Your Nes Mini'

### ISSUE THREAD

**Issue by nikkigubb** [ClusterM/hakchi2#414]
I just downloaded 2.17 through the web installer today.  I am using Wndows 10 and the original cord that came with the NES.  I've tried all of the USB ports on my computer multiple times both making sure the power light wasn't on and was on.  I can hear the sound that my computer is recognizing that something is plugged into the USB port every time.  I have clicked on the install driver button many times.

**Comment by angelbless** [comment]
Same here. Worked fine the first time I loaded the games. Then, I downloaded cover arts and added some new games and it stopped working... done everything ...it just wnt synchronize. I have over 100 mb left.

**Comment by nikkigubb** [comment]
I figured out my problem.  I had to use Zadig to download a driver for the NES and the only way that would work was to force my computer to disable driver signature enforcement prior to using Zadig.
