### ISSUE TITLE
Compressed .nes ROMs?

### ISSUE THREAD

**Issue by 630216-29-2400** [ClusterM/hakchi2#418]
I do apologise but I wasn't sure where to ask this and I've not updated my system for some time so I'm well behind the game here. I will get rid of this as soon as I get the answer.

I know that compressed ROMs are now supported but I'm not understanding how they are supported? When I add NES games to the system do I add an uncompressed .nes file and let hakchi compress it for me or should I be compressing the ROMs myself?

If I'm adding compressed files myself, what compression format should I be using?

With the SNES minis being released this year I've decided that I only want NES games on the NES mini so I will only be using .nes and .fds files.

Thank you, I do appreciate the help.

**Comment by ghost** [comment]
To use zipped NES roms you need Retroarch:

https://github.com/ClusterM/retroarch-clover/releases

For the base Hakchi2, you need to use unzipped roms.

**Comment by 630216-29-2400** [comment]
Thank you, that's all I need to know.
