### ISSUE TITLE
Mac-Based Hakchi2

### ISSUE THREAD

**Issue by NoelBaron** [ClusterM/hakchi2#42]
Hi there,

I caught your tutorial and wanted to give this a try, but I'm on a mac. Is there a way to run this via command line (linux style)? Would greatly appreciate your help.

**Comment by NoelBaron** [comment]
I downloaded Virtual Box with Windows 10, got the latest booted up, but I stall out when it attempts to detect the mini to install the driver for your initial kernel dump.  Any ideas?

<img width="1050" alt="screen shot 2017-01-28 at 1 38 34 pm" src="https://cloud.githubusercontent.com/assets/6867744/22398906/3c5ddb4e-e55f-11e6-8455-00a8e8974560.png">

**Comment by toadle** [comment]
I'd give this a +1. 

Is there any reasonable way to run this on a Mac. Even with Parallels/Virtualbox/VMWare?
I'd love to give anything a testdrive.

**Comment by toadle** [comment]
@NoelBaron I just got it working on a Mac. 
I wrote it down here: https://toadle.me/2017/02/03/how-to-add-more-games-to-you-nes-mini-classic-using-hakchi2-and-a-mac.html
