### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#420]
I have the forever-on-led glitch i tried flashing the original kernel but i still get the damn glitch.

**Comment by ClusterM** [comment]
Hi.
Is it flashed without any errors? Try flash original kernel and dump it again - make sure that checksum error will not appear.

**Comment by ghost** [comment]
when i try do dump it i get this ---------------------------
Warning!
---------------------------
Kernel dumped but the MD5 checksum is unknown: a8b66c12f78af308eb422f543172e911

The kernel is already patched or it's an unknown revision. Please send this message to me (press Ctrl+C). Continue at your own risk.

Do you want to continue?
---------------------------
Yes   No   
---------------------------

**Comment by ClusterM** [comment]
Seems like your dump is corrupted for some reason. Try to download original kernel from torrents (it's easy to find), put it into "dump" folder and flash original kernel again.

If you can't find kernel, contact me via e-mail: clusterrr@clusterrr.com

**Comment by ghost** [comment]
I got it to work i flashed the corrupted dump and works good as ne.

**Comment by ClusterM** [comment]
What...
