### ISSUE TITLE
Can not download the file

### ISSUE THREAD

**Issue by ericcannon** [ClusterM/hakchi2#421]
Tried downloading but I cannot download the file

**Comment by ClusterM** [comment]
Which file?

**Comment by ericcannon** [comment]
I am trying to download the helping hand program. I can download the source file but not the file with the .exe in it.

Sent from my iPhone

On Aug 10, 2017, at 6:09 AM, ClusterM <notifications@github.com<mailto:notifications@github.com>> wrote:


Which file?

**Comment by ClusterM** [comment]
So why are you asking about it here? This is hakchi2 repository.
