### ISSUE TITLE
Feature request: Zapper mod

### ISSUE THREAD

**Issue by bob12111** [ClusterM/hakchi2#423]
I used Hakchi to add some games to my NES Classic, one of which was Duck Hunt!  Now obviously, I can't exactly do a whole lot in the way of playing it, and we all know how the Zappers don't work with LCD TV's, but I just felt it a good way to round off my collection!  

What I was wondering, though, is would it be possible to emulate a Zapper effect?  That is, map a button to the second controller that would register a hit.  For example, in Duck Hunt's 1 duck challenge, I'd press a button on the second controller, and the duck would be hit.  Would something like that be possible?

**Comment by ClusterM** [comment]
Everything is possible if you really want it and ready to spent some time on it.

**Comment by zeusz4u** [comment]
@bob12111 What would there be the benefit of shooting with the controller if you always hit the target? The fun thing with the zapper was that you could miss the shot and make the dog laugh at you in duck hunt.

You could play zapper games on FCEUX emulator, where you could use your mouse for aiming and shooting (still better than nothing).

Unfortunately Zappers won't work with LCDs, and also there's no zapper controller for NES Classic Mini (probably there won't be any). There's been quite a lot of cool zapper games in my childhood: Duck hunt, clay shot, wild gunman, hogan's alley, I really enjoyed them, so bad you can't play them on modern TV sets.

**Comment by Kumoashi** [comment]
Actually, some people have found a way to "Mod" the NES Zapper to work on LCD screens.

Examples:
https://www.youtube.com/watch?v=DzIPGpKo3Ag&pbjreload=10
https://www.youtube.com/watch?v=TgnnMQLC3Vs&pbjreload=10

**Comment by Drakonas** [comment]
This is not something Cluster will fix. This would require a hardware adapter for the Zapper to the Wii controller interface, and that's IF it will actually work in the first place. Closing this, as it is not fixable by software.
