### ISSUE TITLE
Syncing issue on Hakchi 2.17d

### ISSUE THREAD

**Issue by Dylanknowstech** [ClusterM/hakchi2#424]
I just updated from Hakchi 2.17 to Hakchi 2.17d and I synced my NES Classic with the program and after it had synced, it began to reconnect and then suddenly it disconnects without ever reconnecting. I followed the directions in regards to updating the hakchi program by migrating the different folders needed. I tried to disconnect it and then after I plugged it back in to my computer. It gave the indicator that it was connected and then right away it suddenly disconnected. I tried multiple times to reconnect it but it didn't seem to work. It would simply connect and disconnect. My NES works fine and after syncing, all my games and mods are synced so no problem there. I went back to the previous version and I don't have the issue with connecting and it's working just like normal. Hopefully its just a small bug with Hakchi 2.17d.
Thank you for all your hard work Cluster.

**Comment by rhester72** [comment]
You're describing what typically happens when using a USB 3.0 port.  Try another port.

**Comment by ClusterM** [comment]
Try other cable/port.
