### ISSUE TITLE
Folders and Games not Alphabetizing 

### ISSUE THREAD

**Issue by glitchyGhost** [ClusterM/hakchi2#425]
Version 2.17c; freshly loaded hmods, copied over latest mods, 270 NES, 100 SNES and 50 GB, in three folders, inside up to 6 folders, with 35 max in each folder - set in settings OK.  

I cannot get all folders (custom mode) alphabetized?  They are appearing random, or one or two out of place. Tried moving the folder positions but its mainly the games in the NES library being affected.

What am I doing wrong?

Thanks

**Comment by glitchyGhost** [comment]
Attempted with 2.13e, 14, 16, 17c and now 17d.  Hope you can help.

**Comment by ClusterM** [comment]
Which sorting mode selected in NES Mini's shell?

**Comment by glitchyGhost** [comment]
I want 100 games, no folders. The folders / pages are disabled and games per folder set to 100.

I have even bigger issue! Please help...
My NES is now stuck in 480p? Please can you send an original dump to fix it back to 720p? I accidentally had the hdmi plugged in whilst modding on a small LCD tv. 

Hope you can help,

Thanks 

Matt

**Comment by glitchyGhost** [comment]
Just to confirm, reinstalling the latest hakchi2 and the latest cores fixed the game/folder order issue on one NESCE, but I had to reduce the 'games in folders' from 100 to 35.  The other NESCE I have (that's currently stuck in 480p! - see last message!) was intended to have 100 games with no folders but I got a C8 error, so 99 was the limit accepted.  I think the bug lies with the 100 folder setting?  I used to be able to do folders with 100 in no problem. Thanks

**Comment by ClusterM** [comment]
Please read the FAQ.

**Comment by MoneyLaunderer** [comment]
I'm having the same issue. Qty 30 games per folder, automatic as the setting. I've tried every combination and nothing has worked. Even re-installed and started from scratch. Nothing.

**Comment by MoneyLaunderer** [comment]
If you press the "Select" button while in the game folder, it should re-sort it by various categories. I had no idea you could do that until I about went insane. Hope that helps.

**Comment by Drakonas** [comment]
@glitchyGhost The (S)NES Classic cannot handle more than 60 games on one folder, or else you will have problems/crashes.

**Comment by glitchyGhost** [comment]
Thanks for the replies guys, only just seen them.  It was a mod I did for a customer, that I thankfully managed to sort out, although it’s permanently set at 480, which in my opinion looks much better than the 720p default.  Not sure how it happened (possibly disconnecting from the unit whilst signal was being sent to an old tv ? / which I noticed I did a few times) very strange.  So a warning to all regarding being careful as to not lock it to 480p.  It can happen! Thanks
