### ISSUE TITLE
Error Flashing Custom Kernel

### ISSUE THREAD

**Issue by markdidham** [ClusterM/hakchi2#43]
Hi, installing the newest version (first time user overall), and it when it comes time to flash the custom kernel, I get an error almost immediately:

"Access to path .....kernel\initramfs\bin\chroot is deneid. Please try again. 

I've tried using a prior release, and same issue.

**Comment by Ippokun81** [comment]
Hi, I had same problem and problem solved With 2.07 version.
After, i hacked again with the newest version.

**Comment by TruMusic** [comment]
I have the same issue with 2.11 then  i saw on here to try the 2.9 version & it worked... I put 90 games after 90 games I get a C8 error when I try to play a game. So I tried 2.07 and everything went fine then I tried the 2.11 version & same issue again "access to path _____ denied please try again" any help will be appreciated

**Comment by obiDUBkenobi** [comment]
yea i had the same problem.

**Comment by Prize9000** [comment]
I was able to use Hakchi2 version 2.11 the first day I downloaded it but when I tried to use it again a few days later, when I clicked the Synchronize selected games with NES mini button a bubble popped up asking me to "Dump the kernel image of my NES mini and that I only had to do this once and would I like to continue" so I clicked yes. Right after I clicked yes an error bubble popped up which said "C:\users\owner\desktop\data\fes1.bin not found. Please try again."  Somebody please help me.  Thanks!

**Comment by ClusterM** [comment]
This is Windows 10 file attributes problem. Please try latest version.

**Comment by Pito23** [comment]
I'm having same issue with latest version 2.17c... i'm using windows 10 pro, never able to add any game dues this error.

**Comment by ClusterM** [comment]
@Pito23 where your files are located? Have you tried non-portable version?

**Comment by Pito23** [comment]
@ClusterM the files are located inside the desktop > hakchi2 > games... and no, i don't tried the non-portable one version.
Where is it? maybe it's the web installer version?

**Comment by Pito23** [comment]
@ClusterM i'd like to hack my nes mini for the follow "project":

At start up menu i'd like to have 4 folders:

the First with the 30 factory games inside.

the Second one with "my childhood" nes games

the Third with some game boy/game boy color games

th Fourth and last with some game boy advance games.

All of those folders must have a custom icon each.

on youtube i cannot find any video that "clearly" explain how can do this, please help me!!!

Thx
