### ISSUE TITLE
Sound blanks out

### ISSUE THREAD

**Issue by mdouglas23** [ClusterM/hakchi2#431]
Uploaded the newest version of Hakchi to my NES Classic. Copied the Dump, Config and games folders over so I wouldn't lose my current selection of games and now unfortunately the sound periodically blanks out during the menu and gameplay. Any ideas?

Thanks!

-Matt

**Comment by ClusterM** [comment]
I have no idea.

**Comment by ghost** [comment]
This may sound dumb, but have you tried disconnecting and reconnecting both ends of your HDMI cable? Also, have you tried using another HDMI cable? Do you get the same problem?

Based on ClusterM's response, I'm just wondering if maybe it's a connection issue (rather than a Hakchi2 issue).

**Comment by mdouglas23** [comment]
Nope, doesn't sound dumb at all... That was the first thing that I thought of and I tried swapping cables and still the same thing. I did start from scratch though, and it fixed the issue. Thanks so much for the responses and suggestions!
