### ISSUE TITLE
8bitdo NES30 Problem with Buttons X,Y,L & R

### ISSUE THREAD

**Issue by Barbarossa2** [ClusterM/hakchi2#432]
Hi,

i´ve got a nes30 Controller for my nes classic mini with hakchi but it wont work for example withe snes and super mario world. The buttons X,Y,L & R wont work. Also mapping wont work. 

They say: "You need the beta hacked firmware not the official one.  V1. 0 5 Beta"

But i can´t find the firmware...can anyone help me please, reup or sending by mail?

At the moment ive got on the receiver 1.06 and on the controller 4.01 and it wont work :(

Thanks and best wishes from Germany ;)

Ok, i found the 1.05beat0. Can be closed!

Here is the firmware:

[8Bitdo_NesMini_RR_Firmware_v1.05_Beta0.zip](https://github.com/ClusterM/hakchi2/files/1314051/8Bitdo_NesMini_RR_Firmware_v1.05_Beta0.zip)

**Comment by imseandavis** [comment]
Bump to close.
