### ISSUE TITLE
Battletoads infinite lives Game Genie code always rejects with "Can't apply Game Genie code" error

### ISSUE THREAD

**Issue by AnomyBC** [ClusterM/hakchi2#434]
This may seem like a minor thing to complain about, but one problem I've consistently had with Hakchi is that every time I enter the Game Genie code for infinite lives for Battletoads, which is GXXZZLVI, I get this error:

"Can't apply Game Genie code 'GXXZZLVI' to game 'Battletoads' - value not found. Maybe this code is for another game?"

It's definitely the right code because that's what's printed in the physical Game Genie codebook and it's also what's on the Game Genie website. And it works just fine with a real NES. But for some reason Hakchi has never liked it. Every time a new version of Hakchi comes out I try the code again, hoping it will work, but it never does. Can this be fixed? I've been forced to use the 9 lives code for months, and 9 lives just isn't enough. I need like 30 lives just for that stupid Turbo Tunnel level. Please help.

**Comment by ClusterM** [comment]
I'll check.

**Comment by ClusterM** [comment]
Seems like this code is not working with patched version of game :( It's working with original ROM.

**Comment by Drakonas** [comment]
This is not a Hakchi problem. Codes are designed to work with the rom they were made for. If you patch the rom it breaks compatibility with codes. Closing.
