### ISSUE TITLE
Constant red light

### ISSUE THREAD

**Issue by invincibleparm** [ClusterM/hakchi2#435]
No matter what happens, the red light never goes off and I can't continue to add roms or even finish the complete install process. 
There have been three issues:

1. I sometimes get an exec timeout.
2. From the first load out, the hakchi2 client is never green. It opens red and no matter how long I wait, it never changes. 
3. I always have to do the hold reset and then power on, even after the kernal is 'installed'. There is no loading games onto the system at the moment at all.

**Comment by ClusterM** [comment]
Led should be always on after the kernal is 'installed', it's normal.
Try other USB cable/port.
