### ISSUE TITLE
Problem with space left on device (NES)

### ISSUE THREAD

**Issue by widdiam** [ClusterM/hakchi2#437]
Hi, since the SNES mini is coming out soon, I picked up my old NES classic to install the newer version of hackchi. But all I get is the same error. I tried changing port on my pc and it did nothing. 
![sans titre](https://user-images.githubusercontent.com/32379166/30998461-152a86de-a4a5-11e7-90b9-50bda39f33a3.png)

**Comment by MURDATYME** [comment]
I have also received the same Error

**Comment by MURDATYME** [comment]
I uninstalled all Hackchi2 software and reset my NES back to its original out of box state. Then I reinstalled the Hackchi2 2.17d and it worked like a charm.
