### ISSUE TITLE
SNES Classic no longer working after using Hakchi2

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#438]
I won't boot up at all. It shows the red light for only 10 seconds and then resets!

**Comment by nerdnils** [comment]
Have you tried flashing the old kernel back?

**Comment by 03bgood** [comment]
Yes.

On Sep 29, 2017 6:15 AM, "nerdnils" <notifications@github.com> wrote:

Have you tried flashing the old kernel back?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ClusterM/hakchi2/issues/438#issuecomment-333099890>,
or mute
the thread

**Comment by Lory955** [comment]
You have flashed the original nes mini kernel on snes mini.
This is why snes is reeboting.
If you lost the snes original kernel you have to wait until someone release their own.

**Comment by Lory955** [comment]
Of you don't know what you are doing , don't do it...........

**Comment by ghost** [comment]
i tried hakchi2 i dumped the snes kernel ok i tried to flash kernel with more games it reported done but when snes boot its still original snes no games added . it still working ok now i wait for an update hakchi.

snes kernel dump file eu
http://s000.tinyupload.com/?file_id=33105722247060857444

**Comment by nerdnils** [comment]
https://github.com/ClusterM/hakchi2/issues/436
ASAIK more games are not working yet.
Your dump could save 03bgood

**Comment by Lory955** [comment]
@novyyyy
You  cannot put other games on snes mini Now.
Wait for an update of hakchi2 tool .
You are patching original snes kernel with custom nes mini tool, creating a New kernel (same as the original) with the old system calling from nes mini. 
What you are doing it's like a porting.

**Comment by nerdnils** [comment]
Lory955, to me this statement sounds like you already know how to do it but only need to update the code. Is that true?
Or is there some more examining to do?

**Comment by 03bgood** [comment]
Thank you so much, it works now! I was so worried!!

**Comment by olet64** [comment]
Hello 03 i have the same problem :( my snes just keeps blinking its light and nothings showing up on the screen... i seriously dont get this. i was told it was exactly the same as the nes and stuff will go on no problem please help :(((((

and im not sure how to tell hakchi (im using v2.18) to put the snes one back on instead of the nes one because A: i dont see a button to do so and B: cause i dont know what the file is named

**Comment by olet64** [comment]
also i see that there is the option to switch to super nes mini but it doesnt allow me to do so because its greyed out

**Comment by dbelyaev** [comment]
@olet64 snes mini uses the same hardware but a little bit different software (kernel, paths, some extra logic added like rewind etc.), so @ClusterM need to update his software to support snes mini. please, wait for him to research it and let him update this tool accordingly. currently it is only to wait for an update.

**Comment by GoonsteinGuy** [comment]
The hakchi program won’t  run on my pc

**Comment by Drakonas** [comment]
@GoonsteinGuy Ask for help at the proper location on the proper subreddit: https://www.reddit.com/r/miniSNESmods/ and please don't respond to 3 month old closed tickets for an issue. This is a bug tracker, not a troubleshooting forum.
