### ISSUE TITLE
Renaming the original games

### ISSUE THREAD

**Issue by lmnoop** [ClusterM/hakchi2#439]
The original 30 games have pointless SHOUTING and garbage like ™ and ® symbols in their titles. I have been able to edit these through the FTP access to make them nice so it's definitely doable. I just wish it would be possible to do this in hakchi2 and have the changes be remembered in your "profile". Of course you can just disable the built-in games with "offending" titles and replace them with the ripped ROMs which you can edit but still...

**Comment by 03bgood** [comment]
It's asking me for a username and password, when I try to use the FTP tool, on Chrome.

**Comment by 03bgood** [comment]
How do I go about doing this? What FTP tool do I use, because it messes it up with the 6 Mega Man games. MM2 shows up as "MEGA MAN (tm) 2"" instead of just "Mega Man 2". Same goes with the other titles that have (tm) or (c) and it's really annoying.

**Comment by Drakonas** [comment]
The roms on the SNES Classic cannot be modified. The ones included are read-only. You will need to add duplicate roms for each game and disable the originals from Hakchi,
