### ISSUE TITLE
Feature Request: Option to remove Film Grain Overlay

### ISSUE THREAD

**Issue by jasinnerx** [ClusterM/hakchi2#44]
The NES Classic appears to not be putting out a pure HDMI image but instead is muddies it with a film grain type of dithering visible when the contrast is pumped up.  This is true on all 3 of the filter modes.  If these artefacts can be removed it would put it visually in line with other hdmi emulation options.  Example can be found in the following video:  https://youtu.be/Lxek9ZD3Njw#t=12m14s

**Comment by abijanfar** [comment]
This is an issue with the built in emulator, unless we have the source code for it not much can be done about it. Now that we can bypass it by using RetroArch, I think this issue can be closed.

**Comment by ClusterM** [comment]
Yes, it's problem of emulator, not NES Mini.
