### ISSUE TITLE
Using original SNES save states / patching a rom

### ISSUE THREAD

**Issue by Falconion** [ClusterM/hakchi2#440]
Hi there,
I've got a problem with my Final Fantasy VI rom. Unfortunately there's a bug
in the game (I'm 22 hours in), which doesn't let me pass a certain scene.

So I had two ideas:
1) Download a (original) SNES save state and simply upload it to my nes classic.
2) Somehow patch the rom that is already "installed" on the nes mini and keep using my save state.

Both ways don't work (or I'm just too stupid). 
1) I downloaded a save state, and tried to import the save state with hakchi. Of course this doesn't work because the SNES state is a .srm file and not a STATE file the nes mini uses.

So I copied the save state to var/lib/clover/profiles/0/Game Directory.
When I reconnect the nes mini to my tv, open retro arch and "load content" (navigate to the directory above) the save state does not appear and I cannot load it.

I also tried copying the .srm file to "usr/share/games/nes/kachikachi" but there my uploaded games don't appear.

So either I'm too stupid to use retroarch/hakchi or it doesn't work.

Could anyone please help me? 

Thanks and have a nice weekend!

**Comment by Drakonas** [comment]
The roms on the SNES Classic cannot be modified. They have since been found to be read only. You have to add duplicates of the roms you want and disable the originals.
