### ISSUE TITLE
SNES console type options grayed-out.

### ISSUE THREAD

**Issue by lylat1an** [ClusterM/hakchi2#441]
When might the SNES options be available?

I'm trying to use my American SNES Mini in version 2.0.18.11.  (Got it from the Web Installer)

When I try to dump the NAND, Hakchi2 doesn't doesn't detect the system even when I re-install the driver.

**Comment by lewisnfro86** [comment]
It was disabled on purpose as it is not ready, otherwise it would brick your console. Hopefully it is ready in  a few days.

**Comment by lylat1an** [comment]
Ah, I thought I might have been missing something.

Thanks.
