### ISSUE TITLE
Info for everybody regarding 8Bitdo and SNES Mini... ;-)

### ISSUE THREAD

**Issue by donlent** [ClusterM/hakchi2#442]
Hi everybody!

In case you already tried like me to use your 8Bitdo NES30, SNES30 or SFC30 with the Retro Receiver Classic (the one that was released for the NESC last year) then you've probably noticed that even if you're using Firmware 1.05b0 of the RR and maybe the latest Controller Firmware (which as of this writing is 4.01) then you're probably noticed the following:

- Yes, you can pair everything
- Yes, the SNESC will respond correctly at the Main Menu Level....
- But No, the DPAD is NOT working INSIDE of the games themselves...

Unfortunately this is "correct" at the moment. We have to wait until 8bitdo releases a Firmware Update for the RR or Controller which according to this site will be released "soon"

https://www.polygon.com/2017/9/29/16384666/wireless-snes-classic-controllers

 Quote from the website:
**"The RR for NES will also work with the SNES Classic with a firmware update that we’ll be releasing soon"**

So let's hope that the firmware is really going to be released soon... ;-)

Hope that this post will help many of you to not get "nuts" trying to figure out if it works or not.

In case you have a Nintendo Wireless Classic Controller though, I've read online that this already works fine with the current RR Firmware.... So it's really just their own 8Bitdo Controllers in combination with the SNESC that is not yet working...

If you have more updates maybe you can shere them here with the community...

And now I wanted to re-thank cluster and madmonkey for their efforts on this great project...
We all know that they are quietly working for all of us to make us happy, also with the SNESC soon!

Keep up the good work guys and enjosy the weekend, hopefully also spending some moments without coding but with your friends and family...  ;-)

Best,
Don

**Comment by hoderer** [comment]
It's already released & working!
http://download.8bitdo.com/Firmware/Receiver/nes_classic/8Bitdo_NesMini_RR_Firmware_V1.07.zip

**Comment by donlent** [comment]
Hi hoderer

Thank you so much for the feedback!

This is just AMAZING! right before creating the post, it WAS NOT online...
Now a few minutes later it has been published!! :-DDD

Really cool how things go fast sometimes... ;-D

The question is if this new firmware makes also the NES30 on the NESC to behave "correctly" means to have all buttons correctly mapped? Or will it be again a+b+turbo only?

Hoever tries it first can then post the results... that would be great... ;-)

Best
Don

**Comment by hoderer** [comment]
I got the update a few hours ago and it's working just PERFECTLY! when you press down + select while playing you get back into the menu.

**Comment by donlent** [comment]
I just tested as well and it works!! Yeah!! Thanks again hoderer!

As soon as I've time I'll test also with the NESC and the NES30... Really curious if this firmware finally fixes both worlds... ;-)

**Comment by Driche** [comment]
If you update for SNES, do you have to back to the old one for the NES or will new update cover both?

Thanks.

Sent from my iPhone

On Sep 30, 2017, at 7:32 AM, donlent <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi everybody!

In case you already tried like me to use your 8Bitdo NES30, SNES30 or SFC30 with the Retro Receiver Classic (the one that was released for the NESC last year) then you've probably noticed that even if you're using Firmware 1.05b0 of the RR and maybe the latest Controller Firmware (which as of this writing is 4.01) then you're probably noticed the following:

  *   Yes, you can pair everything
  *   Yes, the SNESC will respond correctly at the Main Menu Level....
  *   But No, the DPAD is NOT working INSIDE of the games themselves...

Unfortunately this is "correct" at the moment. We have to wait until 8bitdo releases a Firmware Update for the RR or Controller which according to this site will be released "soon"

https://www.polygon.com/2017/9/29/16384666/wireless-snes-classic-controllers

Quote from the website:
"The RR for NES will also work with the SNES Classic with a firmware update that we’ll be releasing soon"

So let's hope that the firmware is really going to be released soon... ;-)

Hope that this post will help many of you to not get "nuts" trying to figure out if it works or not.

In case you have a Nintendo Wireless Classic Controller though, I've read online that this already works fine with the current RR Firmware.... So it's really just their own 8Bitdo Controllers in combination with the SNESC that is not yet working...

If you have more updates maybe you can shere them here with the community...

And now I wanted to re-thank cluster and madmonkey for their efforts on this great project...
We all know that they are quietly working for all of us to make us happy, also with the SNESC soon!

Keep up the good work guys and enjosy the weekend, hopefully also spending some moments without coding but with your friends and family... ;-)

Best,
Don

**Comment by LoveBootCaptain** [comment]
they work as they should. why should you be forced to switch firmwares? makes no sense.

tested with SF30 (4.01) and N30 (4.01) and RR (1.07)
- on nes mini with turbo A+B
- on snes mini with Y+X

**Comment by PleaseEnterName** [comment]
Those of us who were using the 1.05 beta firmware for the receiver were doing it to get separate X + Y + R + L buttons playing SNES on our hakchi'd NES Classics. I'm sure most people with hakchi'd systems don't want turbo. At least I don't. I want all buttons to register independently, and retroarch to be able to assign buttons.

**Comment by LoveBootCaptain** [comment]
as far as i can see 1.07 works also in retroarch emu's on NES mini.
tested some GBA and SNES roms on the NES mini... both work fine with L + R in GBA and L + R + Y + X in SNES.
in original NES Roms you have A + B + Turbo A + Turbo B
but i didn't messed with custom button layouts in retroarch yet. as for now the default is pretty great for my kind of use and systems.
go try yourself. i never had issues with 8bitdo firmware-updates. the always improve

**Comment by grantbi** [comment]
>as far as i can see 1.07 works also in retroarch emu's on NES mini.
tested some GBA and SNES roms on the NES mini... both work fine with L + R in GBA and L + R + Y + X in SNES.
in original NES Roms you have A + B + Turbo A + Turbo B

I seem to get more input lag on the NES classic with 1.07 firmware (Retro-Arch SNES emulator more specifically). Is this happening for anyone else? Otherwise, it does seem to work for both systems.

**Comment by techhitnz** [comment]
I have an issue using ds4 where all the buttons are mapped incorrectly and shifted clockwise. So B is mapped to Square and A is mapped to X.

**Comment by ajmi982** [comment]
same issue as techhitnz, need a new firmware, 8bitdo are completely unresponsive to me.

**Comment by Drakonas** [comment]
Why doesn't everyone report this to 8bitdo? This is not a Hakchi issue. Closing this.
