### ISSUE TITLE
Feature request: Soft "Home" delay

### ISSUE THREAD

**Issue by PleaseEnterName** [ClusterM/hakchi2#445]
Nintendo added a feature on the SNES Classic Mini to let your reset a game by holding L + R + Start + Select for about 1-2 seconds. It doesn't take you to the Home screen, it just restarts the game. 

Can the hakchi2 Home shortcut by changed to feature a similar delay for Down + Select on NES and SNES? It should almost completely get rid of accidental triggering in some games (Super Metroid will be one of them)

**Comment by Lory955** [comment]
No. 
System calling for reset combination won't work.
As i said in my summary you can't use the reset combination.

**Comment by PleaseEnterName** [comment]
No, not to change the combination... Just to introduce a delay to the hakchi Home shortcut, so you have to hold Down + Select for a second or two in order to invoke the Home shortcut rather than being instant.  

Sorry, maybe I'm misunderstanding? I'll try to find this summary you mention... I don't think we're talking about the same thing.

**Comment by Lory955** [comment]
Maybe changing the time value in the library you can delay it.
But this require more than the ftp connection that hakchi2 gives to us.
You have to manually flash the new file by yourself.

**Comment by Drakonas** [comment]
This has been added. Closed.
