### ISSUE TITLE
arcade games snes 

### ISSUE THREAD

**Issue by secso187** [ClusterM/hakchi2#446]
Are you or any of your peeps considering arcade games for the snes console I hope so I am a killer instinct fan that game never gets old. ok this is more of a request than a problem but I hope you consider it

**Comment by Lory955** [comment]
@secso187
Do you mean MAME games?
Consider that for now the only way to add game on snes mini is by manually flash them onto snes.
This require some skills...

**Comment by PleaseEnterName** [comment]
@Lory955 
Are you even a developer for the main hakchi components? Stop muddying the topics with useless non-answers to questions not even directed to you.

**Comment by FierceLog** [comment]
MAME is the main arcade system emu. If it's on the NES Mini, eventually it will come to the SNES Mini.

Killer Instinct is great in the arcade version or SNES version, with some differences.

**Comment by Drakonas** [comment]
fba core is now included with the retroarch pack. use this to play arcade games.
