### ISSUE TITLE
When attempting to add Puyo Puyo (Japan), empty "Select File" prompt pops up

### ISSUE THREAD

**Issue by asiansteev** [ClusterM/hakchi2#45]
When attempting to add ``` Puyo Puyo (Japan).zip ``` to hakchi2 v2.11, an empty prompt with the title "Select file" pops up. The OK button is disabled so there is no way to add Puyo Puyo.

![capturepuyopuyo](https://cloud.githubusercontent.com/assets/20084/22399036/acb79554-e561-11e6-9d0d-8d61534d1e31.PNG)

**Comment by baconcow** [comment]
You are trying to add a Sega Genesis ROM to a NES. Also, it is might not be a good idea to not link ROMs to GitHub.

**Comment by asiansteev** [comment]
huh, you're right, sorry about that

**Comment by ClusterM** [comment]
Fixed.
