### ISSUE TITLE
Superscope / Nes zapper

### ISSUE THREAD

**Issue by Nerobeus** [ClusterM/hakchi2#450]
Hi,

Do you think that it's possible use a wiimote with 8bitdo BT for emulate superscope / nes zapper ?

**Comment by mrTruch** [comment]
Wiimote uses bar sensor. Superscope and zapper just detect light. I think it wouldn't be the same interaction.

**Comment by Nerobeus** [comment]
Superscope is supported by retroarch, it require only mouse input.

**Comment by Drakonas** [comment]
This is impossible. The superscope would be the only way but the SNES Mini has no ports to plug it into. And even if an adapter was made the SNES mini probably does not interface the proper code with those ports to support the Superscope. And contrary to popular belief, the wiimote uses bluetooth to send the motion data and sensor bar readings (which the sensor bar is really just LED lights) wirelessly to the Wii, in which the SNES mini does not support bluetooth. So you're fresh out of luck.

**Comment by setpixel** [comment]
not impossible. It does have a serial port you could solder to. you could make a hardware interface to the BT device. but yeah - no one would do that.

**Comment by Drakonas** [comment]
I meant impossible using the method he was requesting. lol Should have specified that. Of course with a hardware modification possibly. But yeah, nobody's willing to do that.

**Comment by setpixel** [comment]
yeah also, the nes zapper will never work with a non crt. @Nerobeus look up how a zapper works. its interesting and itll never happen.

**Comment by Nerobeus** [comment]
i want to install a wiimote circuit board inside a superscope, but i need find how make wiimote working.

**Comment by Drakonas** [comment]
@Nerobeus I highly doubt the circuitry in the SNESC for the port will even let you use a superscope-like device even if you made an adapter or custom superscope. It has to have hardware support for controller designs. Same deal with the Nunchuk not working. Just because it plugs in doesn't mean it has support for an unrecognized device type.
