### ISSUE TITLE
Feature Request: Get Rid of Visible Folders by Mapping Folder Access to Button (Please consider for NES AND SNES)

### ISSUE THREAD

**Issue by Hypoxium** [ClusterM/hakchi2#451]
I really can't stand how unofficial the folders look. I'd feel so much better if I could just cycle through folders with a button press. For example, you can press select to switch between most played, release date, etc. I would love the option to just press a button to bring up the next 30 games instead of seeing the folders on my screen and be able to cycle through them like that.

Please consider giving us this option in the future if not now.

**Comment by ClusterM** [comment]
We can't modify shell :(
