### ISSUE TITLE
Feature request: Update NES Mini kernel

### ISSUE THREAD

**Issue by zlinx** [ClusterM/hakchi2#452]
Do you consider the possibility of "upgrade" the NES Mini with the SNES Mini kernel to get the new features (Frames, rewind...) on NES, but with the NES look and games?

Thank you for your awesome work.

**Comment by sund0260** [comment]
I have seen ClusterM respond on this before saying you need to do a NAND B dump from the SNES classic and put it in a certain folder on a hacked NES mini. I have not found a step-by-step for this yet as ClusterM warned doing a kernel swap alone could brick the NES mini.

**Comment by Drakonas** [comment]
This is already possible as @sund0260 said. there is no feature Hakchi needs to add to allow this. Ask for help on Reddit for this.
