### ISSUE TITLE
Upgrade from 2.17c to 2.17 d

### ISSUE THREAD

**Issue by ledste** [ClusterM/hakchi2#456]
This summer was available version 2.17c and I loaded my favourites games in my mini NES and I set-up the software as I like; now I downloaded 2.17d and I started of course as clean and new software.

How to import all the data, configuration from 2.17c?

Thanks

**Comment by Roemer** [comment]
Spend at least 1 minute searching on your own:
See here https://github.com/ClusterM/hakchi2/wiki/FAQ

> Q: How can I update hakchi2 to a new version? I don’t want to lose my games, kernel image and settings.

**Comment by ledste** [comment]
Thanks
