### ISSUE TITLE
SNES Mini returns a USB In Endpoint of 0x82 instead of 0x81

### ISSUE THREAD

**Issue by nambread** [ClusterM/hakchi2#458]
Hi All,

I've been trying to just get the FTP working to poke around on my EU Snes Mini's filesystem but have had trouble. I realise that the tool hasn't been officially had SNES support added, but since this is a device usb config issue I wonder if this is something that needs to be raised before people get their hands on it. The steps are as follows:

1. Got Hakchi 2
2. Installed driver
3. Booted SNES in recovery mode
4. Dumped kernel
5. Installed the clovershell mod
6. Enabled FTP
7. Tried to connect via Filezilla and WINScp

My issue is the error "NES Mini is offline" when trying to connect over FTP. Looking into why I found this section of code:

https://github.com/ClusterM/hakchi2/blob/100852f221b8f1b83c978d29c0cd56f54d7ffab8/Clovershell/ClovershellConnection.cs#L234-L238

When I run my SNES Mini in recovery mode the `inEndp` that gets returned is actually 0x82 (130) not 0x81, meaning my snes mini never actually connects. The VID and PID match those that the program checks.

I tried updating the check to include the new Endpoint, but the data that gets read from the connected `epReader` is all wrong. The first byte in the buffer doesn't actually map to any commands in `ClovershellCommand` so any commands sent from clovershell never get a response. Data does actually come back over the wire though.

I've tried several usb ports and several usb cables on my computer, but nothing seems to help. 

Have I missed a step? I've spent the last few days searching forums and reddit but cannot see anyone else having trouble with the FTP.

**Comment by nambread** [comment]
I should probably add that I'd cloned the stable branch of Hakchi2, about 2 days ago.

**Comment by Asure** [comment]
In recovery (FEL) mode, the system os has not booted, and it's sitting in a recovery prompt/mode.
You missed that the device needs to boot in normal mode.
Also, you missed that you need to install the custom kernel for the clovershell/ftp to work.

And, you need to keep around 30 seconds wait after it says finished when doing the custom kernel. 
At least, looking at Cluster's youtube, i could see that it was doing several things on the serial port still before really 'finished.

**Comment by nambread** [comment]
> 
Also, you missed that you need to install the custom kernel for the clovershell/ftp to work.
> 

I did, but it was only when placing hakchi2 in MyDocuments\Hakchi2 did it work. Previously I had an old version of hakchi2 in that location while running from a bin\debug subdir elsewhere. It must've gotten some paths mixed up.

Got the FTP working eventually, so closing this bug. Still not working, but likely a different cause.
