### ISSUE TITLE
Linking the original games instead of copying them to the writable partition

### ISSUE THREAD

**Issue by DanTheMan827** [ClusterM/hakchi2#459]
On the SNES, the built-in games take around 48.5MB, making a copy of data that already exists on one partition is a pretty big waste of space if it can be accessed another way.

Would it be possible to do bind mounts for the original games so that making a duplicate copy isn't needed?

**Comment by madmonkey1907** [comment]
yes

**Comment by Rahzadan** [comment]
If this isn't possible, would it be possible to have the 21 original games compressed as well? It looks like with the current release candidate of 2.18, it only compresses newly added games when the 'compression' box is ticked, not the original 21 games when 'Original Games' box is checked.

**Comment by Drakonas** [comment]
Why don't people wait patiently for the official release? This is unfinished software. It is not intended for public use yet.

**Comment by gnadenlos** [comment]
This is a public github, so it is.

**Comment by DanTheMan827** [comment]
I think a better term would be "general public use"...

Anyone can download it, but if you don't know how to use it, you may have issues.

**Comment by Drakonas** [comment]
@gnadenlos do you not see there is no release yet for SNES classic on the releases page on Github? Building from source is not an official public release. When a release goes up on the releases page, THEN it will be a release intended for the public. Source code can always have bugs, especially when it is updating often. General users should stick to waiting for official builds that are fully tested. The builds going around the internet are built from the source code, which is not tested yet.

**Comment by rickvug** [comment]
@Drakonas Normally bug reports and legitimate feature requests are welcomed for software projects, even those that are in beta. This is a solid idea for a future improvement rather than any sort of complaint or request for help. It is worth keeping in the issue tracker.

**Comment by timehlers** [comment]
Now 2.20 is released and I think this problem persists. At least I have the original games twice, once in the ro-partition "/" and copied to the overmounted /usr/share/games partition... And it seems to be quite a big waste (about 84 MB).
BTW: Do I always need to synchronize *all* games, when adding one game to the collection? When I untick the already installed, they are deleted after pushing "synchronize". This can't be good for the flash chips...

Best

Tim

**Comment by DanTheMan827** [comment]
Where would I add some commands to run at startup?

```
mkdir /tmp/original_root
mount -o bind / /tmp/original_root```

if I run them manually, I get the original root without the remounts, at that point, I could symlink the games, but I need that to mount every time at boot...

**Comment by DanTheMan827** [comment]
@timehlers well, flash chips can handle around 100,000 writes before they start to fail.

So at least there's that...

**Comment by DanTheMan827** [comment]
#618

**Comment by DanTheMan827** [comment]
282c84a
