### ISSUE TITLE
Numbers in extended font don't show up

### ISSUE THREAD

**Issue by joncco** [ClusterM/hakchi2#46]
If you use "full width" numbers it doesn't show up in the menu.  An example is Super Mario Bros. 3 from the original Famicom Mini (only スーパーマリオブラザーズ appear in the menu)

![img_20170129_104101](https://cloud.githubusercontent.com/assets/2509694/22400676/cb3fce7a-e60f-11e6-83ef-25398088c57e.jpg)

**Comment by ClusterM** [comment]
xsnake already sent me fixed Japanese font. It will be fixed in new version.
