### ISSUE TITLE
(Question) Adding nes rom hacks to nes mini?

### ISSUE THREAD

**Issue by Graycomix** [ClusterM/hakchi2#466]
Since the discovery of hackchi2, I have been adding games I've always wanted to the console. I was wondering if patched .IPS files could be added to the NES mini via this program. As it just states "Not an NES game" Even if I try to trick it by putting .nes at the end of the file name. Any pointers on how to do this? (Or if it's remotely possible.)

**Comment by dbw-holic** [comment]
@Graycomix Did you read the release description for ver.2.09? 

> Patch files stored in "patch" folder. Problem game will be detected automatically by CRC32 checksum. 

> You can add and your own patches too.
