### ISSUE TITLE
Feature request: remembering default "Yes/No" answer

### ISSUE THREAD

**Issue by DaymareOn** [ClusterM/hakchi2#47]
Hi,

when I Add lots of games (like all the nes roms ever created, something like 3000, i think I remember), when I run into a warning like "We don't manage this wrapper number, do you want to try it anyway?", i would like my choice to be remembered for all the other added roms.

Similar thing for:
- bad size,
- "A patch exists, do you want to apply it?"

Pretty please :-) ?

(Awesome GUI, by the way ^^ )

**Comment by ClusterM** [comment]
Done!

**Comment by DaymareOn** [comment]
Thank you :-) !!!
