### ISSUE TITLE
Flash custom kernel doesn´t work @ v2.20rc4

### ISSUE THREAD

**Issue by fr4gstar** [ClusterM/hakchi2#473]
The flashing process finishes successfully, but the snes mini doesn´t work.
The LED lights red, but nothing happen on the screen. When it´s switched off, the LED blinks.
It´s a EU snes mini.

**Comment by Tranquilite0** [comment]
I can confirm that my US SNES Mini also experiences this bug. Flashing original kernel works fine though.

**Comment by Turom421** [comment]
I have the same problem with my US version.  I originally flashed it using 2.18 and was able to get 1 rom working that way.  I reflashed to my original firmware before installing the custom firmware using 2.20.  If I reflash to original or to custom in 2.18, it works.

Booting custom 2.20 always results in me hearing the music for less than a second, and sometimes seeing the screen for maybe a quarter second, then the unit either reboots and does it again, or the red light just goes off.

**Comment by Turom421** [comment]
I was just playing around with it... I am using an HDMI automatic port switching device.  This problem only manifests if I boot the SNES classic using 2.20 custom while plugged into that device.  If I bypass this device, the SNES will boot fine and works perfectly.

If I use the original firmware or custom from 2.18, the SNES classic will boot fine using this HDMI port switching device.  My. Xbox one and Wii-U work fine with this device.  Only the SNES classic on custom 2.20 will not boot when going through this device.

2.20 custom will also work if I boot it with HDMI unplugged and then plug in the HDI cable while using my HDMI port switch.

**Comment by fr4gstar** [comment]
rc5 fixed the problem for me.
