### ISSUE TITLE
Reset-to-menu via clovercon not working in RC4

### ISSUE THREAD

**Issue by rhester72** [ClusterM/hakchi2#474]
Anyone have reset (to menu) for SNESCE working from the stock controller on RC4? Worked for me on an early 2.18 build (as Select + Down), but new defaults (Select + Start + L + R) only resets in-game (and is part of stock anyway), changing to Select + Down in Hakchi2 has no effect and doesn't work.

**Comment by emufrance** [comment]
it's working with defaults  (Select+Start+L+R) on hakchi2_0.20.rc4_debug twitted by cluster

**Comment by ClusterM** [comment]
Can you send me your "config" folder?

**Comment by gnadenlos** [comment]
It's working with default (L+R+Start+Select) and L+Start for me without problems. Only with the hide thumbnail mod reset takes too long, so I have removed the hide thumbnail mod and everything is fast again. (RC4debug)

**Comment by DachandeYautja** [comment]
I also am unable to use reset to menu using the new defaults (Select + Start + L + R) or custom keys even

**Comment by rhester72** [comment]
Problem existed with RC3 compiled from zipped source - compile of RC4 from git and reinstall of Hakchi resolved the problem.  Not sure what the root cause was, but closing as no longer an issue.
