### ISSUE TITLE
Upgrading Nes mini kernel with Snes mini

### ISSUE THREAD

**Issue by codex785** [ClusterM/hakchi2#479]
Is there any way to upgrade Nes mini kernel/system with the benefits of Snes mini?
Do Snes mini provide any indication concerning kachikachi?

**Comment by ClusterM** [comment]
You'll brick NES Mini with SNES Mini's kernel.
But you can transform NES Mini into SNES Mini using .hsqs file (nand-b image). You need to pus SNES Mini's .hsqs file into /var/lib/hakchi/firmware
