### ISSUE TITLE
Building Super Gameboy into Snes Mini - [Update] Retroshield has built a project

### ISSUE THREAD

**Issue by codex785** [ClusterM/hakchi2#484]
I think there is a chance to get supergameboy emulated by CANOE (back in the good old times!) 
I found a Super Gameboy boot rom here:
http://www.its.caltech.edu/~costis/sgb_hack/
i know there are super gameboy roms online (Google)
the idea is:
Create a folder (Suer Gameboy style) tha has gb roms in it
having a command line that launches Super Gameboy boot rom and rom through CANOE, then the .gb game
and we're good to go

**Comment by Dark-Akuma** [comment]
The problem with that idea is that the Super Gameboy was the hardware of the Gameboy packed into a game cart shell, replacing the button interface and screen with a SNES cartridge connection. All that the bios did was the UI stuff. The bios wasn't a Gameboy emulator program.

You will have to settle for a GB emulator.

**Comment by Drakonas** [comment]
This would require hardware in the SNES Classic to support this. Your only option is Retroarch. Closing.

**Comment by RetroShield** [comment]
I guess this is the closest thing you will ever seen:

https://youtu.be/ntD1h-laOfI

It‘s a project i started about 1 Month ago. Hope you Like it.. this is the SUPER GAMEBOY CLASSIC MINI.
Best Regards

**Comment by codex785** [comment]
@Retroshield oh man!
is there a way to test it?
thanks a lot

**Comment by RetroShield** [comment]
@codex785 at moment theres not, i created a .hmod installer that makes a one click installation possible but i still have to fix some bugs and create a programm to manage the roms/saves/boarders. At moment i can say its fully functional but its missing a programm manager like hakchi.

**Comment by codex785** [comment]
@RetroShield 
Maybe one of them can help: @ClusterM , @madmonkey1907 , @Drakonas , @rhester72 , @KMFDManic , @Dark-Akuma ,

**Comment by RetroShield** [comment]
@codex785 thanks for the response, i like to check first if the ppls like the idea and if they do i will put more effort into it :-).

**Comment by Drakonas** [comment]
@RetroShield We are all for it if you want to provide a pull request for the hmod inclusion in ClusterM's clover-retroarch Github project :)
