### ISSUE TITLE
Smaller screen with addet manual addet games?

### ISSUE THREAD

**Issue by Jonny0r** [ClusterM/hakchi2#487]
Original Picture of SMW on SNES MINI.
https://imgur.com/a/lEFlo

Picture of SMW on SNES MINI addet with Hakchi2.
https://imgur.com/a/d5qwY

Why this difference? I thought its the same emulator.

Game Version is NTSC.

**Comment by ClusterM** [comment]
My ROM is working fine without any borders.

**Comment by Jonny0r** [comment]
Sorry ClusterM for waisting your time, just this minute i found out its the different Background, when i use the Background of the first picture then you have the same view (no borders), but when i change to this curtain, then you have the Black borders. :) 

The Picture is simply that small, you only have a different view depends on the background.

https://imgur.com/a/CiAq9

**Comment by shaman78** [comment]
@Jonny0r you can close it

**Comment by Jonny0r** [comment]
Sorry first time i used Github comment :)
