### ISSUE TITLE
Kernal dumped but the MD5 Checksum is unknown

### ISSUE THREAD

**Issue by anondl** [ClusterM/hakchi2#488]
228967ab1035a347caa9c880419df487

This appears when I dump my kernal.

I'm running 64 bit Windows 10  if that helps..

Forgot to mention I am using the SNES Mini

**Comment by RaZer0k** [comment]
this is "kernel-dp-snesusa-release-v2.0.14-0-gd8b65c6" is not defined in the list of kernels, you have to wait until ClusterM added.
Press "yes"... is only alerting that checksum not mach with of know kernel list

**Comment by anondl** [comment]
Oh okay.  Hopefully he's able to add it soon.  Thank you RaZer0k!

**Comment by ClusterM** [comment]
Thank you!
