### ISSUE TITLE
"used by another"-issue

### ISSUE THREAD

**Issue by batluder** [ClusterM/hakchi2#49]
I had my program installed in my DropBox-folder---this seamed smart to ensure a backup that way. But I had an issue every time, I tried to write to the NES mini, after a while I would get an error, that a temp-file was in use by another program, and the whole process was aborted. This of course happens, as DropBox tries to sync the temp folder, while hakchi2 is using it.

Either the temp files could be kept in some default temp file location, or there could be a small timeout and a retry to not break the whole process when something happens, to fix the issue.

**Comment by ThatGuyDogboy** [comment]
An option here would be to ask where you want the temp file stored and then write that to the config.ini file.

**Comment by ClusterM** [comment]
Maybe we should use system's temp folder... I'll try to do so.
