### ISSUE TITLE
[SNES] PAL Rom Patch with Database

### ISSUE THREAD

**Issue by shaman78** [ClusterM/hakchi2#490]
Could somebody try these Rom patches for Pal languages .
I think it's very nice for RPGS :blush:

http://www.romhacking.net/?page=hacks&genre=&platform=9&game=&category=&perpage=100&title=Ntsc&author=&hacksearch=Go

Search : ntsc
Console: super nintendo

Thx

**Comment by shaman78** [comment]
I tried Secret of Evermore (G) (standard is 50fps).
With the High patch on **snes9x** it worked with 60fps.
So the solution of @codex785 in #481 

> I found a trick, patching PAL to NTSC
> http://en.evilgames.eu/snes-pal-to-ntsc.html
> maybe it can be automated in hakchi before converting to sfrom

could work for snesc's original emulator
 
@ClusterM Could you test a few of the games with the patch.

And if it works. Could you implement it that hakchi asks if it finds an game that is in the list if the game should be patched before formatting them to .sfrom format.

**Comment by shaman78** [comment]
Secret of Evermore works fine with the ntsc patch (German)

**Comment by Drakonas** [comment]
This kind of thing does not belong on an issue tracker. This is meant for reporting bugs with Hakchi. Closing this.
