### ISSUE TITLE
error in transfer file to snes mini

### ISSUE THREAD

**Issue by Omar-Diaz-Silva** [ClusterM/hakchi2#491]
i have recibing this message when transfer to snes mini

---------------------------
Error
---------------------------
shell command "mkdir -p "/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi/./CLV-P-NAARE/" && rsync -ac "/usr/share/games/nes/kachikachi/CLV-P-NAARE/" "/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi/./CLV-P-NAARE/" && sed -i -e 's/\/usr\/bin\/clover-kachikachi/\/bin\/clover-kachikachi-wr/g' "/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi/./CLV-P-NAARE/CLV-P-NAARE.desktop"" returned exit code 23: rsync: change_dir "/usr/share/games/nes/kachikachi/CLV-P-NAARE" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

---------------------------
Aceptar   
---------------------------
i think i run a no compatible kernel, 
md5 of kernel.img
5296e64818bf2d1dbdc6b594f3eefd17 *kernel.img

**Comment by Darky2k1** [comment]
Similar error when i tried to go load the USA Roms utilizing the JPN Super Famicom Firmware

` -rf /var/lib/hakchi/rootfs/usr/share/games/CLV-* /var/lib/hakchi/rootfs/usr/share/games/??? /var/lib/hakchi/menu # exit code: 0
mkdir -p "/var/lib/hakchi/rootfs/usr/share/games/./CLV-P-SACCE/" && rsync -ac "/usr/share/games/CLV-P-SACCE/" "/var/lib/hakchi/rootfs/usr/share/games/./CLV-P-SACCE/" &&sed -i -e 's/\/usr\/bin\/clover-canoe-shvc/\/bin\/clover-canoe-shvc-wr/g' "/var/lib/hakchi/rootfs/usr/share/games/./CLV-P-SACCE/CLV-P-SACCE.desktop" # exit code: 23
shell command "mkdir -p "/var/lib/hakchi/rootfs/usr/share/games/./CLV-P-SACCE/" && rsync -ac "/usr/share/games/CLV-P-SACCE/" "/var/lib/hakchi/rootfs/usr/share/games/./CLV-P-SACCE/" &&sed -i -e 's/\/usr\/bin\/clover-canoe-shvc/\/bin\/clover-canoe-shvc-wr/g' "/var/lib/hakchi/rootfs/usr/share/games/./CLV-P-SACCE/CLV-P-SACCE.desktop"" returned exit code 23: rsync: change_dir "/usr/share/games/CLV-P-SACCE" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
   at com.clusterrr.clovershell.ClovershellConnection.Execute(String command, Stream stdin, Stream stdout, Stream stderr, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 665
   at com.clusterrr.clovershell.ClovershellConnection.ExecuteSimple(String command, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 623
   at com.clusterrr.hakchi_gui.WorkerForm.UploadGames() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 860
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 264
clovershell disconnected`

**Comment by Omar-Diaz-Silva** [comment]
content of folder /usr/share/games

root@CLOVER:/usr/share/games# ls /usr/share/games
CLV-P-SAAAE  CLV-P-SAAHE  CLV-P-SAAQE  CLV-P-SABHE  CLV-P-SACBE  CLV-P-SADKE
CLV-P-SAABE  CLV-P-SAAJE  CLV-P-SAAXE  CLV-P-SABQE  CLV-P-SACCE
CLV-P-SAAEE  CLV-P-SAAKE  CLV-P-SABCE  CLV-P-SABRE  CLV-P-SADGE
CLV-P-SAAFE  CLV-P-SAALE  CLV-P-SABDE  CLV-P-SABTE  CLV-P-SADJE

**Comment by shaman78** [comment]
seems there's something wrong in the settings you use because it will write in the nes folder witch isn't existing on the snes

**Comment by Darky2k1** [comment]
@shaman78 - Likely something just not correct in this build since its release client :P

**Comment by Drakonas** [comment]
@Omar-Diaz-Silva Are you still having issues?

**Comment by Omar-Diaz-Silva** [comment]
Hi,
Not, with the new releases, the error is gone
