### ISSUE TITLE
Games not showing up in menu

### ISSUE THREAD

**Issue by voidc0re** [ClusterM/hakchi2#494]
I backed up, flashed the custom kernel, added the retroarch core for snes9x and gba, and then added the games (stored on computer in zip folders) and synchronized. I rebooted the console again after that finished. I just see the standard games and the key combo to reset worked one time, but doesn't work after that. Am I doing something wrong or do I have a different revision that's not compatible?

**Comment by Drakonas** [comment]
@Invidious89 was this ever fixed?

**Comment by Drakonas** [comment]
Closing this as there has been no response for 3 months.
