### ISSUE TITLE
[SNES] Random reboots in menus

### ISSUE THREAD

**Issue by Moltdar** [ClusterM/hakchi2#495]
sometimes it will happen just entering a sub-menu. sometimes it will happen after flashing.
in all cases it might happen in a loop and stop at some pointz
in general, disconnecting/reconnecting fixes it for a while.
happens with rc4 and rc5 across both my units which have retroarch installed and 160 roms.
notes my roms are all set to use folders split evenly, with originals NOT at the root

**Comment by hoderer** [comment]
there is a problem with a higher power consumption after flashing a custom kernel. I'm not quite sure, if it has something to do with you problem, but could be. Did you try to change your power supply? I never had any random reboots. Used RC4 to add 150 SNES-roms und another 200 for different retroarch modules.

**Comment by roflcopter777** [comment]
Should we make a new issue for the power consumption changes? If not then I will.

**Comment by hoderer** [comment]
Good idea, but like I said on gbatemp I don't think it's easy to fix. I Hope I'm wrong about that. I'll write it down in a second.

**Comment by roflcopter777** [comment]
Oh, so you'll make a new entry? Okay.

**Comment by Moltdar** [comment]
Indeed, after a full power down and plugging it in a proper usb power supply, im not getting any issues anymore.
note i had tried usb2 ports as well as usb 3 ports through a hub, and both 1a and 2.1a power-only ports i had tried through that same hub were giving me the issue.
in the end, the official nintendo-shipped usb power supply and my anker portable battery both didn’t give me any issues.
So while annoying when testing after flashing, it’s totally manageable! thanks for the tip!

**Comment by Moltdar** [comment]
but yes indeed fixing the issue would be great, so open a separate ticket if you havent already done so! Thanks!

**Comment by Moltdar** [comment]
fixed by https://github.com/ClusterM/hakchi2/issues/496

**Comment by Moltdar** [comment]
had it happen again with latest build with the fix i had mentioned :(
Only seems to happen when haxchi is running and connected to it, and most of the time but not exclusively after synching games

here are some of the errors i got when it got sometimes either rebooted or got frozen and couldn't even shutdown without pulling power plug
first error is the main one I would get outputted in a loop while it's rebooting (using debug hakchi2)
after 4-5 reboots it always ends up going through, or if I shutdown hakchi2 it stops looping immediately

```
clovershell disconnected
clovershell connected
[ -d /var/lib/hakchi/firmware/ ] && [ -f /var/lib/hakchi/firmware/*.hsqs ] && echo YES || echo NO # exit code: 0
cat /etc/clover/boardtype # exit code: 0
cat /etc/clover/REGION # exit code: 0
Detected board: dp-shvc
Detected region: USA
df /dev/nandc | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code: 0
clovershell read timeout   at com.clusterrr.clovershell.ClovershellConnection.Execute(String command, Stream stdin, Stream stdout, Stream stderr, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 654
   at com.clusterrr.clovershell.ClovershellConnection.ExecuteSimple(String command, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 623
   at com.clusterrr.hakchi_gui.WorkerForm.GetMemoryStats() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 721
   at com.clusterrr.hakchi_gui.MainForm.Clovershell_OnConnected() in D:\Projects\C#\hakchi2\MainForm.cs:line 294
clovershell disconnected
```

```
write error   at com.clusterrr.clovershell.ClovershellConnection.writeUsb(ClovershellCommand cmd, Byte arg, Byte[] data, Int32 pos, Int32 l) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 433
   at com.clusterrr.clovershell.ClovershellConnection.Execute(String command, Stream stdin, Stream stdout, Stream stderr, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 638
   at com.clusterrr.clovershell.ClovershellConnection.ExecuteSimple(String command, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 623
   at com.clusterrr.hakchi_gui.MainForm.Clovershell_OnConnected() in D:\Projects\C#\hakchi2\MainForm.cs:line 254
```

```
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 385
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 240
```

```
clovershell read timeout   at com.clusterrr.clovershell.ClovershellConnection.Execute(String command, Stream stdin, Stream stdout, Stream stderr, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 654
   at com.clusterrr.clovershell.ClovershellConnection.ExecuteSimple(String command, Int32 timeout, Boolean throwOnNonZero) in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 623
   at com.clusterrr.hakchi_gui.WorkerForm.GetMemoryStats() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 721
   at com.clusterrr.hakchi_gui.MainForm.Clovershell_OnConnected() in D:\Projects\C#\hakchi2\MainForm.cs:line 294
no answer from device   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 256
clovershell disconnected
clovershell connected
kill all exec: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 392
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 240
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 385
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 240
clovershell connected
kill all shell: write error - IoTimedOut   at com.clusterrr.clovershell.ClovershellConnection.killAll() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 385
   at com.clusterrr.clovershell.ClovershellConnection.mainThreadLoop() in D:\Projects\C#\hakchi2\Clovershell\ClovershellConnection.cs:line 240
```

**Comment by ClusterM** [comment]
Try other cable/port.

**Comment by mmax3** [comment]
Im having strange issue, probably related to power issue generally.
When Im using HDMI to VGA adapter the console goes into boot,restart loop. Then I used different power adpter. It helped, but still occasionaly when Im saving a game or start from a save, it get restarted. I noticed that the HDMI to VGA converter gets quite hot too. None of this happen when Im using direct HDMI connection to TV. Id doesnt matter if its original or custom kernel .And none of this happened prior to 1st hakchi flashing. So I assume that the console has problem to power "external" devices like HDMI to VGA adapter or also wireless controller receiver [(Issue #668](https://github.com/ClusterM/hakchi2/issues/668)).

**Comment by Drakonas** [comment]
Closing this as it is reported fixed by the OP. @mmax3 the SNES classic probably doesn't provide enough power to power an adapter like that. All I can say is try the usb cable and power adapter the SNES came with. If that doesn't help, it cannot be fixed. This is not a Hakchi-fixable issue. Closing.
