### ISSUE TITLE
Folders not working

### ISSUE THREAD

**Issue by Localhorst86** [ClusterM/hakchi2#498]
So, I just took my both classic consoles (NES and SNES), flashed a custom kernel to it and uploaded a single additional game (each). Both menus had a folder item that said "more games". But both devices froze when I tried to enter the folder.

I then set hakchi to disable folders alltogether, resynced and they worked fine.

Are folders broken? 

Hakchi2 version used: 2.20 exclusively. Web installer.
NES/SNES Classic previously hacked: no
language settings: english and german

**Comment by Darky2k1** [comment]
folders working here...

**Comment by HappyTepid** [comment]
I'm having the same issue.

**Comment by nameless1** [comment]
Same issue here too, have to unplug the device and plug it back in to get the folder to open...

**Comment by Localhorst86** [comment]
Additional info: My systems were previously stock and I used 2.20 to install the custom kernel and the additional game. Systemlanguage is german. Maybe @darkunderdog is running a previously installed foldersetup?

**Comment by rapt3r** [comment]
Exact same issue. Folders not working. System crashes.
Installed the Hack on Stock with 2.20.

**Comment by hoderer** [comment]
Whenever the system freezes or reboots, it could have something to do with your power supply. Try to change your AC-adapter. Maybe it helps. I never had problems with folders.

**Comment by Localhorst86** [comment]
@hoderer while I do think my Aukey 4.8A power supply would have been more than sufficient (seeing as the manuals say that you need a 1A only) I tried with a 3A Anker one as well. The same issue arrose.

**Comment by Darky2k1** [comment]
I did an uninstall and redid everything with 2.20.. and all works who knows...

**Comment by hoderer** [comment]
Ok. Then it's most likely not a power related problem.

**Comment by Localhorst86** [comment]
@darkunderdog trying to find as much information here as possible :)
When you say you "uninstalled and redid everything", did you actually use the uninstall function from the menu or did you only re-flash the stock kernel, then flashed the custom one? What is your SNESC language set to?
I currently reverted back to full stock and want to re-install the non-portable version of hakchi2, but it seems the server is currently down so I might have to wait until tomorrow.

**Comment by Darky2k1** [comment]
I used the uninstall feature within Hakchi, Reinstalled Original Kernel, then installed custom Kernel

**Comment by Darky2k1** [comment]
What version of Hakchi2 can't you find?

**Comment by rsn8887** [comment]
Same problem here: black screen when entering "more games" folder. Unplugging and replugging power then shows the folder contents. Black screen again when leaving "more games" folder by going back to parent. Again, replugging power shows the folder correctly.

**Comment by Darky2k1** [comment]
@rsn8887 does everything work correctly now? or do you still have issues? what type of power adapter are you using?

**Comment by Localhorst86** [comment]
2.20, but the installer was able to grab it just now. I uninstalled hakchi2 completely from my device and PC (deleting the hakchi2 folder in my documents) and did a fully clean install of hakchi2 on my PC and the NES mini (reverting to factory settings here as well), left every setting at default and added a single NES game. Again, the software created a folder titled "more games" that I can not enter. The system freezes, it wont even shut down. I have to disconnect the USB cable to power the device down, and when I power it back on the system enters the folder. But exiting the folder results in the same issue again.

**Comment by ClusterM** [comment]
Seems like you used older version before. Do full uninstall using "Uninstall" feature and install custom kernel again.

**Comment by paranoidpal** [comment]
same problem here.....What's the fix???

**Comment by ghost** [comment]
I'm having the same issue and I never used an older version at all.

**Comment by rapt3r** [comment]
Did a clean install of 2.20 (no previous installations)
Did a full uninstall and a new installation of the kernel.

Folders not working (black screen)

**Comment by Localhorst86** [comment]
@ClusterM nope, i was using 2.20 only. Both systems were stock before, no hakchi ever installed on any of them. I also just re-re-tried by uninstalling it from my NES classic, completely wiping hakchi2 from all my systems (target devices as well as my PC). I can reproduce this issue with 100% "success rate". I even did reset the NES to factory defaults.

**Comment by ghost** [comment]
What is the proper setting to use in order to disable folders? I don't like having to shut off my system by removing the power chord - and I'd like to step around that problem entirely. Do I just select "Disable pages/folders" or something else?

**Comment by rsn8887** [comment]
I have never used anything but 2.20 final release from github (webinstaller). I tried three different power supplies including the original psu that came with the system, no fix. 

I added 65 games. By restarting the system I can see the contents of More Games. It contains another folder MRU-ZOM or something like that with the rest of the added games. If I enter that folder, again I get the black screen crach. A restart then shows the contents for that folder.

By restart I mean disconnecting power and re-connecting power, because the black screen crash disables the power switch on the top of the system.

**Comment by Darky2k1** [comment]
Is everyone having the problem using the web installer version? Have you tried - https://github.com/ClusterM/hakchi2/releases/download/2.20/hakchi2.20.zip ?

Trying to identify commonalities.

**Comment by ghost** [comment]
I used the web installer version for sure. I am retrying now but if it doesn't work - I'll try that one.

EDIT: I was able to disable the folders for now, I might leave it like so until this gets sorted.

**Comment by Darky2k1** [comment]
You should try the version that I listed - It looks like everyone with the issue is using the Web Installer. (Putting more than 30 or so games in one folder will cause other issues)

**Comment by ghost** [comment]
At the time I only had 2. I don't see any advantages to folders anyways and didn't want them in the first place... but interesting that the web installer version could be having some issues.

**Comment by ClusterM** [comment]
Are you using portable or non-portable version?

**Comment by dbw-holic** [comment]
Having same issue here. A previous Hakchi2 user. When Hakchi2 was just out, I downloaded the compressed file version. Copied and overwritten my previous configs and games from 2.17d to 2.20. I did not see any abnormal behavior till I enter "More games..." folder on SNES Mini UI. It shows a black screen, physical power switch stops working. The only workaround is to unplug and re-plug the power cord. Once the screen boots up, I am in the folder where I was trying to open. When I try to exit the folder and back to root directory (Nintendo default UI) same thing just happened. 

I then backed up all my games and started from a full clean Hakchi 2.20 (no configs or any other content have been brought over to the 2.20 version). The issue has been consistently reproduced. FYI, this is an Australian model CLV-301. Also when I have dumped the kernel, Hakchi2.20 did prompt a warning "This is an unknown dump, do you want to continue"

**Comment by mbaran5** [comment]
I have the same issue using the “web installer”. I just went through the process on a SNES that had never been hooked up to a computer before. I did all of this in the last 30 minutes.

**Comment by Localhorst86** [comment]
@darkunderdog @ClusterM The issue seems with the version the webinstaller uses. The standalone version was able to create a working folder structure. I am now going to double check by reverting to the web installer version and back to the standalone

**Comment by ghost** [comment]
I was using the non-portable version from the web installer personally. The SNES Classic had not been modified in any way previously and I added 2 games using all the default settings.

**Comment by Darky2k1** [comment]
@mbaran5 - Utilize this version instead https://github.com/ClusterM/hakchi2/releases/download/2.20/hakchi2.20.zip

**Comment by dbw-holic** [comment]
@Localhorst86 See my comment above, I am using compressed file version and am able to consistently reproduce the issue.

**Comment by ClusterM** [comment]
Seems Oh, this is web installer problem. I'll upload update in a minute.
It will update automatically after few launches.

**Comment by Localhorst86** [comment]
@dbw-holic you are not using clean installs, though. The cause of your issue could be unrelated.

**Comment by rsn8887** [comment]
@Darkunderdog: You were right, it is only the Web Installer version that exhibits this bug!

The portable release works perfectly for me now!

**Comment by Darky2k1** [comment]
@rsn8887 Awesome! :)

**Comment by ClusterM** [comment]
Please update your web-version and reinstall custom kernel.
Sorry for that :(
