### ISSUE TITLE
Not an issue...a concern

### ISSUE THREAD

**Issue by kwise1** [ClusterM/hakchi2#50]
I know nothing about these things. My concern is what I can do wrong.  It took me a long time to get a classic.  Is there a way I can screw this up?  I know the FAQ said original files won't be touched.  Is there a restore if something goes wrong?  I have about 100 games I would like to put on (including original 30). If I try to put them on and they don't fit will it mess up?

Thanks for dealing with these silly questions.

**Comment by baconcow** [comment]
Make sure to follow the instructions and make a backup of the original kernel. Store it somewhere where you will not lose it. If something goes wrong, you can always reflash the system. I have not read about anyone permanently harming their system. The worst case I read about was that someone had to reflash the original kernel. I believe you can even use another kernel. Ideally, they should be identical, although I've read the checksums between them appear to differ. I had the same worries as you and put about 78 game on mine (including the original 30). I am preparing to soon put on an additional 194. Others have successfully put on over 600. As long as you use version 2.11 of hackchi2, and do not increase the folder limit beyond 30, you should have no issues with 100 games with 4 saves states each.

**Comment by kwise1** [comment]
How do you back up the original kernel?

**Comment by baconcow** [comment]
When you first go to add games, the application will guide you through the entire process, including backing up your kernel.

**Comment by kwise1** [comment]
Thank you.

**Comment by mlabarca** [comment]
Also I suggest using this in Windows if possible, there seem to be more issues with people using parallels on Mac or etc.
