### ISSUE TITLE
Transfer SAVE files from NES to SNES

### ISSUE THREAD

**Issue by fluffiebuddie** [ClusterM/hakchi2#500]
So is there any way I could transfer my beloved ROM save files from one console to the other?
Thanks a bunch!

**Comment by ClusterM** [comment]
Only for RetroArch.

**Comment by fluffiebuddie** [comment]
Actually the save file I want to transfer is from a GBC rom, which requires RetroArch.
The problem is that I can't find a clear explanation anywhere of how I can transfer the save files to my SNES mini.

**Comment by Drakonas** [comment]
You need to ask this on reddit or discord @fluffiebuddie this is a bug report tracker not a question asking forum. Closing.

**Comment by 91ajames** [comment]
Should try searching at gbatemp, 

‘ Save File NES to SNES ‘
