### ISSUE TITLE
Bricked SNES Classic

### ISSUE THREAD

**Issue by zimmertr** [ClusterM/hakchi2#501]
I didn't realize when `synchronizing` the stock games would be removed. In hindsight that seems obvious. Anyway, I attempted to flash back the original kernel to recover the original games and my console appears to have soft bricked. 

I can still interface with it through `hakchi2`. Meaning I can try to flash a custom or original kernel at any time. Unfortunately, after a successful flash, only the power LED turns on with the console; the display never works. 

I was able to `telnet` into the console using Putty a single time. I deleted _Chrono Trigger_, the original game I synchronized from `/usr/share/games/`. Unfortunately this did not resolve the issue. And following up with further flashes does not either. I can no longer `telnet` into the device. Have not attempted to initiate an FTP connection.

Anyway it's a bummer but I accept full responsibility for flashing beta software to the device. If I can do anything to aid development or potentially recover my device please let me know. Otherwise, let this at least serve as an instance where it "didn't work."

**SNES Classic**: `USA preorder from Best Buy.`
**Hakchi2 Version**: `2.0.18.11`
**Flashing Date**: `10/7/17`

**Comment by Darky2k1** [comment]
Stock games aren't removed if you have original games checked, You should be able to do an uninstall from Hakchi2 and reinstall your original kernel.. Let us know if that doesn't fix your your system.

**Comment by Darky2k1** [comment]
Also utilize this version of Hakchi2 if you aren't - https://github.com/ClusterM/hakchi2/releases/download/2.20/hakchi2.20.zip

**Comment by ClusterM** [comment]
Try to do uninstall.

**Comment by marduk128** [comment]
same problem, with version rc4 worked well, but with 2.20 died

**Comment by zimmertr** [comment]
Uninstalling and reflashing with v2.2.0 worked. <3 thanks guys. 

Any idea why Chrono Trigger gave me a C7 error? 

Is it possible to play romhacks and custom super nintendo games yet? Like A SMW Central Production for example? It's distributed as a Lunar IPS patch file that you apply to a rom.

**Comment by zimmertr** [comment]
Uninstalling and reflashing with v2.20 fixed it! Thanks guys!
