### ISSUE TITLE
Web ClickOnce, where the dump folder?

### ISSUE THREAD

**Issue by hxhieu** [ClusterM/hakchi2#502]
I want to get a copy of the backup kernel but couldn't find where the dump file with ClickOnce web installer?

**Comment by Localhorst86** [comment]
https://github.com/ClusterM/hakchi2/wiki/FAQ
Q: Where non-portable version stores files?

A: Non-portable version (distributed as .exe file - web installer) stores all files (kernel dump, configs, games, etc.) in the "My documents\hakchi2" folder.

**Comment by hxhieu** [comment]
Thank you! My bad been looking around AppData :(
