### ISSUE TITLE
MD5 checksum is unknown (SNES Mini)

### ISSUE THREAD

**Issue by andwhyisit** [ClusterM/hakchi2#503]
```
Kernal dumped, but the MD5 checksum is unknown:
0f890bc78cbd9ede43b83b015ba4c022
Do you want to continue? Y/N
```

From SNES Mini purchased in Australia.

**Comment by JohnSilver78** [comment]
Have the same problem here...

**Comment by dbw-holic** [comment]
Same here, I also encountered another folder/black screen issue. When I run a SNES game using RetroArch it throws me a "C8: An error has occurred".
If games were launched without using snes9x2010 it just comes back to the selection menu after a blink.

**Comment by dbw-holic** [comment]
@ClusterM Could it be the custom kernel didn't work for Australian model at all? I am having the checksum unknown issue and black screen issue with folders reported here #498 
When I try to launch any unofficially added roms, it blinks screen and goes back to the selection menu immediately.

**Comment by dbw-holic** [comment]
@andwhyisit BTW, just double checked and can confirm the unknown MD5 checksum shows on my screen is exactly the same. (Aus model)

**Comment by Darky2k1** [comment]
I don't believe this is an issue at all.. you can just hit okay and continue.... Its just that it is "Unknown"...  and the person opening this issue didn't mention a problem.. You just need to let cluster know to add them so they are "known"

**Comment by ClusterM** [comment]
Added it to database, thank you!
