### ISSUE TITLE
Issue with folders

### ISSUE THREAD

**Issue by dustbunnyck** [ClusterM/hakchi2#505]
I have hacked my SNES and added 10 games to the unit. When booted up it shows the original 21 games then a folder icon. When I click the icon the screen goes dark and even when I turn the power button off the light stays on so I have to unplug the unit then it turns back on when I plug it back in. After I plug it back in it will have entered that folder and the new games are showing. When I hit the folder to go back to the original games this happens again. I reloaded Hackchi and turned off all folders and I noticed it only shows 20 games then has a folder for the rest of them. I have the same issue when clicking the folder. I'm unsure what I am doing wrong

**Comment by tm0z** [comment]
Mine is doing the exact same thing

**Comment by ClusterM** [comment]
Fixed. Redownload and reflash custom kernel.
