### ISSUE TITLE
C8 error on close when than 60 games in the home folder

### ISSUE THREAD

**Issue by skwipe** [ClusterM/hakchi2#508]
Model : US SNES Classic
Hakchi version : 2.2
Number of games total : 86 (All SNES roms, some rom hacks)

I have tested with "Custom folder structure" and "No folders" option and that's when I get the error
When testing with "Max amount of games per folder > 50" and "Automatic sorting", no error.
When testing with "Max amount of games per folder > 60" and "Automatic sorting", no error.
When testing with "Max amount of games per folder > 80" and "Automatic sorting", no error. (Although it seems to be listing 60 only, and separating the rest in a different folder, so that could be an issue in itself))
When testing with "Max amount of games per folder > 100" and "Automatic sorting", C8 error

Not sure if an issue, or just limitations of the system. I have tested most of the games and they all boot flawlessly. it's only when closing the power that I am getting the error, and I can only unplug the power to close it entirely (will hang forever).

**Comment by ClusterM** [comment]
Limitations of the shell, same as on NES. Check FAQ.

**Comment by nekonall** [comment]
you font have to unplug the power you can hold reset and flick the power switch on/off and it will shut down normally
