### ISSUE TITLE
C8 error on shutdown

### ISSUE THREAD

**Issue by justgoonies** [ClusterM/hakchi2#509]
When ever I hit the power switch I get a c8 error. If I hit the power switch again it shuts down correctly

**Comment by HoodedManLloyd** [comment]
Same here, Hakchi 2.20, everything working real fine.
145.4MB / 300.0MB , added 57 games + 21 originals.
Whenever i shut down the console, C:8 Error, have to Power it back on while error on screen, then Power it off.

Thank you for further support.

**Comment by Dweller7777** [comment]
Can confirm. SNES Mini, Hakchi2 v2.0.20.14, 21 original + 142 custom ROMs. 201.2 MB used. "remove_thumbnails" module installed. System works great otherwise.

As an aside - is the amount of time required for a reset directly proportional to the number of ROMs installed, or total space used? It takes approximately 15 seconds to perform a reset, either using the switch on the console or the controller shortcut.

Thank you!

**Comment by hoderer** [comment]
Get the same error on shutdown (8 of 10 times). Don't have "remove_thumbnails" installed. Hoping for a fix.

**Comment by ghost** [comment]
I have two SNES classics both flashed and both with the same custom ROMs. One does not C8 error at all, the other will C8 error if you shut down on the game select screen but not in a game.

**Comment by DachandeYautja** [comment]
I have the same issue as kpryor98 "will C8 error if you shut down on the game select screen but not in a game."

**Comment by ericiidx** [comment]
Also having this exact issue. Everything else works fine; first power down results in C8 error. Toggling the switch back on and off successfully shuts down.

**Comment by cmayz19** [comment]
I’m receiving the same error on shutdown after adding 5 new games to my system. Have to toggle the power to shut it down fully. It boots up fine though

**Comment by danielsan1** [comment]
Good to hear that I'm not alone :) Have this issue since RC4. My hope was that it will disappear with 2.20 - but still this error while shutting down :( About 100 games, everything works perfect - except the shutdown (I also have to toggle twice) Thanks for help in advance!

**Comment by FGOD1983** [comment]
Same issue here.

I only added 73 games, no mods or whatever installed.

**Comment by danielsan1** [comment]
Guys, I found this https://github.com/ClusterM/hakchi2/issues/406 and played around with the pages/folder/sorting settings. And the issue was gone! Don’t know what that mean to people with just 5-10 more games but splitting equal to pages and max 30 per page fixed it for me!

**Comment by ericiidx** [comment]
Sorry, dunno how to reply on github -- I'm a bad CS grad -- but danielsan1's suggestion fixed the issue for me. Too many games in the root menu. Exactly what he suggested works (Folders, split games equally, max 30 per folder.)

**Comment by BokuNES** [comment]
i found that if i put the rom limit to 80, the error disappear, i think that is a temporary solution to the problem (my snes mini have the thumbnails remove and the music hack modules installed)

**Comment by ghost** [comment]
@BokuNES did you set the limit yourself of is there an option in hakchi to do it?

**Comment by GhostOfFoxhound** [comment]
I just experienced this myself. Has anyone found a solution?

**Comment by FGOD1983** [comment]
try setting the limit lower then 45 per page

**Comment by Drakonas** [comment]
This error is usually due to what @FGOD1983 said: having too many games listed in one folder. Also, try a different USB port or try a full uninstall, og kernel flash, and reinstall of custom kernel. If that doesn't work, backup your saves with Hakchi, uninstall Hakchi from the SNES, flash OG kernel, perform a factory reset from the SNES Classic menu (WILL ERASE ALL SAVES), and flash custom kernel.

**Comment by Drakonas** [comment]
Closing this issue. The OP has not responded since creating the ticket. This is a bug report tracker not a discussion tracker.

**Comment by serious-angel** [comment]
What to do if the same issue?

**Comment by Jatts-Art** [comment]
Getting this error as well, and I do not have the "no thumbnails" addon installed.
