### ISSUE TITLE
Snes some games just black screen

### ISSUE THREAD

**Issue by arc100** [ClusterM/hakchi2#511]
Got everything working for the most part except a 
few of the games I added like Illusion of Gaia don't work. I get for the start screen, there is no sound and when I try to start a new game it is just a black screen.

**Comment by gnadenlos** [comment]
Use the Retroarch mod for problematic games.

**Comment by arc100** [comment]
Okay thanks, I will look into adding that next.

**Comment by DecanFrost** [comment]
Why not just retroarch for all games ?

**Comment by Maelstrom1** [comment]
Would that work for Chrono Trigger? For me, it boots fine, but the opening text after choosing chrono's name and the scroll just ends in a black screen and he never awakens from his sleep.

**Comment by dave11674** [comment]
Im new to snes mini how do you use retroarc ?

Thanks

Dave
