### ISSUE TITLE
Flashing custom kernel error - invalid kernel size: 4491264

### ISSUE THREAD

**Issue by MrOne2** [ClusterM/hakchi2#512]
When I try to flash my custom kernel I keep getting this "invalid kernel size: 4491264" error. I've tried flashing multiple roms at once, and i've tried flashing a single rom. Both give me the same error?   Any advice would be greatly appreciated!

**Comment by ClusterM** [comment]
Kernel can't so big. Are you putting ROMs inside kernel's ramfs? Why?
