### ISSUE TITLE
SNES - C7 Error on some games

### ISSUE THREAD

**Issue by dreynolds2388** [ClusterM/hakchi2#515]
Hello,

I receive a C7 error on some games such as Super Mario All Stars, Killer Instinct, and Street Fighters. I did download the retroarch mod. Could these 3 games be apart of the 25% that do not work on the system?

**Comment by MasterPlatinum** [comment]
Killer Instinct work great for me..

**Comment by shaman78** [comment]
I have seen on Youtube some people playing Super Mario All Stars

**Comment by shaman78** [comment]
Street Fighter #492

**Comment by MasterPlatinum** [comment]
Super Mario All Stars also Working great.

**Comment by dreynolds2388** [comment]
Hmm, maybe it's the ROMs I have. I was using the roms I've had saved for some years after modding the PSP and Wii. Thanks. :D

**Comment by dreynolds2388** [comment]
Apparently I am not installing retroarch correctly. I selected it under modules to install after dropping it into Hakhchi2 but nothing.
