### ISSUE TITLE
Some Music bug...

### ISSUE THREAD

**Issue by Speedmechanic** [ClusterM/hakchi2#516]
Do you know what cause some the game .rom on Snes (US) to skip some notes on the music..like a bar or two sometimes..it's not that bad but can it be resolve?

**Comment by roflcopter777** [comment]
Sounds more like an SPC700/S-SMP emulation issue, as it's not exactly cycle accurate like Higan or Snes9x, so some games may not be emulating it. Maybe.

**Comment by Speedmechanic** [comment]
well..okay but what can i do? IS some snes rom different cuz some others works..

**Comment by roflcopter777** [comment]
I would suggest RetroArch in Snes Classic to get around the games with major sound issues

**Comment by Drakonas** [comment]
We kind of need to know what games, but regardless: what @roflcopter777 said is true. Use retroarch for problem games. Any audio issues with certain games and not others have to do with canoe's incompability with the rom. That is Nintendo's fault, not Hakchi's. Closing this.
