### ISSUE TITLE
Can't write to USB

### ISSUE THREAD

**Issue by Laseki** [ClusterM/hakchi2#517]
Tried pretty much everything at this point, always gives me the same "Can't write to USB" error when trying to upload the custom kernel.
Dunno if it will help, but here is the error message from the debug version: https://imgur.com/a/6UVX5

**Comment by Shona1984** [comment]
Try USB 2.0 instead of USB 3.0
Had the same problem and i tried it now with USB 2.0 and it worked

**Comment by ClusterM** [comment]
Try other cable/port.

**Comment by ohthatsnasty** [comment]
I'm in Australia with a pal Snes mini, having the exact same issue with the exact same error message.

**Comment by risus-sardonicus** [comment]
I'm also having this issue. I tried several USB cables (including the one provided with the SNES mini) and 6 different USB ports on my PC (USB 2.0, USB 3.0, USB 3.1 front and rear). 
The kernel dump is functional and passes as expected. 
When trying to flash the custom kernel the process continues to dumping the kernel and patching it, then throwing the error message. 
I verified the driver is installed correctly, showing "NES Mini" in the device manager.
I disabled antivirus protection (Bitdefender Internet Security 2018).
Still no success.
I'm hoping for suggestions and some help.
![hakchi-2 20-usb-error](https://user-images.githubusercontent.com/32609964/31315212-f90e94a6-ac13-11e7-9584-453e907c6d34.JPG)

**Comment by joetheuseless** [comment]
same problem i hope a fix is released soon i am also using usb 2.0 and the officla Snes Mini usb cable

**Comment by ohthatsnasty** [comment]
I got mine working using a different pc. I had to use one of my front usb 3.0 ports, rear 2 and 3 ports didnt work.

**Comment by cheekywario** [comment]
Using the original USB Cable. I had to switch ports and started hakchi 2.20 as "Run as Administrator"

**Comment by FaizVisram** [comment]
Managed to fix this by simply rebooting my PC. Using a Microsoft Surface 3.

**Comment by NinePoundHammer** [comment]
So I am running into the same problem.  I notice when I connect my SNES Classic it reads ??? for the remaining storage.  I have tried two computers, multiple cables, USB 3.0 and 2.0.  Any ideas?

EDIT:

I was able to resolve my problem by using my secondary computer, a Laptop running Windows 10 (don't have my specs with me currently.)  I was able to get this to work through the webinstaller.  It seems my issue all resided with the installation of the .net 3.5 framework.  Once I was able to sort that out and get it installed I was able to get the driver's installed properly and then the kernel flash went through with no issues.

**Comment by risus-sardonicus** [comment]
I found an awkward but simple solution.
I'm using a Ryzen 1600X with a ASUS Prime B350M-A mainboard and the error kept persisting.
It seems to be related to an unusual USB circuit on the motherboard or driver issue although I never had any problems before.
I thought how about using a USB-3.0 hub and you know what? It works!!!
I use a UGREEN 4port USB3.0 hub 20291 which I bought some time ago on Amazon for about 10€.
Maybe other hubs are working too.

**Comment by Blaze1499** [comment]
I had the same issue as @risus-sardonicus. Using a Ryzen 1700 with ASUS Prime B350-plus mobo, couldn't resolve the issue. Moved everything to a USB and got it to work on both my i5-7200u laptop and my i3-6100 with a h110m mobo. Issue is still a mystery to me so beware Ryzen owners, you may not be able to use hackchi until this is resolved. Will edit if I find a solution

**Comment by KinnusJarkki** [comment]
Had the same problem. Got the error many many times with my computer which has Ryzen 1600 processor, tried different usb cables and ports, error all day long. 
First try with my other computer (no Ryzen there), everything worked properly.

**Comment by Drakonas** [comment]
Please continue discussion on #620 for Ryzen users. For others, this should have been fixed during 2.21 development. 2.20 was still beta software mostly. Closing this.

**Comment by pplatoon** [comment]
i have identic problem. cant write on usb...i have diferent usb and diferent cable and identic error...any solution??
