### ISSUE TITLE
[SNES] - Characters missing from game titles

### ISSUE THREAD

**Issue by funkboy27** [ClusterM/hakchi2#519]
Specifically noticed in Joe and Mac and Joe and Mac 2

The J is missing off both titles within the MENU, however I confirmed that the games do have the correct titles in HAKCHI

EDIT:

Looks like capital U, and J.  small q, w, as well

**Comment by gnadenlos** [comment]
You are missing the fontfix. Do you have the latest hakchi and enabled "use extended font" in the settings?

**Comment by funkboy27** [comment]
Latest Hakchi 2.20.  "use extended font" is checked as well...

**Comment by Drakonas** [comment]
This should have been fixed with newer releases.
