### ISSUE TITLE
Getting Out ofMemory error

### ISSUE THREAD

**Issue by brewc53** [ClusterM/hakchi2#52]
Ok I want to say this is a fantastic hack uploaded a few games and decided today to add them all. I found the file wit all NES roms and have been unsuccesful in doing so. I have tried twice and get about 3/4 of the way through, done the reset/ power cycle about 4-5 times and I get a box that says "Exception of type 'System.OutOfMemoryException' was thrown. please try again"
  Any help of what is going on to cause this?

**Comment by ClusterM** [comment]
I added force garbage collection, seems like it will fix problem on 32-bit systems.
