### ISSUE TITLE
[SNES] Sound Issues (2 titles)

### ISSUE THREAD

**Issue by JDFerel** [ClusterM/hakchi2#520]
While I haven't had a chance to try everything I've installed in my SNES mini to check there's two titles that arn't playing sound right.

Terranigma (PAL, and pre-patch NTSC) is playing no audio at all
Earthworm Jim 2 - no voice lines are being played (a strange click seems to be heard whenever these are meant to be played)

**Comment by roflcopter777** [comment]
Earthworm Jim 2 has that issue due to how it streams audio data, Byuu had an article about it on his Higan site a while back. So far, only Snes9x and Higan play it properly. You can mod RetroArch to load it on the Snes Mini.

**Comment by Jamieasy** [comment]
Are you using a sound bar?!

**Comment by Jamieasy** [comment]
I had issues with this I have to reroute audio through the red and white connecters from tv headphone jack

**Comment by Jafrom** [comment]
Same Problem with my first to test games like Tiny Toons, ToyStory, Lufia,Tom&Jerry all PAL.
Perhaps that could be a problem?

**Comment by TooGz** [comment]
Idem here, it seems that the sound problem occure only with PAL roms.

**Comment by baconcow** [comment]
This does not sound like an issue related to hakchi2.

**Comment by JDFerel** [comment]
@Jafrom Unless you're running Retroarch I do believe PAL roms don't work on the SNES mini, as the NES mini used only NTSC roms also. (Though I could be wrong)
@TooGz Can confirm the EWJ2 rom is USA, Tried both NoIntro and CoolSNES

**Comment by Drakonas** [comment]
These games are incompatible with Canoe, and this is not Hakchi's fault. This a Nintendo code issue. Closing this. Use Retroarch for problem games.
