### ISSUE TITLE
Can't communicate with SNES Classic on 2nd usage:

### ISSUE THREAD

**Issue by Firebrandx** [ClusterM/hakchi2#521]
Using 2.20, I was able to add games no problem. However, I wanted to add some more games, but the red power light on the SNES Classic will no longer turn on when I plug it into my PC's USB. Hakchi2 can't communicate with it either. Was there an error introduced by Hakchi2 after adding new games? The console boots up fine when just plugged into a display. It just won't communicate with Hakchi2 now.

**Comment by Firebrandx** [comment]
I found the problem: I was using the wrong menu command. Needed to use "Flash Custom Kernel.

**Comment by Moltdar** [comment]
then close the issue?

**Comment by Firebrandx** [comment]
Leaving it open because I'm not the only one with this issue. It's a procedural mistake by the Hackhi2 program itself. If you review the issues posted, you'll see I'm not the only one complaining about this. The program leads you to believe all you need do is press the sync games button, which worked on the FIRST attempt to add ROMS. When you go back a for a 2nd attempt, the sync button will not work and you'll never be able to communicate with the SNES Classic. It was only through experimenting that I found the "Flash Custom Kernel" forces correct communication with the SNES Classic.

**Comment by Drakonas** [comment]
Actually people can search closed issues. Issues are meant to be closed when they are fixed or they will clutter the tracker.
