### ISSUE TITLE
Super street fighter 2 keeps giving error when trying to start

### ISSUE THREAD

**Issue by Jamieasy** [ClusterM/hakchi2#523]
Error when trying to start super Street Fighter 2 , first game I have had a problem with using USA room anyone know a fix for this without using retroarch?!!

**Comment by Moltdar** [comment]
yup, same here, tried both USA and PAL using built-in and retroarch snes9x2010, no go

**Comment by Jamieasy** [comment]
Glad I'm not going crazy lol hope they fix this it should work idk why it's a pain in the ass

**Comment by ClusterM** [comment]
Select this game, press Ctrl+Atl+E, write zeros to every field, press OK, sync. Should work.

Will be fixed, thank you.
