### ISSUE TITLE
[SNES] Controller randomly not working after sync/upload/reboot

### ISSUE THREAD

**Issue by emufrance** [ClusterM/hakchi2#524]
Sometimes after 2 ou 3 (random) sync operations, the controller doesn't respond. Need to shutdown the console completely to resolve the issue (v2.20 debug version). Had the same behavior with rc4.

**Comment by ClusterM** [comment]
I noticed it too. Can't understand why it's happens yet.

**Comment by meegle84** [comment]
Same issue here.

**Comment by Drakonas** [comment]
@emufrance are you still having issues with this?

**Comment by emufrance** [comment]
not since the last release (2.21+). But i don't sync often the snes now as my setup is complete.

**Comment by meegle84** [comment]
I did some tests. 
Since I flash the original kernel, then the custom kernel with hmods and roms, and classify roms in subfolders (to not have so much in one folder), the issue has gone.

**Comment by Drakonas** [comment]
I will close this issue for now. Respond here if you have the issue again.
