### ISSUE TITLE
[Feature Request] Option to enable 'debug version' with release Hakchi2

### ISSUE THREAD

**Issue by qwertimus** [ClusterM/hakchi2#525]
I appreciated seeing the processes logged in the 'debug version'; it would be nice if there were an option to enable the 'debug version' / show log / verbose mode with release Hakchi2.
It's also frustrating how the web installer works (installing to an obscure location with appref links), but I'm sure there's a reason for that.

**Comment by Moltdar** [comment]
just rename official executable _release, download the debug one and get the 3 files you need and run whichever one you like?
