### ISSUE TITLE
[Feature Request] CRT Filter Disabled But Scanlines Remain On

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#529]
Would it possible to have this as a checkbox option in the main GUI?

Nice scanlines without the blur!

It can be achieved manually. See the attachment.

![5 turn off filtering but keep scanlines](https://user-images.githubusercontent.com/32608765/31314663-b8f08e68-ac38-11e7-9a39-f379bb0b4534.png)

**Comment by Hackcell** [comment]
I love this idea :-)

**Comment by ghost** [comment]
I\m not sure how to do the above. Maybe someone could create a tutorial?

**Comment by ghost** [comment]
So it looks like you can already do this:

If you just want scanlines without the  blur filter, add the following in the global command line argument:

-filter 2 -magfilter 0

**Comment by Hackcell** [comment]
That worked.
