### ISSUE TITLE
nes classic custom kernel

### ISSUE THREAD

**Issue by nicholastennis88** [ClusterM/hakchi2#53]
It prompts me to download custom kernel, but when i do it says the file cannot be found.. Any suggestions?

**Comment by ThatGuyDogboy** [comment]
Disable all Antivirus programs and rerun. If it doesn't work, check your quarantine on Antivirus. It removes cpio.exe and mkeboot

**Comment by ThatGuyDogboy** [comment]
Also, I had to start fresh with a fresh download and run it as admin.

**Comment by nicholastennis88** [comment]
you're awesome!! thank you!!

**Comment by ThatGuyDogboy** [comment]
I'm assuming it worked?

**Comment by nicholastennis88** [comment]
It sure did!!
