### ISSUE TITLE
Super Famicom Mini problem

### ISSUE THREAD

**Issue by Kazziki** [ClusterM/hakchi2#530]
Note: Have done this with the "Famicom mini" before.
Yes i am using the new version of hakchi2

So like many other's i'm trying to add new games to the new "Super mini famicom"
Unfortunately i don't get very far.
(My device get's recognized as "nes mini" even though I'm using the "SNES mini" (japanese version). Doesn't matter if i delete the drivers. Still installs itself as "nes mini".
Dont know if there's an issue there?)

Anyhow
Trying to flash and dump the kernal.
But during the dumping process i'm greeted with this.
"Invalid console detected! Detected console: SNES"

Now i have indeed selected "Super Famicom mini" as my "Console type".
Yet i still get this error. Any clues?

If i selected the "Snes classic mini" that might mess things up?
Seeing as i'm using the Japanese console.

Thanks in advance!

**Comment by Drakonas** [comment]
This was a problem with early releases of Hakchi. Maybe be patient and wait until it becomes stable next time.
