### ISSUE TITLE
Too many duplicate and distracting issues

### ISSUE THREAD

**Issue by Cabledragon** [ClusterM/hakchi2#531]
There are far too many duplicate, already answered, or down right distracting issues leaking in. (Yes, much like this one.)

It would be nice to keep this area clean and concise while simultaneously offering fair responses to all of those issues as they are resolved, duplicate or not. 

I volunteer myself and my currently ample free time to tidying up this area so that the major issues are able to bubble to the top and form a nice concise bug and feature list. My qualifications are: having lots of free time, having a good understanding of and experience with coding, asm, system design and management, , network infrastructure design and programming, superb English skills, and a desire to ensure the issues that are important are clear and visible to those working on the project so they can spend less time filtering through this and more time doing what they wish to do!

**Comment by TonyXL2** [comment]
Totally agree. Would be very helpful to both the devs AND users like me who want to see ACTUAL issues, and not just someone who wants to know if they can play Genesis games (you know, RTFM type of stuff).

**Comment by Drakonas** [comment]
@Cabledragon @ClusterM has been too busy to check the issues. I'm sure he feels sorry for this. If you contact him via Twitter you can usually get a better response. That's how I was given access to help out. We'd totally love the help. :)
