### ISSUE TITLE
[SNES] Only first sync/kernel update worked, following attempts will not start

### ISSUE THREAD

**Issue by explosiveaction** [ClusterM/hakchi2#534]
Using 2.20.

The initial one-click kernel dump, custom kernel update, and sync of games was a complete success. New game roms were added and tested playable.

Secondary attempts are not working. The sync button presents the 'Install driver' dialogue. Pressing Install will correctly install the driver via cmd batch, but return me to the dialogue and will not proceed.

Have rebooted Win 10, reconnected device.

**Comment by explosiveaction** [comment]
Ran this again with Debug 2.20. It worked the first time as expected. The second time it did not.

The only line in the debug logged when I press "Synchronise" is: Executing task: UploadGames

If I press Install Driver again, it installs, but does not close the dialogue to proceed and does not log anything extra.

I am fairly certain if I blow away the hakchi (or hakchi debug) installation directory, reinstall the software, and run it 'fresh', the software will work again as the full run of dump kernel > flash kernel > add games works. It's only the short run of add games that fails.

**Comment by Firebrandx** [comment]
I had this same issue. The 2nd time around, you have to use the "Flash Custom Kernel" in order to start the correct process of adding more ROMs.

**Comment by explosiveaction** [comment]
Is it correct practice to "Flash custom kernel" prior to each Sync after the initial one? I would think not. Is nobody else having this problem?

**Comment by Drakonas** [comment]
@explosiveaction if you've removed the old hakchi directory you basically removed your original kernel dump. If you do a dump of the kernel AFTER you have ever hacked the console, it is not an original kernel dump. You'll know you have a bad dump if you are getting MD5 checksum errors. You need to either find the original on your computer or find one on the internet for your region.

**Comment by Drakonas** [comment]
Closing this as the OP has not responded.

**Comment by explosiveaction** [comment]
@Drakonas I have not had a chance to re-test this with newer versions. Deleting the hakchi directory was the ONLY thing that would let me do a sync as it forced the program to re-flash the kernel. Once it had performed the sync it would go back to failing again, so had to delete the program for the next sync.

I'll get the latest version and try again soon.

**Comment by Drakonas** [comment]
@explosiveaction if you deleted the hakchi directory without moving the dump folder to the new hakchi directory, then you won't get anywhere. You need to download an unmodified kernel from the internet for your SNES. Redumping the kernel from the SNES is futile as the SNES has already been hacked at one point. You need to find a kernel ripped from a never modified SNES Classic.

**Comment by explosiveaction** [comment]
@Drakonas I don't think you are following the problem I am having. I have a backup of the original kernel, that's not the issue. The issue is the workflow.

1. Install Hakchi
2. Set up ROMS
3. Press Sync
4. Sync is treated as a 'first time' sync and does the kernel dump, flash, and roms sync successfully.
5. Add an additional ROM
6. Press Sync
7. Sync is treated as a games-only sync and fails to recognise that the SNES Mini is connected. This is reproducable after restarting the application and/or reconnecting the Mini to the computer.

WORKAROUND

1. Delete hakchi directory (backing up original kernel for safe keeping)
2. Proceed with steps 1-4 above.

Again I have not tried this since 2.20 so it all may be fixed now.

**Comment by Drakonas** [comment]
If it is doing a kernel dump upon syncing then you do not have an original dump in the folder prior to syncing or it is not named correctly. This is my point. You need your original dump you made when you first synced hakchi for the first time. (dump/kernel_snes.img) You are probably hacking already hacked dumps. Find an untouched dump on the internet please. I've fixed so many people's problems like yours and it was because they had a bad/corrupt dump.

**Comment by Drakonas** [comment]
@explosiveaction Have tried an uninstall from the Hakchi Kernel menu?

**Comment by explosiveaction** [comment]
@Drakonas it is doing a kernel dump upon synching ONLY if I delete the hackchi folder.

If I do NOT delete the hakchi folder and reinstall, it presumably does a dump.

If I do NOT delete the hakchi folder and reinstall, I cannot sync further games after the first attempt.

I've not tried uninstalling via the menu, didn't see that there. I was just deleting the installation folder and then copying the roms folder back over again.

I have my original backup of kernel_snes.img from the very first time I used the software. If that file is present in the Hakchi folder, Syncing of games will not work. If the file is NOT present, syncing of games will work.

**Comment by Drakonas** [comment]
Well if the file is not present, syncing of games will sync, but the kernel on the SNES Classic will be corrupt because it is dumping the kernel from the SNES (which was already modified) and is attempting to use that to hack and then flash back to the SNES.

**Comment by jrn0456** [comment]
I'm having this same issue. Essentially, I need to either delete the hackhi2.21f and restart, or I need to flash the original kernal and then dump it again in order to flash a custom kernal?

**Comment by Rold1** [comment]
So when can I get the original kernal that I dumped the very first time I tried to hack my snes mini I may have lost it or deleted it...I am using 2.21f...every time I try and hack it now it will dump the kernal that is on the mini but always fails to flash the new custom kernal

**Comment by jrn0456** [comment]
[kernel_snes.zip](https://github.com/ClusterM/hakchi2/files/1613217/kernel_snes.zip)

**Comment by Drakonas** [comment]
@jrn0456 do not share the kernel in this tracker please. It is illegal to share in most countries. Secondly, ask for help for this on the proper subreddit: https://www.reddit.com/r/miniSNESmods/ This is a bug tracker not a troubleshooting forum.
