### ISSUE TITLE
Boot loop

### ISSUE THREAD

**Issue by FGOD1983** [ClusterM/hakchi2#535]
I'm having issues with boot loops after playing a game which only get solved by reflashing the games. 

First it happened after playing Tetris & Dr Mario and now again after playing Bomberman 2.

Removing power and plug it back again doesn't help

Edit: Used Hakchi 2.20 final release

**Comment by K4Z1** [comment]
What powersource did you use? USB from TV?
I had the same problem today, and I temporarily fixed it by unplugging hdmi & usb and turning on power (powercycle?) for 30sec. But then I thought my TV's usb port didn't have enough "power" to run the snesc with retroarch. So I used a dedicated usb power adapter and so far it works ...just a theory.
If you (or anyone) can reproduce the issue with a dedicated power source, that would help. Then it's not a power problem.

**Comment by FGOD1983** [comment]
I had this with the USB cable to the power plug of my Chromecast, so I don't think this is power related. This seems a kernel thing to me

**Comment by FGOD1983** [comment]
the new version ends in more boot loops then ever. 

Even when i just flashed the kernel and added games and borders.

Going back to 2.20 kernel fixed it for me

**Comment by Drakonas** [comment]
Why don't you try a different power plug? The SNESC is finicky with needing a specific amount of power.

**Comment by FGOD1983** [comment]
Tried several power plugs but nothing helps and with newer versions of hachii it is getting worse

**Comment by Drakonas** [comment]
You probably have a corrupted install from updating from an old version like 2.20. Backup your saves while hakchi is installed (save state manager in hakchi menu), then uninstall hakchi from the hakchi menu, flash og kernel afterwards (if you get MD5 checksum errors then your og kernel dump is corrupted and you need to obtain an untouched one from an unmodified snes or from the internet), then after that perform a full factory reset from the SNES Classic main menu. THIS WILL ERASE ALL SAVES. Then you should go to your hakchi folder and delete all folders EXCEPT games_snes, user_mods, and dump (NEVER DELETE OR LOSE THE DUMP FOLDER). Then, download the latest 2.21f version released within the last hour, and extract it overwriting everything in your Hakchi directory. This will give you a fresh Hakchi setup, but your games are still there. Load up Hakchi, flash custom kernel, and reselect your games' checkmarks and resync your games.

**Comment by FGOD1983** [comment]
I think you were right about the corrupt install, so far no bootloops or reboots after playing several games and resetting through the controller and making save states. Thx for the tip Drakonas! Seems you were right about the corrupt hachii install!
