### ISSUE TITLE
Save state reboots

### ISSUE THREAD

**Issue by FGOD1983** [ClusterM/hakchi2#536]
I'm having troubles with loading my Battletoads save state. 

It gives reboots, but when i do a rewind of the save state and load it from the end it does work.

Edit: Used Hakchi 2.20 final release

**Comment by Drakonas** [comment]
Which Battletoads game? There are multiples. Has this been resolved with recent versions?

**Comment by FGOD1983** [comment]
It was with battletoads in battlemania, but it seems to be getting worse with new versions. The newer versions of hachii give me reboots on random times and constant boot loops

**Comment by Drakonas** [comment]
You probably have a corrupted install. A lot of users that upgraded from 2.20 to 2.21 had problems and it requires a full factory reset. Backup your saves while hakchi is installed (save state manager in hakchi menu), then uninstall hakchi from the hakchi menu, flash og kernel afterwards (if you get MD5 checksum errors then your og kernel dump is corrupted and you need to obtain an untouched one from an unmodified snes or from the internet), then after that perform a full factory reset from the SNES Classic main menu. THIS WILL ERASE ALL SAVES. Then you should go to your hakchi folder and delete all folders EXCEPT games_snes, user_mods, and dump (NEVER DELETE OR LOSE THE DUMP FOLDER). Then, download the latest 2.21f version released within the last hour, and extract it overwriting everything in your Hakchi directory. This will give you a fresh Hakchi setup, but your games are still there. Load up Hakchi, flash custom kernel, and reselect your games' checkmarks and resync your games.

**Comment by FGOD1983** [comment]
I did use fresh versions of hachii and reinstalled the original kernel several times, but without success so far, but never tried to do a factory reset.

Thx for the tip, will try that tomorrow!

**Comment by FGOD1983** [comment]
so far you seem to be right about the corrupt install! Played several games and resetted through controller combo, made save states, and everything seems to be working without reboots or boot loops. Thx a lot for the tip Drakonas!
