### ISSUE TITLE
can't dump custom kernal

### ISSUE THREAD

**Issue by joetheuseless** [ClusterM/hakchi2#537]
Ok so i can't write the custom kernel i can copy the original kernel to my computer but i get a USB error 20% into writing the custom kernel on the uploading part any ideas? i am using the official USB cable that was with the snes mini and i am using USB 2.0 as recommended 

using PAL UK Mini

https://imgur.com/a/bFlPI

**Comment by joetheuseless** [comment]
bump

**Comment by joetheuseless** [comment]
anyone?

**Comment by Drakonas** [comment]
This is a Ryzen issue on AMD's end, and is not Hakchi's fault. Please refer to #620 . Closing a duplicate.
