### ISSUE TITLE
[SNES] Update rom conversion tool

### ISSUE THREAD

**Issue by codex785** [ClusterM/hakchi2#539]
Can you please update hakchi2 .sfrom conversion tool?

i think this one, updated, is more efficient:
https://gist.github.com/anpage

i got Super Street Fighter 2 - New challengers working with this one

thanks

**Comment by DecanFrost** [comment]
how do you use this ?

**Comment by codex785** [comment]
this is a python script, you have to install pyton
a tool ha been made for this:
https://github.com/dragula96/ezMiniSnesRomConverter/releases

**Comment by barryvdh** [comment]
Which headers are causing the difference? Can you compare them?

**Comment by codex785** [comment]
don't know
i tried this one with super street fighter 2 new challengers that was not working with hakchi conversion (C7) and worked with the python script

**Comment by RaZer0k** [comment]
(First) Left: Hakchi2
(Second) Right: Python Script
Header
![image](https://user-images.githubusercontent.com/10209770/31317233-a37b8148-ac13-11e7-8393-35499a54042a.png)
![image](https://user-images.githubusercontent.com/10209770/31317239-b54a917a-ac13-11e7-9cb4-15c8e958e481.png)
Footer
![image](https://user-images.githubusercontent.com/10209770/31317188-fe6d1356-ac12-11e7-80bb-4db95b2f60d3.png)

**Comment by barryvdh** [comment]
So the python script (https://gist.github.com/anpage/4834433944a2875ee6d4cbb5786c6bf7) doesn't use a footer, just the header (and no WUP ID etc).
He also suggested that here: https://github.com/ClusterM/hakchi2/issues/461 but that didn't mention any performance improvements, just simplification.

**Comment by Darky2k1** [comment]
This also made Goof Troop work...

**Comment by barryvdh** [comment]
So perhaps just a bug with the current script? https://github.com/ClusterM/hakchi2/issues/550

**Comment by anpage** [comment]
I think the extra games working with my script as opposed to hakchi2 is probably more closely related to how I set everything I thought the emulator didn't need to 0x0, rather than it being about combining the header and footer.

**Comment by barryvdh** [comment]
According the the related issues, it did seem to work with rc4 (at least for good troop), so that would suggest neither way is better, but that the recent version just has a small mistake slipped in.

**Comment by Drakonas** [comment]
These issues have been resolved.
