### ISSUE TITLE
Feature Request: XML Cheat support and possible menu

### ISSUE THREAD

**Issue by burnjx** [ClusterM/hakchi2#54]
Hey ClusterM! Great work you are doing!

I was looking through some old files and found a cheat pack for Nestopia. I was thinking it would be great to be able to import them directly into hakchi2. Possibly even with a simple menu (like the rom list) where you can enable and disable certain cheats.

All the cheats are in XML and are formatted as such (Adventures of Rad Gravity, The (USA).xml):

`<?xml version="1.0" encoding="UTF-8"?>
-<cheats version="1.0">
-<cheat enabled="0">
<genie>SUTTXU</genie>
<description>Infinite health</description>
</cheat>
</cheats>`

Here's a link to the pack in case you are interested: [Cheat Pack](https://www.mediafire.com/?eaq1a5cpkk9py22)

While I am no good working with code myself, it doesn't appear this would require much work to implement. Of course I could be totally wrong in that assumption. Anyways, thanks for reading and keep up the great work!

**Comment by nappymike** [comment]
I think that would be a awesome update for 2.12

**Comment by burnjx** [comment]
Looks like Nhakin added support for this in a recent pull request! Very excited for Cluster to merge the code!

**Comment by burnjx** [comment]
This has been added as of revision 134 so I'll be closing this. Amazing work Cluster and Nhakin! This is awesome!
