### ISSUE TITLE
Terranigma not working

### ISSUE THREAD

**Issue by miguel92** [ClusterM/hakchi2#540]
I'm using a spanish PAL version patched to NTSC. So when I start the game on the SNES mini it seems to work, but it has no sound and then it freezes when I start a new game.

**Comment by shaman78** [comment]
read #481 , #490 
http://en.evilgames.eu/snes-pal-to-ntsc.html
Terranigma | HiROM + region lock

**Comment by emufrance** [comment]
Not working correctly even with ntsc+lock patches. Sounds issues (glitches/nosound)

**Comment by miguel92** [comment]
So there is no way to play it right? I have tested Illusion of Time and it has the same issues. I guess there is a problem with Quintet games :( .Thanks for the reply

**Comment by emufrance** [comment]
Works with RetroArch

**Comment by miguel92** [comment]
How do i install retroarch? Can i use it only for Terranigma or it applies for all games?

**Comment by shaman78** [comment]
you can use it only for terranigma

**Comment by miguel92** [comment]
I have installed retroarch and configured it. It works perfectly now. Thanks

**Comment by waroogames** [comment]
miguel92 can you help me to install retroarch and configure it? please :(

**Comment by miguel92** [comment]
Sure. Download retroarch from here [https://github.com/ClusterM/retroarch-clover/releases](url) and drag the zip to hakchi2 app, then choose what modules you want to install. I just selected "retroarch" and "snesx2010". It will request you to flash the new custom kernel to your SNES mini. When it ends flashing you just need your game and insert "--retroarch" and the end of the command line section. Once you are playing the game you can enter the menu pressing select and start, and configure what you want. I hope it helps you!

**Comment by hallomichael** [comment]
hi, i tried it as described here, i installed retroarch in hakchi, i headered my terranigma rom with tush and then i applied the hirom ntsc patch and regionlock patch with lunar ips, and then i loaded the game in hakchi and added the  --retroarch in the command line, but when i start the game theres just a black screen and i can enter retroarch but dont know what to do there, i tried it with the germany and europe version of terranigma but nothing works, please help me ^^

**Comment by miguel92** [comment]
You don't need to patch the game for running it on retroarch. Are you sure you have retroarch installed? Test with other game adding "--retroarch" and press select and start inside the game to see if you have it installed. If it doesn't revise install extra modules.

**Comment by hallomichael** [comment]
Retroarch with the snes module is installed, when the Black screen appears, i can press Start+select and the whole menu with options and all pops up.
But i will try if it works with the unpatched rom
edit: well with the unpatched rom it worked perfectly fine, thank you, now my snes is perfect ^^

**Comment by Igna21** [comment]
I got Terranigma to work on the snes classic mini (using retroarch), but I want the text to be normal and not wide.  I tried patching the rom using lunar ips with the fixed text hack (8x16 font), and that seems to screw up the rom when I try to play on the snes mini.  A black screen shows up. 
Has anybody gotten it to work on the snes mini with the fixed text?  If so, please advise how, because I've ran out of ideas. :(  Thanks in advance.

**Comment by Drakonas** [comment]
There have been developments on this allowing it to work. https://www.reddit.com/r/miniSNESmods/comments/78pu0f/terranigma_playable_with_canoe_maybe_more/dowerw8/ Closing.
