### ISSUE TITLE
SNES console type for European users

### ISSUE THREAD

**Issue by Happy-Ferret** [ClusterM/hakchi2#541]
Curious.

Which console type are users of the European SNES Mini supposed to use?
Is the firmware identical with the SNES Mini Classic (US Edition) or the Super Famicom?

On a side note, will installing hakchi2 delete existing save games?

**Comment by gslance** [comment]
It's just 'SNES Mini' for Europeans.

No, savegames will not be deleted.

**Comment by Happy-Ferret** [comment]
Alright. So I'd pick the US model then (since there's only two to choose from. SNES Classic Mini and Super Famicom)?

**Comment by Drakonas** [comment]
The SNES Minis for Europe and America use mostly the same software build. They are both made to work with the US library of games, and as such won't work well with European roms. You usually need Retroarch for those.
