### ISSUE TITLE
Feature Request: Filter Games list by Console

### ISSUE THREAD

**Issue by FoyzM** [ClusterM/hakchi2#543]
Would help keep it clean for those that don't want to mix games on the different consoles. :)

**Comment by gingerbeardman** [comment]
Folders?

**Comment by Drakonas** [comment]
This is already possible by enabling the custom folders option in the Hakchi menu and sorting games manually.

**Comment by FoyzM** [comment]
I wasn't referring to the Kernel output, I was referring to the management console, the ability to better organise the games would be very helpful PRIOR to building the kernel for upload.

Hope this makes sense.

**Comment by Drakonas** [comment]
See my response on your new issue #1007
