### ISSUE TITLE
SNES Mini Audio Skipping/Choppy

### ISSUE THREAD

**Issue by poolfloat** [ClusterM/hakchi2#545]
The music played while in the SNES Mini menu is choppy and cuts out frequently. This behavior continues into games with the native emulator, and retroarch. I did remove the original 21 games and replace them with ROM copies of them, but it happens with any game/system I play.

Using standard HDMI out to TV, no external sound system or speakers. NES Mini with the same HDMI cord does not have the issue.

Has anyone else experienced this?

**Comment by tecteun** [comment]
I'm guessing this is due to the cpu leak in https://github.com/ClusterM/hakchi2/issues/496 which is solved, but isn't released yet

**Comment by Jafrom** [comment]
Got the same issue though no chopping/cutting during the menu or 21 original games..

**Comment by poolfloat** [comment]
Thanks, I will try that later. I see the web installer has been updated, but I'm old fashioned and used the portable version that has not been yet.

**Comment by miner19** [comment]
Are you saying the web version was updated but the portable wasnt?

**Comment by daranus** [comment]
I can confirm that this bug exists and that I have found the "cause" and for now "solution".

Europe/certain Country roms dont seem to work properly/have sound issues. USA versions seem to work every time, even when the europe/german version fails! Tested with versions of Aladin, DKC2 and more. (another thing I noticed is that hakchi always read the developer right for usa roms and that there is a high chance that if dev states unknown, the sound issues will be present!)
Hope that will help somebody for now :D

**Comment by Drakonas** [comment]
The European and American SNES Classic's canoe was built for the USA library of games only. Most European roms will have issues with Canoe. Use Retroarch if you must have European roms.

**Comment by poolfloat** [comment]
@Drakonas I was using Retroarch and having the sound issue. I actually added a global string to run all games in Retroarch.

**Comment by Drakonas** [comment]
Have you updated to 2.21f after uninstalling hakchi, flashing og kernel (making sure to not get md5 checksum errors) and then installing the custom kernel? Also how much free space is left on your SNES Classic? @NotATreoFan

**Comment by poolfloat** [comment]
@Drakonas I have not updated the kernel since the original release. I will do that tomorrow and check to see if it is improved.

**Comment by Drakonas** [comment]
@NotATreoFan then you'll need to backup your saves, uninstall hakchi, flash og kernel, then perform a factory reset with the SNES Classic menu (WILL ERASE ALL SAVES), and then flash custom kernel. You need to do the factory reset else you will have broken files and leftover junk from the original version which had quite a few problems. Otherwise, you will have even more issues.

**Comment by poolfloat** [comment]
@Drakonas Looks good after the complete factory reset. Loaded up a handful of games last night and didn't experience any of the audio skipping or choppiness.

**Comment by Drakonas** [comment]
Cool @NotATreoFan please message here if the issue arises again. Usually the factory reset helps in dire cases like this.
