### ISSUE TITLE
[SNES/NES] Thumbnail list scrolling workaround

### ISSUE THREAD

**Issue by codex785** [ClusterM/hakchi2#547]
The idea is:
By default, the Arrow is moving and diseapearing when reaching a game tumbnail that does not appear on the screen
my proposal is to make the arrow moving 3 or 5 thumbnails to the left and 3 or 5 thumbnails to the right (or static if there is any coding problem) and make the thumbnail list scroll (right or left)
is this something that can be done?

**Comment by Drakonas** [comment]
You have too many games in one folder. 45 is the limit if you want all the thumbnails on screen. This is a limit of the Nintendo-coded UI, and cannot be fixed by Hakchi.
