### ISSUE TITLE
c7 Fehler

### ISSUE THREAD

**Issue by erwieder** [ClusterM/hakchi2#548]
I have added 2 games and get C7 at game start

**Comment by dewokkel** [comment]
What games did you add?

**Comment by erwieder** [comment]
Secret of Mana (G).smc (Deutsch)
Super Mario World (V1.1) (E) [!].smc (Deutsch)

**Comment by dewokkel** [comment]
You probably want to use NTSC roms. I've haven't had any luck using PAL games yet.

**Comment by erwieder** [comment]
just seen, occurs only in German games on the error

**Comment by Linkinworm** [comment]
I also have this issue, but it's only when I use compressed roms. any and all roms doesn't make a difference, they work perfect if i uncheck compress and resync the games

**Comment by erwieder** [comment]
Now use retroarch with emulator.
so now all the roms go

**Comment by Drakonas** [comment]
Games other than USA releases mostly fail with Canoe, as canoe was built with the USA library in mind for both EUR and USA SNES Classics, and the Japanese library for the JPN Super Famicom Mini. Use Retroarch if you want to run German games.
