### ISSUE TITLE
Goof troop fix

### ISSUE THREAD

**Issue by dewokkel** [ClusterM/hakchi2#549]
Do you guys think there Will be a fix for certain games just like with the nes mini? I’ve got all my favorite games working now except for Goof Troop. I’m not sure if I want to use retroarch just for this one game. 
Anyway, thanks for all the hard work. Much appreciated!

**Comment by deelowe** [comment]
Duplicate of:

#550

**Comment by dewokkel** [comment]
Yeah sorry, we created it at the same time. I'll close it now.
