### ISSUE TITLE
States saved NES Mini to the PC?

### ISSUE THREAD

**Issue by NaikiTurincondeliphone** [ClusterM/hakchi2#55]
We will be able to save, in a future, the saved states of the games of the NES Mini to the PC?

-------------------------------------------------------------------------------------------------------

Mi pregunta es la siguiente, ¿podremos guardar, en un futuro, los estados guardados de las partidas de la NES Mini al PC?

**Comment by warlockv2** [comment]
I would like to know to, would be nice to be able to update the hack on the mini, and not lose save data

**Comment by baconcow** [comment]
You do not lose save data when you update to another version of hakchi2 nor when you put more games on the NESCE with hakchi2. I believe, the only instance that will cause you to lose your saves is when you reset to factory defaults, within the NESCE, and when you flash the original kernel onto the NESCE.

**Comment by warlockv2** [comment]
thats odd, because i added a few games and when i went back, all my saves were totally gone.  il test this again

**Comment by baconcow** [comment]
I have added games half a dozen times and never lost a save. I've even removed games with saves and then added them again, only for their original saves to remain.

**Comment by NaikiTurincondeliphone** [comment]
But I want to save them on the pc in case I change NES someday, I have 3.

**Comment by hpd4cl** [comment]
I would like to be able to download my save states so I can hack them.  There are some things Game Genie can't do.

**Comment by ClusterM** [comment]
I found a way to do it.

**Comment by ajmi982** [comment]
Does this mean the reverse too?! Pull save states from RetroArch on PC and upload to min?!

**Comment by ClusterM** [comment]
Hi.

Sorry for not so fast answer.
I released clovershell tool, you can transfer saves using it.
I planned to integrate it into hakchi2 but later.

February 24, 2017 3:40 PM, "ajmi982"  wrote:
Does this mean the reverse too?! Pull save states from RetroArch on PC and upload to min?!

Sent from my iPhone. Please pardon any spelling or grammar mistakes.

**Comment by NaikiTurincondeliphone** [comment]
Feature available in version 2.15d, thanks!!
