### ISSUE TITLE
Games Compatible on earlier builds don’t work on Newer official build

### ISSUE THREAD

**Issue by jawmuncher** [ClusterM/hakchi2#550]
So after messing with files for awhile. It seems that the current official release is “corrupting” some games. For my testing purposes Goof Troop & Panel de Pon specifically. However both games work just fine if transferred hackchi2_0.20.rc4_debug instead of the latest version. 

If more detailed info is needed just let me know what I need to provide.

**Comment by dewokkel** [comment]
Ah, I just created a topic on goof troop. So you’re saying that if I use the debug version this game will work?

**Comment by jawmuncher** [comment]
Yes. If you use the earlier version of Hakchi listed they’ll work. To be on the safe side I flashed the original kernel before going to the older version and then used the older version to install the custom flash and add those games.

**Comment by dewokkel** [comment]
Thanks! Maybe I’ll just need to wait for a newer version. Goof troop for me is the only one that doesn’t work. All my other games run fine.

Still, thanks for the tip :)

**Comment by FierceLog** [comment]
The audio isn't playing in William's Arcade Greatist Hits.  

There was sound in Joust before, AFAIK.

**Comment by barryvdh** [comment]
If you're sure it worked with rc4, these are the current changes: https://github.com/ClusterM/hakchi2/compare/c7fc8c5989cd3ae6bb2bdc93c9978fb53fd55829...1eb07e299750fdfa2d840d444adda4784f4a3f58#diff-d9dc6bc9b59d50a803132c7eaff90abe

Seems to be some changes with detection in hirom/lorom, not much else, right?

**Comment by barryvdh** [comment]
So according to this thread: https://www.reddit.com/r/miniSNESmods/comments/756zg4/goof_troop_fix/
It mentions the 15 should be 14. According to https://gist.github.com/anpage/c1085055db0242ea3c7558dab56712a5 that is indeed the HiROM/LoROM flag, which also suggest the changes is with the detection of HiRom/LoRom in SnesGame.cs

https://github.com/ClusterM/hakchi2/blob/1eb07e299750fdfa2d840d444adda4784f4a3f58/Apps/SnesGame.cs#L119-L160

**Comment by barryvdh** [comment]
So should be fixed with https://github.com/ClusterM/hakchi2/commit/d976ea7e4279db18c52feb5c0007ec1459827be9#diff-d9dc6bc9b59d50a803132c7eaff90abe I guess :)

**Comment by dewokkel** [comment]
I’m sorry Barry, I’m not really sure what you mean when you say “should be fixed with”. I’m not that tech savvy ;)

**Comment by barryvdh** [comment]
That clusterm pushed a change to fix it, should be in the next release.

**Comment by dewokkel** [comment]
Oh right, that’s what that code means. Sorry :)
