### ISSUE TITLE
Can't install the driver on XP

### ISSUE THREAD

**Issue by BuscaLegnate** [ClusterM/hakchi2#551]
I'm using Windows XP and I can't install the driver.

**Comment by zimmertr** [comment]
Why in the world are you using Windows XP?

**Comment by BuscaLegnate** [comment]
I have an old PC and I don't use it very much.

**Comment by Jamieasy** [comment]
Wow windows xp??!! That belongs in a museum

**Comment by ClusterM** [comment]
Use "Zadig" tool to install driver on XP: http://zadig.akeo.ie/
