### ISSUE TITLE
[NES] remove_thumbnails mod uses up all space available

### ISSUE THREAD

**Issue by deelowe** [ClusterM/hakchi2#552]
Seems to happen every time I try to enable the mod. This is on 2.20.14. To reproduce simply do the following:

1. Use a stock nes mini
2. Flash custom kernel only and allow it to restart
3. Add games or leave with default games (happens either way)
4. Go to Modules --> Install Extra Modules
5. Choose remove_thumbnails
6. Click OK
7. Power the NES per the instructions
8. Wait... The script should finish and the system will appear to hang (black screen)
9. Remove power from NES due to it being hung and then plug back in and power on

The NES will appear to boot fine, but the remove_thumnails mod will not be installed. All available space on the device will be used up. If you check /var using a tool such a du, you'll find /var/lib has a repeating recursive directory structure that appears to go on forever starting with /var/lib/hakchi.

This seems completely repeatable. Perhaps it's a bug with trying to do this before additional games have been added to the system?

**Comment by deelowe** [comment]
Here's the issue:

```
root@CLOVER:~# du -csh /var/lib/*
388.0K  /var/lib/clover
20.0K   /var/lib/foxconn
363.5M  /var/lib/hakchi
16.0K   /var/lib/lost+found
4.0K    /var/lib/profiling-data
```

```
root@CLOVER:~# ls /var/lib/hakchi/rootfs/newroot/var/lib/hakchi/rootfs/newroot/var/lib/hakchi/rootfs/newroot/var/lib/hakchi/rootfs/newroot/var/lib/hakchi/rootfs/newroot/var/lib/hakchi/rootfs/newroot/var/lib/hakchi/rootfs/
bin      etc      lib      newroot  usr
```

**Comment by deelowe** [comment]
When this issue happens, the only way to fix it from what I can tell is to uninstall hakchi, reinstall the custom kernel and re-upload all of the games.

**Comment by ClusterM** [comment]
Fixed. Thank you very much!
Need more testing on both systems...
