### ISSUE TITLE
Retroarch issues with savefiles/exit

### ISSUE THREAD

**Issue by OliverUlm** [ClusterM/hakchi2#553]
I'm playing Secret of Evermore through Retroarch as it's missing some background audio on Canoe. However Retroarch seems to crash quite often upon quitting the game (returning to the menu, shutting the console off - basically just reacting with a black screen). This also results in the SaveRAM not being stored, which means that my saves get lost.

I had been using 2.0.20 rc4 before and Retroarch did crash a lot for me then. Before installing 2.0.20.15 I did an Uninstall through the Kernel Menu and also went back to the Stock Kernel. Then I installed the Custom Kernel and Retroarch + Snes9x Core.

Does Retroarch produce any logfiles that I could get through FTP to help analysis of the issue along?

**Comment by OliverUlm** [comment]
I kept playing around with this and wanted to add some more information:

After I disabled Auto Load State and Auto Save State (which are on by default) the situation has improved quite a bit. However I still see crashes when going back to the menu (instead of the Emulator image freezing until the menu shows up the screen turns black until the menu comes up) and if that happens the SaveRAM will again not be stored.

I do have autosaving of the SaveRAM configured with the default value of 10 seconds so it should store that even during gameplay, no idea why it's not happening.

**Comment by ANTHONYG84** [comment]
I think I am having the same issue as you. When I play a gameboy game and I save it then press the reset button it gives me a C7 error that results in my in game save file to be wiped.

**Comment by ANTHONYG84** [comment]
Did you ever find a solution?

**Comment by OliverUlm** [comment]
Not yet, however the whole SNES mini Mod is so new that I fully expect it to take some time until these things get fixed. There's still lots of things to do and I'm sure these kinks will get worked out eventually.

**Comment by OliverUlm** [comment]
I now managed on two occasions to see the same behavior when saving state manually from RetroArch's menu - so it looks as if the main issue is indeed somehow connected to writing the state to storage.

**Comment by K4Z1** [comment]
I have the same issue: playing PAL games or probably anything with RetroArch, then going to the Mini Home Menu and make a Suspend Point. After that, when I load a different game, or change the folder, or even continue the same game (or same suspend point), it crashes.
It looks like it boots up for a second and crashes again.
Then I can only disconnect power for ~10-30 seconds (maybe with powerswitch on?)

Edit2: Changing the USB power source didn't help.
I had the problem in Super Street Fighter II, when I wanted to make a save in the home menu... hit reset, (I saw for a second that the current save had the same preview image as my already old save file, but I just wanted to save quickly...), overwrite the old save, and the preview image was the same of course, and the savestate was still the old one too. So I basically lost my current savestate when exiting retroarch and going to the home menu...

I want to enable normal quicksave in retroarch if that's possible... (they're deleted when I exit retroarch).

**Comment by OliverUlm** [comment]
Ok, so now I'm on hakchi 2.0.21.32 with Retroarch 0.9c and then screen still goes black when I try to exit Retroarch (with SNES9x 2010 core) after playing for some time. That also always means that the in game saves and savestates created in the meantime get lost.

I believe that the screen going black means that the system is crashing and rebooting back to the menu instead of exiting the normal way. The curious question is however: why aren't the savestates that have already been created preserved?

**Comment by OliverUlm** [comment]
I think I found some clue as to what's happening while reading through the Mod Creation guide. The data is stored on a RAMdisk and presumably copied back at some point. So if the system crashes at some point (while creating a savestate or while switching back to the menu) nothing is copied back. That would explain the behavior (given that Retroarch does auto save the SaveRAM).

So there would be two possible solutions:

a) Keep Retroarch from crashing in some of those situations (preferably)
b) Change the mount scripts in such a way that the save states don't go to the RAMdisk but rather to memory directly.

I could be wrong though.

**Comment by Drakonas** [comment]
This is a limitation of the Canoe emulator, and does not belong in a Hakchi issue tracker. Closing. I recommend using Retroarch for all the Seiken Densetsu games, especially if you use patches.
