### ISSUE TITLE
c8 error when turning system off

### ISSUE THREAD

**Issue by nekonall** [ClusterM/hakchi2#558]
title says it .. system wont cut off after error  unless i hold reset and flick the switch on/off again

**Comment by Darky2k1** [comment]
how many games do you have per folder / on your home screen?

**Comment by nekonall** [comment]
was trying 67 brought it down to 60 and it works fine... odd

**Comment by ghost** [comment]
63 per folder/page seems to be the limit. Anything above 63 will probably give you a C8 error while shutting the system down.

I don't know if this is much of a bug in Hakchi, but rather a limitation of the system itself.
