### ISSUE TITLE
Nes mini does not work after this update for me

### ISSUE THREAD

**Issue by Shreddiebean** [ClusterM/hakchi2#559]
As soon as the new Hakchi 2.2 was out, I could not wait to get the new software, so I got it, and it works on my SNES mini with no issues (other than game compatibility, but that is to be expected). However when I got my NES mini going (after I changed the mode from SNES Classic Mini to NES Classic Mini of course), it will not play any game now, even after I add Retroarch-Clover. I select a game, it fades to black for 5 seconds and returns to the main menu. I don't know what to do, even if i try to flash the system to the original, it does not work.

**Comment by Darky2k1** [comment]
For now I recommend using an old version of Hakchi
