### ISSUE TITLE
Removing  individual games from the orginal 30

### ISSUE THREAD

**Issue by nicholastennis88** [ClusterM/hakchi2#56]
I know it is possible to deselect the original 30. But I also saw that you can remove games individually. Has anyone done this / has anyone had any problems?

**Comment by baconcow** [comment]
When I added games in 2.09, I hid 10 of the 30 games. There were no issues. The only side effect being that you will not get the pixel art from that game in the screensaver that comes up.

**Comment by T3rry12** [comment]
when you choose the original 30 it has a selection box for the individual games ont he right panel.
