### ISSUE TITLE
Add more games?

### ISSUE THREAD

**Issue by Tyler-0220** [ClusterM/hakchi2#560]
When I click add more games there are no roms there to transfer to the snes classic.  Do you have to individually download them onto your computer?

**Comment by Arakon** [comment]
Uh.. did you expect them to magically appear?

**Comment by Tyler-0220** [comment]
Uh... I expected one of the youtube videos to show how they have the entire snes library on there computer?

**Comment by warlockv2** [comment]
well thats illegal.  lol,  find the roms yourself

**Comment by DecanFrost** [comment]
I'm sorry but if the user is not savvy enough to use a simple google search to download roms they should not be messing with hakchi2

**Comment by DecanFrost** [comment]
I'm sorry but if the user is not savvy enough to use a simple google search to download roms they should not be messing with hakchi2

**Comment by DecanFrost** [comment]
Sorry about the duplicate mags

**Comment by miner19** [comment]
Agreed Decan
