### ISSUE TITLE
SNES - Question Free Space

### ISSUE THREAD

**Issue by MasterPlatinum** [ClusterM/hakchi2#562]
Hello,
I have a quick question.
Is there already a reserved space on the console for the replay fonction or it use free space that we use when adding new games?? The console record real time playing for the replay fonction so maybe it could make errors or problems  if we saturate all the free space..

Is it good to keep some space on it like not saturate all the memory with new games for that fonction??

Thanks and sorry for my English..

**Comment by warlockv2** [comment]
I already have this issue open.

**Comment by ClusterM** [comment]
There 10MBytes reserved. Seems like I should increase it.

**Comment by zimmertr** [comment]
@ClusterM any ideas for how much space to leave free in addition to the 10mb of reserved?

**Comment by K4Z1** [comment]
In hakchi2 it showed that I used ~120/300 MB first. Then I played a bit, had some crashes, uninstalled, reinstalled, synchronized, and I have only ~120/~200MB. reinstalled again, and it's 120/250MB now. It's still enough for my games, but it's weird. I don't use rewind at all, so if that could be disabled (optional) and shrink the savefiles, that would be awesome!^^

**Comment by 630216-29-2400** [comment]
Is there any way to disable the "rewind" feature?

It's a nice feature to have on the stock SNES Mini Classic but there's obviously no concern for space there and I'd much rather just game saves without the rewind option to save space. I'm not sure if it would be possible to disable it via a switch in hakchi though?

**Comment by Drakonas** [comment]
@B9KnM8UqQ2W2Vwk7uvZ7 please create a separate issue for that feature request if you wish. As for the original OP's question, this has been addressed. It uses the main storage for rewinds.
