### ISSUE TITLE
HACKCHI DOESNT RECOGNICE SNES MINI

### ISSUE THREAD

**Issue by andpal21** [ClusterM/hakchi2#564]
Hello,

so I downloaded the new hackchi 2.20. Connected my snes classic, wanted to dump my kernel and it just stays there. I have followed the instruction but it just stays on without the light. Is there anything i need to do before I dump the kernel?

Please, let me know.

**Comment by MasterPlatinum** [comment]
Try to do not use the stock USB cable that Nintendo gives in the box.

I had a pain to make my SNES be recognized by my computer. Even driver installed. I had an idea to use an different one from my digital camera and wtf, it works.

**Comment by andpal21** [comment]
Thank you! I will try with another usb cable.
One more thing, where can I download the driver you talk about?

**Comment by andpal21** [comment]
Should I install the one that works with the NES or should I install one that Windows recomends?

**Comment by MasterPlatinum** [comment]
All driver neeed are in the zip file.. but just click on the button in the window when your synchronize your snes..

**Comment by andpal21** [comment]
It doesnt recognize it :(

Not my nes or snes

**Comment by ClusterM** [comment]
Please check FAQ.

**Comment by andpal21** [comment]
Thank you all!
I changed the cable and installed the driver via Zadig. It is working now.

**Comment by MasterPlatinum** [comment]
Great!

I think Nintendo put something or the original USB cable is for power only or they stop some data to prevent some info to reach the PC.

I had a pain to get my friend console Nes classic to be recognized by his Pc

I had the same damn problem with my Snes Classic. I was not able to connect the console to my PC. I had remembered to use another one cable that Nintendo put in the box and it work the first time!!

**Comment by randukes** [comment]
I NEED HELP!!! I accidentally used the old Hackchi and now it wont read my SNES as a SNES. I cant find the dump folder and I already upgraded the Hackchi. Now it wont turn on. What can I do to reverse this and have it read as a SNES? thank you!

**Comment by panic2099** [comment]
I am using the hackchi version 2.3.0 I could add moire games fine.i tried to add more cores and nothing happened.now when I try to do anything a error code pops up telling  me it failed to creat file usb driver installlerx8 6exe 9[#00000020 the process cannot access the file because it is bveing used by another process... can somebody please tell me how to fix it..thankyou
