### ISSUE TITLE
Nosferatu boss glitch

### ISSUE THREAD

**Issue by xam925** [ClusterM/hakchi2#565]
Game has some minor glitch around levels,but heavier glitch when you reach 1st boss.

Tried with snes mini pal version, nosferatu usa version (smc file)

Dunno if it can be useful for improve, thanks as always for your efforts

**Comment by Drakonas** [comment]
This is a bug with Nintendo's Canoe, and not Hakchi. Nothing can be done. Use Retroarch for problem games.
