### ISSUE TITLE
Random - When turning on the SNES Mini - Can't move

### ISSUE THREAD

**Issue by Darky2k1** [ClusterM/hakchi2#566]
When turning on the SNES Mini randomly it boots up to the menu and plays sound but can't move the cursor (This is with a standard wired controller).

Turning it off and turning it back on fixes it

this has happened 3 different times

**Comment by shaman78** [comment]
maybe #555

**Comment by Linkinworm** [comment]
I have a similar issue after game resync, sometimes, can't pin it down to anything but it was from a full game sync to a full game sync in a short time after editing a couple bits of metadate

**Comment by gnadenlos** [comment]
This happens if you removed or moved the game you were using last time.
