### ISSUE TITLE
Snes Games not working

### ISSUE THREAD

**Issue by dave11674** [ClusterM/hakchi2#567]
Hi guys after adding several snes games they wont run

When i add roms and quickly do a google boxart search
Then upload new games i just get a black screen for a few seconds then back to main menu

Any ideas

**Comment by Darky2k1** [comment]
do you use folders?

**Comment by shaman78** [comment]
Maybe Pal games ? #490

**Comment by dave11674** [comment]
Im running us games
Ive got pal and us games on the system at present
Before adding these

Folder options i didnt change but will try the top option i think it is
Thanks for the fast replies guys

Dave

**Comment by dave11674** [comment]
Ps
All the new roms were USA roms

Dave

**Comment by STZ-Mech** [comment]
The only two games I have so far that don't work are:
1. Illusion of gaia (Black screen when you press start at main screen); and
2. Robotrek (Black screen, won't load).

So far everything else I have seems to be working.

**Comment by Linkinworm** [comment]
double check the .desktop file to make sure you did everything correctly? i know i had several issues from missing one naming ID and then the game number ID changing back to 777 for some reason and not what i needed it set to.

**Comment by RaZer0k** [comment]
try using phyton sfc2sfrom.py converter and replace the .sfrom file with the generated one from sfc2sfrom.
this help me with some games.

**Comment by dave11674** [comment]
Thanks guys
So before selecting add games convert to sfrom then add game ?
I think i missed the desktop files on them lol
Oooops
I usually start my game id from 700 and go up one with each game

Will sort the desktop files out first.

With the pre release hakchi2 and doing everything manually they worked ok
But that way i did do each desktop file manually each game.

What tool to compres to .7z as id like the compression
Tho on a side note i did not compress my roms i tried the other day
I was using GG tool too to add game genie codes to the roms
All worked ok :)

Dave
