### ISSUE TITLE
SNES mini classic: connected to lenovo laptop and nothing happens

### ISSUE THREAD

**Issue by Druqsr** [ClusterM/hakchi2#568]
I have it connected to the Lenovo laptop with windows 10
I see it appearing as CLV-S-SNPY
it says it's not up to date, so i update it, but it can't find any drivers
and that's where it ends.. no clue what to 
nothing happens

**Comment by shaman78** [comment]
try shut down snes mini
hold reset and start again

**Comment by Druqsr** [comment]
no result
the only difference is when holding reset button and startingup, the device appears as 'unknown'
but still nothing happens

What is supposed to happen anyway? I double click the device and it starts? 
Does it happen automatically ?
Do i press something?

About resetting, do I hold it down while starting it up? Do I reset it for 10 seconds ?

Sorry i'm a newbie

**Comment by Drakonas** [comment]
@Druqsr did you ever press the "install drivers" button from the hakchi window that popped up before the flash.

**Comment by Drakonas** [comment]
Closing this issue as the OP never responded.
