### ISSUE TITLE
Feature Request: Bulk import images from local storage instead of Google

### ISSUE THREAD

**Issue by esmith13** [ClusterM/hakchi2#57]
Would love ability to import images for games in bulk from local HDD by way of name matching.
In other words, when importing rom "game23.nes" if the file "game23.png" or "game23.jpg" exists as well, pull that in as game box image automatically. This would allow personalized images or stock image download bundles to be used efficiently when importing hundreds of roms thanks to new folder/page option in v2.11.

**Comment by baconcow** [comment]
This is already part of 2.11.

**Comment by esmith13** [comment]
How to I use this undocumented feature? Are you confusing it with the google download option from file menu? I am referring to supplying my own images.

**Comment by baconcow** [comment]
In a folder, you would have:

Battletoads (Japan).jpg
Battletoads (Japan).nes

Adding Battletoads (Japan).nes would automatically add the Battletoads (Japan).jpg in the same folder. If you add 200 games at once, in this fashion, it will add all 200 images to their respective games. I am not confusing it with Google downloading. This uses your own images. You need to compile the current GitHub repository (with Visual Studio) or wait for the 2.12 update that will include this commit (a commit is code that has been added to the repository, but in this case, it has not yet been added to a published release).

**Comment by esmith13** [comment]
I edited my comment to reflect your updated comment. Thanks for the info!
