### ISSUE TITLE
SNES Mini won't start after flash. Or Start and Stop immediatly.

### ISSUE THREAD

**Issue by GenralTOW** [ClusterM/hakchi2#570]
Hi,

I used hakchi2 2.20 (Official release) and hakchi 2.20 RC4.
I downloaded the little fix "remote-exec" too.
I tried changing USB port or Cable.

It worked with hakchi 2.20 RC4 yesterday, but since now when I try to sync any game with the official release, sometime the SNES will stop working. 
I will have to turn it "Off", remove/reconnect cable and turn it "On" again.

And she will go "On" and "Off" immediatly. Sometime It boots correctly and if I turn system "Off" after playing and try to turn it "On" again, "grey screen" or "Off".

Tried to use hakchi 2.20 RC4 to see if it works like yesterday, but same issue now.

Hakchi is still able to flash original kernel and my system works correctly. But impossible for me to add games since it's not stable.

Any idea about the problem ?

**Comment by hoderer** [comment]
I would say: Use the current version (2.0.20.15) and flash stock kernel and then custom kernel again. There was a power leak, which means that the device consumpted more power with custom kernel than with the stock one. Other solution: Change your power supply.

**Comment by GenralTOW** [comment]
Hi,

I'm now using 2.0.20.15 and it seems to be better. But I'm still having random issues :
SNES don't recognize my controller (Need to reboot and it works)
SNES start and stop sometimes.
C7 errors.

I did like everytime. Uninstalled, back to stock kernel, custom kernel with 2.0.20.15 etc... I would like to add that I'm not using Retroarch.

I know that ClusterM will update hakchi2. Posting this was only to help going forward. :)

**Comment by GenralTOW** [comment]
Update : It's very better now.

I close this issue ! :)
