### ISSUE TITLE
Can't install driver 2.20 Win 10

### ISSUE THREAD

**Issue by Cake-sensei** [ClusterM/hakchi2#571]
Hello,

I got the last version Hakchi2 (2.20) and i'm using Windows 10.
I have folowed many tutorials but i have troubles at the moment where I have to install the driver. 
My computer detect the hardware (as unknow periph).

I have do the reset then power on method (with no light) and for the last step (install driver) I got a screen in the debug version who says "Found USB device : "Unknow device#1 (1F3A EFEB)
Installing wdi driver with (nesmini.inf) at <usb_driver>
Press enter to exit and then nothing more happens ...

The left windows show only this message again and again (see the screenshot bellow).

I have tried on USB 3.0 AND 2.0 ports, 2 different computers, with another cable (DSLR)... don't know what to do.

Does anybody get this issue too ?

Sorry for my bad english !

![desktop screenshot 2017 10 08 - 21 08 27 37](https://user-images.githubusercontent.com/32618679/31320146-d61846b6-ac6f-11e7-83c2-37732d3f1509.png)

**Comment by silveraegis39** [comment]
happens to me too, i click install drivers, the window pops up, shows the same text then tells me to press enter to exit the installer... but nothing else happens. i tried uninstalling the unknown device, tried installing manually the drivers but it says there is an error trying to install Nes mini driver... i don't know what to do anymore

**Comment by Henke83** [comment]
Bump! I have the exact same problem and have tried every USB port available. I'm using the european version of the Snes Classic.

Edit: After installing Zadig it seems to support the function to dump the kernel. (http://zadig.akeo.ie/)

**Comment by Cake-sensei** [comment]
The method of Henke83 has worked for me ! Thanks to you !

Plug the SNES mini with usb cable, then push reset & start method (no led), your computer should show the SNES as unknow periph.
In zadig choose install WCID driver (win usb 6.1 xxxxx). That's all.
Flash kernel and Haktchi works perfectly now ! (i have the european version too but i don't know if that makes any difference ?).

**Comment by silveraegis39** [comment]
nope not working for me, says driver installed successfully in zadig but still doesnt work in hakchi, i cant install the nesmini.inf driver

**Comment by silveraegis39** [comment]
Driver Installation: SUCCESS
1 device found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1F3A&PID_EFE8&REV_02;3
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_FF&SubClass_FF&Prot_FF
libwdi:debug [wdi_create_list] Driverless USB device (3): USB\VID_1F3A&PID_EFE8\5&397C2BE2&0&7
libwdi:debug [wdi_create_list] could not read device description for 3: [#0000000D] The data is invalid.
libwdi:debug [wdi_create_list] Device description: 'Unknown Device #1'



those are the last lines of the log from zadig. it says its installed but it cannot read it. is that why its not working?

**Comment by silveraegis39** [comment]
wow! i somehow managed to make it work! its been 40 minutes of me deleting and reinstalling the drivers... and somehow i uninstalled the device AND the driver software, and when i plugged it in again, instead of showing in unknown device, it went into the Universal Serial Bus devices... didnt even have to install the drivers with the nes mini thing. it just worked right off the bat. man, there is nothing to understand there...
