### ISSUE TITLE
clayfighter 2

### ISSUE THREAD

**Issue by nekonall** [ClusterM/hakchi2#572]
crashes after 1st round in a fight  tried 2 different roms .. anyone else have or can dupilcate this issue?

**Comment by RaZer0k** [comment]
hakchi2 use original emulator from miniSNES to load roms. Soo not all roms will run. you have to install retroarch-clover hmod and add --reatroarch to commnad line for the game.

**Comment by nekonall** [comment]
to the front or back of the command line?

**Comment by RaZer0k** [comment]
added in the back. you have to install retroarch-clover first. core and snes9x

**Comment by Drakonas** [comment]
This is an issue with Nintendo's canoe emulator not hakchi. Closing this issue. Use retroarch for problem games by installing the retroarch and snes9x2010 mods and adding --retroarch to the end of the command line.
