### ISSUE TITLE
Has anyone had any trouble with EA Sports games?  A few games glitchy

### ISSUE THREAD

**Issue by yougotaguy1** [ClusterM/hakchi2#575]
NHL '97, Madden '98 both freezing.

Super Starwars just won't play at all (I might have a Pal version)

Wrestlemania Very glitchy 

otherwise 20 other new games working great!!!

Thanks Cluster

**Comment by Deathstryker** [comment]
Haven't tried any EA games yet but I can confirm it does freeze on Illusion of Gaia and Actraiser II.  Just the nature of the default emulator. Dev said about 75% will work. You'll have to use retroarch mod for the ones that don't work well.

**Comment by Drakonas** [comment]
This is an issue with Nintendo's Canoe emulator and not Hakchi. Closing this issue. Use retroarch for problem games.
