### ISSUE TITLE
Cannot Save

### ISSUE THREAD

**Issue by ANTHONYG84** [ClusterM/hakchi2#576]
I can play my roms just fine, but if I am playing a rom from a different system I.E GBC/GBA or Sega when I press the reset button it gives me a c7 error and any in game save I had is gone. Can anybody help me with this?

**Comment by SupaSeal** [comment]
Just Use The Restore Points As Saves

**Comment by ANTHONYG84** [comment]
i'm sorry could you elaborate?

**Comment by ANTHONYG84** [comment]
anybody know about the restore point

**Comment by Drakonas** [comment]
This has been fixed since then if you uninstall hakchi from the hakchi menu, then flash og kernel, then perform a factory reset from the snes classic main menu (THIS WILL ERASE ALL SAVES, backup your saves before uninstalling hakchi if you need to!).
