### ISSUE TITLE
Can't dump kernel

### ISSUE THREAD

**Issue by GJST** [ClusterM/hakchi2#580]
I've followed the instructions, my computer recognizes the SNES mini, tells me to install the driver. The driver installs, but it just brings me back to the steps screen, it doesn't dump the kernel.

**Comment by slavaf1** [comment]
I have the same problem with SNES mini:(
Use USB cable from the console pack. 
My computer: Macbook pro (2012), windows 10.

**Comment by rylar717** [comment]
I have seen the SNESC console cable does have some challenges.  Try using a different USB cable other than the one that came with the console

**Comment by slavaf1** [comment]
rylar717, thank you! 
It worked for me! 
I think we should add this to hakchi2 FAQ...
