### ISSUE TITLE
Not detecting SNES Classic

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#584]
I flash the custom kernel, everything seems to work fine, then I  try to add games to the SNES Classic, it won't recognize the console and bypass the 3 step thing that says:

Please do the following steps:

1. Connect your NES/SNES Mini to PC via USB Cable

2. Turn it on

3. Install driver if not installed yet

When I click on install driver, it says that the NES/SNES Classic was not found. This never happened to me with the NES Classic. So what's going on? I can reconnect it to the USB port and turn it on by holding reset and power and then letting go. It acts like it installs it but nothing happens, as far as adding games goes.

I already flashed the custom kernel. The system wouldn't boot up, so I flashed original kernel and it now works. Tried it again to see if it'll work. Still won't detect it. Don't know what's going on?

If I try to reflash the custom kernel., It says "Kernel dumped but the MD5 checksum: [long list of numbers and letters] is unknown. Do you want to continue? Yes/No" I select "Yes", then once again the SNES Classic doesn't boot up, only when I restore the original kernel, it does.

I can still reflash original kernel but I cannot get the custom kernel to work nor add more games. What am I doing wrong? It won't install games nor detect the SNES Classic, like it did with the NES Classic.

One more thing, when I flash the custom kernel, at about 75%, I hear the USB disconnect sound, is that normal? I think that's what's causing the issue. Maybe not, I don't know.

UPDATE: Thought I got it to work. It seemed to add the 120 games I selected and even compressed them but when I booted up, only the original 21 games were showing up.

**Comment by ChadHakchi** [comment]
Ok. This happened with my Famicom mini, Well what I did was i deleted my Hakchi then downloaded it again.

Did all the steps and HUZZAH! It worked.

**Comment by 03bgood** [comment]
I did the same thing and re-added all 120 games. When I only had 40, I tried it and it STILL only showed the original 21 games!

**Comment by giomismo** [comment]
I have the same exact problem regarding the game synchronization. 

These are the steps I have followed: 
1.- I have been able to make a kernel dump using FEL mode.
2.- I have also been able to update the custom kernel using FEL mode. 
3.- Then I added some games on hakchi2.
4.- Finllay I tried to synchronize. In this step, hakchi2 does not detect the SNESC. When starting the SNES in NOT FEL mode (just power on and wait some seconds), the unknown device has the name "CLV-S-SNPY". Then, after clicking on "Install driver if not installed yet" on the SNES connection waiting screen, the new prompt says "NES Mini not found, sorry". Maybe there is required another driver installer for this "CLV-S-SNPY" device? Maybe the driver can be the same, but the driver installation software (or hakchi2) does not support this new name?

I am stuck at this point, anyone had this issue and has been able to solve it?

Thanks in advance.

**Comment by timcannell** [comment]
I have the exact same issue😥

**Comment by timcannell** [comment]
I compiled a release build of Hakchi from latest source last night...

**Comment by thickey256** [comment]
I had this same issue..  I'm using virualbox running Windows 10 on a Mac.  I wasn't able to install the virtualbox extensions at first so I was doing everything with USB1 emulation, and it wouldn't connect.  But once I sorted out the USB speed and changed to USB3 emulation it worked without any problems.

So could it be related to USB speed (virtual or actual)

**Comment by timcannell** [comment]
I have just tried with my 2016 dell XPS as opposed to my aging desktop PC. Same cable but this time it worked without a hitch. I can only conclude it's the usb ports or the hub I was going though. Hope this info helps.

**Comment by giomismo** [comment]
Can you tell which OS and architecture was failing and which worked?
In my case I am using a Windows 7 64 bits on a relatively modern computer (4 years). If I am not wrong I have tried both USB 2.0 and USB 3.0 and both failed, so it does not seems to be a speed issue in my case.

**Comment by timcannell** [comment]
Both machines running Windows 10 N 64 bit but my Dell XPS 8300 desktop is 6 years old using an Anker powered hub. Laptop is Dell XPS 15 2016.

**Comment by giomismo** [comment]
It worked on another computer (laptop this time) with a Windows 10 64 bits.

**Comment by 03bgood** [comment]
I finally got it to detect the SNES Classic and it acts like it added the games, but when I power on the console on my TV, only the original 21 games show up. I don't know what's going on?

**Comment by Viral87** [comment]
I have the same issue, my pc (W10 64bit) doesn't recognize the SNES Classic. Thou the first time (kernel dump and first game addition) it worked after several tries (I switched the USB port 3/4 times), now I cannot change the game list because my laptop refuses to see the SNES Classic.
I've already tried using the reset method, the zadig method and unabling the unknown driver license block from win10.
None of them worked.
I can play with my SNES Classic all 21 original games plus the 19 I added, but I cannot add more or even restore the original kernel.
I hope there will be a fix to this problem.

**Comment by 03bgood** [comment]
Yes, this is ridiculous!

**Comment by zimmertr** [comment]
Lol, you are the most ungrateful person ever. And clearly have no idea how open source projects work. 

_This_ is ridiculous.

**Comment by james-stocks** [comment]
Why close this if it's not resolved @03bgood ? That will only cause duplicate issues to be filed.

I also have this problem - dumping original kernel worked fine; updating the device ahead of syncing games appeared to work; but after this step (which ends in rebooting). The device is not available as a USB device in Windows 10. It's not appearing as a faulty or unknown device in Device Manager; it is completely missing! That suggests something quite low level.

On other ports on my PC; the device appears as CLV-S-SNPY but appears to be missing a driver; and the driver install util complains no device was detected.
I can maybe try some things like manually installing the driver (if I can find the file for it) or connecting the device indirectly via a USB hub; or finding a completely different PC to use.

EDIT: Got it working. Either I needed to re-run "Flash custom kernel" or I had never actually done that. I suspect the instructions I was following online were missing this step.

**Comment by kclay** [comment]
Windows 7 x64 Enterprise . First usb slot didn't work.. switch to another and windows picked it up so try different slots. Also be sure to follow the steps to have it turned off and hold reset then power.. Atleast on my windows it will make a noise when its picked up.

**Comment by BillyDanzini500** [comment]
This is What I Get.. "No Answer From Device" Please HELP

![no answer](https://user-images.githubusercontent.com/26205546/31807863-7ea965c2-b53e-11e7-9b00-fdcc56f82027.jpg)

**Comment by Cameron1391** [comment]
Have the same problem here. Driving me nuts

**Comment by BillyDanzini500** [comment]
I figured it out. Before you flash the system and click yes hold the reset up and power button on (like when you put it in developer mode), then click yes when it asks you “do you want to flash the system”. For some reason you have to put it in developed mode before it prompts you to put it in developer mode. Now my system is working again.

**Comment by Paul330** [comment]
That doesn't work for me. I am still struggling with the "not finding snes" problem and I don't know exactly what's the problem. I could sync the games some days ago for one time but since then I couldn't.

**Comment by BillyDanzini500** [comment]
If you’re having trouble finding the new/snes is “zadig” to find the driver for the system.  Here is the download link.. http://zadig.akeo.ie/downloads/
find the right zadig for your windows.

**Comment by Paul330** [comment]
Zadig didn't help so far. I used zadig 2.3 for Windows 10 64bit and installed WinUSB (v6.1.7600.16385) but nothing changed. SNESC connection is lost during flashing the custom kernel and the device is no longer found.

**Comment by ballinboy4613** [comment]
Had the same problem and this worked for me. Let me know if this helps. https://www.google.com/amp/s/amp.reddit.com/r/miniSNESmods/comments/752dc9/how_to_use_hakchi_2_on_a_mac_with_virtualbox/

**Comment by BillyDanzini500** [comment]
Try uninstalling the same modules you installed. I deleted some of the modules and had to put them back just to uninstall them again

**Comment by Paul330** [comment]
Thanks for your hints. Deinstalling the Hakchi Kernel via the hakchi menu helped. I think I crashed the kernel during retroarch installation. Now everything works fine again.

**Comment by ChadHakchi** [comment]
Mine works even the firzt time i downloaded hakchi 2.21f witb no problems

**Comment by diouro** [comment]
I had to comment on this, thanks to @thickey256 I finally got it. I was also running virtualbox on my Mac and after a couple of hours trying all I had to do was install the VirtualBox Extension Pack that allowed me to change the default USB configuration of my VM from 1.1 to 3.0.

**Comment by sega95** [comment]
I had the same issue, until i used the official cable that came with the system. It has a white label saying to unplug the cable when not in use.
The other one I had came with a second hand nes mini and powered on fine no problems, but clearly was not up for data transmission or something, as my laptop could not even detect it using that cable

**Comment by zerosix** [comment]
^^^ +1

Didn't work for me on two computers until i tried using the cable it came with and it worked right away

**Comment by Drakonas** [comment]
Everyone needs to continue any of this conversation on the proper subreddit. This is a bug tracker, not a forum to discuss problems. We get notifications of every update on this tracker, and the more junk to filter through the longer it will take to fix issues.
