### ISSUE TITLE
Some chinese characters are not shown

### ISSUE THREAD

**Issue by soonjistarr** [ClusterM/hakchi2#586]
Hello.
First of all, thank you very much for your great work.
I installed hakchi2 version 2.20 on my super famicom mini (japanese ver.).
I added some roms and confirmed they work fine.
However for some original roms with title including chinese alphabet, several chinese alphabets are not shown from the main screen.
For example, the '聖剣伝説2' is shown as '剣伝説2' (first character is missing).
Likewise for the legend of zelda, one chinese alphabet is missing from the original title.
I think the missing problem is only on main screen.
Thank you.

**Comment by LanceloteHK** [comment]
I know it is quite an effort to put the all the kanji fonts into the library. But at least I hope that all those kanji of the original  games can be shown correctly. Thank you.

**Comment by Drakonas** [comment]
I am not able to check this @soonjistarr as I do not have the roms nor contact with ClusterM. Has this been fixed? If not I can add the "bug" label.

**Comment by Drakonas** [comment]
Closing this issue as @soonjistarr has not responded.
