### ISSUE TITLE
sega mega drive and Sega genesis rom support for SNES mini?

### ISSUE THREAD

**Issue by Jake225** [ClusterM/hakchi2#589]
hi i know this isn't a issue...well it kinda is.  But will hakchi2 be able to flash Sega mega drive and Sega genesis roms and even NES games to the SNES mini any upcoming update of hakchi2 or is this not possible? 

Kind Reguards :)

**Comment by missionfloyd** [comment]
It can already do this. You need to install retroarch
https://github.com/ClusterM/retroarch-clover/releases
