### ISSUE TITLE
Power light flashes after updating

### ISSUE THREAD

**Issue by bruston81** [ClusterM/hakchi2#59]
Hi all,

So I followed the instructions, all went well, says I'm done and wait for the power light to go off and restart.... The power light never goes off, and it just keeps flashing on and off slowly.... I can't reset it, can't turn it off, no output to TV.... All I can do is put it back in FEL mode and restore the original kernel.... Any ideas?
Thanks!

**Comment by bobuk1973** [comment]
I have the same issue exactly with my European nes mini and when I restart I just get a blank screen and no boot up. Able to restart after reflashing original kernal.

**Comment by bruston81** [comment]
I'm doing this via Parallels for Mac.... 
by any chance are you too? Maybe we need a native Windows computer?

**Comment by gaxy123** [comment]
I have the same issue, also with Parallels on a Mac.

**Comment by stayupthetree** [comment]
Same issue, but only when I don't use 2.11 and I build from source. I don't see a way of logging to see any unknown errors

**Comment by mikebetz42** [comment]
Having the same issue with Windows 7 and hakchi2 2.11. Power light blinks, looks to be stuck in a boot loop. Tried this with just a handful of games. hakchi2 says all done, but stuck with the blinking light. I let it sit for a long time.  Tried it on the TV, and looks like it's stuck in that boot loop....

**Comment by stayupthetree** [comment]
Oddly enough I was used 'git clone' to copy the repo and build from there. Was never able to get a successful flash. downloaded the master.zip and used that to build and it worked flawlessly.  I don't know if you guys are using official releases or from source so I can't say what is going on. This is just what worked for me for some strange reason.

**Comment by mikebetz42** [comment]
I copied the the whole dir from the desktop to the laptop, and I was able to get it working using my laptop with Windows 10. I was using the pre-built executable.

**Comment by bruston81** [comment]
Awesome! I'll check that out this weekend, just have to get my old windows laptop running again! Thanks!

**Comment by wmartindale408** [comment]
Hi All,

After bashing my head over the red blinking LED, we found all of your posts here in this thread.
We had been testing on a Mac+VMware+Windows 7 64-bit.  And had no luck, always the blinking LED.

We just had the chance to try on a physical Windows 7 64-bit host, and had success!

Good luck.

**Comment by BarnetChopper** [comment]
I get the same ..also using parallels.

**Comment by raydoo** [comment]
Also used Parallels to flash the NESC starting ye olde windows

**Comment by bruston81** [comment]
I pulled my old windows 7 machine out of the closet and it worked flawlessly.... no more flashing power button... parallels must have been the issue, as it has been with a few other issues, like getting a USB windows 7 installer created to repair the old windows machine.... wonder if there is something more stable us Mac peeps could use.....
