### ISSUE TITLE
Option to remove autoplay folders ?

### ISSUE THREAD

**Issue by pascl** [ClusterM/hakchi2#593]
Hi,
On SNES mini, when you have savestates on each game, it seems to have rewind demos more often than normal demos.
So I wanted to disable these normal demos. Then I was looking for matching files and I removed the autoplay folders present for the 21 games that seems to be for these demos.

It seems that these folders are back at each new sync with hakchi.
Can we have an option to have these folders or not ? (about 30MB for all 21 folders)

PS: if someone know syntax for these files and how to generate them, it would be also interesting if you want to add demos on non-stock games ;)

**Comment by Drakonas** [comment]
The shortcuts have been removed from recent versions of hakchi.
