### ISSUE TITLE
Scrolling left makes furthest game icon disappear (SNES Classic Mini)

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#596]
Minor issue - when on the default setting (extra games in a new folder, original games in root), if you scroll left (in the folder with more games), the game at the end on the right disappears before it reaches the end of the screen. Compare this to the normal games screen and the game icon at the end doesn't disappear before the screen end.

**Comment by Drakonas** [comment]
You need to have 12 or more games in a list for it not to do this. It is a native UI bug with the SNES Classic.
