### ISSUE TITLE
Unable to Add ROMS to "Selected Games" List

### ISSUE THREAD

**Issue by AlexFad53** [ClusterM/hakchi2#597]
Hi - Could be a simple issue here in  that I need to get a different ROM pack as mine was put on my laptop last year by my brother so I could play SNES games on my laptop. Or possibly, I downloaded Hackchi wrong? But I don't know how that is an issue due to the application opening and seeming to run correctly.

I click "add more games" 
Go to file called SNES PACK. 777 ROMS
Select the game/file, click open (I have both zipped and  unzipped  versions of the ROM pack I have)
Error message: "Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click quit, the application will close immediately. Access to path *C:\Users\Alex\Dcouments\hackchi2.20\hachi2\config\ini is denied

Thanks for your help!

**Comment by brandonrdnt** [comment]
How are you running Hakchi?  Did you install it using the web installer or are you running it from a folder on your computer?  It looks like you have a permissions issue, you might be able to fix it by right-clicking on Hakchi and selecting "Run as Administrator"
![runas](https://user-images.githubusercontent.com/32648434/31350159-63fc4a04-ace3-11e7-9b16-6f998051d270.png)

**Comment by AlexFad53** [comment]
Thanks for responding Brandon. Per instructions of the website, as a new user  I attempt to use the web installer. However, I keep getting error messages that something might be wrong with my connection. I was able to get through with the web version ONCE, and dont know why the instance worked just once. After getting to the final step where you click Install, Hakchi completely closed.

In case the below error box isnt showing up, when  I use the web version the error box is "Application download did  not succeed. Check your network connection, or contact your system administrator or network service provider"
![image](https://user-images.githubusercontent.com/32646606/31350688-244db9ac-acf6-11e7-8cb1-fa20b6b5e739.png)

**Comment by AlexFad53** [comment]
Run as administrator did not work for the actual zip version.

**Comment by brandonrdnt** [comment]
What kind of antivirus are you running?  I've seen reports of AVG causing issues with preventing Hakchi from writing to the Documents folder.  I personally use Norton and it always throws fits with web installer applications, including my own (I'm a software developer).  You may need to try adding Hakchi to your "allowed" apps list or whitelist.

**Comment by Drakonas** [comment]
@AlexFad53 you need to obtain the original kernel your brother dumped from the SNES Classic before modding it to use this. Please ask for help with this on the SNES Mini Mods subreddit. This is a bug tracker for reporting bugs with Hakchi, not a personal help line, and you will get faster results there: https://www.reddit.com/r/miniSNESmods/
