### ISSUE TITLE
Classic games just black screen

### ISSUE THREAD

**Issue by Bombahee** [ClusterM/hakchi2#598]
Hi guys, I managed to add games on my snes classics and  it show up on my main menu, but when I select the game, it shows black screen for a few seconds and go back to main menu...

I installed classic games like...

1942
Balloon Fight
Bomberman
super mario
battle city
twinbee
etc...

Sorry, I'm so new in hacking these snes nes things.

hoping for guidance from you guys..

thanks in advance

**Comment by Drakonas** [comment]
These are NES games. You need retroarch to run these, as the SNES Classic can't natively run NES roms. Ask here if you need help with that: https://www.reddit.com/r/miniSNESmods/
