### ISSUE TITLE
Q: Difference between internal version 2.0.20.14 and internal version 2.0.20.15

### ISSUE THREAD

**Issue by orenigittigitt** [ClusterM/hakchi2#599]
For a short period v2.20 (internal version 2.0.20.1**4**) was available before it was update to v2.20 (internal version 2.0.20.1**5**). 
As I didn't find any information about changes between these internal verisions, maybe anyone can provide some information I have possibly overseen. Just wondering if there might be a reason for me to update my 2.0.20.14 kernel due to 'something'.
Cheers

**Comment by gnadenlos** [comment]
Fixes for Japanese systems AFAIK.

**Comment by orenigittigitt** [comment]
Thanks. Is there a changelog I can query in such cases?

**Comment by Arakon** [comment]
It's called github. Look at the "code" sections, check the commits that contain a change to the revision number. Last commit to have the same revision number change is also the last change to be included in the release.

**Comment by orenigittigitt** [comment]
Well, thank you. Saw what's part of the commit message in https://github.com/ClusterM/hakchi2/commit/afb1d8a8b5fde2e4d49ad9c42e29d64f65074718 but still wondering if I would have to deinstall/install kernel anytime I'm updating Hakchi within a major release.

**Comment by ClusterM** [comment]
It was hotfix for Super Famicom owners. You don't need to reinstall kernel every time.

**Comment by orenigittigitt** [comment]
Thank you, great job your doing here in your spare time! Chapeau!

**Comment by Drakonas** [comment]
Next time please ask these kind of questions on the SNES Mini Mods subreddit or Nintendo Classics Discord. This is a bug tracker for Hakchi, not a personal help line.
