### ISSUE TITLE
Can't repack ramdisk

### ISSUE THREAD

**Issue by mdridley** [ClusterM/hakchi2#6]
Uninstall or Sync are both doing this. Can't seem to find a way around it.

Using Windows 10.

**Comment by ClusterM** [comment]
Hi.
Please try to use another folder/disk. I think that path to app is the problem.
Anyway I'll try to fix it.

**Comment by ClusterM** [comment]
Also repack procedure will be changed in next version.

**Comment by mdridley** [comment]
That was it! Moved it to the C: root and it worked great!

**Comment by ClusterM** [comment]
Version 2.09 should work on any drive now.
