### ISSUE TITLE
SNES MINI ! I can't flash the kernel or synchronize games ! Windows Error

### ISSUE THREAD

**Issue by jfsb75** [ClusterM/hakchi2#600]
Hello everyone ! 

I'm coming here seeking for help about the Snes Mini ! i want to add games (like everyone does i guess) so i've downloaded the Hakchi2 tool. I chose the Snes Classic Mini system and i dumped my kernel ! 

So now, i've got the problem (i've tried a lot of things) ! 

Impossible to flash the kernel ! i got this error screen 
![image](https://user-images.githubusercontent.com/32647669/31349208-98d20a90-ad22-11e7-8219-e5250895513e.png)

i don't understand what's wrong ! So if you guys have a solution at this issue, i'll appreciate it so bad :) 
Thank everyone

**Comment by Turom421** [comment]
Are you using the USB cable that came with your SNES Classic and plugging it into a USB port on the back of your computer?

**Comment by Drakonas** [comment]
USB 3.1 ports are not supported. Try using a 3.0 or older port.

**Comment by Drakonas** [comment]
Closing this as there has been no response.
