### ISSUE TITLE
[hakchi2] Any way to sync from modified SNESCE to the PC ?

### ISSUE THREAD

**Issue by emufrance** [ClusterM/hakchi2#601]
Situation: A friend brought his SNESCE with a custom firwmware and some additional games. He don't know how to install Retroarch and other games.

How i can sync my hakchi2 (or newer) install with his snesce without wiping it ?

**Comment by brian91292** [comment]
Use the FTP feature in hakchi2 and copy /usr/share/games to your computer.

**Comment by jcbelinda** [comment]
Emufrance, if you figure this out, please let me know. 
My situation is a bit different. I actually did my mod to my snes mini, and everything works well, but my computer wiped everything. Including my original kernel. So I want to know how to copy all the snes info to my computer without wiping all my saves so I can add more games. Let me know if u figure this out

**Comment by brian91292** [comment]
....I literally posted the solution.

**Comment by jcbelinda** [comment]
Ok may I ask what FTP means? I guess I don't understand. I apologize

**Comment by brian91292** [comment]
Google my dude, download an FTP client such as FlashFXP or something and look in the tools menu in hakchi. Enable the FTP server, then click open FTP client. Then browse to the directory I mentioned above and drag and drop the games folder to your computer.

**Comment by emufrance** [comment]
Thx @brian91292
