### ISSUE TITLE
Games list

### ISSUE THREAD

**Issue by 90sretrogamer** [ClusterM/hakchi2#603]
Hi All
I am very new to this. Are the games included in the hack instructions? I followed it all and didn't see any games in the games folder except for the original. 

If they have to be downloaded from another site can someone provide a good site where I can get a mass dump of games?

**Comment by Arakon** [comment]
No. Piracy links do not belong here.

**Comment by jgoldsack** [comment]
Google is your friend.

**Comment by zimmertr** [comment]
What you're asking for is illegal and you should be aware of both that and the consequences of your actions before you use this software for illegal purposes.

**Comment by 90sretrogamer** [comment]
Ok thanks.
