### ISSUE TITLE
MAME Roms

### ISSUE THREAD

**Issue by skufo88** [ClusterM/hakchi2#604]
im trying to load NBA Jam T.E. for mame i switched the command line from zip to fba and its still not loading can i add --retroarch or does that mean its not combatibal? PLZ HELP!!!

**Comment by JamBerge** [comment]
There's several posts online about how to get MAME working, google is your friends. You are probably missing BIOS files. You can place them into the game folder itself or lookup and find out how to use the missing_bios files .hmod in Extra_Cores.

**Comment by Drakonas** [comment]
This is not the place to ask for personal help for setting up roms. This is for submitting bugs for Hakchi. Ask elsewhere please.
