### ISSUE TITLE
SNES -Command line --fullscreen

### ISSUE THREAD

**Issue by MasterPlatinum** [ClusterM/hakchi2#606]
Hello,
Is there a way to make the command line --fullscreen working?
I tried to make it work but i got a C7 error when game loading, 
i put this:

/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-YFENC/Donkey_Kong_Country_2.sfrom.7z --volume 100 --fullscreen -rollback-snapshot-period 600

Thanks :) !

**Comment by Drakonas** [comment]
.... Canoe doesn't have a fullscreen argument option. What are you doing?

**Comment by MasterPlatinum** [comment]
In the FAQ and search Google about hakchi2 commands

**Comment by MasterPlatinum** [comment]
There 

https://github.com/ClusterM/hakchi2/wiki/Command-line-arguments

**Comment by Drakonas** [comment]
@MasterPlatinum that was for Clover, the NESC emulator. SNESC uses a different emulator called Canoe. lol. The arguments haven't been found for Canoe yet, if they even exist.

**Comment by Drakonas** [comment]
![Image](http://genesis.whatbox.ca:42424/img/chrome_2017-10-09_22-37-26.png) @MasterPlatinum You forget this wiki and code was also for the NES Mini released last year. It was just updated for SNES Mini.

**Comment by gingerbeardman** [comment]
Canoe command line arguments: https://github.com/ClusterM/hakchi2/issues/478#issuecomment-335000772
