### ISSUE TITLE
hakchi 2.2 Write Error when synching games

### ISSUE THREAD

**Issue by marcaces** [ClusterM/hakchi2#609]
This error page happens everytime i try to add games to my US snes classic. I had no problems with dumping the kernel, and loading the custom kernel. But once I try to  synchronize the selected games. These errors keep popping up. Any solutions to this problem? I've tried different ports, and I'm using the usb cable that came with the snes classic. Any help would be appreciated. 
![screen shot 2017-10-09 at 2 45 42 pm](https://user-images.githubusercontent.com/32654574/31360996-ec457db4-ad05-11e7-9dcd-949022ad3aaa.png)

**Comment by drbourbon** [comment]
exact same issue here. tried with different cables. I am on a mac with oracle virtualbox.

**Comment by DecanFrost** [comment]
did you resolve this ? if so what was the solution

**Comment by drbourbon** [comment]
yes, it turned out it was a common problem with usb connection being very slow in virtual box. I switched to a different windows emulator and everything worked fine.

**Comment by seannbastard** [comment]
which windows emulator did you use?

**Comment by drbourbon** [comment]
parallels
