### ISSUE TITLE
my computer deleted files

### ISSUE THREAD

**Issue by jcbelinda** [ClusterM/hakchi2#610]
Hello. I have hakchi 2.20 for my snes classic edition. ive done this before with my NES classic so I know how to complete the mod. I modded my console yesterday, and dumped my original SNES kernel. after doing so, I flashed the custom kernel, added the driver, and then added the games. my snes classic works flawlessly. 
here Is the problem. my computer deleted all my files. I don't have the original dump anymore. I don't have even the custom kernel saved or the games I had in hakchi. everything is gone. I already have saved files on my snes classic edition. I don't want to have to reset everything to factory settings. 
is there any way that someone can help me flash my saves or how I can make sure I don't lose anything on the actual snes mini as far as saves are concerned??? from there, can I flash my friends original kernel and add the saves to it? is that even possible??

**Comment by zimmertr** [comment]
Computers only do what humans tell them to do.

**Comment by jcbelinda** [comment]
i dont need a smart a comment. please move along. i didnt delete the stuff from my computer. im not an idiot. as a matter of fact i have yet to lose anything from my NES classic mod but yet this stuff vanished. so please move along.

**Comment by TonyXL2** [comment]
You do not have an issue with the hakchi2 program, so why are you posting this here? 

Look at the issue below yours: "hakchi 2.2 Write Error when synching games". That is an actual problem with the program, and the user included a useful screenshot so the devs can investigate.

Try reddit or other SNESc-related message boards for your computer problem.

**Comment by jcbelinda** [comment]
I posted this here because I thought other people could help me find out if I could use the program to keep the saves I already have and transfer them over. 
But I guess there is nothing but assholes here that don't want to read the whole issue and try to help out.

**Comment by zimmertr** [comment]
Glad you could resolve your issue
