### ISSUE TITLE
MINI Not Found

### ISSUE THREAD

**Issue by kbarrett1985** [ClusterM/hakchi2#612]
Having an issue synchronizing to customize the kernel. I follow all steps, and then get a windows box pop up saying "NES Mini not found, sorry".

I am using USB that came with the system and have tried others as well with no luck. I am selecting SNES as the type, but message says NES. Any ideas?

Thanks

**Comment by Drakonas** [comment]
Are you following the on-screen instructions? Wait for the system to turn off, then disconnect then reconnect the USB, then hold reset while flicking the power on, and continue to hold reset until the bar starts moving, and then let go of reset. Also, this will not work with USB 3.1 ports. You have to use a USB 3.0 or older port.

**Comment by Drakonas** [comment]
No response from OP, so I am closing this.
