### ISSUE TITLE
USB extension cable (Nyko) does not register input from SNES controller (SNES Classic)

### ISSUE THREAD

**Issue by beyondmany** [ClusterM/hakchi2#615]
Summary: Using hakchi2 v 2.2.0 on SNES Classic, the device no longer registers input when using the Nyko Extended Link Extension cable (https://nyko.com/products/extend-link-for-nes-classic-edition)

(Note: Cable works fine on an unmodified SNES)

Steps:
0. Windows 10.
1. Install  hakchi2 v 2.2.0 on SNES Classic
2. Add games 
3. Disconnect via USB
4. Reconnect to TV and insert the Nkyo cable and  SNES controller that game with the SNES Classic.
5. Power on SNES Classic
6. Attempt to use controller (buttons, D-pad)

Observation:
1. Nothing happens.

Workaround:
1. Disconnect Nyko extension cable and insert the SNES Classic controller directly into the SNES Classic.
2. Functionality restored.

Note:
1. Hardware or power cycle reset has no effect.
2. Inserting the extension cable after bootup has no effect.

Occurs 5/5.

I don't have any other extension cables to try.

**Comment by LGSilva** [comment]
It appears this extension cable is for the original NES classic, not the SNES.

Have you tested it on an unmodified SNES ?

**Comment by beyondmany** [comment]
@LGSilva  Yes, it worked perfectly on the unmodified SNES classic prior to installing hakchi2 2.2.0.

**Comment by sectokia** [comment]
Do you have a NES mini controller you can try, or any other controller with a shorter cable?

Can you ensure that when it works without hakchi that it's powered from the same USB power source as when it's not working?

**Comment by warlockv2** [comment]
This is not isolated.  Iv heard othwr have same issue on tourube videos.
How odd

**Comment by beyondmany** [comment]
@sectokia I do not own a NES mini, nor the controller for it. I'm using the original SNES classic USB power cable. 

@warlockv2 Thanks for confirming the issue.

**Comment by nfsutim** [comment]
Using Extension cable on snes mini with original controller results in controller not working at all.

unplug extension cable works fine.

**Comment by beyondmany** [comment]
@nfsutim yes, that is indeed a summation of the workaround...

**Comment by bmany** [comment]
*bug

**Comment by beyondmany** [comment]
Anyone else able to use an extension cable? If so, which brand and model?  Thanks!

**Comment by beyondmany** [comment]
@sectokia @warlockv2 UPDATE: I discovered that the extension cables from INSIGNIA (https://www.bestbuy.com/site/insignia-6-extension-cable-for-nintendo-snes-controller-2-pack-black/6025000.p?skuId=6025000)  work as expected when used on the modded SNES Classic console. It's not clear why the Nyko cable no longer works after installing the custom kernel.

**Comment by Drakonas** [comment]
I use these and they work perfectly. https://www.amazon.com/gp/product/B01N5CA2JS/ref=oh_aui_detailpage_o05_s01?ie=UTF8&psc=1

This seems to be a brand design issue, and cannot be fixed by software. Closing.

**Comment by beyondmany** [comment]
@drakonas thanks for the follow up. I agree, having tried another brand works.

**Comment by androidand** [comment]
I know this is closed but I just wanted to add this. I don't think this is a SW issue. I have some extension cables (unknown brand) that work with both connectors on my NES Classic and on player 2- connector on my SNES Classic. It also works after some wiggling on SNES Classic player 1 port. I am suspecting issues with the Console connector, but it could of course also be the cord connectors that somehow are out of spec.
