### ISSUE TITLE
No sound after adding new games

### ISSUE THREAD

**Issue by SkylaDoragono** [ClusterM/hakchi2#619]
I have a weird issue, and I think it may be because of my TV, but it's still weird.

Before I add games to my SNES mini, I can get sound just fine.  However, once I add games using Hakchi, all sound immediately dies.  It's not just sound in games, it's on the main screen as well.  This just happened with my SNES mini, but this also happened when I added some games to a friend's NES mini, however, he didn't have the sound issue on his TV.  I was able to restore my SNES mini without issues, and I can get sound again.

My TV is an older flat screen from 2010, and is a hospital grade PDi television.  I believe at this point, PDi was still using Zenith-based technology for their televisions, but I can't be 100% sure.  It's still odd that the sound would work before I add games, but not after.

**Comment by Drakonas** [comment]
May I ask how many games you are trying to install? The system will only allow a total of 252MB to be added including mods and games.

**Comment by SkylaDoragono** [comment]
I only installed like... five or six extra games?  The total MB afterwards was somewhere around 91.

When I added games to my friend's NES, it was much more, but still didn't total over 252MB.

**Comment by SkylaDoragono** [comment]
![untitled-2](https://user-images.githubusercontent.com/32659845/31523426-70f91408-af81-11e7-870c-69d8beff13d3.png)
![untitled-3](https://user-images.githubusercontent.com/32659845/31523427-7111982a-af81-11e7-9a61-fe894febe7f6.png)
![untitled-4](https://user-images.githubusercontent.com/32659845/31523428-7128e714-af81-11e7-8c46-2c9c63d7a2ac.png)

Sorry for the double reply; here's my buddy's set up for his NES, and the games that I tried on my SNES.  Yes, some are hacked/translated/whathaveyou, but I encountered this issue even without the altered ROMs on there.

**Comment by Drakonas** [comment]
... The SNESC uses some of the space already for the built in games. And they can't be removed. Secondly you need to update to 2.21b, AND factory reset and then uninstall hakchi from your SNES Classic, as 2.20 used up more space than necessary and you cannot remove the files without a reset. 2.21 fixes an issue where the original games were copied into the storage, when that was unnecessary.

EDIT: Also, canoe doesn't like modified roms. Try running those games in Retroarch.

**Comment by SkylaDoragono** [comment]
These two were done before 2.21b came out, ftr.

I had restored the original kernel to my SNES mini when the sound didn't work; does that count as uninstalling hakchi from my system, or do I need to consult the wiki?

**Comment by Drakonas** [comment]
You need to actually run an uninstall from the hakchi2 program after doing a
factory reset from the snes classic main menu. Uninstalling also flashes
the og kernel, but it also removes all the hakchi2 files. The kernel
doesn't have all of the modified files. Just an FYI, the factory reset from
the snes classic erases all saves, so makes sure you use the save state
manager in tools when the custom kernel is installed to backup your saves.
You can then restore after everything is done. But restore one at a time.
The restores fail often for me but you can just try again.

**Comment by SkylaDoragono** [comment]
Success!  That worked!  Thank you very much for your help!

(BTW, that Breath of Fire II is the re-translation by Watercrown Productions, with all the extra bells and whistles and anime-style opening added, and it works BEAUTIFULLY.)

**Comment by SkylaDoragono** [comment]
I take it back.  It only worked once.  I spent the last three hours trying to add more games, trying to completely wipe and add games fresh, and then finally just added those games that I had before back, and nothing.  Sound won't play again.

I have no idea why it only worked once, or why it's just doing it on my TV.

**Comment by SkylaDoragono** [comment]
OMFG nevermind.  It's just how my stupid TV processes sound; I need to cycle the sources before the sound will play.
