### ISSUE TITLE
New games not showing up, only the original 21 games

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#621]
I just added like 120 games to the SNES Classic (all compressed) and it acts like it adds them, but when I boot up the console on my TV, only the original 21 games are showing up. What's going on?

**Comment by Drakonas** [comment]
120!!!!? You are probably adding way too many games. Most people can only fit about 60-80 extra games before running out of space. The SNES classic only has 252MB to work with your chosen extra games or mods other than the ones that came with the console (which cannot be removed... they can be hidden but not removed).

**Comment by 03bgood** [comment]
They now show up but some of the games like Illusion of Gaia and ActRasier 2 have issues. Don't know why.

**Comment by Drakonas** [comment]
You need to use RetroArch with those games. See the compatibility list for Canoe: https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/htmlview?sle=true# Some games don't work with the default emulator, so you need to install RetroArch. There are guides for this. https://www.youtube.com/watch?v=2NaDNqV-qZ4

**Comment by zimmertr** [comment]
You need to read documentation and understand what you're doing and WHY you're doing it when it comes to alpha software. Not blindly fumble around and ask questions that you didn't spend anytime researching on your own.
