### ISSUE TITLE
Transfer save states to PC

### ISSUE THREAD

**Issue by jcbelinda** [ClusterM/hakchi2#623]
Is that an easy way to transfer save states already in the NES/SNES mini to computer PC? My minis have already been modded and I don't have access to original kernel or custom kernel on my pc. 
This mod was done by a friend and now I want to do add additional games myself. But I want to ensure that I don't lose any of my saves.

**Comment by brian91292** [comment]
This is something you should ask about on reddit or some other forum, not github.

But look in the tools menu, there's a save state manager.

**Comment by jcbelinda** [comment]
In order to utilize the save state manager, it says that I have to flash the custom kernel. Again I don't have this kernel in my pc

**Comment by dave11674** [comment]
Custom kernel is built into the software mate

dave

**Comment by dave11674** [comment]
ive just transferred my save state for zelda to my pc
can i use this save stat with snes9x or similar ?
thanks

dave

**Comment by Drakonas** [comment]
https://www.reddit.com/r/miniSNESmods/comments/761m8j/srm_to_canoecloverclvs_converter/?st=j98rvhjr&sh=2711b33c this can be usd to convert savestates from PC and back. Please don't ask for personal help on this issue tracker. This is only for submitting bugs for the Hakchi code. Ask on the SNES Mini Mods subreddit next time.
