### ISSUE TITLE
Games Not Working

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#624]
ActRaiser 2: Black screen after Enix logo
BS Zelda (Quest 1): C8 error
BS Zelda (Quest 2): C8 error
Illusion of Gaia: No sound, then black screen after pressing start at title screen
Wario's Woods: Works but music skips badly and sound gets distorted during gameplay
The Legend of Zelda: Goddess of Wisdom (ROM Hack): C7 error

I sure hope future updates fix these issues with these games. I kinda enjoyed IoG, when playing it on my New 3DS w/ CFW. I have no interest in using RetroArch since that probably has issues, too.

**Comment by Juli199696** [comment]
Try to use the USA version of the game (The Original) version. I tried TMHT Turtles in Time and DKC2 and got bad sound Skipping aswell on the EU/GER version. I will gonna try the USA version the next days.

**Comment by zimmertr** [comment]
Please close this issue. It is redundant and unnecessary. OPs problem could have been resolved with 3-4 minutes of research. There are about 5000 similar issues on this project already. Search before you post........... https://github.com/ClusterM/hakchi2/issues/582

https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/edit#gid=2014317767
