### ISSUE TITLE
I am getting this error while trying to dump the kernel from my SNES Classic

### ISSUE THREAD

**Issue by GeorgeJellybean** [ClusterM/hakchi2#625]
![exception has been thrown](https://user-images.githubusercontent.com/32662574/31369223-94520292-ad48-11e7-91b5-38ada0fd1c4c.PNG)

I've tried all that I can think of to fix the issue, but every time I try, I get this error after trying to dump the kernel

So now as of v2.21b, I run the debug version and get this
![exception has been thrown2](https://user-images.githubusercontent.com/32662574/31417100-194e8894-adf3-11e7-93b0-0c55f42794a7.PNG)

![exception dos](https://user-images.githubusercontent.com/32662574/31417101-1bdfed64-adf3-11e7-8a77-3f28587de3a8.PNG)

Anybody have any ideas at all??

**Comment by joetheuseless** [comment]
same problem and the creator has no idea why this is happening! junk software needs alot of work gonna stick to my SD2SNES until this is fixed at this moment in time its broken

**Comment by Drakonas** [comment]
Thanks for calling this "junk software" when it works for most people just fine. Ryzen is not supported due to a problem with Ryzen's USB driver design (their fault not ours).

See issue #620 . Closing this as a duplicate.
