### ISSUE TITLE
Can't install music hack after Retroarch

### ISSUE THREAD

**Issue by Darkshadow3582** [ClusterM/hakchi2#626]
I can't install custom music because al time give me a "kernel size error"
I try install a simple sound like TLoz theme (2.2mb) but nothing and if try install manually make a soft brick

**Comment by ClusterM** [comment]
Seems like you have invalid kernel dump.

**Comment by Darkshadow3582** [comment]
If I reflash another kernel,maybe fix the problem?

**Comment by ClusterM** [comment]
You need correct kernel to install mods, not to flash it.

**Comment by Darkshadow3582** [comment]
How can I find out which kernel is correct?
I have the original dump before I start to modify it, is that?

**Comment by ClusterM** [comment]
Can you say MD5 of your kernel dump?

**Comment by Darkshadow3582** [comment]
Of course
MD5: d76c2a091ebe7b4614589fc6954653a5

**Comment by Darkshadow3582** [comment]
In the end I could solve it
Thanks for everything and hope you continue to improve the project;)

**Comment by zimmertr** [comment]
@Darkshadow3582 please both post your solution and close this issue. By posting your solution you can help others who experience this issue as well.

**Comment by Darkshadow3582** [comment]
Sure
I restore the kernel and still skipped the same error
A friend gave me his kernel and restore it with hakchi 2.20 and then install the custom kernel with the hakchi 2.21b web installer and everything works perfectly

**Comment by zimmertr** [comment]
Thank you for sharing. Please close this issue now.
