### ISSUE TITLE
Questions about NES Classic and its usage with hakchi2

### ISSUE THREAD

**Issue by efgamer** [ClusterM/hakchi2#627]
Hello there.

I'm concerned about the warranty and I've a couple of questions:
1 - Does the driver that I need to install modify something on the NES Classic?
2 - What does dump exactly do? Does it change anything on the NES Classic after the original image has been dumped? 
3 - Regarding the dumping process, why the NES Classic doesn't turn off even if I press the power button after the process has been completed?
4 - I accidentally pressed the power button at the start of dumping process while it was installing the driver and pressed again while the dump was in progress, did I screw something up?
5 - What is the difference between uninstalling and flashing original kernel?
6 - What does boot original kernel / custom kernel to RAM do and what is the difference with flashing original / custom kernel?

**Comment by TonyXL2** [comment]
This is a repository for bugs, not a message board for questions. If you have a specific problem, post details/screenshots/etc so it can be diagnosed. If you have questions, post to reddit or other SNESc-related message board.
