### ISSUE TITLE
Sonic 1 crash issue

### ISSUE THREAD

**Issue by NoeleyC** [ClusterM/hakchi2#628]
When soft resetting back to the menu from this game, my Mini crashes and I have to physically reset the machine. Not seen that issue with any other games (have tried a selection of Megadrive and GBA games)

**Comment by ghost** [comment]
I had similar problem resetting back to menu from games.when pressing combination retroarch would pop up it would then c8 or c6 error and hang  .physical reset needed . 
to try fix change the reset buttons combination to other combination of buttons i set to L R only . this worked for me .

**Comment by NoeleyC** [comment]
I'm not getting any error message, the machine simply crashes out. I'll try retransfer the game tonight, maybe something got corrupted song the way the first time!

**Comment by NoeleyC** [comment]
Reset Mini back to stock, and reflashed with newest version of the hack, then reinstalled all ta games. Everything works great now! (and I recommend using custom folders so you can separate games by system type and add custom folder icons!)
