### ISSUE TITLE
C7 Error -- Global Command Line Arguments

### ISSUE THREAD

**Issue by ecmyers** [ClusterM/hakchi2#63]
I tried to apply the scanlines to all the games by typing **--enable-crt-scanlines, -sc** into the global command line field; however, afterward whenever I try to load any game I get the C7 error. I was previously able to apply this command to individual games in 2.10, though I haven't tried it on a game-by-game basis yet in 2.11. I tried applying it twice, and I believe I am typing it correctly! What am I missing?

**Comment by ClusterM** [comment]
I'll check it.

**Comment by ClusterM** [comment]
I checked it and it's working fine. Make sure that you entered this argument correctly. And you can to change this option without sync in the new version.

**Comment by ecmyers** [comment]
Thanks! I tried it again (the new version makes this much easier!), and it's working now. I realized the problem was I thought the full command was

--enable-crt-scanlines, -sc

But I tried it with just "--enable-crt-scanlines" and that did the trick. I don't know what the "-sc" is for, but I guess it doesn't matter. Sorry for the confusion.
