### ISSUE TITLE
Snes mini classic > Cant unpack ramdisk

### ISSUE THREAD

**Issue by Antcr** [ClusterM/hakchi2#633]
Hi All, hope someone can help? I'm trying to flash my UK Snes Mini classic, I've dumped my kernel but when I try to custom flash it, I receive the following error: 'cant unpack ramdisk'. Can someone help explain as to how I resolve this issue?

many thanks

Anthony

**Comment by ClusterM** [comment]
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems

**Comment by Drakonas** [comment]
Since the OP has not responded, I am closing this.
