### ISSUE TITLE
Crashes in windows, and language pre-set to russian

### ISSUE THREAD

**Issue by Arakon** [ClusterM/hakchi2#636]
Whenever I try any SNES connection (upload, kernel flash or retroarch install), I get "hakchi2 has stopped working". This happens with debug and portable version, not even getting a debug output before it crashes. This is with internal release 32, also happened with 30 and 31. I'm running Win 7/64 bit.

Also, config defaults to russian text.. probably should default to english.

`Base directory: D:\hakchi2
Loading config
Starting, version: 2.0.21.32
Loading games
Loading D:\hakchi2\data\nescarts.xml
Loading D:\hakchi2\data\snescarts.xml
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
clovershell connected
[ -d /var/lib/hakchi/firmware/ ] && [ -f /var/lib/hakchi/firmware/*.hsqs ] && echo YES || echo NO # exit code: 0
cat /etc/clover/boardtype # exit code: 0
cat /etc/clover/REGION # exit code: 0
Detected board: dp-shvc
Detected region: EUR
df /dev/nandc | tail -n 1 | awk '{ print $2 " | " $3 " | " $4 }' # exit code: 0
mount | grep /var/lib/clover # exit code: 1
mkdir -p /var/lib/hakchi/rootfs/usr/share/games/ && du -s /var/lib/hakchi/rootfs/usr/share/games/ | awk '{ print $1 }' # exit code: 0
mkdir -p /var/lib/clover/profiles/0/ && du -s /var/lib/clover/profiles/0/ | awk '{ print $1 }' # exit code: 0
NANDC size: 290,6MB, used: 144,1MB, free: 131,5MB
Used by games: 95,4MB
Used by save-states: 2,2MB
Used by other files (mods, configs, etc.): 46,6MB
Available for games: 226,8MB
Saving config
`

**Comment by ClusterM** [comment]
I uploaded it with my config by mistake.
Need to sleep more...

**Comment by Arakon** [comment]
Okay, this appears to be related to overwriting the existing 2.20 version with 2.21b.. when I create a fresh folder, it works.

**Comment by NeroSchiz** [comment]
I just deleted russian in the Language folder and that seemed to work
