### ISSUE TITLE
Is there a way for mapping controllers in built-in emulator?

### ISSUE THREAD

**Issue by Bumblecito** [ClusterM/hakchi2#637]
Hello there !
I'm unable to map my PS3 and PS4 controllers connected through 8bitdo retro receiver, I only can map'em if I install RetroArch and using the SNes core, but I really like the built-in emulator.
Is there or will be a way for maping from Hakchi without installing RetroArch?

Thanks !

**Comment by ClusterM** [comment]
Only to rebuild covercon driver.

**Comment by Bumblecito** [comment]
Thank You !
May I request that? or is it hard?
Sorry I'm noob

**Comment by ClusterM** [comment]
It's very specific task... I can try it later.

**Comment by Bumblecito** [comment]
I would thank You infinitely.

Regards !

**Comment by ajmi982** [comment]
I so want this but think we need a new 8bitdo FW

Sent from my iPhone. Please pardon any spelling or grammar mistakes. 

On Oct 10, 2017, at 1:51 PM, Bumblecito <notifications@github.com> wrote:

Hello there !
I'm unable to map my PS3 and PS4 controllers connected through 8bitdo retro receiver, I only can map'em if I install RetroArch and using the SNes core, but I really like the built-in emulator.
Is there or will be a way for maping from Hakchi without installing RetroArch?

Thanks !

**Comment by Bumblecito** [comment]
I'll reported it to 8bido too, they say maybe they won't update the receiver firmware because they would have to update all their controllers too.
Too bad =(

**Comment by ajmi982** [comment]
When did they say that?!  That's terrible

Sent from my iPhone. Please pardon any spelling or grammar mistakes. 

On Oct 11, 2017, at 6:51 AM, Bumblecito <notifications@github.com> wrote:

I'll reported it to 8bido too, they say maybe they won't update the receiver firmware because they would have to update all their controllers too.
Too bad =(

**Comment by Bumblecito** [comment]
I sent an inbox to 8bitdo, they said:
"Thanks for the feedback.
Will pass on your message to our IT team.
We are currently on holidays. Will resume work on the 9th.
We kindly ask for your patience."

**Comment by ajmi982** [comment]
any update on this? thank you

**Comment by Drakonas** [comment]
This question should have originally been asked of the 8bitdo team. This has nothing to do with Hakchi. Closing.

**Comment by Drakonas** [comment]
Discussion will be left open for those that want an update.
