### ISSUE TITLE
Can't Sync Games

### ISSUE THREAD

**Issue by JoeyAFC** [ClusterM/hakchi2#638]
![image](https://user-images.githubusercontent.com/32683785/31402767-e30b0c02-adee-11e7-9be7-3f70c6ddeafe.png)

Can't get any further than this screen, I click on install driver and all i get is:

Found USB device: "NES Mini" (1F3A:EFE8)
Installing wdi driver with <nesmini.inf> at <usb_driver>

Press Enter to exit this driver installer

What am i doing wrong?

**Comment by dohmygoodness** [comment]
same problem! :/
Windows 10 E 64bit

**Comment by dohmygoodness** [comment]
@JoeyAFC Can you tell me how you fixed it if you did? Thanks!! :)

**Comment by JoeyAFC** [comment]
@dohmygoodness

Kept downloading the latest version and it just worked. Guess there was bugs in the build I had
