### ISSUE TITLE
Demo mode now broken

### ISSUE THREAD

**Issue by szissoucorp** [ClusterM/hakchi2#64]
If you leave the NES Classic idle and let the Demo mode start, after the mario jumping animation it tries to select a game but will endlessly scroll the folders.  Looks like its searching for the original 30 games and can't find them so it just keeps scrolling the folders.

**Comment by ecmyers** [comment]
That's sort of tragic.

**Comment by mlabarca** [comment]
That's weird. Demo mode worked fine for me. Maybe it happens randomly if
the game it's looking for happens to be inside a folder.

**Comment by szissoucorp** [comment]
If you have a ton of roms the home screen is just a bunch of folders, if demo mode starts from here it will just scroll endlessly the folders.  If you are already inside a folder that has one of the original 30 roms and demo mode starts from there, it will just keep selecting that original rom or roms in that particular folder.

**Comment by frostitution** [comment]
It's not really broken - it just can't find/read any of the special demo files that come with the initial 30 games. You can disable the "demo" feature in the settings anyway.

**Comment by ClusterM** [comment]
Yep, it can't find any game with demo. So there is only one way to fix it - create some demos for other games.

**Comment by szissoucorp** [comment]
I like to leave my NES Mini running 24-7 in demo mode on a monitor I have set up.  So if there is a way to add folder logic to the demo mode in the next version that would be great.

**Comment by seanrox** [comment]
Since most NES games already have attract/demo modes built into them, I wonder if they could be activated for games that are added to the original 30? Of course not knowning how Nintendo worked the demo mode into the menu software, I guess it's hard to say, unless someone is already working on figuring it out. Either way it's great that we can add (or remove) games to our units...

**Comment by ClusterM** [comment]
You can create your own demos using new clovershell mod.

March 11, 2017 3:23 AM, "SeanRox"  wrote:
	Since most NES games already have attract/demo modes built into them, I wonder if they could be activated for games that are added to the original 30? Of course not knowning how Nintendo worked the demo mode into the menu software, I guess it's hard to say, unless someone is already working on figuring it out. Either way it's great that we can add (or remove) games to our units...

**Comment by seanrox** [comment]
Thank you @ClusterM for the reply. Time to dig into the FAQ and learn how to create demos.
