### ISSUE TITLE
Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.

### ISSUE THREAD

**Issue by DefKorns** [ClusterM/hakchi2#640]
![image](https://user-images.githubusercontent.com/32590804/31402881-de3ec748-ade6-11e7-80bf-855ed41d66dd.png)

OK, here's whats happening: 

At firts i tried the web_installer update, open 2.21b > uninstall > flash original kernel > flash custom kernel and this error poped-up a few seconds after. 

Went back to 2.20.

Tried the same process with standalone version, same result. But now when i tri to flash the original kernel on 2.21 i get the error again.

Gonna try the debug version now.

**Comment by reverte** [comment]
update to the newer version

**Comment by reverte** [comment]
https://github.com/ClusterM/hakchi2/issues/634

**Comment by DefKorns** [comment]
i was able to install custom flash with v2.21b (internal version 2.0.21.32) but still have errors on the debug while flashing:

Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWUSBResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWUSBResponse.cs:line 22
   at com.clusterrr.FelLib.Fel.FelRead(UInt32 length) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 241
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 274
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 16 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Error: Exception of type 'com.clusterrr.FelLib.FelParseException' was thrown.   at com.clusterrr.FelLib.AWFELVerifyDeviceResponse..ctor(Byte[] data) in D:\Projects\C#\hakchi2\FelLib\AWFELVerifyDeviceResponse.cs:line 26
   at com.clusterrr.FelLib.Fel.VerifyDevice() in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 275
   at com.clusterrr.FelLib.Fel.Open(UInt16 vid, UInt16 pid) in D:\Projects\C#\hakchi2\FelLib\Fel.cs:line 155
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64

**Comment by Drakonas** [comment]
This has been fixed by Cluster.
