### ISSUE TITLE
Does installing Retroarch completely replaces the build in emulator?

### ISSUE THREAD

**Issue by JPVDO** [ClusterM/hakchi2#644]
The new hackchi version 2.21 has a list to automaticly detect "problem" roms leaving you with the option to use retroarch instead.

Does this mean that ALL the roms on the SNES mini will load in Retroarch? Or only the ones that are reported to have problems?

Is it posible to configure it to function like this :

Stock plus "good"roms --> Build in emulator.
"Problem" roms --> Retroarch?

**Comment by Arakon** [comment]
That's how it already functions. ONLY if --retroarch is added to the command line of a rom will it load in retroarch.

**Comment by JPVDO** [comment]
Thank you for you awnser! 

Do i still have to add -retroarch to the commandline in this version of Hakchi?
And do i still need to install Retroarch separately? 

I am trying to play street fighter alpha 2 and my commandline has changed to:

/bin/snes /usr/share/games/CLV-U-XIAVZ/Street_Fighter_Alpha_2_(E)_[!].sfrom.7z

Am i correct that no emulator has been defined?

Other games look like this:

/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-YWUYC/Super_Adventure_Island_(Europe).sfrom.7z --volume 100 -rollback-snapshot-period 600
