### ISSUE TITLE
After using the new version of hackchi the button combination to reset your console doesn't work anymore.

### ISSUE THREAD

**Issue by JPVDO** [ClusterM/hakchi2#647]
After using the new version of hackchi the button combination to reset your console doesn't work anymore.

Can you please fix this?

**Comment by Asure** [comment]
There's a a new default combination with down+select enabled by default it seems.
Go to Settings -> Controller Hacks -> Change the button combination.
There you can restore your settings solving this problem.
Also: Click "Save settings to snes mini now option." offcourse :)
