### ISSUE TITLE
Untoggling the 'Original Games' option a few times will demand to re-flash custom kernel

### ISSUE THREAD

**Issue by Asure** [ClusterM/hakchi2#648]
Reproduce:
- Uninstall hakchi2 .
- Flash back the original kernel.
- Ensure you are on a clean system w/ only original games listed
- Install custom kernel, wait for the process to finish, and light to turn green.
- Check/Uncheck the 'Original Games' in the list at least 3 times. Leave it 'checked on'.
- I have about 47 games listed in my list + Original Games at the top.
- Now click 'Synchronize'
- Error: Unknown CRC message appears and you can't sync / 'need to flash custom kernel for your old games'
- Expected: Sync option should complete normally.

**Comment by Drakonas** [comment]
Have you tried uninstalling hakchi2, flashing original kernel AND then performing a factory reset from the main menu of the SNESC? WARNING THIS WILL ERASE ALL SAVES, but it is necessary to remove leftover files from bad/old hakchi installs in dire circumstances like this.

**Comment by Drakonas** [comment]
Closing this as there has been no response from the OP.
