### ISSUE TITLE
I keep gettin a c8 error when i shut down my SNES mini

### ISSUE THREAD

**Issue by NateKush86** [ClusterM/hakchi2#650]
I upgraded from hakchi2.20 to 2.21b
I have the originals uninstalled with 116 roms installed.
I have retroarch installed along with the snes core for problem games.
Now all the games i have played so far work without fail, but when shutting down my snes i get a C8 error.
Is there something i can do to correct this error? any help would be appreciated.

**Comment by zimmertr** [comment]
Do you consistently get a c8 every time you shut down? I've gotten it as well, but only once randomly.

**Comment by NateKush86** [comment]
yeah every time i shut down i get one

**Comment by K4Z1** [comment]
max. 59 or 60 roms in a folder allowed. (I use max. 30 roms like it said somewhere in a FAQ)

**Comment by ClusterM** [comment]
How many games on screen you have?

**Comment by brian91292** [comment]
I made a really ghetto shell script to kind of detect situations when this has occurred and just shutdown the console anyway, I could release it if enough people care.

The script doesn't prevent the c8, it just shuts down your console a few seconds after the you encounter the error.

**Comment by NateKush86** [comment]
I guess it could be that i disabled pages and folders than. Too much on one screen?

**Comment by harmonoff** [comment]
hey Brian, I plan to leave my current set-up as is (with ~100 games on the main menu.) 
Can you please somehow submit the script to us (or me) so we don't have to keep resetting the console?  It's pretty annoying/worrying to see the error every time and otherwise I love my SNES classic... appreciate your work on this, cheers!

**Comment by brian91292** [comment]
https://www.dropbox.com/s/mjcv1efms01gu2g/S92crash-fix.sh?dl=0

Like I said, this is a really ghetto script, and I wouldn't recommend it for basic users. Just copy it into /etc/init.d, when your console gets C8 error should turn off a second or two later. If you need to.uninstall it just FTP in and delete the file.

**Comment by harmonoff** [comment]
Wow, thank you so much! Forgive my ignorance / lack of coding knowledge,
although I am very knowledge about computers in general so I should be able
to figure out with some guidance.  Where is this /etc/init.d directory you
speak of?  Is it on the actual SNES classic?  Please advise easiest way for
a PC user to get to the folder to drop your custom script in!  Thank you
again & I appreciate your help..

**Comment by brian91292** [comment]
Yeah just enable the Ftp server in hakchi then use an Ftp client to browse to that directory (I prefer flashfxp). Then it's just drag and drop.

**Comment by Drakonas** [comment]
@NateKush86 how much space do you have free on your SNES. You really want to have about half or more free to save room for saves. Also C8's tend to happen when the storage gets more full.

**Comment by Drakonas** [comment]
Closing this issue because of no response from the OP.

**Comment by bdombek** [comment]
Hey Brian, You're dropbox link is no longer working, I'd really like to use the script on my classic
