### ISSUE TITLE
Minor typo in Italian translation

### ISSUE THREAD

**Issue by alessiocali** [ClusterM/hakchi2#651]
The italian entry for the original games is "xx giochi originali" whereas it should be just "Giochi originali" to be consistent with the english translation. I know it's silly but that 'xx' bugs me out everytime I browse over the original game folder ^^"

**Comment by ClusterM** [comment]
It's not type, I can't contact Italian translator to update translation. Can/want you help?

**Comment by alessiocali** [comment]
Sure I'll give it a shot. I'll also check if there are some other things left behind.

**Comment by Drakonas** [comment]
This has been fixed.
