### ISSUE TITLE
tar error (doesn't find directory) while syncing games on nes mini

### ISSUE THREAD

**Issue by msx2k** [ClusterM/hakchi2#652]
Hi, I'm trying to sync my games after I experienced #634 (I'm on 2.0.21.32 now): the custom kernel installs perfectly now, however I get this error when I try to sync my games:

``shell command "tar -xvC /var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi" returned exit code 1: tar: can't change directory to ' /var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi': No such file or directory
``
I checked via telnet and there's nothing inside that /games directory. 

UPDATE:
I also tried to uninstall, flash original kernel and reflesh custom kernel again, but it didn't solve the problem.

![screenshot](https://user-images.githubusercontent.com/25409407/31408908-55f69ff4-ae0a-11e7-8056-ba70e35092c3.PNG)

**Comment by andyderuyter** [comment]
Same here. Don't know if it is of any relevance, but I have a EURO nes mini

EDIT:
`/var/lib/hakchi/rootfs/usr/share/games/` is empty in FTP.

EDIT 2:
Creating the folder `nes` inside `/var/lib/hakchi/rootfs/usr/share/games/` and the folder `kachikachi` inside `/var/lib/hakchi/rootfs/usr/share/games/nes/` through FTP fixed the error, but nes only boots with a black screen. Connection with Hakchi and FTP is still possible.

EDIT 3:
Removing the folder `nes` from `/var/lib/hakchi/rootfs/usr/share/games/` fixes black screen, but results back to the error from shell command.

**Comment by msx2k** [comment]
I’m on a EURO nes as well; hackchi2 used used to work perfectly on it until yesterday.

**Comment by stevenEno** [comment]
I am on a US nes and seeing the same error.  Tried it for the first time yesterday.

**Comment by KMFDManic** [comment]
I think you may possibly have wrong console type selected in hakchi. This error is basically trying to find an nesc path.

**Comment by stevenEno** [comment]
We are installing on an NES Classic.

**Comment by kaleneet** [comment]
For me an EURO NES with the same problem, first time hakchi2 on nes

**Comment by KMFDManic** [comment]
Did you try making sure u selected nes classic as system in selector?  That is an error related to snes classic trying to flash with non-existent nes classic command lines. I would suggest making sure nes classic is chosen, then uninstall hakchi, then flash original, then custom kernel.

**Comment by stevenEno** [comment]
Yes, I ran through the install twice selecting NES Classic both times.

**Comment by KMFDManic** [comment]
I can test on my nes classic when I am home.  But, no issues on snesc.

**Comment by KMFDManic** [comment]
I can test on my nesc when I get home shortly.  I have hakchi that is not released yet, and can test that one too.

**Comment by KMFDManic** [comment]
I always compile the wip hakchi, to test out changes and various perimeters, etc.  I only recommend this course of action for those who understand the responsibilities and inherent risks of not being officially released, with his blessing.

**Comment by madmonkey1907** [comment]
open telnet and execute mkdir -p /var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi
then it'll work
or wait for update

**Comment by andyderuyter** [comment]
@madmonkey1907 How is that different than creating the folders in FTP?

**Comment by madmonkey1907** [comment]
it is not. just easier.
if you have black screen, add or remove some games afterwards.
if you still have black screen after that, install/uninstall some hmod, or perform memboot(should be in latest version I think?)

**Comment by andyderuyter** [comment]
Started from scratch.
- Selected NES Classic Mini as console type
- Installed kernel: no problem with that
- Synced game: error
- Created folders: no error, but black screen
- Synced another game: no error, still a black screen
- Installed 'No thumbnails hmod': no error, still a black screen
- Removed own games (only originals left): no error, still a black screen
- Uninstalled 'No thumbnails hmod': no error, still a black screen

@madmonkey1907 Regarding memboot. Is this the option under 'Kernel' -> ''Boot patched kernel from RAM"? This won't brick my nes?

EDIT:

I've done the 'Boot patched kernel from RAM': no error, still a black screen

**Comment by madmonkey1907** [comment]
yes, it is. it will not brick your console.

try this
select NES Classic Mini as console type
install/uninstall some hmod OR memboot
create folders, do
mkdir -p /usr/share/games/nes/kachikachi
just in case there is an error in filename somewhere
unselect ALL original games
add at least 12 non-original games
sync

then check if it's still black screen
if it is, backup your saves, telnet execute
~~hakchi mod_uninstall~~ rm -rf /var/lib/hakchi
this will delete all your data(shouldn't delete saves, but just in case)
and start from step1

**Comment by KMFDManic** [comment]
That is how I initially bypassed the error to run retroarch last week, with ftp/telnet.  I am unaffected by the error now.  But, some appear to be.  Cluster will patch what needs patched, need not worry.  Madmonkey stated the same solution I used.  It worked great.

**Comment by andyderuyter** [comment]
@madmonkey1907 & @KMFDManic thanks for all your help and suggestions, but I think I'll be using 2.20 for my NES again. More reading and trying to get the newest version of Hakchi to play nice, instead of playing the damn games ;)

**Comment by KMFDManic** [comment]
@andyderuyter, don't fret, it should be an easy hot fix.

**Comment by andyderuyter** [comment]
@KMFDManic Hey, I'm cool with everything that happens :) I'm glad that I can play games on these little machines (have both nes and snes), and everyone involved is doing what they can in their spare time. So, no complains from my side...

**Comment by KMFDManic** [comment]
My access denied video should offer a temporary fix, too.  Deleting temp folder.  But, a proper patch is gonna happen, regardless.

**Comment by mattamsterdam** [comment]
same prompt when syncing games to NES as posted by msx2k  "code 1: tar: can't change directory to...." -

![hakchi2 error nes](https://user-images.githubusercontent.com/32719376/31466103-5470bd1e-aed6-11e7-9262-00bf8a209a79.jpg)

**Comment by stevenEno** [comment]
Thank you everyone for all of your help.  I tried all the steps around creating the directory, deleting the var/lib/hakchi directory and everything in between, but I am still just getting a black screen.  I may just work with a previous version as well until there is a patch.

**Comment by Wookie2000** [comment]
Hi - I am having the exact same error on a Euro NES mini. Tried all the steps with no fix. Which older version of Hakchi should I use? 

I tried 2.21 and 2.17 with same errors.

**Comment by kaleneet** [comment]
i had the same error before, now I'm using the new version 2.21c and got this error, is it related?

![error](https://user-images.githubusercontent.com/32710318/31492194-549c02fc-af4a-11e7-86e4-0a82e0f38861.jpg)

**Comment by ClusterM** [comment]
Fixed.

**Comment by jlloyd0306** [comment]
Still getting it here using hakchi v2.21b

**Comment by Drakonas** [comment]
@jlloyd0306 get a fresh hakchi2 directory and request help on reddit. Nobody else is having this problem anymore, so you probably have a corrupted install. https://www.reddit.com/r/miniSNESmods

**Comment by Slywars** [comment]
Hi,
Please excuse my bad english.
I am a new user with this software, I fear I did something wrong because I now have this error 
![image](https://user-images.githubusercontent.com/35539546/35060304-0c157098-fb8c-11e7-9a11-5f0277433932.png) when I try to add new games, I use in the first time version 2.20 and when I tested version 2.21d this error appeared to me, I check on this forum hoping to find a solution to my problem, I would like if someone could send me the link explaining in detail how to solve my problem.
Thanks verry much

**Comment by KMFDManic** [comment]
@Slywars SNESC?
