### ISSUE TITLE
MegaMan X2 slowdown and distorted audio

### ISSUE THREAD

**Issue by Jamieasy** [ClusterM/hakchi2#653]
Any fix for MegaMan X2 using stock emulation?!

**Comment by Arakon** [comment]
The stock emulator is closed source and can't be modified to fix specific games.

**Comment by 03bgood** [comment]
They better fix the issues with MMX2.

**Comment by ibuprofen6** [comment]
I haven't had any issues with mega man x2. Had the frame rate issue at times but that is just mega man. I still haven't upgraded to fill release of hakchi yet however.

**Comment by 03bgood** [comment]
Framerate issues are still present in both the original cartridge releases and Virtual Console re-releases.

**Comment by Jamieasy** [comment]
Thanks guys

**Comment by ghost** [comment]
the only problem comming from missing compatibility is the sound glitches in specific portions of the game

**Comment by Mime64** [comment]
Try adding -no-lowlatency to the end of the command line for that game and see if it helps.

**Comment by x925** [comment]
if you haven't fixed this yet, there is a fix but it doesn't use the stock emulation, you need to install retroarch as well as snes9x2010 and change the command line to /bin/snes /usr/share/games/CLV-U-CWMNT/Mega_Man_X_2.sfrom.7z  i just did this and it seems to have gotten rid of all of the lag, though rewind does not work at all but the save states do

**Comment by Drakonas** [comment]
actually there has been a fix for the distorted audio problem, similar to the Street Fighter Alpha 2 patch. https://a.safe.moe/VERWo.zip

**Comment by x925** [comment]
i tried that and while it fixed the audio the lag seemed to persist in this game

**Comment by Drakonas** [comment]
The lag is mostly due to canoe, not hakchi I believe, but more testing is needed I suppose.

**Comment by Drakonas** [comment]
This has been fixed as of 2.21f. See #921 for details.
