### ISSUE TITLE
Hakchi 2.21b Produce Flicker

### ISSUE THREAD

**Issue by DanyMode8** [ClusterM/hakchi2#655]
Hello, i noticed when i play some games or stay in the home menu, sometimes the Screen is Flickering, i don´t know what is the reason, before with others versions this no happens.
Hope you can fix it ClusterM please, and GREAT JOB
Saludos desde CHILE :D

**Comment by DanyMode8** [comment]
i noticed it after install Retroarch and snes 2010

**Comment by ClusterM** [comment]
Are you sure it's because of hakchi? Try to uninstall it and reproduce please.

**Comment by DanyMode8** [comment]
ClusterM i Discover that is when i install retroarch, after that, produce little flicker sometimes in some games or in main menu (select games), if i no install retroarch and snes 9x 2010 no flicker.
Sorry for my inglish, hope you understand Thanks.
PD: The unique form that i can install retroarch and snes 9x is copy the archives from retroarch_clover.09 and paste in user_mods, when i drag the zip archive (retroarch_with_cores)  and put on the hakchi screen appear a denied signal.

**Comment by Drakonas** [comment]
Is this still an issue @DanyMode8 ?

**Comment by DanyMode8** [comment]
After i had install the last version no problem, Everything is Ok. Thanks for your Support and Awesome Job
