### ISSUE TITLE
Games Not Working

### ISSUE THREAD

**Issue by warsavior86** [ClusterM/hakchi2#656]
1.) Chrono Trigger Flames of Eternity - Game gets stuck on intro screen dialogue...The screen is black and am not able to get past the screen regardless of any buttons pushed.
2.) Star Ocean - Black screen when trying to run game...end up getting a c7 error when resetting.
3.) Dragon Ball Z - Hyper Dimension...same issue as Star Ocean.
4.) Dragon Quest 3 - Same issue as Star Ocean.

**Comment by zimmertr** [comment]
Have you tried RetroArch? How about the existing patches for some of those games? If not, why are you making this post? Have you read any of the existing resources about this project? Or are you just in the habit of jumping blindly into alpha software without reading anything?

**Comment by warsavior86** [comment]
Thanks for your mature response. I'm sorry we are not all pros like you when testing out a patch release. For those having this same issue though, using RetroArch to solved this problem.

**Comment by zimmertr** [comment]
Searching an issue board for similar issues before posting is something that more than just _pros_ can do. In fact, it is encouraged on virtually every website in existence. 

Here: https://github.com/ClusterM/hakchi2/issues/582

https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/htmlview?sle=true#gid=2014317767

And that's just a single mature issue on GitHub. Feel free to search Google or GitHub yourself and you'll see a few dozen other similar questions. 

Lastly: https://stackoverflow.com/help/how-to-ask
