### ISSUE TITLE
Please fix compatibility issues!

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#658]
The game compatibility for the SNES Classic is horrible! Lots of games still don't run or do run but are very problematic and these are the ones I'm talking about:

Goof Troop: C7/C8 error
Illusion of Gaia: No sound and black screen after pressing start
ActRaiser 2: Black screen after Enix logo
Championship Pool: C7/C8 error after choosing which mode to play
Street Fighter Alpha 2: Corrupt graphics
Super Street Fighter II: The New Challengers: C7/C8 error
Robotrek: Hangs on Enix logo
Terranigma: Haven't tested this one but the region lockout prevents you from playing it
SimCity 2000: Sound issues
Wario's Woods: Sound issues
BS Zelda (Quest 1): C8 error
BS Zelda (Quest 2): C8 error
The Legend of Zelda: Goddess of Wisdom (ROM Hack): C8 error

**Comment by zimmertr** [comment]
Have you tried RetroArch? How about the existing patches for some of those games? If not, why are you making this post? Have you read any of the existing resources about this project? Or are you just in the habit of jumping blindly into alpha software without reading anything?

**Comment by 03bgood** [comment]
How good is RetroArch?

**Comment by zimmertr** [comment]
Okay, it appears you haven't. This is not a valid issue then. Please close this issue and ask your question in a support community like Reddit instead of a software issue board.

**Comment by ghost** [comment]
@zimmertr Have you tried Burger King? If not, why are you complaining about Mc Donalds giving you a cheeseburger without cheese?!

Seriously, some people want to use the integrated emulator and just wish that compatibility is improved.

Goof Troop for example already has an easy fix. Just open the UNCOMPRESSED rom with any hex editor and change the 15 in the screenshot to a 14. https://i.imgur.com/nILxmWK.png

**Comment by 03bgood** [comment]
The RetroArch one isn't that great. The native emulator runs Kirby's Dream Land 3 perfectly while the RetroArch one has slowdown issues. RetroArch really isn't worth it.

**Comment by pilotS1** [comment]
I have  Super Street Fighter II: The New Challengers running I can post proof :).

All Soundissues are related to PAL Roms dont use pal roms the sound is out of sync because of the 50hz and glitches only use US or J roms.

Ah and by the way stop complaining. Its free. If you want better emulation get a retropie and be done with.

Most of Enix games wont play like Illusion of Gaia I havent figured out why though.

**Comment by Dremarozt** [comment]
Can you elaborate on super street fighter 2? I am trying with a USA Rom and it is not working

**Comment by 03bgood** [comment]
I get a C8 error and Alpha 2 shows up with severe corrupted graphics, almost like NES game would.

**Comment by Dremarozt** [comment]
Also yes, I find this compatibility issues troublesome, I would love they get resolved as I do not really like using RetroArch

**Comment by 03bgood** [comment]
I don't understand why the NES Classic had better compatibility but the SNES Classic doesn't. Nintendo put less effort into the SNESC, than they did with the NESC. The only few games I couldn't get to run were a Batman game and either Rad Racer 2 or R.C. Pro-Am 2. The rest ran great. It's almost if it Nintendo did this on purpose so people would stop pirating games to the SNESC. I hope not.

**Comment by pilotS1** [comment]
You have to use a different romset for street fighter. Here is proof. 
![img_20171011_001005](https://user-images.githubusercontent.com/32688488/31413310-e5c34070-ae18-11e7-90f2-724b9aca18f3.jpg)

**Comment by zimmertr** [comment]
Thumbs down me all you want. This post is redundant and unnecessary. And OPs question could have been resolved with 3-4 minutes of research. There are about 5000 similar issues on this project already. Any other community (cough SO) would be flaming him for not using the search function by now. 

Search before you post........... https://github.com/ClusterM/hakchi2/issues/582

https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/edit#gid=2014317767

Anyway I don't eat BK or MD. I'm a vegetarian. And health conscious.

**Comment by ajmi982** [comment]
Fix it urself. So ungrateful. 

Sent from my iPhone. Please pardon any spelling or grammar mistakes. 

On Oct 10, 2017, at 5:52 PM, Thomas (TJ) Zimmerman <notifications@github.com> wrote:

Have you tried RetroArch? If not, why are you making this post?
