### ISSUE TITLE
Retroarch

### ISSUE THREAD

**Issue by Galokz** [ClusterM/hakchi2#659]
I'm trying to get Top Gear 3000 working. (My favorite game.) It asks me if I want to use a 3rd party emulator to run it. I click yes. When I try to run it, it just goes back to the menu. Any help?

**Comment by K4Z1** [comment]
I had the same issue with roms that were in .fig format. I just renamed them to .smc and they worked.

**Comment by Galokz** [comment]
Mine was already named to .smc

**Comment by ihadmail** [comment]
I had a similar problem with ALL games that needed retroarch using hakchi 2.20 and retroarch_with_cores 0.9b

I switched to retroarch_with_cores 0.8 and solved my problems. 

Out of 75 games that were known to not open in SNES without retroarch, only 4 needed the command line modified to manually direct to retroarch using the "--retroarch" code.

**Comment by Drakonas** [comment]
@Galokz Have you actually installed the retroarch module along with the SNES9x2010 core? Or were you trying to run retroarch without having retroarch installed on the Snes Classic...

**Comment by Drakonas** [comment]
Closing this as there has been no response for 3 months.
