### ISSUE TITLE
Source Array Not Long Enough

### ISSUE THREAD

**Issue by Spottedfeather** [ClusterM/hakchi2#66]
I don't know what this means, but I just tried to add a game, Gilligan's Island, to Hakchi2 2.11, and got this...
"Source array was not long enough. Check srcIndex and length, and the array's lower bounds"

I was able to add the game after extracting it from the zip file, but just thought I should bring this up in case someone else was having the same trouble.

**Comment by ClusterM** [comment]
I think that it's already fixed. If you will meet this error again:
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems...
