### ISSUE TITLE
USB errors???

### ISSUE THREAD

**Issue by joetheuseless** [ClusterM/hakchi2#660]
latest build disabled driver enforcement tried using several USB cables disabled Windows 10 virus security disabled UAC installed the driver with Zadig now its showing up in device manager but same problem persists USB error's when flashing the custom kernel !! i tried to install the driver but it says No nes mini found sorry even though i ripped my kernel first time 

Using Ryzen 1700 and Windows 10

Whats up

**Comment by wangyung** [comment]
if you used 2.21b, you can try 2.20.
I got the same problem on 2.21b, but 2.20 works fine

**Comment by ClusterM** [comment]
Which error, lol?

**Comment by nicholemattera** [comment]
Duplicate of #620 

There is already an issue created for this. It seems to have something to do with Ryzen based PCs. When trying to install the custom kernel or dumping the kernel it produces "Can't write to USB" errors. I also recieved an IO error once that made the entire app not respond.

**Comment by Drakonas** [comment]
Duplicate of #620. Closing.
