### ISSUE TITLE
SNES Filters Hack cause C7 Error after applying command line.

### ISSUE THREAD

**Issue by Jonny0r** [ClusterM/hakchi2#661]
Hello,

i dont know if im the only one, but some people i know from US already got it working :(

1) Hakchi 2.21b installed, clean dump.
2) Space Mod, RetroArch, Snes9x, Snes Filter mods installed.
3) Add "--no-scanlines" or "--smooth43" to the Global Command Line, checked that im in CRT / 4:3 view.
4) Start the Game "C7" Error.
5) Remove the Global Command Line Again, everything works fine again.

6) Games with RetroArch for sure work well, but the Canoe "all" cause C7.

Does someone has an idea?

**Comment by drunkenchrono** [comment]
The Overmounting did not work correctly :)

root@CLOVER:/var/lib/hakchi/rootfs/usr/bin# ls -al
drwxr-xr-x    4 root     root          4096 Jan  1 00:00 ..
-rwxr-xr-x    1 root     root          2443 Jan  1 00:00 canoe-custom-filters
-rwxr-xr-x    1 root     root          2443 Jan  1 00:12 clover-canoe-shvc
-rwxr-xr-x    1 root     root          2262 Oct  7  2017 clover-canoe-shvc.old


i backup clover-canoe-shvc and rename  canoe-custom-filters to clover-canoe-shvc should fix this

ClusterM should fix then the overmounting

**Comment by ClusterM** [comment]
Are you using latest RetroArch mod? It can conflict with SNES Filters Hack because it overmounts clover-canoe-shvc too. Try to update to latest RetroArch.

**Comment by Jonny0r** [comment]
@drunkenchrono @ClusterM

Thanks for your support, it works now very well. The issue was i copied the new "RetroArch Files" to the mod folder and overwrite the old files but hakchi did not regonize this and still use the 0.8 till you drag and drop the latest files.

so with RetroArch 0.9C its working without any Problem, only older (perhaps sub 0.9) cause troube :)
