### ISSUE TITLE
Using database for RetroArch

### ISSUE THREAD

**Issue by Dremarozt** [ClusterM/hakchi2#664]
I have not been able to use this feature on the version 2.21b that says hakchi will ask me to use retroarch via a database, do anyone knows how to use it?

**Comment by ihadmail** [comment]
From the screenshots I've seen you simply add the games to your list and hakchi will give you the popup if the native SNES emulator won't run it.

**Comment by Dremarozt** [comment]
ah, it is on hakchi I get it now I thought it was going to be on the system itself and since I already had added this games this popup was not appearing

**Comment by DecanFrost** [comment]
i added in a few games that dont run on built in emulator and never got the prompt to select retroarch   and yes im on 2.21b
