### ISSUE TITLE
Access to the path 'ash' is denied. 

### ISSUE THREAD

**Issue by kakauran** [ClusterM/hakchi2#665]
Cannot install custom kernel as I continually get an access to path is denied error.

Access to the path 'ash' is denied.   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive)
   at com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 507
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 261

**Comment by ClusterM** [comment]
Which version (internal number, in about box)?

**Comment by SMSProv** [comment]
Hello I am having the same exact issue. Follow the instructions to the tee. To answer your question @ClusterM, 2.0.21.32

**Comment by SMSProv** [comment]
Just in case, I tried version 2.0.20.15 as well. Same issue.

**Comment by ClusterM** [comment]
Is is portable or web-install version? Can you reproduce this problem on debug version?

**Comment by SMSProv** [comment]
Hey @ClusterM so far I have tried both, web-install and portable on 2.0.21.32 and portable on 2.0.20.15.

Let me try debug version on 2.0.21.32, and report back.

**Comment by kakauran** [comment]
I have tried all three versions. Here is the debug log.
[debuglog.txt](https://github.com/ClusterM/hakchi2/files/1373876/debuglog.txt)

**Comment by SMSProv** [comment]
[Debug.txt](https://github.com/ClusterM/hakchi2/files/1373907/Debug.txt)
So ended up with the same issue.. got a simmer of hope, but errored out two different ways, eventually ended up with the same error (Access to the path 'ash' is denied.)

Attached is the two errors I got this time before getting the denied access 'ash' error.

**Comment by SMSProv** [comment]
I tried an a different computer entirely, and all is working well. Interesting...same SNES system

**Comment by therourke** [comment]
I had a similar problem: 'access to path rivercityransom.nes is denied'. I had to go back to rc3 of hackchi to get anything to work. Then I tried the above and changed to a different user in Windows. Everything worked again. What happened? I can't find mention of rivercityransom in any file, or even in regedit. I deleted all versions of this file everywhere.

**Comment by madmonkey1907** [comment]
sounds suspiciously like you guys are using some garbage av product.

**Comment by therourke** [comment]
I am on a Lenovo x220 laptop with Windows 7. I'm using the same software as all of y'alls. Don't know what the garbage refers to.

**Comment by madmonkey1907** [comment]
anti-virus. those with the problem, which av do you have installed, if any?

**Comment by therourke** [comment]
Haaa. I see...

I don't use any anti-virus, except windows built in occasionally. Why would that create a popup in hakchi?

I need to run the debug version on my machine, but can't do that right now. Will report back

**Comment by kakauran** [comment]
i don't have antivirus either and turned windows defender off while trying this.

**Comment by madmonkey1907** [comment]
I summon @KMFDManic He mentioned he knows what's causing this.

**Comment by therourke** [comment]
Ironically... I just tried the debug version.... and it worked fine :-) so nothing to debug. But the problem remains with other versions

**Comment by KMFDManic** [comment]
Hello, @madmonkey1907, Correct, this video contains the fix.  And, @therourke, your issue still exists til you follow my video.  Normal Hakchi2 will remain broken.  Here is the fix...

https://youtu.be/mGooTybpodM

**Comment by KMFDManic** [comment]
@kakauran, my video will fix your problem.  It is merely a false positive that needs cleaned up.

**Comment by therourke** [comment]
That sorted it! Thanks @KMFDManic. That pesky temp folder was the problem

**Comment by KMFDManic** [comment]
Glad it helped:)  I helped many with this trivial issue for years.
