### ISSUE TITLE
BAD Patching And Slowdown Tumbnails 

### ISSUE THREAD

**Issue by THE-PBV** [ClusterM/hakchi2#666]
The patches are BAD  Like lucky luke.
in the top of the screen flickering.
If i patch it with luna IPS  It works perfect.

And the Remove_tumbnails are  not FIXED AND SLOWDOWN

**Comment by brian91292** [comment]
You need to uninstall then reinstall the remove_thumbnails module. Top of the screen flickering? Don't even know what you're talking about.

**Comment by ClusterM** [comment]
There are much more glitches without patch...
