### ISSUE TITLE
MD5 Error

### ISSUE THREAD

**Issue by dreadyman** [ClusterM/hakchi2#667]
![grafik](https://user-images.githubusercontent.com/32687481/31413612-6d56c100-ae1a-11e7-94ea-1ede59173e09.png)

What should i do now?

**Comment by ihadmail** [comment]
This error is due to you not having the stock kernel on the SNES. Click "Ja" and continue.

**Comment by dreadyman** [comment]
Thank You!

**Comment by ClusterM** [comment]
It's not error, just warning. And it's OK if you have already flashed custom kernel.

**Comment by dreadyman** [comment]
Everything worked perfect :)

**Comment by dreadyman** [comment]
Thanks again.
