### ISSUE TITLE
[SNESC] Random reboots with 8bitdo retro receiver

### ISSUE THREAD

**Issue by hoderer** [ClusterM/hakchi2#668]
Looks like there is a power related issue with the 8bitdo retro receiver. I get random reboots/freezes when using them both. Is anyone out there who can confirm this? It's way worse when using retroarch (n64 for example). I already tried different power supplies / cables. I tracked it down to the retro receiver by using the original cable-gamepads. Everything's fine when using them. Not sure if this is the right place for this issue. Most likely 8bitdo are the only ones who could fix that, but since I'm not a programmer, maybe there is a chance to get it fixed by cluster. Thanks for looking into this!

**Comment by adamcarter1** [comment]
Did you update the firmware on the retro recievers?

**Comment by Bumblecito** [comment]
I'm using both receivers and never got a reboot.
Let me try with n64 core later and I'll report again.
How often does it happen?

**Comment by hoderer** [comment]
@Bumblecito: Thank you VERY much for this! When playing 2 player Mario Kart 64 (which - by the way - runs quite nicely) I can't finish even one grand prix race (150cc). The plugin is the glupen64. You have to remap the controllers in the retroarch menu to get it working. Maybe I have to find a working power cable / adapter combination, since there are HUGE differences. Can't wait for your test results.

How to map the controller in retroarch (especially for glupen64):
just go the main menu in retroarch - settings - input - input user 1 binds
scroll down to user 1 control stick x and youll see 4 parameters relating to the analog stick, and just follow the below settings. User 1 Control Stick X - Right D-Pad (should read 12) User 1 Control Stick X - Left D-Pad (should read 11) User 1 Control Stick Y - Down D-Pad (should read 14) User 1 Control Stick Y - Up D-Pad (should read 13). Same with buttons and user 2 binds for 2nd player.

@adamcarter1: Of course I updated to firmware v1.07 (about 1 minute (!) after it appeared on their site on sept., 30th -  couldn't wait for it).

**Comment by Bumblecito** [comment]
Well I've been testing all week and only had one reboot.
Tried with Mario Kart with retroarch 1.0 and hakchi 2.21d

**Comment by Drakonas** [comment]
I am using two 8bitdo retro receivers with no issues. Make sure you are using a usb port that is providing enough power. I've had issues when not providing enough power to the SNES classic.
