### ISSUE TITLE
Game Genie Code Issue Contra

### ISSUE THREAD

**Issue by AIRGHOST77** [ClusterM/hakchi2#67]
when using "Start With Infinite Lives  SLAIUZ" and "Keep Weapons After Losing A Life  GXIIUX" if you pick up the F (Flame Gun) upgrade it automatically resets your game and has Error code C7.

**Comment by graykimbrough** [comment]
I am still getting Error code C7 when using these two codes with Contra (and using version 2.13e). It seems to happen at times other than when I pick up the flame gun, but I will keep looking.
