### ISSUE TITLE
Flashing custom kernel resuslts in a bootloop

### ISSUE THREAD

**Issue by Dedwan** [ClusterM/hakchi2#670]
I can't seem to make the hack work.
Everytime I flash the custom kernel, the SNES classic goes into a bootloop and even shut down itself (even if the operation seems to go smoothly).
I need to flash back to factory kernel, but even this way I often need to reflash it because the first (or the second) time the problem doesn't solve. I've tried to switch both the cable and the usb port, but I'm back to square one.

**Comment by ClusterM** [comment]
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems

**Comment by Drakonas** [comment]
Since the OP has not responded I am closing this.
