### ISSUE TITLE
Total Space reporting differently

### ISSUE THREAD

**Issue by DecanFrost** [ClusterM/hakchi2#671]
Flashed back to stock and then flashed custom using Hakchi2 2.21

if I run Hakchi2 2.20 it reports total Space 252mb
if I run Hakchi2 2.21 it reports total Space 232mb

Im not sure why that is  ... so what one is right..  

Im going to flash back to stock and flash custom using 2.20 and then report back what each version reports as total space

**Comment by brian91292** [comment]
Not an issue, more space was reserved in the newer version (30MB instead of 10MB). Have to ask @ClusterM the exact reason for this.

**Comment by K4Z1** [comment]
My Hakchi2.20 said 201,5MB... I uninstalled custom, flashed original again, and then custom again with few original games and 70 other games. Also removed unused saves in the save-state manager... 201,7MB, why is that?
I would solder some USB chip to that if it worked haha....

**Comment by ClusterM** [comment]
More space was reserved in the newer version (30MB instead of 10MB) because save-states on SNES Mini are huge.
You can install "extra_space" mod to move save-states to other partition, reserved amount of space will be reduced to 5MB.

**Comment by ClusterM** [comment]
Also note that original games are not taking space anymore, so actually you can store **more** games now.
