### ISSUE TITLE
MD5 Checksum

### ISSUE THREAD

**Issue by CoolK92** [ClusterM/hakchi2#673]
What to do now ?

![unbenajhkkjhnnt](https://user-images.githubusercontent.com/32656145/31416605-82225616-ae2a-11e7-9da5-52f892052122.jpg)

**Comment by gingerbeardman** [comment]
Try dumping again to be sure.

**Comment by CoolK92** [comment]
Dumped again... same Message.

I'll flash original Kernel, plug it to the TV to check if everything is fine and then flash custom Kernel.

**Comment by ClusterM** [comment]
Check FAQ.

**Comment by gingerbeardman** [comment]
> Q: It says that the MD5 checksum is unknown when I'm trying to flash custom kenel! What I need to do?
>
> A: There are two possible reasons:
>
> You have some unique unknown revision of NES Mini, please send your kernel dump in this case.
> Some custom kernel already flashed.
> It's safe to continue in both cases.
