### ISSUE TITLE
Which Size Is Correct - Debug Details or Info in Hakchi at Bottom?

### ISSUE THREAD

**Issue by Darky2k1** [ClusterM/hakchi2#675]
Image:
https://i.imgur.com/kaUsh9z.png

Which is Correct?
165.9MB used by games or 71.7MB used by games
or
246.9MB Available for games or 216.9MB Available for games

these seem to contradict each other

**Comment by ClusterM** [comment]
Debug is correct for advanced users and GUI is correct for average end user. It reserves space for save-states and system data.  Check FAQ about free space calculation.
