### ISSUE TITLE
[SNES] Can't drag a game into a folder of the same name in Folders Manager

### ISSUE THREAD

**Issue by Gwindalmir** [ClusterM/hakchi2#678]
If I have a folder of the same name as a game, I can't drag the game into it.
There's no error message, it just doesn't work.

See screenshot, the game Mortal Kombat can't be dragged down to the folder below of the same name.
![image](https://user-images.githubusercontent.com/1127170/31418419-c886beac-adea-11e7-880e-35b528393456.png)

Changing the folder name, allows me to drag it in.
![image](https://user-images.githubusercontent.com/1127170/31418487-10cf1560-adeb-11e7-912e-e2bd8ae6375c.png)

**Comment by Drakonas** [comment]
Confirmed.

**Comment by ClusterM** [comment]
Fixed, thank you.
