### ISSUE TITLE
NES Classic Hack Error Code

### ISSUE THREAD

**Issue by jimwobrien** [ClusterM/hakchi2#680]
So I downloaded the hackchi2 software, downloaded the ROMS and uploaded everything, it Flashes my custom kernel but when I try to sync the additional games I get this message:
![img_5864](https://user-images.githubusercontent.com/32694453/31421690-c50ebca8-ae16-11e7-933f-08f6bbc3dfeb.JPG)

Any suggestions? What am i doing wrong?

Thanks

**Comment by andyderuyter** [comment]
#652

**Comment by MindController** [comment]
Did you change the console type to NES Classic Mini?

**Comment by monkeyass2017** [comment]
I had same error, had to revert back to 2.17d

**Comment by jimwobrien** [comment]
Tried that, uninstalled and reinstalled the 2.17d but it keeps defaulting to the original and gives me the same error message 
--------------------------------------------
On Wed, 10/11/17, monkeyass2017 <notifications@github.com> wrote:

 Subject: Re: [ClusterM/hakchi2] NES Classic Hack Error Code (#680)
 To: "ClusterM/hakchi2" <hakchi2@noreply.github.com>
 Cc: "jimwobrien" <jimwobrien@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Wednesday, October 11, 2017, 5:10 AM
 
 I had same error, had to revert
 back to 2.17d
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by stevenEno** [comment]
Is 2.17d the last working version for the NES Classic that doesn't get this error?

**Comment by andyderuyter** [comment]
@mrenoeshs Not in my case, the previous release (2.20) didn't have this issue

**Comment by Urbanorecord** [comment]
I have the same error in Nes Mini CLV-001. I have tried all the possible solutions without success.

**Comment by Aks3n** [comment]
I'm having the same problem, went back to an earlier version for now.

Any updates on this?

**Comment by jimwobrien** [comment]
Is there a version of hakchi2 that is confirmed to still work for the NES Mini?  

    On Thursday, October 12, 2017 10:54 PM, Aks3n <notifications@github.com> wrote:
 

 I'm having the same problem, went back to an earlier version for now.Any updates on this?—

**Comment by Drakonas** [comment]
13 days ago this was fixed by Cluster. Closing.
