### ISSUE TITLE
'' USB read error: IotTimeOut '' error when trying to dump the kernel (with v.2.20b)

### ISSUE THREAD

**Issue by Makiaveli25** [ClusterM/hakchi2#681]
![error](https://user-images.githubusercontent.com/32695414/31422792-295163f8-ae1e-11e7-89ba-08766563ae18.JPG)

Something to do? Wait for the new version?

**Comment by Makiaveli25** [comment]
with the latest version of hakchi2 ver. 2.21b

**Comment by Makiaveli25** [comment]
and with hakchi2 ver.2.20 it the same thing

**Comment by Bumblecito** [comment]
Try not to keep pushing reset button after PC detects the snes mini.
I mean, release the reset button after You hear the "plugged in" pc sound.
If that doesn't work, try to plug it in another usb port or reinstall driver.

**Comment by joetheuseless** [comment]
same problem i read it is due to incompatibilities with AMD Ryzen i hope  we can figure this out i have tried 15 times now to dump the kernel with no vail

**Comment by Drakonas** [comment]
@Makiaveli25 are you still having trouble?

**Comment by Drakonas** [comment]
Closing this. please keep Ryzen discussion on issue #620. This is a duplicate.
