### ISSUE TITLE
Chrono Trigger Black Screen Freeze

### ISSUE THREAD

**Issue by ahnolde** [ClusterM/hakchi2#683]
During a cutscene transition, Chrono Trigger gets stuck on a black screen early in the game when Lucca starts to explain Marle's lineage. Anyone else make it past this in build 2.21b?

**Comment by OliverUlm** [comment]
Are you running Chrono Trigger with Retroarch or with the built in Emulator? If you don't know it's the built in.

**Comment by ahnolde** [comment]
Running with built in, haven't installed retroarch

**Comment by ahnolde** [comment]
Managed to get past this point by deleting the game and trying a different rom, except when I went to delete the rom, hackchi is saying I have only 220mb instead of 300mb? Oh well, got Chrono Trigger working so that's the most important thing!

**Comment by bolleholle** [comment]
So this means it was a bad rom, right? Nevertheless the problem ist solved
