### ISSUE TITLE
Some issues with SNES/NES mini with 2.21b (retroarch icon corrupted on SNES - oringinal 30 NES games doesn't run)

### ISSUE THREAD

**Issue by Pito23** [ClusterM/hakchi2#686]
hi with the latest release (2.21b), after drag and drop CloverApp for retroarch app (0.9b) in hakchi2 window, at the SNES MINI menu the retroarch icon is shows corrupted... any help?

Also i've issues with my NES MINI: after update hachi2 from 2.17 to 2.21b and modified specific string of Parasol Stars EUR nes Rom to works with retroarch (add latest retroarch mod and type " --retroarch" at the string end), the game doesn't run and return back to menu... also the original 30 games icon are corrupted and doesn't run...

ANY SUGGESTION PLEASE?

**Comment by OliverUlm** [comment]
It always helps to know the exact version of Hakchi - there have been several releases of 2.21b. Look under Help / About. The most recent version is 2.0.21.32. If you're not using that version you might want to download again.

As for the NES mini - my feeling is that the new developments are strongly focused on the SNES mini right now, so you might want to download the old 2.17 again and keep using that for the NES until things settle down a bit.

**Comment by Pito23** [comment]
hello, the hakchi2 version is the latest v2.21b (internal version 2.0.21.32)... maybe i can delete the retroarch app from the snes mini for now, but i still do not understand why the icon shows corrupted.

For the NES issues i'll try to format and resinstall everything.

**Comment by dem1980** [comment]
If i could help...
I notice that when i open the folder where is the icon of retroarch, the display of the folder content is very slow, like with the plugin which remove thumbnails.
I don't know if the reason is the broken icon of retroarch or only the retroarch option in folder
I have last version of hakchi2 2.21b and retroarch 0.9b

**Comment by Pito23** [comment]
i don't know because i don't have that plugin installed. Also my retroarch app is in the root folder of hakchi. by the way thx.

**Comment by Deathstryker** [comment]
After updating, have you tried installing stock kernel and then reinstalling custom kernel on both machines and then uninstalling all mods and reinstalling all mods?

**Comment by Pito23** [comment]
Yes but only for the SNES MINI... and sa result i've the retroarch icon corrupted issue for it.
Instead i've to do it for the NES MINI... but I would rather not do it because of all the mods i've already installed in it for, mame, pce, megadrive, ect... And i do not understand if i could launch all those roms in the same way using the "old" strings text or i'll must use the " --retroarch" thing on them...

**Comment by Deathstryker** [comment]
Do you really need the CloverApp shortcut? You can still access RetroArch menus without it. I know that doesn't really solve your issue but it's a possible workaround if you don't like the way it works. I don't currently have CloverApp installed so I can't confirm if it's an issue.

> And i do not understand if i could launch all those roms in the same way using the "old" strings text or i'll must use the " --retroarch" thing on them...

What does your old string look like?

**Comment by Pito23** [comment]
Yes of course, that icon is useless but i wonder why it's not showing in the way should be... it's without a reason.

For the NES issues, i must check the old strings but they have specific path for each emulator, and my question is if those strings are correct even in the newer hakchi2 releases or i can launch alla the emulator simply typing " --retroarch" at the end of each string without modified other parts?

**Comment by 03bgood** [comment]
This is happening to me, too. The original 30 NES games show up as corrupted. What do I do?

**Comment by Pito23** [comment]
i had to reinstall everything: reflashing back original kernel and then flashing the custom one. Finally reinstall mods and games... now it works but is  very annoying.
