### ISSUE TITLE
Issue controls (D-pad) N64 games

### ISSUE THREAD

**Issue by RuudFl** [ClusterM/hakchi2#687]
I installed hackchi 2.20 and retroarch 0.9 but have issues with the controls in N64 games. For instance Mario Kart 64 works, but i can't use the d-pad with the original SNES controller that came with the SNES mini (EUR).

The d-pad does not work, but when i look into quickmenu -> controls everything looks okay. There is no option to select analog d-pad or something, so kind of stuk now with the D-pad controls on N64. Any one else had issues with this?

**Comment by drunkenchrono** [comment]
use for n64 games a WII Classic Controller Pro its working without any issue :)
playing mario 64 , zelda , diddy kong and starfox 64 no problems
