### ISSUE TITLE
Update to new Hackchi

### ISSUE THREAD

**Issue by nnd81** [ClusterM/hakchi2#688]
Hello, first I would like to say thank you for all your work and for providing a way to add more games on nes/SNES.  Sorry for asking if this was already explained as I am new to all of this, I used Hackchi  2.20 that was released 2 or 3 days ago supporting snes, all the games I wanted and added are working till now. What I would like to know is after I update hackchi to the latest available version on my pc, do I need to upload kernel again to console, and do I also need to restore factory settings on my SNES? Thank you.

**Comment by dave11674** [comment]
basically get the new 2.21 and extract it to your hakchi folder it will overwrite old hakchi files
now run the program and goto kernel > flash custom kernel

this will update the custom kernel and your good to go
your games list will remain in tact
i didnt restore any settings in my snes mini

dave

**Comment by orenigittigitt** [comment]
Doing this I was faced with a md5 checksum warning which I confirmed. Process then continued flawlessly.

**Comment by Angelowaslike** [comment]
Really want to know what's the cause of that md5 checksum warning as well.

**Comment by Drakonas** [comment]
@Angelowaslike it means the kernel on the SNES classic is partially corrupt. A reflash of OG kernel and then custom kernel is typically recommended when that happens.
