### ISSUE TITLE
Browsing folder structure to pull off save games

### ISSUE THREAD

**Issue by dave11674** [ClusterM/hakchi2#689]
hi guys
is it possible to wire onto the board to list folder structure to read and write save games
not save state as i know this option is already available.
on a side note these save states are they usable with any pc emulator to date ?
if so this thread is mute lol

i basically want to load the save/state on my pc and add GG codes
ive used GG tool on zelda to add codes to the rom, fixed checksums and added roms
rom works fine but no cheats are on !!
it works fine for other games like mario and actraiser as an example

im sure i found a site yesterday with a wire up to the inside points of the snes mini to do what im asking above lol
knew i should of bookmarked it :)

thanks

dave

**Comment by dave11674** [comment]
ok so ive just realized its built in now with hakchi :)

so on to my next questions
i see the savefiles are named...
cartridge.sram
cartridge.sram.hash

so will i be able to load this sram file into an emulator 
do my codes and resave and re-upload to the snes mini
im seeing hash
so is it doing a checksum on the sram file ?

thanks again

dave

**Comment by dave11674** [comment]
ps the page i was on about in my first thread is right here on the github lol

https://github.com/ClusterM/hakchi2/wiki/Modifications-and-modules-guide

dave

**Comment by Drakonas** [comment]
A quick google search turns up the answer: https://www.reddit.com/r/miniSNESmods/comments/761m8j/srm_to_canoecloverclvs_converter/?st=j98rvhjr&sh=2711b33c
