### ISSUE TITLE
Flash NES classic Kernel to Famicom mini possible?

### ISSUE THREAD

**Issue by CarlosSilva403** [ClusterM/hakchi2#69]
I purchased 2 Nintendo Family computer minis (Famicom) and realized there is no language option.  Can I flash the Famicom with the Nes kernel and get English options?  

Thanks

**Comment by ClusterM** [comment]
Hi.
Kernel doesn't contain any language data. You need to replace string resource files.
hakchi2 will support modules soon, so it will be possible to translate Famicom using some mod.

**Comment by CarlosSilva403** [comment]
Awesome!   Can't wait and great support!
