### ISSUE TITLE
I did not create a kernel dump

### ISSUE THREAD

**Issue by noart1** [ClusterM/hakchi2#690]
I did not create a kernel dump, what should I do, where can I get my native kernel?

**Comment by nerdnils** [comment]
This here is for bugs in hakchi2 not for stupidity.

**Comment by noart1** [comment]
I thought here can help an ordinary person. I acted on instructions from the program

**Comment by nerdnils** [comment]
Again: this here is NOT for help! Use reddit/twitter/a forum.
And if you acted on the instructions from the program you did not lose your kernel as instructed. Good

**Comment by noart1** [comment]
Ok. Good. Thank you.
