### ISSUE TITLE
Help with the snes mini hack 

### ISSUE THREAD

**Issue by M1loScorpius** [ClusterM/hakchi2#691]
That such greetings I am new in this of being able to add rooms to the mini super nes and I have some doubts I hope they can help me.
The first question is about how I can delete games that do not work well and add some new, every time I have to add this having to synchronize holding the reset button and then the power button?

Another question is regarding the new release, I use 2.0.20.15
I can download the new version and what risk are you?
Works better ?
And how can I use it?

Thank you for your help

**Comment by beyondmany** [comment]
@M1loScorpius 
1. You can delete games by right clicking on them in the list and choosing the menu option "Delete selected game"
 2. You should not have to enter the developer mode (holding reset at boot) each time. Check your USB if firmly connected. Once you've successfully installed the driver at least once, the subsequent installations only require you to power on the device and then add new games.
3. Firmware upgrades are done at your choosing. Read the https://github.com/ClusterM/hakchi2/wiki/Changelog to see the list of changes.
4. Enjoy!

**Comment by Deathstryker** [comment]
> every time I have to add this having to synchronize holding the reset button and then the power button?

To add games, you don't have to do this. The program will tell you when you need to do this.

> I can download the new version and what risk are you?

Yes. Make sure you install over top of the old version with all of the files. And before putting games on your system with a new version of the app, be sure to re-flash the custom kernel and then add your games.

**Comment by M1loScorpius** [comment]
Thanks @Deathstryker @beyondmany for the answer ! I already flash the kernel and be able to add my games...
I another question sorry :P Is there any way to customize the game library so that they look inside the interface in order. 
Example 
Megaman X, Megaman X2... Megaman X3 

thanks for your help

**Comment by Deathstryker** [comment]
I don't have the app interface with me right now, but if you go into the window where you arrange games, and select "split equally" I think it will arrange the original games with the new games.

**Comment by M1loScorpius** [comment]
Nice I try that Ty so much for your  help !!
