### ISSUE TITLE
Can't enable Select + A/B turbo option on SNES Mini

### ISSUE THREAD

**Issue by amayatsky** [ClusterM/hakchi2#694]
The application allows me to select this option but unfortunately it does nothing :(
After the console reboot and reopening of the hakchi2 this option is no longer selected in the menu.
Shortcut for the system reboot is working A-OK.
App v2.0.21.32, console model CLV-301, kernel md5: d76c2a091ebe7b4614589fc6954653a5.
Anything I can do to help?

**Comment by ClusterM** [comment]
Tesing

**Comment by ClusterM** [comment]
Fixed, thank you.

**Comment by amayatsky** [comment]
Thanks a lot!
