### ISSUE TITLE
Problem with Kernel Dumping

### ISSUE THREAD

**Issue by StupidKernel** [ClusterM/hakchi2#695]
Everytime I tried to dump the kernel it says it cannot because there is already a process going on.

The french part basically says : the process cannot acces the file because the file is used with another process
![error](https://user-images.githubusercontent.com/32715165/31457054-9df657ca-ae89-11e7-98e2-72860a8b5c7c.png)

**Comment by nex86** [comment]
restart your computer.
Make sure the driver for FEL mode is installed.
hold the reset button on your snes mini, plug in usb while still holding reset. release button, then install driver.

**Comment by Drakonas** [comment]
@StupidKernel was this resolved?

**Comment by Drakonas** [comment]
Closing this issue as the OP has not responded.
