### ISSUE TITLE
Missing original 21 Games. Don't have original kernel dump!

### ISSUE THREAD

**Issue by tombombadil3x** [ClusterM/hakchi2#698]
After the upgraded to v2.21, I was unable to Drag/Drop. So I uninstalled.  In doing so, I somehow lost my original kernel dump!

When I reinstalled, I tried to make a Kernel Dump and received a "can't unpack ramdisk" error.  I backed out and tried my SNESmini on my TV, and all of the box art for my original 21 games is gone, and they will not run!  My new 15 games that I've installed run perfectly.

At this point, I'm crazy nervous, and just want to get back to my original 21 games, but I don't have a kernel dump! Help please.

**Comment by warsavior86** [comment]
Dude, calm down...just google for original snes kernel...i think there are some youtube videos too that include a link to an original kernal file...just add this kernal to the dump folder in hakchi folder and flash original kernal whenever you have your snes classic hooked up.

**Comment by alEx783** [comment]
How can i do a 'backup' of my snes kernel?
If i want to unistall hakchi2 and return to my original snes..

**Comment by ihadmail** [comment]
[Stock_snes_kernel.zip](https://github.com/ClusterM/hakchi2/files/1377633/Stock_snes_kernel.zip)

This is my stock kernel. Navigate to your folder where hakchi executable is. Make a folder titled "dump". Place this file in that folder. Now you can open hakchi and sucessfully click on flash stock kernel.

**Comment by tombombadil3x** [comment]
Thank you very much!!

**Comment by NicholasB85** [comment]
Thank you very much. My system became a brick during the latest update and flashing back to your stock kernal helped. Obviously I lost all my save states etc. but now my console is working again. I was stuck at just having a black screen before this. I think my stock kernal had became corrupt.

**Comment by Drakonas** [comment]
Please refrain from posting links to copyrighted content, unless you want Nintendo to DMCA Hakchi.
