### ISSUE TITLE
generate a List of titles

### ISSUE THREAD

**Issue by DecanFrost** [ClusterM/hakchi2#700]
Is there anyway to generate a list of my games in Hakchi2  showing proper Title names.

easier to share what I have working vs typing it all up

**Comment by MindController** [comment]
If you go to the config folder in the hakchi2 directory, you'll see a "folders_snes.xml" file which contains the name of each game folder (e.g. CLV-U-ESSUP) and the corresponding game title (e.g. Harvest Moon).
