### ISSUE TITLE
Save State Manager Using???? (Windows User)

### ISSUE THREAD

**Issue by MonshouNoMarth** [ClusterM/hakchi2#701]
Does Save State Manager work importing save states from PC to SNES mini?
I want to transfer my savestate from my pc to snes mini, so I followed all steps about export that "save".
I changed file extension from ".clvs" to "tar.gz", unpacked with winrar, deleted .hash file and replaced .sram file with my savestate edited with HxD (I opened .src>analisys>checksum>sha-1, and pasted hex string in file's last row and saved as "cartridge.sram").
Then I repacked it in a .rar file, recompressed as .tar.gz file and changed again extension to ".clvs" and unpacked again for getting the file which I have to restore.
But, when I import this file with Save State Manager, exit from Hakchi2 and play my snes game which I imported its savestate, It doesn't recognize my savestate and only It shows Snes Mini's save.
Did I do anything wrong? Which steps I have to follow?
My PC has Windows7, Should I use a Linux PC?
PD: Sorry for my horrible English ^^'  I will be so thankful if someone knows a solution.

**Comment by DanBonez** [comment]
What game are you attempting to do this with? This method only works for some games.

**Comment by DanBonez** [comment]
You could also try accessing the save folders via FTP and replacing the cartridge.sram files that way. I've found that works better for the games that do work.

**Comment by MonshouNoMarth** [comment]
> What game are you attempting to do this with? This method only works for some games.

> You could also try accessing the save folders via FTP and replacing the cartridge.sram files that way. I've found that works better for the games that do work.

Fire Emblem Monshou no Nazo xD
Ok, I'll try it. Thank you!
Edit1: via FTP? I'll use FileZilla, thanks again ^^
Edit2: "Where I have to replace cartridge.sram? I'm so "noob" :S

**Comment by DanBonez** [comment]
https://github.com/ClusterM/hakchi2/issues/578#issuecomment-336189860

I got into some detail there.  Save folders are located: var->lib->clover->profiles->0-> then the game ID

**Comment by Paladin341** [comment]
So I followed your steps DanBonez, but after I transfered the files and replaced the catridge.sram, there was a sound issue.

I played Super Mario RPG on SNES mini (part of the original 21 games) and copied those save files. Then I bought a Super Famicom mini and I'm trying to copy those files to a rom version of Super Mario RPG (US).

I know Super Mario RPG's game code for the originals is CLV-P-SABQE and the user added game is CLV-U-ZZXIY. The file transfer was successful and I'm able to play the save state, but now there is a sound issue. I'm unsure on how to fix the sound issue.

**Comment by DanBonez** [comment]
That's unusual. I have been unable to get Super Mario RPG to work myself, but I've been transferring a .srm file from my emulator to the SNESC so the situation is a little different. I've never encountered a sound issue before just by changing the .sram file.

**Comment by Paladin341** [comment]
I played with it some more and the sound will fix it self if you restart the game. I'm not too sure why resetting the game fixes the sound. I can upload a video to show you my sound issue.

This also happened to other save files from the original core 21 games. It happened to Mega Man X and Kirby Super Star.

**Comment by Paladin341** [comment]
Ok, here is the youtube video I recorded to show the sound issue. Let me know what you think.
https://youtu.be/XSXphlNt3dU
