### ISSUE TITLE
Wont let me Hack consecutively 

### ISSUE THREAD

**Issue by xela224** [ClusterM/hakchi2#703]
After a succesful Hack I close the program save the games and mods and then unplug the SNES and it works great...however when i try to plug in a new SNES and try to sync the games it thinks i have a NES plugged in and wont let me start the hack process. it tries to install the NES drivers instead.

my only solution so far has been to re-download Hackchi again and start all over from scratch. please help

**Comment by hoderer** [comment]
Can't you just choose 'SNES mini' in the menu? It's the first I read that the device isn't recognized correctly. Strange thing...

**Comment by MonshouNoMarth** [comment]
Did you select"Snes mini/Super Famicom Mini" when Hakchi2 was starting?
Strange...

**Comment by hoderer** [comment]
Funny, MonshouNoMarth and me answered the same thing the same time :-)

It's under Settings --> Console Type

**Comment by ihadmail** [comment]
This is simple. 

Go to your folders where hakchi installed. Find the "dump" folder. Rename it to something like "dump-whoeveryouscalpedthesnesto" make a new folder titled "dump". 

Open hakchi, dump kernel, flash new kernel, add games, add retroarch. Profit. Donate to ClusterM for helping you profit.

**Comment by xela224** [comment]
thx hoderer and MonshouNoMarth but the console type is set to Snes so thats not the problem, I will try i hadmail's suggestion and let you know if it works out.  

also Cluster deserves every donation he gets for doing this.

**Comment by xela224** [comment]
It didnt work, not sure what the issue is but thx for the suggestions.

**Comment by Drakonas** [comment]
Use separate folders for different SNES Classics. Also, it always says installing "NES" drivers even for SNES Classics. That shouldn't affect your issue.

**Comment by Drakonas** [comment]
Are you still having issues @xela224 ?

**Comment by Drakonas** [comment]
Closing this issue as the OP has not responded.
