### ISSUE TITLE
can't unpack ramdisk2

### ISSUE THREAD

**Issue by 77920** [ClusterM/hakchi2#704]
Upon using hakchi 2.21 i did what was required and dumped the original kernel
im trying to upload a custom kernel to it but i get error can't unpack ramdisk2
what's wrong?

**Comment by ClusterM** [comment]
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems
https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems

**Comment by 77920** [comment]
Had to use the debug copy for it to work.
