### ISSUE TITLE
Issue with games past starting at S and above

### ISSUE THREAD

**Issue by warlockv2** [ClusterM/hakchi2#705]
this is strange, but with newest hakchi, all games halfway threw s and above  such as super adventure island 2 and up to zombies ate my neighbors,  give a c7 error now,  it looks like the database in hakchi stops at this point as well and all information in it is unknown.  dont know if its related or not,  but iv tried reinstalling everything, readding games, etc.  same error.  canoe or RA doesnt matter,  same error.   almost as if the database is not configuring the games properly and causing errors maybe

**Comment by ihadmail** [comment]
I just tested this out on mine. I could not replicate your problem. Not with 50 games installed. Not with 100 games installed and not with 175 games installed. 

I was using Hakchi 2.0.21.32 and have retroarch_with_cores 0.9c installed on it with the retroarch and snes9x2010 cores.

**Comment by Linkinworm** [comment]
Games above S work fine for me, whats broken for me is compressed games though thats what throws a c7 error. could you have similar issue and didnt realise?

**Comment by warlockv2** [comment]
i replicated it.  i think.   i redid everything again but stayed at pc.  seems my pc went to sleep mode i guess when its at the s's if i leave it alone.  i guess this caused it to still show the games but not actually.  i dont know honestly.  its weird, but i got it working now by just doing half, then adding the other half. and everythign works fine.
