### ISSUE TITLE
some PAL games dont work with retroarch on 2.0.21.32

### ISSUE THREAD

**Issue by hectorevil** [ClusterM/hakchi2#707]
some PAL games dont work with retroarch on 2.0.21.32 like Ilusion of Time appears the message "This game pak is not designed for your super famicom or super nes" while on 2.20 works correctly

**Comment by Jonny0r** [comment]
Had the same issue, but official PAL games are not supported, simply patch to NTSC and they will work, at least for me this was the case.

**Comment by hectorevil** [comment]
Retroarch support all roms included PAL. Patch to NTSC? No. I will continue using 2.20 to install this type of games that give this error

**Comment by hectorevil** [comment]
This game on PAL version works perfectly on retroarch

**Comment by ClusterM** [comment]
Force NTSC patching removed.
