### ISSUE TITLE
Scanlines somehow forced on Retroarch games when you enable Bilinear filtering

### ISSUE THREAD

**Issue by Jenslyn87** [ClusterM/hakchi2#708]
Anyone tried this? I'd like to remove scanlines from everything, and normally they aren't there on the genesis games I've added. I was happy to add the global command to get rid of the scanlines (but retain bilinear filtering) on my SNES games. However, when I enable bilinear filtering on my Genesis games via Retroarch, the scanlines also appear (but oddly enough only after a restart of the game or the start of a different game). I assume somehow the two features are yoked in the system. Any solutions / advice?

**Comment by Jonny0r** [comment]
Just found out i have the same issue. I also dont like scanlines and perfer the Bilinear filter so i enabled it on RetroArch, then the new Filter Hack for Canoe came out and i was really happy for have Filter also there. I add RetroArch 0.9c and now i just start an RetroArch game and i have full scanlines enabled but never did it and also find no real solution to disable them again.

Edit: Just gave it a try and remove the global command line (in my case --smoth43), but the problem on RetroArch stays, so i assume it a problem of the latest retroarch config 0.9c

**Comment by Jonny0r** [comment]
Start - Select > Onscreen Display > Onscreen Overlay > Display Overlay OFF (Or Scale as you perfer)

to remove the Scanline on RetroArch

**Comment by Jenslyn87** [comment]
Yes, actually you're right. I assumed it was a problem with the command line, but it's apparently not. The problem's still there after I removed the line also. 

Let me try what you wrote there!

**Comment by Jenslyn87** [comment]
You're right that it removes the scanlines, but only until I restart the game. But I found a different fix that removes them permanently for me at least. I just press 'start' on where it shows the actual file (scanlines.cfg or scanlines.png I believe) and that makes the file designation disappear. After that it says nothing, and the scanlines don't return!

**Comment by Jonny0r** [comment]
Just find out the same, stupid stuff :D 
Looks promissing and yes they dont return :)
Thanks for your support.

**Comment by Jenslyn87** [comment]
Thanks for your help, Jonny0r! Good thing we solved it:)

**Comment by ClusterM** [comment]
Known bug. This is not RetroArch repo.
