### ISSUE TITLE
Not all games downloaded, pulling hair out...

### ISSUE THREAD

**Issue by BrueCrew** [ClusterM/hakchi2#709]
Hello, I am not a super techie guy.  I looked at several tutorials and tried my best, but not all my games downloaded?  Only A-E downloaded and  I dont see the rest, any help in this would be awesome. Thanks!!!

**Comment by Jenslyn87** [comment]
You probably put too many games in a single folder. Check that the folder limit isn't also the limiting factor :)

**Comment by BrueCrew** [comment]
Where do I see how many can go in a folder?  My buddy gave me his game list, he had no issues, but he also is not around to help me out.

**Comment by BrueCrew** [comment]
Total games 181

**Comment by Jenslyn87** [comment]
Settings -> Pages / Folder Structure / Maximum games per page/folder. I recommend keeping the number relatively low and making several folders. Pick "Custom - show Folders Manual every time" to do that

**Comment by BrueCrew** [comment]
I will give that shot, will post with an update in a few...

**Comment by BrueCrew** [comment]
That did not work

**Comment by BrueCrew** [comment]
How long should everything take to download?  I did all the box art, flashed custom kernel, then when I sync it only takes maybe 2 mins and then says done?

**Comment by BrueCrew** [comment]
Did a factory reset and no help... Im at a loss...

**Comment by Jenslyn87** [comment]
Sorry, I'm not sure what the problem is then. Try to follow a youtube guide, I guess!
