### ISSUE TITLE
Doom 64 loads to a red screen

### ISSUE THREAD

**Issue by JohnSid45** [ClusterM/hakchi2#710]
I've been having issues with a few of the games I've loaded to my SNES mini.  Doom 64, E.V.O., and a few others were crashing at launch initially.  Others were crashing when I tried to exit back to the menu. 
 Reflashing the whole thing after 2.21b was out, then installing Retroarch seems to have fixed most of the issues, but Doom still won't load.  It is no longer crashing, but opens to a dark reddish-black screen and freezes there. I managed to fix E.V.O. by simply deleting it and adding it back after Retroarch was there, but Doom still won't load.  I tried adding the "--retroarch" to the command line but it doesn't seem to have helped.  I saw another comment that mentioned this, but there wasn't a resolution provided.
Correction: Doom (SNES), not Doom 64. 
Update: it fails on my NES as well.  However, Earthworm Jim loads on my NES and crashes with a C7 error on my SNES.

**Comment by ClusterM** [comment]
Doom is working for me on canoe. And it's reported as problem game for Snes9x2000 core.

**Comment by JohnSid45** [comment]
Well, v2.21c and the new Retroarch and Clover fixed Earthworm Jim, but Doom still won't load. I have both snes9x2005 and snes9x2010.  Oh well - it's hardly my top game when I've got 110 other working SNES/GBA games on my SNES and around 800 NES/SNES/GB/GBC/GBA/Atari games on my NES. :)
