### ISSUE TITLE
Soft Reset in v2.21c doesnt work anymore.

### ISSUE THREAD

**Issue by Jonny0r** [ClusterM/hakchi2#714]
Hello,

im sorry to open a topic, but just flashed v2.21c and the Soft Reset doesnt work anymore, i double checked the Keys (set mine to L+R+SELECT) to avoid problems with RetroArch, but doesnt work.

Autofire works fine, normally dont use it, but in this case i would like to try.

Custom Kernel Reflashed just for testing, doesnt work.

**Comment by Joonie86** [comment]
I have the exact same issue, it worked fine on 2.21b.

**Comment by Jonny0r** [comment]
Puuh, then im not stupid :) Thanks for the confirmation.

**Comment by Cerberus1337** [comment]
I updated mine to v2.21c and my select and start Soft reset was still working.

Decide to try and recreate your issue so i changed mine to L + R + Select and updated setting to my SNESC and It stopped Working for me as well. 

I Changed it back to Select + Start, Updated Settings to SNESC and it works Fine Again.
Maybe the issue is using 3 button combo. try Switching back to Select + Start and or any other 2 Button Combo.

Hope I helped.

**Comment by Joonie86** [comment]
I was using Dpad Down + Select, and it got broken as soon as I updated to 2.21c (flashed new kernel) and just tried switching to Select + Start , still broken.

**Comment by KongsNutz** [comment]
Same issue here, flashing Custom Kernel works to restore my selected combo (Down+Select) however syncing games removes it. (Scripts being auto added im guessing is the issue)

**Comment by Cerberus1337** [comment]
Weird. I Forgot to Mention that i'm using web installer and that's how i updated to 2.21c and i didn't have to Flash Custom Kernel As indicated in the release notes. Not sure if that makes a Difference. Let me try flashing it and Synching Games.

**Comment by KongsNutz** [comment]
I didn't flash custom either at first, just syncd in new version since it now auto updates scripts (noticed reset didn't work and tried saving settings to snes and that didn't work so I tried a flash which worked, then broke again on syncing another game) but I bet the control hack script is being overwritten with each game sync too to nothing.

**Comment by Cerberus1337** [comment]
So I Flashed Custom Kernel Got a Checksum error after Kernel Dump but i ignored it and continued. After Custom was done flashing my soft reset was broken.
I synched 2 new Games and after they were done synching Soft reset Working again.
I assume synching games also updates settings? 
Something Definately Weird happening. Maybe Cluster can make sense of it!

**Comment by ClusterM** [comment]
Which version are you using - portable or web-installer?

**Comment by Cerberus1337** [comment]
Flashing Custom Kernel Killed My Terranigma Game.
Had To delete it and add it again and synch games to system.
Soft reset Still Working though.

**Comment by Cerberus1337** [comment]
Web Installer as i mentioned earlier.

**Comment by ClusterM** [comment]
Can you show me contents of your
    
    /etc/preinit.d/pc000_clovercon

and

    /etc/preinit.d/p0000_config

files?

**Comment by ClusterM** [comment]
Also, which console are you using?

**Comment by Cerberus1337** [comment]
How can i show u the contents?

USA SNESC Model

**Comment by KongsNutz** [comment]
i used portable and snesc if that counts

**Comment by Cerberus1337** [comment]
SU203395774

**Comment by ClusterM** [comment]
@Cerberus1337 download them using FTP.

**Comment by KongsNutz** [comment]
Tried flashing custom kernel again, reset combo works again. Then i resynced games again and it broke again

**Comment by Cerberus1337** [comment]
/etc/preinit.d/pc000_clovercon:

if [ "$cfg_clovercon_enabled" == "y" ]; then

CLOVER_BOARD_NAME=$(cat $mountpoint/etc/clover/boardtype)
MODULE="clvcon"
[ -f "$mountpoint/lib/modules/$(uname -r)/extra/$MODULE.ko" ] || MODULE="clovercon"

echo "clovercon_hack: starting driver"
echo "home button combination: $cfg_clovercon_home_combination"
echo "autofire: $cfg_clovercon_autofire"
echo "autofire XY: $cfg_clovercon_autofire_xy"
echo "autofire interval: $cfg_clovercon_autofire_interval"
echo "famicom 2nd start workaround: $cfg_clovercon_fc_start"

case "${CLOVER_BOARD_NAME}" in
	fp)
		module_params=2,195,1,194
		;;
	ep)
		module_params=1,195,2,194
		;;
	dp-hvc)
		module_params=1,-1,2,-1
		;;
	dp-shvc)
		module_params=1,-1,2,-1
		;;
	dp-nes)
		module_params=1,195,2,194
		;;
esac

overmount /lib/modules/$(uname -r)/extra/$MODULE.ko
insmod $mountpoint/lib/modules/$(uname -r)/extra/$MODULE.ko module_params=$module_params home_combination=$cfg_clovercon_home_combination autofire=$cfg_clovercon_autofire autofire_xy=$cfg_clovercon_autofire_xy autofire_interval=$cfg_clovercon_autofire_interval fc_start=$cfg_clovercon_fc_start

fi

**Comment by Cerberus1337** [comment]
/etc/preinit.d/p0000_config:

cfg_clovercon_autofire='0'
cfg_clovercon_autofire_interval='8'
cfg_clovercon_autofire_xy='0'
cfg_clovercon_enabled='y'
cfg_clovercon_fc_start='0'
cfg_clovercon_home_combination='0x000C'
cfg_disable_armet='n'
cfg_fontfix_enabled='y'
cfg_snes_extra_args=''

**Comment by ClusterM** [comment]
Seems like there is garbage from previous version. Please update again (to build 2.0.21.41), it will be removed automatically.

**Comment by KongsNutz** [comment]
Will try that now, thanks

**Comment by ClusterM** [comment]
Just sync games with new version (or save config via menu), you don't need to reinstall kernel.

**Comment by KongsNutz** [comment]
I'll wait for the portable zip to update since web installer is broken (has never worked on my win10)

**Comment by ClusterM** [comment]
@KongsNutz it's updated too. But you can just delete "hakchi2\bin\Release\mods\mod_hakchi\hakchi\rootfs\etc\preinit.d\p0000_config" file.

**Comment by Cerberus1337** [comment]
Hmm Web Installer was not working for me either when hakchi2 was closed.
I opened Hakchi2 and Ran it again and it went through just fine.
Although it works and doesnt work for me randomly at times so who knows.
Win7 32 Bit BTW.

**Comment by KongsNutz** [comment]
Downloaded portable.zip (internal .41)
Still says 40 in the app

**Comment by ClusterM** [comment]
@KongsNutz try now. Seems like github lagging.

**Comment by KongsNutz** [comment]
All good now Mate, thanks (Donation coming your way)

**Comment by KongsNutz** [comment]
@ClusterM what's your paypal mate, your websites link is broken
Nevermind, I did it, cheers mate

**Comment by Jonny0r** [comment]
clusterrr@clusterrr.com

Thanks for fixing this issue. I had the reflash the Custom kernel to fix it, only syncing was not enough :)

To support you was really one of my best donations i ever did, you are really fast in support and fixing issues. Awesome.

**Comment by Jonny0r** [comment]
Fixed in v2.21c (internal version 2.0.21.41)

**Comment by amayatsky** [comment]
Kernel reflash helped to solve the issue.
Turbo is working now too, thanks!

**Comment by Flasani** [comment]
Sorry I´m new and my english is not perfect haha^^

I have the 2.21b Update and now i have the Problem: First it Synchronise Perfect (tried it with 2 Games first) now 2nd time when i tried it´s writing install Driver...  Done but it would not synchronise! So i read here that i need to make an Update!

NOW i want to do but i want not to have Problems with my Controller like you write it here! Ähm...

So, my Question is:
What should i do to have no problems with something?
What Ordner should i import to the New Update Ordner 2.21c?
i know "Config" and "Dumb" is important... annything more?

And if i do an Update is something important to know?

Sorry for my bad English ^^

thanks for Help °°

**Comment by Jonny0r** [comment]
Lade einfach die neuste version runter v2.21c (internal version 2.0.21.42) dort ist der fehler schon behoben.
Wenn du kein Risiko eingehen möchtest oder kannst, solltest du auf der Version bleiben mit der du Zufrieden bist. Entpacke einfach die Neue Zip und kopier einfach alles rüber, das klappt. Wenn du updatest können immer Fehler auftreten die vorher nicht da waren, das kann man so nie sagen. Bei mir klappt alles mit der Version 2.0.21.42.

**Comment by Flasani** [comment]
Wow... Thanks :D haha
Also alles von der Neuen Datei einfach in meinen Ordner und ersetzen? Cool werd ich gleich Probieren Danke...

Ps. Woher weißt du, dass ich Deutsch red? HAHA^^
Egal, Thanks für die schnelle antwort!

**Comment by Jonny0r** [comment]
Das Ordner hat dich verraten.. :D

**Comment by Flasani** [comment]
Leider... :(
Hab alles aus dem Ordner in meinem ersetzt!

Steht: Warte auf Nes/SNES Mini

Darunter Schritte... 1,2,3
bla bla... geht nicht weg auch wenn ich den Treiber Installier! 
![neue bitmap](https://user-images.githubusercontent.com/32740442/31507421-e72a47d4-af7a-11e7-8382-374955ae0d9d.jpg)

**Comment by Jonny0r** [comment]
Hast du eine Custom Kernel schon geflasht? Wenn "Ja" sollte das klappen einfach wenn dein SNES mit USB verbunden ist und du es einfach an machst. Ansonsten würde ich sagen hier wurde der Custom Kernel noch nicht geflasht. Auf Deutsch "Flashe benutzerdefinierten Kernel"

**Comment by Flasani** [comment]
aber ich hab doch schon 2 spiele oben,... ^^ Egal,.. ich probiere es nochmal...

**Comment by Jonny0r** [comment]
Dann ja dann, dann findet er aus irgendeinem Grund deine Konsole nicht.
Also wenn der Custom Kernel geflasht ist und du neue Spiele hinzufügen möchtest, kommt dieses Fenster, dann machst die Konsole an und sobald sie erkannt wird geht es los. Würde mal versuchen anderer USB anschluss, Neustart, anderer PC, anderer verbindungstecker, ansonsten gehen mir auch die ideen aus.

**Comment by Flasani** [comment]
Vielen Dank!!! Ich hab den Kernel erneut Flaschen müssen...^^ Offenbar habe ich wie ich vom Kernel eine sicherheitskopie gemacht habe beim zweiten mal den Kernel Verschoben xD Mein Gott,... so deppat kann nur Ich sein xD

Vielen DANK!!! Danke... ohne dich hätt ich ewig gebraucht!!!
