### ISSUE TITLE
Add ability to toggle running a game through RetroArch using the UI

### ISSUE THREAD

**Issue by gingerbeardman** [ClusterM/hakchi2#716]
This will help speed up testing of games. 

Maybe special button combo?

**Comment by ClusterM** [comment]
Actually there is already secret combo %) Run game and hold DOWN button to start it using RetroArch.

If it's game with "--retroarch" argument, otherwise hold UP to start it using canoe.

And this is not RetroArch repo.

**Comment by gingerbeardman** [comment]
Thanks man!

Great work
