### ISSUE TITLE
SNES Classic v 2.21c base games issue

### ISSUE THREAD

**Issue by cjwheatley** [ClusterM/hakchi2#717]
So I downloaded the latest version of the firmware to free up space for more games and it worked but now when I boot up the SNES mini the original 21 games are broken links that do not play. I can play all of the rest of the games that I loaded up but not the original 21 games included with the system?

**Comment by ClusterM** [comment]
Version number?

**Comment by hxhieu** [comment]
I got the same issue.
Web installer 2.0.21.41
Stock games thumbnails all broken and C7 error upon loading them

**Comment by ClusterM** [comment]
Have you tried to reinstall custom kernel? Which mods have you installed?

**Comment by ClusterM** [comment]
Also try 2.0.21.42.

**Comment by cjwheatley** [comment]
Yeah the version that I was having that issue with is 2.0.21.42.

**Comment by cjwheatley** [comment]
Stock game thumbnails are broken and a C7 error when trying to load those games.

**Comment by cjwheatley** [comment]
Yes I have tried to reinstall the custom kernel. No mods installed.

**Comment by ClusterM** [comment]
Please do the following steps:

https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems

**Comment by goncalvesjoao** [comment]
I've got the same issue guys, not also the thumbnails don't appear but the original games are broken.

**Comment by goncalvesjoao** [comment]
Guys, to whomever had this issue, I uninstalled hakchi2 and reverted to the original kernel.
Everything works great.

Installed hakchi2 again, and uploaded the extra rooms again and everything is working fine 👍

**Comment by JohnVlachos** [comment]
Same problem here. Yesterday it worked fine, today I tried to add a few more games and now all the original ones have stopped working:/

**Comment by zeitgeist-red** [comment]
Same problem here. It worked fine prior to today.

I'll install the debug version and post back.

**Comment by ghost** [comment]
Same problem. Worked fine until today.

Going to install and run debug. Hopefully that will help.

**Comment by cryptolute** [comment]
Upgraded from 2.20 to 2.21c and do not have any of these issues. Original games display and boot fine, soft reset works and this upgrade actually fixed a problem I had where when shutting the console down nothing would happen, red light would stay on, console running, etc. I would have to turn it back "on" (press power up) then push it back down to the off position for a 2nd time to get the console to shut down.

2.21c has resolved this issue. Thanks clusterm!

**Comment by hxhieu** [comment]
@goncalvesjoao Did you have to backup the save games/states before uninstall hakchi2?

**Comment by goncalvesjoao** [comment]
@hxhieu For the original ones I did not, but I lost the saves for the custom rooms which naturally get deleted after we return to the stock kernel.

I still have my MegaMan X saves in place aha ;)

**Comment by hxhieu** [comment]
Cool thanks. Then I need to find the way to back up my custom roms saves first and retroarch too, been making progress on them...

**Comment by mos3joker** [comment]
I found this solution on some other website and it worked for me. Just go to Kernel - Flash custom kernel. It willl give you a warning window at some point, just click OK. And that's it. All original games are working and no save state lost. :)

**Comment by hxhieu** [comment]
Updated to 2.0.21.42 and Flash Custom kernel then all stock games are back :)

Btw, if anyone is wondering how to backup SRAM (cartridge save), the Tools > Save-State Manager does it all. It backups both restore points and SRAM!

All sorted for me, yay!

**Comment by Drakonas** [comment]
Closing this as it has been 19 days without a response from the OP. Assuming fixed. Respond if not so and I will reopen only for the OP.
