### ISSUE TITLE
Unable to start hakchi2_web_installer.exe

### ISSUE THREAD

**Issue by Zentriefugal** [ClusterM/hakchi2#720]
Good morning,

since this morning I am unable to start the web installer anymore. Here you can find a link to the log file (mostly in german). 

https://www.dropbox.com/s/xjxehjki5jgmrs9/6NLWL1ME.log?dl=0

Not sure if it's my fault but till now I couldn't find any workaround.

greets
Zentrie

**Comment by cjwheatley** [comment]
Likewise I cannot get the web installer to start for me.

**Comment by geeaprob** [comment]
same here

**Comment by Zentriefugal** [comment]
Found a little workaround which may not be the best method but worked at least.

1. Installed the Tool "Everything" (https://www.voidtools.com/)
2. Started Everything and searched for "hakchi"
3. Deleted all Files found by "Everything"
4. Started hakchi2_web_installer.exe

For me this worked great and the allready added games stayed in the tool.
