### ISSUE TITLE
Error when addind game (Picture for Debug)

### ISSUE THREAD

**Issue by troufiniou** [ClusterM/hakchi2#722]
Hi !

I'm using Hakchi 2.21c and I try to put some game on it (Earthbound Fr translate) and Zelda Minish Cap (GBA) but got a bug when upload some game.

[https://i.imgur.com/QVpZLfh.png](https://i.imgur.com/QVpZLfh.png)

Thanks :)

**Comment by ClusterM** [comment]
Please try 2.0.21.42.

**Comment by troufiniou** [comment]
Tried and working don't know why lel
