### ISSUE TITLE
Error "Code 127"...

### ISSUE THREAD

**Issue by blackjack-78** [ClusterM/hakchi2#723]
Hi!

I'm an "old hakchi2"user, never had an issue.

But since i've updated to the latest version 2.21c(internal version 2.0.21.41), when i'm trying to sync games with my snes mini, i've got this: "error 127".
![sans titre](https://user-images.githubusercontent.com/25226478/31494400-6a55f89c-af53-11e7-99e4-fd27005ba222.png)
Tasukete Cluster-San...
(Already trying to desinstall and reinstall...same issue...).

**Comment by ClusterM** [comment]
Please try 2.0.21.42.

**Comment by blackjack-78** [comment]
I've tried with version 2.0.21.42, just now...
No more "code 127" error but another issue...
Here's the thing: 
![sans titre](https://user-images.githubusercontent.com/25226478/31495471-0ad20e56-af58-11e7-83c0-85580782284b.png)

Thanks for your response by the way. (^_^)

**Comment by ClusterM** [comment]
Weird. Have you tried to reinstall custom kernel?

**Comment by ClusterM** [comment]
Ah, i understood...

**Comment by ClusterM** [comment]
Or maybe something is corrupted during update... Try to remove hakchi2 from PC and reinstall again.

**Comment by blackjack-78** [comment]
I've tried to reflash the custom kernel and i've this now: 
![sans titre](https://user-images.githubusercontent.com/25226478/31496007-04bacde4-af5a-11e7-8195-ef6feeaef701.png)

I'm going to desinstall from my pc and reinstall as you said...

**Comment by ClusterM** [comment]
It's not error.

**Comment by blackjack-78** [comment]
Ok!!!
Seems to work this way(desinstall hakchi2 from pc and reinstall...). No more "errors messages".
Need to test on my tv.

I'll be back with the"results"...

Thanks for the response and for your time.

**Comment by blackjack-78** [comment]
Works very well, retroarch too( i love the scanline patch ^^).

спасибо my friend!
