### ISSUE TITLE
JP SFC Language selection overmount files

### ISSUE THREAD

**Issue by samwisely** [ClusterM/hakchi2#725]
Something you may want to test/add to your mini faq - this enables language selection on a JP SFC Mini:

From a EU rom image you need:
/usr/share/ui/snes-eur/resources/fonts/l.font
/usr/share/ui/snes-eur/resources/fonts/m.font
/usr/share/ui/snes-eur/resources/fonts/s.font
/usr/share/ui/snes-eur/resources/layout/asset/sprite/wallpaper/wall.png
/usr/share/ui/snes-eur/resources/scripts/env/env_eur.lua

And on JP you overmount them as:
/usr/share/ui/shvc/resources/fonts/l.fnt
/usr/share/ui/shvc/resources/fonts/m.fnt
/usr/share/ui/shvc/resources/fonts/s.fnt
/usr/share/ui/shvc/ resources/layout/asset/sprite/wallpaper/wall.png
/usr/share/ui/shvc/resources/scripts/env/env_jpn.lua

It's really buggy to get it working and I had to use a completely factory reset system to get it to work right however mine is now in english. You can also edit the image for /usr/share/ui/shvc/resources/sprites/packed.png along with overmounting with a white highlight box instead of gray for a uniform look. It also seems the original roms all need disabled for this to work.

**Comment by samwisely** [comment]
I also figured out how to retain the original color scheme so you don't need to do the wallpaper/packed.png overmounts:

hex edit /usr/share/ui/shvc/resources/scripts/env/colors_jpn.lua and change "colors_jpn" to "colors_eur" (one string instance in the hex of the file) and overmount it to the system as /usr/share/ui/shvc/resources/scripts/env/colors_jpn.lua

This leaves your overmounting as:
/usr/share/ui/shvc/resources/fonts/l.fnt
/usr/share/ui/shvc/resources/fonts/m.fnt
/usr/share/ui/shvc/resources/fonts/s.fnt
/usr/share/ui/shvc/resources/scripts/env/env_jpn.lua
/usr/share/ui/shvc/resources/scripts/env/colors_jpn.lua

**Comment by Drakonas** [comment]
This is honestly a bit advanced for the FAQ. We really made the FAQ for newbies. We also don't really wish to risk filesystem replacements like this. If people want English they should wait to buy a European/American SNES Classic instead of buying from a scalper. Nintendo is releasing more throughout the holidays.

**Comment by Drakonas** [comment]
Also the FAQ Is for Hakchi-related stuff.. this is a Famicom vanilla fix really.
