### ISSUE TITLE
Install driver for Kernal Dump fails on Windows Vista

### ISSUE THREAD

**Issue by BodgerAndBadger** [ClusterM/hakchi2#726]
When trying to dump the kernal I follow the steps to install the driver.
However windows I see the exe flash up and run however the driver must fail to install

Consequently I'm unable to dump the kernal or connect the SNES mini to hakchi2.

**Comment by Gardosen** [comment]
I don't think that it is worth it to make the app compatible with Vista. 
Vista is legacy when it comes to support.

Also if your system is capable of running vista, you could also upgrade to windows 7. Just a small sidenote.

Kind regards
