### ISSUE TITLE
Mac and hakchi2 with wineskin issues

### ISSUE THREAD

**Issue by spotanjo3** [ClusterM/hakchi2#727]
I never had a problem with NES CLASSIC version of Hakchi2 2.14b until now.

What I do is that I compiled it with wineskin for your newer version to use both NES CLASSIC MINI and SNES CLASSIC MINI and I got this error message:

I click MS .NET 3.5 and click RUN

and message is: Do you wish to run winetricks? The following command will be executed: winetricks dotnet35 and I click RUN

and the message said Winetricks Commands Finished!! One second. Too suspicious. Something is wrong because it didnt show many lists before it is complete.

So I go ahead and click hakchi2.20 and nothing is coming up.

ERROR!

ERROR, tried to run command WSS-winetricks when the wrapper was already running. Please make sure the wrapper is not running in order to do this.

HELP ?! Please investigation.

**Comment by adamcarter1** [comment]
Two points.

1) I commend you on trying to get this set up on a mac. Being a mac user myself.

2) this program was meant to run in a windows environment. I have heard of this program running on a virtual machine like vmware.  I prefer bootcamp myself. Be that as it may,  I don’t think you can expect the author to troubleshoot his app for macs.

**Comment by spotanjo3** [comment]
Hello, adamcarter1.

I am aware that this is for windows.

So, you did it through bootcamp with windows 10 I take, right ?

**Comment by Gardosen** [comment]
use bootcamp or a virtualbox/vmware enviornment where you install windows 7/10.

Kind regards

**Comment by spotanjo3** [comment]
I thought so. Thanks.
