### ISSUE TITLE
Ooops, it seems like.... is not going not work correctly with the original emulator

### ISSUE THREAD

**Issue by Timminator87** [ClusterM/hakchi2#729]
Hey Guys,
i wanted to install secret of evermore on my snes mini and i get the message:

Oops, it seems like " Secret of Evermore (G).smc " is not going not work correctly with the original emulator. Do you want to use a 3rd party emulator for this game ( it needs to be installed) ?

When i press yes and install the game it doesnt work.

Is there a solution for it ?

**Comment by Jonny0r** [comment]
I assume you did not install the RetroArch and Snes9x plugin, but Secret of Evermore (G) should be normally be playable with Canoe and NTSC Patch.

**Comment by ClusterM** [comment]
Please read FAQ.
