### ISSUE TITLE
Nand Dumping

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#732]
I'm not sure if this is intentional or not but every time I try to dump the NAND I get an error message: Unable to Write to USB. Is that normal?

**Comment by Jonny0r** [comment]
Could it be that its the same error then in this thread?

https://github.com/ClusterM/hakchi2/issues/728

I assume you installed the driver already, perhaps did a restart, checked different USB Ports 3.0 / 2.0 and things like that?

**Comment by ghost** [comment]
I failed to specify, this is a SNES Classic.
No go. Is NAND dumping supposed to work at this point?

**Comment by KB0x** [comment]
The other thread wasn't relevant since I have an Intel based desktop and laptop and neither were able to dump the NAND. I tried all different ports, swapped cables. Rebooted. I managed to get the device to not respond at all at one point.

Windows 10 x64 on both computers.

**Comment by ghost** [comment]
I'll close this now but I have some advice for people. I found that my ability to dump kernel was possible on any port on my system. To get a NAND dump I had to use a USB 3.1 Type A port on the rear of the motherboard. Again the Decrypted NAND-B partition (and the new NAND-C) required a separate rear USB 3.0 port. This motherboard is supposed to have 3-4 different USB controllers, most provided by Intel.

I also found that the Micro USB connector on my SNES mini is slightly recessed behind the case, it's possible to connect and use the console, but it won't dump anything. Give that Micro USB connector a gentle wiggle and push, it'll click and suddenly everything works there too.
