### ISSUE TITLE
Anyone any luck with sensible soccer?

### ISSUE THREAD

**Issue by BodgerAndBadger** [ClusterM/hakchi2#736]

**Comment by msx2k** [comment]
I’m running it perfectly *using retroarch*. It’s a PAL rom only AFAIK and I’m not aware of an  NTSC patch for it so it won’t work on canoe.

**Comment by BodgerAndBadger** [comment]
Cannon fodder which is an EU only rom apparently works fine. I have retroarch and copied the relevant files to the usermods folder.

Is it possible to amend the commandline option for Sensible soccer in some way so it is possible to run it on the SNES mini?

**Comment by BodgerAndBadger** [comment]
Solved!!!!

Ok download the retroarch file.
Drag and drop the tetrarch_with_cores into Hakchi2 to the panel where you would add games.

Locate the problem game (Sensible soccer in this case) and click on it. In the right pane you can then see the text that runs the emulator , simply add --retroarch to the end.

Sync the games and bobbins!!

PS You can also use this to run NES and Megadrive games, Outrun / Golden Axe on the Snes anyone???

**Comment by gingerbeardman** [comment]
Until we can play the Amiga version, I prefer playing the MD version as you can see more of the pitch than in the SNES version.
