### ISSUE TITLE
Dragon Quest III not recognized as a non-supported game

### ISSUE THREAD

**Issue by Genju78** [ClusterM/hakchi2#738]
so hakchi does not automatically add --retroarch in cmd line.

**Comment by tashenawa** [comment]
I'm by no means an expert on this stuff, but I DID get Dragon Quest III, Star Ocean, Tales of Phantasia, Seiken Densetsu 3 (aka Secret of Mana 2), and Terranigma to all work perfectly. I'm using hakchi v2.21c (internal version 2.0.21.42) and uploaded the retroarch.hmod and selected it in the modules tab, then I put --retroarch at the end of the command line for each of these games. MAKE SURE there is a space between the end of the command line and the "--retroarch". Everything is working great now and I'm so happy to have these games working on my snes classic!! I could not get these games to work on the hakchi 2.21b version.

**Comment by Genju78** [comment]
Hi tashenawa, my point was to indicate that hakchi2 doesn't tag correctly dragon quest III as an un-supported games with native emu. 
For the games un-supported on native emu and well recognized as-so, hakchi2 automatically add the "--retroarch" in cmd line.
for DQ3 you need to add it manually.

**Comment by isage** [comment]
Japanese DQ3 works fine in native emu. DQ3 with english translation patch won't ever work on native emu, because it uses ExHIROM mapping, which is unsupported by canoe.

**Comment by Genju78** [comment]
Hi isage, 
now it's more clear. that's the reason why
Thank you !
