### ISSUE TITLE
Good Troop 

### ISSUE THREAD

**Issue by jcbelinda** [ClusterM/hakchi2#739]
Has anyone gotten Goof troop to work on snes classic?? 
I've downloaded many games that have worked except for goof troop. When I load the rom on my snes classic, it loads it into a black screen and then it doesn't go any further from there. After several minutes of waiting I press reset, and I get an error. 
Has anyone else gotten this game to work? It's one of my favorites

**Comment by DecanFrost** [comment]
you have to decrompress the file and hex edit it, and change a specific value from 15 to 14 (or vise versa, cant remember) its at the end of the file,  basically changing it from HiRom to SLowRom

**Comment by snessy7** [comment]
It was fixed in 2.21 a couple days ago.  You may have to delete Goof Troop from hakchi and re-add it, but it now detects it properly.

**Comment by rsn8887** [comment]
Yes I can confirm re-adding it worked for me. At first, Goof Troop was not working (C8 Error). Then, I deleted it from the hakchi games list, re-added it, and synchronized the games again. Now it works.

**Comment by jcbelinda** [comment]
Ok I just tried doing the conversion over to 2.21 and it didn't work at all for me. Not only did goof troop not work but it also corrupted all the original 21 games and wouldn't allow me to play them. I have no idea what happened.

**Comment by jcbelinda** [comment]
How exactly do I hex edit something on hakchi? I don't believe I know what that is or how to do it

**Comment by ghost** [comment]
You need a hex editor program. 

https://en.wikipedia.org/wiki/Hex_editor

**Comment by jcbelinda** [comment]
I've downloaded one and honestly it looks super foreign to me. So I'm just gonna forget about it for now. Don't want to mess anything up. 
And then I tried hakchi 2.21 b and c and the original games become corrupted for some reason. No clue what is going on

**Comment by Drakonas** [comment]
Goof Troop is stated as not working in the compatibility list. Use Retroarch to run it. https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/htmlview?sle=true#

This is not a discussion board. Keep these kind of questions on the forums or in a discord chat. This is for submitting bugs with hakchi. Rom incompatibility is a problem with Nintendo's code not Cluster's. Thank you.
