### ISSUE TITLE
Tetris & Dr. Mario freezes (overscan patch applied)

### ISSUE THREAD

**Issue by LeanderAT** [ClusterM/hakchi2#741]
I've applied the overscan patch for Tetris & Dr. Mario (posted on reddit I think)...but the game freezes. I only see the start menu and then either get a black screen or it freezes.

Any ideas?

EDIT Just tested the normal Rom...there's overscan but it's only a minor cosmetic glitch..the game is fully playable on my TV.

**Comment by Cuddles07** [comment]
Be sure you have a clean dump of the game and apply the hex edit _**after**_ hakchi makes the .sfrom. I did this and I have no freezing or black screen.

**Comment by LeanderAT** [comment]
Thanks! However, I'm a complete noob here...just found a patch file and used Flips to apply the patch. I don't know how to hex-edit and how to apply it after hakchi makes the .sfrom.

Or can I just add the fresh ROM to Hakchi and apply the patch there somehow?

**Comment by Cuddles07** [comment]
You have to run the game though Hackhi (Don't compress it) first to create an .sfrom then edit with a hex editor. I recommend using HxD Hex editor. To find the .sfrom of the game you need to go Documents > Hakchi2 > Games_SNES > and then find the folder the game is under. There should be a .sfrom there. Open it with the hex editor and find this line "0010040". It should be all the way at the bottom. The second value in the line should be a 15, you need to change it to a 14 and save the file. This should take care of the over scan issue and you will be able to transfer the game over to your SNES mini. This is how I did it at least.

**Comment by LeanderAT** [comment]
Thanks, I'll try that!

**Comment by Drakonas** [comment]
@LeanderAT Has this been resolved? Please respond or close the issue if so.
