### ISSUE TITLE
[SNES] - Error during game syncing.  

### ISSUE THREAD

**Issue by funkboy27** [ClusterM/hakchi2#742]
I didnt get a screenshot, so this may not be of help.

on SOME SNES consoles (2 so far), an error popped up while attempting to sync games.   I tried less games, original 21, just new games, and the error persisted.  If I tried on another SNES, it would work fine.

When syncing, an error would pop up while it was building folders.  Essentially the error said "Not a directory" with regards to the share/games folder.  After the error syncing was automatically cancelled.

I was able to get past the error by TELNETing into the SNES, and going into the SHARE folder.  Sure enough, there was a games file there, but it was supposed to be a folder!  

I deleted the games file, and created a games folder in its place.

Voila!  The system could sync the files after that.   Tested the SNES out and it seems to work perfectly.

This was on 2.20, 2.21b, and 2.21c.  Same issue on random consoles, but not all.

**Comment by ClusterM** [comment]
Do it: https://github.com/ClusterM/hakchi2/wiki/If-you-have-any-problems please

**Comment by Drakonas** [comment]
@funkboy27 has this been resolved? Please respond or close the issue if so.

**Comment by funkboy27** [comment]
It hasnt been resolved.  When I have time, I'll try and use the debug version to post the log.  It happens consistently when I use any build beyond 2.20.  I'm still able to fix it, but that GAMES file is being created at some point probably during the custom kernel upload. 

I'll try and do it today when i have a moment

**Comment by Drakonas** [comment]
I would advise uninstalling hakchi completely, flashing og kernel (making sure no md5 checksum errors occur) and then do a complete factory reset from your SNESC main menu (WARNING THIS WILL ERASE YOUR SAVES. Backup the saves before the uninstall of hakchi if you need them). Then flash custom kernel.

**Comment by funkboy27** [comment]
Okay cheers.  I believe it’s something to do with the hakchi folder as well. I didn’t want to have to rebuild my games list lol.

**Comment by Drakonas** [comment]
Wouldn't hurt. MAKE SURE TO BACKUP the dump folder above all else if you decide to reset your hakchi folder. It contains your OG kernel.

**Comment by Drakonas** [comment]
Has this been fixed @funkboy27 ?

**Comment by funkboy27** [comment]
I have reflashed original kernel and then flashed custom again using 2.21F. I am able to sync without issue.  
However, I believe the problem would still persist on a virgin console. 
 As I mentioned before, a GAMES file was created when it should have been a GAMES folder.  Since the GAMES folder already existed (i noticed that some files stayed on the device, despite flashing the original kernel back) it didnt have trouble loading the folder with games.

The next time I mod a friends console, I'll try a fresh install of Hakchi, and see if the issue persists.  I believe you're still on to something Drakonas, that it has something to do with my Hakchi folder, since I have just updated the files in it, instead of starting over fresh.

**Comment by Drakonas** [comment]
Performing a full factory reset after uninstalling hakchi and flashing og kernel, while erasing save files, usually fixes all these issues, as it removes leftover files from bad/old hakchi installs.

In any case, glad you got it fixed. Reopen this issue if you ever have problems again.
