### ISSUE TITLE
Error: shell command "tar -xvC

### ISSUE THREAD

**Issue by Gohan1990** [ClusterM/hakchi2#743]
Hi,

Since I decided to mod my mini Snes, I figured I would do the mini NES as well. SNES worked fine however whenever I try to add games to the mini NES It comes up with the attached error. I'm unsure if it's a bug with the latest software as I have tried some previous versions with no success.

Any advice or where to go from here would be much appreciated. 

![error](https://user-images.githubusercontent.com/32753395/31523986-29da41c2-affa-11e7-9654-1140409cd1db.PNG)

**Comment by msx2k** [comment]
652

**Comment by msx2k** [comment]
#652
