### ISSUE TITLE
[Question] Ability to use the NES classic mini emu on the SNES MINI

### ISSUE THREAD

**Issue by asturur** [ClusterM/hakchi2#744]
Hello and thanks for this nice tool.

I just go installed lib retro mod to use the nes games.
I was wondering if it would be possible to get inside the NES classic mini original emu and use it as an option to run nes games.

Would there it be any advantage? what is the  emu used by the NES classic mini?

**Comment by ghost** [comment]
Or ability to setup the dual boot from Hakchi2, and add NES games to the "NES side" of the dual bootable SNES
https://www.reddit.com/r/miniSNESmods/comments/76fr80/release_nessnes_classic_dualboot_mod_v03_no_more/?st=j8uqkuhv&sh=4ff77e68

**Comment by Drakonas** [comment]
@Hidki has answered this question. Video Guide: https://www.youtube.com/watch?v=Dahbyi3MQ08
