### ISSUE TITLE
Transferring original cart saves to the SNES Classic

### ISSUE THREAD

**Issue by meaninglessname** [ClusterM/hakchi2#747]
I dumped my Secret of Mana save file onto my PC and it works with emulators. I tried to see if I could get it to work on the SNES Classic. I think it's possible.

I opened FTP and went to the folder where cartridge.sram for Secret of Mana was located, then I replaced that file with my old save file (renamed as cartridge.sram). The machine wouldn't detect it. However, when I tried the reverse and opened ZSNES with a save that had been created on the SNES Classic...that worked flawlessly. If it can go one way, it should be able to go the other way.

I figure there must be something in the hash file that prevents my old save file from working, But I'm not a programmer and I wouldn't know how to go into the hash and "correct" it so it recognizes the save. But there must be a way....has anyone been working on this?

**Comment by Aks3n** [comment]
/u/cheese-demon over on reddit has just posted a tool for this.

https://www.reddit.com/r/miniSNESmods/comments/761m8j/srm_to_canoecloverclvs_converter/

**Comment by meaninglessname** [comment]
That's cool, but....I don't understand how to install it....

**Comment by ClusterM** [comment]
You need to export save from SNES Classic, unpack it as .tar.gz archive, replace save file, repack it back and import to SNES Classic.

**Comment by Drakonas** [comment]
@meaninglessname was this ever resolved? If so or if you have given up please close the issue.

**Comment by kamikazilucas** [comment]
how do you find the saves on ftp
