### ISSUE TITLE
Covers minor visual bug

### ISSUE THREAD

**Issue by ghost** [ClusterM/hakchi2#749]
I noticed that something about my covers seemes odd. Mine are 227x204px and it seems that the most right vertical pixel line is displayed at the left, next to the cover.  I also noticed that on the right side there is a 1px wide gap through which I can see the background of the menu. Is my cover size wrong or is that a bug?

**Comment by ghost** [comment]
Today I tested a variety of different size variations. It seems that the size of my original covers will always be resized incorrectly to either 227x204 or 228x203. When manually editing the small pictures and making them 228x204 it fits perfectly. 
I suggest that you could toggle a "resize to optimal size (228x204px)" option next to the browse pictures button.

**Comment by ghost** [comment]
Solution: Used https://bulkresizephotos.com/ to size all the covers to exactly 228x204px using settings png + black background. Now all the covers look fantastic. If someone wants to use mine, here you go: https://imgur.com/a/rLuL4

**Comment by Drakonas** [comment]
This should have been fixed with newer versions of Hakchi that addressed image sizing.
