### ISSUE TITLE
Can't add more than one game

### ISSUE THREAD

**Issue by Diovivente** [ClusterM/hakchi2#750]
In the Hakchi2 program, I'm unable to add more than one game. If I add a second game, or try to add multiple at the same time, it will replace the one with one other.

**Comment by Diovivente** [comment]
Nevermind, I fixed it. I figured, rather than delete this, I'll leave it up for anyone else having this "problem". It was my own stupidity. I wasn't adding the roms, I was adding their .zip files. I had to unzip them and then they would add perfectly.

**Comment by MrXCuci** [comment]
Individual zips should work though

**Comment by Drakonas** [comment]
Issues can be searched from the closed issues list. Closing.
