### ISSUE TITLE
Updating the portable version

### ISSUE THREAD

**Issue by Pito23** [ClusterM/hakchi2#753]
Hi everybody,

i have a question regard the updates of the portable version.

Usually i do the wiki guide: copy the contents of the newer version folder in the older one overwriting the contents must be overwritten.

But in the last version (2.21c) i had some issues both for the nes and snes, like some games doesn't work anymore, some original games corrupted and so on...

I've already fix all the issues, after some attempts, deleting and reinstalling game and, for the nes mini, formatting everything and reinstalling games and mods...

So, what's i'd like to know is; when a newer hakchi2 version came out, and after copy/paste new folder in the older one, have i to reflash kernels and reinstall all the mods FOR EVERY UPDATE? Or it's not necessary...?? Reinstall everithing everytime is a true nightmare especially for the arcade roms whis has different command lines and specific mods...

A clarification would be appreciated, thank you.

**Comment by ClusterM** [comment]
Hi.

You don't need to reflash kernel after update. Usually.

**Comment by Pito23** [comment]
Yes i know... usually, ok.

thx :)
