### ISSUE TITLE
Command line for built in games

### ISSUE THREAD

**Issue by shurp** [ClusterM/hakchi2#754]
Is this possible? would be nice to allow changing settings like --use-decorative-frame for the built in games

**Comment by MindController** [comment]
As a work around, you can deselect the default games and just readd them like your other roms.  That'll open up the option for the command line.

**Comment by Drakonas** [comment]
Yes @shurp the built in games are not able to be edited or deleted. They are read-only. At best you can add an extra copy of the game to edit and disable the included one like MindController said. But that uses extra space.
