### ISSUE TITLE
Shell command error on fresh install . flash

### ISSUE THREAD

**Issue by DecanFrost** [ClusterM/hakchi2#757]
Hakchi 2.21c
   New Kernal Dumb of SNES
    Flashed custom, Retroarch mode, Snes9x2010 mod & Extra Space mod
         Total Space 257.4mb

Flash over games 244.3mb,   get to very end and give error msgs.   
      also noticed total space amount went back to 232.7.mb ?? very odd

![22473419_10159476548810054_780844488_o](https://user-images.githubusercontent.com/26047042/31539521-c2d29af6-afd6-11e7-9d0f-02bb0c316a56.jpg)

**Comment by ClusterM** [comment]
Please try version 2.21.d.

**Comment by Drakonas** [comment]
@DecanFrost Has this issue been resolved?
