### ISSUE TITLE
Possible to trim down save state sizes at all?

### ISSUE THREAD

**Issue by TheTrainGoes** [ClusterM/hakchi2#758]
First off, ClusterM if you read this thank you for all your hard work on this!

I am curious to know if it is possible to trim down save states sizes at all.  

I have a combination of things on my SNES Classic (NA version):
- Preloaded games
- Additional SNES games in a folder
- NES games in a folder
- GB games in a folder
- GBA games in a folder

Combined, I have a total of 152.8MB used of an available 213.3MB

That 213.3MB already factors in a decent amount of save game files I have.

Save game files for SNES come in at around 2MB each, which means for the ROM + 4 save game states you are looking at around 9-10MB of storage used.

My first though was that the rewind feature was taking up a lot of space, so I tired some adjustments.  I used The Adventures of Batman & Robin for SNES.

The original arguments were:
 --volume 100 -rollback-snapshot-period 600

Leaving --volume 100 as it was, I changed  -rollback-snapshot-period 600 to
 -rollback-snapshot-period 100

This still left me with a few seconds of rewind time, but did not change the save game size by a noticeable amount.

I then removed  -rollback-snapshot-period 100 from the command line arguments altogether for the game, and it did not make a noticeable difference.

This was confirmed by looking at one of the SNES games I have running from RetroArch directly, which also has save game files that are around the 2MB mark.

Am I doing something wrong here?  It feels off that the save game states are larger than the game itself in a lot of cases.

**Comment by fchinaski-pt** [comment]
It is indeed odd that save files for simple games are so big. I'm not quite sure how much space internal saves (normal game saves within the game) occupy however. I don't plan to keep many save states for suspended games, but do the internal saves also occupy around 2MB each?

**Comment by gromber** [comment]
very interested in remove rewind and have more normal savestates size, that button could be used to select retroarch as alternative without using pc.

**Comment by Drakonas** [comment]
This has already been resolved by the latest Retroarch update as of writing (1.0C). The snapshots were not being compressed.

**Comment by gromber** [comment]
yes but not for native emulator.

**Comment by Drakonas** [comment]
@gromber There is not anything that can be done to compress canoe saves further. That is a Nintendo issue, not ours. The saves by default use that much.
