### ISSUE TITLE
C8 error on Genealogy of the Holy War

### ISSUE THREAD

**Issue by DJD2497** [ClusterM/hakchi2#759]
I have a rom that has an English translation of Fire Emblem: Genealogy of the Holy War. When I try to start it up, I get a C8 error. The rom works perfectly fine on the snes emulators, but I can't get it to work on the snes mini. It does have a .sfc extension too. And I have also only added like 9 games not including fire emblem. 
I did a little research and someone had a c8 error on the regular NES mini on start up because they used the wrong picture size. I'm not sure if this would be the case. 
Any ideas?

**Comment by DJD2497** [comment]
Update: it is a c7 error when I hit restart after boot up and a c8 when I shut it down after boot up. I also took the picture off of it and it still does not work.

**Comment by Drakonas** [comment]
This game is unsupported by Canoe. Use retroarch to load this game.
