### ISSUE TITLE
NES Mini not found Driver Issue?

### ISSUE THREAD

**Issue by cjXDD** [ClusterM/hakchi2#76]
Was trying to set up my NES mini with the roms and all that.
When I try to download/install the drivers, it says NES Mini not found. I have tried redownloading, disabling anti virus, restarting, etc. 
Whenever I plug it into my pc, it comes up as CLV-S-NESY. Any help would be appreciated, thanks.

**Comment by mlabarca** [comment]
Have you rub the tool and done the steps described? Holding down reset
button before turning it on, mainly.

**Comment by cjXDD** [comment]
Worked, thanks. Video I watched made it sound like I had to install drivers first. Doing the steps worked.

**Comment by radsker** [comment]
I can't get any connection between pc and mini
