### ISSUE TITLE
Error on Famicom Mini(v2.21c /transform from NES Mini using .hsqs file)

### ISSUE THREAD

**Issue by nekod-aisuki** [ClusterM/hakchi2#761]
1.Uninstall NES mini(v2.17d)
2.Flash custom kernel(v2.21c)
3.I transform NES Mini into Famicom Mini using .hsqs file.(v2.21c)
4.Add games and Synchronize(v2.21c)
5.Get a error and monitor black out(v2.21c)
#It reproduced twice.(error message1 & 2)
#I think that mods folder do not install.
![error01](https://user-images.githubusercontent.com/32777006/31557636-983878a2-b084-11e7-90b5-8ce9a176cdf9.jpg)
![error02](https://user-images.githubusercontent.com/32777006/31557647-9e49c430-b084-11e7-9dc9-e59da1833f67.jpg)

----ex----
1.Uninstall NES mini(v2.17d)
2.Flash custom kernel(v2.17d)
3.I transform NES Mini into Famicom Mini using .hsqs file.(v2.17d)
4.Flash custom kernel(v2.21c)
5.Add games and Synchronize(v2.21c)
6.Success!!

Sorry for my poor English.

**Comment by jaycaesar** [comment]
I've received this error too when trying to load games on a NES classic.

I used 2.17 and 2.21 portable and both result the same. 

I flash original kernel
then flash custom kernel
When I sync to add games, every single time it goes on "building the folder structure" I get the error.

**Comment by Drakonas** [comment]
You need to be uninstalling hakchi, flashing og kernel, then flashing custom kernel in that order.

**Comment by Drakonas** [comment]
@nekod-aisuki @jaycaesar are you still having trouble with this?

**Comment by nekod-aisuki** [comment]
I tried ver2.21f by your instruction.
I had no error!
Thank you!
