### ISSUE TITLE
Error for scyn (snes mini)

### ISSUE THREAD

**Issue by Redghost22** [ClusterM/hakchi2#764]
Hello !
I have a issue when i scyn the snes mini

I have two cases : After, I switch on the snes
- i heard the usb connection and then i stop pressing the button reset. I have the light so i stop
- or i continue to press and i don't have the light but after i heard the disconnection with a error.
I have this error : USB read error out: loTimeout

I got this with the last debug  hakchi2 :
Executing task: FlashKernel
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 128 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 12624 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Device detection successful
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 128 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 65536 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 49152 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
-> 48 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
Checking USB endpoints...
OUT endpoint found: 1
OUT endpoint maxsize: 64
IN endpoint found: 130
IN endpoint maxsize: 64
Trying to verify device
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
<- 32 bytes
<- 13 bytes
-> 32 bytes
<- 8 bytes
<- 13 bytes
-> 32 bytes
-> 16 bytes
<- 13 bytes
-> 32 bytes
USB read error: IoTimedOut   à com.clusterrr.FelLib.Fel.ReadFromUSB(Byte[] buffer, Int32 offset, Int32 length) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 208
   à com.clusterrr.FelLib.Fel.ReadFromUSB(UInt32 length) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 217
   à com.clusterrr.FelLib.Fel.FelRead(UInt32 length) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 240
   à com.clusterrr.FelLib.Fel.ReadMemory(UInt32 address, UInt32 length, OnFelProgress callback) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 319
   à com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 362
   à com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress) dans D:\Projects\C#\hakchi2\WorkerForm.cs:ligne 437
   à com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() dans D:\Projects\C#\hakchi2\WorkerForm.cs:ligne 542
   à com.clusterrr.hakchi_gui.WorkerForm.StartThread() dans D:\Projects\C#\hakchi2\WorkerForm.cs:ligne 281
USB read error: IoTimedOut   à com.clusterrr.FelLib.Fel.ReadFromUSB(Byte[] buffer, Int32 offset, Int32 length) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 208
   à com.clusterrr.FelLib.Fel.ReadFromUSB(UInt32 length) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 217
   à com.clusterrr.FelLib.Fel.FelRead(UInt32 length) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 240
   à com.clusterrr.FelLib.Fel.ReadMemory(UInt32 address, UInt32 length, OnFelProgress callback) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 319
   à com.clusterrr.FelLib.Fel.ReadFlash(UInt32 address, UInt32 length, OnFelProgress callback) dans D:\Projects\C#\hakchi2\FelLib\Fel.cs:ligne 362
   à com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress) dans D:\Projects\C#\hakchi2\WorkerForm.cs:ligne 437
   à com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() dans D:\Projects\C#\hakchi2\WorkerForm.cs:ligne 542
   à com.clusterrr.hakchi_gui.WorkerForm.StartThread() dans D:\Projects\C#\hakchi2\WorkerForm.cs:ligne 281

**Comment by Drakonas** [comment]
@Redghost22 has this been resolved. Please close this ticket if so.

**Comment by Redghost22** [comment]
No. I will try today on another computer

**Comment by Drakonas** [comment]
Is it working now @Redghost22 ?

**Comment by Drakonas** [comment]
Closing this issue as the OP has not responded.
