### ISSUE TITLE
SNES Classic - Flashing But Not Syncronizing Games

### ISSUE THREAD

**Issue by KingHippo27** [ClusterM/hakchi2#773]
So I've been on a mission to get Hakchi2 working on my SNES classic.  After my jobs tech support refused to let me install the SNES driver on my work laptop and decided to install VirtualBox on my personal Mac. 

The software is running smooth, recognizes my USB (set to USB 3). 
- When I place the device in flashing mode my instance of Windows 10 recognizes it, dumps the kernel and initiates and reports successful completion of the flash process. Note, I believe it works b/c I can now exit to the main SNES menu with "Select Down"
- When I try to sync the games it will hang at "Waiting for device"  then give me a plain  "Device Error" message.  I've also received another error that said something like unable to load device or something to that effect.  

I have reboot my Mac and the Virtual instance, installed the USB driver several times, and tried different USB cords without any success.  I found two similar previous issues:
1) A recent post from cluster recommended trying a different USB cable and/or port.  I've tried this (used my Kindle data cable) to no avail...  It's also important to note that I believe I am correctly flashing the kernel b/c the "Select Down" shortcut is now working on my SNES Classic, meaning I do not think the cable is the issue. 
2) Issue 332: seemed similar  (https://github.com/ClusterM/hakchi2/issues/332)
They also recommended new cord and I tried FlywithSean's advice without any luck either  
"When using VirtualBox after the custom kernel is loaded on delete the USB from the USB list on virtual box in the bottom right of the screen around your windows box and add it again when it says NES and not tablet in flashing mode"

Any advice?  Would love to get this amazing program working.

**Comment by Wopfi** [comment]
I have exactly the same problem. Flashing the SNES works but synchronizing games doesn't. It hangs in "Waiting for device" and next I get a "Device Error". Also, when I connect the SNES the green mark in the bottom left corner only stays green for about 15-30 seconds and then turns red. I'm using Windows 7 in VMWare Workstation as I'm on Linux. And I've tried different USB cables as well.

**Comment by rachop3no2** [comment]
I had the same problem using mac parallels. I solved my issue by doing all instructions with my laptop plugged in to the power cable. I am guessing here, but perhaps the SNES is not getting enough power without the power cable.

**Comment by PresD81** [comment]
I flashed my nes and lost the kernel I tried to reverse it but doesn't work now when I power it down it stays on, I found stock kernel to download and make dump folder but when I dump it says something about ram and won't synchronize games I can't even install the driver I'm not techs so can someone please help me with simple instructiones i dnt have the Nintendo USB cord or adapter it went mia

**Comment by KingHippo27** [comment]
Just Tried with the macbook connected to power and no luck...

**Comment by KingHippo27** [comment]
So... 
It seems my instance is seeing and writing to the SNES mini in flash mode when it sees it as "Onda Unverified Tablet in flashing mode".  I say this only bc "Select Down" now works, otherwise my mini looks exactly the same.
When I try to sync games by powering on the mini instead of entering flash mode my comp sees it as "Nintendo CLV etc..." and this is when I get the write error.

**Comment by pballada** [comment]
Same issue here, using Virtualbox, probably is something related to virtualization?

**Comment by KingHippo27** [comment]
Tried w/ the non-potable web installed version, still no luck.   

Mixmaster, I agree.  Its odd though, the VB instance does not have an issue viewing and writing when in flash mode, and the instance correctly identifies/labels the SNES as Nintendo when trying to sync which makes me think the drivers installed correctly (from other posts w/ driver issues they simply see the device as the clover name ie CLV-XXX).

Any other ideas?

**Comment by Wopfi** [comment]
As I'm using the portable version I tried my exact setup on my brother's computer on native Windows 7 and it worked without a flaw. Looks like this problem is indeed somehow related to virtualisation.

**Comment by ghost** [comment]
I had this problem as well until I enabled the USB 2.0 controller in my VirtualBox VM. You'll need to install the VirtualBox extension pack first; what you need to do is all described here: https://toadle.me/2017/02/03/how-to-add-more-games-to-you-nes-mini-classic-using-hakchi2-and-a-mac.html

**Comment by thezakattac** [comment]
Hey @KingHippo27 ,

I had this same exact issue - even following the link above provided by @adamschlag still gave me what I believe is the same exact problem that you did. When it is entering the sync game phase, are you turning on the SNES, waiting for it to appear in the USB list on the bottom right as "Nintendo (etc./whatever)", selecting that and then getting the error?

That's where I got locked up. I found a solution on another thread that worked instantly for me. On the Virtual Box settings (make sure you are actively logged out of the instance so you can change them), go to Ports/USB. Use the "Add filter" button, turn on the SNES, and you will see it appear on the bottom right, just like when you are trying to select it to sync games. This will add it as a filter that Virtual Box will remember. Now, go back and try - when you turn on the SNES, Virtual Box should now recognize it on its own, and skip over the error. I was ELATED when it finally worked - I hope it does the same for you!

**Comment by KingHippo27** [comment]
Thanks for all the help.  Have a newborn, but will have time to try tonight.
Zakattack - Did you end up using USB 2 or 3?

**Comment by KingHippo27** [comment]
Great news, Its working!  Now I just have to figure out how to get MAME running...
Some troubleshooting tips for Virtual Box:
1) This website is a good place to start
https://toadle.me/2017/02/03/how-to-add-more-games-to-you-nes-mini-classic-using-hakchi2-and-a-mac.html
2) When configuring VB, make sure you:
a) Install extension pack (prior to creating your windows instance)
b) Under settings add USB Port 2
c) Add a filter for your devices (subtle button to the right of the screen).  Add both nintendo/regular mode (by simply turning on your SNESC) and Flash mode (hold reset -> hit power -> release reset).  By doing this VB will automatically connect these devices when they come on

Other tips
- Use the web installer version of Hakchi 
- Ensure data micro USB cord 
- Some people have had success by plugging in laptop during this process

**Comment by tomh79** [comment]
Had the same problem. Could install custom kernel but not synchronize games. The solution that solved the issue for me: when the custom kernel is installed, shut down or pause the virtual machine, delete all usb devices in the settings of virtual box. then add both new (the one with just power on and the one while holding down reset) and resume. now it should work.

**Comment by unknownbreaker** [comment]
@ClusterM @KingHippo27 
Is it possible to add the VirtualBox tip to the FAQ for non-Windows users?
![image](https://user-images.githubusercontent.com/6026454/35226762-51342936-ff5a-11e7-81b3-282b76e6006f.png)

Originally asked about adding to README, but realized it belongs in wiki instead.

**Comment by DunnHatani** [comment]
@tomh79 This worked for me. I did notice that the SNES, (non-flashing mode) stopped auto connecting through virtualbox. So removing them and then re-adding them worked right away. I shut down the VM as opposed to suspending but didn't try suspend. I happened to be on USB 3.0 as that was one of the recommended fixes but it'd be worth a shot on USB 2.0 as well.

**Comment by subvertallchris** [comment]
Running Win 10 via Virtualbox on OSX, my fix was to delete the device through Device Manager and uninstall the driver when prompted, reboot, and reinstall the driver. It installed the driver and uploaded games immediately.
