### ISSUE TITLE
Add box art compression functionality using pngquant or OptiPNG (loseless)

### ISSUE THREAD

**Issue by electrocret** [ClusterM/hakchi2#774]
Add the option to have box art compressed with pngquant. It cuts the image size down by about 70%, which if you spread that over ~100 games, it adds up to a couple MBs of saving which is enough for an extra few games. I ran it on the boxart for my 147 Games, and saved 9.91MB.

For anyone interested in compressing their images until this is implemented you can download Pngyu (Pngyu is a Gui implementation of pngquant), and drag the Hakchi2 folder into the window then start compressing. It'll compress all png files it can find in the Hakchi2 folder (art, folder_images, games, games_snes).

Note: Boxart compression should probably remain optional because pngquant is a lossy compression format, and some people may not like the lowered quality.

**Comment by hoderer** [comment]
Thank you! A very good idea - every MB counts! :)
An implementation where this is up to the user would be great!

**Comment by MrXCuci** [comment]
Rather use OptiPNG, does lossless compression aswell and supports other lossless formats: http://optipng.sourceforge.net/

**Comment by electrocret** [comment]
OptiPNG is a good option as well. It doesn't get as good of compression as pngquant. I honestly haven't noticed any differences between the boxart before and after compressing it with pngquant besides the file size.

**Comment by hoderer** [comment]
I just tried it and it saved me 35 (!) MB of space of my 600+ games on the snes mini. And I'm totally satisfied with the picture quality. This is just great and in my opinion totally worth implementing!

**Comment by ArieKindicator** [comment]
Compressing artwork is a very good idea. I use RIOT for that matter and I reduce the color palette to 128 for the box art and 16 for the thumbmail. You can hardly tell the difference but the file sizes decrease tremendously.

Hakchi2 looks in the `art` directory for artwork that matches the filename of a game. However, hakchi2 reprocesses the images when adding it to the games directory and the result is increased file sizes for artwork (double in size). After adding a game all images in the game directory have to be reprocessed manually again to reduce the file sizes.

Hackchi2 should look in the `art` directory for matching artwork and when the dimensions of the images fit the requirements then those files should be added to the games directory without reprocessing the images.
