### ISSUE TITLE
Universal One Second Audio Lag

### ISSUE THREAD

**Issue by Zero042** [ClusterM/hakchi2#776]
After flashing to 2.21b and c I noticed that the entire system has a one second sound lag. The Main Menu, Original Games and Added Games all have this issue. If I flash the original Kernel then it goes away. What could I be doing wrong?

**Comment by TwrcGH** [comment]
I also have this issue after flashing 2.21c.  It hasn't had any previous hakchi versions on before just to rule out some sort of previous version causing issues.

Thanks.

**Comment by billiumw** [comment]
I have this issue on any version I flash, new or original. I am not sure what the issue would be.

**Comment by billiumw** [comment]
Now i have this issue when flashing the original kernal back, odd.

**Comment by Drakonas** [comment]
@Zero042 @billiumw @Lissard This can be addressed by backing up your saves, performing an uninstall of hakchi from the SNES Classic using the hakchi tool, then flashing og kernel making sure you do not get a md5 checksum error, and performing a factory reset from the SNES Classic main menu (WILL ERASE ALL SAVES). Then flash custom kernel again afterwards. There are most likely residual files from bad/old hakchi installs on your systems.

**Comment by Drakonas** [comment]
No response from OP. Closing this ticket until they respond.
