### ISSUE TITLE
Upgrade from hakchi 2.20 to 2.21 

### ISSUE THREAD

**Issue by jcbelinda** [ClusterM/hakchi2#777]
I've tried several times to get the new hakchi to work but it's not working for me. 
Everyone I use hakchi 2.21, the original games will not work. Every game I've loaded to the snes works, but not the oringal 21. These games have a black border with a crack in the middle. 
What am I doing wrong? 
I've copied the kernel dump over. I've even tried dumping original kernel and then flashing a custom one and it won't work. When I go back to 2.20 it works flawlessly.

**Comment by JackWitherell** [comment]
I fixed this by Uninstalling and then re-patching the kernel. Issue still stands, whatever differences between 2.20 and 2.21 exist make it so you have to reinstall the kernel to get back original games.

**Comment by JackWitherell** [comment]
By the way- this process does not delete save states or save data from your original games. Not sure about custom games. I didn't check.

**Comment by pitbzury** [comment]
custom game save stays too, if you want to delete them, try the game save-state manager in tools

**Comment by Drakonas** [comment]
@jcbelinda did you ever resolve this? Please close the ticket if so.
