### ISSUE TITLE
Original games not working (C7 error) + covers gone?

### ISSUE THREAD

**Issue by Siedjeey** [ClusterM/hakchi2#778]
So I just updated to the 2.21 verions and also installed the RetroArch on my SNES mini and added some Genesis games as well but for some reason now it no longer shows the covers of the original games and they don't work anymore (C7 error)? See below

**Comment by Siedjeey** [comment]
This is how it looks now... Any help?

![b13ee606-4836-4c5c-86c1-f4c91c73eda9](https://user-images.githubusercontent.com/21155453/31575198-2869a50c-b0e1-11e7-84e1-21ed4ea29e3e.JPG)

**Comment by AlanVis** [comment]
same here. 
covers and original games doesn't work any more.
error C7

**Comment by AlanVis** [comment]
Solved.

a) Nand Dump (for backup)
b) Reflashed original kernel
c) Flashed modified kernel

**Comment by ClusterM** [comment]
Nand dump is useless for backup. Original kernel flash too.

**Comment by AlanVis** [comment]
But solved the problem

**Comment by Siedjeey** [comment]
So only flashing modified kernel should solve the issue as well? Try it tomorrow
