### ISSUE TITLE
game transfer 2.15 to 2.21

### ISSUE THREAD

**Issue by Robo-1982** [ClusterM/hakchi2#779]
First of all forgive me for the bad English.

I'm using hackchi2.15 for nes, but now I want to use 2.21 for the snes. I want my games to transfer from 2.15 to 2.21. How do I do that? Copy - paste into the games_snes folder doesn't work. There's something different in the command line, but I can't figure out what I'll have to do to fix this. Anyone???

**Comment by ClusterM** [comment]
You need to proceed games again, you can't just copy them.
