### ISSUE TITLE
RetroArch

### ISSUE THREAD

**Issue by abijanfar** [ClusterM/hakchi2#78]
Official support of madmonkey's RetroArch mod without overriding 1942 rom.

**Comment by ClusterM** [comment]
Me and madmonkey are working on mod system now.

**Comment by debtslave** [comment]
You guys are awesome Keep up the good work

**Comment by puregamingnut** [comment]
wow you guys are the best keep up the great work i have not tried installing retroarch yet will wait until you guys make it stable but fully enjoy my nes mini with all the extra roms

**Comment by bfluryx1234** [comment]
Done with 2.12.  Issue can be marked closed.
