### ISSUE TITLE
SMWC Production - No Player 2 Being Deteced

### ISSUE THREAD

**Issue by zimmertr** [ClusterM/hakchi2#783]
I've just started playing An SMWC Production with my girlfriend and we noticed that the game is not allowing Luigi to spawn at the beginning. Is the built in emulator somehow not detecting the second controller port for this romhack?

**Comment by The-MAZZTer** [comment]
Make sure you have "Two players, simultaneously" selected in the game settings in hakchi. If it is set to one player the second controller is disabled.

Hakchi has a database of known games but it does not include ROM hacks AFAIK; you'll have to configure those yourself in the game settings.

**Comment by zimmertr** [comment]
Closing as it's not likely a software issue. If anyone has any insight I would appreciate it as a further comment.
