### ISSUE TITLE
delay on reset after enabling "remove_thumbnails"

### ISSUE THREAD

**Issue by Ferkner** [ClusterM/hakchi2#786]
After upgrading to 2.21c and reflashing the snes mini, i deleted the small thumbnail images from the games_snes folder as well as enabling "remove_thumbnails"in the modules. This and dividing the games into pages to avoid the C8 error on powering down are the only difference from the first time. 

Now when i reset to the home menu, whatever screen I was on in a game will stay there for a good five seconds or more. The menu music will play for a few seconds before the screen changes from the previous game to the menu.

**Comment by ClusterM** [comment]
Already fixed in 6ee1d902992d786fe6c8d9ec8f151f1c3bcb04be

**Comment by Ferkner** [comment]
How do I implement this fix?

**Comment by Ferkner** [comment]
Anybody?

**Comment by ClusterM** [comment]
Reinstall it.

**Comment by Ferkner** [comment]
reinstall what? Hakchi2? Reflash from scratch? I just did it two days ago, and your fix was 5 days ago?

**Comment by ClusterM** [comment]
Reinstall remove_thumbnails...

**Comment by Ferkner** [comment]
That didn't help. I uninstalled it, then reinstalled it and it was the same thing. Then I re-flashed from scratch using 2.21d, and have the same issue. Whether the games are in folders, pages, or all on the same page, there is still a lengthy delay. What should the delay normally be? For me right now it's over five seconds.

I don't know if it's because I deleted all the thumbnails from the individual game folders, but this doesn't seem to be an issue for anyone else.

**Comment by nekonall** [comment]
i started having the same delay but only on turning the system on after that its fine

**Comment by Ferkner** [comment]
I uninstalled the remove thumbnails mod and put thumbnail images back in each game's folder. The delay isn't nearly as bad before, but there is still a delay. I guess it's normal since it's basically a small computer rather than an instant-on console.

**Comment by Drakonas** [comment]
@Ferkner Cluster was saying to uninstall hakchi, update your hakchi program using the instructions in the FAQ on the wiki page here, and then reflash the custom kernel with the new version and then install your mods again.

**Comment by Ferkner** [comment]
I ended up doing that in the end, and it didn't really help. I'm chalking up the delay tri the fact that i loaded a lot of games and that it's a mini computer that doesn't work instantly like a console.

**Comment by Drakonas** [comment]
If you have more than 30 games in a folder that is probably your issue. You need to separate the games into different folders. It helps.

**Comment by Ferkner** [comment]
It might help but it looks like crap and is annoying to navigate. Maybe I'll make custom folders for genres and add folder icons.

**Comment by Drakonas** [comment]
That's what I do. :) You'll want to have more than 12 games per folder or the scrolling will be screwy.

**Comment by Drakonas** [comment]
@Ferkner did you ever resolve this? Please close this issue if so.

**Comment by Ferkner** [comment]
No, but I'll close it anyways.
