### ISSUE TITLE
New default settings for Retroarch seem incorrect?

### ISSUE THREAD

**Issue by jsvrson** [ClusterM/hakchi2#787]
Love the scanlines and borders in Retroarch now, but the games are overlapping with the borders. Is this the price to pay for pixel-perfect scanlines, or can the size be adjusted without breaking the scalene placement?

**Comment by MrXCuci** [comment]
Overscan crop is disabled by default now, see release notes.

**Comment by ClusterM** [comment]
This is NOT RetroArch repo.
