### ISSUE TITLE
[SNES] Let's talk about Satellaview support

### ISSUE THREAD

**Issue by codex785** [ClusterM/hakchi2#789]
Has anybody managed to launch Satellaview games through canoe?
I always got C7/Black Screen
Thanks a lot

**Comment by shmoinkle** [comment]
I had to use retroarch & snes9x2010 with the BS Zelda games. Otherwise, same issue.

**Comment by Drakonas** [comment]
Satellaview games will probably never launch through Canoe.

**Comment by Drakonas** [comment]
This is not going to be possible. Only retroarch will be able to support this.
