### ISSUE TITLE
Mario Adventure ROM?

### ISSUE THREAD

**Issue by tjm694** [ClusterM/hakchi2#79]
I have patched several NES ROMS with the Mario Adventure hack.  I cannot get a good copy to play on the NES Mini.   Every time I add one, I keep getting blocky characters.  Any ideas or patch?

**Comment by tjm694** [comment]
This is with Hakchi2 2.11

**Comment by baconcow** [comment]
This is an emulation issue, not a hakchi2 issue. Please see [this reddit thread](https://www.reddit.com/r/nesclassicmods/comments/5mpyxg/is_my_rom_x_working_megathreadconsolidation/), for assistance.
