### ISSUE TITLE
 [SNES] "C7 error" for Secret of Mana & Yoshis Island [German language versions] :-( Is it possible to run without RetroArch?

### ISSUE THREAD

**Issue by Tshakka** [ClusterM/hakchi2#792]
I know that NTSC Games should be prefered to use for the SNES classic Mini but i strongly want to play Secret of Mana in german again, since this is the version that i know from my childhood.

**The german version has really iconic (and trashy) translations** to it "Pogopuschels" (the rabbids), Goblins watching the "Lindenstraße" (which is an old german soap opera). Something that the englisch texts cant give me :(

**I got many PAL Versions to work properly** by deleting the headers of the roms and applying the **"to NTSC" and "anti Region lock" patches** to them (https://evilgames.eu/snes-pal-to-ntsc.html).
The german version of "Aladdin" for example runs without any sound troubles after that, maybe because it is played in 60Hz afterwards

I read in the google compatibility list that it is possible to run the EU version of SoM by applying the NTSC patch: (https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/edit#gid=2014317767)

For me (german version) it doesnt work at all. Unfortunatley still the "C7 error" comes up. (compressed or uncompressed rom and i tried two different rom versions, sfc/smc)

Can anyone help out here? As i dont want to use Retroarch for just this game. I dont care if the texts in the starting screen are a little washed out, since this just makes 0,5% of the game. i just want to play it in german.

Thanks in advance :(

**Comment by ClusterM** [comment]
1. Try latest version, import those games again.
2. Try select game, press Ctrl+Alt+E, will all fields with zeros and re-sync.

**Comment by Tshakka** [comment]
Cool thanks it works for Secret of Mana! Even without display format issues when it is patched to NTSC. Yoshis Island doesnt work but thats okay, i can play that one in english.
