### ISSUE TITLE
Play Nes, Megadrive etc. games on SNES Mini?

### ISSUE THREAD

**Issue by LeanderAT** [ClusterM/hakchi2#793]
How you can play Nes, Megadrive etc. games on the SNES Mini? The games are detected by Hakchi but won't run. Nes games jump to a black screen and go back to main menu/game selection screen).

What do I need to play them?

What about Gameboy (GB, GBC, GBA) games? Can you play them with 2 players?

**Comment by hoderer** [comment]
Please ask this kind of questions here:
https://gbatemp.net/threads/hakchi2-nes-mini-very-simple-pimp-tool.456256/page-1

**Comment by LeanderAT** [comment]
Thanks!

**Comment by ClusterM** [comment]
Read FAQ.
