### ISSUE TITLE
Only NES games not working on SNES mini

### ISSUE THREAD

**Issue by LstoneM** [ClusterM/hakchi2#795]
I've been using hakchi 2.21b ok on my SNES mini. Everything's working well ( Snes, Master system, mega drive, N64 & gameboy) but I've just added NES games & none of them are working. I just get a blank screen for a few seconds then it returns to the menu. I've done a full factory reset & I'm running with loads of spare memory. Any ideas how I can fix this problem? Thanks for your help.

**Comment by devedse** [comment]
Same here :)

**Comment by MrXCuci** [comment]
Upgrade to latest version and latest Retroarch and try again.

**Comment by devedse** [comment]
Installing RetroArch fixed it for me, might be good to add something about that to the README.MD :smile:

Edit: Fixed autocorrect

**Comment by LeanderAT** [comment]
Thanks, I will try that! Where can I get retroactive?

Could you also help me with Mame games please? Tutorials explain how to start Neogeo games...

I want to play Rodland, Bubble Bobble 2 and Wizard of Wor.

How should I edit the command line? The games don't have a bios I think. BB uses Taitofx...others use only a driver but I cannot find the driver in Mame.

PS Bubble Bobble on NES has some flickering...how do you fix it?

**Comment by LstoneM** [comment]
I've updated to Hakchi 2.21d & re done the whole process with the most up to date retroarch. I'm still having the same problem. Everything is working fine except NES games which just bring up a blank screen then return to the menu. Any other ideas what might be causing this?

**Comment by LeanderAT** [comment]
Maybe the NES game does not work. 
My user_mods folder contains retroarch.hmod and the core files...moreover, RetroArch is in the list of games...I pasted the folders games and mods in the Hakchi folder. Then it was added. Maybe you don't have all these steps?

**Comment by electrocret** [comment]
Try using different ROMs. I had a similar issue when using No-Intro roms. 
[https://github.com/ClusterM/retroarch-clover/issues/103](https://github.com/ClusterM/retroarch-clover/issues/103)

**Comment by LstoneM** [comment]
Thanks! I've changed the ROMs I was using & it's all working fine now. My no-intro NES ROMs were the problem.
