### ISSUE TITLE
Games download but dont work

### ISSUE THREAD

**Issue by Litfam877** [ClusterM/hakchi2#796]
C8 error pops up after console is turned off. Games show up on console but when clicked it just turns to black screen then goes to home screen.

**Comment by MrXCuci** [comment]
Retry from the beginning and use games in folder option.

**Comment by Drakonas** [comment]
@Litfam877 please respond or close this issue if it has been resolved. Thank you.

**Comment by Drakonas** [comment]
Closing this as the OP has not responded.
