### ISSUE TITLE
saner install directory?

### ISSUE THREAD

**Issue by Linkinworm** [ClusterM/hakchi2#799]
Is is possible to choose our install directory for hakchi? It took me what seemed like forever to find it was in appdata folder in another random named folder, would like if i could install to program files or anywhere else really

**Comment by Drakonas** [comment]
You never want to put those files in program files, or you will have problems. Instead you should be downloading the hakchi2.zip (not the web installer) and extract it somewhere in your user directory, like Downloads. You can move the dump and games_snes folder from the appdata folder into the extracted hakchi2 folder after you do that.

**Comment by Drakonas** [comment]
@Linkinworm Please respond or close the ticket if this has been resolved. Thank you.

**Comment by Linkinworm** [comment]
Sorry I will close it but before I do 1: why is that folder a bad idea? 2: maybe we could just get an option on the installer to select a directory for everything instead? I had a second hdd set up as basically a copy of the windows folder structure with "program files, program files (x86) just so sanity sake 3: when updating hakchi whats the best way to copy over files just move everything over from a new build or anything specicic I can just move out like the exe?

**Comment by Drakonas** [comment]
@Linkinworm Program files folders in windows are locked down and prevent files from writing certain files there. They are only designed for software that actually installs with an installer, but then the data needs to be stored elsewhere like AppData. Programs typically can't write data to their program directory unless run as administrator, which produces more problems if you decide to run the program later as a non-administrator.

Running the non-web-installer version from a folder in your user folder like Downloads is advised to prevent permissions issues preventing files from being written. I've already seen someone's hakchi get flashed with custom kernel without ever writing the OG dump to the folder.

The best way to update is to uninstall hakchi with the old version and then flash og kernel; then, close hakchi and delete all folders but games_snes, config, user_mods, and dump, then overwrite all files with the new version, run hakchi and flash custom kernel.
