### ISSUE TITLE
Hakchi should prevent or warn users when syncing games could cause c8 errors

### ISSUE THREAD

**Issue by The-MAZZTer** [ClusterM/hakchi2#800]
The FAQ covers recommendations for game counts in folders: https://github.com/ClusterM/hakchi2/wiki/FAQ

Hakchi should warn you if you are putting too many (or even too few) games in folders. Otherwise users who are not familiar with the FAQ will think hakchi is not flashing their games properly.

There are numerous issue reports about c8 issues, likely from users who are running into this problem.

My suggestions:

- If you put over ~~45~~ 30* items in a folder (including implied Back item) in the Folders Manager dialog, highlight the node in the treeview (maybe put a warning icon instead of a folder icon and make the node text red). Make the tooltip indicate that thumbnails will not show up correctly due to too many games.
- If you put over 90/50 items (depending on NES/SNES mini, and including any implied Back item), put an error icon in the treeview on the folder and color the node text red. The tooltip can inform the user that their device may encounter lock ups and C8 errors when using the menu with the configuration. If the user tries to sync anyway, hakchi should give them a confirmation dialog stressing what will happen, or even not allow them to sync at all.
- If the user has less than 12 items in a folder, show a warning the same way as the first bullet point, but the tooltip should indicate scrolling may be glitchy in the menu.

For "warning" and "error" icons I am thinking of the standard Windows messagebox icons, something like that style.

Alternatively, you could leave the Folders Manager as is, but replace the OK with a "Validate" button. This button would open another dialog (or you could rework Folders Manager into a wizard dialog with two pages) that would check for all the above conditions and display a checkmark, a warning mark, or an error mark.  Accompanying text would tell you the possible consequences for failed validation. The user may or may not be allowed to continue syncing on error (as per my suggestions above). On error they would be allowed to go back and fix the problem.

I would prefer the inline validation method myself, as it gives the user immediate feedback so they can fix it as they're building their folders, instead of wasting time on a configuration that won't work.

\* The FAQ says 45 but my NES Classic can only hold 32 thumbnails in the bar before it overflows. Limit to the standard 30 (or 31 including back button) to keep it looking nice?

**Comment by ClusterM** [comment]
Good idea.
