### ISSUE TITLE
C7 On all Original Games

### ISSUE THREAD

**Issue by zelionthunder** [ClusterM/hakchi2#802]
Alright I've been working on this for a bit, read over every related article I could find.
I have flashed back to original kernal on my SNESc multiple times.
From there I flash custom kernel, then add in retroarch with cores. Sync games, all added games work fine, just originals give me C7 error when launching(they appear as they should, no broken image icon).
Original Games is checked when syncing, and all games are checked as well. Having this issue on 2.21c and 2.21d. I don't think I'm missing any steps, but at this point I'm bit frustrated and could use a outside view on it.

**Comment by DecanFrost** [comment]
did you solve ?

**Comment by zelionthunder** [comment]
I believe it had something to do with residual file that I had moved over from another version of hakchi.
Started fresh, tested small and it worked. So then just moved games over.
