### ISSUE TITLE
[Request] USB Hub driver support for additional external USB devices

### ISSUE THREAD

**Issue by patoJamriska** [ClusterM/hakchi2#803]
The idea behind this is to add external storage to the nes/snes mini with the use of a hub. I have not had a chance to fully check the kernel of the source code to determine if it is possible to add such feature, but considering is linux based I can't see why this shouldn't be possible, just a matter of getting the drivers to work, be able to mount the other ports, and we can add external storage as well as expand the number of controllers if needed on other portions of retroarch. The hub should still be able to provide power over to the unit as normal.

**Comment by ClusterM** [comment]
No, it's impossible.
