### ISSUE TITLE
SNES Mini changes game order whenever a game is selected

### ISSUE THREAD

**Issue by green1012red** [ClusterM/hakchi2#805]
I have a feature request. Can we make the SNES Mini keep games in order? By default, it rearranges the order of games every time a game is selected. Whenever a game is selected, it puts it at the beginning of the line. Maybe with 21 games it's okay, but as more games are added, it becomes hard to find a specific game. Alphabetic would be preferable. Even better would be to let us choose the order. (For example, I want "Castlevania" to sort before "Castlevania 2". I don't want to have to rename "Castlevania" to "Castlevania 1" in order to get it to sort correctly. Or maybe I want "Contra" and "Super C" next to each other).

Thank you SO much for making this app for us! I LOVE adding more games to the SNES Mini.

**Comment by Robo-1982** [comment]
Just use 'select' to re-arrange the games. Change it into 'select bij title', your games are now in alphabetical order.

**Comment by green1012red** [comment]
Omg, THANK YOU!
