### ISSUE TITLE
Issue with Synchronize selected games NES/SNES Mini

### ISSUE THREAD

**Issue by SieOne** [ClusterM/hakchi2#806]
Having problems Synchronizing my SNES roms, using Hakchi 2.21b.
Have dump my kernel, added my rom where it prompted me to flash my custom kernel (hold down reset on my MiniSNES and power on while still holding down the rest button), got my cover art, all good for far, but when I go to select Synchronize selected games NES/SNES Mini I get a prompt saying Connect your NES/SNES Mini, turn on, and install driver, but when IK click on the Install driver nothing happens.

Has anyone else had this?

**Comment by ClusterM** [comment]
You can try to find answer in FAQ.

**Comment by SieOne** [comment]
Have had look on the FAQ ClusterM, but to no avail. Have look on line, and on numerous videos but no one seems to of run into this trouble. Have tried rebooting, new USB cable but no joy.

**Comment by qingjian0** [comment]
Had the same problem, tried a diffrent PC with fresh installed win10 and everything works well. Just to mention, this PC that gave me the problem used o work perfect flashing nes mini and snes mini but all of a sudden it stopped working, tested diffrent usb ports and diffrent cables but same freezing issue. Try a fresh install of win10 or another PC.

**Comment by SieOne** [comment]
All good, downloaded 2.21d and it worked no problem. Thanks for the input.

**Comment by Garymf** [comment]
I also get the problem. I am using 2.21d , after flash the kernel, and google pic & adding game, is connect then got the problem

shell command "tar -xvC /" returned exit code 1:tar: can't open '._bin':Read-only file

Anybody can help? I just got one computer at home

**Comment by Drakonas** [comment]
Closing this issue as the OP's problem was fixed. @Garymf should create a new issue if they are still having problems.
