### ISSUE TITLE
Option to chance original game names 

### ISSUE THREAD

**Issue by THE-PBV** [ClusterM/hakchi2#808]
A option to chance the original game names
like yoshi`s island to Super mario world 2 : yoshi`s island.

**Comment by nekonall** [comment]
lol i agree it kills the ocd ...

**Comment by Drakonas** [comment]
Unfortunately it is impossible to edit the included games on the SNES Classic. They are read only. The only option is to add an extra copy of them into Hakchi, rename them, and disable the originals (which will use up your rom storage as you cannot delete the originals)
