### ISSUE TITLE
Lost my original SNES Classic Kernal 

### ISSUE THREAD

**Issue by Skylance87** [ClusterM/hakchi2#811]
Had to reformat my pc and lost my kernal does anyone have a kernal i can download i cant seem to find any listed on search

**Comment by fpmpaolo** [comment]
I have one on my Google Drive but...are you sure it works for you? 
If so, give me your mail address and I will link it

**Comment by Skylance87** [comment]
as long as its the US Kernal yes it will work for me and thanks my email is {PRIVATE EMAIL REDACTED @Drakonas}

**Comment by SassyFish256** [comment]
I also lost mine, if you could email the link to {PRIVATE EMAIL REDACTED @Drakonas}, that would be awesome, thanks.

**Comment by fpmpaolo** [comment]
I have the EU kernel. I'm from Italy

**Comment by ghost** [comment]
Interested in your EU kernel fpmpaolo.

**Comment by jimfoxington** [comment]
Could I get a copy of the EU? {PRIVATE EMAIL REDACTED @Drakonas}

**Comment by ghost** [comment]
The stock kernel md5sum for Europe is:

- d76c2a091ebe7b4614589fc6954653a5
- c2b57b550f35d64d1c6ce66f9b5180ce
- 0f890bc78cbd9ede43b83b015ba4c022

Look through this for more kernel checksums of other regions (ctrl f one of the above checksums):

https://github.com/ClusterM/hakchi2/blob/b542b5c6189b125f58203c59f5325a584c931291/WorkerForm.cs

**Comment by fpmpaolo** [comment]
Ciao a tutti!

You can download the dump of the EU kernel from here
{COPYRIGHTED CONTENT REDACTED @Drakonas}
don't worry it's a Google Drive link.

You can check the md5sum in here
http://onlinemd5.com/

**Comment by ghost** [comment]
Thank you very much

**Comment by Drakonas** [comment]
This is not the place to ask for illegally distributed copyrighted content. Keep this to private messages or forums that allow sharing of pirated material. Closing.
