### ISSUE TITLE
C8 error when shutting down Snes mini

### ISSUE THREAD

**Issue by Mathbeach** [ClusterM/hakchi2#817]
Like the title say always getting a c8 error while shutting down snes mini have to disconect power to shut it off?? Whats causing that?

**Comment by ClusterM** [comment]
Version number? Can you send me NAND-C dump?

**Comment by Ferkner** [comment]
I've read that it's from having too many games on the one page instead of splitting them up in pages or folders.

**Comment by fpmpaolo** [comment]
So even in miniSNES we have to divide games into several folders?

**Comment by ClusterM** [comment]
Read FAQ please...

**Comment by Mathbeach** [comment]
Probably right cause i put all game on the startup menuno folder can this error break my mini long term?

**Comment by ClusterM** [comment]
No, it will not brick.
