### ISSUE TITLE
Problem with windows 10

### ISSUE THREAD

**Issue by Poulpi06** [ClusterM/hakchi2#819]
hi,

the "v2.21d (internal version 2.0.21.52)" doesn't work on Windows10 64bits,

on start, the download of .net Framework 3.5 failed with the 0x80070005 error.

can you fix it

************************************
Component .NET Framework 3.5 SP1 has failed to install with the following error message:
"A failure occurred attempting to install .NET Framework 3.5 SP1."

The following components failed to install:
- .NET Framework 3.5 SP1

See the setup log file located at 'C:\Users\*\AppData\Local\Temp\VSD47CA.tmp\install.log' for more information.
************************************
install.log:

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package '.NET Framework 3.5 SP1', phase BuildList
Reading value 'SP' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v3.5'
Unable to read registry value
Not setting value for property 'DotNet35SP'
The following properties have been set for package '.NET Framework 3.5 SP1':
Running checks for command 'DotNetFX35SP1\dotNetFx35setup.exe'
Skipping ByPassIf because Property 'DotNet35SP' was not defined
Result of running operator 'ValueEqualTo' on property 'AdminUser' and value 'false': false
Result of running operator 'VersionLessThan' on property 'VersionNT' and value '5.1.2': false
Result of running operator 'VersionEqualTo' on property 'VersionNT' and value '5.2.0': false
Result of running operator 'ValueEqualTo' on property 'ProcessorArchitecture' and value 'IA64': false
Result of checks for command 'DotNetFX35SP1\dotNetFx35setup.exe' is 'Install'
'.NET Framework 3.5 SP1' RunCheck result: Install Needed
EULA for components '.NET Framework 3.5 SP1' was accepted.
Copying files to temporary directory "C:\Users\*\AppData\Local\Temp\VSD47CA.tmp\"
Downloading files to "C:\Users\*\AppData\Local\Temp\VSD47CA.tmp\"
(15/10/2017 18:30:41) Downloading 'DotNetFX35SP1\dotNetFx35setup.exe' from 'http://go.microsoft.com/fwlink/?linkid=118076' to 'C:\Users\*\AppData\Local\Temp\VSD47CA.tmp\'
Download completed at 15/10/2017 18:30:42
Verifying file integrity of C:\Users\*\AppData\Local\Temp\VSD47CA.tmp\DotNetFX35SP1\dotNetFx35setup.exe
WinVerifyTrust returned 0
File trusted
Running checks for package '.NET Framework 3.5 SP1', phase BeforePackage
Reading value 'SP' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v3.5'
Unable to read registry value
Not setting value for property 'DotNet35SP'
The following properties have been set for package '.NET Framework 3.5 SP1':
Running checks for command 'DotNetFX35SP1\dotNetFx35setup.exe'
Skipping ByPassIf because Property 'DotNet35SP' was not defined
Result of running operator 'ValueEqualTo' on property 'AdminUser' and value 'false': false
Result of running operator 'VersionLessThan' on property 'VersionNT' and value '5.1.2': false
Result of running operator 'VersionEqualTo' on property 'VersionNT' and value '5.2.0': false
Result of running operator 'ValueEqualTo' on property 'ProcessorArchitecture' and value 'IA64': false
Result of checks for command 'DotNetFX35SP1\dotNetFx35setup.exe' is 'Install'
'.NET Framework 3.5 SP1' RunCheck result: Install Needed
Verifying file integrity of C:\Users\*\AppData\Local\Temp\VSD47CA.tmp\DotNetFX35SP1\dotNetFx35setup.exe
WinVerifyTrust returned 0
File trusted
Installing using command 'C:\Users\*\AppData\Local\Temp\VSD47CA.tmp\DotNetFX35SP1\dotNetFx35setup.exe' and parameters ' /lang:enu /passive /norestart'
Process exited with code 1603
Status of package '.NET Framework 3.5 SP1' after install is 'InstallFailed'
************************************

**Comment by DanTheMan827** [comment]
Failing to install .NET has nothing to do with Hakchi

**Comment by ghost** [comment]
I formatted my PC and performed a fresh install of Windows 10 on it last year. When installing Windows 10 (instead of merely upgrading from Windows 7 to Windows 10), some versions of NET Framework are not already installed in the OS. To install the additional versions of NET Framework, you have to enable them through the “Turn Windows Features On or Off” window. I provided a link below that helps you locate this window in Windows 10.

Note that when installing the additional versions of NET Framework, your PC will need to be online to download and install additional files.

https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10

**Comment by Turom421** [comment]
I use windows 10 64 bit and all versions of Hakchi work.

**Comment by Poulpi06** [comment]
@DanTheMan827 : ok, but i don't need .net install, but hacki need it.

@maskedmaniac : thanks, i will try this. 3 comments, and just one good answer, thanks . Regards

@Turom421 : thanks, that's help me a lot.
