### ISSUE TITLE
Selecting folder reloads main screen

### ISSUE THREAD

**Issue by wbechard** [ClusterM/hakchi2#82]
I have 58 games installed on a freshly downloaded 2.11.

I have a folder generated that lists Ice Climber - Zelda II, but when I press A or Start, the main screen reloads with the original games from A to I.

**Comment by debtslave** [comment]
had this problem as well. What you need to do is completely uninstall hakchi2 from the system and restore to original settings. then re-flash.

**Comment by wbechard** [comment]
Thank you for the insight!  

So start with a fresh unzip of hakchi2, immediately flash original kernel, and (after nesc reboot) begin loading games with this new hakchi?

Do I have that correct?

**Comment by debtslave** [comment]
go into the original hakchi2 folder under the kernel menu select uninstall. this should remove all trails of the mod. please also note go into the nes and do a system restore as well to factory settings to be safe. then take a fresh copy of the installation and load the games. let me know how it goes

**Comment by wbechard** [comment]
Perfect, thank you for clarifying, I hadn't noticed that option previously.
