### ISSUE TITLE
Games patched with Lunar ips give me C7 error

### ISSUE THREAD

**Issue by funkytowel360** [ClusterM/hakchi2#826]
I keep on getting a c7 error on games i patched with translations. all games have a black screen and when i reset i get a c7 error.

run as administrator with lunar ips on files extracted by zip, with there SFC file. Tired it without comprising, then with and see no change. While using lunar i selected register file type, if that helps.

I am not using Retroarch

**Comment by ClusterM** [comment]
Which games?

**Comment by Drakonas** [comment]
@funkytowel360 Has this been resolved? Please close the ticket if so.
