### ISSUE TITLE
hakchi2 v2.21d only allows one game to be added

### ISSUE THREAD

**Issue by Sonictendo** [ClusterM/hakchi2#829]
The program is only allowing me to add one game no matter how many I drag or add to the list. When I try to add another game, it laps over the previous game I added. Please help!!

**Comment by McGiogen** [comment]
Probably duplicate of https://github.com/ClusterM/hakchi2/issues/750.
Are you adding zip files or rom files? The latter should work.

**Comment by Sonictendo** [comment]
I appreciate your response and for your help. Wasn't thinking and that was the issue. I was just confused since all the ROM's were under some kind of Tefar Setup. So I had to individually install them and then unzip.
