### ISSUE TITLE
Some problem games

### ISSUE THREAD

**Issue by smlad** [ClusterM/hakchi2#830]
So all works excellent, but i found some problems with some popular games/roms
1. Top Gear 2, when using through deaufult emulator 2player mode stops at black screen, when using retroarch 2player mode works, but sound glithes at some levels, minor visual glithes. tried many roms both E and U, but the problem still goes
2. Waterworld, music glithes, found only E rom
3. Star Wars return of the Jedi, some glithes with fps in some scenes

**Comment by mmax3** [comment]
4. Rock n roll racing, upgrade screen and result screen has visual (inverted) graphic glitch

**Comment by JeffSeverino** [comment]
There is already a public spreadsheet. 
https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/edit#gid=2014317767
Please, research before posting this kind of "issue".
