### ISSUE TITLE
"NES Mini not found, sorry" (SNES Mini issue)

### ISSUE THREAD

**Issue by LoosGuccreen** [ClusterM/hakchi2#831]
**EDIT:** Solution for this case has been found, see posts below. I let the case open, because a FAQ update could be advised. I let clusterrr see if he thinks so.

_________________

Hi. I don't know if I'm encountering an issue with myself or with your program. I was able to use it successfuly with the NES Mini back in the days with no problem but I can't seem to make it work with the SNES Mini (v. 2.21d)

Here is my problem: I can patch the kernel successfully, the device still works (the Kernel boots up as if nothing changed), but I'm stuck at the step where I'm supposed to upload some games to the device (my game list is currently empty, I just have the 21 default games right now).

So, your program asks me to lit up my SNES Mini when connected to the computer and to Install the driver if needed. I assume the driver here is a different driver from the FEL one since you don't ask the console to be on FEL mode at this step.

The thing is, my SNES Mini is not recognized by your program, although it is present on the Peripheral Manager. When I try to install the driver, the CMD tells me "NES Mini not found, sorry" and refuse to install any driver (also, I tried to boot it on FEL mode just to be sure and here I can Install the driver with the tool but your program can't find the SNES Mini.

I'm not exactly sure what have gone wrong, but I assume it's the "install the non-FEL mode driver" step that fails me. Is there a way to force the installation of the driver ? Like (it's not a Windows driver signature check issue or something like that. I can install the FEL-mode driver). Also, I'm not holding reset at anytime during boot (and I tried other USB Ports, but I repeat, it is recognized as "CLV-S-SNPY" by the task manager).

Do you have any idea ?

In advance, thanks a lot for your help. If that's a bug, I'd be happy to help resolve it if you need me to do specific tests.

![mmc_2017-10-16_12-06-31](https://user-images.githubusercontent.com/6335020/31606853-8f5b7fee-b26a-11e7-86de-2dc7ec270a8b.png)

**Comment by LoosGuccreen** [comment]
Update: I tried to install a generic USB driver using Zadig but hakchi2 still fails to find it (with WinUSB, libusb-win32, libusbK and USB Serial). 

Also, I've seen [here](https://github.com/ClusterM/hakchi2/issues/584) that some people are having the same issue as I do, but the issue has been closed without resolution and except the "try another computer" solution, I don't see much that could help me

**Comment by LoosGuccreen** [comment]
Update: Tried on an other computer (both Windows 10 64b), same result, at the same step

**Comment by T3rry12** [comment]
I am having the same issue, tried several computers, also manually updating the driver.

I couldnt even get ti to recognise, it keps being unknown device, but as soon as it came up as CLV-S-SNPY i rebooted the snes in recovery mode, and the driver installed via the "install driver" button in hakchi.

**Comment by T3rry12** [comment]
nevermind, i guess i proclaimed victory too soon, it did show up as nes mini in device manager, but it wouldn't interface with hakchi, so i rebooted the snes and it went back to the same issues with showing as CLV-S-SNPY

**Comment by T3rry12** [comment]
another update, after it showed up as CLV-S-SNPY i updated the driver, and it showed the nes mini driver as an option, i updated it to that driver, now it appears properly in device manager, and i can install the driver via hakchi, but hakchi never gets past the "waiting for nes/snes" window so it never syncs, even though in the install driver command it does detect the hardware.

**Comment by T3rry12** [comment]
I finally won, I did the upload custom kernel from the menu and then it let me upload games

**Comment by LoosGuccreen** [comment]
You did it on FEL mode or on non-FEL mode ? (aka reset or non reset mode)

**Comment by LoosGuccreen** [comment]
YESS it did indeed work (had to flash original kernel and then flash custom Kernel) ! Maybe a FAQ update would be appropriate ?

**Comment by T3rry12** [comment]
i ended up installing the driver in FEL mode, then flashed the modded kernel in FEL, then after it finished i could upload the roms, i assume at that point the flash reset it back to non-FEL

**Comment by MotleyLou** [comment]
Hello Everyone,

Semi-Newbie with Hakchi.

Just got a NES Mini that I believe was hacked and "restored". Noticed choppy menu music, also, I cannot perform a System Restore via the console. So, I figured I'd rather load games I wanted, and ended up learning Hakchi via YouTube vids etc.

Now, I cant even Dump or Flash my Kernel (downloaded a supposed Stock Kernel) Long story short...when I try to 'Hold Reset while pressing power and waiting a few seconds' never get the unit to go in to Developer Mode so I can backup/restore the Kernel. I did download and install my Windows driver for USB devices with Zadig. Tried 2 different laptops (both running Windows 10), tried different USB cables, and ports...etc 

Can anyone help, so I can at least Restore this NES, or ultimately upload all the Rom's I added into Hakchi? I also tried 3 different HakChi builds (2.21d, 2.17, and 2.11).

**Comment by MotleyLou** [comment]
Forgot to add...when I hold reset, then power, then release reset, the unit just powers up, so Hakchi never "finds it"

**Comment by ghost** [comment]
Perhaps learn what you're doing before you do it. Sounds like you're going to have to solder it.

**Comment by LoosGuccreen** [comment]
What happens when you try to launch it in FEL mode? (Normally: the led don't light up but after a few seconds you hear the windows "plugged device" sound)

Please check:
- the cable you're using (try with the stock one if you have it)
- your Peripheral Manager (opposite to what I have said earlier in this thread, there is not two drivers. If you see the CLV-S-SNPY on your Peripheral Manager, it means that your device is not fully hacked (it means that your nes mini is connected on non-FEL mode which is not intended to be used with a computer))

**Comment by MotleyLou** [comment]
Both the computers I tried it on (both Windows 10) see my NES as a “media player” That’s the thing, I can never get it to go into FEL Mode. Also, not sure if the USB cable that came with it, is the stock version. I had another cable, but same results. I did just order (just in case it matters) a power supply and cable from Nintendo. 

I thank you for replying, also, just in case I tried doing it off of 4 older Hakchi builds, in case my unit was modded early on. Pretty sure my problem lies with how my computer sees the unit. If I can just get it to go into FEL Mode. Like I said, the units on screen menu to factory default it, doesn’t work...guessing someone hacked this already, then sold it to me “like new”...bought it on eBay.

**Comment by LoosGuccreen** [comment]
You shouldn't be able to disable the FEL mode, even by hacking it (or at least by hacking it using hakchi). That's something hard linked to how the AllWinner CPU works.

The two most probable issue I can see here is a deficient reset button (does it work as intended when you use the console normally?), or a deficient USB cable (I don't know if FEL mode asks for a certain amount of power or something that could force the console to reset when trying to boot up in FEL mode). Otherwise I'm out of idea, but the option "another hack have disabled the FEL" seems quite unlikely to me

**Comment by MotleyLou** [comment]
Loos,

Thank you very much for replying to my questions. I found out, my USB cables were to blame. I tried a third cable and had success. Thank you so much for helping out.

**Comment by Drakonas** [comment]
The main cause of this, I believe, is overwriting the files for the hakchi update since 2.20 debug. 2.21 added an option to detect for NES Mini or SNES Mini, but if you didn't erase the config file, it would still think you were using an NES Mini. Following the proper update instructions in the FAQ would have bypassed this. Closing this issue.

**Comment by BZA-B** [comment]
Yeh I just had the exact same problem. I'm in Australia so dunno if thats the problem. But after it didn't do what all the vids said I was worried I'd started something I couldn't finish so I'm not gonna hack mine anymore lol.......fuk that. I got a Pi3 but I wanted to play all my SNES games on the official system, but I suppose a hack isn't official. Yep I give up. My Pi3 n 8Bitdo do a pretty sweet job so not gonna risk breaking the SNES Mini. The comment from Motleylou kinda scared me too. Having choppy music on it from a possible previous hack. I'm looking forward to picking up a NES Mini soon. Wonder when there gonna announce preorders for them. They did say January 2018 so couldn't be too far off. Oh well, not I've given up on Hakchi forsure, PEACE! PS. Checkout my channel BENOFFICIALMASSIVE on YT if anyones keen :)

**Comment by CLYDEVIEW** [comment]
Can someone please answer in thick as **SHIT** speak for those non GEEKS among us (ME)?
P.S I'm typing this in non "FEL" mode whatever the "FUK" that is.  I simply would like an answer in human speak before the 30 day return policy runs out..

**Comment by CLYDEVIEW** [comment]
My Q is simple, my PC and Laptop do not even know the Mini SNES is connected, so what chance does HAKCHI2 have of doing anything, let alone kernel dumps or adding games. Thats like asking a blind bloke to point at the moon. Every Solution I've read on Google all assume I can actually tell my snes what to do. Not so.  I've tried swapping USB ports and 3 different PC's and still nothing.  The snes mini will play built in crap but as far as I'm concerned the fukkin thing is off hire. 
Like everybody else on this site I want to play the games "I LIKE" not the garbage that came with it.

**Comment by aznxstazy** [comment]
It most likely your USB cable. Use the usb cable that came with the SNES. That solved my error message "NES Mini not found, sorry".

**Comment by CLYDEVIEW** [comment]
OK, i'll try that. Thanks!

**Comment by Fortyseven** [comment]
Had the `NES Mini not found, sorry` error, too. It was a crappy cable, in my case, as well. Swapped it out for a better one, and: 👍

**Comment by CLYDEVIEW** [comment]
Thank you Fortyseven for your assistance, Gave up and binned the unit, resorted to Raspberry Pi 3. Does the same job but better. WHO KNEW?

**Comment by Oywee72** [comment]
I have Win10 64bit OS with Hakchi2 CE v.3.5.2  -I tried different cables, different ports, different Hakchi2 software versions, etc. but Hakchi2 would NOT let me install/flash a driver, until I installed a different driver called, Zadig v.2.4 , after that I could finnally dump kernel, upload ROMS easilly on my SNES mini, everything works just perfectly!

**Comment by cpitrolo** [comment]
I performed my first-ever attempt at hacking the NES MINI and was successful. Beginner's luck? I won't speculate. I did use Hakchi2 CE 1.2.5 and Zadig. PC uses Windows 7. Had issues finding the driver until Zadig was used. After that, I flashed twice: one using Zadig and then using Hakchi2. It worked. Like I said, perhaps beginner's luck, but hey......

**Comment by ponduzn** [comment]
I have tried all suggested information through this thread, except using the cable that came with, as that is not an usb cable, its connected to a power brick.
I have tried 6 different usb cables, all of which is supposed to be able to transfer data, still not working.
Whenever i try to boot into reset mode, by holding reset button, and flicking power button, power LED always lights up, and windows does not recognize a new device connected.
My model is the 821 games version, SUPER MINI SN-02, is this not compatible? 821 games and 99% of them are shit lmao.
Please help, else i have to order another one. Only reason i got this one is that the picture on ebay lied about the item description.

**Comment by LoosGuccreen** [comment]
@ponduzn I might be wrong here but there's a high probability that, as the unit you got is not being distributed by Nintendo, it doesn't include the same hardware as the "usual" SNES Mini and is not compatible with hakchi2, unfortunately

**Comment by ponduzn** [comment]
> 
> 
> @ponduzn I might be wrong here but there's a high probability that, as the unit you got is not being distributed by Nintendo, it doesn't include the same hardware as the "usual" SNES Mini and is not compatible with hakchi2, unfortunately

Well that explains it lol. Thanks for your fast reply! will order the legit one! cheers!

**Comment by Fortyseven** [comment]
For those interested, found a pic on Amazon. Check out them sweet DB9 connectors! 😎😏

![image](https://user-images.githubusercontent.com/156409/71420983-16c81900-2646-11ea-8fd5-e7347c77bfac.png)

**Comment by ponduzn** [comment]
> 
> 
> For those interested, found a pic on Amazon. Check out them sweet DB9 connectors! 😎😏
> 
> ![image](https://user-images.githubusercontent.com/156409/71420983-16c81900-2646-11ea-8fd5-e7347c77bfac.png)

So does anyone know of a way to add\remove games to this type of console ? 
It actually surprised me how many racist and sexual games there are in this 821 console, and really want some of them gone :P 
Here is a video showing what i'm talking about for reference: 
https://www.youtube.com/watch?v=hURWHPZHXAk&fbclid=IwAR36NacWIdRkuvrIHJeQcGFFgdRmsr5I3Vw1rDoSzvsPDFe-KOzr9u_OVrQ

**Comment by Ragnarok2869** [comment]
****CHANGE THE MICRO USB CABLE**** some cables charge and other so transfer data.
