### ISSUE TITLE
Missing games

### ISSUE THREAD

**Issue by durubz** [ClusterM/hakchi2#833]
Successfully added and sync games, I saw all the games after initial scroll. After playing a game and back to main menu some games were missing. Any idea?

**Comment by ledste** [comment]
NES or SNES? Version of the software used? etc etc.

**Comment by durubz** [comment]
SNES used hackhi2 v2.21d and retroarch 1.0 Thanks

**Comment by durubz** [comment]
Tried changing the number of folders in Main menu to 45 instead of 100. Issue solved and closed.  Thanks
