### ISSUE TITLE
Nes Mini Classic error adding games.

### ISSUE THREAD

**Issue by qingjian0** [ClusterM/hakchi2#834]
Done a lot of NES mini without any issues until now.
Got this brand new, ORIGINAL nes mini classic.
Flashing original and modded core works fine but when it is adding games I get this error.

Shell Command "rm -rf
/var/lib/hackchi/rootfs/usr/share/games/nes/kachikachi/CLV-*
/var/lib/hackchi/rootfs/usr/share/games/nes/kachikachi/???
/var/lib/hackchi/menu" returned exit code 1:rm: can´t stat
/var/lib/hackchi/rootfs/usr/share/games/nes/kachikachi/´CLV-*:Not a
directory
rm: can´t stat
´/var/lib/hackchi/rootfs/usr/share/games/nes/kachikachi/???´: Not a
directory

Anyone know whats wrong here?
Tried 3 diffrent pc, tried all the USB ports
Tried the original micro usb cable and 5 other.
Same result everytime.
When flashing original all works fine, dumping works fine.
As soon as hackchi is syncronizing to add games I get this error.

**Comment by qingjian0** [comment]
Tried on a fresh installe Win 10 PC and it works great now.
This is very odd because Ive done a lot of NES and SNES mini on this same pc that im writing from now and suddenly it does not work anymore. Tried diffrent PCs aswell with no success until now with a fresh installed one.

**Comment by ghost** [comment]
Download the Debug version of Hakchi2 on the releases page. Reproduce the error so it ends up in the debug.log in the Hakchi2 Debug version folder. Zip the folder up and send it to Cluster. His email address is found in Help -> About in Hakchi2, right at the bottom. It's fairly easy to do and you'll be helping anyone that has that problem in the future, which is great.

**Comment by qingjian0** [comment]
Thx ill do that later today.

**Comment by Drakonas** [comment]
Since this is inactive and technically fixed I am closing this.
