### ISSUE TITLE
Original FDS games not working on Famicom mini (kachikachi) with latest Hakchi updates

### ISSUE THREAD

**Issue by Slugoid** [ClusterM/hakchi2#836]
This issue was raised a while ago, but with 2.21d I am still getting issues with playing the factory FDS games on my Famicom mini. I have installed retroarch as well. All other games are working perfectly.

I'm not sure if this has been solved already or I'm doing something wrong.

**Comment by atarimonkey2000** [comment]
I installed Hackchi on my Famicom mini today and ive having the same issue. (plus it will randomly crashes in the menu as well?!?).

Works perfectly on my euro snes mini though! :)

**Comment by Drakonas** [comment]
@Slugoid @atarimonkey2000 The Famicom Mini's built in emulator doesn't support FDS games... you need to run the game with retroarch using the nestopia core (fceumm core doesn't support FDS either)

**Comment by atarimonkey2000** [comment]
@Drakonas what you talking about?!? Of course the Famicom mini supports FDS games, it comes with 4 of them built in! (Zelda, Zelda 2, Metroid, Castlevania).

**Comment by Drakonas** [comment]
Those aren't Famicom Disk System games....

**Comment by Drakonas** [comment]
I am sorry I was wrong. I'm not as familiar with the NES games. haha

**Comment by Drakonas** [comment]
@atarimonkey2000 Are you still having the issue?

**Comment by atarimonkey2000** [comment]
I think your confusing the Famicom Mini with the Nes mini! The Famicom mini has 4 FDS games, and after i installed an older version of Hackchi2 (without retroarch) it ran all fds games i tested. It's the latest version of Hackchi that seems to refuse to run the built in FDS games.

**Comment by atarimonkey2000** [comment]
yeas, still having issues with the latest version of hackchi im afraid! :(

**Comment by Drakonas** [comment]
Ah I see... I will change the label then, and see if we can get this fixed. But to be honest the newer releases are really focusing the SNES Classic.

**Comment by atarimonkey2000** [comment]
@Drakonas thank you! :)

**Comment by Slugoid** [comment]
@atarimonkey2000 Which older version are you using that works with the pre-installed FDS games?

Since most of the FDS games on the Famicom mini are Japanese, I decided to just installed the US/EU versions of the game for the time being.  Nonetheless, it's still a issue that needs to be looked at.

**Comment by Drakonas** [comment]
@atarimonkey2000 I can see why you want the FDS versions now.... https://youtu.be/KQ7NVh1_QOM sexy music.... Maybe I should try to find English patches of this.

**Comment by Drakonas** [comment]
I can confirm this affects the SNES Mini as well. I have tried both the default retroarch hmod as well as also installing the use_nestopia module. Can't get FDS games to boot.

**Comment by Drakonas** [comment]
This also seems to affect FDS games other than the originals. Thought I should note.

**Comment by Drakonas** [comment]
Update: FDS games will work in retroarch if you install the FDS BIOS optional from KMFDManic's core set and install ClusterM's retroarch module alone. I recommend not using KMFDManic's main cores (they usually have bugs), but the _km_bios_fds_req.hmod module is literally just the bios file. However, I don't feel justified linking to pirated content. I'll leave you to find the coreset. A google search should easily find it.

**Comment by atarimonkey2000** [comment]
@Drakonas Thanks for your help, thats gotten everything working! (even strangely fixed the power cutting out problem i was having!?!) Cheers dude! :)

**Comment by AllegroDigital** [comment]
Just noticed that this was a problem on mine as well. Hoping to get time to test with Drakonas' solution this weekend.

**Comment by Drakonas** [comment]
@atarimonkey2000 the downside is it is not using the native kachikachi emulator on the Famicom Mini :( Which is why this is still an issue.

**Comment by AllegroDigital** [comment]
Maybe I'm doing something wrong? But after dragging KMFDManic's latest _km_bios_fds_req.hmod into hakchi2 - v2.21e and adding the module, the fds games still crash after opening. retroarch and translate_famicom are the only other modules added onto my fami mini.

**Comment by atarimonkey2000** [comment]
@Drakonas Hopefully it will get fixed. In the meantime, this is fine! Thanks again for your help! :)

**Comment by Drakonas** [comment]
You only need the retroarch mod @AllegroDigital You may need to perform a complete uninstall and og flash and try again.asd

**Comment by AllegroDigital** [comment]
Hmm...
So here are the states my famicom mini is in

1. factory - works fine, no roms are addable
2. custom kernal - works fine, no roms added yet
3. custom kernal + added roms - original fds games no longer work. screen goes black then back to menu, added games such as Akumajou Densetsu give an error when I try to load them, other roms work fine
4. retroarch added - added games such as Akumajou Densetsu and Nazo no Murasame Jou now work, but the original fds games (castlevania, zelda, zelda 2, metroid) still go to black screen
5. adding _km_bios_fds_req.hmod - appears to have no impact

**Comment by Slugoid** [comment]
From my testing, version 2.12 seems to be the version that works perfectly with my Famicom mini so far.
- Original FDS games working
- All added ROMS working
- All added FDS games working (no need for RetroArch)
- All FDS games will change disk automatically (RetroArch required used to change disk using buttons)

Until the problem gets solved, I'll be sticking with 2.12 for my Famicom, and newer version for the NES/SNES.

**Comment by AllegroDigital** [comment]
Thanks for the tip re: 2.12
Confirmed as working great for me. Down side is it doesn't seem to have all the letters (no"W" or "4") for game titles in the menu... so I'd still like to see an actual fix in 2.20+ . But with 2.12 and retroarch for the games with missing modules, everything is working great.

**Comment by ClusterM** [comment]
Will be fixed in version 2.30. Thank you!
