### ISSUE TITLE
Clarification on folders

### ISSUE THREAD

**Issue by darrelhunt** [ClusterM/hakchi2#84]
The FAQ states:

```
Q: How folders feature works? Why I can't customize my folders structure?

A: There is no way (yet?) to customize folders manually since it's too easy to break something. Folders structure will be created and alphabetically sorted automatically based on number of games and number of maximum games per page (you can select it via menu). There are two styles of folder structure:

Pages. Every page contains games and shortcuts to other pages. This style used when there are not so much pages/folders.
Tree. It looks more like folders and contains root directory with sub-directories. This style used when there are at least 12 pages with games because shell need at least 12 items to show them without glitches.
```

I've recently added the entire library to mine and chose 60 games per page.  Comes out to roughly 10 pages.

It seems to arrange them as such 1-60 (alphabetically) in one group, then links to other pages (61-120,etc)  and each page has links to every other page and the ability to go to that page directly.

I notice in the source that there are folder graphics with #-z and back arrows.  Leading me to believe that in the UI, i'd be shown a list of folders with games arranged by letter.  Am I correct in assuming that if I put the number of games per page back to 30, it would generate more than 12 pages.  It would switch to the Tree option where I'm shown a list of folders #-z.  Have the ability to say go to the A folder and only see games that start with A.  Hit the back folder to go back to the list of #-Z?

**Comment by ClusterM** [comment]
Next version will have total folder control, it's just not released yet.
