### ISSUE TITLE
Clovershell read timeout

### ISSUE THREAD

**Issue by jackkknifejones** [ClusterM/hakchi2#840]
I am pretty sure i did everything right but get this when i synchronize selected games. what should i do ? thank you

**Comment by jackkknifejones** [comment]
also said kernel dumped but the md5 checksum is unknown when flashing new kernel

**Comment by cleardragon** [comment]
Disconnect the hdmi from the snes mini and just connect it to the pc to upload roms

**Comment by Drakonas** [comment]
be nice cleardragon. @jackkknifejones it would be nice to have the image I expect you meant to post along with your submission?
