### ISSUE TITLE
NESCE - shell command "mkdir - p... 

### ISSUE THREAD

**Issue by DefKorns** [ClusterM/hakchi2#842]
Hello ,

i was using hakchi 2.17 on my mini Nes and now i updated to 2.21d (internal version 2.0.21.53).

- Uninstalled previous version
- flashed original kernel
- flashed custom kernel
- uninstalled all hmods
-installed new hmod

after this when i try to add games i get this error:

![image](https://user-images.githubusercontent.com/32590804/31642921-394e1648-b2dd-11e7-9456-b1e31cf1883f.png)

thanks in advanced

PS: Console is working with the original games, they all work. Reset button combination also working. And i tried right now adding "--retroarch --core fceumm" to de advanced command-line and no retroarch

**Comment by ghost** [comment]
Do you mean you uninstalled Hakchi 2.17 or do you mean you ran the Kernel -> Uninstall feature?

**Comment by DefKorns** [comment]
Kernel > Uninstall

**Comment by ClusterM** [comment]
Uninstall, reinstall custom.
But you can make NAND-C dump first and send this dump to me if you wanna help to fix it.

**Comment by DefKorns** [comment]
@ClusterM it didn't work. I also tried:
- Uninstall
- Reinstall custom
- Uninsntall
- Restore original rom
In both cases only cases only the original games work. When i tried to add games i get the above error.

 But i already managed to "fixit".

-  flash custom kernel
- installed retroarch
- telnet to NESCE
`# cd /var/lib/hakchi/rootfs/usr/share/games/nes/`
`# ls -l`
`-rw-r--r--    1 root     root         16790 Jan  1 00:00 kachikachi`
`#mv kachikachi kachikachibackup`
`# ls -l`
`-rw-r--r--    1 root     root         16790 Jan  1 00:00 kachikachibackup`
- added a test game and it worked
- checked the dir and now instead of a file kachikachi i have a dir
`# ls -l`
`total 24`
`drwxr-xr-x   50 root     root          4096 Jan  1  1970 kachikachi`
`-rw-r--r--    1 root     root         16790 Jan  1 00:00 kachikachibackup`
- removed original games (worked)
- add the rest of the games (also worked)

now my only doubt is if i should or shouldn't delete the kachikachi file.

PS: please note that the kachikachi original file is set to 0644 (read & write),  so root shouldn't have any issue overwriting it :(

**Comment by DefKorns** [comment]
@ClusterM here's my [NAND-C Dump](https://wetransfer.com/downloads/c97737726a440d3504616d9df5f64ea520171017120021/28fed8173a1fd3fdc45ac01fc6077feb20171017120021/c05db3)

**Comment by Drakonas** [comment]
@DefKorns just to check back in after a while. Is this still an issue?

**Comment by DefKorns** [comment]
@Drakonas  i fixed with the solution above `#mv kachikachi kachikachibackup`  but i still don't know if i can remove the kachikachi file.

**Comment by Drakonas** [comment]
if you moved the kachikachi to kachikachibackup, you can remove the kachikachibackup file if you wish, but then you won't have a backup. Glad you got it fixed.

**Comment by DefKorns** [comment]
But i still dont know what happened. Why was hakchi trying to create a folder over a file.
the (now) kachikachibackup is a file and hakchi was executing a mkdir -p. 
That's why I asked if I should remove it, cause now i have a kachikachi (folder) and a kachikachibackup (file).

Thats weird 😄

**Comment by Drakonas** [comment]
Well as long as it works it shouldn't hurt anything. kachikachibackup is not big enough to really be a problem for space.
