### ISSUE TITLE
SNES Mini stays frozen a few seconds after synchronize

### ISSUE THREAD

**Issue by AndreSanctus** [ClusterM/hakchi2#845]
My SNES Mini stays frozen a few seconds after synchronize.
I am on hakchi2 v2.21d.

Anyone knows why?

This happened after i downloaded manually some HD box arts and dragged them to the name of the games. But for what i understood, hakchi2 automatically converts the box arts to a new resolution right?...

**Comment by ledste** [comment]
Maybe it's long process and the processor of mini SNES is not like a strong CPU.

**Comment by AndreSanctus** [comment]
The freeze was more than 40 seconds. Anyway i made a full uninstall and installed again hakchi2.

**Comment by ledste** [comment]
If the cover is heavy can be but never tried this. ciao.

**Comment by Drakonas** [comment]
Has this been resolved @AndreSanctus ?

**Comment by AndreSanctus** [comment]
Yes, after a new uninstall and install.
