### ISSUE TITLE
SNES Mini with only 224,1MB even after extra_space module installed

### ISSUE THREAD

**Issue by AndreSanctus** [ClusterM/hakchi2#846]
Hakchi2 2.21d says my SNES Mini has only 224,1MB.
And this is after i installed the "extra_space" module... wasn't supposed to have 300MB total?

**Comment by DanTheMan827** [comment]
The extra_space mod moves your saves to the extra partition, if you don't have many saves, this won't save much space.

If you make heavy use of save states, I personally wouldn't use that mod since it can only hold around 24 of them, they take around 2MB each

**Comment by AndreSanctus** [comment]
After i uninstalled everything in my snes mini, i only flashed the custom hakchi2 kernel and i get only 238,3MB total space (with only the original games and without saves). I thought it was around 300MB...

**Comment by DanTheMan827** [comment]
The extra space provided with extra_space is only used for saves, hakchi cannot use that space for games with the mod.

**Comment by DecanFrost** [comment]
Correct me if I'm wrong. But the extra space hmod essentially releases the reserved 50mb space in the main nand which was reserved for save states back to the games portion and will then move the save states to an unused portion dynamically as they are created ..  there is an different hmod that installs the games to that other partion untill its full and then continues to install to main nand. The 50mb reserved space on main name will remain in tact for save states

**Comment by Drakonas** [comment]
@AndreSanctus The SNES Mini has about 315MB of space, but 80 of it is used by the games already on the console, and they cannot be removed, only hidden. You're stuck with around 240MB or less I'm afraid.

**Comment by DecanFrost** [comment]
It would make for a nice feature to remove them comoletly and add different games or even re-add those exact same games via roms . I gathered up those same games as roms added covers and let hakchi2 compress them and they take up half the space (41mb)
________________________________

**Comment by Drakonas** [comment]
Unfortunately, it's impossible. They are unable to be written to or be deleted. It's a limitation of the SNES Classic system. @DecanFrost You're stuck with the ~240MB.

**Comment by DecanFrost** [comment]
Has anyone tested the extra space mod on an NES Mini.  Would it work the same way

**Comment by Drakonas** [comment]
@DecanFrost The SNES Mini is the only one of the two that has a 50MB extra unused partition on the system, which the extra_space mod uses. The NES Mini doesn't have that, so no it would not work. Also the extra_space mod is never recommended because in almost all situations your saves will fill up the 50MB and then you will have crashes. Lastly, please ask this kind of thing on Reddit and don't respond to 3 month old issues next time.
