### ISSUE TITLE
Windows 10 Norton Antivirus issue

### ISSUE THREAD

**Issue by NoeleyC** [ClusterM/hakchi2#847]
While every version of hakchi2 I've installed on my laptop has proven tricky to run (as Norton scans it and declares it too new and with not enough registered users) I cannot install version 2.21d at all, Norton removes the hakchi exe file and also a language dll. I mark these for exception, but it keeps rescanning them. I didn't install 2.21c but 2.21b is still working OK on my laptop. Has anyone experienced the same?

**Comment by Drakonas** [comment]
Hint: Don't use Norton. Can't really help you there. The only thing you can do is to try to add it as an exception, which you've already tried.

**Comment by Drakonas** [comment]
This is a Norton issue, not Hakchi. The user should try to submit the program to Norton support to have them add an exception to prevent detecting as a "false positive".
