### ISSUE TITLE
Alphabetized folder suggestion. 

### ISSUE THREAD

**Issue by firestonex** [ClusterM/hakchi2#85]
I think it would be great if we could get an option for 26 folders, and have them sorted by alphabet automatically into the folders.  Something easy, like a one check option instead of going to switch how many games in each folder. 

all games starting with A goes in the first folder, B in second, and so on and so on.
There will of course be a lot more games in some folders than others, but it would make it a lot more organized and easier to find what you are looking for. 

oh ya, I guess there would also need to be a folder for games that start with a number.

**Comment by warlockv2** [comment]
im pretty sure thats already been prepared for next release, but i cant say for certain but if you read threw the commits, you will see them

**Comment by ClusterM** [comment]
Yes, it's already done. Will release soon, after some tests.
