### ISSUE TITLE
Boulder Dash NES game not working on SNES Classic

### ISSUE THREAD

**Issue by SassyFish256** [ClusterM/hakchi2#851]
When I select the game, the screen goes black and it resets, but other NES games work fine.

**Comment by Robo-1982** [comment]
Tried latest version of retroarch?

**Comment by SassyFish256** [comment]
no, but for some reason, hakchi wont pick up my snes.

**Comment by SassyFish256** [comment]
I installed the latest version, but it still doesn't work.

**Comment by electrocret** [comment]
Have you tried a different distribution of the ROM? I know the NES emulator doesn't like No-Intro Roms. https://github.com/ClusterM/retroarch-clover/issues/103

**Comment by SassyFish256** [comment]
i reflashed the custom kernel using 2.21e and it works now.
