### ISSUE TITLE
failed to add "hmod"

### ISSUE THREAD

**Issue by nimbylive** [ClusterM/hakchi2#852]
I cannot add any of hmod files to hakchi.

Everything in hakchi works just fine for me. I have added many games and everything that should work(is compatible with the stock emulator) has worked flawlessly. 

However, I cannot add any of the hmod's so that I cannot add retroarch. I have the files from this site and I have attempted to drag and drop them(as seen in more than 1 youtube vid), but I just get a black "no" symbol and can never add any of them.
I have also attempted to drag and drop the zip file(per instructions). I have tried the most recent and gone back to two previous versions of zip files. I have drug each over to hakchi, while it is running, and it just keeps giving me the no symbol.

Is there a specific procedure for adding them other than the instructions?

**Comment by ArieKindicator** [comment]
I have some similar issues when adding or updating hmods. I can drag and drop hmods on hakchi2 (plus sign) but the hmods are not updated. and the date and time stamps of the files do not change.
Somehow, it seems that hakchi2 doesn't actually process/update the hmods files.

Q. I have 2 hakchi2 installs: 1) the web installer/updater and 2) the stand-alone directory (zip) version. Are there (known) conflicts when 2 or more hakchi2 editions are installed on the same computer?

**Comment by nimbylive** [comment]
The plot thickens. My Hakchi2 still does not appear to add hmod.

I was able to play Seiken Densetsu 3, and Terranigma today (I patched Terranigma with the NTSC patch and I am unsure if that solved the problem or not). Illusion of Gaia would not start (not surprising, but worth a look) and neither would tales of Phantasia.

The other odd piece was that although I cannot see any of the new cores in hakchi2 I do have retroarch running on my snesc. I was playing Seiken Densetsu 3 and hit select and start(mostly because the screen went dark and I wasn't sure if it would come back) and the retroarch screen came on. 

I haven't added the --retroarch command to any games, but it would appear as though some are working because of it.

**Comment by Drakonas** [comment]
Have you tried not using the web installer? Also you are dragging and dropping the entire retroarch_cores.zip that you get from the releases page for Retroarch cores, correct? And @ArieKindicator you need to use one or the other. Having them both on the computer does not conflict, but I imagine using them alternately will produce issues.

**Comment by nimbylive** [comment]
The web installer did not install properly for me. I cannot remember if it was a permission or exception error, but an error message popped up when I attempted to run that installation. I have attempted to drag the zip file from the the website onto the open program window with no luck. It is very odd and I will work on it again tonight. Does the web installer version include the cores already packaged?

**Comment by douglie007** [comment]
I had to add them one by one and in the modular area active them.  I added retro arch first then each of the cores

**Comment by Drakonas** [comment]
@nimbylive I said to NOT use the web installer. I was assuming you were already using it. Where are you extracting Hakchi2 to? You need to be placing it into a folder in your user directory, not in the C drive root or program files.

**Comment by nimbylive** [comment]
Okay, well good to know on the web installer, it didn't work for me anyway. I believe that I have the program in the program files (I just dropped them there so they can easily be moved). 

This thing is weird with what is working and what is not, but I will take advice from above and move the program to a better location. I installed the program on my pc here at work and was able to drag and drop the retroarch zip file into it. I may just bring my snesc in and do everything here.

**Comment by Drakonas** [comment]
@nimbylive I would move the dump folder over and personally re-extract hakchi. The permissions of everything including the games_snes folder are probably fucked in the program files hackchi folder now. The dump folder doesn't matter though (it normally just has your OG kernel file) You never want to extract things that don't have an installer to program files. Windows Vista and newer cause problems when you do that. Hopefully Hakchi was able to dump the kernel. It may not have. If there is no file in dump, then you need to find a kernel on the internet. If you've installed the custom kernel it's too late, as dumping the kernel will dump a corrupted kernel.

**Comment by nimbylive** [comment]
I still do not know why my pc won't allow me to add these(not a problem of this program), but I tried the procedure on a different pc and it worked perfectly. Thanks to everyone for the help.
