### ISSUE TITLE
Preview for additional games too...!

### ISSUE THREAD

**Issue by r3tro80** [ClusterM/hakchi2#854]
It's possible to add the preview for the added games too?

I mean the automatic preview with Mario showing the installed games, it works only for the original included roms but doesn't work for added games... 

Originally how this feature works? Are movie clips or the Snes Mini starts the emulation and exit automatically after some minutes?

Thanks.

**Comment by Drakonas** [comment]
There are two forms of savestates you need to create, one is easy and covers most of the demos, and you just need to create a savestate for it to load for that, but it will not be a recording, rather it will just load from when you made the savestate, so during a cutscene/main menu would be good. This one is loaded when mario spin jumps on the savestate.

The second, when mario hits the game like a question block, is a recording, and requires you to create a savestate and edit the savestate to create an input recording of the game button by button, which even I don't know how to do, as it is very time consuming.

**Comment by r3tro80** [comment]
@Drakonas It's the second on i'm interested for... Have you an idea of where this file is located for original games?

**Comment by Drakonas** [comment]
@fastpop72 see the issue linked above. Someone posted info on how to do it.
