### ISSUE TITLE
Missing encoded character in desktop file causes C8 when navigating into folder

### ISSUE THREAD

**Issue by sceptre2k3** [ClusterM/hakchi2#857]
Using Wordpad, this is what the .desktop file looks like for a setup that doesn't have issues (only the last line of the .desktop is relevant):
  Copyright=hakchi2 Â©2017 Alexey 'Cluster' Avdyukhin
There is a special/encoded character before the copyright.

Using Hakchi2 2.21d (the version that was available on Sunday Morning), I had added a game and edited the details of the game.  The .desktop generated in this case did not have the special/encoded character:
  Copyright=hakchi2 ©2017 Alexey 'Cluster' Avdyukhin

When this particular .desktop file is uploaded to the Super NES Classic (US version) and the folder containing the .desktop's game is navigated to, there is a C8 error.  Worse yet, since the Super NES Classic remembers the folder that it was last on, shutting down and powering back on will return to the same folder, which again will encounter the problematic .desktop file and cause the C8 again.  Not sure if there is a way to recover directly on the console.  Instead, the user may have to use Hakchi2 to re-uploaded the same games/config, which will reset the folder memory.

Issues:
  1) not sure why the special/encoded character was left out in this particular instance?  the game wasn't anything out of the ordinary (Super NES Monopoly US) and the information entered in the UI were normal as well:
    Players=2
    Simultaneous=1
    ReleaseDate=1992-09-01
    Publisher=PARKER BROTHERS
  2) During the game uploads, would there be a way to verify/fix/warn about .desktop's that have this issue?  Currently, a user wouldn't know there is an issue until navigating to that exact folder with the .desktop and there may not be an non-instrusive way to recover when the C8 occurs

**Comment by Drakonas** [comment]
You are having problems probably because you are using Notepad/Wordpad to edit the desktop file. Windows notepad/wordpad isn't made to handle linux-based files. Use Notepad++ or Sublime Text instead.

**Comment by Drakonas** [comment]
@sceptre2k3 was this ever resolved? Please close it if so.

**Comment by sceptre2k3** [comment]
Hi,

Yes, it was indeed because I used Notepad/Wordpad to edit the desktop file.  I only did this with Monopoly and a few other games, and these seem to be the problematic ones.

Would there be any value in making Hakchi2 more robust to detect/handle situations where people did the same thing?  If so, perhaps another enhancement type item is better for tracking.
