### ISSUE TITLE
"extra space" module

### ISSUE THREAD

**Issue by Gab-75** [ClusterM/hakchi2#860]
This is not a real issue, but a request for clarification... :)

The extra space module allows to use a portion of unused NAND space (about 50MB) to store the savestates, but I didn't understand well if also the "standard" free NAND memory may continue to be used to store the savestates (when the extra NAND space is full).., thanks in advance for answer/clarification! :)

**Comment by Drakonas** [comment]
Please don't use this issue tracker for asking questions. This is meant for bugs/feature requests only. Go to the Nintendo Classics Discord for that. The extra_space module makes the 50MB partition the only storage for savestates.

**Comment by Gab-75** [comment]
Sorry for the "improper use" and thanks for the  answer/clarification!  :)
