### ISSUE TITLE
Rival Turf

### ISSUE THREAD

**Issue by burgerrob** [ClusterM/hakchi2#863]
Has anyone managed to get this working ? i dont see it on the list of problem games.

When i try to run this game it just freezes then when i hit the reset button it pops up an error screen.. any suggestions ?

**Comment by Drakonas** [comment]
Then why don't you submit an entry to the list, instead of making a useless issue request that is not an issue request? This is for bugs/feature requests only. Ask on the Nintendo Classics discord if you have a question please.

**Comment by gromber** [comment]
no problem with this game.
