### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by Redghost22** [ClusterM/hakchi2#865]
Hi,
 i try to sync the snes with the lastest version of hakchi.
I push the button reset then the power one. I wait until my computer recognize the snes. The light will show up (so i stop) and if I wait more the light don't show but the consol disconnect, connect and after i have a USB error.

Can you help me thanks

**Comment by Drakonas** [comment]
You are supposed to disconnect the cable if you already connected it, then hold the reset button WHILE pressing power and keep holding reset until Hakchi picks up the signal, and then LET GO of reset but keep power on. Then wait until flashing is over and the light turns off.

**Comment by Drakonas** [comment]
Please respond if this was resolved or not. @Redghost22
