### ISSUE TITLE
Issuing "exit" at telnet shell prompt crashes Hakchi2

### ISSUE THREAD

**Issue by rhester72** [ClusterM/hakchi2#866]
If you enable telnet and connect, as soon as you issue an "exit" command at the telnet CLI prompt, the session will disconnect and immediately after the Hakchi2 binary will crash.  Using stand-alone Hakchi2, 100% reproducible with every build.

**Comment by juanlin** [comment]
Happening to me as well on portable 2.21d (2.0.21.56), connecting with telnet (Windows 10) or putty. It happens whenever:
(a) I enter 'exit' in telnet
(b) Ctrl-C out of the username login prompt

But does not happen if I hit the X to close the telnet window.

It does not happen with the debug build of 2.21d (2.0.21.56).
