### ISSUE TITLE
Problem when shutting down console

### ISSUE THREAD

**Issue by rovervt** [ClusterM/hakchi2#868]
Hello, 
when I shut down the console, always show a C8 error, and i can only shutdown turning on and turning off one more time. How can I fix it?

**Comment by ArieKindicator** [comment]
Try to remove the last added games, they might be the problem. You might have disconnected your device too early after coping games to the device and some files/games might be corrupted.

1. remove the added games and check for C8 error
2. add the removed games again and check if the C8 error returns.

**Comment by rovervt** [comment]
Ok, i'll try it. Thank you very much!

**Comment by cruxan** [comment]
It could be because you have to many games without folders.

**Comment by rovervt** [comment]
Yes, i have 103 games, so I will try to divide it into folders with Hakchi and I'll tell you. 
Thank you very much!

**Comment by DecanFrost** [comment]
I reloaded with 2.21d on both my systems and I get c8 on shutdown I put 2.21c back on with same games and c8 error gone

**Comment by rovervt** [comment]
Finally, i've found the solution. The error only appears if you are in the game list. If you start a game or if you are into a game, and you shut down the console, it shuts down perfectly. If someone has also this problem, this could be the solution, at least right now.

**Comment by Drakonas** [comment]
The solution: Don't install so many games. SNES Classic does not like a lot of games. 80-90 should be a recommended maximum.

**Comment by rovervt** [comment]
Ok, this is a good advice. And I can delete 15 games without problem. I will test and I tell you. Thank you to everyone!

**Comment by hoderer** [comment]
I don't know if that's true. I have 707 (!) games incl. compressed cover artwork (thanks Pngyu), custom backgrounds and custom icons installed for the following systems:

Atari 2600, C64, NES, Sega Master System, PC Engine, Gameboy, Sega Mega Drive, Super Nintendo, Nintendo 64, Gameboy Color and Gameboy Advance

I have up to 200 roms in one folder. The shutdown-error occurs only 2 out of 10 times I turn it off and to be honest: It really doesn't disturb me a lot as long as everything else is working flawlessly...

**Comment by Drakonas** [comment]
@robertocastroserantes Has this been resolved? And hoderer, arcade games are tiny in comparison to most other consoles.

**Comment by rovervt** [comment]
If I divide the list in folders, the problem dissapears, but folders division is very slowly in comparison of have the whole list of games without division, mostly when you are in a game and try to come back. So, the people have to choose if they want to avoid the error and have a slow snes mini, or have the error with more speed.

**Comment by Drakonas** [comment]
The SNES Classic can only handle so many games listed in one list. That is not a Hakchi limitation, but a hardware limitation. Closing this.
