### ISSUE TITLE
SNES mini rebooting after loading state of SEGA rom

### ISSUE THREAD

**Issue by MrPokemon270588** [ClusterM/hakchi2#869]
Hello. Can somebody tell me if there is a difference between running SEGA game with adding "--retroarch" line and without it. The point is i was trying to play Earthworm Jim 2 sega version (because snes version lacks some sound effects on snes mini emulator) and installed retroarch for it. Then i added --retroarch line (don't ask why). So i've played it a couple of minutes and when i tried to save state and then load it, snes mini freezed then rebooted, showed me the menu screen and then rebooted again. I unplugged usb cable and it didn't help. Only after a couple of minutes it worked again fine. But when i tried to play game again all started over. So i deleted Jim 2 and tried to play other game ( snes game on snes mini emulator without retroarch). And it happened again. NOT on retroarch emulator. That made me frustrated. After a couple of minutes i tried to install and play Jim 2 again without --retroarch line. And it worked fine (for now at least). So anyone knows whats going on? Is it power supply problem? I've tried usb plus laptop and usb plus 5v adapter. No difference. Hakchi 2.21c.

**Comment by Drakonas** [comment]
First of all SEGA games can't use --retroarch, that is only for SNES games using ClusterM's core. You need to add the mega drive/genesis game to hakchi and keep the line as default, as well as make sure you have installed the genesis_plus_gx core from the retroarch cores releases (as well as the retroarch hmod itself). If the command line has anything but "/bin/clover-**_canoe_**-shvc-wr" at the beginning of the line you NEVER add --retroarch to it! The --retroarch is only for running snes games through **_canoe_** as a passthrough. For Mega Drive/Genesis games, the default command line should look something like:

        "/bin/md /usr/share/games/CLV-G-SWDVQ/Castle_of_Illusion_Starring_Mickey_Mouse_(USA__Europe).md.7z"

As long as your Hakchi is up to date it should detect what console the rom is from that you are adding and change the command line accordingly.

**Comment by MrPokemon270588** [comment]
Thank you for your reply. So the embarrassing fact that I added --retroarch could result rebooting device even when playing **not** sega games, even after JIM 2 deleted? Or it is just coincidence and there is some power problem?

**Comment by Drakonas** [comment]
--retroarch is only for the retroarch snes core. It doesn't work for other platforms.  If you change the command and resync it should be fine.

**Comment by MrPokemon270588** [comment]
I've deleted the --retroarch line. Changed hakchi to 2.21d. Reflashed kernel. Resynced. Played some time - it was ok. Then SNES Mini crashed on other SEGA game. I did not put any lines anywhere. Obviously there is some power supply problem. It is not only me with this issue. My snes was powered with laptop usb.

**Comment by Drakonas** [comment]
First of all, which version of JIM2 are you trying to run? Sega CD or Mega Drive/Genesis? The Sega CD isn't supported by any emulators for SNES Classic yet. The extension for the rom needs to be ".md".

**Comment by MrPokemon270588** [comment]
Correct. .md. I have genesis rom. It's not only Jim 2. I have problems with Asterix Power of Gods sega rom. And one time i even had problem with snes game Bubsy.

**Comment by Drakonas** [comment]
Does the command line start with /bin/md (See the entry in the Hakchi2 window)? If so, have you installed the genesis_plus_gx AND retroarch modules?

**Comment by MrPokemon270588** [comment]
Yes. Indeed it starts with /bin/md. I'm not sure where should i look to know what modules are installed. I can find modules-install modules. And there i see genesis_plus_gx. Does that mean it is installed?

**Comment by Drakonas** [comment]
it doesn't hurt to install again if it was already installed, so install that AND the retroarch one, and see if that fixes it.

**Comment by MrPokemon270588** [comment]
Ok. I'll try. The thing is it doesn't happen too often. Today i played for about an hour until i saw that problem. As soon as i face it again, i'll post here. Thank you a lot.

**Comment by MrPokemon270588** [comment]
Ok, so I reinstalled all retroarch modules including genesis_plus_gx. In five minutes of playing got reboot loop again. Sega game. Maybe usb cable problem?

**Comment by MrPokemon270588** [comment]
Sorry for open/reopen business

**Comment by Drakonas** [comment]
what are you powering the system from? You need to be using the cable it came from and plugging it either into a computer port (try back and front) or directly into a power plug in the wall. Using a USB hub or plugging it into a TV/monitor or console USB will produce issues.

**Comment by MrPokemon270588** [comment]
I plugged it into laptop usb. Maybe it causes problem. I'll try to use only my 5v 2A adapter. See what happens. Thank you.

**Comment by Drakonas** [comment]
@MrPokemon270588 are you still having problems with this?

**Comment by MrPokemon270588** [comment]
Didn't have a chance to play.  The next time I experience the problem, i'll post here.

**Comment by Drakonas** [comment]
Closing the issue until then. I will still see your response.
