### ISSUE TITLE
How to add games after I hacked NES?

### ISSUE THREAD

**Issue by Solscud007** [ClusterM/hakchi2#87]
Thanks ClusterM for making hakchi2. It was rather easy and painless. I cherry picked some 45 games to add to the original 30 NES games. 

How do I re-edit what is on there and add more? Do I simply repeat the steps and uncheck the games I no longer want as well as add more roms that I want to try?

Also just FYI, I kept my original 30 NES games and the save states were still there after I added 45 more games. So that was cool.

**Comment by NotNer0** [comment]
Yes you add more or uncheck the ones you dont want, then redo all the steps
