### ISSUE TITLE
Hakchi: Keeping my games when using 2 different PC

### ISSUE THREAD

**Issue by Georges8** [ClusterM/hakchi2#871]
Hello everyone,

I've installed hakchi 4 days ago with a friend's PC, now I've got parallels running on my personal mac, I'm glad for that but I'm lost with all kernel options. I kept my original kernel dump somewhere... My question is: how do I keep my modified snes with all games added, folders, since I didn't kept my hakchi settings (i erased all on my friend's pc). I wonder what option (flash custom kernel, NAND...) could allow my snes to export modifications, specially games added on my "new" hakchi2 running on parallels. I would love not starting from scratch (spent many time on it, love my library) Thanks

**Comment by Scanlineman** [comment]
Your library is stored here:
hakchi2\games_snes

I zipped my folder up and put it aside as a back up in case I lost it. You could zip your folder then just move it to your other computer.

**Comment by Georges8** [comment]
I should have done that, copying this /games_snes folder on a usb stick, I didn't.
Is there a way hakchi2 can adapt, restructure folders from what my snes has inside?
At least recognize and show content? I'm afraid, as I don't really understand kernel options, to erase all... Thank you Scanlineman

**Comment by Georges8** [comment]
Finally, I chose "synchronize with snes mini" and lost my installed games, but I started rebuilding my collection and it'll not take long, thanks
