### ISSUE TITLE
Snes Mini Original 21 Games C8 error

### ISSUE THREAD

**Issue by nonnoUmby** [ClusterM/hakchi2#872]
Hello! 
Recently I tried to add a few new games to my European SNES Mini. I already did it without problems back when Version 2.20 came out. But after I added a couple other games, the console took a lot longer than usual to show on the TV, and when it did the original 21 games had broken covers, and when I tried to load them I was greated with a C8 error message. The 18 games I added (for a total of 39 with the original 21) had no problem running, but when I hit the reset button in order to return to the main menu, the console took several seconds to show the menu, while the music was already playing. 
I updated hakchi to the 2.21d version, but it still didn't resolved the problem. 
What should I do? Do I have to restore the orginal kernel and lose all my progress or there is something else I can do?
Thanks to everyone who can help me.

**Comment by DecanFrost** [comment]
Change your folder setting to hold more thsn 30 titles. If you got 31 games set it to 40 or 50

**Comment by nonnoUmby** [comment]
I already tried that (set it to 40, being 39 games), but still nothing...

**Comment by Drakonas** [comment]
What platform were these games you added from? @nonnoUmby

**Comment by nonnoUmby** [comment]
They are all SNES games, in the American and Japanese format (NTSC) @Drakonas

**Comment by gixernaz** [comment]
1. Backup your save states and back it up twice (encountered a corrupted save state with Super Mario Kart) in two different folders, save it somewhere safe: 
- Open hakchi2 > Tools > Save-State Manager
2. Uninstall the custom kernel: 
- Open hakchi2 > Kernel > Uninstall 
to restore your original flash.
3. Once your SNES Mini has reverted back to it's original kernel, boot it up and Format/Reset your SNES Mini. It's now safe to turn off and unplug your SNES Mini once it's done formatting.
4. Now in your PC, backup your original kernel dump and games:
- Documents\hakchi2\dump
- Documents\hakchi2\games
- Documents\hakchi2\games_snes
 by moving them to a different folder temporarily.
5. Uninstall your old hakchi2 completely: (I'm using Windows 10)
- Uninstall via Control Panel > Uninstall a Program.
- Manually delete this folder: C:\Users\YOURUSERHERE\Documents\hakchi2\ if it still exist.
- Manually delete this folder: C:\Users\YOURUSERHERE\AppData\Local\Apps\ if it still exist.
6. Download Cluster's latest hakchi2:
hakchi2_web_installer.exe
7. Once done, restore your backup folders:
- Documents\hakchi2\dump
- Documents\hakchi2\games
- Documents\hakchi2\games_snes
8. Plug your SNES Mini back in, reinstall hakchi2(if it ask you to dump your kernel, click yes) and add your games again.
9. Once installed, you can now finally restore your save states and make sure to do it one by one:
- Open hakchi2 > Tools > Save-State Manager

**Comment by ClusterM** [comment]
Try to reinstall custom kernel.

**Comment by nonnoUmby** [comment]
Thanks @gixernaz , by following your greatly detailed guide I was able to restore all the games and save datas! Also Thank you to everyone who responed!
