### ISSUE TITLE
[REQUEST] Driver for Windows, to use Snes Mini´s gamepad when its conected to PC

### ISSUE THREAD

**Issue by gromber** [ClusterM/hakchi2#873]
I love this gamepad, and i think this could be a great idea without buying a mayflash adapter, in hakchi2 an option that make a gamepad available on windows pc, in xinput, to use with emulators and pc games.

**Comment by tonyrayo** [comment]
If I understand this request correctly, I believe that it is outside the scope of this project.  There are however existing projects to interpret Nintendo's controllers as xinput devices ([this project](http://www.wiinupro.com/home) for example supports the Wii U Pro Controller, Wiimote + extension [which I believe the SNES Classic would fall under as it uses the same interface], Joycons and more).

It could be possible to use the SNES/NES Classic/Mini systems as controller pass-through devices, however I think it might make more sense (as well as be easier) to attach to a Wiimote and connect via Bluetooth (especially if you have one or more Wiimotes on hand).

**Comment by gromber** [comment]
i only want to use original gamepad with snes classic mini, without buying anything more on pc.
hakchi runs on snes mini when you add games, save manager... on hackhi2, why not when you activate a pc gamepad mode.

only an idea, i dont know the difficult.

**Comment by Drakonas** [comment]
This isn't something software can do. You need a hardware adapter for this like Mayflash. The SNES classic doesn't send inputs through the cord, and even if it did, the lag would be insanely horrible, too horrible to play with.

**Comment by ClusterM** [comment]
It will be laggy. It's better to build adapter to connect contoller directly to USB, it's pretty simple.

**Comment by gromber** [comment]
oohh too bad, so maybe i should buy a adapter or a 8bitdo, i love this gamepad :)

**Comment by ArieKindicator** [comment]
Buy a SNES USB-controller on AliExpress for less than $3. I have one and it is of good quality.

**Comment by Shoothimnow** [comment]
From what it sounds like, you want to instead of doing

SNES Controller -> SNES to USB Adapter -> Computer -> Emulator

you want to 

SNES Mini Controller -> SNES Classic -> USB To PC -> **Read Controller as USB** -> Emulator

It doesn't... really.... work that... way =\

**Comment by sathdor** [comment]
I just made up my adapter a couple days ago, following this tutorial:
[http://www.instructables.com/id/Teensy-USB-Wii-Classic-Controller/](http://www.instructables.com/id/Teensy-USB-Wii-Classic-Controller/)
You can also buy a premade adaptor like this:
[http://www.mayflash.com/Products/PCUSB/PC052.html](http://www.mayflash.com/Products/PCUSB/PC052.html)

Btw, 8bitdo sfc30/snes30 is a great device, but you still get a small amount of input lag compared to a wired controller. Oh, and it still feel a bit different from a first party Nintendo gamepad.

**Comment by beyondmany** [comment]
@sathdor the links in your post return a 404.

**Comment by sathdor** [comment]
Sorry, my mistake, they work now.

**Comment by Drakonas** [comment]
Closing this issue as this will never be implemented unless some miracle happens.
