### ISSUE TITLE
[Hakchi2 GUI] Text issue French version

### ISSUE THREAD

**Issue by codex785** [ClusterM/hakchi2#878]
![text issue](https://user-images.githubusercontent.com/32591366/31821977-3ef1447c-b5a7-11e7-8155-6053aaade017.jpg)

If only the line was long enough!!

**Comment by Drakonas** [comment]
This has been fixed. :)

![Pochette](https://a.safe.moe/5jBo1.png)

**Comment by codex785** [comment]
![inkednot fixed_li](https://user-images.githubusercontent.com/32591366/31991788-e3aaa60a-b978-11e7-8daa-783d62141c2b.jpg)
not fixed 2.12e

**Comment by Drakonas** [comment]
Make a new hakchi folder (extract the hakchi2_2.21e zip), and copy games_snes, dump, and user_mods folders to the new folder from your old folder.

**Comment by codex785** [comment]
doesn't change a thing. issue still there
text is still "illustration" instead of "pochette"

**Comment by ClusterM** [comment]
Fixed.
