### ISSUE TITLE
Is the CODE of FF 3 built in miniFC correct?

### ISSUE THREAD

**Issue by SuperANIJA** [ClusterM/hakchi2#88]
Even if uncheck miniFamicom's built-in ROIM Final Fantasy 3 ( ファイナルファンタジー®III ), it will not disappear after transferring.
Even if move to a folder It's at the root.
I have not confirmed but the symptoms that it disappears are reported on 2 chan.

Looking at the hidden_games file in the debug version, CLV-P-HABJJ exists. Despite it appears in the menu.
I doubt the possibility of CODE mismatch.

**Comment by ClusterM** [comment]
You are right, it's code mismatch. Fixed. Thank you!
