### ISSUE TITLE
Kernel not dumping / waiting for device

### ISSUE THREAD

**Issue by Cameron1391** [ClusterM/hakchi2#880]
I have hackchi 2 set up to my SNES classic mini , the games are all on the program but I can't synchronize them on the system.
when i go to "Sync selected games" I follow the steps but then when I go to "Install drivers" it sits there and does nothing. The black loading screen comes up and nothing happens. I can't get the games to sync on the system although i'm doing everything right. What is going on?
I'm running Windows XP

**Comment by Georges8** [comment]
Hi,
In the black loading screen you must press enter once, I think.
Could be something else, but...

**Comment by DanyMode8** [comment]
you dumped the original kernel? and after that flash custom kernel? (and hold reset buttom and power the snes without release the reset until you listen the USB sound)

**Comment by Cameron1391** [comment]
I do press enter at the black screen. Nothing happens. 
I do follow instructions and hold reset and power button next then release and hear the USB sound but still nothing and hackchi2 doesn't seem to pick up the system

**Comment by LPXIII** [comment]
I Have exactly the same issues. I try different computer, différent UsB cable,  different UsB port but Just nothing happen. I install the driver many times and I follow the instructions but nothing. So I can't dumb the Kernel, I cant flash the Kernel. 
Thk for a solution.

**Comment by Georges8** [comment]
With a virtual pc running on my mac(parallels), hakchi didn't allow "sync games" untill I pluged the mac, didn't work running on battery, without any message to tell me so, I had to check the forum here. Just in case...

**Comment by Cameron1391** [comment]
PC is plugged in to the charger

**Comment by Drakonas** [comment]
Here's a hint @Cameron1391 Don't use an unsupported operating system. The driver is most likely incompatible with XP. Windows XP automatically receives loads of viruses regardless of what antivirus you have because Microsoft isn't patching the system anymore. If anything XP machines should never connect to the internet anymore unless you want your entire house invaded by malware. Get a new machine or upgrade to Windows 7 which should be supported by your PC. Windows XP is no longer supported by most software today.

**Comment by Cameron1391** [comment]
Thanks, I will let you know how it goes when I try different Windows . I
have a Windows 10, maybe that's why I was having issues

**Comment by Cameron1391** [comment]
Drakonas, by golly, that worked! 
I did it through my Windows 10 laptop and all games I selected copied and played on the system without any issues. 
It wouldn't recognize on my Windows XP at all.
Awesome, thanks !

**Comment by Drakonas** [comment]
Glad to hear! ^^
