### ISSUE TITLE
[NESC] Unable to flash custom Kernel: MD5 + Invalid Kernel Size

### ISSUE THREAD

**Issue by thesk8rguitarist** [ClusterM/hakchi2#881]
I have dumped original kernel and tried flashing custom only to constantly receive the checksum error which reads:
"Kernel dumped but the MD5 checksum in unknown: a5b24e0081a50f3b693be6f220bb7971 Do you want to continue?"
I hit yes, then receive the error "Invalid kernel size 455680"

I've been running in loops all morning. What am I doing wrong?

**Comment by ArieKindicator** [comment]
I had this too, you have to restore the original kernel and start over.
To 'fix' the checksum error I uninstalled all extra modules (that were not installed, obviously), a complete uninstall, and a factory reset (in the options menu). Then I flashed the original kernel back on the device.

But first, you could try to do a factory reset only, and then reflash the custom kernel. As factory reset might fix the checksum error.

**Comment by thesk8rguitarist** [comment]
Well I just followed all those steps to the "T". Once back to factory, I held reset and pushed power, then clicked "Flash Custom Kernel" and get the exact same results. 

Any ideas to progress?

**Comment by thesk8rguitarist** [comment]
Ok I finally got the custom kernel loaded. I had to go back and use Hakchi 2.17d. Flashing the kernel there worked the first time with no issues. So there's something possibly wonky with 2.21

**Comment by thesk8rguitarist** [comment]
Now the NES Shows all 30 games as missing files, and any games I add to it are only in Black and White. 

I flashed custom kernel in Hakchi 2.17d as 2.2 and 2.21 would not allow me to flash the kernel. Any idea why I'm having the issues I have now?

**Comment by Drakonas** [comment]
@thesk8rguitarist the checksum error means your untouched kernel dump was corrupted or deleted and redumped from a modified NESC kernel. You need an OG unmodified kernel either by restoring from a backup (which has been consistently recommended to do so, and has to be done manually by backing up the file in the dump folder), or by obtaining one from elsewhere.

Basically Hakchi uses the dumped OG kernel to make the custom kernel. If the OG kernel dump is redumped from a (S)NES Classic that has ever been hakchi's EVER, then creating a custom kernel from that will most likely (A) not boot or (B) not work properly with games.

This usually happens by deleting your dump folder accidentally when upgrading hakchi to a new version, or starting hakchi from an entirely new folder without copying the dump folder to the new location.
