### ISSUE TITLE
ClusterM Hakchi 2.21e LAST VERSION?

### ISSUE THREAD

**Issue by DanyMode8** [ClusterM/hakchi2#882]
Hi ClusterM, i will hope to know when you going to release other version or if this is an definitive edition, to play my games normally, beacause im bored to delete all my save states every time when i change the version.  This version of hakchi is very stable? or wait to other version to play all my games normally and don´t change anymore?
Hope you can answer me please, and Congrat for your Job you´re Awesome.
Saludos desde Chile :D

**Comment by hoderer** [comment]
Why don't you export your save states before updating with the save state manager (TOOLS --> SAVE STATE MANAGER) and import them when you got the new version running...!?

**Comment by Drakonas** [comment]
@DanyMode8 technically a factory reset nowadays is only needed for dire situations. Most of the bugs causing residual files to be left over have been resolved. The only way you'd need to factory reset these days is if you flash a corrupted kernel and the system is unable to be fixed after an og flash and hakchi uninstall. I've been switching between versions with just a uninstall and og flash from the old version and then a custom kernel flash after switching to the new version, just fine.

If anything, only minimal leftover data will be there, which will not be much space-wise to worry about.
