### ISSUE TITLE
NES | hakchi2 v2.21e (2.0.21.60) | mkdir error

### ISSUE THREAD

**Issue by kaleneet** [ClusterM/hakchi2#885]
Hi, I'm trying to sync my games, the custom kernel installs perfectly, however I get this error when I try to sync my games:

```
shell command "mkdir -p
"/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi""
returned exit code 1: mkdir: can't create directory
'/var/lib/hakchi/rootfs/usr/share/games/nes/kachikachi': File
exists
```

![mkdir error](https://user-images.githubusercontent.com/32710318/31838195-ee0db402-b5db-11e7-9593-5df89a0f6799.jpg)

**Comment by DefKorns** [comment]
@kaleneet  i had the same proble with the previous version.

 But i managed to "fixit".

-  flash custom kernel
- installed retroarch (optional)
- telnet to NESCE
`# cd /var/lib/hakchi/rootfs/usr/share/games/nes/`
`#mv kachikachi kachikachibackup`
- added a test game and it worked
- removed original games (worked)
- add the rest of the games (also worked)

**Comment by kaleneet** [comment]
@DefKorns the solution worked! Thanks!
