### ISSUE TITLE
paypal

### ISSUE THREAD

**Issue by bigjobbyx** [ClusterM/hakchi2#886]
the paypal donation button doesn't function as expected on your website. I am in the UK if this helps

**Comment by bonxraw** [comment]
Q: How can I donate to you?
A: My PayPal: clusterrr@clusterrr.com
And thank you! This really helps me a lot. I have many ideas in my head but I have not so much time because I'm busy with commercial projects. Remember that it's just hobby for me, I'm doing it for fun :)

**Comment by bigjobbyx** [comment]
made a donation. Thanks for your hard work
