### ISSUE TITLE
Folders and Games disappear

### ISSUE THREAD

**Issue by Teoc99** [ClusterM/hakchi2#89]
All the games and folders just disappeared, leaving the home menu there with no game folders.

I'm sure if I flash the NESC again it will have a fresh start. 

What is the best way to make the NESC Mod stable?

**Comment by warlockv2** [comment]
make sure your not going over 35 games in a folder.  at least not for now, i found that to make things alot safer

**Comment by Teoc99** [comment]
Thanks for the response. I have been doing 30 games per folder. Any other ways to make the mod with no issues is greatly appreciated.

**Comment by ClusterM** [comment]
It's hard to say something without some shell output. Next time do not reflash it but try to download files using clovershell.
