### ISSUE TITLE
Power LED open in fel mode while dumping kernel.

### ISSUE THREAD

**Issue by MikeBpro** [ClusterM/hakchi2#893]
Hello, when I try to dump the kernel my power led open even in fel mode and then I get this message '' no answer from device ''

**Comment by MikeBpro** [comment]
Forgot to mention, It's a SNES classic.

**Comment by Gab-75** [comment]
Did you try to use a different USB cable and/or a different PC USB socket?

**Comment by MikeBpro** [comment]
Done both, problem is still there..

**Comment by Gab-75** [comment]
Maybe is an useless question... did you install "nesmini_driver" ?

**Comment by MikeBpro** [comment]
I installed it with Zadig to be sure, seems installed correctly, my power led still turn on everytime I start to dump kernel

**Comment by Gevander** [comment]
I am having the same exact issue, not sure what is happening but my power led  also comes on during kernel dump

**Comment by MikeBpro** [comment]
Impossible this is a fake snes, bought it day 1, so it's probably not this.

**Comment by Gab-75** [comment]
Did you try to use a different PC and/or Windows OS ?

**Comment by MikeBpro** [comment]
Yup, not working..

**Comment by Gevander** [comment]
so i just noticed that the circle in the bottom left corner of the application is red where in some screen shots it is green, could that have anything to do with this problem?

**Comment by Drakonas** [comment]
I advise to only use the cord that came with your SNES Classic. Try a different USB port on both of your PC's. USB hub/monitor/tv/game console ports will most likely result in not enough power. Most likely the ports on your PCs you are trying aren't providing enough power. You also need to have 2.21+ to work with the SNES Classic. Also, make sure you are installing the driver if not installed already.

**Comment by Drakonas** [comment]
@MikeBpro Did you ever get this resolved?

**Comment by sykonawt** [comment]
@Drakonas  i had the same problem regardless of the usb cable i used.  tried it on my laptop and my rig.  LED light would always turn on during kernel dump.  so after all the frustrations, i started trying out different solutions. this is what i did. @MikeBpro  first download and run hakchi2_web_installer.exe then download hakchi2.21f.zip.  extract and go to root\hakchi2.21f\hakchi2\driver and run nesmini_driver.exe as admin.  now run hakchi as admin and go about the whole shabang.  LED light WILL turn on during kernel dump.  LED light WILL turn on when you synchronize your games but it should work and it wont give you any errors.  everything worked successfully on mine even though the LED light would turn on. good luck.

**Comment by Drakonas** [comment]
OP has not responded after 2 days, and @sykonawt has provided a solution. I am closing this, and will reopen if needed. This is usually due to using unsupported USB ports. Some laptops have none that actually work well with Hakchi. Using another computer can often fix the problem.
