### ISSUE TITLE
ROMs keep getting wiped from hdd

### ISSUE THREAD

**Issue by Pandahboy** [ClusterM/hakchi2#894]
This is the second time this has happened to me and it is very frustrating. The first time I didn't know what happened to all my ROMs but now I figured it out. Someone asked me if I would be able to put games on their NES Classic for them and I said sure. I went into settings on Hakchi2 v2.21d and changed the Console type from SNES (USA/Europe) to NES (USA/Europe). When I did this there was an Error message that came up saying "Access to the path '<ROM NAME HERE>' is denied." After this message I could see all of my ROM files which were in an open window next to Hakchi2 just start disappearing. I had all my ROMs stored in the hakchi2/games folder.  They are not in my recycling bin either because it was empty prior to this happening. This is the second time this has happened and now I have to get my ROMs AGAIN for the third time. Why is it doing this?

**Comment by ArieKindicator** [comment]
Hakchi2 simply removes existing games from your connected device as it sees it as a new one (different region) and therefore deletes all installed games.

However, you can uncheck your games without deleting them. So, don't press the delete button, just uncheck those games you don't want te be installed.

[Feature Request]Hakchi2 should give the user a choice to 1) delete all games from the device, or 2) store/backup all games (including cover art and settings) to a  backup folder.

**Comment by Pandahboy** [comment]
I didn't get that choice it just erased everything and now I have to take another 4 hours to get everything back. I'm going to turn off my external hard drive from now on if I need to make the switch because I can't be downloading everything every time I switch consoles.

**Comment by Drakonas** [comment]
The real solution to this tbh is to use two separate Hakchi folders for NES and SNES. Are you still needing this issue open @Pandahboy ? If you want this to be a feature request it should be listed as such.

**Comment by Pandahboy** [comment]
That is actually a very good solution. Thank you for the advice. I was just really frustrated because I had everything just the way I like it and then everything got erased twice.

**Comment by DanTheMan827** [comment]
#841 has been in development for a while, this fixes this problem along with separating the clover profiles, so things like switching to a Japanese image doesn't mess up the non-japanese ones.
