### ISSUE TITLE
Hakchi drag and drop won’t work can’t add no mods .

### ISSUE THREAD

**Issue by krec9** [ClusterM/hakchi2#897]
Any help on this I wanna add retroarch with cores but its not letting me add them I can’t even drag and drop a game?

**Comment by gnadenlos** [comment]
Copy them to the folder yourself.

**Comment by Drakonas** [comment]
@krec9 do you still need help with this?

**Comment by krec9** [comment]
Yea it still doesn’t work

**Comment by Drakonas** [comment]
Well this isn't a place to ask for personal help with Hakchi. This is for reporting bugs. Ask on the https://www.reddit.com/r/miniSNESmods/ subreddit for help.
