### ISSUE TITLE
Experiencing transparent issues in KDL3 that weren't in the previous build

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#902]
Kirby's Dream Land 3 had no transparency issues in the previous build. How do I know this, I saved my data on stage 2-1 and I was in an underwater area and the water was in fact transparent, then after I updated Hakchi; about a week later, I loaded the restore point and the water was no longer transparent. How did compatibility get worse since the last build, instead of better?

**Comment by ghost** [comment]
in hakchi select the game and press strg+alt+e. check the preset id, it should be A210. maybe the update accidently changed that, i dont know.

**Comment by 03bgood** [comment]
Should I still use the current build or should I go back to an earlier build, when the transparency still worked 

Update: Just changed it to A210, will it work now?

Update 2: It works now! The water is transparent again! Yay!
