### ISSUE TITLE
Original PAL SNES kernel dump needed

### ISSUE THREAD

**Issue by 100kd** [ClusterM/hakchi2#903]
Greetings,

It appears that I've bricked my SNES mini by trying to flash a wrong kernel into it. Nothing seems to help and I have no original kernel dump for said console on my computer.

Will someone be kind enough to post or e-mail me an original SNES kernel? {PRIVATE EMAIL REDACTED @Drakonas}

Any help is appreciated.

**Comment by enewton** [comment]
I've emailed you a dropbox link

**Comment by SergioGDP** [comment]
Hello,

I am in the same boat as 100kd.  I have bricked my SNES and could use the original kernel. 

I would appreciate any help.  Thank you.

{PRIVATE EMAIL REDACTED @Drakonas}

**Comment by Drakonas** [comment]
This is not the place to be asking for links to kernels... This is copyrighted content. Please keep this to private messages or forums that allow sharing of pirated materials.
