### ISSUE TITLE
games not working

### ISSUE THREAD

**Issue by Bombahee** [ClusterM/hakchi2#904]
I managed to add games on my SNES but can't play, it just give me black screen and go back to main menu

games i added

1942
antartic adventure
Balloon Fight
Bomberman
pacman
battle city
twinbee
galaga
ice climber

etc

did i miss something?

**Comment by moltke44** [comment]
Waiting for some kind of resolution as well. Same error with the single oddity that the first added game did and continues to load up fine. None of the others will work and just give a quick black screen and back to the menu. I have around 50 games set up in a couple folders. Box art all shows fine, and again the first game I choose at random works but no other added.  The originals still work.

**Comment by Drakonas** [comment]
Did you install the retroarch and the nestopia retroarch modules to be able to play the NES games? The SNES Classic doesn't have the software to play NES titles by itself.

**Comment by Hurgnation** [comment]
Signed up to say I'm having this same issue. Have managed to get everything else running fine, extra SNES roms, including ones that don't come with native miniSNES support, N64 and GBA games. But for some reason, I can't get any NES games to run. Tried using --retroarch and --use_nestopia, neither work, just a blank screen then return to menu.

I haven't tried many games, just the ones I was interested in, but for the sake of mentioning them, they are:

Legend of Zelda
Zelda II
Teenage Mutant Ninja Turtles

Wonder if it's worth pointing out that this is on an Australian SNES, which I think comes under the euro version.

**Comment by Bombahee** [comment]
@Drakonas can you guide us how to use retroarch and nestopia retroarch or any link for tutorial how to use those two? thanks in advance!

**Comment by Drakonas** [comment]
I am sorry. I did more research on how to use NES games with Retroarch on newer versions. The main retroarch module includes the emulator but you need to add something more to the command to use it. Download the retroarch_with_cores.zip from here, open up hakchi2 and drag and drop the entire zip onto the window to copy the files to the proper folder. Then go to Modules -> Install Module and install the retroarch module and any other cores for the platforms you wish to play (not required for NES). Follow the instructions on screen to flash the modified kernel with the modules.

Then, back in Hakchi, find all your NES games and instead of "--retroarch" in the command line use "--retroarch --core fceumm" or "--retroarch --core nestopia". Some games may work better with one over the other. Just test to see. If it runs fine no need to change really.

**Comment by Hurgnation** [comment]
Thanks Drakonas, though I still can't seem to get it to work using this method, tried both "--retroarch --core fceumm" and "--retroarch --core nestopia". Has the same result as before, black screen for 5 seconds then returns to home screen. I've included a screenshot of hakchi2 in my system to see if there's something glaring that I'm missing if you don't mind having a look:

https://imgur.com/a/ufuMh

The full command line on that one reads: "/bin/nes /usr/share/games/CLV-H-RPCQP/Zelda_II_-_The_Adventure_of_Link_(U)_.nes --retroarch --core fceumm"

Cheers

**Comment by Drakonas** [comment]
Did you drag and drop the retroarch_with_cores.zip on the Hakchi2 window? And you did install the retroarch hmod correct? Have you tried deleting and re-adding your nes roms?

It seems the info i found on --retroarch --core is for use on the NES mini only. That was outdated info on the official github readme. I apologize. It should just be /bin/nes /etc/etc/etc.nes

Maybe I need to submit a pull request to get that readme cleaned up once I figure this all out.

**Comment by moltke44** [comment]
So, my issues was with some of the SNES games actually. Some of those that needed retroarch. I ended up just actually grabbing ROMs from a couple different sources and actually most of them popped up. I don't know if this will help but you should at least try it something simple might just do the trick. By the way thanks for all the feedback I'm actually still going to try and get some of the more complicated games like Tales of Phantasia to work which right now I still only get a black screen on. Any thoughts on that one?

**Comment by Hurgnation** [comment]
sigh, turns out after all that, it was the roms I was using. Redownloaded them and they work fine. Thanks guys.

**Comment by Drakonas** [comment]
@moltke44 Tales of Phantasia uses some advanced code in-game that is unsupported by Canoe (most likely the voices in the intro). You'll need to resort to Retroarch for that game unfortunately. Ask for help on the SNES Classic Mods subreddit (https://www.reddit.com/r/snesclassicmods/) if you need assistance with setting that up. @Hurgnation Good to hear you found the issue.

**Comment by Bombahee** [comment]
It works now, thanks @Drakonas !
