### ISSUE TITLE
Original 21 Games Not Working (Resolved)

### ISSUE THREAD

**Issue by Jeyl1984** [ClusterM/hakchi2#906]
Hakchi2 v2.21e

So I got an SNES Classic, loaded some titles onto it, flashed a custom kernal and hooked it up to my TV set. Upon startup, the system played it's menu music to a blank screen for about six seconds before showing the original menu. Only the original 21 games were not there. Each selection was missing the cover artwork and attempting to play the original pre-loaded games did not work. Loading the custom games worked just fine, but the original ones just aren't there.

I checked and made sure the "Original Games" selection was selected and even flashed the original kernal. Flashing the original kernal worked, but not the custom one. Flashing the custom and synchronizing the games just makes the original games unplayable.

Suggestions?

**Comment by Drakonas** [comment]
May I ask how many games and what platforms you added? The SNES Classic only can handle so many games before the memory fills.

**Comment by Jeyl1984** [comment]
All the games are strictly for the SNES console and the current memory usage is at 100.9MB out of the 225.6MB with 125 games loaded. Is there a specific limit to how many games you can put onto the system even if the memory says you're in the green?

**Comment by Drakonas** [comment]
Do you have all the games in one folder? That would be your problem. The SNES Classic can only handle showing 60 or less games at one time, 45 if you want the thumbnails to show on screen. I recommend separating the games either automatically into folders, or sort them yourself with custom folder layout. See the settings menu for this.

**Comment by Jeyl1984** [comment]
I set the filing system to automatic and number of items per folder to 30, but she's still giving me hiccups. All the custom games still show up fine, but the originals are coming up blanks even after Hakchi2 re-organized them.

I did notice this however. After doing some more kernal flashing, this warning pops up that occurs when I initiate 'Flash Custom Kernal'.

> Kernel dumped but the MD5 checkscum is unknown:
> 030508abbcf6726b10f3604224de8d3a
> Do you want to continue?

Would that be an issue?

**Comment by Drakonas** [comment]
your kernel was dumped from a modified system then... you need to find an original kernel dump from the internet and place that in your dump folder. then flash the OG kernel first, then custom kernel.

**Comment by Jeyl1984** [comment]
Found out what was causing the problem and it's pretty embarrassing. Turns out I was updating the software incorrectly. I was only dragging the hakchi.exe file only instead of everything else. After replacing all the files in the original folder with everything in the updated folder, I flashed the custom kernal again. Looks like that did the trick.

Thanks Drakonas for your timely replies. Sorry for wasting your time.

**Comment by Jeyl1984** [comment]
Oh, that Kernal that was dumped? I think that was because the SNES I was having issues with was someone else's SNES classic. The Dump that was on my system came from my SNES that I had already played for a while (Some saved games, SF2 unlocked). She still restores the system well enough so that shouldn't be a problem, should it?

**Comment by Drakonas** [comment]
Yeah that was most likely the issue. I'd advise against using two SNESCs with the same PC, unless you can keep two hakchi folders and be diligent about using one with one SNESC and the other with another.

Closing this issue for now. Reopen it if you have issues again.
