### ISSUE TITLE
Using Multiple PCs

### ISSUE THREAD

**Issue by JFork36** [ClusterM/hakchi2#908]
Not exactly an issue, but I can't find info on this anywhere. 

I hacked my SNES on a friend's PC. I copied all the hakchi folders onto a flash drive so I'd have the kernel, etc.

He moved out suddenly and now I'm planning to use a different PC to update my SNES. How can I do this without starting over from scratch?

**Comment by jgoldsack** [comment]
Install hakchi to your new PC, then copy the folders from the flash drive to the new installation folder.

**Comment by JFork36** [comment]
I did that. My game list didn't appear. I feel like I'm missing something obvious.

**Comment by jgoldsack** [comment]
Strange. I did the same thing and had no issues.

Are your games in the games_snes folder?

**Comment by JFork36** [comment]
Oh shoot. That's it. Won't have access to the PC till tomorrow. I'll toss the ROMS in there and let you know what happens.

**Comment by Drakonas** [comment]
@JFork36 did this ever get resolved?

**Comment by JFork36** [comment]
Copied the contents of the hakchi game folder on my thumb drive over to the folders on the PC. Of course it wasn't working until I also went into the dump folder and copy/pasted the snes kernel as well. Flashed the custom kernel once and was able to pick up where I left off adding games to the SNES Classic. Thanks for your help guys.
