### ISSUE TITLE
Slowdown and auido distortion in certain games

### ISSUE THREAD

**Issue by x925** [ClusterM/hakchi2#909]
A few games i added to my classic have distorted sound and slowdowns in certain areas, i believe that if i were to use the snes9x2010 emulator over the stock one it would fix these issues but i have no idea how to change which emulator they actually use

**Comment by juanlin** [comment]
Add --retroarch to the command line arguments.

> Q: I want to run game on RetroArch instead of original emulator, how to do it?
>
>A: Select game and edit "command line", just append "--retroarch" to the end of it, after space, without quotes.
https://github.com/ClusterM/hakchi2/wiki/FAQ

**Comment by x925** [comment]
Just tried this and it caused that game to just not boot

**Comment by juanlin** [comment]
Do you have the retroarch-clover module and snes9x or snes9x2010 cores installed?
https://github.com/ClusterM/retroarch-clover/releases

If you have the modules installed and it's still happening, try installing and running CloverApp-ForSNES and loading/running your game through that, and see what error shows up.

**Comment by x925** [comment]
I should have them installed but ill install them again just in case

**Comment by x925** [comment]
No idea what im doing, i just reinstalled all of the modules, it boots with the following command line
"/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-CWMNT/Mega_Man_X_2.sfrom.7z --volume 100 -rollback-snapshot-period 600" 
but it just black screens if i use 
"/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-CWMNT/Mega_Man_X_2.sfrom.7z --volume 100 -rollback-snapshot-period 600 --retroarch"

**Comment by Drakonas** [comment]
Have you installed the retroarch module and a single snes module of choice using Hakchi2? @x925 ? Those are required to use Retroarch... https://github.com/ClusterM/retroarch-clover/releases

**Comment by x925** [comment]
https://imgur.com/a/LuqD0
That is a list of the modules currently installed in my system

**Comment by Drakonas** [comment]
Uninstall all but the modules that concide with the games you plan to use. Also, if you haven't modified the bios_template mod you shouldn't be installing that. Same goes for music_hack. password module should only be installed if you plan to use it. other than that only install the cores you plan to use as well as the retroarch mod. You are probably using up too much space of your SNESC.

**Comment by x925** [comment]
Alright i just uninstalled all but the Snes9x2010, retroarch, remove_thumbnails, extra_space,  gambatte, and mgba

**Comment by Drakonas** [comment]
try uninstalling extra_space unless you really need the space. That limits your savestates total useable space to 50MB. and you may have filled up that space.

**Comment by x925** [comment]
Just took the extra space out, and no change

**Comment by Drakonas** [comment]
I would probably try uninstalling hakchi altogether using the Uninstall feature in the Hakchi2 menu, and start fresh and install what you need for the game you want first, then branch out... try to narrow down what exactly is the issue. I can't reproduce this from my end as everything is working for me. If you haven't done that since updating from any older version of hakchi, you should be doing that every update.

**Comment by x925** [comment]
I'm specifically trying to get megaman x2 to work, it isn't much of an issue if i can't fix it but figured id try at least

**Comment by x925** [comment]
i think i fixed the problem by changing the command line to /bin/snes /usr/share/games/CLV-U-CWMNT/Mega_Man_X_2.sfrom.7z from /bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-CWMNT/Mega_Man_X_2.sfrom.7z --volume 100 -rollback-snapshot-period 600

**Comment by x925** [comment]
This definitely fixed it, and i really appreciate all of your help through this and i kind of feel stupid for not trying it earlier
