### ISSUE TITLE
Final Fantasy I & II (Japan) - FF II crash

### ISSUE THREAD

**Issue by MelonGx** [ClusterM/hakchi2#91]
![ff12](https://cloud.githubusercontent.com/assets/7697767/22928101/9bf2075e-f2ef-11e6-9ab0-8cd713d7d0d1.png)
On this title screen, when I press A to enter FF II, it always flashes back to this title screen.
FF I has not had this problem.
Is it fixable?

**Comment by baconcow** [comment]
This is an emulation or ROM issue, not a hakchi2 issue. (This reddit thread) [https://www.reddit.com/r/nesclassicmods/comments/5mpyxg/is_my_rom_x_working_megathreadconsolidation/] may provide you with further help or discussion emulation or ROM issues.

**Comment by MelonGx** [comment]
I'll not join in the reddit because of the FUCKING "care to try these again?" loop on registry.

**Comment by baconcow** [comment]
As an alternative, you could translate FF2. Since the console comes with FF1, you shouldn't need it.

**Comment by soulctcher** [comment]
@MelonGx, the built-in emulator is not quite as good as some others, and I would recommend what bacon does; patch the FF2 release and use that, instead of the 2 in 1 ROM.

**Comment by MelonGx** [comment]
I don't need to discuss FF2 single ROM because it works well.
If nothing can be done by hakchi2 side on this 2 in 1 one, then no need to discuss this issue any further.

**Comment by baconcow** [comment]
Sorry I could not help. With being able to put around 700 games on the Famicom Mini, one would think the separate ROMs would be adequate; especially when they are both tested to work flawlessly. My only suggestion, if you are set on using the 2-in-1 ROM, is to wait for additional emulator support in the upcoming hakchi2 build, using RetroArch. If you want to play it, right now, you could always compile the current version, here on GitHub, and follow the Reddit rules for adding RetroArch support. This would allow you to have FCEU core support, giving you another emulator at which to test the game with. Alternately, what is the MD5 of your FF1&2 ROM? I can compare it with what I have at my end. Perhaps there is a different version of this ROM (from another set) that you could test.
