### ISSUE TITLE
Enable "Classic Demo" for added games.

### ISSUE THREAD

**Issue by ReyVGM** [ClusterM/hakchi2#910]
Would it be possible for the "Classic Demo" option to play for added SNES games?

The "My Gameplay Demo" works for added games as long as you make a save state, which is to be expected since they play from the rewind segment. 

But for "Classic Demo", whenever Mario touches one of the added games, nothing happens. I assume this is something that could be addressed since when Mario touches one of the original 21 games, all the system probably does is load the game and let the attract mode play for a few seconds/minutes and then goes back to the menu. Certainly something can be tweaked for one of the added games to load when Mario touches it too?

Thanks for reading and sorry if this has been asked before, but I didn't see anything when I searched.

**Comment by ArieKindicator** [comment]
Look at  [url=https://github.com/ClusterM/hakchi2/issues/64]#64[/url]

**Comment by rhester72** [comment]
There is no 'attract mode' for any of the games.

What you see with "Classic Demo" is effectively pre-programmed save-state style recordings done by Nintendo and hardcoded on the device.

If the format for those recordings (which is presumed to simply be timed inputs and variable states) is ever known and documented, theoretically, a "playback generator" of sorts could be written...but given that this was requested in the early days of the NESCE and nobody's bothered to reverse engineer the format or create such a tool, I consider it rather unlikely (and moreso because with save states on the SNESCE, you more or less have the same effect now).

**Comment by Drakonas** [comment]
To clarify @rhester72 into a direct answer, the prerecorded gameplay footage (classic demos) cannot currently be created for a game, and is limited to the original 21 already created recordings for the included 21 games. This may be possible in the future.

However, there are two forms of demos that Mario initiates. When he hits the game like a question block, that initiates the aforementioned footage (or attempts to), but if you create a savestate, Mario can spin jump onto the savestate and load the game from the point the savestate starts without any inputs, so it's good for cutscenes and intros/titlescreens. That feature works for retroarch games as well, not just canoe games.

**Comment by ReyVGM** [comment]
Thanks for the replies.

I didn't know they were "pre-recorded" demos. I thought the system was just starting a game and letting the attract mode run for a certain time before going back to the system menu.

As for there being no "Attract Mode", every game has a demo/intro/gameplay if you let it run, people usually call that an Attract Mode.

**Comment by Drakonas** [comment]
Yes, but that attract mode won't work for games other than the originals unless you made a savestate where you want it to play from.

**Comment by ReyVGM** [comment]
No, that's different from what I'm asking. What I'm asking is for "Classic Demo", what you're saying is "My Game Play Demo". The latter works fine. I addressed both in the OP by the way.

**Comment by Drakonas** [comment]
Oh I'm sorry. Technically we know the command used to create the recording, but we don't exactly know how to implement it yet.

        canoe-shvc -rollback-snapshot-period 720 -rom /var/lib/hakchi/squashfs/usr/share/games/CLV-P-SABRE/CLV-P-SABRE.sfrom --volume 75 -rollback-snapshot-period 3600 --sram-file /var/lib/clover/profiles/0/CLV-P-SABRE/cartridge.sram -filter 1 --pixel-perfect --use-decorative-frame /usr/share/backgrounds/10_curtain/10_curtain_pixel_perfect --save-time-path /var/cache/clover//volatile/CLV-P-SABRE/suspendpoint0/state.time --wait-transition-fd 10 --start-transition-fd 14 --finish-transition-fd 15 --save-screenshot-on-quit /var/cache/clover//volatile/CLV-P-SABRE/suspendpoint0/state.png -rollback-mode 1 --rollback-ui /usr/share/canoe/rollback-ui --enable-sram-file-hash -rollback-output-dir /var/cache/clover//volatile/CLV-P-SABRE/suspendpoint0/rollback/

But use of it would be quite advanced to figure it out.

**Comment by ReyVGM** [comment]
Gotcha. Hopefully one day one of you can crack it and have it working :)

Thanks for the reply.

**Comment by tygill** [comment]
Someone over on reddit seems to have possibly figured out how to convert save states to the 'autoplay' classic demo format:
https://www.reddit.com/r/miniSNESmods/comments/78wq01/creating_a_classic_demo_for_an_added_rom_canoe/

According to the post, converting a save state is just renaming some things inside the save state (prefixes change from numbers to capital letters, and .break files become .inputs.state).

**Comment by PRT2066** [comment]
Yeah it was easier to figure out than I thought it would be. Probably could make a batch or something to automate the process a little bit.

**Comment by Drakonas** [comment]
Since this has been actually answered, I am closing this. The discussion will be left open.
