### ISSUE TITLE
Micro Machines doesn't detect 2 controllers connected to play 4 player? (2 players sharing one controller)

### ISSUE THREAD

**Issue by mattcoops** [ClusterM/hakchi2#911]
Micro Machines doesn't detect 2 controllers connected to play 4 player? (2 players sharing one controller)

**Comment by rhester72** [comment]
Canoe doesn't, but Retroarch does.

**Comment by mattcoops** [comment]
thank you so much. Installed retroarch and it is working perfectly. thanks for the help!
