### ISSUE TITLE
Hakchi2 v2.21e Super Famicom Mini - ENTER PASSWORD SCREEN

### ISSUE THREAD

**Issue by m1nhx** [ClusterM/hakchi2#912]
Hey guys,

I managed to complete this on my SNES Mini fine and all happy, this time round tried to do the same on my Super Famicom mini and I can only get pass the install module and flash custom Kernel !! once done the mini power light stays on even though I switch it off ?

When I try and boot it up it shows "ENTER PASSWORD" after several buttons press shows "ACCESS DENIED"

So I thought ok maybe I shouldn't use the same folder for both machines - so I started again flash factory kernel back and all was working again with the mini.  renamed hackhi2 folder and ran the webinstaller .. all good - dumped kernel again (success), didn't install any modules this time and just hit flash custom kernel (again stated it was a success), hooked up to TV and again get the warning issue "ENTER PASSWORD" not sure what to do - maybe should have used the uninstall module component - but I'm thinking if I've flashed the factory kernel than all modules would be uninstalled automatically ... any help with this is much appreciated...

*UPDATE*
it looks exactly like Hardcore scripting -- password protection from the mod guide - the strange thing is I've never enabled this feature!!

https://github.com/ClusterM/hakchi2/wiki/Modifications-and-modules-guide

**Comment by Drakonas** [comment]
Umm... do you have anybody else in your family that could have set up the password? This can't exactly happen by accident, unless your kernel dump was downloaded from the internet and they set a password on it.

You can try uninstalling the password module from the modules menu in Hakchi.

**Comment by m1nhx** [comment]
Thx uninstalling the password mod did the trick!
