### ISSUE TITLE
[request] Implement the CRT Filter from the NES Mini on the SNES Mini...

### ISSUE THREAD

**Issue by SkyDude79** [ClusterM/hakchi2#916]
Would this be possible? I and many others think the NES Mini CRT Filter is better and more "genuine" than the new one for the SNES. But it is more advanced and most likely more heavy on the CPU, so perhaps it would generate slow-down issues for SNES games? Could be the reason why they changed it to a simpler one perhaps... Would love to have the possibility to swap to that tho.

Thanks for an amazing hack!

Cheers,

SkyDude

**Comment by rhester72** [comment]
Not really possible - the NESCE "wobble" filter is part of the emulator binary itself, not a filter/shader.

The reason for the "simpler" shader on Canoe is twofold - first, it's a horsepower issue, and second, Nintendo wisely decided to mask that problem by claiming that by the time of the SNES, most people had moved on to composite hookups and thus the signal was 'cleaner' and the NESCE filter would look more "dirty" than the system did in real life.  Either way...there's no way to bring it to the SNESCE.

**Comment by SkyDude79** [comment]
Too bad... But thanks for a good answer. :)
