### ISSUE TITLE
Is Kirby Dream Land 3 now working with Canoe?

### ISSUE THREAD

**Issue by efgamer** [ClusterM/hakchi2#917]
I was readding some games and I realized that the suggestion to use a 3rd party emulator (which is Retroarch) is gone for good when Kirby Dream Land 3 is added. Does it mean that now it is compatible with Canoe?

I'm using 2.21d version and haven't updated to the last version of Hakchi2. The message actually has gone automatically. Does Hakchi2 check if a game is compatible or not with Canoe online?

I've played the first 2 stages and I haven't got any issues so far, also the transparency and SRAM seems to be working now BTW.

**Comment by Drakonas** [comment]
Change the preset ID to A210 (ctrl+alt+e) to fix trasparency issues.
