### ISSUE TITLE
Can't load more than 24 rooms???

### ISSUE THREAD

**Issue by daveDGAZ** [ClusterM/hakchi2#918]
I successfully hacked my SNES classic last night and it was easy enough for me to do it so thanks ClusterM!
I loaded a few ROMs and 2/3 worked great, (one would not open, no biggie), but when.i downloaded more ROMs I tried to add them but I can only get to 24 max, what's the deal #pleasehelp

**Comment by Drakonas** [comment]
What game console are the roms from? The SNES Classic only has about 240MB free space to add games but that space is also used by the saves.

**Comment by daveDGAZ** [comment]
Snes

**Comment by Drakonas** [comment]
are you adding the roms after extracting them, or are you just adding the games as is?

**Comment by daveDGAZ** [comment]
As is

**Comment by Drakonas** [comment]
I would advise extracting the files you downloaded with software like winrar and see if there is more than one file in them. You should only see one file inside each compressed archive. If there is, you probably downloaded a GoodSet pack for the game. We advise against using those roms, and instead using No-Intro roms. The file names can be an indicator of what pack you downloaded. For example, Earthworm Jim (USA) is No-Intro (what you want), and Earthworm Jim (U) [!] is a Good Set rom.

**Comment by daveDGAZ** [comment]
Where do you suggest getting ROMs from?

**Comment by Drakonas** [comment]
Google. You won't get help from us for that, as it's illegal to download them.

**Comment by daveDGAZ** [comment]
Ok, so I'll unzip the files tonight and try again, thanks allot

**Comment by daveDGAZ** [comment]
How do I get winwar?

**Comment by Drakonas** [comment]
https://www.rarlab.com/download.htm It has a free version that is basically an infinite demo mode... it will warn you to buy it every time you start it after so many days, but only when you open a file with it. It won't nag you otherwise. Solid software, and a good company.

**Comment by Drakonas** [comment]
@daveDGAZ did this ever get resolved?

**Comment by daveDGAZ** [comment]
Yeah, turns out I was downloading virus filled ROMs that almost killed my
laptop. Took me a couple days to repair it, now I'm getting ROMs from
another source and it's all working well, thanks
