### ISSUE TITLE
Stubborn NESC will not mod!

### ISSUE THREAD

**Issue by Teoc99** [ClusterM/hakchi2#92]
My NESC refuses to mod!

I have tried hakchi 2.11 several times. Dumped the kernel, and re-flashed with custom. 30 games per page. I have no issues modding other NESC's. But this one particular NESC will not mod!! 

Help me out please. What do I need to do to get the extra games on this stubborn system?

**Comment by warlockv2** [comment]
more detail is needed,  have you been able to dump the kernel/upload new one, have you tried uploading a few games instead of alot etc.

**Comment by Teoc99** [comment]
Hi Warlockv2, Thanks for responding! I am not sure what you mean by upload a new kernel. How would I do that? 
Normally I just dump the kernel, and flash the custom, and it works with no issues on other NESC's. Just not this one. I will try to upload fewer games and report back instead of loading 655 games.

**Comment by Teoc99** [comment]
I have tried using a fresh hackhi install of 2.11 and simply removed one nes game from the 30, with no luck. I have also followed the instructions below with no luck. Hakchi will finish successfully, but when I turn the NESC on the TV, the arrow remains on bubble bobble as if nothing changed. 

1: unzip the hakchi2 file to a new hakchi2 folder
2: open that hakchi2.exe
3: add the games to the list that you want added
4: download the covers
5: change any of the setting that you want ex: controller reset, autofire, etc
6: hook up the nes to the computer
7: turn the nes classics power on
8: after about 1 minute, turn the nes classic off
9: press the "synchronize selected games with the nes mini" button
10: follow the prompts

**Comment by baconcow** [comment]
You need to hold the reset button down, while powering on the system, in step #7.

**Comment by Teoc99** [comment]
Thank you baconcow. Still no luck modding with a fresh folder, and going through those instructions while holding down reset during power up in step 7.

**Comment by baconcow** [comment]
Well, I would suggest waiting for 2.12 to release (which should be soon) and then give it another try. Perhaps, I will write up detailed instructions, with images.

**Comment by Teoc99** [comment]
Thanks for your help. I've modded about 15 other NESC's. I wonder what makes this particular NESC so unresponsive to Hakchi, or what I might be doing incorrectly.

**Comment by baconcow** [comment]
Have you been able to flash the original dumped kernel back on the system and then giving it a retry?

**Comment by Teoc99** [comment]
Just to be clear, the "original kernel" is defined as the first dumped kernel from a brand new NESC, correct? If that is the case, that kernel has been deleted. When I extract a new folder, it begins with no dump folder, and then after I add games and cover art, the kernel is dumped and a dump folder is created. 

Not sure what you mean by options reset in the config.ini. Wouldn't the config.ini be reset when a new folder is extracted?

**Comment by SupahDave** [comment]
I had some problems before like you are experiencing and I've figured out how to get Hakchi to work flawlessly every time. Instead of powering the unit on BEFORE starting the flash process, I leave the unit off until I start the process in Hakchi. The program will bring up a window telling you to turn the unit on and that is when I hold reset and turn the power on. Works 100% of the time...

**Comment by Teoc99** [comment]
SupahDave, thanks for responding. However, that doesn't work for me either.

**Comment by Teoc99** [comment]
Baconcow, 
I managed to get someone else's original kernel, flashed it, and tried again, but still no luck at all!

**Comment by ClusterM** [comment]
It's hard to help without UART output. Do you tried version 2.12?
