### ISSUE TITLE
NES Classic Mini success with hakchi, not with SNES Classic Mini

### ISSUE THREAD

**Issue by Whiteiswong** [ClusterM/hakchi2#920]
I successfully got hakchi2 to work with my NES Classic Mini using v2.17d.  I do remember that it was an adventure getting the program to recognize my NES Classic Mini but I did accomplish that.

I downloaded v2.21e to go with my SNES Classic Mini.  However, after way more trials and tribulations I can't get the program to recognize the SNES.  I can get the driver installation program to at least acknowledge that the system is connected but that's about it.

![capture](https://user-images.githubusercontent.com/33039728/31910127-1fd38c3c-b802-11e7-92a7-4fb2a1801943.PNG)

I tried to install the driver from here.  I rebooted (Windows 7) and selected "Disable Driver Verification Enforcement." I tried multiple different USB cables.  I tried turning the system on without holding Reset.  The Device Manager even states the "USB Device" is working properly and even shows the driver.  

However, hakchi never recognizes it as being connected.  Any ideas?

On a side note, I still have the v2.17d program for the NES.  How do I make the v2.21e recognize all that was done already?

Thanks in advance!

**Comment by Drakonas** [comment]
Are you using a 3.0 or newer port? Try using a 2.0 port or using an older port or different PC if you have to.

**Comment by Whiteiswong** [comment]
Wow, so simple.  Yes, I changed to the USB on the other side which should be 2.0 and all worked like a charm.  Thank you Drakonas!
