### ISSUE TITLE
Where can I find the NTSC patch for Ufouria: The Saga?

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#924]
The music plays slower (like 50Hz) when loading the ROM via an emulator or the NESC and I want it to be fast, like in the Virtual Console version. Where can I download an NTSC patch, if one exists?

**Comment by Drakonas** [comment]
Why don't you search google or ask on a discord channel. This issue tracker is for submitting problems with the Hakchi code, not asking for personal help.
