### ISSUE TITLE
BS Zelda not working (C7 error)

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#925]
I cannot get BS Zelda (Both the 3rd and 4th Quests) to work. When I launch them, I get nothing but a black screen and if I hit reset, a C7 error comes up.

**Comment by Drakonas** [comment]
BS Zelda will not work with canoe. It is also reported not working with ClusterM's Retroarch cores yet. Give it time. It may work with the upcoming SNES9x 1.54.1 core, if you feel courageous in installing that directly from the github source. But it is quite slow in emulating most things.

**Comment by 03bgood** [comment]
Just used the RetroArch add-on and I no longer get a C7 error and the game boots fine.

**Comment by Drakonas** [comment]
good to know thanks.
