### ISSUE TITLE
How do I get Terranigma to work on the SNES Classic?

### ISSUE THREAD

**Issue by 03bgood** [ClusterM/hakchi2#926]
I have a NTSC SNES Classic and running Terranigma forces the message "This game pak is not designed for your Super Famicom or Super NES" and I have no idea how to bypass this! It even does it to me on SNES9X on my PC as well. None of the NTSC patches seem to work and I still get that message. This is bullshit!

**Comment by Shoothimnow** [comment]
So if this is a problem on the PC, it sounds like your ROM is bad... and not technically an issue with Hakchi2 (which you are on the issues board for Hakchi2 to let Cluster know what he in specific needs to fix).

I would look on Reddit for a solution to this, as this doesn't sound like an issue with Hakchi2 in specific.
