### ISSUE TITLE
Original games have choppy sound can barely hear it anymore

### ISSUE THREAD

**Issue by cerealofmana** [ClusterM/hakchi2#927]
After adding new games the original do not play sound properly anymore. The added games however do not have any problems. I've tried messing with the audio settings with no success. Are there any other things I can try before I mess it up.

**Comment by Drakonas** [comment]
#This may be related to my submitted issue  #921, which I have confirmed.

**Comment by Drakonas** [comment]
This has been fixed with 2.21f released today.
