### ISSUE TITLE
Adding .NES games not working

### ISSUE THREAD

**Issue by XGoldenboyX** [ClusterM/hakchi2#928]
HI all,
I have this issue where I add .NES games to my list. It does install and show the NES games thumbnails with my SNES ones.

Once I start the .NES game it loads to a Black screen and then goes back to the SNES Mini games menu.

What am I doing wrong ?

thank you

**Comment by Drakonas** [comment]
Have you installed an NES retroarch module as well as retroarch? you can't run NES games on an SNES classic when it doesn't have the software to run it.

**Comment by XGoldenboyX** [comment]
Thanks , just found out as well.

excelent !

**Comment by Drakonas** [comment]
Glad to hear. Please reopen if the problem happens again.
