### ISSUE TITLE
Unable to create suspend points #SNES Mini

### ISSUE THREAD

**Issue by lpossamai** [ClusterM/hakchi2#929]
When I want to save a game (Suspend Point), I press the "RESET" button and then I press "DOWN" on the controller. 

How-to save a game: http://en-americas-support.nintendo.com/app/answers/detail/a_id/27241/~/how-to-save-game-progress-%5Bsuper-nes-classic-edition%5D

However my SNES Mini freezes. I cannot do anything else and I need to take the power out and plugin again. When doing it, it tells me there is a "C8" error and I should contact support.nintendo.com.

I have hacked my SNES Mini using the new official hakchi2: https://github.com/ClusterM/hakchi2/releases

Before doing it, when I had my original games, I was able to save the progress of a game by following the steps that I mentioned above.

Note that this issue happens with any of the 62 installed games I have; which some of them are:

Aladdin,
D-Force,
Donkey Kong country 2,
Donkey Kong country 3,
Donkey Kong country,
F-Zero, 
Mega Man X2, 
etc.

hakchi2 version: 2.21e
Windows version: Windows 10 PRO 64 bits

Is there anything else I should do? Is anyone else having the same issue?

Thanks,
Lucas

**Comment by lpossamai** [comment]
**UPDATE 1:**

The "C8" error actually happens when I shut the SNES MINI down. Not when trying to create a suspend point.

For the suspend point it just freezes and I need to shut it down.


**UPDATE 2:**

NAND-C (for debugging) available for download here: https://drive.google.com/open?id=0B9VRju-W-e4nOHBZRUNPdFNiVzQ

I've used hakchi2.21e_debug to get the debug log: [debuglog.txt](https://github.com/ClusterM/hakchi2/files/1410325/debuglog.txt)

What I've done to get that debuglog.txt:

1. Downloaded hakchi2.21e_debug
2. Installed mod snes9x2010 + retroarch (https://github.com/ClusterM/retroarch-clover/releases)
3. Removed all the ROMS
4. Only uploaded ONE ROM
5. Played the game for 5 minutes
6. Pressed the "RESET" button
7. Pressed the "DOWN" button on the controlled to go to the Suspended point
8. SNES MINI freezes
9. Shutdown snes mini, close hakchi2.21e_debug.

I've taken all the games out, installed mod SNES9x2010 + retroarch, and uploaded only one ROM to test. Then I played the game for 5 minutes and pressed the 

**UPDATE 3:**

The "C8" error has been fixed; the cause was too many games (+60) on the screen. Found the solution here: https://www.reddit.com/r/miniSNES/comments/7562pc/modding_the_snes_classic_with_hakchi2_faq/

**Comment by Drakonas** [comment]
@lpossamai you're supposed to create a suspend point by pressing Select and down on the controller.... not reset and down.

**Comment by lpossamai** [comment]
@Drakonas that doesn't work. When I had the original games, I was able to save by pressing Reset + DOWN, like mentioned here: http://en-americas-support.nintendo.com/app/answers/detail/a_id/27241/~/how-to-save-game-progress-%5Bsuper-nes-classic-edition%5D

Please re-open this ticket.

**Comment by Drakonas** [comment]
That doesn't work on Hakchi I believe.... @lpossamai Hakchi uses down + select on the controller (hold it for a second or two), as it is easier, and I believe that down plus reset will only work with original games on og kernel anyways. Because of the way Hakchi has to load games, I believe the idea was scrapped.

**Comment by Drakonas** [comment]
If you want to reopen this you can, but it needs to be listed as a feature request.. and perhaps Cluster can find a way to add it in the future.

**Comment by lpossamai** [comment]
@Drakonas Is there any tutorial/how-to for saving games (creating suspended points) once they are hacked using Hakchi? If so can you please send me the link and I'll try it again?

**Comment by Drakonas** [comment]
@lpossamai Hold down and select on the controller while a game is loaded..... I do it all the time. If it gives you an error you need to uninstall hakchi, flash og kernel, factory reset your SNES Classic (erases all saves as well as residual files from bad hakchi installs) and install custom kernel again.

**Comment by lpossamai** [comment]
I'll try that once I get home and will update this ticket with findings.

**Comment by lpossamai** [comment]
@Drakonas by pressing DOWN+SELECT for a second or two, it takes me to the main page and I can see the little icon blow the game as a Suspended Point. How can I save it tough? When pressing down again SNES freezes.

**Comment by Drakonas** [comment]
I see....... @lpossamai I would advise uninstalling hakchi from the hakchi menu, then flashing OG kernel (making sure no md5 checksum errors occur), then go to the SNES Classic main menu and perform a factory reset (WILL DELETE ALL SAVE FILES, backup any you need with the savestate manager before uninstalling hakchi if you have any..), then flash custom kernel again. My guess is you have residual files from older/bad hakchi installs that need to be cleaned and may be causing your issue..

**Comment by lpossamai** [comment]
@Drakonas that worked!!! I can now save the games... Thanks!
