### ISSUE TITLE
[NESC] All works perfectly except all NES games show no color

### ISSUE THREAD

**Issue by thesk8rguitarist** [ClusterM/hakchi2#930]
Finally got my NESC modded just fine. GBA, GBC, SNES, Genesis works fine. All NES games including all original 30 are in Grayscale only. I did not issue a global command line argument for this and followed all proper instructions.

This specific console has been giving me a lot of grief about modding it. I kept getting MD5 Checksum immediately followed by Invalid kernel size in Hakchi 2.20 and 2.21. It wasn't until I used the web installer that it finally dumped the custom kernel. Ever since then, all NES games are in Grayscale. Anybody know what I need to do?

Restoring to complete factory reset allows original games to be played in color again.

**Comment by Drakonas** [comment]
@thesk8rguitarist if you're getting invalid checksum errors then your original kernel dump is not original, but dumped from a modified NESC. You need to find a clean dump of an un-hakchi'd kernel from a non-modded NESC, and place it in the dump folder. The dump is used to create the custom kernel as well as when installing mods. If that is already modified and it tries to modify it again it will surely end in a broken kernel.

**Comment by thesk8rguitarist** [comment]
I will see if this helps. I just started from scratch on this console again (uninstalled all Hakchi). I dumped custom kernel using the web installer, booted and all original games were there and in color. Added one game and rebooted, all fine and in color. Added the GB/GBC mod with no extra games, booted and all original games were missing and the one extra NES game was grayscale. Uninstalled the GB/GBC mod, rebooted and all original games showed back up, but now all games in grayscale again. 

Going off to find a virgin dump and try yet again. Will report back.

**Comment by thesk8rguitarist** [comment]
Writing out all my steps here:
Uninstalled Hakchi and flashed original kernel that I had
Reset NESC back to full factory default via system menu
trashed all dump folders and former kernels
Reboot brand new factory default NESC and dump the kernel (just to have that one as well). Kernel dumped, but got this error "Kernel dumped but the MD5 checksum is unknown: 4da4a80f20ace080312ea01d7c685d5e. Do you want to continue? Clicked yes. 
Moved console Kernel (A) to desktop and replaced with kernel found [here](https://www.reddit.com/r/nesclassicmods/comments/5rb99p/i_think_i_bricked_my_neshelp/dd65r9y/) I'll call it Kernel B.
Flashed custom kernel (using B). Encountered exact same checksum error as before (With downloaded Kernel B). Custom Kernel completed flashing.
Installed one NES game, all is good. Color and originals present
Install gambatte for GB/GBC, then load in one game (Super Mario Bros Deluxe). and now I  get C7 error to reboot.
Installed SNES9x, Genesis, and GBA mods with one game for each (Aladdin, Aladdin, Advance Wars respectively). Genesis and SNES give me C7 error, GBA reboots to home w/o error.
NES games still present and all in color with no problems. but now all other mods not working.

I have to laugh a little (or I'd go crazy) because I'm literally in the opposite scenario I started in.

**Comment by Drakonas** [comment]
... You need to obtain a kernel from the internet that is untouched. dumping a kernel from your nesc that is already hacked will just bring you back to a broken kernel. Find one online and place it in the dump folder, like I said.

**Comment by Drakonas** [comment]
Have you had any luck with this @thesk8rguitarist ?

**Comment by thesk8rguitarist** [comment]
I haven't. I wasn't able to find a virgin dump that day, and haven't had a chance to get back to it. I'll likely tackle it again in the morning and report back once I find a dump.

**Comment by thesk8rguitarist** [comment]
I finally fixed this issue. I realized that I needed to create a completely new folder to mod a different console. Set up a new folder, with it's own Hakchi 2 zip, and everything worked out great.
