### ISSUE TITLE
Dragon Ball Z Hyper Dimension on SNES MINI is not working :( 

### ISSUE THREAD

**Issue by M1loScorpius** [ClusterM/hakchi2#932]
Hello everyone Is there any way to run this game on SNES mini with the latest HACKCHI 2 update ? 
regards !

**Comment by JeffSeverino** [comment]
Please, check the compatibility spreadsheet before asking this. It is constantly being updated by users and some of the solutions reach there first hand. https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/edit#gid=2014317767 
There are much more important issues for Cluster and Madmonkey to check than ROM compatibility.

**Comment by Drakonas** [comment]
This game is unsupported by Canoe as per the compatibility list above. Use Retroarch instead.
