### ISSUE TITLE
Cannot Flash Kernal / Sync Games. Already did both once.

### ISSUE THREAD

**Issue by Megelith** [ClusterM/hakchi2#934]
I already was able to use hakchi2 once when it was first released for my SNES. Now every time I try it does not find the SNES mini. I have tried just using the power switch to sync and also reflashing the custom kernal and using the reset switch. Neither find the SNES mini. I have tried multiple USB ports on 2 different desktops and also on my laptop. None of them can find it. I have tried using the program Zadig to install generic drivers and it fails to install them which gives the message FAILED (Resource already exists). I'm not sure where to go from here.

**Comment by Drakonas** [comment]
If you update hakchi in the same folder it is probably looking for an NES mini as the old version did not know between the two and it saves it in the config as NES mini. You should backup your dump, games_snes, user_mods folders and erase everything else (including config!!!) DO NOT DELETE DUMP folder, it contains your og kernel dump!

**Comment by Megelith** [comment]
I extracted the latest version of Hakchi to a new folder. I copied the folders you mentioned to it as well. I still can't get hackhi to find my snes mini. I am using the cable that came with it but I have also tried a spare I have. I am selecting the US/Europe Snes when it prompts which is what I own. I'm not sure if this affects anything but in Device Manger it labels the SNES mini Unknown USB Device (Device Descriptor Request Failed).

**Comment by Drakonas** [comment]
you need to try a different port, possibly on the back of the PC. Or try a different PC altogether.

**Comment by Megelith** [comment]
Okay I tried the ports on the back of my PC. They did not change anything. I tried the other ports on my laptop which also did not change anything. Then I tried the ports on the back of my newest PC and it gets stuck in a loop of the USB connecting and disconnecting. 

Edit: I figured out that the disconnecting was my fault. I changed the usb port power settings and it no longer disconnects and reconnects. However no matter the port/pc hackchi2 still does not detect my snes mini.

**Comment by Drakonas** [comment]
Are you still using the original cable?

**Comment by Megelith** [comment]
Yes.

**Comment by Drakonas** [comment]
To be honest if these are both new PC's the ports may not be compatible. It's best to have an older 3.0 port or to have even a USB 2.0 port. Do you have any older PC's you can try? There's nothing else I can think of.

**Comment by Megelith** [comment]
The first PC i tried has 2.0 ports on the mobo which I tried. The new one has 2.0 on the case which I also tried. I'm thinking at this point something strange happened when I synced the first batch of games on to it. I haven't seen anyone else with problems mention the name in the device manager being different like mine is. The SNES still is playable so it is not bricked. Sorry I can't provide more information on whats wrong.

**Comment by Drakonas** [comment]
This may seem like a stupid question, but you are reconnecting the cable every time it tells you, correct? And you are then holding reset while you flick on the power switch, then letting go of reset ONLY if it connects? If it just sits there for more than 10 seconds, then something is wrong that I am unsure of.

**Comment by Megelith** [comment]
Correct, I am reconnecting the cable before I hold reset and I do wait for the USB to connect to the PC before turn on the power switch.

Edit: Sorry. I meant I hold reset then hit the power switch, then wait until it connects to let go of reset.

**Comment by Drakonas** [comment]
umm... I am not sure I understand correctly? You are disconnecting and reconnecting the USB, and THEN holding reset -> press power on, wait for the PC to attempting to recognize the device then let go of reset? If that doesn't work you need to try Zadig's driver solution some more. Other than that I don't know what to tell you. You might try asking on the subreddit to see if someone else is having the problem.

**Comment by ReyVGM** [comment]
In my case, I've never had to reconnect the cable when prompted. Once the cable is connected and the SNES mini is recognized (you have to first turn it on by the way), all I do is turn off the system and then do the Hold Reset instructions.

**Comment by Drakonas** [comment]
@ReyVGM if you want to risk there being residual power left in the system when you enter recovery mode, be my guest. The purpose is to have all power leave the system before entering recovery mode which may prevent any unknown issues.

EDIT: What I mean is it clears out the onboard temporary memory when you do it. For most electronics it is a good idea before flashing onto a chip. It may flash successfully and be fine if you don't do that, but it has a higher chance at affecting something negatively.

**Comment by ReyVGM** [comment]
Ah, didn't know that. Next time I'll disconnect when prompted.

**Comment by Paul330** [comment]
Did you find a solution for your problem? I am stuck with the same issue. Already used different cables and ports. When I flash the custom kernel the PC disconnects the SNESC at about 75% of progress and doesn't reconnect it. Also installed Zadig 2.3.701 for Windows 10 64bit and installed Driver WinUSB (v6.1.7600.16385) on the SNESC without any problem when the original kernel was flashed. But nothing helped. I don't know what else I could do. I synchronized games when hakchi2 2.21b came out without any problem, but since then I was not able to synchronize anymore without changing anything.

**Comment by Drakonas** [comment]
@Paul330 you probably have a corrupted install. Backup your saves while hakchi is installed (save state manager in hakchi menu), then uninstall hakchi from the hakchi menu, flash og kernel afterwards (if you get MD5 checksum errors then your og kernel dump is corrupted and you need to obtain an untouched one from an unmodified snes or from the internet), then after that perform a full factory reset from the SNES Classic main menu. THIS WILL ERASE ALL SAVES. Then you should go to your hakchi folder and delete all folders EXCEPT games_snes, user_mods, and dump (NEVER DELETE OR LOSE THE DUMP FOLDER). Then, download the latest 2.21f version released within the last hour, and extract it overwriting everything in your Hakchi directory. This will give you a fresh Hakchi setup, but your games are still there. Load up Hakchi, flash custom kernel, and reselect your games' checkmarks and resync your games.

**Comment by Drakonas** [comment]
The full factory reset is rarely needed but with corrupted installs it is the only way to clear 99% of the problematic leftover files from bad/old hakchi installs.

**Comment by Paul330** [comment]
Hi Drakonas, thx for ya feedback. What I did yesterday was:
-Flashed the og kernel from hakchi2 2.21b which was the first version I used and which should be the original kernel (size: 2670kb)
-Factory Reset via SNES Menu (I hope this is meant by full factory reset)
-Deleted all hakchi2 versions I had and made a new folder where I extracted 2.21e.
-Dumped the original kernel from the SNES and flashed the custom kernel, or wanted to flash. Had the same problem as before.
-So back to og Kernel.
What I do now:
-Factory reset
-Use a very old laptop I rarely use and install 2.21f
-Start everything from the beginning. 
What do you mean with load up Hakchi?

**Comment by Paul330** [comment]
What I found out now was, that when I flash the custom kernel and it looses the connection to the SNES I can't shut it down so the red LED stays on. When I connect it to the TV I come to the Enter Password screen. When I enter the password (Konami Code) I come to the games I flashed during my first try and which are nowhere in the hakchi2 now. So I think the custom kernel crashed somehow. I think this is the reason why it loses the connection to the SNES. I the made the works reset, but came back to the password screen and then to the custom kernel with the games I flashed.  Is this a known problem?

**Comment by Paul330** [comment]
Could this be from Retroarch? I tried to use retroarch because I had some roms that didn't run and since then the problems started.

**Comment by Paul330** [comment]
The deinstalling from the hakchi menu worked for me (I am an idiot :-)). Thank you a lot I think it works now. Will try retroarch in the afternoon.

**Comment by Paul330** [comment]
So everything is working. I have all the games I wanted on the SNESC and all of them work without any problem. Thank you again.
