### ISSUE TITLE
Original SNES games not working

### ISSUE THREAD

**Issue by jaywilda9** [ClusterM/hakchi2#935]
So after i added the games i wanted, i checked them to see if if they work properly. But when i checked the original games so came on and no issues, other's the sound was really low. And some i would just get a black screen. Any one else have this problem? Any solution or advice to fix this would be great.

**Comment by Drakonas** [comment]
Please ask this on the https://www.reddit.com/r/snesclassicmods/ subreddit. This is not a place to ask for personal help with setting up Hakchi, but for submitting bug reports.

**Comment by jaywilda9** [comment]
oh ok

**Comment by Shoothimnow** [comment]
I just went to the reddit, and there is a post saying to use https://www.reddit.com/r/miniSNESmods/ now.

**Comment by Drakonas** [comment]
That needs to be stickied. Thanks for the headsup @Shoothimnow
