### ISSUE TITLE
Axelay (SNES) graphic glitches

### ISSUE THREAD

**Issue by ReyVGM** [ClusterM/hakchi2#936]
This is very minor, but I wanted to report it just in case. But in Axelay, using canoe, on level 2 and level 6 there's a long horizontal line that appears near the bottom on the screen. In level 2 it appears near the middle of the level, and in level 6 it appears near the end of the level.

**Comment by Drakonas** [comment]
Please submit this to the compatibility list. https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/htmlview?sle=true# This issue tracker is for Hakchi bugs, not canoe bugs which are 99% Nintendo's code.

**Comment by ReyVGM** [comment]
Thanks..

Axelay is only playable by adding it with hakchi, so I thought this was the correct place to report it.

How do I edit that compatibility list? I have a google docs account, but I don't see a button or anything to edit while on that list.
