### ISSUE TITLE
How to Update Hakchi please ?

### ISSUE THREAD

**Issue by TechnoSurYoutube** [ClusterM/hakchi2#937]
Hello,

Being on Version 2.21d of Hakchi and Version 1.0c of RetroArch, I would like to know how to update to the latest version of Hakchi because I saw this in the 2.21e "Scripts autoupdate, so you don't need to reflash custrom kernel after every update."

Thank you

**Comment by Drakonas** [comment]
Please ask this on the MiniSNESMods subreddit next time. This is a bug tracker, not a personal help agent.

If you had read the FAQ, you would have had your answer: https://github.com/ClusterM/hakchi2/wiki/FAQ

**Comment by TechnoSurYoutube** [comment]
I already read the F.A.Q but I try to update hakchi2 in my console but not the Windows program because I already know how to do it!

The F.A.Q describes that the updated part programs Windows but not that of the Console!

What handling should I do?
And excuse me for putting my question in the bug tracker because I did not know or put the question!

**Comment by Drakonas** [comment]
@TechnoSurYoutube Sorry if I sounded harsh. Lots of tickets coming through lately, and it's hard to manage all of them. Uninstall Hakchi, flash OG kernel, then flash custom kernel with the update. This will not affect your save files, but you may need to resync your games.
