### ISSUE TITLE
Driver for SNES Classic

### ISSUE THREAD

**Issue by benwol94** [ClusterM/hakchi2#939]
Hi.  New to hakchi.  Question - when I installed the driver for the SNES Classic, Windows says it was installing the driver for the NES Classic.  Is that correct (because the hardware is basically identical)?  Or, was Windows supposed to use an SNES Classic-specific driver.

**Comment by xorith** [comment]
That is correct, according to my own usage. You need to tell hakchi2 what console you have though, but the driver appears to be the same. Mine worked flawlessly. :)

**Comment by Drakonas** [comment]
This is normal @benwol94 as long as you chose SNES as your platform you are fine.

Btw, please keep questions like this to the miniSNESMods subreddit or ask on the Nintendo Classics Discord server. This is bug tracker, not a question answer tracker.
