### ISSUE TITLE
Need help getting started

### ISSUE THREAD

**Issue by dogman2017** [ClusterM/hakchi2#94]
I know this may be in the wrong place, but these are concerns that I have and just need a little guidance.

OK, I have a NES classic and had someone else MOD it before I discovered this program. I currently have 760+ games on there but found a couple that I don't have and would like to add them. I don't have the ROMs that were put on my NES. Is there a way to copy what I already have on there or will I have to go and individually find each ROM and add them again. One last question, I know that you can use .nes ROMs  on there is there another format that will also work. Some of the ROM sets have a different file type.

Please help me get on the right track. I am chomping at the bit to use this but hate the fact that I will lose all the games on there. Also, if someone could guide me to a good sites for ROM I'd appreciate that.

**Comment by baconcow** [comment]
Everytime you use hakchi2, it will overrite each ROM on he system. Therefore, you will need to have all of the ROMs you want to add.

I am only aware of NES ROMs with the extension .nes. What other extensions do your NES ROMs have?

To find NES ROMs, Google is your best choice. Please see the Reddit topics as they cover all of these things in great depth.
