### ISSUE TITLE
Uninstall vs Flash Original Kernel

### ISSUE THREAD

**Issue by benwol94** [ClusterM/hakchi2#940]
What is the difference between doing an Uninstall and simply Flashing the Original Kernel?  

When I did an Uninstall, the Uninstall process ran and I was then prompted to Flash the Original Kernel.  Is that normal?

**Comment by Drakonas** [comment]
flashing an original kernel leaves the files on the main storage, uninstalling attempts to remove all mods, roms, and extra junk leftover by the hakchi install, but the initial part of the uninstall process just affects the storage, and the og kernel still needs to be flashed for the full uninstall.

For a complete factory reset, which is needed in dire cases, you can do that after the uninstall/og flash from the main menu of the snes classic. THIS WILL ERASE ALL SAVES, but it removes any extra junk from bad hakchi installs, especially the early builds. It may end up freeing some space for you if you used early builds and have yet to do that. You can backup your saves from the hakchi tool.

Btw, please keep questsions to the snesMiniMods subreddit or on the nintendo classics discord. This issue tracker is meant for submitting bugs, not questions.

**Comment by benwol94** [comment]
Thanks.  Sorry about that.  Will redirect in future.
