### ISSUE TITLE
NES Mini Classic - Cannot dump kernel

### ISSUE THREAD

**Issue by djlong37718** [ClusterM/hakchi2#941]
Hello, I have used the hackchi program to add games on my SNES mini and had no trouble. I recently managed to get a NES mini and tried to add NES games on it using hackchi. I was unable to dump the kernel. I followed the steps and received the following message "NES Mini not found, sorry" and to Press enter to exit. I was using the same computer as when I added games on my SNES and I was using the mini USB from NES box. I have since tried a new computer, bought a new NES mini cord and I am still getting the same error message. I have tried to use Zadig version 2.3 (but I am not able to find my NES mini on that or even Unknown Device. It comes up as media player) I am not overly familiar with Zadig. I have even disabled driver enforcement on my computer. Nothing is working. Any advice would be appreciated. Thanks

**Comment by ReyVGM** [comment]
For NES Mini I recommend you just download the hakchi las updated for NES Mini specifically and before it included the SNES Mini.

**Comment by gdanz** [comment]
I messed up mine today. when i try to dump the kernel, it states can't unpack ramdisk.  I have no idea what this means. I'm using the Hackchi program as well. When trying to flash custom kernel, it states sequence contains no elements.

**Comment by ReyVGM** [comment]
Move the hakchi folder to drive c.

**Comment by Drakonas** [comment]
@djlong37718 it would be best to ask this on https://www.reddit.com/r/miniSNESmods/ subreddit or GBA Temp. This issue tracker is not a personal help line with computer issues. It is for submitting bugs with Hakchi's code. Considering other people have it working fine, you will get a quicker answer at one of those places.
