### ISSUE TITLE
SNES Classic Mini - shuts down randomly

### ISSUE THREAD

**Issue by LeanderAT** [ClusterM/hakchi2#942]
After having zero problems at all my SNES Classic Mini shuts down randomly from time to time. Hakchi latest version, RetroArch, Kyland K custom cores.

https://www.youtube.com/channel/UCoRrbw6gyi4KRPGUNnVVjMQ

SNES, NES, Megadrive and MAME games. 

Played Donkey Kong, NES version...made my way up to the prinzess...then the SNES powered down...

Any ideas?

**Comment by hoderer** [comment]
Try changing your power supply. I noticed that it makes a huge difference using different cables/power adapters. I'm on the same setup as you and had random shutdowns from time to time before I changed my power cable and adapter. I know it sounds strange, but there's a good change that that is the solution. Let me know if it worked. Good luck :)

**Comment by LeanderAT** [comment]
Thanks for your reply! I use the default cable and connect it to a USB port with 5V power supply. I only had these shut downs at a friend's...not at home...however, I took everything to his place...so it shouldn't make a difference.

I stumbled over the USB port on the floor yesterday..and kicked it around. Maybe the connection is loose now. I have to test it at home.

**Comment by gingerbeardman** [comment]
I ask had this using two different USB ports (Switch dock and my projector) until I started to use an iPhone USB plug. Mini seems really picky about power source.

**Comment by Drakonas** [comment]
Yes, you need to try different power plugs, preferably one that provides more power.

**Comment by ghost** [comment]
The AC adapter supplied with the NA SNESC has these specs listed on the bottom:

Input: 100-240V~50-60 Hz0.2A
Output: 5.0V-1.5A

Not every USB adapter has the same input/output, so if you are using a different adapter (like if you are using a generic adapter with a Super Famicom), make sure it has the same ratings, otherwise you may experience power related issues.

**Comment by Drakonas** [comment]
They come with one? There wasn't one in my box o.O. Even though I picked it up from Gamestop. Lol. Thanks for the info.

**Comment by gingerbeardman** [comment]
@Drakonas only the USA version comes with AC adapter https://www.nintendo.com/super-nes-classic/

**Comment by ghost** [comment]
Sorry, “NA” stands for North American. The information I provided was from the North American SNESC’s supplied AC adapter.

**Comment by Drakonas** [comment]
Just an FYI, a legitimate AC Adapter can be picked up from the Nintendo online store: https://store.nintendo.com/ng3/us/po/browse/productDetailColorSizePicker.jsp?&productId=prod930020&categoryId=cat870406

@LeanderAT Did you ever get this working?

**Comment by LeanderAT** [comment]
I have a USB port with 5V power. Everything works at home but not at a friend's. It could be that the cable wasn't inserted properly...or moved a bit during play.

**Comment by Drakonas** [comment]
@LeanderAT there are like 20 different types of 5V adapters. The volts make no difference. It's the amps that matter. Look at maskedmanic's first post. You need one with 1.5A (1500mA) of power or close to it.

Also @gingerbeardman @maskedmaniac my version was NA version :/
