### ISSUE TITLE
Bricked My Nes Classic Help

### ISSUE THREAD

**Issue by gdanz** [ClusterM/hakchi2#943]
I messed up my NES Classic today. When i try to dump the kernel, it states can't unpack ramdisk. I have no idea what this means. I'm using the Hackchi program as well. When trying to flash custom kernel, it states sequence contains no elements. Also, when i pug the nes into the tv it keeps turning on and off. Should i just throw it in the trash?

**Comment by hoderer** [comment]
Thats the kind of post which should to a forum like GBAtemp for example. This is an issue board and your specific question/problem is more of a community one and most likely an user and not a software issue.

**Comment by gdanz** [comment]
Am I in the wrong place? I though you could ask questions here.

**Comment by ReyVGM** [comment]
Move the hakchi folder to drive c.

**Comment by gdanz** [comment]
ReyVGM, what's that mean? It's in a folder on the desktop. Really not sure where the C drive is?

**Comment by gdanz** [comment]
ReyVGM, do I move the whole folder or something? Please help.

**Comment by gdanz** [comment]
So I moved the whole folder to the C drive. Opened it and tried to dump the kernel and it's giving me a can't unpack ramdisk error.

**Comment by Drakonas** [comment]
You need to ask this on the GBA Temp forums or https://www.reddit.com/r/miniSNESmods/ subreddit. You will get quicker answers there. This is not a personal help line. This is for submitting bugs with Hakchi's code.
