### ISSUE TITLE
QSound error message after Updating to 2.21e

### ISSUE THREAD

**Issue by chaosrefugee** [ClusterM/hakchi2#944]
I updated today to the latest version of hackchi2 and was trying to add some new games including an arcade game. I included the qsound.zip in the game folder and proceeded to sync. I ended up getting an error message that says "Access to the path QSOUND.ZIP is denied" and it stopped the sync. I unselected the arcade game and still got the error message. After completely removing the game folder, the error message keeps popping up and is preventing me from altering anything at this point. The message even popped up when trying to flash the original kernel though it seemed to have gone through. I thought uninstalling and reinstalling hackchi2 from my computer might help but no dice. Any advice or suggestions?

**Comment by juanlin** [comment]
Possibly related to #665 
AV is flagging hakchi2. Fix is in that thread.

**Comment by Drakonas** [comment]
This is an antivirus problem. You need to add an exception for the qsound.zip to your antivirus.
