### ISSUE TITLE
Invalid console selected

### ISSUE THREAD

**Issue by RaZer0k** [ClusterM/hakchi2#946]
trying to flash my mini Snes:

Invalid console selected! Detected console: SNES   at com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress) in D:\Projects\C#\hakchi2\WorkerForm.cs:line 511
   at com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 544
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 281
Invalid console selected! Detected console: SNES   en com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress) en D:\Projects\C#\hakchi2\WorkerForm.cs:línea 511
   en com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() en D:\Projects\C#\hakchi2\WorkerForm.cs:línea 544
   en com.clusterrr.hakchi_gui.WorkerForm.StartThread() en D:\Projects\C#\hakchi2\WorkerForm.cs:línea 281

**Comment by Drakonas** [comment]
Have you chosen SNES Mini as your primary platform in the Settings -> Console Type.

**Comment by RaZer0k** [comment]
Yes i performance a uninstall and then a flash original kernel. But the result was a invalid dump md5.

Here is the log doing a full circle...uninstall...original...custom
[debuglog.zip](https://github.com/ClusterM/hakchi2/files/1416773/debuglog.zip)

**Comment by RaZer0k** [comment]
i check what happen... my custom kernel was installed with 2.20 but i uninstall with 2.21e so when the uninstall popup to accept install original kernel... this try to dump again... but the md5 result dont mach with the list.

Doing a menu flash original kernel with my original dump. Correct the problem. The popup from uninstall option that tell you to install original kernel. dont have to dump again.

**Comment by Drakonas** [comment]
Is the problem fixed? Do I understand correctly? If it is fixed, please close this issue.
