### ISSUE TITLE
PS2 to Wii Controller Converter Support

### ISSUE THREAD

**Issue by techhitnz** [ClusterM/hakchi2#947]
It would be awesome if you could add support for the following [PS2 to Wii Converter](https://www.aliexpress.com/item/Game-Controller-Adapter-Player-Converter-for-PS2-to-for-Wii/32813664614.html?spm=2114.search0104.3.1.ckxAtE&ws_ab_test=searchweb0_0,searchweb201602_5_10152_10065_10151_10344_10068_10345_10342_10547_10343_10340_10341_10548_10541_10084_10083_5370020_10307_10175_10060_10155_10154_10056_10055_10539_10538_10537_10312_10536_10059_10313_10314_10534_10533_100031_10103_10073_10102_5590020_5640020_10142_10107,searchweb201603_24,ppcSwitch_5&btsid=0ce370b1-5d91-4099-8b99-c62f404bae21&algo_expid=59456f80-7cba-489f-bbca-5e482bd678a4-0&algo_pvid=59456f80-7cba-489f-bbca-5e482bd678a4).  As you can see in the feedback comments, it's working on a NES Classic Mini - "Super marche nickel avec mes anciennes manettes psx/ps2 sur ma mini Nes. Wonderfull ! It works perfectly with my mini nes classic to play all the old school video games emulators via dualschock pads from psx/ps2."![utb8xheahe_4iujk43fqq6z fpxap](https://user-images.githubusercontent.com/32992068/32037782-6b9ca2ec-ba83-11e7-8293-104c48f42c42.jpg)
![utb8tbeahe_4iujk43fqq6z fpxaj](https://user-images.githubusercontent.com/32992068/32037783-6c656290-ba83-11e7-993e-db5e707fab4a.jpg)

However, it is not working on the SNES Classic Mini at all (no input detected on menu, retroarch or canoe).  I ordered two in the hopes that I can use my PS2 Arcade Sticks to play fighting games both in games supported by Canoe and Retroarch.  I know it's not a specifically a hakchi2 issue, but adding support would make my day.   I don't really want to buy another arcade stick if I can help it.  

Arcade stick used:
 - Hori Real Arcade Pro 2

Thank you.

**Comment by Shoothimnow** [comment]
I'm sure if you purchase an adapter for one of the coders, they would better be able to assist you.  But seeing that you might be the only person to have this (as they most likely don't), then the likeliness of them getting to this before anything else is waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaay low in priority.

Again, if you were to get them one, they would probably be more inclined to get it working.

**Comment by Drakonas** [comment]
This would be a limitation of the (S)NESC hardware. Hakchi can't really do anything to affect supported controllers/adapters. You just have to find an adapter that works.
