### ISSUE TITLE
Hakchi2 won't start after update

### ISSUE THREAD

**Issue by sevenx4life** [ClusterM/hakchi2#948]
I just updated hackchi2 and it won't load. This is a screenshot of the error I am getting. Any ideas of how to fix this?
![image](https://user-images.githubusercontent.com/33117097/32042434-7c53c29c-ba05-11e7-8704-6bbc3d1f859d.png)

**Comment by Drakonas** [comment]
Delete everything but the user_mods, dump (DO NOT DELETE DUMP), and games_snes folders and copy a fresh install of hakchi2 in its place. If you are using the web installer, do the same (the folders) for the AppData hakchi folder and reinstall hakchi2.

**Comment by sevenx4life** [comment]
Thank you, that did the job! :)
