### ISSUE TITLE
changing homescreen music?

### ISSUE THREAD

**Issue by Hurgnation** [ClusterM/hakchi2#949]
Hi there.

Was wondering if there's currently a way to change the music on the home screen? It might just be me, but I find it really grating when I'm playing a game and jump back to the menu to save or load a state. Ideally, I'm thinking of replacing it with something like the Super Metroid title music which I think might fit nicely, but I'm not seeing an option in hakchi2.

Has this been done before?

Cheers

**Comment by juanlin** [comment]
Check your hakchi2\user_mods\music_hack.hmod folder.

**Comment by Hurgnation** [comment]
you're awesome!
