### ISSUE TITLE
Amdstrad CPC core: How can you type/run a game?

### ISSUE THREAD

**Issue by LeanderAT** [ClusterM/hakchi2#950]
Amdstrad CPC core: How can you type/run a game?

Pressing the gamepad buttons only types Y, Z etc...how can I run a game? Do I have to use a command in the command line?

At the moment I only have /bin/cpc /usr/share/games/CLV-Z-QXHMV/romname.dsk.7z

**Comment by Drakonas** [comment]
Cluster did not make this core. You need to ask this of the person who made it. Thanks.
