### ISSUE TITLE
Google search for images fails after new update was pushed

### ISSUE THREAD

**Issue by msettlemeyer** [ClusterM/hakchi2#951]
Attempting to use the "google for images" feature now times out every time it's used.

**Comment by Drakonas** [comment]
What region are you in? What version specifically are you using? what platform? What windows version? We need more details other than "Not working".

**Comment by msettlemeyer** [comment]
US region. v2.21e was what I was using before I was pushed an update last night. I'd give you the new version, but I don't have my machine with me at the moment.

**Comment by Drakonas** [comment]
What update are you talking about? 2.21e is the latest version still...

**Comment by msettlemeyer** [comment]
Ok, maybe my machine is compromised then. Does hackchi even have the ability to push updates?

**Comment by Drakonas** [comment]
No.

**Comment by Drakonas** [comment]
Apologies, if you're using the web installer it may have auto update function. Try going to your Hakchi AppData folder, deleting everything but games_snes, config, user_mods and dump (DO NOT DELETE DUMP UNDER ANY CIRCUMSTANCES), then reinstall hakchi with the latest update manually.

**Comment by Drakonas** [comment]
What region are you in @msettlemeyer Curious now that multiple people have reported issues.

**Comment by msettlemeyer** [comment]
I'm in the US. Your suggestion seems to have fixed the problem.
