### ISSUE TITLE
Question about Autoupdate script

### ISSUE THREAD

**Issue by Pito23** [ClusterM/hakchi2#955]
The feature "Scripts autoupdate, so you don't need to reflash custrom kernel after every update." works also for the portable version?

**Comment by Drakonas** [comment]
I'm not sure what the answer to this is @ClusterM ?

**Comment by TechnoSurYoutube** [comment]
I even know what it means AutoScript update, basically if we click on Synchronize the games after keeping the files of the configuration, games and kernel, the games will be added and there will be no problem?

**Comment by Drakonas** [comment]
@TechnoSurYoutube he was curious if this exists in the portable version as well as the web installer. I was confused what the feature meant, but now I understand. Yes @Pito23 This feature was implemented in the portable version as well. Closing.

**Comment by TechnoSurYoutube** [comment]
So basically, I just need to take the files of the old version of hakchi and put them in the new version (dump, config, games ...) and I'll just have to click on Sync games for that the scripts are updated?

If I'm right, tell me yes unless it's wrong

**Comment by Drakonas** [comment]
@TechnoSurYoutube You are correct.
