### ISSUE TITLE
Access to path '7800.rom' denied

### ISSUE THREAD

**Issue by romadu** [ClusterM/hakchi2#960]
Hi,
I'm stuck with an error and now I can't revert. I tried adding 7800.rom to bios_template.hmod to enable Atari roms to work. Now I'm unable to avoid this error, even though I've removed the file, reverted to a previously copied set of hakchi2 folders, restarted, etc. This occurs even if I try to flash to original kernel, or uninstall extra modules. I don't know why hakchi2 is still looking for this file, nor how to force hakchi2 to stop looking for the file.
Thanks for your work, the SNES classic was working great until this happened.

**Comment by Drakonas** [comment]
Have you tried uninstalling Hakchi from the SNES Classic using the Uninstall function in the Hakchi menu, then flashing OG kernel?

**Comment by romadu** [comment]
Unfortunately the uninstall function has the same error. I have a new installation, downloaded as hakchi2 zip, and the error still comes up, without any of the files from the previous installation.

**Comment by romadu** [comment]
I managed to resolve the issue with the debug version of Hakchi2, restoring the original firmware. I still get the error if I use a new install of either web installer or zip version of Hakchi2 - only the debug version doesn't have the error.

**Comment by romadu** [comment]
I think this might be the issue though
https://www.youtube.com/watch?v=mGooTybpodM&t=4s

**Comment by Drakonas** [comment]
Did you move the dump folder over to the new Hakchi install? Because if you didn't you are probably getting MD5 checksum errors. If you are getting those you have corrupted your kernel on your SNES. Hakchi uses the kernel dump to create the custom kernel and every time you install a mod. If the dumped kernel is dumped from a SNES that was already modified, the dump will be broken upon trying to hack it to create the custom kernel. You need to find an unmodified OG Kernel dump on the internet. We will not help you with this here as it is copyrighted content.

**Comment by romadu** [comment]
Hi. Yes, I copied over the original dump of the kernel. In the original
version of hakchi2, regardless of what I do I get the error message. If I
try to uninstall I get the error message, if I try to uninstall or install
any hmod I get the error. That occurs with a fresh install from .zip
version of hakchi2.

Fortunately using the debug version I don’t get the error. I dumped the
modified kernel, then replaced it with the original kernel and reflashed
back to the unmodified kernel. Opening that in the original hakchi2 still
caused the error but using the debug version I was able to setup the SNES
classic again without any errors, so I’ve just used the debug version
without any issues.

I’m not sure why the error is persistent with the standard version of
hakchi2, because with the fresh install there aren’t any extra hmod and I
had put the original dumped kernel back into the SNES, yet the error kept
occurring.

Thanks very much for your help.

**Comment by Drakonas** [comment]
If you used the debug version at any point in time, if you wish to use newer versions, you need to perform a  full factory reset, else there will be files cluttering the SNES classic which are probably causing your issue. You need to backup your saves, uninstall hakchi with the debug version then flash OG kernel with it. Then, on your SNES Classic home menu, go to options and perform a factory reset (THIS WILL ERASE ALL SAVES, BACKUP WITH CUSTOM KERNEL FIRST), then switch over to the latest Hakchi program (copying dump, as well as games_snes if you wish) and then flash custom kernel with it and sync your games and re-import your saves if you need to.

**Comment by romadu** [comment]
Thank you

**Comment by Drakonas** [comment]
Respond if you have further troubles. I see no reason to keep this open when you have it working in the debug version.

**Comment by romadu** [comment]
Agreed, thank you

**Comment by cauruin** [comment]
I am having the same problem. It is being used as a debug program. I hope the problem is resolved.

**Comment by Drakonas** [comment]
@cauruin next time open a new issue instead of responding to a month+ old one.

**Comment by Drakonas** [comment]
@cauruin ask for help with this on the miniSNESmods subreddit, please.
