### ISSUE TITLE
How to remap buttons on SNES Mini for NES games?

### ISSUE THREAD

**Issue by AlexAkulov** [ClusterM/hakchi2#961]
Сейчас для NES игр на моей SNES используется крайне неудобная раскладка. Странно, почему об этом никто не пишет. Я считаю, что значительно удобнее было бы переназначить A -> B, B -> Y. В инструкции к retroarch я нашёл, что для каждой платформы можно сделать свои настройки контроллера, но я не могу понять в каких конфигах кнопки настраиваются сейчас и будет ли работать этот трюк с /opt/retropie/configs/*nes*
Может я вообще не туда копаю и есть есть более правильный и простой способ переназначить кнопки для NES?

**Comment by Drakonas** [comment]
@ClusterM You'd be best to answer this.

**Comment by ReyVGM** [comment]
This has nothing to do with Hakchi.

This is about Retroarch.

**Comment by pommmme** [comment]
I disagree that this request is about Retroarch. NES Classic firmware can dual-boot on the SNES Classic hardware. Since NES games can be played with the SNES controller without using Retroarch, it would be nice to be able to set a button config with Y-B acting as B-A, respectively.

Note that this should happen at the emulator level and not necessarily the game menu.

**Comment by ReyVGM** [comment]
Ah, you are right. Forgot about dual boot.

**Comment by AlexAkulov** [comment]
Hi, guys! I lost half day however I have found the solution! It is very easy.
I publush step by step detailed instruction:
- run any nes game
- press <kbd>select</kbd> + <kbd>start</kbd> to show RetroArch menu
- "Quick Menu" 
- "Controls"
- to change buttons you should press <kbd><</kbd> or <kbd>></kbd> on gamepad
I set these settings:
```
User 1 B :          Auto Y (btn)
User 1 Turbo B:     Auto X (btn)
User 1 A :          Auto B (btn)
User 1 Turbo A :    Auto A (btn)
```
- press "Save Game Remap File" 
Your settings will be saved into this file: `/etc/libreto/.config/retroarch/config/remaps/FCEUmm/FCEUmm.rmp` and now button mappings for NES will be loaded from this file (maybe you should select this file in "Load Remap File" item once)

**Comment by ReyVGM** [comment]
That doesn't work if you are not using retroarch.

**Comment by Drakonas** [comment]
The OP has found a solution. Closing this issue.

**Comment by thallestorchi** [comment]
i cant setup controls under quick menu > controls (only for nes emu FCEUmm) not show the buttons swap 

see my image 

https://drive.google.com/open?id=0BwHrXGubJVRQZmNZTWNGQ2UtQ3hheHJtS2s5dzRXZ3hudTZv

**on snes is fine** 

see my image

https://drive.google.com/open?id=0BwHrXGubJVRQN1JwRjctcVdZaHJ2Wlk0cGdKcXowZWFpX0ZN
