### ISSUE TITLE
flashed nandb to nandc, what to do?

### ISSUE THREAD

**Issue by petopp81** [ClusterM/hakchi2#962]
Im an idiot, I was really tired last night and by accident flashed a nandb file to the nandc on my famicom mini, everything works, but it can't be detected on my PC so i can't add any new games or reflash the correct nandc, what should i do? And yes i am a idiot and aware of it! :(

**Comment by Drakonas** [comment]
Try going back to an older version of Hakchi way before the SNES updates, and try to uninstall and restore the OG kernel from that. The older versions use a slower FEL method that may allow you to achieve success.

**Comment by madmonkey1907** [comment]
@petopp81 , did you solve it? I can help, though for now you'll have to use ext2 instead of ext4

**Comment by petopp81** [comment]
@Drakonas I tried that and it didn't work, but I will give it another go. I get a black screen when i startup but that happened a few times before i fucked up as well.

@madmonkey1907 No, not solved yet, would be great with some help but you have to consider that I am a novice so if you could explain for a total idiot like myself ;)

**Comment by madmonkey1907** [comment]
https://www.dropbox.com/s/bzgcok7sowigkk8/hakchi-gui-win32-reflash.zip?dl=0

1. dump kernel
2. unpack kernel
3. rebuild kernel
4. memboot

after that you can use hakchi2 as usual, start from scratch

**Comment by petopp81** [comment]
Thank you @madmonkey1907, will try this! One stupid question though, What is memboot?

**Comment by madmonkey1907** [comment]
there is a button called 'memboot' in the software linked. otherwise, it literary means 'boot from memory'

**Comment by Drakonas** [comment]
This should have been asked on Reddit rather than here. This is a place for reporting issues that you know what the problem is, not trying to find a solution. https://www.reddit.com/r/miniSNESmods/ Also closing as it has been 3 months without a response.
