### ISSUE TITLE
Hack Chi 2 Issue

### ISSUE THREAD

**Issue by SpideySenses** [ClusterM/hakchi2#965]
Hey Guys,

Having an issue when I have added the SNES roms into Hack Chi 2 and when I try to play it on my TV, it displays ENTER PASSWORD. Not sure why I'm getting this as I have followed the steps in You Tubes. What will fix this trouble as I can't even play my original games. 

I've Downloaded both HakChi2 and I used retroarch_with_cores. When I moved over the files from retroarch_with_cores, I had the options to add Music, Password, and the Retroarch. I chose all 3. Still i'm having issues, if anyone has a fix, please tell. 

Thanks,

**Comment by tygill** [comment]
When you selected the Password option, you told hakchi to install the password module. You need to uninstall that with hakchi, after which you shouldn't see the password prompt.

You may also want to remove the Music module, since by default it just disables the background music.

**Comment by ReyVGM** [comment]
Why the F would you add a password module if you don't want a password?

**Comment by Drakonas** [comment]
@SpideySenses needs to uninstall the password module. Since they have not responded, I am closing this issue.
