### ISSUE TITLE
SNES mini US ver. Overheating

### ISSUE THREAD

**Issue by Danteku** [ClusterM/hakchi2#966]
After running latest build, console physically heats up within 30 minutes of use.  Using original cable and charger.

**Comment by ajmi982** [comment]
Same issue here. 

Sent from my iPhone. Please pardon any spelling or grammar mistakes. 

On Oct 29, 2017, at 12:48 AM, Danteku <notifications@github.com> wrote:

After running latest build, console physically heats up within 30 minutes of use. Using original cable and charger.

**Comment by Drakonas** [comment]
How did you update to 2.21f? Did you uninstall hakchi, flash og kernel, then flash custom kernel? If so, then try backing up your saves with Hakchi, uninstalling, flashing og kernel, then performing a full factory reset from the SNES Classic menu (WILL ERASE ALL SAVES), then flashing custom kernel. If that doesn't help and you are using the original cable and power plug then this is not a Hakchi problem as you two are the only ones that claim to have an issue, so it may be a hardware fault.

**Comment by Danteku** [comment]
Fresh console, used it in stock condition for several hours with no issues.
Ran Hakchi 2 on PC.  Connected my console and flashed custom kernel to 2.21f.
All games run perfectly, and were checked with the current list running in Google docs.
Heat comes from the bottom of the system and runs rather hot.  Not sure if this is normal or not; have not found any information.
Will try to reset the system and reinstall according to steps listed above.

**Comment by THE-PBV** [comment]
why are there not BETA versies of hakchi?  The last hakchi versions are totally NOT stable at all.
en super Buggy.

people now download buggy versions as stable versions

**Comment by Drakonas** [comment]
@THE-PBV Please do not spread this kind of stuff across issues. It's obnoxious and rude.

**Comment by Frank-5** [comment]
My 2.21f did the same. Got very hot after about 20 minutes of just sitting in title screen and demos playing.  I reverted back to 2.21c and it does not run hot under same conditions.   Something in 2.21f (d,e? also/maybe haven't tested those) must be to blame.  Dunno.  I'm keeping my 2.21c setup with the uncompressed busy box patch until 2.21f gets sorted.

**Comment by Frank-5** [comment]
(I used @Draconas' method for the update)

**Comment by megaDRONe86** [comment]
@Drakonas I believe this issue is related to this one https://github.com/ClusterM/hakchi2/issues/921 because all started after removing delay from /bin/remote-exec in this commit https://github.com/ClusterM/hakchi2/commit/124f65ddedbd41a2179c8b61fd6d634fa599aaf9 and the solution provided in this commit https://github.com/ClusterM/hakchi2/commit/124f65ddedbd41a2179c8b61fd6d634fa599aaf9 with simply unpacked busybox was not good enough. I still have no idea why @ClusterM just didn't return usleep back and why this was removed? I believe removing sleep from infinite loop caused 100% CPU usage that caused overheat as a result.

**Comment by Danteku** [comment]
So.
I followed the steps from earlier.
After removing AND uninstalling all traces of extra ROMs and Hakchi kernel, I ran my system as if it were out of the box.
It was working fine, without a heating issue.
I reinstalled the latest build, 2.21f, only to run into the heating issue again.
While it doesn't seem detrimental (I haven't run it for more than two hours just in case though), it definitely is bizarre.
It seems as if the started is drawing too much power, as it emanates from the underside, near the back, close to the power port.

**Comment by megaDRONe86** [comment]
I played today more than hour on 2.21f and from my perspective tempreture of the console is normal. I updated from 2.21d just by reflashing custom kernel to fix this issue https://github.com/ClusterM/hakchi2/issues/921 .
Personally I don’t get any issues on 2.21f right now so I am planning to leave this version unless any major issues would be found or major update available.

**Comment by Nintendog** [comment]
I have the exact same issue. I installed hakchi 2.21f on a clean factory SNES Classic US.  Not took very long before it started to heat up. Would be appreciated if you could try to fix this. Thanks.

**Comment by Frank-5** [comment]
Ok.... So, after a few things learned I was able to get 2.21f installed and NO overheating problem now!!   Following instructions is the key...  Refer to @Drakonas' instructions. The key to this is to perform the full factory reset:
1) back up any save states you want to keep first
2) uninstall current version of Hackchi2
3) Flash original kernel 
4) make sure system is running correctly and not overheating.  If it is overheating with factory kernel then you might have an issue with your unit or your power source
5) Now... Go to Options / System Reset / Reset to factory settings. This. Step. Is. Necessary. 
6) Install new version of Hackchi2. (2.21f as of this post) per @Drakonas' instructions above. Make sure, like he said, to keep dump, games_snes, config, and user mods.  (I had to remove the RetroArch hmod files because RetroArch didn't install correctly.  I had to do that separately for some reason. Then extract the new hackchi2 zip into the existing Hackchi2 folder with those 4 folders you kept.   
Run Hackchi2 and flash custom kernel
You will need to re sync your games again after this

**Comment by Frank-5** [comment]
Still having issues installing RetroArch 1.0c back though, but that is a different issue I think already posted elsewhere.

**Comment by monkeyass2017** [comment]
Will @cluster be updating Hakchi to solve this problem ?

**Comment by Drakonas** [comment]
@monkeyass2017 Why don't you mention @ClusterM not cluster. Entirely different person.

**Comment by devabuse** [comment]
I am wondering if my snes mini is also affected by this. It's a bit warm to the touch at the bottom after a while (my sessions with it are usually 1 or 2 hours), but is that the same as what others are experiencing here?

**Comment by Frank-5** [comment]
My US SNES classic mini  is still running normal temperature using 2.21f and RetroArch 1.0. After many hours it is definitely not hot and barely warm anywhere on the unit.  I just picked up two more units ( !! :-) )  yesterday as gifts.  Couldn't believe the store had them sitting right there on the shelf.  I modified one of them  using 2.21f. It runs normally also.  Will test the other one later. But I dont see this issue with my units as of now.

**Comment by Frank-5** [comment]
For those of you still experiencing a heat problem after modding their SNES classic here is a discussion on Reddit on how to measure your core temperature:  https://www.reddit.com/r/miniSNESmods/comments/7ck6nn/how_to_read_temps_on_snescesfcmini_the_answer_not/
I've modded 3 units with 2.21f and RetroArch 1.0 and have had zero issues with overheating.  My reported temperatures after an hour of playing has been no greater than 56C on any of my modded SNES classics... They are all running fine.  I have not added any other cores other than those provided by @ClusterM.  And I'm not running the music hack, nor the extra space, nor the password hack either.

**Comment by will822** [comment]
New to the forum and was wondering if the overheating is a serious concern? I am still on 2.21d and have noticed that the snes runs a bit hot after about 30 minutes of usage. Seems that the latest version 2.21f also has systems running hot.

**Comment by Drakonas** [comment]
@will822 most people have found that doing a backup of your saves, performing clean uninstall (from Hakchi Kernel menu), flashing OG kernel (with no MD5 checksum errors), then performing a complete factory reset from the SNES Classic menu (THE KEY PART), then flashing custom kernel again seems to fix it.

**Comment by Frank-5** [comment]
I've been running 2.21f with RetroArch 1.0 for at least two weeks and temperature is not hot even after running several hours. I have several cores as well installed (glupen64, mgba, fba, etc) and no issues (except for no n64 saves but this is already know issue)

**Comment by Frank-5** [comment]
The key is, as stated above:  factory reset after uninstall and reflash of OG kernel.  (be sure and save any states first before uninstalling custom kernel)  Then reinstall 2.21f, RetroArch and cores then re sync games.  If still running hot then there may be HW issue.

**Comment by will822** [comment]
Thanks Drakonas and Frank-5. I did an uninstall of Hakchi and flashed the original kernel then performed a factory reset and reflashed the custom kernel with 2.21f and Retroarch 1.0c. Seems to be running great now. Played for almost 2 hours earlier and the system was barely warm.

**Comment by Frank-5** [comment]
Great!! I think like @megaDRONe86 said earlier, this heating issue may be related to issue #921 where busybox was compressed and had to be uncompressed every time sleep was called in remote-exec.  Perhaps the factory reset completely removes prior compressed files and allows the uncompressed files to be correctly used.  (My unit was getting noticeably hot with 2.21f before I followed the above procedure)  Just a thought.  Anyway 2.21f is great for me for now.  I'd like to think we could close this issue but perhaps there is still something going on that needs looking at...

**Comment by ClusterM** [comment]
I'll return usleep binary.

**Comment by sitrick2** [comment]
I followed the instructions here to return to factory settings -- uninstalled hakchi, flashed original kernel, did a factory reset in the settings -- and I'm still getting random reboots on reset. The heat seems to be minimal, it might run a touch warm after a long session but nothing that feels concerning, but after about an hour or so of playing if I hit the reset button the NES will flash the GUI for a second before rebooting, and will continue to do so until I power off and let it rest. I bought the official nintendo power supply for it (before I was using a random USB outlet plug), so I know it's getting enough power.

Is this a hardware issue? This wasn't a problem I had at all until the most recent hakchi version, and now it seems to be consistent across any settings.
