### ISSUE TITLE
Add lr-beetle-pce-fast module (=PC Engine support)

### ISSUE THREAD

**Issue by real-amano** [ClusterM/hakchi2#97]
As I saw, hakchi2 will support 2 additional NES cores: nestopia and fceumm. 

I would rather go just with one of them (a second core is shipped as the built in stock core from Nintendo anyway) and add the lr-beetle-pce-fast core instead.

You wonder why? The PC Engine features an 8bit CPU (like the NES). So it could be emulated at full 60 fps. And it has the same controller layout as the NES by default (the A button is called “Y“, otherwise it is the same). Thus all games will run  with the stock controllers. Shipping NES, Sega Master System and PC Engine support by default will cover 99 percent of the 8 bit console world. And those 8 bit systems with their limited controllers seem like the natural fit for the Mini NES.

**Comment by real-amano** [comment]
Addendum: The PC Engine (in the western world known as the “Turbografx-16“) was marketed as a 16 bit console. But at the core it was just an 8 bit system with a 16 bit CPU.

The PC Engine was known for its good Arcade ports, you could have better versions of Gradius, Gradius 2 and Life Force (=“Salamander“) and part IV of the Castlevania saga. Add to the list some arcade staple like R-Type, Out Run and Street Fighter II.

**Comment by sanjay900** [comment]
Remember, you can always just add it in yourself.
Its not hard to add in your own cores.

**Comment by sanjay900** [comment]
But anyways, cores dont take much space anyways, and so we can always just add it instead of trying to replace a core;

**Comment by real-amano** [comment]
In my eyes shipping the PC-Engine module would make more sense than even shipping a Super Nintendo module. By default you will not be able to play most Super Nintendo games because of the missing “X“, “Y“, “L“ and “R“ buttons. You can play Super Mario AllStars. But that's probably it.

**Comment by sanjay900** [comment]
Like i said, ship both. In fact, I'm actually one of those people using the SNES module, since i have a classic controller.

**Comment by ClusterM** [comment]
RetroArch mod moved to other repository: https://github.com/ClusterM/retroarch-clover

It's easy to add any module since mod is just archive with RetroArch, cores and simple scripts.

**Comment by ClusterM** [comment]
PCE added.
