### ISSUE TITLE
not so much an issues but a question

### ISSUE THREAD

**Issue by nekonall** [ClusterM/hakchi2#970]
has anyone got secret of mana 2 patched with a english title screen to work  .. ive heard of it working english trans with retroarch but when i try and patch the tilte i get errors

**Comment by Drakonas** [comment]
.. Why are you asking for something like this on a bug tracker? This is for reporting bugs with Hakchi. You are creating an issue for the built in emulator on the SNES Classic which has nothing to do with Hakchi compatibility. Ask this on the MiniSNESMods subreddit or Nintendo Classics Discord. Closing this.
