### ISSUE TITLE
SNES Classic light not turning off, no video output

### ISSUE THREAD

**Issue by chaosrefugee** [ClusterM/hakchi2#971]
After synching some new games, the SNES Classic shut off differently. The video output when off, but the light on the console stayed on until I had to unplug the usb. I figured something was up with these games, so I removed them on hackchi2 and synched again. Afterward, there was no video output from the system still. I turned it off and the light on the snes stayed on still as well. It would only turn off by removing the usb cord. I have uninstalled hackchi2 from the program and flashed the original kernel, but it still seems to do the same thing afterward.

**Comment by Drakonas** [comment]
This is not a problem with Hakchi. You might try different USB ports or different cables. If you are having problems on OG kernel though, that is not something we can fix. Try what I said or ask on the MiniSNESMods subreddit. There's not anything I can do to help here. I hope your SNES Classic doesn't have a manufacturing fault.

**Comment by Pheonix123777** [comment]
How can you close this when others have the same problem. After using Hakchi and adding some more games, the light would stay on after turning off the power. Also, I tried different cords and nothing seems to be working.

**Comment by chaosrefugee** [comment]
Pheonix123777,

I eventually found a solution for this. Follow this thread on Reddit: 

https://www.reddit.com/r/miniSNESmods/comments/7zziwh/yup_i_bricked_it/

I was able to finally fix the problem by going into ftp and deleting the “ /var/lib/clover” folder like it suggests. Worked perfectly afterward and haven’t had a problem since! Hope you can get your system working as well!
