### ISSUE TITLE
NES Mini not found - needs source code update

### ISSUE THREAD

**Issue by DavidKorpiewski** [ClusterM/hakchi2#973]
I bought a brand new NES Mini and tried to use hakchi2 on it and it always says "NES mini not found, sorry".  I looked at the source code and found that the driver (nesmini_driver.cpp) is set up to exactly match the USB Guid of "FF176DC4-7BEE-43BE-9BF2-F9299CB990BD"  However, what I'm finding is that my NES mini is showing up with a completely different GUID which is:  "88BAE032-5A81-49F0-BC3D-A4FF138216D6".  Unless there is some way to manually change a GUID, could you guys please compile in an "either or" into the code base so that it can install the driver based on this new GUID?  I've seen a few other people have this issue, and I assume its because the USB GUID is wrong.   
Another strange thing is that in my device manager its showing up as "media-player" rather than what some people said of something else that has NES in the name.

Finally I used zadig and its showing up with a different USB ID than what I saw in a video for when you install these.   According to a youtube video I should have USB ID of  1F3A EFE8.  But I'm seeing a USB ID of 10D6 11011.   

The unit seems to be completely real and came in a new unopened Nintendo box and had unopened cables.  Speaking of cables I've tried four different USB cables to make sure cables wasn't the issue.  I also used two different computers.   Both computers simply say "NES mini not found, sorry". 

Please help!
David

**Comment by Drakonas** [comment]
Looks like you may have received a bootleg NES Mini. A knockoff. Not anything I can do here to help you.

**Comment by DavidKorpiewski** [comment]
Its not one of those cheap junk rips offs that sell for like 27 dollars on ebay.  This is an official unit with an official serial number even.   
If you can't help me, then can you tell me what tools you need to compile the nesmini_driver and I will compile it myself?   It looks like it was compiled under linux with the make files, but I didn't think you could compile under linux and make a windows binary.

**Comment by Drakonas** [comment]
Different GUID means a differently manufactured device from the original release. And they have not released more NES Mini's since the original manufacturing. It means it's a different device from the originals entirely.

**Comment by Drakonas** [comment]
I don't know what is used to compile the source. Ask on the Nintendo Classics discord. This is not something to ask on a bug tracker, as it is not a bug.
