### ISSUE TITLE
[TUTORIAL] Create autoplay for added games (SNES Mini/Classic Demo).

### ISSUE THREAD

**Issue by r3tro80** [ClusterM/hakchi2#975]
Here's a tutorial for creating autoplay Classic Demo for added games.

The original guy behind this is **r9delta** from reddit.com. THANK YOU!!!!

I just added some steps to his tutorial to better tune the recordings.....

This autoplay works only if you use the original Snes Mini CANOE emulator, NOT RETROARCH.

LET'S START! 

- First you have to modify the command line of the game you want to create the autoplay.

- At the end of the command line you will find "-rollback-snapshot-period 600", change to higher value like this "-rollback-snapshot-period 30000"

- Now sincronize the games to Snes Mini to save this modify then plug your Snes Mini back to your TV.

- Turn on and launch the game. Everything you do will be recorded as "rollback". You can play or you just can let the game going in demo...

- When you decide to finish this "recording" press the RESET BUTTON and return to Snes Mini menu.

- Now save the floating suspend point to a save state then turn off your Snes Mini.

- Let's return to Hackhi2, plug the Snes mini to PC and go to the Tools/Suspend Point Manager.

- Save the Save State of your game to your pc, you will have a .clsv file.

- Open it with Winrar, then open the file inside with Winrar another time.

- You will find a "CLV-x-xxxxx" folder name, be sure the write it down, you will need it later.

- Continue to explore the dirs inside until you reach the "rollback" dir. Save it to your desktop.

- Rename the "rollback" dir to "autoplay".

- Inside you will find some files... rename the following files like this:

"0.break" to "A.inputs.state"
"0.inputs" to "A.inputs"
"1.break" to "B.inputs.state"

- You're almost done. Now put the "autoplay" dir with the renamed files inside "games_snes\CLV-x-xxxxx" (the name you found inside the save state) in the hakchi2 folder (usually it's inside your Documents folder).

- If you want you can edit back the command line of the game to original value, "600" instead of "30000".

- Now sincronize the games another time, hakchi2 will inject the games with the "autoplay" dirs too...

- Plug your Snes Mini back to your TV, be sure to remove the save state you created. 

- Don't touch anything and wait for demo mode, you have to wait until Mario pushes the game and check if the autoplay you created works.

- You're done.

**Comment by Drakonas** [comment]
This is not a place to post a tutorial. Thanks though.

**Comment by ReyVGM** [comment]
This worked perfectly. Thanks.
