### ISSUE TITLE
MAME Games

### ISSUE THREAD

**Issue by BillyDanzini500** [ClusterM/hakchi2#976]
Can someone please help me figure out how to get “Daytona USA” to work on my snes mini.  So far all of my mame games work on FBA but not Mame2003.

**Comment by BillyDanzini500** [comment]
I’m having trouble with “Street Fighter 3 3rd Generation” and “Killer Instinct 1 & 2”

**Comment by Frank-5** [comment]
There are some really good resources on Reddit to answer questions like these. Also search Google and YouTube.  Some great tutorials on setting up mame2003 for the SNES Classic. This is not the place to ask questions such as these, as this is for reporting Bugs and issues.  Someone will be along to close this issue.

**Comment by Drakonas** [comment]
This is not the place to ask for personal help. This is for reporting bugs for Hakchi. Ask this on Reddit or Discord.
