### ISSUE TITLE
Issue with folders - Control Pad does not work

### ISSUE THREAD

**Issue by ameisenmann** [ClusterM/hakchi2#977]
Hi,
I set up my SNES Mini with retroarch, snes9x and Genesis mod and custom folders. First it seemed to work but then I added another game (fig file) and controls do not react anymore in the menu.
When I disabled folder structure it worked again but when I configure any custom folder structure it won't work again. When starting my SNES PAL game with Option -retroarch I get C3 error but the game starts. Even original games get C3 error after starting but seem to play OK.
I will flash the factory kernel now.

**Comment by Drakonas** [comment]
A: Sometimes when syncing games the controls lock up. A simple reboot of the SNES fixes it.
B: It's --retroarch not -retroarch.

**Comment by ameisenmann** [comment]
I cozld only fix it by flashing factory kerlen and starting from scratch. Since then the problem did not occur anymore.
For me -retroarch works fine :)
--retroarch is more Linux style isn't it?

**Comment by gBaH0JI9I** [comment]
@ameisenmann 
You will be surprised, but inside the SNES is linux.
And "-retroarch" in command line do nothing, should be "--retroarch".
;-)

**Comment by ameisenmann** [comment]
That explains something :)
Then I am puzzled why the games that have sound issues or do not start at all magically work like a charm by adding "-retroarch". So it must do the same.
