### ISSUE TITLE
why are there not BETA versies of hakchi?

### ISSUE THREAD

**Issue by THE-PBV** [ClusterM/hakchi2#978]
why are there not BETA versies of hakchi? The last hakchi versions are totally NOT stable at all.
en super Buggy.
people now download buggy versions as stable versions
Version 2.21D is The last good working version for everybody.

**Comment by Drakonas** [comment]
I use 2.21F with no issues. Most people are just not updating properly. This is not something to ask on a bug tracker.

Uninstall Hakchi, Flash OG Kernel, (perform factory reset on Snes Classic here if you still have issues), then flash custom kernel with new version of Hakchi. This is the proper way to update with 0% chance of issues.

Also, Hakchi2 is still very much beta software for the SNES Classic anyways.... People would just get mad if Cluster wasn't providing something for people to use while he gets all the bugs fixed.
