### ISSUE TITLE
Some NES games work then after 49 black screen

### ISSUE THREAD

**Issue by joeysmallz** [ClusterM/hakchi2#979]
So all the original games work and I counted 49 NES games that worked but after the 49 just get black screen then main menu. I'm only at 18.9 mb of space so I know I'm not even close to limit. I can put 300 SNES games and they all work. Just can't figure out how the beginning 49 work then after none of the rest work. I tried it fresh from scratch but getting same issues.

**Comment by Frank-5** [comment]
You need to make sure that you don't have more than 30 or so games in each folder. If you try to have them all on the main screen then this problem will occur.  Just select original games in main screen and automatic folders for added games.

**Comment by joeysmallz** [comment]
Yeah I don't have them in the main menu and I don't have more then 30 per folder either. I'm a play with it some more to try to figure it out

**Comment by joeysmallz** [comment]
So I don't know if any one has been having the same issue but I just dropped 1090 NES roms in directly and they worked. If I download the box art then go to the games_snes and pull those folders (that way i dont have to do it every time) and add it to my desktop then try to drop it back in the games_snes that's when the games are not working or only some will and then go blank then back to home. I know on the NES I didn't have this problem.

**Comment by joeysmallz** [comment]
I forgot to mention it's only a problem for NON SNES games I cam take the SNES out and put them back and they'll work.

**Comment by Drakonas** [comment]
@joeysmallz If you have not tried this already, try backing up your saves, uninstalling hakchi from the Hakchi Kernel -> Uninstall function, flashing og kernel, THEN performing a factory reset, and then flashing custom kernel with the latest hakchi2. That usually fixes oddities like this for people, as the factory reset needs to be performed on vanilla firmware with no hakchi installed. The uninstall is needed to restore the OG kernel completely. Flashing OG kernel by itself leaves the modifications on the system but just puts OG kernel on it. The factory reset is needed to remove residual files from old/bad hakchi installs that usually cause these problems.

**Comment by Drakonas** [comment]
This should have been asked on Reddit rather than here. This is a place for reporting issues that you know what the problem is, not trying to find a solution. https://www.reddit.com/r/miniSNESmods/ Also closing as it has been 5 months without a response.
