### ISSUE TITLE
Hakchi 2 - List of Games with issues

### ISSUE THREAD

**Issue by J3llyBird** [ClusterM/hakchi2#980]
Hello,

I'm totally new to programmering and using hakchi.

So, I have carefully gone through the compabillity list and picked games I would like to play on the SNES Classic Mini. It's my first time and I haven't yet synchronized any of them until I'm sure they will work with the buillt in emulation without any issues.

Now to my problem, I've selected a couple games with issues that can be fixed with patches but I just don't know how to patch them. I tried applying a IPS as instructed with Lunar IPS which is totally new to me, it worked according to it but I still get the message from hakchi when selecting the patched file that it isn't compatible and if I want to use a 3rd party emulator instead. Is that normal?

The thing is I want to keep my SNES mini as clean and original as I can, I just want to throw in some games, no mods, retroarch or anything like that.

Here are my list of games I want that have issues according to the compabillity list:

Actraiser 2
Bust-A-Move
Kirby's Dream Land 3
Soul Blazer
Super Double Dragon
Terranigma
Mega Man X2 & X3
Illusion of Time/Gaia

Some of them don't have fixes or patches, but I'm writing them down just in case you guys know something that doesn't say on the compabillity list.

Is there a way for anyone to be really kind and send a download link to game files that already finished and ready to use? Would be appreciated not to use hex editior and other programs I never used before.

I'm grateful for the help and of course, thank you in advance!

**Comment by ReyVGM** [comment]
This site is to report issues or request features.

For those questions ask on gbatemp or the snesmini reddit (google it). I would recommend not asking where to find ROMs as most sites/forums forbid it since they are kind of illegal.

**Comment by ameisenmann** [comment]
I would really recommend trying retroarch with command line parameter --retroarch for troublemsome games because many PAL games have sound issues. As I remember most of the games you listed have sound issues with built-in emulator but they will start. With retroarch parameter they will start in snes9x. Of course you need to install this as extra module, too

**Comment by efgamer** [comment]
From the experience that I'm having testing many games on the native emulator I can tell you not to waste your time playing other than the 21 originals games using the native emulator. Go and stick with Retroarch when possible instead and you won't caught yourself noticing a glitch. 

The snes9x2010 is a good Retroarch SNES core and can emulate almost all games without any issues at all.

**Comment by Drakonas** [comment]
This is not a place to discuss rom compatibility with Nintendo's emulator. This is a place to report bugs with Hakchi itself, or request features. Closing.
