### ISSUE TITLE
Going thru folders controller disconnects (stops working)

### ISSUE THREAD

**Issue by rubiopaul02** [ClusterM/hakchi2#981]
First of all thanks for this great tool. 

My issue is when i go thru a folder and get in the controller stops working, and i have to shut down the console to make it work again. At first i was using a wireless controller, but the issue repeats with a wired controller.   The folders have each less than 30 games( i deleted games and amount per folder but still the same).  

Any ideas ?Thank you

**Comment by Drakonas** [comment]
How much free space do you have reported by Hakchi?

**Comment by rubiopaul02** [comment]
actually around 150mb, i have less than 100 games (incluiding original 21)

**Comment by electrocret** [comment]
I have also ran into this issue when I go into a folder. Disconnecting and reconnecting the controller fixes it for me.
Edit: After thinking about it, I haven't had this problem since reflashing to fix #545 . Maybe that'll fix it for you.

**Comment by Drakonas** [comment]
Are you using the power adapter and cable that came with the console? @rubiopaul02

**Comment by rubiopaul02** [comment]
yes, im using what came in the box.   Also i noticed it happen more often if i jump between games

**Comment by Drakonas** [comment]
Try backing up your saves, uninstalling Hakchi through the Kernel -> Uninstall function, then flashing OG kernel (make sure you get no MD5 checksum errors), then go to your SNES Classic main menu and perform a factory reset from the options menu, then flash custom kernel again. @rubiopaul02 There are probably leftover files from old/bad hakchi installs.

**Comment by rubiopaul02** [comment]
That seemed to do it, when i did it the first time got the md5 error, but now it work and issue hasnot appeared again.  Thanks
