### ISSUE TITLE
When selecting a BACK folder, the screen skips to the right

### ISSUE THREAD

**Issue by degstr** [ClusterM/hakchi2#983]
So I have all my games separeted in alphabetical folders. I can scroll through the games with no problem but when I get to the last icon (wich is the "back" folder), the screen skips to the right to only show that icon. It does that in every folder.

I'm not sure if I am being clear. Doesn't affect functionality at all, only annoying.

**Comment by Drakonas** [comment]
This is a limitation of the firmware of the SNES Classic. You need to have 12 or more games in a folder for it to work properly. Closing this.
