### ISSUE TITLE
Altered free space calculation... Why?

### ISSUE THREAD

**Issue by migsou82** [ClusterM/hakchi2#985]
What is the importance of having changed the calculation of memory, if after the memory is in the same limited there already was in the Mini NES?

**Comment by Drakonas** [comment]
If you're talking about there being only around 240MB free space on a fresh install of Hakchi, it is correctly being detected. The SNES Classic uses about 60MB of the space for the built in games, and those games cannot be deleted or edited. They are read only. As such, you can disable them, but you cannot remove them, so the space has been removed from the total available space.
