### ISSUE TITLE
snes compatibily

### ISSUE THREAD

**Issue by JustinForest** [ClusterM/hakchi2#989]
I've been looking through the list of games that don't work correctly or at all, and was wondering if these will be permanent issues, or will future updates to hakch2 be able to solve some of them.  There are only a few games I want to add anyways that don't work so not a huge deal, but i've been following this site for months, sinces the nes classic, and seen it constantly updated. i've been holding off on modding the snes classic, because I only want to do it once, so I'm waiting for the "definitive" version, of the software, when all the bugs, and features get ironed out.

**Comment by Arakon** [comment]
Considering this is opensource software and community-driven, there never will be such a thing as a "final" version without flaws and "everything" included.

**Comment by megaDRONe86** [comment]
I think current version 2.21f is pretty solid. I configured my SNES mini and I don’t found any issues so far.
For all not working ir buggy games you could use RetroArch emulator instead built in one.
As for the game list support by the built in emulator here it is: https://docs.google.com/spreadsheets/d/12HKfz4ZQBy6Ip5awvh8t2aV5cVswYlnsdKxn9xoIW2Y/htmlview?sle=true#

**Comment by ghost** [comment]
Some of the roms dont work because they use functionality which is simply not emulated, so it's not a Hakchi thing.

**Comment by ghost** [comment]
I have 2 consoles, one for modding constantly and one for modding with the final übermod. I am 100% certain that this console will eat dust for the rest of my life while I wait for this übermod. The moment to enjoy modding is now and it's in the nature of every modder to keep on modding and tweaking stuff constantly and continuously work towards the ultimate mod which will never be there, but it's the process of continuous optimisation that leads to the ultimate mod that is possible by community effort. So in essence everybody needs to experiment with all mod versions to iron out bugs and stuff. Just waiting for others to complete this feat is quite frankly not what community driven development is about.

**Comment by JustinForest** [comment]
I'm not a modder. I just want to have a system that my baby will be able to enjoy growing up with a similar experience I had, without having to let her into my collection and ruin my games value.

**Comment by megaDRONe86** [comment]
Justin absolutely! Me too.

**Comment by ghost** [comment]
Then, you have that system already, but maybe not with the games you played as a kid. Without the mod you have an excellently stable system from Nintendo, a consumer product.
I dont want to sound harsh btw, just want to make something clear about consumer products you pay for vs community driven OSS development

**Comment by Drakonas** [comment]
@JustinForest these compatibility issues are not patchable by Hakchi. This is a Canoe problem, which is Nintendo's design. The only thing that can be done is find patches to patch games to make them work, but lots of games like Star Ocean and Tales of Phantasia will never run on Canoe because of the required hardware emulation needed to run the game that Canoe does not have support for.
