### ISSUE TITLE
Problem with space left on snes 

### ISSUE THREAD

**Issue by ludomadinina** [ClusterM/hakchi2#990]
Hi, 
There's only 237,8MB left on my snes.
I worked on VMware fusion with OS X.
I first hack well and found 300MB with web installer hackchi2.
As I couldn't install others emulators, I used hackchi2 zip version. Then it's the beginning of many desinstall action with the two versions of hackchi.
How to find my space back please?

PS: I desinstall everything and set back to origin on the original mini snes version.

Thank you by advance

[ecran SNES hack raté.pdf](https://github.com/ClusterM/hakchi2/files/1435936/ecran.SNES.hack.rate.pdf)

**Comment by ludomadinina** [comment]
I can't even play with Europe version of games.

**Comment by Gab-75** [comment]
237,8 MB are the "normal" free storage space on an hacked SNES mini... you can increase a little the free memory available with the extra_space module (the module moves the savestates on 50 MB of unused NAND memory, but, in this case, you have "only" 50 MB for your savestates (if you like use a lot of savestate points it could be a problem).

NB: Canoe (the native emulator of SNES mini) doesn't support PAL(Europe) games, so you need to patch them (with the related NTSC patch) or, as an alternative, you can use retroarch with SNES9X2010.

**Comment by Drakonas** [comment]
This is normal @ludomadinina. The SNES Classic's built in games are non-removable and non-editable. Unchecking them just hides them. Like @Gab-75 said, the extra space mod will give you more space, but you run the risk of C8 errors running out of save space because it limits the save storage to 50MB and all the built in roms use 2 to 3MB of storage per savestate.

**Comment by ludomadinina** [comment]
Hello, 
thank you for your answers.
I was pretty sure that at the first hack, hakchi was indicating 300MB on space. My fault so. But whatever, I'm now confused. The screen shot as you see in my pdf file appears each time I hack, is it normal?
then, I did install retroarch and the other cores. But I can play only with nintendo games (snes, nes, GB, GBC, GBA) but I can't play with Europe version. for example, I put Zelda PAL version. It's read in English whereas the first time (before retroarch), it was read in French. Besides, all sega systems and arcades are not opened. Black screen for one second then nothing.  Do you have any clue?

**Comment by Drakonas** [comment]
@ludomadinina your kernel dump is corrupted. If you have deleted the Hakchi directory without backing up the dump folder, then you have lost your original kernel dump. Once a SNES or NES Classic is hacked, the kernels are modified, and cannot be restored without a dump prior to being hacked. If you delete the dump folder, Hakchi will dump the kernel from the console again but it will be a broken dump, and those errors will occur. Hakchi uses the Original dump to create the custom kernel, and if the original dump is bad it will produce errors and weird problems on your SNES Classic. Your only option is to find an untouched original dump on the internet. Do not ask for this here. It is copyrighted content.

**Comment by ludomadinina** [comment]
Ok, I think you described my problem. I did found different dumps. with different size. Do yo know the size of the original dump?

**Comment by Drakonas** [comment]
It depends on your region @ludomadinina 
                "d76c2a091ebe7b4614589fc6954653a5", // SNES Mini (EUR)
                "c2b57b550f35d64d1c6ce66f9b5180ce", // SNES Mini (EUR)
                "0f890bc78cbd9ede43b83b015ba4c022", // SNES Mini (EUR)
                "449b711238575763c6701f5958323d48", // SNES Mini (USA)
                "5296e64818bf2d1dbdc6b594f3eefd17", // SNES Mini (USA)
                "228967ab1035a347caa9c880419df487", // SNES Mini (USA)
                "632e179db63d9bcd42281f776a030c14", // Super Famicom Mini (JAP)
                "c3378edfc1b96a5268a066d5fbe12d89", // Super Famicom Mini (JAP)

Use this site to check the md5 of the img file you download: http://onlinemd5.com/ (extract the file from zips/rars/7z's first)

Any MD5 will work as long as it's from your region.

**Comment by ludomadinina** [comment]
I tested my kernel snes.img on the website onlinemd5.
File checksum indicate D76C2A091EBE7B4614589FC6954653A5 as your first proposition.
2,734,080 Bytes size file.
I think it's the original kernel.
The virtual machine installed the files in my OS X documents directory. This is the file I just checked with your help.
I will set the machine back to original and restart the hack to check if everything works now.
Thank you very much.

**Comment by Drakonas** [comment]
If that's the case try that yes. @ludomadinina Your kernel is probably just corrupted on the SNES then.

**Comment by ludomadinina** [comment]
Nothing changed. I can play SNES, GBCA and Master system files but not with French versions and Megadrive, Genesis and Neo Geo don't work.
I found a kernel on the net.
I wil try again with this version to see if I can deblock the system.
Thank you for support.

**Comment by ludomadinina** [comment]
Nevertheless, I think I found the good kernel because the message as in my first post doesn't appear anymore. now, I think I'll have to find the clue with retroarch and its different cores to play Zelda in French. Thank you, I suppose the problem is closed.

**Comment by Drakonas** [comment]
@ludomadinina did you reinstall retroarch and the required modules?

**Comment by ludomadinina** [comment]
Yes, I did. everything looks fine for nintendo and sega now. My Zelda3 is translated in French too. I just didn't find the good core for the Neo geo games i want to play. fba and csp2 don't seem to work (black screen before going back to menu).if you have any suggestion... Anyway, many thanks again!

**Comment by Drakonas** [comment]
My pleasure. Glad to be of help. Also be aware mortal kombat won't run in FBA, and CPS2 doesn't work quite yet I'm afraid. It is claimed to be working in KMFD's coreset but his coreset tends to have more bugs for people I've asked. @ludomadinina

**Comment by ludomadinina** [comment]
I spend few days to try different cores. Many little Neo geo games run (baseball, bust a move etc...) but I don't find a way to make metal slug 3 run on the machine. For all sega and nintendo platforms, everything is very fine. so cool!

**Comment by Drakonas** [comment]
@ludomadinina you need to be using the roms from the romset the emulator is made for. I'm not sure what version it is though, as @ClusterM didn't list what MAME version the FBA core is built against. I would try finding a rom from the 0.139 romset possibly, but you may have to try different ones.

**Comment by Yosh1002** [comment]
theres Only -30 Storage Left ;-;

**Comment by Yosh1002** [comment]
Fixed Already Lol
