### ISSUE TITLE
[Feature Request] Allow a user to change the output resolution

### ISSUE THREAD

**Issue by skforty** [ClusterM/hakchi2#991]
**Description:**
The mini-snes and nes classics output 720p, but it would be great for a variety of reasons if we could output in lower/higher (480p/1080p) resolutions.   

TBH, I've not read up enough on the hardware so I don't really know if this is even possible. 

**Justification:**
_480p_
For my SONY BVM and PVM CRT's I hook up all of my old systems in RGB (~15khz Horizontal Scanrate/~240p), but when I hook up these mini-systems over HDMI (via HDMI-to-SDI), it shows up super small since the BVM is displaying a 4:3 image inside of a 16:9 output on a 4:3 CRT.  Adding a 480p mode would let me full screen the mini's on my BVM.

I realize this one is more niche, because most normal consumer CRTs that had HDMI input were widescreen and therefore would look right, however, this would still be helpful for some of the other Sony 4:3 HD CRT's that had DVI or HDMI input as they would be displayed fullscreen.

_1080p_
For displaying on PC/TV monitors that have native resolutions of 1080p.  This would help with latency, and clarity, as some of these monitors don't have hardware up-scalers, and even the ones that have them can introduce unwanted latency.

Thanks!

**Comment by ghost** [comment]
Technically yes it is possible. There are a few modes available, just cat the file /etc/fb.modes to see them and do a fbset <mode> to set a specific mode.
Yet, the emulator changes the mode, so it's not quite useful. You would have to modify the emulator for this to work, or maybe I am overlooking something.

**Comment by Drakonas** [comment]
This would be possible, but I would expect that there would be lag induced from doing so, which may make games unplayable.

**Comment by djritz0** [comment]
Retroarch can set the display

**Comment by Drakonas** [comment]
not what they're talking about @djritz0 it still outputs in 720p signal to the TV.

**Comment by DanTheMan827** [comment]
I think the chip has a max resolution of 1280x800

**Comment by Drakonas** [comment]
Doing more research, this is not possible due to hardware restrictions. Get a TV that has better support for 720p signals. Closing.

**Comment by skforty** [comment]
Hey, I just wanted to chime back in and say thanks for digging into this more and doing the research.  Much appreciated!  

Just a note, I read about people having their systems get stuck in 480p, and on a hunch I assumed it was when the system was unable to get the DDC information from the display and so it would default to SD to be safe.  I was able to repro this by using an adapter to strip the DDC info out, and sure enough, the system would start in 480p.  Unfortunately, it didn't change the emulator aspect, and without a fullscreen (pixel perfect) aspect ratio, it didn't help.  It would have worked for retroarch though.

Thanks again!

**Comment by madmonkey1907** [comment]
Resolution is controlled by ini file somewhere in share. You can set 480p for game and/or menu mode separately. Neither stock menu, nor emulator support that properly. Works great in retroarch though.
