### ISSUE TITLE
[Simple feature request] Option to add a nested "Original Games" shortcut to each folder.

### ISSUE THREAD

**Issue by bslenul** [ClusterM/hakchi2#994]
Hey :)

I'd like to be able to replace original games with patched versions (restoration or translation patches for example) so that they appear in the main menu instead of the "More games" folder, it could be a simple option in hakchi2 like this: https://i.imgur.com/dn80HWg.png or just by adding "--original-folder" in the command line or something like that, idk.

I know I can do this with custom folders but I prefer the default settings for folders with the "Original games" in every folder, etc. (for those who don't know what I'm talking about, here's a comparison between custom and default folders settings: https://youtu.be/nl68q-437J0 ).

**Comment by Drakonas** [comment]
It is not possible to modify the original games on the SNES Classic, but what you are asking is already possible if you had checked the Pages/Folders structure options in the Settings menu before asking. Closing this.

**Comment by Drakonas** [comment]
To clarify, you can hide the original games and add duplicates, but the SNES Classic has locked the original roms to prevent deletion/editing.

**Comment by bslenul** [comment]
That's not what I asked, sorry I'll try to explain better:
I just want some of my games to appear on the main menu (and not in the "More games" folder).
I know you can't remove original games (but you can hide them).
The custom folders option CAN'T act like the default settings (check the video) so I don't want to use it.

So basically I just want to be able to move games on the main menu while keeping the default folders settings. It's just done by moving the game folder from /usr/share/games/00X to /usr/share/games, it's really easy, but right now you have to do it manually.

**Comment by Drakonas** [comment]
If you had tried what I said, the Pages/Folders menu can do this already. @bslenul Use Custom folder option.

**Comment by bslenul** [comment]
Sorry I didnt see the reply since it's locked, but no the custom folders CAN'T do what I wanted, for example the "Original games" shortcut, with custom you need to select "Back" multiple times depending on where you are in your folders.
But it's ok I managed to do it myself by messing with the CLV-S-0000X folders: https://www.reddit.com/r/miniSNESmods/comments/7b5v8p/quick_example_of_what_you_could_do_with_folders/

**Comment by Drakonas** [comment]
Ahhhhhhhhh. I see now. Sorry.

**Comment by bslenul** [comment]
No problem :D I explained it very poorly so I can't blame you!

But we can let this one closed, I think shortcuts for Folders Manager (see issue #998) would be more effective and modulable!

**Comment by Drakonas** [comment]
Agreed
