### ISSUE TITLE
[Simple feature request] Add an option to automatically move games to main menu without using custom folders.

### ISSUE THREAD

**Issue by bslenul** [ClusterM/hakchi2#995]
My previous post was misunderstood and closed so I'll try to explain better. I'm sorry I'm not english and sometimes it's hard for me to explain clearly what I have in mind D:

I'm just asking for a really simple feature: an option to move added games on the main menu instead of the "More games" folder.
It is simply done by moving your games from /usr/share/games/00X to /usr/share/games, BUT right now you have to do it manually and every time you sync your games :/

**So, what I'm suggesting:**
-Just add a box to tick on hakchi2 like this: https://i.imgur.com/oqdANb0.png
-or by adding a "--main-folder" command or something like that.
Once the box is ticked or the command is added, your games will be uploaded in /usr/share/games instead of /usr/share/games/00X

**Why not using custom folders instead?**
Because some of us really like the "Original games" folder inside every folder and the fact that you can switch to another folder without having to go back to the previous one.
Here's a comparison between custom and default folders to see what I mean: https://youtu.be/nl68q-437J0

**Comment by ReyVGM** [comment]
Personally I'm not very clear as to what you are asking. Your english is fine by the way, but the explanation is not clear to me.

You can have all or any new game on the 'original games' menu/folder. Just don't add any folders. But if you want folders arranged in a specific way, select the "custom folder" option in hakchi, you can organize folders anyway you want. I know the program asks if how you want the folders arranged, but after it has arranged them, you can move, delete, rename, and create as many folders as you want. You can put folders inside folders, or just have them all on the 'original games' menu.

Also, I'm not clear what you mean by custom folders vs default folders? The SNESC doesn't have folders, so I don't know what you mean by default? If you don't want a folder inside another folder, and then having to press Back 2 or 3 times to go back to the main menu, then use Pages instead of Folders.

Other than that I'm not sure what is it that you want.

**Comment by rubiopaul02** [comment]
You can change the icons folder when you are on the 'menu folder ' When the menu pops out you select the folder icon ( the bigger one on the right). It gives you option to change it.  there are several icons for the folder (nes, fammicon, snes, sega , etc and folders with letters.  
The only one i dont see how to change is the back icon.  Also you can choose your own icons

**Comment by bslenul** [comment]
By default settings I mean Pages/folders structure set to "Original games in root -> Automatic in subfolders". This way you have your original games in main menu and a "More games" folder. In the "More games" folder you have your 1st set of 30 games directly + folders with other sets of games + "Original games" folder (which brings you back to the main menu). When you select another set of games you still have the other sets folders + "Original games" folder, etc.

With the custom folders you don't have that "Original games" folder and you can't switch directly to another set of games, you have to select "Back" then chose the folder you want.

I have a patched rom of Contra III and I want it to appear on the main menu instead of the original Contra III rom. So I had to do this:
-In hakchi2 I unchecked the original Contra III rom.
-I added my patched Contra III rom for hakchi to create the .desktop, the .sfrom and the thumbnails.
-Synchronized my games.
-Go in my SNESC with FTP and past my Contra III folder in /usr/share/games.

This way I have Contra III patched on the main menu with the other original games and I can keep the "default settings" for folders. It would be just simpler with only a box to tick.

**edit:**
I'm so sorry, it's soooooooo hard for me to explain :/ In two words I just want to be able to move a game in the main menu without having to use the custom folders.

The Folders Manager would be so much better if you could create shortcut to another folder :(

**Comment by ReyVGM** [comment]
Ok, first of all, you are asking for TWO things. One is to have a specific folder structure, and the other is to have extra games on the main menu.

For the folder structure question, it appears you made a video which shows you using both? So I don't understand what more you can want? As for having Contra on the main menu, you are over complicating yourself using the ftp. Just select "Custom -show folder manager" in Settings -> Pages/folder structure. Hit "synchronize games" and the folder manager will open. In there you can drag and drop any game to the main menu or create any folder you want under any name you want and put them anywhere you want.

**Comment by bslenul** [comment]
I know that, but you can't make shortcuts to the other folders or to the main menu with the Folders Manager :( You have to select "Back" every time, then change folder. It's just less practical...

I'm going to bed, it's almost 4am here already D: Thank you anyway for trying to help me! It's my fault I can't explain my problem clearly the way I'd like to :/

**Comment by ReyVGM** [comment]
Again, from the video you posted it seems you already can do what you are asking with the folders? 

Look, enter the pages/folder structure, select the folder structure you want. Then select custom. Open the folder manager and the structure you selected will be there (you can also select the structure you want in there, btw). Now, once you're there, move the games to any folder you want, including the main menu.

Can you make a video showing what you have right now and comment exactly on what part of the video is the problem?

**Comment by bslenul** [comment]
My games are divided into 3 folders: ACT-ILL, KIR-ROC and RTY-ZOM.

This is what I have with default folder settings: https://i.imgur.com/oZf30yn.png

As you can see you can easily switch from folder to folder anywhere you are because you ALWAYS have folders for the other games and a "Original games" folder.

This is what I have with custom folders: https://i.imgur.com/7Lmv7tC.png

Here you only have your 30 games and a "Back" folder.

So let's say you're in the "RTY-ZOM" folder and want to go to the "KIR-ROC" folder, with custom folders you have to select "Back" then "KIR-ROC" (= 2 black loading screens), while with default you just have to select "KIR-ROC" :)
Same for going back to main menu, with custom if you are in "RTY-ZOM" you need to select "Back" 2 times when you just have to select "Original games" with default.

So yeah, I really like the default settings and I want to keep it, but if I keep it I can't move my patched roms on the main menu with hakchi, I have to do it manually, that's my problem.

**EDIT:**
A good alternative would be to be able to create shortcuts with the Folders Manager :)

**EDIT2**
I'm closing this and making a new feature request for shortcuts in Folders Manager, I guess it will be easier this way.
