### ISSUE TITLE
Two Compression Questions

### ISSUE THREAD

**Issue by markched** [ClusterM/hakchi2#996]
Not an issue, just two questions and I could not find the answer amongst other posts. 

First question, Now that Hakchi2 can compress files, is there any benefit to NOT compressing files? 

Second Question, Are there any specific game types (Genesis, GBA, MAME... ETC) that we should be leaving uncompressed? or should we have EVERYTHING compressed regardless of game types?

**Comment by Frank-5** [comment]
Pretty sure you need to ask this question on the many resources available such as Reddit, etc. and not here.  This is for ISSUES relating to HackChi and not a general help forum to answer questions.  
But to answer  part of your question anyway, compressing saves space but doesn't work with N64 Roms, at least in my experience with glupen64. Most All my other Roms are compressed.

**Comment by markched** [comment]
Wow. Thanks for the quick response. I figured the community would want to take care of itself rather than fan speculation on other pages.


Thank you for the help.

Mark Chedrawe
(902) 209-3910
Sent from my iPhone

On Nov 3, 2017, at 10:13 PM, Frank-5 <notifications@github.com<mailto:notifications@github.com>> wrote:


Pretty sure you need to ask this question on the many resources available such as Reddit, etc. and not here. This is for ISSUES relating to HackChi and not a general help forum to answer questions.
But to answer part of your question anyway, compressing saves space but doesn't work with N64 Roms, at least in my experience with glupen64. Most All my other Roms are compressed.

**Comment by Frank-5** [comment]
I don't think that anyone is trying to "fan speculation" on other pages. It is just easier for ClusterM to address the issues relating to HackChi without having to sort through a bunch of questions that can be handed by the community in the proper forums.  By the way, you should probably remove your personal info from your git response through email unless you want you cell phone and name on your responses.

**Comment by Frank-5** [comment]
I think @Drakonas, et. al. can help direct you to some great places to get further information on using Hackchi2.  but this area really is best used to report issues and request features.

**Comment by markched** [comment]
How do I edit a comment? I thought the email was the response? I didn't know it would filter back to here!

**Comment by markched** [comment]
Never mind. Figured it out. In the mobile version you can't but desktop webpage you can. Thanks man! Appreciate the help.

**Comment by markched** [comment]
Do you know a good forum for Q&A? I don't have anymore questions for now but it could be useful for later

**Comment by Frank-5** [comment]
No problem.  Glad to help any way I can.  I've been really having a blast with my SNES mini this past couple weeks.  Thankful to get one so quickly and not paying scalpers crazy prices.  Just walked into store and asked.     Great piece of equipment. And madmonkey, Clusterm, and all the folks that developed these tools did it just for the love of gaming.  Be nice if folks would donate more to them so development could progress faster.  

Here is a good place to ask questions and learn:  
https://www.reddit.com/r/miniSNESmods/

**Comment by Frank-5** [comment]
Another place:
https://gbatemp.net/threads/hakchi2-nes-mini-very-simple-pimp-tool.456256/page-671

**Comment by Frank-5** [comment]
And 
http://m.neogaf.com/showthread.php?t=1444556&page=100000

**Comment by Frank-5** [comment]
@markched, you should probably close this issue now

**Comment by Drakonas** [comment]
This is not the place to ask general questions. This is for reporting bugs or requesting features. Please ask on Reddit or forums next time.
