### ISSUE TITLE
Hakchi2 can not open. "Hakchi2 has stopped working"

### ISSUE THREAD

**Issue by SNESDUDEBLUE** [ClusterM/hakchi2#997]
I have never had this problem with any other program before but I simply can not open hackchi. I've tried driver updates, changing the compatibility mode, installing and reinstalling previous versions and current ones, but I can not get the program to load. Any suggestions?

**Comment by ReyVGM** [comment]
Disable your antivirus or firewall and see if it opens.

Also, right click on the .exe and select to open as administrator.

Also, are you using windows or what?

**Comment by SNESDUDEBLUE** [comment]
I am using windows 10 and have tried opening as administrator. I have tried allowing it through the firewall as well, but no luck.

**Comment by ReyVGM** [comment]
Anti virus?

**Comment by ReyVGM** [comment]
Uninstall and don't use the web installer again. Download the regular zip and extract the files anywhere you want and use the program like that.

**Comment by SNESDUDEBLUE** [comment]
Thanks for the suggestions but didn't have any luck. Disabled firewall/anti virus and all of the above. Just tried it on my laptop and it works fine, just not on my desktop. So, at least there is that.

**Comment by Drakonas** [comment]
This sounds like corruption on Windows side. A reinstall of your computer may be in order. This is something outside of the boundaries of Hakchi. Closing.
