### ISSUE TITLE
Sequence contains no elements at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)

### ISSUE THREAD

**Issue by kimllee** [ClusterM/hakchi2#999]
Hi,

I deleted portable version of hakchi 2.21f after i uploaded games in my snes mini.
I redownloaded it to add more games to the snes mini but I have the following error now when I want to synchronize the snes.

_Sequence contains no elements   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at com.clusterrr.hakchi_gui.WorkerForm.DoKernelDump(String dumpPath, Int32 maxProgress, Int32 progress) in D:\Projects\C#\hakchi2\WorkerForm.cs:line 493
   at com.clusterrr.hakchi_gui.WorkerForm.FlashKernel() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 544
   at com.clusterrr.hakchi_gui.WorkerForm.StartThread() in D:\Projects\C#\hakchi2\WorkerForm.cs:line 281_

My Hakchi folder is in C: drive.
Thank you.

**Comment by ReyVGM** [comment]
If you DELETED the original hakchi folder, then you're pretty much starting over with a new hakchi folder. That's what's probaby causing the issue.

Flash the original kernel back to the SNES, then flash the custom kernel back and it should work.

**Comment by Frank-5** [comment]
If he deleted the hackchi2 folder then he also deleted his OG kernel in the dump sub folder.  He can't flash the OG kernel back until he has his original kernel in the dump folder.  So.. Unless it still is in the trash then he will have to try and find a compatible original kernel.   Don't know why anyone would delete the dump folder unless they didn't read the 1000 warnings on not to delete the dump folder.

**Comment by Frank-5** [comment]
This is a user error and not really a hackchi issue. Although if the program would more gracefully let the person know instead of the way it did in this case that would be better.

**Comment by kimllee** [comment]
Thanks for your answers guys. I was expecting this answer... I know i did a very bad move...
Where can i find an OG snes (EU) firmware please ?

**Comment by kimllee** [comment]
Thnak you for your answers. Problem solved. I flashed the console on another computer and I hopefully kept the Hakchi folder with the OG firmware in it :D
Issue solved. I close it.
Thank you.
